### PR TITLE
Adds old 2016 security, maint tunnels and cargo sort room.

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: Added old 2016 Security + Many other map changes.
add: Old 2016 Cargo (Fills in the spot where the detective office was)
add: Old maint tunnels around security
del: Removed Old Security
tweak: Cargo airlock no longer overlapped by firelock when opened
tweak: EVA looks more like the 2016 style.
fix: Fixed missing plating under window in AI sat
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Hey guys, it's been a long journey but here it is! 2016 Sec with a modern twist. It's a bit of old mixed with a bit of new mixed with a bit of improvements. The map has been thoroughly tested and I am 100% it is ready to go. If there are any changes that need to be made, please post screenshots with the requested changes below it.

Screenshots below!!

image

image

image

image

image

image

image

image

image

image

### CODE REVIEW

**Comment by praisenarsie** [comment]
firefox_2018-01-18_22-52-40
3/4 SPIIRIIIRIRIRIRIIIIIIIIIIITE

IN ARMORY

**Comment by tortellinitony** [comment]
where is perma?

**Comment by Manly-Dwarf** [comment]
Where's perma?

**Comment by yoyobatty** [comment]
image
 Here it is.

**Comment by tortellinitony** [comment]
that's not good

**Comment by yoyobatty** [comment]
Okay, don't just tell me that it's not good, tell me what I can do to change and improve it.

**Comment by tortellinitony** [comment]
make it like the current perma

**Comment by yoyobatty** [comment]
k

**Comment by Pyko1** [comment]
Yeah this version of the sec had whole off station perma, which most of the people hated as far as i know.

**Comment by Pyko1** [comment]
also what happened to detectives office next to bridge, seeing you got one next to sec too.

**Comment by 2Dollarbill** [comment]
I think having perma on station would be great, allows for the potential of escape unlike the off-station one. Also make sure to include the gulag, if you can do those, this is a +1 for me.

**Comment by tortellinitony** [comment]
cargo fills in spot where dets office was

also did you mapmerge

**Comment by Pyko1** [comment]
cant really support this as long as its missing a proper on the station perma.

**Comment by Carbonhell** [comment]
1) needs a proper perma, can just copypaste the current one somewhere
2) conflicts

**Comment by yoyobatty** [comment]
Hey guys, I've been busy with irl normie stuff so I'm going to try to fix this asap, hopefully sometime later today.

**Comment by ghost** [comment]
i love you yoyo

**Comment by Carbonhell** [comment]
any news, @yoyobatty ?

**Comment by ghost** [comment]
stale

**Pull request closed without merging**
