### PR TITLE
[MIRROR] Add the ability to osay from the viewvar dropdown

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/32804
--------------------
Why:
sticky wanted this

### CODE REVIEW

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by ghost** [comment]
Build finished.

**Comment by JohnGinnane** [comment]
we get it you build

**Review by KayeArray — APPROVED** [review]

**Pull request merged**
