### PR TITLE
Mass Lavaland Nerfing: No Mercy Edition 2.0 THE SECONDCOMING

### PR DESCRIPTION
**Pull request by Jujumatic**
Original PR #5566

Lavaland is meant to be a tough place, yes. However I think that for the extremely high risk of death for pretty much every second that you're on there, there is a lot of inconsistence between the rewards being ok to being horrendously, hilariously bad. Plus I got fed up of the mobs in lavaland a long time ago anyway, so this should help balance out the risk/reward factor considerably. I don't want to go to lavaland to risk dying in like 5 seconds and then have to sit out the rest of the round because of it. The stuff on lavaland can be pretty cool and there's not much incentive to getting them by being gated behind so much prep time to not die instantly, so when you get some cool stuff the shuttle has already left. Not cool.

🆑 Arzion (revived by Jujumatic like, 2 years later)
tweak: Lavaland has been nerfed in multiple aspects, mostly regarding the creatures. No more "M-MUH D-DIFFICULTY!!!" for you.
balance: You can no longer transform into an inferior ashwalker when drinking the Dragon's Blood potion anymore.
tweak: The gods have realized that the blood-drunk miner is still really just a human, but still felt generous enough to reduce its health to 400 from 900, double the amount of health that a regular human has.
tweak: The nerf hammer has finally come crashing down on megafauna, reducing their health to 1500 from 2500 and damage reductions to their melee attacks (not their special abilities!) and in the case of Colossus and Hierophant, their projectile attacks too. Legion (the megafauna) had its health reduced to 550 from 800. Swarmer Beacon had its health reduced to 300 from 750.
tweak: The nerf hammer has no mercy. Regular fauna is affected too. Goliath health has been reduced to 200 from 300, along with its unique ancient variant having its health reduced to 300 from 400. Goliath damage reduced to 20 from 25. Tentacle stun reduced to 5 seconds from 10.
tweak: Legion (the mob) had its health slightly reduced to 60 from 75, while legion skull damage has been reduced to 8 from 15 (the skulls bite only). The unique variant of the Legion had its health reduced to 100 from 120. Legion's skull spawn delay has been increased, which means you should be able to fight more Legions at a time without being overwhelmed by skulls.
tweak: Watcher's health has been halved to 100 from 200. Damage reduced to 12 from 15. Magmawing health reduced to 140 from 215. Icewing health reduced to 120 from 170.
tweak: The tendrils are not safe either. Necropolis tendril health has been reduced to 175 from 250, and the rate at which fauna is spawned from the tendrils has been reduced, taking 60 seconds to spawn a creature instead of 30.
/🆑

second changelog for the little thing I did:
🆑
tweak: Lavaland staff creates lava tiles with a cooldown of 5 seconds now, down from 10 seconds.
/🆑

### CODE REVIEW

**Comment by mikolaj007** [comment]
+1
i might actually start playing miner now

**Comment by k-k-karma** [comment]
it's supposed to be hard, fuck off saltlord

**Comment by k-k-karma** [comment]
then again it'll be easier for me to powergame as miner. go ahead.

**Comment by Pringleschipman** [comment]
lowering Goliath health isn't all that necessary as they are already easy to kill. same goes for legions. however lowering their health really wont effect gameplay in any serious manner.

**Comment by mikolaj007** [comment]
alright ill +0 this for now. im gonna go learn how to fight the bastards and then decide if they need a nerf

**Comment by Jujumatic** [comment]
Updated the description with an explanation for the PR

**Comment by WarRage333** [comment]
Tentacle stun reduced to 5 seconds from 10.

this is the only thing i agree with, everything else is unneeded in my opinion.

All the bosses with their dance dance revolution mechanics are retarded tho

edit

keep collosus and heiro at 2.5k

reduce the rest.

**Comment by yoyobatty** [comment]
Lavaland really doesn't need work, also what a disgusting PR, fix it.

**Comment by Manly-Dwarf** [comment]
Lavaland is meant to be hard.
Now you want to know what's not okay? Holoparasites & Free Antag as rewards for it.

when dwarves

**Comment by biggiOS** [comment]
i generally disapprove of nerfing lavaland
if nerfing fauna, maybe colossus and hierophant but ashdrake, bubblegum and legion are fine imo

**Comment by Majick1** [comment]
Goliath: damage/stun nerfs look good, i'd probably leave the health though so they're not getting 2 shot with upgraded PKAs
Legion mob: Don't touch it, literally just get a Ripley with laser cutter and it's a no-damage kill
Watcher: Ok with it losing health to be more a glass cannon, it's already hard with it having a hitscan beam on you the instant you duck back out of cover
Tendril: The spawn delay is a good change, once you get above 5-6 mobs currently it's a neverending killfest until you get run over
Hierophant: Maybe 2000 instead of 1500, put more randomness in the attack patterns so it doesn't keep spamming the same one over and over at times

Will hold off on the others, I don't get to fight them often enough to make a judgement without playtesting

**Comment by JessHorserage** [comment]
>Tentacle stun reduced to 5 seconds from 10.

Please, take my first born.

**Comment by ghost** [comment]
@Majick1 you can use an ore box to absorb watcher boolet, then duck out to bop them

**Comment by WarRage333** [comment]
You cant since the projectile speed change, you don't even see the sprite of the beam when you aggro watchers.

**Comment by yoyobatty** [comment]
Very stale and not being discussed.

**Pull request closed without merging**
