### PR TITLE
[MIRROR] Replaces highpressure windows with plasma windows

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/29051
--------------------
closes #29048

Removes high pressure windows all together, since the same function is being performed by reinforced plasma windows

### CODE REVIEW

**Comment by tortellinitony** [comment]
our map needs changes!

**Comment by ghost** [comment]
nu supermatter sucks

**Comment by ghost** [comment]
yeah tony these map changes only affect engineering i think?
we don't have the SM so we can't replicate those changes

**Comment by ghost** [comment]
you could replace the reinforced glass between the engine area and engineering with rplasma glass. and remove high pressure windows from the code.

**Review by j-mie — APPROVED** [review]

**Comment by j-mie** [comment]
> yeah tony these map changes only affect engineering i think?
> build failed
> "undefined type: /obj/structure/window/reinforced/highpressure/fulltile"

gg

**Pull request merged**
