### PR TITLE
Killed brain death

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
balance: You now no longer suddenly and inexplicably die when hitting the brain damage cap of 200.
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Yes its tested, yes it works and no it does not runtime.

**Comment by ghost** [comment]
i'm assuming this removes 400 brain damage making the brain melt too as well right?

**Comment by GuyonBroadway** [comment]
400 brain damage can only be achieved if an admin manually sets your brain to 400, otherwise it can never go over 200.

**Comment by ghost** [comment]
👎 add messages that tell you your brain is shutting down

**Review by ghost — APPROVED** [review]
Code OK

**Comment by GuppyLaxx** [comment]
Yes please

**Comment by Manly-Dwarf** [comment]
hurry up and merge this
this shit breaks cluwnes and turns it into an instakill spell

**Comment by ghost** [comment]
+1
brain damage death as part of the trauma shit makes me want to die

**Comment by SplergeBucket** [comment]
ahyegh

**Comment by SplergeBucket** [comment]
+2

**Comment by TDcoolguy300** [comment]
Erik said the code is OK, two headmins said sure

**Pull request merged**
