### PR TITLE
Re-adds thrower circuits

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Thrower circuits are back
/:cl:

## About The Pull Request
Title.

## Why It's Good For The Game
Science nerds wanted this.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
code is ok

**Comment by TrickyDickRichard** [comment]
+1 throwing is good

**Comment by enthethan** [comment]
Queue x number of people -1'ing this because of muh science powercreep

**Comment by Manly-Dwarf** [comment]
@enthethan hi
thrower circuits were removed because they could oneshot people really easily among other things
knowing how circuitnerds are able to churn out shit in five seconds didn't really make that process better
this is a really dangerous PR

**Comment by mikolaj007** [comment]
#10697 
i am entirely aware that i was under extreme levels of salt when i made the PR, but i believe thrower needs a nerf before it can be readded.
-1

**Comment by Toxici11i** [comment]
this makes forged bullets look weak

+1

**Comment by Toxici11i** [comment]
@yoyobatty please to god though, nerf how many you can stack in a circuit, or increase their complexity.

**Comment by karmaisblackandbluepilled** [comment]
+1 but I can already see that this will end up getting circuits removed lol

**Comment by Manly-Dwarf** [comment]
this is a big fat -1 from me honestly
the thrower circuits were such bullshit, an undetectable object that instantly crit you because you got close to the guy carrying it
no thanks

**Comment by diegoxt45** [comment]
oh god please stop giving science more ways to fuck with people

**Comment by ghost** [comment]
-1, this shouldn't even need a vote.

**Comment by AnthonyJNgo** [comment]
This is really too strong. I like giving players options, and having circuits is something that differentiates us from other servers. This PR will make circuits too strong imo and lead to their eventual removal. Another -1, going to have to close this PR.

**Pull request closed without merging**
