### PR TITLE
Adds combo moves to nanosuit + bug fixes and code cleanup.

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: Nanosuit has a headstomp and powerpunch combo.
add: Nanosuit has a boot sequence and revised EMP reboot sequence.
del: Removed morphine injection from Nanosuit.
code: Nanosuit code is a bit cleaner and has been given a vip treatment for maintainability. 
/:cl:

[why]: I've added some cool abilities for the nanosuit's strength mode such as a combo head stomp (4 successful head stomps while victim is below 40 health) which explodes their head in a shower of gore. The other one is  a power punch which can be randomly triggered if you get a series of random quick punches and a normal punch together causing the wearer to get a sudden urge to punch the living shit out of their victim, sending them flying back and dealing a ton of damage. 

Another thing I've done is added a startup to the nanosuit, mainly because I thought it was sci-fi like and gave the user a bit of a delay before they could start murderboning (It's only 12 seconds approx.). I've also added some other messages for resetting the nanosuit from EMP mode, (This was actually not being triggered due to the renaming of the suit mode bitflags from a few PRs ago) and a homage to Crysis to where you hear a defib noise before getting back up.

Morphine also got removed because it was causing issues like players falling asleep and moving at normal speeds even when out of speed mode. 

Also code has had some bug checking and maintenance done.

Here is a video: https://imgur.com/G34WhRv

### CODE REVIEW

**Comment by k-k-karma** [comment]
+1, very nice

**Comment by earthmoonjune** [comment]
+1

**Comment by Eagle-Eyess** [comment]
sure +1

**Comment by yskefunky** [comment]
holy shit yoyo if you keep working like this you're literally going to end up coding your own game into the nanosuit

but ok +1

**Review by Jujumatic — APPROVED** [review]
dank-e

**Pull request merged**
