### PR TITLE
Separated chems have a 10% spawn chance

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
balance: Glow berries seperated chem trait spawn chance now 10% up from 5%
/:cl:

## About The Pull Request
It increases the likeliness this trait will spawn.

## Why It's Good For The Game
Because apparently it would almost never spawn.

### CODE REVIEW

**Review by Jujumatic — APPROVED** [review]

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
+1

**Comment by Lxtoofonea** [comment]
+1

**Comment by RafRoq** [comment]
Feelt bad when I spent 20 minutes and 100+ seeds to NOT find it

**Comment by Maroonenahmoron** [comment]
+1, fair enough if you can't upgrade seed extractor.

**Comment by earthmoonjune** [comment]
+1

**Pull request merged**
