### PR TITLE
Adds a voice of god autosurgeon to wizard's spellbook

### PR DESCRIPTION
**Pull request by Arzion5**
:cl:
add: Added a voice of god autosurgeon to wizard's spellbook.
/:cl:

Fun gimmicky item, again

### CODE REVIEW

**Review by KayeArray — APPROVED** [review]

**Comment by KayeArray** [comment]
+1

**Comment by ghost** [comment]
Sure +1

**Comment by ghost** [comment]
wait... bantz is headcoder... so is mcbaw- I CAN MERGE THIS!

**Comment by ghost** [comment]
Your Fix/Feature pull request delta is currently below zero (-1). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by PopNotes** [comment]
I mean technically headcoder but yeah

**Comment by ghost** [comment]
eat shit @HonkBot

**Comment by PopNotes** [comment]
fall off your horse @HonkBot

**Comment by KayeArray** [comment]
LOL why do we have the point system here

**Comment by GuyonBroadway** [comment]
pettion to rename it to "E-Penis size"

**Pull request merged**
