### PR TITLE
Adds Zootsuit, Elvis Jumpsuit, and Pimpstick

### PR DESCRIPTION
**Pull request by McHatters**
Porting back some small stuff from the depths of old Hippie, brought up from the depths of many rebases.

image
image

:cl: McHatters
add: Purple Zootsuit, Elvis Jumpsuit, and Pimpstick
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by Carbonhell** [comment]
Needs modularization

**Review by Carbonhell — DISMISSED** [review]
Modularization

**Comment by GuyonBroadway** [comment]
B I G P A P A

**Review by JohnGinnane — DISMISSED** [review]
Looks good to me

**Comment by Manly-Dwarf** [comment]
B I G

P A P A

**Review by JohnGinnane — APPROVED** [review]

**Comment by McHatters** [comment]
Funny enough the zootsuit was still in the code, it just wasn't being used

**Comment by ghost** [comment]
please bring this +1

**Pull request merged**
