### PR TITLE
[s] nothing to see here.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
code looks good BUTT I would make the changelog a little more cryptic.

And would hold off on merging this till halloween.

**Review by GuyonBroadway — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
Just to be clear I ain;t gonna BLOCK this till Halloween, just a recommendation if headmins agree.

**Comment by KayeArray** [comment]
how common is this event?

**Comment by ghost** [comment]
Do our floor cluwnes qdel people or not?

**Comment by KayeArray** [comment]
they either tear their limbs and organs out or cluwne them

**Comment by KayeArray** [comment]
oh **GOD**

**Pull request merged**
