### PR TITLE
[DNM] The Good, the Bad, and the Grey (Sprites Edition)

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Manly Dwarf, Yoyobatty, SatouOnBroadway/Navi.OS, Shazzzbot, Gannets, b i t e m e, other servers (CEV Eris, Goonstation and Tau Ceti)
add: Completely reworked Security
add: The Abzats Machineshotgun is back, just as you remember it!
add: Added the AK-922, a classic gun, complete with its golden variant.
add: The Syndicate Tophat, a fancy traitor item that was originally meant to be a replacement for the balloon. It's here though, so
imageadd: Security now has brand new sprites. Oy, guvna.
imageadd: Numerous nukie guns and ammo now have new sprites.
tweak: The L6 SAW now fits on your back.
/:cl:

## About The Pull Request
Pre-approved
Security overhaul and sprite update, soon to be more maps and guns and balance and stuff.

## Why It's Good For The Game
Security sucks right now and needs buffs, but also that's hard to do when riot shields exist.

Forum thread for discussion: https://forums.hippiestation.com/viewtopic.php?f=20&t=1450

Fart

The gun sprites were made by Shazbot from CEV Eris, the Golden AK was tuned up by SatouOnBroadway/Navi.OS.
Nuke Op suit sprites by b i t e m e, from Tau Ceti.
Security sprites by Gannets, from Goonstation.
All of the code that I didn't understand got passed to Yoyobatty, from Canada. I paid him in syrup.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Don't bother codechecking this I won't listen to you

**Comment by MaterialisticThings** [comment]
+1 THIS IS NEEDED

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by ExpAntique** [comment]
+1

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: dc05d74f3dd7344ebebe4697fa69108b969ace58
Pull Request: bf2f24a54b5c152fbc08a5c2e8695c945b77f196
Server: 56dffd5b15c3d0072fa3f7298fcca339487db1d5

##### Comment
Just for sprites. Also abzats.

**Comment by JessHorserage** [comment]
>changing an rng block to a flat armour boost.

Holy shit can this guy just be a fucking head god of awesome. +mexican car cleaner.

**Comment by mikolaj007** [comment]
why the fuck is this merged and why the fuck does l6 saw doesnt spawn with magazine? you broke toy guns you nigger

**Comment by Manly-Dwarf** [comment]
oh shit sorry let me go fix that

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 1a2f3cb65fa92f3586a20c50efa8ed20e257fb7b
Pull Request: bf2f24a54b5c152fbc08a5c2e8695c945b77f196
Server: 44b8fe368f82921e929f0690f17ba9738271e5db

##### Comment
Just for sprites. Also abzats.

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 1a2f3cb65fa92f3586a20c50efa8ed20e257fb7b
Pull Request: bf2f24a54b5c152fbc08a5c2e8695c945b77f196
Server: dd0298ee74c908edd73ef9fdcb12c86a9eb23c3b

##### Comment
Just for sprites. Also abzats.

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 91a4d5a438db997d704c9295343e7bf40f2e7e76
Pull Request: bf2f24a54b5c152fbc08a5c2e8695c945b77f196
Server: f76779e756f0af1d6bf287b1bcb75f58f6236a3b

##### Comment
Just for sprites. Also abzats.

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: cbba97d1e020f6e4bd96e3ea814a08c18327746a
Pull Request: bf2f24a54b5c152fbc08a5c2e8695c945b77f196
Server: 56a21609227b77d5e0dfa4544cc220f189707f6a

##### Comment
Just for sprites. Also abzats.

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 260977d467c52f5dea6e352a3a1e80be2f33c29f
Pull Request: bf2f24a54b5c152fbc08a5c2e8695c945b77f196
Server: 1f18fc6380271376dfc8b87dad10baaa830da60f

##### Comment
Just for sprites. Also abzats.

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by Manly-Dwarf** [comment]
@AnthonyJNgo why you make a million mirrors and ruin dis PR I fart on your firstborn

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 22d89f8846e9bbdd6ba2942c90bc6d0b4452c096
Pull Request: d1ea3b94776c0979b4f68f96c90023a6d2761474
Server: 370b0ae3bf5ff7039d8a659141ed35642c552b40

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by Manly-Dwarf** [comment]
I'm probably just going to fetch this, put in the rest of the sprites, and get this merged. We can do this in pieces, now that I think about it.
Testmerges are a conflict nightmare and I no longer want to deal with them.

**Comment by Manly-Dwarf** [comment]
ohhh yes very good conflicts

**Comment by lunaman22** [comment]
+1 britcop look nice

**Comment by ghost** [comment]
got pictures? am curious

**Comment by Manly-Dwarf** [comment]
heeeeeeeeeeeeelp

**Comment by Manly-Dwarf** [comment]
it's been a month and the conflicts are just increasing

**Comment by TrickyDickRichard** [comment]
u ok there bud

**Comment by Manly-Dwarf** [comment]
going to port all of this over into another PR

**Pull request closed without merging**
