### PR TITLE
You can now eat through headgear

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: You can now eat through headgear
/:cl:

### CODE REVIEW

**Comment by Majick1** [comment]
-1 sounds dumb

**Comment by yoyobatty** [comment]
@Majick1 this was a feature that has only recently got added in, traditionally you would be able to eat with headgear and masks on. I give this a +1

**Comment by Pringleschipman** [comment]
having to remove headgear to eat is annoying.

**Comment by ghost** [comment]
extremely based

**Comment by Jujumatic** [comment]
Old hippie port so I don't think input is needed

**Comment by WarRage333** [comment]
I don't remember how it worked before but you still had to take people's helms off to feed them, if it's still like that +1

**Comment by bigbluebeaker** [comment]
+1

**Comment by mikolaj007** [comment]
-1

**Comment by Manly-Dwarf** [comment]
mikolaj must be put to death
+1

**Comment by ghost** [comment]
Eh fuck it

**Review by ghost — APPROVED** [review]

**Comment by cris5311** [comment]
finaly, that was one of my fav features

**Pull request merged**
