### PR TITLE
Slime will now eat a little faster

### PR DESCRIPTION
**Pull request by xTrainx**
[Changelogs]: # slime will now eat faster

🆑 xTrainx
tweak: slime will now eat faster, and get more nutrition
/🆑

[why]: # got some request from user to make xenobio a bit more viable since round here tends to laST 30 minutes, so slime will now eat faster, reducing downtime when farming slimes

last one got closed by mistake

### CODE REVIEW

**Comment by ghost** [comment]
+1 yea

**Comment by WarRage333** [comment]
Xenobio is too slow, we need more xenobio buffs

**Comment by JohnGinnane** [comment]
@Chnkr @HippieStation/head need input otherwise I'm gonna merge

**Comment by dreamcrab** [comment]
+9

**Review by ghost — APPROVED** [review]

**Pull request merged**
