### PR TITLE
Don't panic!

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt
add: Nanotrasen would like to remind everyone to NOT PANIC, with the addition of new posters!
/:cl:

Sprite by @Crysoskis

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
HELP ME WE HAVE A PLASMA LEAK
THERE'S A FUCKING CHANGELING RUNNING AROUND MAULING PEOPLE WITH TENDRILS LONGER THAN ME
SOME CRAZY ATMOS GUY IS FIGHTING IT WITH FIRE BUT HE JUST BURNED DOWN ALL OF MEDICAL
SECURITY IS TRAPPED IN THEIR DEPARTMENT BY SOME CRAZY AI WHO IS HURLING INSULTS AND FLOODING PLASMA
AND SOME CMO IS SPREADING AN INCREDIBLY LETHAL VIRUS
WE HAVE NO HARDSUITS LEFT

**Comment by Eagle-Eyess** [comment]
what is this

**Comment by ghost** [comment]
A HHGTTG reference

**Comment by GuyonBroadway** [comment]
Yes but where is your towel?

**Comment by ghost** [comment]
Here it is... I happened to lose my washcloth, soap, tin of biscuits, flask, compass, map, ball of string, gnat spray, wet-weather gear, and space suit... Could you lend me yours?

**Review by yoyobatty — APPROVED** [review]

**Comment by ghost** [comment]
@yoyobatty merge?

**Pull request merged**
