### PR TITLE
Dwarf Sprint 1 finishing touches: I do it for free edition

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Carbonhell, Manly Dwarf
add: Dwarves are now a playable species. As of now, they require alcohol and CO2 to survive.
add: Everything is subject to change. Dwarves as a project is not even close to being done.
add: Carbonhell did literally everything. Dwarf did nothing and is just piggybacking.
admin: Admins, since you're inevitably going to get ahelps about players wanting to play as a Dwarf for the round, you make someone a Dwarf by going to Change Outfit and selecting Dwarf. Don't use Species unless you want to kill them. Don't overdo it unless you enjoy having players adminhelp over suffocation.
server: Please reconsider fullstripping Dwarves unless you want to give our admins a headache. They need that Co2 tank.
/:cl:

## About The Pull Request
does things, makes dwarves playable and testable, adds a jumpsuit that actually works for them, makes them look better.

## Why It's Good For The Game
review code

yes

### CODE REVIEW

**Comment by TrickyDickRichard** [comment]
yes ver good

**Review by ghost — APPROVED** [review]
Code looks good.

**Comment by cb583** [comment]
i like

**Comment by carlopault** [comment]
ok

**Comment by wheezl** [comment]
+1

**Comment by waterwater1212** [comment]
Urist is in a constant state of internal rage, after being rained on in 152.

**Comment by Maroonenahmoron** [comment]
Breathe easy, little men.

+1

**Pull request merged**
