### PR TITLE
Miami Vice Officers Clothing

### PR DESCRIPTION
**Pull request by DeityLink**
Commission for Wheezl, Sprites by BurntDevil (and fixed by myself)

miamivice
miamivice2
miamivice3

The first Tubbs jacket can have its buttons toggled with alt-click.

The pendant spawns in Tubbs' pocket and can be worn as a uniform accessory.

Each round a random uniform and suit will be picked for both officers. Their suits will match according to the visuals above (vertically)

:cl:
* add: Added new clothing for the vice officers.

### CODE REVIEW

**Comment by wheezl** [comment]
+3

**Comment by carlopault** [comment]
yes

**Comment by byandaccount** [comment]
+1 good idea and cool outfits.

**Comment by MrEpicSax** [comment]
+1, purps vote is worth 2 so this meets the minimum requirements.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
