### PR TITLE
[READY] Basically, Instant Explosions 2: The Search For More Money: E…

### PR DESCRIPTION
**Pull request by yoyobatty**
Ported the epic instant explosions PR from /tg/station: https://github.com/tgstation/tgstation/pull/50594

byong-extools is built on the server, it's tested and I'm not seeing any issues.

I also tried out tesla, it significantly speeds up the performance of it's explosions and prevents delayed queued explosions.

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
i am salty you made the spaceballs joke before I could

**Comment by karmaisblackandbluepilled** [comment]
oh yeah +3
how tf did you not kill yourself trying to make a 70 file thing work

**Comment by MrEpicSax** [comment]
+1 speedmerge

**Comment by KingTerrytheTerrible** [comment]
oh man this is gonna be fun to abuse5

**Comment by yoyobatty** [comment]
> oh man this is gonna be fun to abuse5

Edgy...

**Review by Neotwr — APPROVED** [review]

**Pull request merged**
