### PR TITLE
[MIRROR] Fixes projectiles not hitting people resting, a bit of refactoring of how projectile target collision is done

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42241
----------------------------
Everything now uses can_hit_target, some checks were moved around, living canpass moved to living movement, and check_bitfield() define helper now has extra () wrapping for peace of mind.

### CODE REVIEW

**Comment by ghost** [comment]
Salty sec mad they can't spam down a hallway and hit everything at once so they made this PR

smh literally shaking and crying

**Comment by Manly-Dwarf** [comment]
LITERALLY SHAKING

**Comment by xTrainx** [comment]
gonna be honest, i feel it would be more realistic as it is, you wouldn't usually be able to hit someone prone unless you were aiming specifically for them, and you wouldnt be able to hit anyone farther with the same bullet

**Comment by ghost** [comment]
@xTrainx @Manly-Dwarf let this PR through tho, it fixes code so the resting thing can be made into a feature and not a glitch

**Review by yoyobatty — APPROVED** [review]

**Comment by RafRoq** [comment]
That's a shit pr

**Pull request merged**
