### PR TITLE
[MIRROR] New .357 Revolver Sprites

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43438
----------------------------

## About The Pull Request
New .357 revolver sprites! In response to #43405 
Left is the syndicate's 357 revolver, middle is the russian revolver, and right is the gold revolver that only admins can spawn anyway.

I can swap the left and middle sprites around if you guys prefer.

## Why It's Good For The Game

Prettier sprites are always good!

## Changelog
:cl: WJohnston
imageadd: New .357 revolver sprites.
/:cl:

### CODE REVIEW

**Comment by yoyobatty** [comment]
Thoughts?

**Comment by mikolaj007** [comment]
Look nice

**Comment by ghost** [comment]
no soul

**Comment by Manly-Dwarf** [comment]
Meh. Would like to see the det's revolver updated with that style, too.

**Comment by yobob591** [comment]
+1 Old one looks like a black brick with a wood handle slapped on

**Review by Jujumatic — DISMISSED** [review]

**Comment by Jujumatic** [comment]
the dmi didn't get updated...

**Comment by Manly-Dwarf** [comment]
yeah it seems like this new mirror bot has some issues with updating sprites or somethin

**Comment by ghost** [comment]
absolutely disgusting

**Comment by mikolaj007** [comment]
mirror bot didnt mirror sprites

**Comment by Majick1** [comment]
+1 shiny

**Comment by ExpAntique** [comment]
+1

**Review by yoyobatty — APPROVED** [review]

**Comment by bigbluebeaker** [comment]
+1

**Pull request merged**
