### PR TITLE
[MIRROR] Techwebs update: Protolathe/Circuit imprinters combined into techfabs!

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/36055
--------------------
Doing my little update piece by piece because I'm lazy and because storage PR is going to conflict everything ever.

Techfabs do not link to RND consoles, and have their own interface for producing things.
RND production machinery code refactored.
Techwebs have categories views instead of just a goddamn design list.
Old machinery will be kept in, as some places will keep them. Read: Engineering, robotics, etc.

- [x] Map this stuff in
- [x] Bugtest

:cl:
experimental: Protolathes and circuit imprinters combined/changed to techfabs. All departments can now print related circuit boards. Engineering and science will keep their lathe/imprinter design by default at roundstart because they have specialized labs for those.
/:cl:

### CODE REVIEW

**Comment by JohnGinnane** [comment]
ffffffffffffffuck sake

image

**Comment by JohnGinnane** [comment]
Okay there's no actual conflicts so I'll force merge as soon as Travis says so

**Comment by JohnGinnane** [comment]
image

**Comment by JohnGinnane** [comment]
you're tearing me apart travis

**Comment by JohnGinnane** [comment]
i don't know how to fix this

The runtimestation.dmm doesn't have this line but it should and Travis seems to have it

**Comment by Pyko1** [comment]
fixed

**Comment by JohnGinnane** [comment]
how

**Comment by Pyko1** [comment]
just overwrote the map with proper TG version and fixed conflicts.

**Comment by JohnGinnane** [comment]
damn, I tried same and didn't work for me, oh well, thanks for that!

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
