### PR TITLE
[MIRROR] Modularises vending machines

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/36508
--------------------
Each machine now has its own file, which includes it's refill cannister for easy maintenance

:cl: JohnGinnane
refactor: Vending machines now have their own files which includes their refill cannister. The machines themselves are unchanged
/:cl:

It seems like it might be easier to add and maintain vending machines if they're in their own files. The vending functionality hasn't moved. I thought about using datums to represent the products, contraband, and premium items for each machine, and then using those datums to automatically calculate their refill charges (default 1/3, but can be adjusted). Let me know if you think this is a good idea.

I did a quick run around boxstation and made sure all the vending machines still have their stuff, and they do!

### CODE REVIEW

**Comment by JohnGinnane** [comment]
\>tg merged my pr
later virgins

**Review by JohnGinnane — DISMISSED** [review]

**Comment by JohnGinnane** [comment]
We actually need to integrate this because we have our own fiels

**Comment by JohnGinnane** [comment]
I have something special in mind for this, to make our life easier in terms of adding our own products, but let's atomise that for later. For now I've made our modularised code look similar to tg code

**Comment by ghost** [comment]
goodbye john
it was good knowing you
you must go on to bigger and better things

**Comment by JohnGinnane** [comment]
what

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
