### PR TITLE
[MIRROR] Update TGS API to 3.2.0.2

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34276
--------------------

### CODE REVIEW

**Comment by Chnkr** [comment]
fuck you @tortellinitony

**Comment by praisenarsie** [comment]
don't let tony merge upstream prs ever again

**Comment by tortellinitony** [comment]
nothing's gonna break don't worry

**Comment by praisenarsie** [comment]
i swear if i find the data folder missing i am gonna fucking pwn you

**Pull request merged**
