### PR TITLE
Unfucks the Syndicate Shuttle turrets

### PR DESCRIPTION
**Pull request by NautilusViper**
## Changelog
:cl: NautilusViper
tweak: Syndicate Infiltrator turrets no longer wallbang and stunlock everybody who comes into range.
/:cl:

## About The Pull Request

The Infiltrator was using heavy caliber penetrator rounds for some godawful reason and this makes that not so.
## Why It's Good For The Game

Literally everybody fucking hated this, the infiltrator became infinitely more dangerous than the actual nukies themselves, especially when parked at escapes so anybody who runs towards departures gets gatted to death from something they could never see coming.

### CODE REVIEW

**Comment by Majick1** [comment]
+1 finally

**Comment by mikolaj007** [comment]
+1

**Comment by Manly-Dwarf** [comment]
thanks

**Review by ghost — APPROVED** [review]
Headmin and designer approved so merging this asap

**Pull request merged**
