### PR TITLE
Adds a hippiefied version of Deltastation lovingly named "Delturd"

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
add: Added a Hippiefied version of Deltastation with a pool, lcasschem labs, slightly improved medbay and maint chem lab. Filled with all sorts of maint tunnels and hidden fun things for your grey-tiding projects. 
/:cl:

[why]: Deltastation has lots of maint tunnels and stuff that hippie players could make fun shit out of and some variety would be very nice with regards to maps.

hippieifed the sign.

image

The pool and gym 

image

Maint chem tucked snugly away.

image

The Lcasschem lab, replaces what was a Science break room and bathroom area, we don;t pay you to take breaks we pay you to do dangerous scientific experiments!

image

Improved cloning lab, has an extra cloning mahcine and some mannitol/mutadone pills. 

image

Improved cryo, adds a third cryo tube.

image

Mining has the free ripley, this was surprisingly the best spot to stick it do it didn't block anything or cover any pipes.

image

Delturd has both the supermatter AND a sing/tesla setup. MORE POWER!!

image

Deltruds bar has a nice wooden flooring.

image

And Delturds combined clown/mime office has the golden bike horn, I COULD add a separate clown/mime office but I think little differences between maps are fun. Plus the clown/mime fighting over the golden bike horn sounds funny to me.

image

Delta is full of fun maint shit and things to do, its big sure but about 30 players would just about staff it good.

### CODE REVIEW

**Comment by ghost** [comment]
"Delturd" heh.

**Comment by GuyonBroadway** [comment]
It was either going to be Delturd or Deltard

**Comment by GuyonBroadway** [comment]
Oh turns out delta has TWO ss13 signs, lemmie fix that.

I also forgot the clowns bike horn case.

**Comment by ghost** [comment]
what engine does delta use?

**Comment by GuyonBroadway** [comment]
Ah the supermatter, BUT there is an area for the tesla/sing, i forgot to jsut add the generator.


Damnit my cat walks in and I get distracted.

**Comment by GuyonBroadway** [comment]
Ok now this is ready/

**Comment by ghost** [comment]
https://github.com/HippieStation/HippieStation/pull/3522

**Comment by j-mie** [comment]
yeah, I really don't like the idea of maintaining 3 different maps considering we already don't fucking maintain box.

**Comment by GuyonBroadway** [comment]
we've actually kept box mostly up to date, we're just missing one thing and that's the advanced docking console for the nukie shuttle which I need to get on and add.

**Comment by DinduStuffin** [comment]
Yeah but do consider the potential for this map for nations, Jamie.
It wouldn't hurt to have a hippiefied delta map for events like that.

**Comment by ghost** [comment]
@GuyonBroadway actually i added the advanced nukie console

**Comment by PopNotes** [comment]
Delta is a good map, I approve. My only complaint is that by all means it should be Deltard instead of Delturd.

**Comment by ghost** [comment]
we can just add it and if it becomes unmaintainable, just disable it

**Comment by 2Dollarbill** [comment]
+1 from me. Let's try new things.

**Comment by bardofrage** [comment]
Eh, why not, +1.

**Comment by GuyonBroadway** [comment]
build this

**Review by ghost — APPROVED** [review]

**Pull request merged**
