### PR TITLE
Cures cancer

### PR DESCRIPTION
**Pull request by ghost**
:cl:
del: Cancer borgs have been deleted
/:cl:

### CODE REVIEW

**Comment by SireTurret** [comment]
-1.

**Comment by DaydreamPuppeh** [comment]
-1

**Comment by diegoxt45** [comment]
-1, mad?

**Comment by TrickyDickRichard** [comment]
-1 ur mad

**Comment by private-tristan** [comment]
-1

**Comment by Manly-Dwarf** [comment]
+1
pepehell

**Comment by karmaisblackandbluepilled** [comment]
-1 hoes mad

**Comment by mikolaj007** [comment]
+1, clown borgs are the fucking menace of refusing to follow laws, doing stupid shit because "pranks"
play a clown

edit: I edited your message to save your github account, they do have profanity rules.

**Comment by sagattyy** [comment]
-1

**Comment by mkikt4743** [comment]
-1, can't believe I pied you so hard you went full /tg/ coder mode.

**Comment by AnthonyJNgo** [comment]
-1 for obvious reasons

**Comment by ghost** [comment]
-1 begone

**Pull request closed without merging**
