### PR TITLE
Adds back a surplus chance to the holoparasite kit

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
balance: forget what tg said, Holoparasites ARE in the surplus kit!
/:cl:

[why]: Fuck tg balance

### CODE REVIEW

**Comment by PopNotes** [comment]
AW FUCK YEAH THIS IS THE SHIT

**Review by KayeArray — APPROVED** [review]

**Comment by KayeArray** [comment]
+1

**Comment by ghost** [comment]
yeah boy
+1

**Comment by KayeArray** [comment]
has input, merging

**Pull request merged**
