### PR TITLE
makes catbeasts clumsy I think idk how to code

### PR DESCRIPTION
**Pull request by SireTurret**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Turret
add: Catbeasts are now clumsy, thus making them unable to use anything useful.
/:cl:

## About The Pull Request

yes

## Why It's Good For The Game

catbeast yes

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
this is a web edit PR that you didn't test, did you

**Review by ghost — DISMISSED** [review]
webedit but code is consistent so I'ma approve

**Comment by SireTurret** [comment]
> this is a web edit PR that you didn't test, did you

i'll check it when im not lazy as fuck

**Comment by SireTurret** [comment]
does not work help

**Comment by SireTurret** [comment]
oh no

**Comment by ghost** [comment]
@SireTurret hold your horses, I'm debugging this right now

**Comment by ghost** [comment]
@SireTurret your original code works, did the thing where I handcuffed myself. Revert the recent push.

**Comment by SireTurret** [comment]
should work now

**Comment by ghost** [comment]
@SireTurret never mind, I did this for you. Why did you think it didn't work?

**Comment by SireTurret** [comment]
> @SireTurret never mind, I did this for you. Why did you think it didn't work?

@HideAndSeekLOGIC so I launched my own private server, made myself into a catbeast, tried to activate a flashbang but it didn't explode in my hand like it usually does

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
+1 this was supposed to be done right after the pacifism change.

**Comment by ghost** [comment]
going to merge

**Pull request merged**
