### PR TITLE
overhauls probabilities - more slings less blob

### PR DESCRIPTION
**Pull request by ghost**
less blob more slings (and some more revs)

:cl: Thefastfoodguy
experiment: overhauls probabilities - hopefully more slings less blob
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
only making this pr so the server/repo configs dont get out of sync

**Comment by PopNotes** [comment]
hurrr nurrr y not remove blob durrr

**Comment by ghost** [comment]
because some people say "bleb is good rts gamemode hurrdurr"

**Comment by tortellinitony** [comment]
This isn't the config that is on the server. Ask a host

**Comment by ghost** [comment]
@tortellinitony I asked @McBawbaggings, didn't he say "make a PR"?

**Comment by ghost** [comment]
i said that i should manually update the repo with what we have live

**Comment by ghost** [comment]
oh, ok

**Comment by ghost** [comment]
will this config be considered to be the server's config?

**Comment by ghost** [comment]
yeah, so players actually see what we run live and that players can propose gamemode changes proper

**Pull request closed without merging**
