### PR TITLE
Multiple IPC screen support

### PR DESCRIPTION
**Pull request by tortellinitony**
Removed moth wings as they will be added by the /tg/ PR and added support for more than one IPC screen instead.

### CODE REVIEW

**Comment by Pyko1** [comment]
many of these changes will just make the moth mirror conflict again since they are fixed already there.

**Comment by Pyko1** [comment]
+1 even tho should really separate the moth changes from this

**Comment by tortellinitony** [comment]
OK I figured we could merge this and then merge the moth fixes but I'll fix the conflicts if that is gonna g et merged first

**Comment by JohnGinnane** [comment]
@tortellinitony is this ready?

**Comment by ghost** [comment]
IS IT

**Comment by Carbonhell** [comment]
IS IT???

**Comment by JohnGinnane** [comment]
image

**Comment by Carbonhell** [comment]
seems to be stale/dead, closing?

**Comment by tortellinitony** [comment]
yes its ready

**Comment by JohnGinnane** [comment]
image

**Review by JohnGinnane — APPROVED** [review]

**Comment by JohnGinnane** [comment]
Going to merge this now that big PR is merged

**Pull request merged**
