### PR TITLE
minor clean up on squeaks components for clown gear

### PR DESCRIPTION
**Pull request by ghost**
falsely told john he had to delete the squeak component when he didn't
so here's some minor clean up

### CODE REVIEW

**Comment by ghost** [comment]
wait actually on merging this

**Comment by ghost** [comment]
please wait for this https://github.com/tgstation/tgstation/pull/39847 to be merged/denied before touching this PR

**Comment by ghost** [comment]
ree

**Comment by ghost** [comment]
required code has been merged for this to work

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
