### PR TITLE
scout now costs a reasonable ammount

### PR DESCRIPTION
**Pull request by diegoxt45**
🆑
balance: scout now costs 1 point
/🆑
it shouldn't cost 3 points, fucking steamport

i also forgot to upload this on the actual hippie master branch, bruh moment

### CODE REVIEW

**Comment by DON-KARMA** [comment]
Scout is actually the most overpowered ability because you can eat a fugu gland while in scout mode and be invincible but able to attack from anywhere on the map.

**Comment by diegoxt45** [comment]
> Scout is actually the most overpowered ability because you can eat a fugu gland while in scout mode and be invincible but able to attack from anywhere on the map.

well, that's not intended is it...

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by Manly-Dwarf** [comment]
fix fugu gland
then +1

**Comment by ghost** [comment]
Once there is an issue thing for the fugu gland, +1.

**Comment by AnthonyJNgo** [comment]
+1 after fugu gland is addressed.

**Review by AnthonyJNgo — APPROVED** [review]
One digit code change, it's fine. Merge this AFTER fugu gland gets merged.

**Pull request merged**
