### PR TITLE
Manual Reverts

### PR DESCRIPTION
**Pull request by ghost**
Reverts #12761 and #11992

### CODE REVIEW

**Comment by ghost** [comment]
Not sure what's wrong with this one. If someone can point out what's pissing off travis, I'll fix it.

**Comment by karmaisblackandbluepilled** [comment]
code\modules\mob\living\living.dm:817:error: : invalid expression

**Comment by ghost** [comment]
Yeah, I got that much. Not sure how to fix it. I never touched that line when I made the initial PR.

**Review by Neotwr — CHANGES_REQUESTED** [review]
update your PR's body using the appropriate template explaining Why It's Good For The Game yeet

**Pull request closed without merging**
