### PR TITLE
Revert "Reverts atmospheric and computer icons."

### PR DESCRIPTION
**Pull request by ghost**
Reverts HippieStation/HippieStation#4904

ok seriously the old sprites suck, new ones good

### CODE REVIEW

**Comment by dreamcrab** [comment]
can you not

**Comment by ghost** [comment]
can @Chnkr stop closing these because he doesn't like sprites

**Comment by dreamcrab** [comment]
how do you expect this to be merged when the majority of heads just accepted the opposite of this pr

**Comment by GuyonBroadway** [comment]
Fairs fair this gets at least 24hours before I push any buttons.

**Comment by ghost** [comment]
@MoreRobustThanYou Stop opening pull requests

**Pull request closed without merging**
