### PR TITLE
Buffs spatial gateways

### PR DESCRIPTION
**Pull request by ghost**
:cl:
balance: You can now fight against gay teleporting clock cultists, by going through their own portal!
/:cl:

### CODE REVIEW

**Comment by Majick1** [comment]
+1, high risk high reward gameplay always welcome

**Comment by MaterialisticThings** [comment]
+1

**Comment by Manly-Dwarf** [comment]
high risk high reward always welcome

**Comment by cris5311** [comment]
+1
I think everyone agrees why this is great

**Comment by AnthonyJNgo** [comment]
The PR description says it all.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
