### PR TITLE
Crabbans now work AFTER roundstart

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
bruh

**Comment by Manly-Dwarf** [comment]
make them drop all of their stuff too

**Comment by ghost** [comment]
done, @Manly-Dwarf 
now to wait for it to compile

**Comment by Manly-Dwarf** [comment]
we need to stop speedmerging things, but seeing as this should have been available from the start I'll go ahead and chuck it in

**Review by Manly-Dwarf — APPROVED** [review]

**Pull request merged**
