### PR TITLE
craftable wooden mugs [mergeable] 

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: # Wooden mugs for a craftable, easy reagent container for people to make out of wood
:cl: zamolxius
add: Added wooden mugs to the personal crafting menu in the tribal tab
imageadd: added wooden mug sprite
/:cl:

[why]: because there are no renewable reagent containers (except bottles) for ashwalkers, in example, or the hermit. Except the shitty mushroom bowl which doesn't really give a lot of satisfaction. plus i'm getting a really cool sprite, you'll like it
6d86365b6f49660bf19ec0dec41431e1

### CODE REVIEW

**Comment by ghost** [comment]
>it compiles despite the assignment operator having no right hand side argument

GOD I LOVE BYOND CODE

**Comment by ghost** [comment]
bump. tested. works, doesn't break like a glass mug, etc etc. would it be better in the crafting tribal tab or when using the wood inhand? no variable filling sprite

**Comment by ghost** [comment]
ready for review and merge

**Review by JohnGinnane — APPROVED** [review]
code looks good to me

**Comment by JohnGinnane** [comment]
Need @HippieStation/head input please

**Comment by ghost** [comment]
bump

**Comment by Carbonhell** [comment]
sure +1

**Comment by ghost** [comment]
bump

**Comment by Dinopeaks** [comment]
+1

**Comment by praisenarsie** [comment]
+1

**Comment by Jujumatic** [comment]
+999999

**Comment by Manly-Dwarf** [comment]
-1 Overpowered

**Comment by Pyko1** [comment]
sure +1

**Comment by praisenarsie** [comment]
fucking doesn't even merge it afterwards

@Carbonhell I'M TELLING YA IT'S FLAWED

**Comment by earthmoonjune** [comment]
+1

**Comment by praisenarsie** [comment]
approves an already merged pr, that's meta

**Pull request merged**
