### PR TITLE
[MIRROR] Server tools API v3.2

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/32459
--------------------
Also made the config external to make future upgrades easier

### CODE REVIEW

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by ghost** [comment]
Build finished.

**Comment by praisenarsie** [comment]
```
07:47:39 code/__DEFINES/server_tools.dm:8:error: #error /tg/station server tools interface unconfigured
07:47:53 code/modules/server_tools/st_interface.dm:18:error: missing expression
07:47:53 code/modules/server_tools/st_interface.dm:80:error: missing left-hand argument to !=.
07:47:53 code/modules/server_tools/st_interface.dm:80:error: missing left-hand argument to !=.
07:47:53 hippiestation.mdme.dmb - 4 errors, 0 warnings (11/17/17 7:47 am)

**Pull request closed without merging**
