### PR TITLE
[URGENT] Nerfing atmos circuits

### PR DESCRIPTION
**Pull request by Shdorsh**
[Changelogs]: # Capped max pressurization through atmos pump circuits to prevent maxcaps in < 3 minutes ingame and hopefully strongly nerf explosions 

:cl: Shdorsh
balance: rebalanced atmos circuits
/:cl:

[why]: I told you folks I'll nerf it into oblivion if you act like shitlords using it. Consider this nerf "minor", more to follow if I see or hear of some more maxcap autism.

### CODE REVIEW

**Comment by Carbonhell** [comment]
Can you quickly test it to be sure it doesn't break anything?Also slap [READY] when done
+1 obviously

**Comment by WarRage333** [comment]
>not using things to their full potential and above

Nerf it harder, theres very bad things you can do with these.

**Comment by Shdorsh** [comment]
I am currently busy working for university, so testing this will sadly have to wait for a bit. If any of you guys can or want to take the lead on this, You're welcome.

**Comment by earthmoonjune** [comment]
+1

**Comment by Iamgoofball** [comment]
its almost like we had a reason to not merge these

**Comment by Carbonhell** [comment]
Doesn't mean that they cannot be improved anyhow.

**Comment by Shdorsh** [comment]
Every game mechanic can be either overpowered or pretty good depending on how you balance it. We just had the problem that further research was required to correctly assess the boundaries and the potential of coderbus.

**Comment by Shdorsh** [comment]
I'll have to wait until tomorrow evening to test this, unless someone is ready to do it on homeservers, or just testmerge and see it in action if the situation becomes really dire and close to unplayable.

**Comment by Eagle-Eyess** [comment]
+1

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
Merging, the code shouldn't break anything

**Pull request merged**
