### PR TITLE
[MIRROR] Removes Grandpa as a random first name

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43789
----------------------------

## About The Pull Request

Removes Grandpa from the first name list. 

## Why It's Good For The Game

Grandpa is no longer an acceptable name under naming policy since it falls under a honorific/nickname, so there is no reason for it to be generated as part of a random name.

## Changelog
:cl:
del: Removed grandpa from the first name list. 
/:cl:

### CODE REVIEW

**Comment by mikolaj007** [comment]
but why
-1

**Comment by k-k-karma** [comment]
fucking retarded TG maintainers

**Comment by JessHorserage** [comment]
Idea: Replace Grandpa with NiggerFaggot.

**Comment by Majick1** [comment]
-1 waste of a pr

**Review by yoyobatty — APPROVED** [review]

**Comment by Manly-Dwarf** [comment]
-1 waste of a pr

**Comment by ghost** [comment]
-1

**Comment by ghost** [comment]
Don't think we need to modularise this, so closing thanks to massive negative feedback

**Pull request closed without merging**
