### PR TITLE
Catbeasts are now hurt by chocolate

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Chocolate now causes liver failure in catbeasts. Try it out!
/:cl:

### CODE REVIEW

**Comment by TrickyDickRichard** [comment]
ok, this might be a little based

**Comment by ghost** [comment]
heart failure or no balls

**Comment by karmaisblackandbluepilled** [comment]
+1 based

**Comment by MaterialisticThings** [comment]
+1 BASED

**Comment by ExpAntique** [comment]
+1

**Comment by cris5311** [comment]
+1

**Comment by Manly-Dwarf** [comment]
can you morons stop trying to one-up /r/tgstation and instead focus on actually making hippiestation better?
+1

**Comment by ghost** [comment]
+1, merg time

**Review by ghost — APPROVED** [review]

**Pull request merged**
