### PR TITLE
Added 2 diamond coins to the bar 

### PR DESCRIPTION
**Pull request by Jujumatic**
Following up from #7374, this adds two diamond coins to the bar.

This was requested so that the RD and botanists are less likely to be at each other's throats fighting for the diamond coin, and also to make it easier to get said coins since the only other diamond coin on the station is in some weird place in maint or something

### CODE REVIEW

**Comment by JohnGinnane** [comment]
I know it's a tiny change but can you post pics pls)

**Comment by Jujumatic** [comment]
ahhhh the map bot will do it

**Comment by JohnGinnane** [comment]
idk if this needs head input or not

**Comment by JohnGinnane** [comment]
@HippieStation/head

**Comment by Pyko1** [comment]
I recall you can use a slots machine to turn those diamond coins in to like 20 cheaper coins and use them to buy everything with a coin cost from a vender.

Don't like it.

**Comment by Pyko1** [comment]
slots
and that's just 1 diamond coin

**Comment by Jujumatic** [comment]
Yup, the point is that botanists get their coins so they can unlock the strange seeds, and the RD can use it for his science or whatever

**Comment by Pyko1** [comment]
I dont think this is a good way to handle that, maybe just add some greatly lesser value coins in to maintloot spawner. So everyone can get their coin, with some effort.

**Comment by Pyko1** [comment]
also do you really think they will share if there is 2, implying that the bartender wont just pocket them every round to be used as leverage.

**Comment by Jujumatic** [comment]
only one way to find out ;)

**Comment by Jujumatic** [comment]
to make it simpler i could add one coin somewhere in botany maint and the other in sci maint, if that's better

**Comment by JohnGinnane** [comment]
I think adding easily accessible coins kinda defeats the purpose of premium. You might as well just add the premium items to the normal list just to cut out the time it takes to get the coin you're almost guaranteed

**Comment by Jujumatic** [comment]
my idea was to make it so that it wouldn't be too much of a hindrance while keeping as close to how it used to be as possible

if this is a problem i could just change the megaseed vendor so it gives out the 10 extra seeds instead of being locked behind a coin requirement

**Comment by JohnGinnane** [comment]
idk how it was in the past but the whole point of premium and contraband is that it's a hinderance. You have to work to get the cool shit

**Comment by Carbonhell** [comment]
Why wouldn't this need head input...? It does.
-1, the purpose of coins and their use is based on the fact that they are rare. There is a hidden trick to reuse a single coin multiple times, use that.

**Comment by Jujumatic** [comment]
closing - it's no longer diamond coins

**Pull request closed without merging**
