### PR TITLE
Ports scrubbers and air pipes to layer 1 and 3.

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: Pipes for scrubber and air supply have now been moved to layer 1 and 3 so they can fit on the same tile, completely designing the stations pipe layout.
/:cl:

[why]: Because I was bored and like using new features.

### CODE REVIEW

**Comment by Eagle-Eyess** [comment]
As long as it doesn’t break anything +1

**Comment by yskefunky** [comment]
seems ok +1

**Comment by ghost** [comment]
god no this'll be ugly -1

**Comment by yoyobatty** [comment]
This is going to wait a bit until tg fixes pipe layering.

**Comment by bardofrage** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Comment by GuyonBroadway** [comment]
**CONFLICTS!**

**Comment by yoyobatty** [comment]
Waiting on tg to fix layering to get this merged.

**Comment by yoyobatty** [comment]
Redoing this soon.

**Pull request closed without merging**
