### PR TITLE
sdfs

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: optional name here
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Shouldn't the Clown have a dog and the Mime a cat? Cats are quiet and lazy creatures whereas dogs are usually loud and active. Usually.

**Comment by fluxcapacitor1337** [comment]
+1

**Comment by ghost** [comment]
Maps with diff:

<details><summary>hippiestation</summary>

Old | New | Status
--- | --- | ---
 |  | Modified

</details>
<br>Last updated from merging commit d334afd5fdd345100fdd3dee2aaadc18ff1fe7b4 into cd9491ec94bf23b4cab4f855559b03f828164c2a

**Comment by ghost** [comment]
this was an accident

**Comment by Manly-Dwarf** [comment]
uh ok

**Pull request closed without merging**
