### PR TITLE
[MIRROR] Antag Panel / Check antagonists Refactor

### LINKED ISSUE #28467: Traitor Clowns still clumsy
Traitor clowns still clumsy and unable to use guns.

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34236
--------------------
Important stuff:
- Traitor Panel is now fully automated, for most antag types you shouldn't worry about that code anymore. Just add your special admin_add/admin_remove/antagpanel_data/get_admin_commands if you have any.
- Abductor gamemode is gone
- Traitor specialization refactored ( Fixes #28467 )
- Custom/Brother/Abductor admin add can now choose team/antag name to add to
- Monkey fixes...
- get_teams() helper
- Antagonists without owner are now valid state, should be treated as unassigned and any antag code accessing GLOB.antagonist directly should check for that. get_antagonists() filters these.

Visual changes are minimal, open to feedback on these.

### CODE REVIEW

**Comment by Pyko1** [comment]
added files to hippiestation.dme

**Comment by Pyko1** [comment]
someone prolly needs make changes to shadowling to make it compliant

**Comment by Pyko1** [comment]
eww wew, slings all around shitting on the mirror

**Comment by tortellinitony** [comment]
Shadowlings don't use antag datum?

**Comment by Pyko1** [comment]
shadowling code is causing merge conflicts here and there.

Should prolly just disable sling for now and if someone wants it back he can recreate all the needed crap for the new system.

**Comment by Pyko1** [comment]
some vital shadowling shit might be missing from mind.dm, so would be best to disable it and bring the sling refactor up to date with needed changes and then re-enable.

**Comment by GuyonBroadway** [comment]
is it safe to merge this now slings are disabled?

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@Chnkr #5304 would actually fix slings, because i added antag datums for them

**Pull request merged**
