### PR TITLE
Fixes emojis

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
fix: Emojis work again!
add: More emojis.
/:cl:

Also added a bunch of tg's emojis to our file.

### CODE REVIEW

**Comment by Pyko1** [comment]
Could use pics of the new emotions added as they are a feature, also they need head input

**Comment by Carbonhell** [comment]
@tortellinitony pictures please

**Comment by tortellinitony** [comment]
thats what the icon bot is for you dingus

**Comment by ghost** [comment]
hell yes bring these bad boys back +1

**Comment by Carbonhell** [comment]
Holy fuck i thought the bot only said what icon file had a diff
I literally just found out it shows pics
Im dumb
+1

**Comment by praisenarsie** [comment]
@Carbonhell local doodoo head has never heard of clicking arrows

**Pull request merged**
