### PR TITLE
Improves spurdo mask translation

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
tweak: Improves spurdo sparde mask translation
/:cl:

[why]: Because this https://lingojam.com/SpurdoTranslator

### CODE REVIEW

**Comment by Carbonhell** [comment]
Yeah sure, +1

**Review by Carbonhell — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
I hereby class this as a bugfix.

**Comment by Carbonhell** [comment]
>declaring tweaks as bugfixes
are you high

**Comment by GuyonBroadway** [comment]
It's less a tweak and more a correction of spurdo translation.

**Comment by Lxtoofonea** [comment]
sure seems harmless enough +1

**Comment by earthmoonjune** [comment]
+1

**Pull request merged**
