### PR TITLE
Gets rid of hygiene

### PR DESCRIPTION
**Pull request by ghost**
Who needs that anyways

### CODE REVIEW

**Comment by NautilusViper** [comment]
just run into a shower every now and then

**Review by yoyobatty — APPROVED** [review]
I like plus we tried to soft code it out which only sort of worked

**Comment by ghost** [comment]
Why should I entertain a useless mechanic

**Comment by ghost** [comment]
Hygiene is literally nothing, there's no reason to keep, or remove it.

**Comment by Majick1** [comment]
+1, removing it stops wasting server power on shit nobody ever wanted

**Comment by ghost** [comment]
@NautilusViper you need to fullstrip

**Comment by Majick1** [comment]
Don't think you actually do, it just gives you the message about being an idiot

**Comment by lunaman22** [comment]
you need to remove jumpsuit and suit to clean, only that i think. It'll still give you the idiot message if you have hat, glasses, shoes or tie

**Comment by ghost** [comment]
dude that's literally a fullstrip. I don't know if this was patched but I'm pretty sure it doesn't wash you or your clothes if you don't strip.

**Comment by KingTerrytheTerrible** [comment]
you fucked it up

**Pull request merged**
