### PR TITLE
[MIRROR] Misc Pubby fixes and tweaks

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/38819
--------------------
:cl: Denton
fix: Pubbystation: Fixed the QM camera console's direction.
code: Pubbystation: Used the correct aux bomb camera subtype and replaced loose tech storage boards with spawners, as is done in the rest of the map.
tweak: Tesla balls no longer blow up disposal outlets/delivery chutes and cameras.
/:cl:

- QM console was facing the wrong direction, the tool storage crate chute looks better with a Y offset now. Replaced the atmos side entrance airlock with the non-glass type that has a big visible "A" on it.
- Aux bomb cam was not using the new subtype, secure tech boards were mapped in instead of using spawners.
- Tesla ball zaps have a tendency to blow the disposal chutes and cams inside the chamber - this is bad, since you can't secure them by wrenching down like with tesla coils/rad collectors. Grounding rods don't properly protect from that either, so I ended up blacklisting cams and disposal outlets/delivery chutes.

### CODE REVIEW

**Comment by Pyko1** [comment]
oh welp, prolly better remove the pubby changes from this.

**Comment by Pyko1** [comment]
and have them coming from later mirror, and only apply energyball changes.

**Comment by yoyobatty** [comment]
@Pyko1 good to merge?

**Comment by Pyko1** [comment]
yeah

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
