### PR TITLE
[MIRROR] New brain trauma: expressive aphasia

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43608
----------------------------

## About The Pull Request

Adds a new brain trauma: Expressive Aphasia. You can only use the [1000 most common english words](https://splasho.com/upgoer5/phpspellcheck/dictionaries/1000.dicin). Anything not on that list will either get garbled or cause you to forget what you wanted to say mid sentence.

You can try what it's like in [the up-goer 5 editor](https://splasho.com/upgoer5/).

## Why It's Good For The Game

We could always use some more traumas to spice medical up, this is something that the wizard/syndies or admins could unleash on the crew for mass confusion. It's also quite fun to try and work around that limitation.

## Changelog
:cl:
add: New trauma: Expressive Aphasia only. Restricts your speech to the 1000 most common english words.
/:cl:

### CODE REVIEW

**Comment by mikolaj007** [comment]
+1, just fix the weird conflict out of nothing

**Comment by Majick1** [comment]
+1, 1000 words might be too many to affect gameplay that much though

**Review by ghost — APPROVED** [review]
nice mem

**Comment by ghost** [comment]
@Majick1 oh boy you don't know what you're in for

**Comment by bigbluebeaker** [comment]
+1

**Review by ghost — APPROVED** [review]

**Pull request merged**
