### PR TITLE
Readds shocker circuit, nerfed

### PR DESCRIPTION
**Pull request by Carbonhell**
:cl:
add: Added the shocker circuit back
balance: But tweaked its power use so that it uses 10000W(basically half a supercell, and 66% of a normal high one, so you can only shock once and can't shocklock people like before
/:cl:

[why]: It was fun, and I don't think a full removal is required... Well, yet, atleast.

### CODE REVIEW

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by ghost** [comment]
Build finished.

**Comment by ghost** [comment]
**NO**

Let's not add a zero-downsides tazer to the game that can be mass-produced at roundstart

**Comment by KayeArray** [comment]
Afaik regardless of what the power usage is changed to the tesla circuit lets you outright nullify it.

I agree with chnkr, an automatic stunbaton with limitless power, no need for aim and not even an inhand sprite should not be considered okay just because it relies on circuit autism.

**Comment by dreamcrab** [comment]
-9999

**Comment by Carbonhell** [comment]
it is not roundstart,you still need to do a bit of research + assemble an actual circuit(even tho it's not hard) for it
and with the current setting, with an high capacity power cell it is one use and then you need to recharge, whereas a stunprod lasts for 6-7 uses, so this is the actual downside
let's try to reach an agreement instead of fully removing it, i could make it bulky like the large tesla relay so it can't be put into assemblies/drones perhaps?

**Comment by ghost** [comment]
> it is not roundstart

It IS roundstart, you can manufacture it with the items available on the station at the start of the game, no interaction with mining needed.

> and with the current setting, with an high capacity power cell it is one use and then you need to recharge

This does not matter, this is a stunprod that can be assembled within seconds, and printed without any downside, since batteries can just be mass-produced

**Comment by KayeArray** [comment]
Making it actually shock people so it can be countered with protection would be a good start rather than this knockdown bs.

Secondly it being in inhand assemblies is also bs, you can at least see a drone coming.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
amazing camarad

**Comment by Carbonhell** [comment]
sadly all current assemblies can be used inhand too, even drones, so i can't change that... I guess the shocker circuit has no chance to be brought back in,huh

**Comment by dreamcrab** [comment]
im gonna say no again just for emphasis

**Comment by Shdorsh** [comment]
Add an obscenely long reload time at the end and maybe an okay-ish charging time at the start with a warning message and it's fine?

**Comment by k-k-karma** [comment]
fuck no

**Comment by Shdorsh** [comment]
You know, like with the injector circuit, where the mob needs to stand still for a while.

**Comment by k-k-karma** [comment]
@Shdorsh what's your discord again?

**Comment by Shdorsh** [comment]
chuckster#8566

**Pull request closed without merging**
