### PR TITLE
Buffed IED

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: optional name here
add: Adds a stronger version of the IED you can craft
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

I feel as though the current IED is a little too weak, so I created a buffed counter part that requires 100 fuel and more time to make.

### CODE REVIEW

**Comment by PopNotes** [comment]
you fucked up

**Comment by yoyobatty** [comment]
Explain

**Comment by GuyonBroadway** [comment]
Jenkis says `01:19:53 code/modules/crafting/recipes.dm:38:error: /obj/item/grenade/iedcasing2: undefined type path`

Also, YOU FORGOT TO MAPMERGE! YOU FUCKED IT UP!!!

**Review by KayeArray — CHANGES_REQUESTED** [review]
Firstly why is there a map change?

Secondly why haven't you just made the improved IED a child of the original IED to save yourself from pasting a shitload of code?

**Pull request closed without merging**
