### PR TITLE
[MIRROR]  ~SPELL CARDS~, homing projectiles, and more!

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/36147
--------------------
Adds spell cards. They're a wizard spell that shoots a burst of 5 semi-accurate homing cards.
Projectiles now have a homing framework, complete with some variant of simulated inaccuracy.
The said wizard spell will make use of a new mob component, that allows that mob to select targets by moving their cursor near them. It will give a visual and lock onto the nearest mob to the cursor, allowing the homing projectiles to target on the locked on mob/object.
Removes colliding variable from projectiles - We never used it after Bump was refactored to Collide.
Images soon when I get the lockon datum-components to work.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
>19 files changed

**Comment by JohnGinnane** [comment]
that should be at least 20 actually

**Comment by Manly-Dwarf** [comment]
Well, it's quite cool now that we have homing projectiles.

**Comment by optimumtact** [comment]
you need to mirror https://github.com/tgstation/tgstation/pull/36259

**Comment by JohnGinnane** [comment]
Ah okay, thanks @optimumtact 

Need to look at https://github.com/HippieStation/HippieStation/pull/7003#issuecomment-372019711

**Comment by optimumtact** [comment]
well it doesn't explain what happened in teh spellbook folder though
that looks like a whitespace conflict or something

**Comment by JohnGinnane** [comment]
I'll have a look later today when I'm home, see if there's a mismatch in folder structure with projectiles and then check the spellbook

**Comment by JohnGinnane** [comment]
Looks like we already had that change in place @optimumtact , all we needed was to add the new files to our .dme

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
