### PR TITLE
Add chemical reaction for soda water

### PR DESCRIPTION
**Pull request by cris5311**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Added chemical reaction for soda water
:cl:
## Why It's Good For The Game
You can now make soda water in chem. No more running out of soda for the station!

### CODE REVIEW

**Review by yoyobatty — CHANGES_REQUESTED** [review]
Not modularized at all

**Comment by ghost** [comment]
put it in the hippiestation folder

**Comment by cris5311** [comment]
Like this? Sorry for my mistakes, this is my first pull.

**Review by AnthonyJNgo — CHANGES_REQUESTED** [review]
"Bar_Reactions.dm..dm""

Is this supposed to be like this?

**Comment by cris5311** [comment]
fucked up my branch, will reopen it with fixed one

**Pull request closed without merging**
