### PR TITLE
PLENTS 2: the re-platning!!

### PR DESCRIPTION
**Pull request by GuyonBroadway**
Now with less haphazard placements. 

:cl: GuyonBroadway
add: Nanotrasen has decided to do something about the terrible mental state of the crew, rather than use licensed psychiatry experts they have shelled out on a bunch of cheap pot-plants that a brochure told them will totally help improve everyone mental states. 
/:cl:

[why]: Plants are nice. And you can pick them up to make your sprite become the plants sprite. It might help you hide in a pinch but anyone with a sharp eye and a strong pimp hand will show you what-for. 

A few examples.
image
image
image
image
image
image

### CODE REVIEW

**Comment by dreamcrab** [comment]
neat

**Comment by PopNotes** [comment]
Much better. This doesn't address my previous concern, however, about the plants making it far too easy to escape security and the like.

**Comment by ghost** [comment]
there's something far too comical by escaping security by hiding behind a potted plant

**Comment by JohnGinnane** [comment]
It's amazing really. It's criminal to not have enough plants to make it feasible, seeing as someone went to the trouble of adding it to the game.

**Comment by PopNotes** [comment]
It's funny, but pretty broken. I still would MUCH prefer these plants be like they are in Goon, where you can just sort of run onto their tile and be SORT of hidden from view so chasers would have to keep a keen eye out, as well as being able to shake them to get goodies.

**Comment by JohnGinnane** [comment]
@PopNotes I think these plants are in a higher layer than players already, so you sort of are covered (at least from what I saw on /tg/ last night)

**Comment by dreamcrab** [comment]
wait the plants used to be like you could run behind him, is that not what this is?

**Comment by JohnGinnane** [comment]
If you pick up a plant with both hands empty you basically become the plant. Your icon is hidden completely and you can walk around with the plant icon instead

**Comment by dreamcrab** [comment]
why not make it so the plant is obscuring you and you walk around with your sprite behind it

**Comment by JohnGinnane** [comment]
It's something /tg/ did so, maybe not a bad idea. This PR just adds plants to the map to make use of the feature homey

**Comment by dreamcrab** [comment]
if you can hide behind the plants when theyre on the map and your sprite is visible when you pick them up im down with this

**Comment by PopNotes** [comment]
You can run behind plants to become semi-hidden, but you can also still pick them up to disappear completely.

**Comment by Carbonhell** [comment]
the fact that your sprite becomes the plant's is balanced by the fact that you are slow when moving as a plant, and hovering the mouse on a disguised guy shows the name of the guy,not the plant's name.

**Comment by dreamcrab** [comment]
kay sounds good +plants567u359

**Comment by PopNotes** [comment]
You shouldn't have to shift click every single plant on your path to find the chuckleshit that stole the spare. That's bad:tm:.

**Comment by Carbonhell** [comment]
hovering mouse != shiftclick

**Comment by PopNotes** [comment]
Constantly having to shift your eyes between the item preview and the screen itself = just as fucking bad

**Comment by Carbonhell** [comment]
pmuch takes the same time of looking at each plant in the screen to find someone who's under it like on goon,not a big difference imo

**Comment by dreamcrab** [comment]
i would really prefer it if you were just behind it even in hand but whatever!!!! nerds!!

**Comment by PopNotes** [comment]
having to look at plants and having to mouse over/shiftclick plants, then look at the info, then look back to the plants is a :b:reddy big difference my dear black man

**Comment by GuyonBroadway** [comment]
Not only that but plants are not solid but if a player picks it up they are now suddenly solid and can be pushed,  its because the players sprite temporarily BECOMES the plants sprite so clicking the plant means you hit the player/tase the player/stab the player.

It also means you can find people hiding in plants by running into them and they can hardly fight back as holding a plant required two hands.

**Comment by Pyko1** [comment]
Needs pollen allergy that you can get randomly when hiding in a plant, that makes you sneeze when near a plant.

Since I can already see people camping with guns behind a plant,

**Comment by GuyonBroadway** [comment]
The thing is most plants are transparent enough that you can see someone standing behind them and in order to "hide" you need two hands to pick it up.

**Comment by Pyko1** [comment]
I recall at least in the lavaland syndie outpost there were some plants that pretty much covered you completely with only 1 or 2 pixels left visible. But yeah, only the one next to bridge looks like it could cover you without holding it.

**Comment by ghost** [comment]
yeah i love roleplaying as the plant in that one shuttle
you get to go around and literally whack people with yourself
its great
+1

**Comment by KayeArray** [comment]
+1

**Comment by GuyonBroadway** [comment]
counting bantz this is a +3

**Review by ghost — APPROVED** [review]

**Pull request merged**
