### PR TITLE
CashMoney

### PR DESCRIPTION
**Pull request by AliiTea**
memes

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by AliiTea** [comment]
This is the greatest change in hippie history.

InstaMerge4Memes

**Comment by PopNotes** [comment]
there is literally no reason not to merge this

**Comment by Carbonhell** [comment]
code is ok
but why

**Comment by AliiTea** [comment]
Someone mentioned bay renaming plasma and that hippie should do something similar.. someone shouted Gold is Cash Money and thus here we are.

**Comment by tortellinitony** [comment]
No :-1:

**Comment by j-mie** [comment]
no

**Pull request closed without merging**
