### PR TITLE
Plumbing: A New Generation of Powergaming

### PR DESCRIPTION
**Pull request by ghost**
ports the following prs from /tg/:
https://github.com/tgstation/tgstation/pull/44833
https://github.com/tgstation/tgstation/pull/45082
https://github.com/tgstation/tgstation/pull/45185
https://github.com/tgstation/tgstation/pull/45243
https://github.com/tgstation/tgstation/pull/45263
https://github.com/tgstation/tgstation/pull/45473
https://github.com/tgstation/tgstation/pull/46149
https://github.com/tgstation/tgstation/pull/46448
https://github.com/tgstation/tgstation/pull/46759

tested, it works

### CODE REVIEW

**Comment by Toxici11i** [comment]
_### autistic screaming_

steamport you fool, did you make sure that plumbing will work with how chempiles exist, along with solidification and not brake the universe?

Also - consider this, A 900u tank of BP at -200*C with a sprayer system attached. Spray it, cause 9000 bars of BP to be duped, set off explosion as antag and laugh as the server dies

**Comment by ghost** [comment]
There is no buildable sprayer system, lol

**Comment by ghost** [comment]
what if u break a pipe

**Comment by ghost** [comment]
@zamolxius Nothing happens.

This isn't like the atmos pipenet, where gas just lingers in the pipe. Because pressure, reagents _instantly_ use the pipes to go from A to B.

**Comment by Toxici11i** [comment]
> There is no buildable sprayer system, lol

fair enough, it was one of the things listed on the /tg/ roadmap however

also obligatory +1 due to the fact its time to finally automate chemistry without macros

time to remake factorio inside of ss13....

**Comment by mikolaj007** [comment]
+1, add lcass to this and we are golden

**Comment by yoyobatty** [comment]
https://github.com/tgstation/tgstation/pull/47190 because it has fixes

**Comment by karmaisblackandbluepilled** [comment]
+1 bro i'm gonna fuckign cOOOOM
to explain more why I like it:
It's machine chemistry more fun since you'll have to actually make machines instead of just le mindless clicky. Sure, you can just do it the old fashioned way, but with this you can make mass-production lines of liquid life and shit. I can't wait.

**Comment by DaydreamPuppeh** [comment]
This looks really fun. Perfect for setting up medicine to be produced automatically while I fuck off and do other shit

**Comment by mkikt4743** [comment]
so no more bombs? dang -1

**Comment by ghost** [comment]
@mkikt4743 ????

**Comment by mkikt4743** [comment]
oh wait I thought this replaced chem nvm

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 6cc78caa1921aa8c53b5dccd2cb689f36cd019db
Pull Request: 3f0878bc34b31ff3e26e6c8620a8c3d32b19d96c
Server: ef9936d15e5818f076482fc5ac0370fc0f5b84a5

##### Comment
likely going to be terrible, blame steamport for everything

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 6cc78caa1921aa8c53b5dccd2cb689f36cd019db
Pull Request: cd557e5f8a5538408b0d9c71aaa9116977c111cf
Server: 9d378ebc9f04544a5fdde425c7c9dd3fe32f4393

**Comment by Toxici11i** [comment]
This seems fine as is, been using it for a while and havent ran into any universe destroyin bugs, works fine.

Although its gay you cant mass produce patches

**Comment by AnthonyJNgo** [comment]
I would really like to see how it plays out on TG before we merge this completely and before I +1 this.

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: d96dfd7ea1d7ee3dfd8e5346b3ee12174d0661e1
Pull Request: 5c59b7fd1535b8c1edaacf7e71ed760ace444545
Server: 4831a1f70cb28087d67c8cc11c901c96588ab2d3

**Comment by Manly-Dwarf** [comment]
I like the experimentation but this might turn into a chemistry disaster. Fix the message spam.

**Comment by ghost** [comment]
@Manly-Dwarf 
firefox_KVJlB2cINg

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: f8c5b949d24ea4044a9753583d29b107c5289831
Pull Request: 5c59b7fd1535b8c1edaacf7e71ed760ace444545
Server: 5e51f79b22cdd4f0866641dcde4140997e768f69

**Comment by Maroonenahmoron** [comment]
I've seen it in action and it looks pretty good, continue to merge fixes/additions that are needed here

**Comment by cris5311** [comment]
+1
yessss finally

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 265560b95ab40f7bb315342bbdde8109f276dd95
Pull Request: 5c59b7fd1535b8c1edaacf7e71ed760ace444545
Server: 56a4521021db782d9c2d4e6b490c4c4d3cd1a071

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: d41998c59f63249a3afceed5ec6a21d89342b536
Pull Request: 5c59b7fd1535b8c1edaacf7e71ed760ace444545
Server: 89a47853bc4c816228cdaf6744c7a02008acf7d7

**Comment by karmaisblackandbluepilled** [comment]
+1 gonna cooom

**Comment by mememanrino** [comment]
+1 Automated tricordrazine factories, and surprisingly isn't a nerf or completely overpowered buff, rather balanced.

**Comment by Majick1** [comment]
Well tested and looks like everyone's a fan, +1

**Review by yoyobatty — APPROVED** [review]

**Comment by ghost** [comment]
#### Test Merge Removed

**Pull request merged**
