### PR TITLE
Infiltrator event!

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: 30+ minutes into the round, if the station is relatively intact, an infiltrator team has a chance to be sent in!
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
better than space pirates +1

**Comment by Majick1** [comment]
+1, more reasons to not call shuttle at 20-25 minutes is good

**Review by ghost — DISMISSED** [review]
Code is modularised - I have no experience in antag and event code so I'll assume it's gucci

**Comment by JessHorserage** [comment]
For reference, the fuck is infiltraitors?

**Comment by cb583** [comment]
Infiltrators are the grey ayylmaos who come and probe your ass, they are normally admin spawn but this will change that

**Comment by cris5311** [comment]
+1,

isnt that abductors that probe your ass?

**Comment by mikolaj007** [comment]
they are
infiltrators are basically nukies but stealthy

**Comment by mikolaj007** [comment]
+1 because i forgot.

**Review by ghost — APPROVED** [review]
she'll be roight

**Comment by ghost** [comment]
looks like this has enough votes

**Pull request merged**
