### PR TITLE
[MIRROR] Ports wheelchairs from Hippiestation

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42401
----------------------------
:cl: Jujumatic, port by Denton
add: Ported wheelchairs from Hippiestation. They're craftable with 4 sheets of metal and 6 rods. The less arms you have, the slower you move!
/:cl:

Original PR: https://github.com/HippieStation/HippieStation/pull/7502

I hope @coiax is still up for coding the quadriplegic quirk since that would be amazing.

weed

### CODE REVIEW

**Comment by Dinopeaks** [comment]
W E N E E D T H I S R I G H T B O Y S

**Comment by yoyobatty** [comment]
Guess I'll have to delete outdated code in this pr.

**Comment by Jujumatic** [comment]
@yoyobatty code deleted yet?

**Review by Jujumatic — DISMISSED** [review]

**Comment by ghost** [comment]
Reopening this so we can un-modularise this

**Review by yoyobatty — DISMISSED** [review]

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
