### PR TITLE
Changelings can now actually revive

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt
balance: Changelings can actually revive again
/:cl:

Whoever thought this change was a good idea, burn in hell.

### CODE REVIEW

**Comment by Eagle-Eyess** [comment]
+1

**Comment by Manly-Dwarf** [comment]
And so the day has finally come when someone saltcoded my saltcode. Figures it'd be Amari.

Yeah, sure. Merge this. I have no issue with Changeling being insanely annoying and overpowered again. You didn't even make it so they couldn't revive when on fire, so whatever.
The quicker the gamemode gets removed, the better I say.
(how the fuck do you lose as changeling there are people who still easily murderbone the whole station without buying ANY powers, just using horror form jesus shit)

EDIT:
You didn't even not make it admin revive. Yes. The chips all fall into place now. The salt must flow.

**Comment by ghost** [comment]
@Kawaii-Big-Boss You have nerfed changeling so hard, as soon as I hear the sound effect, I immediately ask to trade for another antag, because you turned it into a dumpster fire.

**Comment by Manly-Dwarf** [comment]
Haaaahahahahah.
Imagine thinking that me removing revive and buffing the shit out of changeling as a whole is turning it into a dumpster fire. Changeling legit has an infinite ammo glock, still can mutesting, still can barf on cuffs, still has a shitload of tools at their disposal in order to just fuck everyone's shit. People still murderbone all the time and succeed as a ling.
I said this before when I first merged the PR, if you die as a ling you're honestly just bad and deserved the death. That's SS13.

But again, I have no issues. If you want to assist me in removing the gamemode, by all means.

**Comment by ghost** [comment]
> infinite ammo glock

Yeah, because that's better than a revive that can be stopped by cremating it, turning it into burgers, or throwing it under the mining shuttle

> still can mutesting

still not as bad as peruoflourdican eyedropper

> still can barf on cuffs

this pretty much tells anyone nearby, and anyone who knew you were cuffed there, that you're valid

> if you die as a ling you're honestly just bad and deserved the death

There's hardly any counter to a giant fucking lynch mob with stunbatons and lasers... especially when combat is stun-based

**Comment by Manly-Dwarf** [comment]
>Yeah, because that's better than a revive that can be stopped by cremating it or throwing it under the mining shuttle

I see this argument a lot and every single time it convinces me that people didn't actually play. Which doesn't surprise me, since you were permabanned at the time. Every single round, lings would :g up and smash the crematorium + gibber. Sometimes the mining console too. Basically meaning your only efforts to get rid of them was to space them, and if you got ambushed in, say, engineering maint, you were fucked and that was it. Nobody would come to save you, if you somehow managed to outrobust the ling, they could adminheal and run away, screaming that you were a traitor. If they retract their armblade and other gear, nobody will know they're a ling.
Literally the only way to kill ling is to powergame them out, or get insanely lucky because the ling player is stupid, and in that case they deserve to die.
>still can mutesting

Perfluorodecalin eyedroppers are indeed quite useful, but would you rather stun + cuff and mutesting them during all of that or have to manage inventory for beakers and the chemicals at hand? Mutesting costs nothing, compared to perfluoro which at the very least requires a pocket slot and a few seconds. When someone is typing up "HELP I GOT STUNNED MAINT LING", that's all the time in the world.
>this pretty much tells anyone nearby, and anyone who knew you were cuffed there, that you're valid

Yeah. So don't use it in front of a crowd. If you got fucked and it's over, HoS has you cuffed and a group is there at the ready to kill you, then you deserve to die.
>There's hardly any counter to a giant fucking lynch mob with stunbatons and lasers... especially when combat is stun-based

Fleshmend, Lube, First-Aid Kids, shooting back, maint chokepoints, flashes, horror form, flashbangs, so on.
Get good. Most people on this server don't lynchmob you, if you did somehow get lynch mobbed then just put on your ling space suit and charge out the airlock, transform into someone else, and keep going.  Otherwise, again, you deserved to die.

**Comment by ghost** [comment]
First of all, gibber can be re-built. The eyedropper is instant chemical injection (i've used it with neurotox before). Or you can just build a ripley and gib them with the drill. Death alarm circuits ARE a thing. Fleshmend doesn't do shit when greytide is throwing IEDs at you... because it's probably gonna set your ass on fire.

**Comment by Manly-Dwarf** [comment]
I almost never see IEDs actually used on me. I see people making them every now and again, but they aren't efficient.
Gibber can be rebuilt but not many people actually do it unless lings are 100% confirmed and they've started powergaming to counteract it.
I think you missed the point with the eyedropper.
Miners usually take the RIPLEY and end up dying or ditching it. Otherwise, just smash that too.
Very few people use circuits, and circuits have been nerfed a ton. Again, if you're dying to this kind of stuff, then you need to pick your battles quicker and learn what to attack first as a ling.

The point of removing revive is to ensure antags have to be on the same playing field. You don't get to cheat death and just instawin because you felt like it, considering how many other tools you also have at your disposal. If you died as a ling, it's because you colossally fucked up and the whole crew was after you, and you didn't make the right steps to escape, transform, and keep going. That, or you weren't robust enough to fight off your assailants (which doesn't require you be that robust at all considering ling's powers). We did the same thing with Wizard and literally nobody had a problem with it outside of some spells suffering from unintended side effects, like Arcane Barrage.

**Comment by ghost** [comment]
What you gonna do next, remove vampire revive?

**Comment by Manly-Dwarf** [comment]
No, vampire just sucks and needs total reworking. I actually didn't know they could revive, because unlike requiring a crematorium, you legit only have to throw them out into space or just put them IN the chapel, which is much different than putting them in access-locked devices.

Vampire is like if someone hated how lings worked, but instead of actually fixing their core design, just nerfed them into the ground. I did something similar, which is why I don't have a problem with reverting the revive nerf. It didn't actually fix the core issue with lings being poorly designed and boring as sin, it just made them more fair on a playing level.
Do note though that there were several buffs in that same PR, too. It was an effort to compensate for the loss of revive. So if you want to revert revive's nerf, you might want to revert those buffs too.

**Comment by ghost** [comment]
Actually, fullpower vamps don't burn or disintergrate in the chapel. For reference, vamps become fullpower at 666 blood, and get revive at like 800.

**Comment by Manly-Dwarf** [comment]
Well, that's different then I'd say. Still don't think you should be able to cheat death, but at least it's not literally free.
Vampire still sucks though. Lots and lots of issues.

**Comment by ghost** [comment]
I mean, once you GET revive, using it costs 0 blood.

**Comment by Manly-Dwarf** [comment]
oh okay
vampire sucks even more then, but not as bad

**Comment by ghost** [comment]
lol

**Comment by Carbonhell** [comment]
Meh sure, +1. Noone liked this change and it made changelings pointless. Just let it back till someone seriously revamps lings

**Comment by earthmoonjune** [comment]
-1, im not against lings reviving, but the way it was before with how it was just free was pretty lame. should find a compromise between the two, similar to how vamps need to get how ever much blood in order to revive. could be something like you need to absorb x amount of people in order to revive and once you revive you'll need to absorb that same amount of people to revive again.

**Comment by ghost** [comment]
@t-f-w revive unlocks at like 800 blood... but after you get that, it costs 0 per revive

**Comment by ghost** [comment]
I personally +1 this change. Lings are probably the least fun antag to play at this point in time, owing some of that to the fact that any accidental death and you're out for good.

Considering lings are probably one of the hardest antags to play (holy shit how many objectives do they need to do) and that out-of-cover lings can be disposed of in numerous ways, there is no reason not to chuck this back in.

**Comment by Manly-Dwarf** [comment]
@HideAndSeekLOGIC 
>changelings
>hard

I keep forgetting our new playerbase is NOTHING like our old playerbase.

**Comment by ghost** [comment]
yeah they aren't very hard to play as but not letting them regen makes them just reskinned stealth traitors.

**Comment by biggiOS** [comment]
+1 i seriously still dont get it why KBB wants to make lings jusg reskinned traitors instead of "the thing"

**Comment by Lxtoofonea** [comment]
+1 everyone I talked to hated kings not being able to revive

**Comment by Manly-Dwarf** [comment]
Should be closed for #9601

**Pull request closed without merging**
