### PR TITLE
Manual upstream merge

### PR DESCRIPTION
**Pull request by ghost**
fixes #4890
fixes #4866
fixes #4870
fixes #4871

also fixes some map runtimes

### CODE REVIEW

**Comment by ghost** [comment]
This PR needs to be manually merged by @JamieH or whomever has access to the database, as there are database updates in this PR.

**Comment by ghost** [comment]
```
18:47:31 hippiestation/code/game/gamemodes/vampire/vampire.dm:100:error: SSblackbox.add_details: undefined proc
18:47:31 hippiestation/code/game/gamemodes/vampire/vampire.dm:103:error: SSblackbox.add_details: undefined proc
18:47:31 hippiestation/code/game/gamemodes/vampire/vampire.dm:109:error: SSblackbox.add_details: undefined proc
18:47:31 hippiestation/code/game/gamemodes/vampire/vampire.dm:112:error: SSblackbox.add_details: undefined proc
18:47:36 hippiestation/code/modules/reagents/chemistry/holder.dm:131:error: SSblackbox.add_details: undefined proc
18:47:37 hippiestation/code/game/gamemodes/wizard/spellbook.dm:60:error: SSblackbox.add_details: undefined proc
18:47:37 hippiestation/code/game/gamemodes/wizard/spellbook.dm:63:error: SSblackbox.add_details: undefined proc
18:47:37 hippiestation/code/game/gamemodes/wizard/spellbook.dm:288:error: SSblackbox.add_details: undefined proc
18:47:37 hippiestation/code/game/gamemodes/wizard/spellbook.dm:517:error: SSblackbox.add_details: undefined proc
18:47:37 hippiestation/code/game/gamemodes/wizard/spellbook.dm:534:error: SSblackbox.add_details: undefined proc
18:47:37 hippiestation/code/game/gamemodes/wizard/spellbook.dm:551:error: SSblackbox.add_details: undefined proc
18:47:37 hippiestation/code/game/gamemodes/wizard/spellbook.dm:569:error: SSblackbox.add_details: undefined proc
18:47:38 hippiestation/code/modules/admin/verbs/testdummy.dm:13:error: SSblackbox.inc: undefined proc
18:47:38 hippiestation/code/modules/admin/verbs/testdummy.dm:14:error: SSblackbox.add_details: undefined proc
18:47:40 hippiestation/code/modules/admin/verbs/spawnfloorcluwne.dm:20:error: SSblackbox.add_details: undefined proc
18:47:40 hippiestation/code/modules/admin/verbs/spawnhuman.dm:12:error: SSblackbox.add_details: undefined proc
18:47:40 hippiestation/code/modules/mentor/mentorpm.dm:15:error: SSblackbox.add_details: undefined proc
18:47:53 hippiestation/code/game/gamemodes/nuclear/nuclear_challenge.dm:49:error: SSblackbox.set_val: undefined pro
```

Need to update this.

**Comment by ghost** [comment]
Build finished.

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by ghost** [comment]
Build finished.

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by ghost** [comment]
Build finished.

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by ghost** [comment]
Build finished.

**Review by j-mie — APPROVED** [review]

**Pull request merged**
