### PR TITLE
[MIRROR] Remove shocker circuit

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/32758
--------------------
:cl: oranges
del: Removed the shocker circuit
/:cl:

It's a little bit too overpowered

### CODE REVIEW

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by ghost** [comment]
Build finished.

**Comment by Carbonhell** [comment]
-1111111111111111111111

**Comment by praisenarsie** [comment]
shut up

**Review by KayeArray — APPROVED** [review]

**Comment by HippieBartels** [comment]
Thanks but no thanks

**Comment by Carbonhell** [comment]
don't worry,adding it back in

**Pull request merged**
