### PR TITLE
Vampires: Dead and not loathing it

### PR DESCRIPTION
**Pull request by NautilusViper**
## Changelog
:cl: NautilusViper
balance: Reviving is now an inherent vampire power available from the start. Who the FUCK thought that IMMORTAL VAMPIRES should have to UNLOCK being IMMORTAL?
balance: Vampirize is now unlocked at 666 total blood instead of 700. 666 is the ceiling, it's common sense.
balance: Hypnotize now takes two seconds to cast instead of five. Now it's not completely worthless!
/:cl:

## About The Pull Request

These were the big three uh oh spots that I've observed for vampires. Reviving should never have been locked behind 800 fucking blood, being able to come back from death is literally the one thing about vampires that's remained consistent throughout pop culture.
666 blood is the threshold where the in-game text itself tells you that you've hit your full potential, and that not being the case was misleading.
Hypnotize taking FIVE SECONDS of uninterrupted casting to stun someone is ass-bustingly hilarious, because someone thought it was actually a good idea.

## Why It's Good For The Game

Vampires are AIDS. Gameplay wise, they're supposed to replace changelings, which were a very heavily flawed but still infinitely more fun antag to play than vampires are. This is a meager attempt at making the reverberating 'SUCC' seem more like an audible opportunity for becoming the bat man than a knell of frustration.

### CODE REVIEW

**Comment by ghost** [comment]
i like this

**Comment by ghost** [comment]
Thanks for making vamps not glorified greytide +1

**Review by ghost — DISMISSED** [review]
code looks good

**Comment by Manly-Dwarf** [comment]
>balance: Reviving is now an inherent vampire power available from the start.

-1

Everything else is cool. I'd like it if blood draining was sped up, and I could probably do that myself.
But no. We've had this discussion with changelings, antags reviving from death cheapens the hunt for antags and just makes rounds drag out while also making them massively more powerful especially if they don't leave any evidence. At least Vampires leave evidence in their corpses, and there is the inherent weakness to the Chapel/holy objects so I'm willing to discuss it for this gamemode.

**Comment by NautilusViper** [comment]
> > balance: Reviving is now an inherent vampire power available from the start.
> 
> -1
> 
> Everything else is cool. I'd like it if blood draining was sped up, and I could probably do that myself.
> But no. We've had this discussion with changelings, antags reviving from death cheapens the hunt for antags and just makes rounds drag out while also making them massively more powerful especially if they don't leave any evidence. At least Vampires leave evidence in their corpses, and there is the inherent weakness to the Chapel/holy objects so I'm willing to discuss it for this gamemode.

Vampires instantaneously dust while crit (or just dead? one of those) in the chapel, can't revive with holy water in them and just being whacked with a bible is enough to expose someone as a vampire in the first place. It also takes a full minute to revive from death and Vampires don't get that ez pz go headslug, run into a vent and find a corpse meme tactic that changelings did. Vampires really, REALLY get the short end of the stick as far as power goes, especially compared to regular old traitors. Giving them the one single thing vampires are known for as a starting ability would give them the edge they need to not be the 'FUCK' antag of lowpop.

**Comment by Manly-Dwarf** [comment]
Okay, I can see the reasoning there. Just want to know, does vampire revive simply make them alive again or aheal?
Either way this still doesn't quite do enough for me, Vampire is still really slow and boring, and I'd rather most of the development go towards Pillar Men. This gamemode needs more of an "oomph", and not in a Changeling way.

**Comment by ghost** [comment]
Literally as soon as a person gets exposed as a vampire anyone even remotely robust will begin to drag corpses to chapel. Considering vamps are basically greytide when they start off, this gives them a pretty alright safety net in case of an early death; those happen all too often.

**Comment by Manly-Dwarf** [comment]
In practice, it's not really just reviving in maintenance after some traitor bags and drags you, it's reviving right as you're about to be taken to the crematorium, regenerating any limbs that came off, and also breaking cuffs to just escape or instantly stun the guy who killed you.
Not a problem if it's not aheal, but if it is aheal then hell no.

**Comment by ghost** [comment]
Let me check the code.

EDIT: Yep, that's a full heal. All limbs regrow as well. There should probably be some way to give an indication to anyone near the corpse that it's about to revive.

EDIT 2: There is a message which pops up to anyone around the reviving vamp and a sound that plays if they are missing any limbs. However, this is done instantaneously and with no delay so just as you said they can pull out a stun prod and completely reverse the situation.

**Comment by ghost** [comment]
@Manly-Dwarf Would you be alright if vamps got stunned for a good 10-20 seconds after reviving? It would mean that all the messages and sounds would play to anyone nearby, giving them enough time to act. @NautilusViper, would you be fine with making this change?

**Comment by Manly-Dwarf** [comment]
Sure, that'd fix the problem easily.

**Comment by NautilusViper** [comment]
I'd say a ten second stun and a spooky noise would be acceptable.

Although I don't really know how to implement that, so.

**Comment by ghost** [comment]
Nigga I'll do it then

**Comment by ghost** [comment]
@Majick1 @cris5311 can you give this bad boy some of your thoughts?

**Comment by ghost** [comment]
how about this: vampires are objectively false and the more people look at them the less powers they have, but 1v1 they are perfect predators of the night. alone, they have powers to help them stay unnoticed until striking

**Comment by mikolaj007** [comment]
i dislike vampire as a concept due to the fact that the best way to play them is to stun someone, cuff them, suck blood for 2 minutes while the victm is slowly dying then move on to the next person. traitors have TC's at their disposals and changelings can change and can steal dna using the sting. vampires dont have any such options until they kill at least one or more people

**Comment by cris5311** [comment]
+1

Vampires as of now are extremly weak im the begining, which nmakes them quite unfun if you dont get lucky. especally if your job dosnt have acces to any sort of stun weapons it can become very tedious. With those changes, I think, vampire will be a bit more fun in the beginning and it does make sense that an imortal vamp is imprtal

**Comment by Manly-Dwarf** [comment]
@mikolaj007 hits the nail on the head. Vampires is just a really bad mode, even if you buff them.

**Comment by NautilusViper** [comment]
> +1
> 
> Vampires as of now are extremly weak im the begining, which nmakes them quite unfun if you dont get lucky. especally if your job dosnt have acces to any sort of stun weapons it can become very tedious. With those changes, I think, vampire will be a bit more fun in the beginning and it does make sense that an imortal vamp is imprtal

This is a very poorly spelled yet very similar line of thought to the one I have.

> @mikolaj007 hits the nail on the head. Vampires is just a really bad mode, even if you buff them.

Here's my bargain: Vampire will be a less bad mode after this buff.

**Comment by NautilusViper** [comment]
https://github.com/HippieStation/HippieStation/blob/fd39ad73d08ca49c11c92127d8ef075037677569/hippiestation/code/datums/antagonists/vampire.dm#L220

What if I reduced this from five seconds per succ tick to three seconds per? That would at least speed up the succing process a good bit. I've heard the sentiment of 'succing is boring and takes too long' and this would help supplement that.

**Comment by Majick1** [comment]
Been holding off on input with so many ideas flying around, maybe to alleviate the issue cris brought up about no stuns, give the vampire a hypnotism ability similar to cult stun to keep it lore friendly and have a roundstart way to get your early targets.

**Comment by NautilusViper** [comment]
> Been holding off on input with so many ideas flying around, maybe to alleviate the issue cris brought up about no stuns, give the vampire a hypnotism ability similar to cult stun to keep it lore friendly and have a roundstart way to get your early targets.

The idea behind the Hypnotize buff (5s > 2s) is exactly that, giving vamps a reasonable way to stun without TOO much effort. Two seconds should be just enough to get a stun on someone after a successful disarm shove, table, water slip et cetera.

**Comment by JessHorserage** [comment]
+1

**Review by yoyobatty — APPROVED** [review]

**Comment by NautilusViper** [comment]
merg wen

**Comment by ghost** [comment]
I'll assume KBB gave this a +1 so it's time to yeeeeet

**Pull request merged**
