### PR TITLE
[MIRROR] [READY] Replaces sleepers with stasis beds (Lifeform Stasis Unit)

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43075
----------------------------
This is a revive of #36090, however I have not touched sleepers ~~at all~~, instead implementing stasis beds as a new structure
*Sleepers have since been updated to delete their circuit board if they are spawned on any map*

See also: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=16171

~~No mapping updates right now, I'm not exactly sure how i want to do the map updates anyway~~

The stasis beds will put patients in stasis, they require power. Stasis halts most of Life() with some exceptions. This includes bleeding, reagents, disease, breathing, and more. The patients are fully exposed while in stasis, so you are able to apply treatment. Most of the time you will have to take them out of stasis to allow the treatment to take effect. Stasis also halts corpse decay, so it may seem as if they had died sooner than they really did.

~~__Needs sprites, currently using placeholder ones. It looks like the operating table right now.__
The required sprites are the sprite for the bed itself, a broke sprite, and a "panel open" sprite. I am not a spriter and I don't want to attempt it~~

## What's the point?
I want medical to be better integrated with the station's resources, and other departments. The aim of these is to replace the sleepers on the map and remove the sleepers circuit board from being available in-game. (It was generally removed but intentionally left in as a loot item somewhere) This will cause the medical department to lose the chemical generation function that the sleepers provide, so their treatment must use supplies from medbay storage, chemistry, botany, cargo, mining, or space exploration, depending on how desperate they are. These stasis beds will allow doctors to place patients in stasis while they gather or await the appropriate supplies for treatment.

### Why is this good for the game?
I think it will encourage cooperation between departments, and allow medical to be hurt if the other departments get hurt, and they haven't stocked up.

I want some discussion!

:cl: JJRcop and Kmc2000 (sprites)
add: Replaced Sleepers with Lifeform Stasis Units. These place patients in stasis, a new status effect that halts biological functions indefinitely. It also prevents corpse decay.
/:cl:

placeholder stasis icon, but is ok for final unless i get a new sprite
Screenshot_20190309_061033
*it's probably gonna be final*

todo (please give feedback on this):
 - [x] ~~figure out if parts like manipulators should be used in building, and how they affect perf~~
   - not right now
 - [x] implement deconstruction like other machines
 - [x] implement the replacement of sleepers
    - ~~change how sleepers work to remove chemical regeneration?~~
    - ~~readd this to a subtype?~~
    - [x] remove sleepers from techwebs and map entirely?
        - removed from station maps but not ruins
        - map spawned sleepers delete their circuits when initialized
 - [x] get sprites for this whole thing
   - [x] get better sprites
   - [ ] get fixed sprites
      - not merge blocking, the sprites work but the tubes are slightly misaligned
 - ~~allow interoperation with operating computer~~
   - ~~increase surgery probability?~~
   - in another PR

### CODE REVIEW

**Comment by WarRage333** [comment]
Bad = replace sleepers 

Good = add along sleepers

**Comment by mikolaj007** [comment]
i can see the reason behind their decision tho. sleepers are pretty strong.

**Comment by mikolaj007** [comment]
but yea, -1, because chemistry never makes heal chems and we rarely have good doctors on board anyway

**Comment by Jujumatic** [comment]
DO NOT MERGE THIS IS BASICALLY GOOF MEDICAL IN DISGUISE

**Comment by NautilusViper** [comment]
> Bad = replace sleepers
> 
> Good = add along sleepers

**Comment by Majick1** [comment]
I also support the add alongside sleepers, maybe make these portable as a way to get someone in crit to medbay without them dying on the trip. Also with hippie players they'd probably succumb as soon as they got put in stasis anyway

**Comment by ExpAntique** [comment]
-1

**Comment by ghost** [comment]
This needs modularisation asap. Further PRs aren't going through because of this gay ass shit

**Review by yoyobatty — DISMISSED** [review]

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
