### PR TITLE
[MIRROR] Removes vorecode

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43991
----------------------------
## About The Pull Request
wtf? 

## Changelog
:cl:
del: Removed the ability of fat people to vore monkeys, and the ability of aliens to vore humans.
code: Removed stubbed out would-be functionality related to stomach contents
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
We already went through this, it was a matter of time until /tg/ freaked out about the joke, too.
-1.

**Comment by Manly-Dwarf** [comment]
This also removes the ability for xenos to do this, too, which is actually a real xeno strat so they can transport people around - even through vents. What the fuck is this lame grudgecode?

**Comment by ExpAntique** [comment]
-1 dumb and gay

**Comment by Majick1** [comment]
-1 if it removes a gameplay mechanic like manly said

**Comment by k-k-karma** [comment]
WAAAAAAAAAAAAAH WAAAAAAAAAAH MY VORECODE IS BEING REMOVED!!!! HOW ELSE AM I SUPPOSED TO ERP WITH VORE ON HIPPIE NOW?

**Comment by ghost** [comment]
foot fetishists exist,  clearly to excise this tumor of depravity we must make all spacemen spawn with no legs

**Comment by k-k-karma** [comment]
footstep noises were actually added by a tg foot fetishist

**Comment by NautilusViper** [comment]
apparently, beyond the 'hur dur vore' meme, I'm told that the code for devouring is _really_ shitty, though I'm not experienced enough to confirm or deny that

if true, maybe someone who gives a shit should try building new devour code from the ground up so we can still eat monkeys

**Comment by Manly-Dwarf** [comment]
No, really, we went over this a year ago when Karma found the code and threw a fit as well. I even bought into it at first until I realized that it was actually just a fucking stupid joke that's been in the game for years.
https://github.com/HippieStation/HippieStation/pull/9604
Plus, this also removes it from Xenos, using "M-MUH FETISH CONTENT!!!" as a reason to stealthily grudgecode xenos. Keep doing what you do, /tg/.

**Comment by mikolaj007** [comment]
i never used it, so if it increases amount of code we have to run pointlessy without xenos around +1

**Comment by AnthonyJNgo** [comment]
The meme stays, and removing an aliens ability to devour a human which is literally what they do is insane. Closed.

**Pull request closed without merging**
