### PR TITLE
[MIRROR] Fixes science scaling to decrease materials rather than increase....

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/36253
--------------------
heh heh?
:cl:
rscadd: Oh hey guys, RND shows correct material values now, don't hurt me!
/:cl:

### CODE REVIEW

**Comment by JohnGinnane** [comment]
This doesn't look right, going to watch for previous PRs to merge before merging this

**Comment by JohnGinnane** [comment]
Requires #6987

**Comment by Pyko1** [comment]
should be ok for merge

**Comment by Pyko1** [comment]
added the fix from https://github.com/HippieStation/HippieStation/pull/7067/files to this PR

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
