### PR TITLE
Adds Endostation

### PR DESCRIPTION
**Pull request by LastCrusader105**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

Adds Endostation
map

## Changelog
:cl:
add: Added Endostatiob
add: Added musical instrument and plushie vending machines
add: Added New areas (only mapping related)
/:cl:

## Why It's Good For The Game
new map always good
awakens the Hippie Squad

atm its just to make sure the Map is acceptable to hippie code before i go adapting it to fit Hippie

### CODE REVIEW

**Comment by yoyobatty** [comment]
I like but we currently fixing old rusted out hippie code atm so this might not get merged soon

**Comment by AnthonyJNgo** [comment]
@yoyobatty As long as he clears any conflicts we should be g2g yeah?

**Comment by LastCrusader105** [comment]
> @yoyobatty As long as he clears any conflicts we should be g2g yeah?

good to test merge it now, map works i just dunno how hippie it is

**Review by AnthonyJNgo — APPROVED** [review]
map changes, lgtm

**Comment by Pyko1** [comment]
Should had prolly added the map in to:
https://github.com/HippieStation/HippieStation/blob/master/_maps/_basemaphippie.dm

as that is the file we actually use for maps, instead of:
https://github.com/HippieStation/HippieStation/blob/master/_maps/_basemap.dm

**Comment by Pyko1** [comment]
@LastCrusader105

**Comment by carlopault** [comment]
+1

**Comment by LastCrusader105** [comment]
done on new PR https://github.com/HippieStation/HippieStation/pull/12888 cause im not good at github

**Comment by xTrainx** [comment]
Hey this replaced the main hippistationap

**Pull request merged**
