### PR TITLE
New Wizard Spell - The Almighty

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Added a new wizard spell - The Almighty. It allows them to choose a target, and then shift into a position of "advantage".
code: Client mouse tracking is now available again.
/:cl:

### CODE REVIEW

**Comment by WarRage333** [comment]
video?

**Comment by ghost** [comment]
https://cdn.discordapp.com/attachments/276455180852264960/630933403197505548/UodY3cH4um.webm

**Comment by ghost** [comment]
Incase anyone is wondering _what this actually does_: for normal, non-player mobs, it just teleports you randomly around them and attacks them.

But if it's a player, you will teleport to the _furthest point from their cursor_ and attack. And it can be repeated.

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by cris5311** [comment]
+1

**Comment by ExpAntique** [comment]
+1

**Comment by Majick1** [comment]
Ok, +1

**Comment by Manly-Dwarf** [comment]
this is a self-admitted anime reference
stop

**Comment by mikolaj007** [comment]
+1 lol

**Comment by ghost** [comment]
@Manly-Dwarf nope, wrong.

image

**Comment by Maroonenahmoron** [comment]
I'm going to request that in order to prevent easy OHKOs with stun batons, wants etc. that the wizard that does this becomes unarmed for a duration but each punch they throw the following ones hit harder/can be punched quicker on the target. If the spell is going to have a cooldown, make it long but reduce it based on the combo of punches thrown.

**Comment by ghost** [comment]
Ok, i've changed it to work similarly to how @Maroonenahmoron suggested.

**Comment by Maroonenahmoron** [comment]
+1, looks like we ironed things out on what it can and can’t do.

**Comment by ghost** [comment]
Discord_dHYhviC7wU

**Comment by MaterialisticThings** [comment]
+1

**Comment by Toxici11i** [comment]
+1 if only meele and no baton

**Comment by danxnader** [comment]
It was tested on me, for some reason. Overpowered, transitions are too fast, so you can't just attack wizard back

**Comment by ghost** [comment]
@danxnader Ok, I kinda made the cooldown between teleports a bit longer.

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: de389cb9b69fc080531deec8a2e83ba48640b312
Pull Request: da2392c798c8e6c100c6ca05c0cefe112e7b2c39
Server: dccc308a28849e631b188dd6abad96f80cf4c384

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: de389cb9b69fc080531deec8a2e83ba48640b312
Pull Request: da2392c798c8e6c100c6ca05c0cefe112e7b2c39
Server: 20701673e74cd3729382b7a56cf2295e851c4bcb

##### Comment
black

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: f4c6e8cadc57eb5725dfbcd5120c87c83013bb57
Pull Request: 0429effc5d400f9e4487e56756e1100f50a942c2
Server: d694dd9d1ef6a59a4921ed970f026e6255367029

##### Comment
black

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 6cc78caa1921aa8c53b5dccd2cb689f36cd019db
Pull Request: 0429effc5d400f9e4487e56756e1100f50a942c2
Server: ef9936d15e5818f076482fc5ac0370fc0f5b84a5

##### Comment
black

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by Manly-Dwarf** [comment]
wizard crap
fix the cooldown bug

**Comment by cris5311** [comment]
+1
sure why not

**Review by ghost — APPROVED** [review]
merging once you fix the cooldown bug dwarf talked about

**Comment by diegoxt45** [comment]
why ins't this merged?

**Pull request closed without merging**
