### PR TITLE
Botany 50 mutagen fix

### PR DESCRIPTION
**Pull request by mikolaj007**
## Changelog
:cl: Mideanon
fix: Putting 50 mutagen in a plant no longer mutates it after changing the species
/:cl:

## About The Pull Request
now when mutating species, you no longer have to fear for your plant to get mutated again and fucking something up

disregard the commits, i fucked with virus code on my master and reverted it for this branch

### CODE REVIEW

**Review by Jujumatic — APPROVED** [review]

**Comment by Jujumatic** [comment]
tested?

**Comment by mikolaj007** [comment]
No not really, but it should work

**Comment by Jujumatic** [comment]
test it 🔫

**Comment by mikolaj007** [comment]
alright i realised my solution was stupid, because it meant other chems didnt take effect.
we can do this either the easy way or the hard way.
either copy the proc to modularize it, or put the 50 mutagen code into the original proc.

**Comment by RafRoq** [comment]
See if it remove the nutriment or and water

**Comment by RafRoq** [comment]
Because when you add any chemical to a tray it already remove the reagents this is caused by something else

**Comment by mikolaj007** [comment]
Its caused by the way mutation is handled
Its something like:
If 5 mut
Else if 2 mut then
else if 1 mut then
Then it runs all the other stuff like water and nutriment

Then it destroys all reagents with the method i used

Your 50 mut thing isnt included in the else if chain, so it runs independently

**Comment by RafRoq** [comment]
Then recreate the proc using comment

**Comment by Jujumatic** [comment]
I guess just add a boolean which turns to true if the plant mutated with 50 u and then put the boolean check with the prob check that causes the plant to mutate if it detects mutagen or whatever

**Comment by Jujumatic** [comment]
So basically copy the entire proc for applyChemicals and you can put all the checks there. Like that we don't need to use ..() either

**Comment by Carbonhell** [comment]
what is the issue here?i don't get it, does this also remove water and nutriment?

**Comment by Carbonhell** [comment]
?

**Review by yoyobatty — APPROVED** [review]

**Comment by yoyobatty** [comment]
I meant to close

**Pull request closed without merging**
