### PR TITLE
Adds autosurgeons to RnD

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Autosurgeons can now be researched and made in RnD!
/:cl:

### CODE REVIEW

**Comment by cris5311** [comment]
+1

this is good

**Comment by karmaisblackandbluepilled** [comment]
+1 me coOOOOOOOOOOOOM

**Comment by TrickyDickRichard** [comment]
lmao dab +1

**Comment by WarRage333** [comment]
Please up the crafting cost to include some ore, its really strong. 4000 titanium and 4000 uranium, add 2000 diamond if you don't want every material to be readily available on the station.

Otherwise +1 if i were a designer

**Comment by Majick1** [comment]
Kinda hesitant on just giving it to science, maybe make it a really expensive cargo purchase in a medical locked crate

**Comment by ghost** [comment]
add it to cargo honestly. capitalism is a thing, if you don't create goods which would be in demand there will be no commerce

**Comment by AnthonyJNgo** [comment]
The description needs to be fleshed out with more information.

**Comment by ghost** [comment]
closing in favor of Auto-Doc

**Pull request closed without merging**
