### PR TITLE
we don't have that much coverage tbh

### PR DESCRIPTION
**Pull request by praisenarsie**
coverage

### CODE REVIEW

**Comment by Carbonhell** [comment]
Issue resolution 5 d
mfw:
AI cameras Map Issue
#1709 opened on Jun 5, 2017 by HonkBot

**Comment by praisenarsie** [comment]
@Carbonhell p sure it's showing average

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
Is this...a feature or what?
In doubt, +1

**Comment by tortellinitony** [comment]
i don't like how there are so many stupid badges

we  just copied them from tg let's get our own

**Comment by praisenarsie** [comment]
@tortellinitony if we are getting our own labels, keep the made in byond one

**Pull request merged**
