### PR TITLE
[MIRROR] Updates travis to build on BYOND 512.1403

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34546
--------------------
:cl: Frozenguy5
code: Travis now builds on BYOND 512.1403
/:cl:

@ optimumtact 

firefox_2018-01-17_19-52-53

### CODE REVIEW

**Comment by praisenarsie** [comment]
aeiouaeiouaeiouaeiouaeiouaeiou

**Review by praisenarsie — APPROVED** [review]
hey i made this

**Comment by Pyko1** [comment]
should prolly update our byond before merging this

**Comment by praisenarsie** [comment]
no need?

**Pull request merged**
