### PR TITLE
Badmin Gauntlet changes

### PR DESCRIPTION
**Pull request by ghost**
:cl:
balance: The Badmin Gauntlet/Syndie Stone's Shockwave now moves faster
balance: The Badmin Gauntlet/Syndie Stone's Shockwave now stuns for 3 seconds.
add: Captain Nanotrasen now has his own shield, rather than a bananium shield.
/:cl:

sprites for shield by Sagaty12

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
ok ok +1

**Comment by Majick1** [comment]
+1

**Comment by lunaman22** [comment]
+1 why not

**Comment by sagaty13** [comment]
+1 yes

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
