### PR TITLE
Makes buying Wiz spells not a complete gamble.

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: The Spellbook now actually tells you if a spell requires a staff or not.
/:cl:

## About The Pull Request
What is this format and why

## Why It's Good For The Game
destroy guyon

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
I removed the garbage capitalizing because it looked ugly.
I thought it would make it more visible to players but all you really need is the "Can" or "Require"

**Review by Carbonhell — DISMISSED** [review]
Why did you mirror the whole proc? Can't you just do . = ..() and add the staff string to .?

**Comment by Carbonhell** [comment]
jesus christ stop

**Comment by Maroonenahmoron** [comment]
Despite this being open and closed and the title changes, yes. I don't even want to hunt down the mime or clown to get a staff that I believed I did not need. +1

**Comment by Manly-Dwarf** [comment]
Wait, changes like these need +1s?

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by k-k-karma** [comment]
you made it a feature, and this can affect rounds

**Comment by Manly-Dwarf** [comment]
dumb

**Review by ghost — APPROVED** [review]
Yeah, looks good

**Comment by TheMeatGod** [comment]
+1

**Review by yoyobatty — APPROVED** [review]
Has enough votes.

**Pull request merged**
