### PR TITLE
[MIRROR] Support stations with multiple z-levels

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35339
--------------------
:cl:
refactor: Map initialization now supports stations with multiple z-levels.
fix: The map reader no longer sometimes expands the world size inappropriately.
tweak: Pride's Mirror's destination has become less predictable.
/:cl:

Continuation of #34633, pursuant to completing the port of #32037. Big and probably deserves some actual scrutiny but things seem to be working in my tests and all the debug output checks out.

Done:
* **Support multi-z station maps**, planetstation here we come
* Load Lavaland and Reebe dynamically
* Allow any mix of multiple z-levels in one `.dmm` and multiple `.dmm` files
* Remove the last of the `ZLEVEL_` defines
* Allow map json files to specify traits for their maps
* Use traits to configure which levels are up/down relative to each other (ladders, chasms)
* Use traits to configure space linkage (transitions) rather than a separate config

Future work:
* Final tweaks to support multi-z mining zones and away missions
* Coordinate with DB folk to decide if default ordering of z-levels should be changed
* Migrate z-level lists in `GLOB` and subsystems to vars on `datum/space_level` for ease of maintenance
* Heap-allocation of z-levels and subregions, related deallocation and clearing

Output of "Debug Z-Levels" on a station map with three of them:
image

### CODE REVIEW

**Comment by ghost** [comment]
Maps with diff:

<details><summary>Space</summary>

Old | New | Status
--- | --- | ---
 |  | Deleted

</details>
<details><summary>Space2</summary>

Old | New | Status
--- | --- | ---
 |  | Deleted

</details>
<details><summary>SpaceStation</summary>

Old | New | Status
--- | --- | ---
 |  | Deleted

</details>
<br>Last updated from merging commit 0272df7f445de8e53e728c0887dc91c95c4f64ca into 398b8e3a8f5f046e85285384d9dd6ac664b14ac8

**Comment by Carbonhell** [comment]
let's wait a day or two before dealing with this pr, it touches too many files

**Review by praisenarsie — APPROVED** [review]
@Carbonhell @Chnkr maintainers can't merge this due to the runtime checker in travis but since you are code owner, you can merge this whenever you can. i've reported the runtime upstream so to avoid conflicts let's merge this asap

**Comment by praisenarsie** [comment]
nevermind the fix has been merged upstream, now to wait for travis and merge this and get it over with

**Comment by praisenarsie** [comment]
FUCK

**Comment by praisenarsie** [comment]
YOU

**Pull request merged**
