### PR TITLE
[MIRROR] Ore Stacking

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/33062
--------------------
Ores can now be stacked to 50. At that point they'll be weight class huge (5). Ore satchels now can hold weight class 5 to compensate, as well as having a 16 combined weight class with 8 slots to compensate.

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
this needs some minor mapping tweaks.

**Comment by KayeArray** [comment]
https://github.com/tgstation/tgstation/pull/33165

**Comment by JohnGinnane** [comment]
@GuyonBroadway what sorta changes?

**Comment by JohnGinnane** [comment]
Gonna take a stab at fixing the ore changes

**Comment by JohnGinnane** [comment]
@GuyonBroadway @Chnkr it compiles, however I'm not sure what map tweaks are needed, so let me know

**Pull request closed without merging**
