### PR TITLE
Upstream merge

### PR DESCRIPTION
**Pull request by ghost**
Fix our code to work with new roundend shit, I also recompiled tgui and the changelog.

Closes all mirror PRs.

### CODE REVIEW

**Review by KayeArray — APPROVED** [review]
he said it actually works when tested !!!!

**Comment by Blute1** [comment]
wow I always love these prs because you cant fucking revert anything because its all one jumbled mess

**Comment by GuyonBroadway** [comment]
You should not be reverting any of the PRs this is comprised of directly anyway.

**Comment by ghost** [comment]
*scream

**Comment by ghost** [comment]
@Blute1 anyone who knows how to git can revert individual commits

**Pull request merged**
