### PR TITLE
Gondolas now drop gondola meat

### PR DESCRIPTION
**Pull request by WarRage333**
## Changelog
:cl:

fix: Gondolas now drop thier meat when butchered 

/:cl:

## Why It's Good For The Game

You can now make people gondolas what a terrible fate

### CODE REVIEW

**Review by Carbonhell — APPROVED** [review]

**Comment by Manly-Dwarf** [comment]
do me a favor and fix the gondola sprites while you're at it
the "leg" and "hide" sprites are reversed for some reason

okay thanks

**Comment by WarRage333** [comment]
The face sprite is also missing, this is a whole can of spaghetti i don't want to touch to fuck something up

**Comment by Majick1** [comment]
Did he ever fix the sprites?

**Comment by WarRage333** [comment]
Il fix the sprites in a different pr when i get round to it

**Pull request merged**
