### PR TITLE
[MIRROR] [Ready] [Reviewed] Nanites 2

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/37922
--------------------
:cl: XDTM
add: Added programmable nanites to science!
add: Science now has a nanite chamber, a nanite program hub, a nanite cloud console and a nanite programmer.
add: From the program hub you can download nanite programs (unlocked through techwebs) to disks.
add: You can then customize their functionality and signal codes through the Nanite Programmer.
add: The nanite chamber is necesary to inject nanites into a patient, and it's also used to install/uninstall programs into a patient's nanites. A second person is required to man the console.
add: The nanite cloud console controls remote program storage; it stores program backups that nanites can be synced to through cloud IDs.
add: Nanite programs range can be either helpful or harmful; their main potential is that they can be enabled at will through the use of remotes and sensors. The potential uses are endless!
add: More detailed information is available in the wiki.
/:cl:

We're back, now with components instead of reagents! Goodbye snowflake checks!
I took the chance to think about some criticisms about the potential op-ness on the last PR. 

First, the new setup means that to get/update nanites you need at the very least someone else to operate the console for you, meaning that a lone roboticist still needs to put himself at some risk during injection. Another option is to go for cloud-based nanites; meaning you don't need someone else every time you want a new program for your nanites, but on the other hand anyone can upload some bad stuff while you're not watching the cloud control console.

Second, i added a traitor item: the nanite hijacker. It will be available to all traitors, not just roboticists, and it will allow the user to upload programs remotely to nanited hosts. It will likely come with a kit with some disks. It _will_ need some tweaking, since it pretty much allows you to click on someone and watch them die if you have the right disks and they have nanites, which is a bit too harsh.

TODO list:
- Clean up some leftover chem-nanites code DONE
- Techweb integration DONE
- New sprites (Thanks MrDoomBringer and KomradeSpectre!) MOSTLY DONE
- Missing interfaces for the chamber DONE
- Cloud storage interface DONE
- Add some new types of programs NEVER ENOUGH
- Nanite-interactive gadgets and machinery (nanite detectors, and so on) MAYBE LATER
- <s>Convert existing nanites into this system if possible</s> Convert nanite chems into other stuff DONE
- Refactor GET_COMPONENT away DONE
- Add to roundstart map

### CODE REVIEW

**Comment by JohnGinnane** [comment]
\>science gets another cool feature

**Comment by GuyonBroadway** [comment]
>science gets another cool feature

Good, science needs some more fun after all thier nerfs.

**Comment by nalarmg** [comment]
CI failed. This needs looking into.

**Comment by GuyonBroadway** [comment]
Prolly cuz some unstaged additions to the dme.

**Comment by Carbonhell** [comment]
needs dme changes and tgui to be recompiled

**Comment by Carbonhell** [comment]
needs tgui recompile(could be done later though) and the metastation diffs to be applied to our map(the nanite lab)

**Comment by JohnGinnane** [comment]
gonna have a look at this now

**Comment by JohnGinnane** [comment]
This is ready to go, I only commited the updated tgui.json but I might have more trouble with tgui...

**Review by JohnGinnane — APPROVED** [review]

**Review by yoyobatty — APPROVED** [review]

**Comment by JessHorserage** [comment]
If you are stunned, how are you supposed to use the anti stun nanite?

**Comment by ghost** [comment]
voice activation nanites

**Comment by JessHorserage** [comment]
I realised that and got it to work, but whats the full proccess on giving myself a selection of nanite stuff if im on my own

**Comment by ghost** [comment]
1. Make cloud backup thing
2. Multitool a public nanite chamber board, and set the cloud backup ID
3. Make public nanite chamber
4. Get in public nanite chamber, close it, then click on it
5. Ta-da!

**Comment by JessHorserage** [comment]
MULTITOOL, AHHH! Cheers.

**Pull request merged**
