### PR TITLE
No more emote keybinds!

### PR DESCRIPTION
**Pull request by ghost**
:cl:
del: No more emote keybinds, except for scream and fart. Ya'll abused em.
/:cl:

### CODE REVIEW

**Comment by yoyobatty** [comment]
keep flipping and spinning in

**Comment by Manly-Dwarf** [comment]
SPEEDMERGE SPEEDMERGE SPEEDMERGE SPEEDMERGE
DO NOT KEEP FLIP AND SPIN

**Comment by Manly-Dwarf** [comment]
CRASHING ADMINS GAMES WITH EMOTES W T F

**Comment by ghost** [comment]
I AM CONFUSED

**Comment by Manly-Dwarf** [comment]
my logic is
scream and fart are both pretty spammy emotes that can get annoying, but if you spam them you either take oxy damage or lose your butt and can't fart any more
if you're gonna have spammy emotes that can do things like impact your sprite (i.e hitbox) then i am probably gonna mash a button furiously while in combat

**Comment by karmaisblackandbluepilled** [comment]
Keep flip and spin on, maybe clapping too. That doesn't crash it.

**Comment by Manly-Dwarf** [comment]
do not do it for the reasons i explained why

**Comment by SireTurret** [comment]
> Keep flip and spin on, maybe clapping too. That doesn't crash it.

why do you have such horrible sense of things that work and things that don't

**Comment by Manly-Dwarf** [comment]
steamport3
never ask me again why i don't trust tg prs, don't like upstream merges, and don't like the mirror bot

**Pull request merged**
