### PR TITLE
Ministation updates

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: wheezl
add: Updates ministation
/:cl:

## About The Pull Request
Wheezl basically paid me to make this PR

## Why It's Good For The Game
Map update lol

### CODE REVIEW

**Comment by wheezl** [comment]
+3 made some quality of life changes and did some shit to the AI sat yolo

**Comment by Zyzarda** [comment]
+2 needs more content

**Comment by MrEpicSax** [comment]
+1 merge

**Comment by carlopault** [comment]
+2

**Pull request merged**
