### PR TITLE
Deletes an abomination from the codebase

### PR DESCRIPTION
**Pull request by tortellinitony**
We don't allow ERP so there is no reason to have these in the codebase.

### CODE REVIEW

**Comment by Spacedong** [comment]
-1

**Comment by ghost** [comment]
-1

**Comment by PopNotes** [comment]
-1

**Comment by GuyonBroadway** [comment]
Dlidos are not about ERP, they are a saint's row-esque display of audacity and toilet humour.

**Comment by GuyonBroadway** [comment]
I disagree with this PR but the code is to standard.

**Review by GuyonBroadway — APPROVED** [review]

**Comment by WallaceShark** [comment]
-1.

**Comment by ghost** [comment]
they can be pretty funny, and are spawn-in only.

i'd rather they be kept.

-1

**Comment by ghost** [comment]
-1

**Comment by DinduStuffin** [comment]
+1
they're admin only and haven't been used like, at all in the past few days to my knowledge so I don't see much reason to keeping them around

**Comment by mlgdatboi** [comment]
-1 
Removing what started hippie will likely end it too kys

**Comment by j-mie** [comment]
Let's keep em. It's admin only.

**Pull request closed without merging**
