### PR TITLE
Monkey 2: my balls itch edition

### PR DESCRIPTION
**Pull request by ghost**
Now that https://github.com/tgstation/tgstation/pull/32431 has been merged, Monkey is much less OP.

:cl: Thefastfoodguy
add: Monkey is now re-enabled!
/:cl:

### CODE REVIEW

**Comment by dreamcrab** [comment]
im not thrilled about monkey, i will ask the lads if they want monkey or not but as it stands i dont really want it

my vote will be that of the players that are online when i ask this the next time i am on

**Comment by ghost** [comment]
i doubt making hardsuited people immune makes it much better at all
this something that players should decide really
but i cant really reccomend making it a mode agaim

**Comment by ghost** [comment]
monkey is revs but worse
if you want another conversion gamemode, gangs should be brought back

**Comment by ghost** [comment]
@dreamcrab Shouldn't a few monkey rounds be run during highpop to see how everyone like it?

@McBawbaggings PLZ NO GANGS

**Comment by PopNotes** [comment]
@McBawbaggings unless someone wants to do a serious remake of gangs, hell the fuck no

**Comment by dreamcrab** [comment]
i want gangs too

**Comment by ghost** [comment]
I actually have a monkeymode overhaul, just waiting for /tg/ to end their feature freeze

**Comment by ghost** [comment]
This does nothing, config is not managed from git

**Comment by ghost** [comment]
@Chnkr Actually, a while back, the server config was uploaded to git

**Comment by ghost** [comment]
@MoreRobustThanYou This literally does nothing, changing the config on git does not change the config on the game server.

**Comment by dreamcrab** [comment]
everyone hate the trial monkey run so im gonna say no -13

**Comment by ghost** [comment]
I will try this again once my monkey mode overhaul reaches /tg/

**Pull request closed without merging**
