### PR TITLE
SMES wiring change

### PR DESCRIPTION
**Pull request by AnthonyJNgo**
:cl:
tweak: Removes the Engineering SMES
fix: Changes the wiring for the main SMES so that singularity/tesla don't go instaloose
/:cl:

Removes the single SMES inside the singularity room. Changes the wiring so that the Singularity/Tesla/Supermatter will all power the four main SMES from the same wiring path and will also draw power from the same path. Roundstart power won't really be an issue because the Singularity emitters and computers won't draw enough power to drain anything unless someone actually goes there and starts setting it up and powers it on. This _should_ solve 2 issues.
#12195 and #11835 

The SMES removal is circled in red, the wiring change is circled in blue. A single wire is moved in the hallway between the SMES room and the Singularity room.

smesedit

edit: I forgot to run the map merger hook before I committed, however the mapping changes are the same. I'll commit a fix in just a minute.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
what is mapmerge

**Comment by AnthonyJNgo** [comment]
@steamp0rt Just reinstalled my OS slipped my mind that I didn't have my mapmerge hook installed. I'm downloading python now, give me like five minutes.

**Comment by ghost** [comment]
REEEEEEEEE fix your changelog so people actually know the SMES is fixed.

**Comment by yoyobatty** [comment]
Looks like you didn't map merge, read the wiki if you need to know how to do it

**Comment by AnthonyJNgo** [comment]
> Looks like you didn't map merge, read the wiki

@yoyobatty 
mfw you literally did not read the edit I made over an hour ago to the main post

**Comment by ghost** [comment]
Spicy

**Comment by AnthonyJNgo** [comment]
Alright I'm going to try something

**Comment by Maroonenahmoron** [comment]
Very nice, thanks for taking care of this, +1

**Pull request closed without merging**
