### PR TITLE
PYKOAI RETURNS

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Pyko, CZ
soundadd: fugg i'm de ai now :-DDDDD 
/:cl:

## About The Pull Request
s

## Why It's Good For The Game
peed

merg

### CODE REVIEW

**Comment by SireTurret** [comment]
+100000000000000000000000000000

**Comment by Manly-Dwarf** [comment]
SOUNDFILES YET TO BE CONVERTED:
Radiation Storm

**Comment by Manly-Dwarf** [comment]
going to speedmerge this because fuck it

**Comment by Maroonenahmoron** [comment]
Yes, +1

**Comment by mikolaj007** [comment]
needs to be louder

**Comment by G-erma** [comment]
Add a way to toggle between the "Improved" version and the old

**Comment by ghost** [comment]
>implying you'd want to listen to the old version

**Pull request merged**
