### PR TITLE
[MIRROR] Automatic deadminning

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42780
----------------------------
Automatically deadmins admins on certain roles, configurable via config options and client preferences.

todo;

- [x] make it better.
- [x] make it EVEN better.

### CODE REVIEW

**Review by yoyobatty — APPROVED** [review]
Thoughts @t-f-w @Lxtoofonea @Carbonhell

**Comment by Jujumatic** [comment]
deadmin someone if they're inactive for 1 day 😏

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by Maroonenahmoron** [comment]
+1

**Comment by Carbonhell** [comment]
It starts off by default so it can be merged already if that's the issue. Regarding the possibility of adding this system, dunno. It hasn't been an issue and i do play as security while adminning with no issues.
-1 from me.

**Comment by Lxtoofonea** [comment]
what carbon said spooked me a bit, so staying neutral for now

**Comment by DaydreamPuppeh** [comment]
On all head roles basically

**Comment by DaydreamPuppeh** [comment]
Also all antags

**Comment by Carbonhell** [comment]
On a second note, GAs would probably benefit from this, so +1

**Comment by Zyzarda** [comment]
Yeah cool +1

**Pull request merged**
