### PR TITLE
Adds new abandoned crate loot [READY]

### PR DESCRIPTION
**Pull request by yoyobatty**
Mirror of: https://github.com/tgstation/tgstation/pull/46906
https://github.com/tgstation/tgstation/pull/48300

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
dunno why travis is freaking out, this is a cool PR.

**Comment by mkikt4743** [comment]
+1 please merge already

**Comment by AnthonyJNgo** [comment]
Travis has been having strokes over the slightest things lately, not really sure what is up with that.

**Review by AnthonyJNgo — APPROVED** [review]
Literally just modifying possible items you can receive, this all looks good and is fine.

**Pull request merged**
