### PR TITLE
[MIRROR] Clown Ops

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/36459
--------------------
Addresses #36418

clownops

### CODE REVIEW

**Comment by Jujumatic** [comment]
YES

**Comment by Manly-Dwarf** [comment]
It took this long for "clown ops" to happen and yet it's just a reskin of nuke ops weapons and Goonstation item theft.

**Comment by tortellinitony** [comment]
# Requires #7017

**Comment by ghost** [comment]
Pretty cool +2.65

**Comment by JohnGinnane** [comment]
\>voting on mirrors
🤔

**Comment by Pyko1** [comment]
lets see if just restarting the travis jobs is enough

**Comment by JohnGinnane** [comment]
Nah the issue is this PR was opened before a previous one was merged, so it's trying to put in those changes even but it's kinda broken. I'm fixing it now though

**Pull request merged**
