### PR TITLE
Adjust bee

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: The beebox now starts in a crate in botany. A queen bee and some honey frames are now also included
/:cl:

### CODE REVIEW

**Comment by yoyobatty** [comment]
This is an obvious balance change and feature creep disguised as a fix, please don't add stuff like queen bees to the map because you want to powergame botany or are too lazy to order shit from cargo.

**Comment by ghost** [comment]
@yoyobatty I would've added this in the first place, but I thought beebox/premade came with a queen bee

anyways I DID put it as `tweak` and not `fix` in the CL

**Comment by ghost** [comment]
"tweak"...

this is an add, mein negro. +1 once you change the changelogs, bees are nice. If they're too stronk we'll revert.

**Comment by ghost** [comment]
Closed in favor of https://github.com/HippieStation/HippieStation/pull/12267

**Pull request closed without merging**
