### PR TITLE
Removes the Credit Roll

### PR DESCRIPTION
**Pull request by AliiTea**
Removes the Credit Roll at round end.

### CODE REVIEW

**Comment by AliiTea** [comment]
fuck.

**Comment by bardofrage** [comment]
yes please

**Comment by DinduStuffin** [comment]
+1
how the hell did this even get merged

**Comment by tortellinitony** [comment]
do it right

**Comment by GuyonBroadway** [comment]
-1 we just need McBawbaggins or someone to run creditstool.exe serverside to change the credits to include our own people.

**Comment by ghost** [comment]
just ran it on the live server, hopefully that should work?

**Comment by GuyonBroadway** [comment]
It should! Unless we forgot to change its config to point to hippiestation.  And the thing is due to upstreams and whatnot i think it might display some tg guys anyway.

**Comment by j-mie** [comment]
Yeah, don't do this.

1) We already are using the contributors from the HippieStation repo, but because we are using /tg/ code it picks up /tg/ contributors too.
2) You're completely breaking the modular system here, If you really want to remove it untick the credits.dm file in our DME.
3) I don't see any reason to remove it, it doesn't make round end last any longer.

**Pull request closed without merging**
