### PR TITLE
Fixes stun nettles

### PR DESCRIPTION
**Pull request by mikolaj007**
## Changelog
:cl: Mideanon
fix: Stun nettles now work like stun batons with 1-3 uses, 5 - 25 damage and stun duration based on potency
/:cl:

## What this does:
basically stun nettles now work like stun batons, but always on, dont deal 15 damage and have between 1-3 uses depending on potency
~~removes stun nettles. there are missing sprites for the plant itself and DNA machine modified seed. I dont actually care enough about them to sprite.~~
found and crushed the fucking bug that prevented the sprites from showing up
YEEEEEEEEEEEEEEEEEET

## Why It's Good For The Game

Stun nettles were never actually used, were incomplete if i remember correctly and mostly caused salt when trying to get death-nettles.

### CODE REVIEW

**Comment by Jujumatic** [comment]
Make them like stun batons

**Comment by mikolaj007** [comment]
hmm, alright. that might actually make them usefull. ill also add an option for them to be mutated into death and back

**Comment by Eagle-Eyess** [comment]
It be cool if they were a one time use item. Stun nettles being able to always stun would be a little broken as theyd be a straight upgrade to the stun gun and baton alike.

**Comment by mikolaj007** [comment]
1 use per 20 potency to limit them.

**Comment by Eagle-Eyess** [comment]
5 uses is still a lot, id say three at max and thats even stretching it. remember one hit is plenty of time to cuff a person or even just kill them.

**Comment by mikolaj007** [comment]
the commit right before the killing should work properly. only the sprites are missing.

**Comment by Manly-Dwarf** [comment]
uh okay

**Comment by Lxtoofonea** [comment]
+1

**Pull request merged**
