### PR TITLE
Unfucks nullrod

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
balance: Reverted nullrod nerf but removed anti-magic component and no drop trait.
/:cl:

## About The Pull Request
This removes the nullrod nerf we did that essentially just reskinned. However, TG also decided to add the anti-magic component which was dumb because chaplain now has it. Since anyone can use nullrod it makes you op against wizards and cults which I think should not be allowed. I also removed the no-drop trait for the godhand, armblade and chainsaw because manly requested it.

## Why It's Good For The Game
Again, I wanted to have the null rod have it's own unique abilities but the anti-magic and no drop trait on other stuff was putting into slightly op territory.

### CODE REVIEW

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by ghost** [comment]
anti magic is pretty cool against wizard, really varies shit up, but make it only for the chaplain if he wears chaplain suit + has holy water inside him + holds null rod

**Comment by biggiOS** [comment]
+1

**Comment by yoyobatty** [comment]
So nautilus did a pr which I think is better because they left antimagic trait in. The reason I took it out on this pr is because manly told me the chaplains antimagic ability pr was merged.

**Pull request closed without merging**
