### PR TITLE
[MIRROR] Antag directory reshuffling. And some minor fixups/renames.

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34886
--------------------
- Moves all antag code to modules/antagonist.
- Gamemode dir should only contain gamemode related code. (Eventually axed)
- Renames get_antagonists to get_antag_minds

### CODE REVIEW

**Comment by Pyko1** [comment]
This is going to be such a fun to fix...

**Comment by ghost** [comment]
-1

**Comment by JohnGinnane** [comment]
This will take a little time to go through

**Comment by Carbonhell** [comment]
holy fuck everything conflicts
run

**Comment by JohnGinnane** [comment]
Okay this isn't going to work because this PR was created before https://github.com/HippieStation/HippieStation/pull/6031 was merged so it's missing lots of critical information so I'm going to create a new branch to try and re-do this

**Pull request closed without merging**
