### PR TITLE
Adds a new roundend sound

### PR DESCRIPTION
**Pull request by ghost**
shamlessly ripped off the discord

### CODE REVIEW

**Comment by PopNotes** [comment]
>.wav

also credits to jaykin bacon

**Comment by GuyonBroadway** [comment]
Fucking postal is a top lad.

**Comment by PopNotes** [comment]
export the file as an ogg you dipshit

**Comment by ghost** [comment]
@PopNotes SS13 can play WAVs

**Comment by PopNotes** [comment]
@MoreRobustThanYou bad etiquette, ogg it bls

**Comment by ghost** [comment]
@PopNotes fixed

**Review by ghost — DISMISSED** [review]
Code OK

**Comment by KayeArray** [comment]
+1

**Comment by PopNotes** [comment]
build this

**Comment by ghost** [comment]
+1

**Review by JohnGinnane — APPROVED** [review]
🔈 🆗

**Comment by Arzion5** [comment]
Good nightrogen, sleep tightrogen. +1

**Comment by 2Dollarbill** [comment]
ok. +1

**Comment by dreamcrab** [comment]
sure +6

**Comment by ghost** [comment]
merge, this got +3 @HippieStation/maintainers

**Pull request merged**
