### PR TITLE
Spacemen no longer take a ritual bite out of an organ before inserting it during surgery

### LINKED ISSUE #11492: Make organs inedible
You insert the liver into Darren Rowley's chest.
You bite the liver.
You can taste iron.
That didn't taste very good...

You insert the cybernetic liver into Darren Rowley's chest.
You hungrily nibble the cybernetic liver.
You can taste iron.
That didn't taste very good...

After an accident with superhol i went to try to self surgery replace my liver but when it finished putting it in i bit into it, rendering it unusable for surgery.

In general just make organs inedible so surgery does not get cucked.

guess this is also an issue since i dont know whats up with eating organs after completing a step

### PR DESCRIPTION
**Pull request by ghost**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
fix: Fixes spaceman hunger rendering self-surgery organs unusable.
/:cl:

## About The Pull Request

drunkards can now fix their liver damage without having to interact with medbay autists. Fixes #11492 .
## Why It's Good For The Game

gay shit cunt ass

### CODE REVIEW

**Comment by WarRage333** [comment]
speed merge just get one maintainer to check is code good

**Review by ghost — APPROVED** [review]
not a maintainer but lgtm

**Review by yoyobatty — APPROVED** [review]
Is this old code?

**Comment by ghost** [comment]
@yoyobatty nah

**Comment by WarRage333** [comment]
DOES NOT WOOOOORK 

yeah even when pullings things out you attack your self

and organs still get eaten

**Pull request merged**
