### PR TITLE
Ports sheet solidification.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: Guyonbroadway
add: Iron, Silicon, Uranium, Plasma, Gold, and Silver can all be solidified with 5u pyrosium, 5u cryostylane and 20u of the pertinent chem.
balance: Banana Juice can be made into bananium but it takes 80u as opposed to 20u.
fix: The plastic sheets recipe now makes sheets based on how much of the chems you used in the reaction as opposed to just making a flat 10 sheets. 
/:cl:

[why]: Old codebase port.

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
to those who might worry that this might make science too stronk, do remember that most cool science stuff needs titanium, diamond and bluespace mesh these days which cannot be obtained via these recipes. 

I nerfed bananium a little because the cargo value is immense.

**Comment by PopNotes** [comment]
yes

**Comment by KayeArray** [comment]
pls use cryogenic fluid to shill my memes

**Comment by GuyonBroadway** [comment]
It was this way prebase even when we had cryofluid.

**Comment by ghost** [comment]
thought i posted on this
never was a fan of the solidification recipes primarily due to honk cooler allowing honk mechas near every round

**Comment by GuyonBroadway** [comment]
I thought of that and make bananium have a one in four chance of spawning a banana instead. 

I can tweak that value too if need be.

**Comment by KayeArray** [comment]
i'm mixed considering how buffed sci/chem are right now

**Comment by GuyonBroadway** [comment]
Again, most of the shit you can get needs titanium, diamonds and bluespace mesh anyway. All this means is that if you get autistic with a botanist you could bypass mining for minerals and very slowly at that.

**Comment by GuyonBroadway** [comment]
Should have said for SOME minerals.

The only minerals you can combobulate exist on the station in small quantities at roundstart anyway.

**Comment by KayeArray** [comment]
have you seen the shit Eris does?

**Comment by GuyonBroadway** [comment]
If its the duping solid chembars that's due to a bug, its not really fair to balance around unintended behaviour.

**Comment by KayeArray** [comment]
Yes but I'm still concerned about the powercreep even when solid chem duping is fixed and smoke machine is removed

**Comment by GuyonBroadway** [comment]
It wasn't really powercreepy prebase and that was when R&D was easier to do.

**Comment by GuyonBroadway** [comment]
The worst I ever saw of it prebase was Dr.Malachi using the silver to upgrade the cloning machines.

**Comment by Pyko1** [comment]
Honestly i think around 100 to 1k  bananajuice should equal to 1 bananium, and have a recipe to convert them around.

**Comment by Pyko1** [comment]
so you can mass bananas and cheese clowns juice to make bananium, but its hard coded amount and itentional

**Comment by tortellinitony** [comment]
Use frost oil like plasma does or integrate this with the chem states of matter thing instead

**Comment by GuyonBroadway** [comment]
I changed it from frost oil because old codebase recipe.

**Comment by tortellinitony** [comment]
why

**Comment by GuyonBroadway** [comment]
It wound't really be an old codebase feature if I changed it too much. Plus frost oil is a bitch to get even on a good day.

**Comment by tortellinitony** [comment]
yeah you need botany there's a reason. This makes it super easy

**Comment by GuyonBroadway** [comment]
Making it rely on botany is about as good as never on a server like this. We had it prebase and it was hardly an issue besides the tide of honks which I can fix by making that recipe less efficient.

**Comment by tortellinitony** [comment]
Pretty sure they added gold solidification so you have to change that too

**Comment by GuyonBroadway** [comment]
Dunno if they did but I will check, in any case I did test this and it worked nice and runtime free.

**Comment by GuyonBroadway** [comment]
Seems they did add solid gold, all this means is I can cut some code out.

**Review by ghost — DISMISSED** [review]
Please do something about the ungodly amount of whitespace in this PR

**Review by ghost — DISMISSED** [review]

**Comment by GuyonBroadway** [comment]
Nerfed the bananium recipie in a less silly way.

**Review by ghost — APPROVED** [review]
die honkbot

**Comment by ghost** [comment]
+1

**Comment by KayeArray** [comment]
mme +1

**Comment by bardofrage** [comment]
+1

**Pull request merged**
