### PR TITLE
Revert "[MIRROR] [s] Prevents a certain kind of antag-rolling abuse."

### PR DESCRIPTION
**Pull request by ghost**
Reverts HippieStation/HippieStation#11553

### CODE REVIEW

**Comment by k-k-karma** [comment]
+1, why would we want people to just suicide instead of letting them antag roll? just make it so people can metagrudge people who antag roll because they're always antag when they spawn and the problem will solve itself.

**Comment by yoyobatty** [comment]
This doesn't fix anything. The most I'm going to accept is if you remove the admin message.

**Comment by Manly-Dwarf** [comment]
hahahahahahahahahahahahah

**Comment by AnthonyJNgo** [comment]
Going to -1 because I am against encouraging antag fishing. You either play the game and get a chance at antag, or you don't play.

**Comment by ExpAntique** [comment]
-1

**Comment by DaydreamPuppeh** [comment]
-1

**Comment by lunaman22** [comment]
it's banned anyway so why do you want it back?
want to get antag when no admins are on hmmmm

**Comment by NautilusViper** [comment]
-1 no

**Comment by ghost** [comment]
stupid

**Pull request closed without merging**
