### PR TITLE
Changes some map related things

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: Add Engineering access requirements to Engineering SMES'
add: Added wire nodes to the vault glass windows
add: Added more fire alarms around the station
add: Added latex gloves to chemistry
fix: Fixed an unconnected pipe in science maint
fix: Removed an unconnected air vent in armory
fix: Fixed camera in research division and re-added a cam to circuitry lab
tweak: Robust doors now have same security levels (6) as sec and command doors.
/:cl:

[why]: Please tell me what you think of these changes. I also removed the pixel_x/y = 0 lines.

### CODE REVIEW

**Comment by Carbonhell** [comment]
God bless. +1

**Comment by Carbonhell** [comment]
ready?

**Comment by yoyobatty** [comment]
Yes sir

**Comment by HippieBartels** [comment]
+1

**Comment by yoyobatty** [comment]
@t-f-w

**Comment by earthmoonjune** [comment]
+1

**Review by TDcoolguy300 — APPROVED** [review]
Sure

**Pull request merged**
