### PR TITLE
Blacklists mime's cats from pictures

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
fix: Mime's cat has been blacklisted from pictures, preventing players from using them as invisible box disguises
/:cl:

[why]: Big oof

### CODE REVIEW

**Comment by yoyobatty** [comment]
To be honest, it might be better to upstream this and make this a blacklisted typecache/list but whatever, I'll keep the snowflake code until it's necessary,

**Review by GuyonBroadway — APPROVED** [review]
Code gud but this is a balance change really. Needs hedminns

**Comment by yoyobatty** [comment]
I'm pretty sure this was an unintended feature but I guess I'll tag it

**Comment by bardofrage** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Pull request merged**
