### PR TITLE
[MIRROR] Prevents soviet and capitalist golems from being eligible in random golem choices

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42867
----------------------------
:cl:
tweak: Soviet and Capitalist golems no longer appear in opportunities where a random golem species was selected, primarily golem mutation toxin.
/:cl:

This PR is necessary because of the stupid conversion meme golems that immediately hijack any round they sneak their way into. Intended as an admin only feature entirely and ended up sneaking through anyways through several loopholes. This closes the last remaining loophole that I'm aware of. To briefly describe it, strange seeds can get the golem mutation toxin, which randomly chooses *any* golem race, including the soviet golem and capitalist golem. IIRC it's also available with some obscure xenobio fuckery I can't be arsed to explain. 

You could call this a nerf but it's ridiculously niche and fixing a completely unintended balance consequence so I'm not going to bother arguing about what tag this PR gets.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
To anyone who wants to merge this, Soviet & Capitalist Golems are actually invisible in-game. They're totally bugged.

**Comment by Jujumatic** [comment]
probably something to do with icon states being overridden by hippie icon states

**Review by ghost — APPROVED** [review]
Yeah nah she'll be right

**Comment by ghost** [comment]
@Manly-Dwarf we'll just make a new PR for the icons if need be

**Pull request merged**
