### PR TITLE
make slimes eat a little faster

### PR DESCRIPTION
**Pull request by xTrainx**
[Changelogs]: # slime will now eat faster

:cl: xTrainx
tweak: slime will now eat faster, and get more nutrition
/:cl:

[why]: # got some request from user to make xenobio a bit more viable since round here tends to laST 30 minutes, so slime will now eat faster, reducing downtime when farming slimes

### CODE REVIEW

**Comment by ghost** [comment]
FUCKING MODULARIZE IT

**Comment by ghost** [comment]
You've made changes to /tg/ files, please mark these changes.

**All modifications to non-hippie files should be marked.**

- Multi line changes start with `// hippie start` and end with `// hippie end`
- You can put a messages with a change if it isn't obvious, like this: `// hippie start - reason`
  - Should generally be about the reason the change was made, what it was before, or what the change is
  - Multi-line messages should start with `// hippie start` and use `/* Multi line message here */` for the message itself
- Single line changes should have `// hippie` or `// hippie - reason`

If you need to mirror a file, or function into a hippie-specific file, please leave behind a comment stating where it went.

```
// hippie start - Mirrored this function in <file> for <reason>
bunch of shitcode here
// hippie stop
```

Once you mirror a file, please follow the above for marking your changes, this way we know what needs to be updated when a file has been mirrored.

**Review by ghost — APPROVED** [review]
Code OK, needs @HippieStation/head approval

**Comment by xTrainx** [comment]
but why tho

**Comment by xTrainx** [comment]
@Chnkr this was not a mirror pr

**Pull request closed without merging**
