### PR TITLE
roundstartcatbeasts

### PR DESCRIPTION
**Pull request by ghost**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Catbeasts playable roundstart
/:cl:

## About The Pull Request
Players can choose to be a catbeast at the beginning of a round.

## Why It's Good For The Game
Give eccentric players the roundstart role they never knew they wanted.

### CODE REVIEW

**Comment by Pyko1** [comment]
+1ish with some changes how catshits work all together.

Could use some other changes as well, such as updates on rules releated to catshits dunking and what catshits can do.
As well as possibly, removing/lessening the genetic defects to make catshits at least somewhat challenging game.
Also ensuring that catshits can not be antags, no matter what. You have to make a choice to be a bait dunking dunkers, or a real antag.

I mean you are already guaranteed a a jump on them, do you really need them to be also geneticalyl utterly defective as well?

**Comment by carlopault** [comment]
-2 barackosama is trying to convert Hippie to furry MRP this is the start of something horrible dont do it

 > I mean you are already guaranteed a a jump on them, do you really need them to be also geneticalyl utterly defective as well?

Yes they need to be utterly defective at everything do you hear yourself smh Pyko is a  furry supporter just like Barack

**Comment by illusineer** [comment]
> -2 barackosama is trying to convert Hippie to furry MRP this is the start of something horrible dont do it
> 
> > I mean you are already guaranteed a a jump on them, do you really need them to be also geneticalyl utterly defective as well?
> 
> Yes they need to be utterly defective at everything do you hear yourself smh Pyko is a furry supporter just like Barack

stfu hoe I am a TransFur TransFur deez nuts onto your momma head xDDDDDD U HAVE BEEN OWNED

**Comment by AnthonyJNgo** [comment]
Failed to gather enough votes, also catbeast is a punishment mutation.

**Pull request closed without merging**
