### PR TITLE
ERTs no longer stop the round from ending

### PR DESCRIPTION
**Pull request by ghost**
:cl:
fix: ERTs no longer stop the round from ending
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
lame

**Review by yoyobatty — COMMENTED** [review]
Is there an explanation as to why it happens, and how does this line of code fix it?

**Comment by ghost** [comment]
@yoyobatty Gamemodes will check to see if all the antags are dead to see if it can end the round, if the gamemode is non-continuous, by looping through antag datums. However, if an antag datum has `prevent_roundtype_conversion` set, it will be ignored.

**Comment by Manly-Dwarf** [comment]
ERT feels kinda dull honestly. The only times they get sent in is when antagonists are boning, they're not useful any time else. ERT Engineers have worse equipment than the CE or antagonists, or even the holotool if my memory is correct. ERT Medical Doctors blow themselves up 9/10 times. Security Officers are just that and Commanders are not whitelisted and guaranteed to be idiots as a result. Everyone splinters up and tries to fuck up the antagonist, then calls the shuttle because they don't have cloners or anything that might let the round resume, that or I give them the nuke codes and tell them to end it that way.

Ideally I'd want to see the ERT ship get some more stuff, or make ERT a big more meaningful and quick, able to take on situations like plasmafires and get the round back in motion, rather than just being round-enders for lame murderboners.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
