### PR TITLE
Added new roundend sound

### PR DESCRIPTION
**Pull request by JohnGinnane**
:cl: JohnGinnane
soundadd: Added a new roundend sound
/:cl:

I think this is by the same guy who does the "I wonder what would happen if I lit in a match in a room full of nitrogen". I found this on facepunch somewhere

### CODE REVIEW

**Comment by Jujumatic** [comment]
is there a way for me to hear the sound? i can't seem to find where i can do that

**Comment by JohnGinnane** [comment]
If you download it and then open it in VLC

**Comment by ghost** [comment]
+1

**Comment by Pyko1** [comment]
sure, why not

**Pull request merged**
