### PR TITLE
Adds a new hat, the turban

### PR DESCRIPTION
**Pull request by Jujumatic**
I added a turban to the list of hats and put it in the clothesmate - it assigns an alternate scream sound whenever you are wearing it.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
is this in bad taste? 🤔

**Comment by Jujumatic** [comment]
maybe - some random guy asked for it lol

**Comment by praisenarsie** [comment]
got a feeling that 'some random guy' was yourself

**Comment by Jujumatic** [comment]
actually it was not. but i liked the idea when i heard about it, and i wanted to give a shot at making a new item

**Comment by Pyko1** [comment]
I have been wanting a turban for a while, but its not only that, its also a loin cloth uniform, a melee weapon when wet, or wrapped around a soap as well as high tech liquid absorption device.

aka a towel.

**Comment by ghost** [comment]
I don't see how it'd be in bad taste if it's literally just a turban hat.

**Comment by Carbonhell** [comment]
>another allah meme
no -1

**Comment by Manly-Dwarf** [comment]
Gonna have to agree with carbonhell that we already have a pretty good allah meme in the form of the Execution Sword.

It just feels low effort, especially by not having the item be tied to the Chaplain.

**Comment by Jujumatic** [comment]
i just got sprites for this. will update the branch soon.

if this thing gets merged i'll expand on it by adding the towel shit and crafting stuff for it

**Comment by Jujumatic** [comment]
sprites have been added, this is ready to merge

**Comment by Pyko1** [comment]
I have no complaint against more hats +1

**Comment by ghost** [comment]
I'd associate turbans with sikhs more so than muslims :thinking:
there's even a jewel in this one

**Comment by ghost** [comment]
we need this

**Comment by JohnGinnane** [comment]
@Jujumatic when you get time can you post pics? @Carbonhell are you sure -1 on this? what does this mean to the PR

**Comment by Carbonhell** [comment]
basically what kbb said, it's just a low effort allah meme, do we really need it?I'd be fine with the hat only,but the sound too seems meh

**Comment by Jujumatic** [comment]
sound is easy to remove if yall dont like it so i have no problem with it

**Comment by Jujumatic** [comment]
is the description ok as well? if not i can change it to a sikh prayer because that's what i did for the current description, but i want to keep that kind of shitty joke in place

**Comment by Jujumatic** [comment]
image

image

image

image

**Review by JohnGinnane — APPROVED** [review]
looks great

**Comment by Carbonhell** [comment]
eh sure for me,+1

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
