### PR TITLE
[MIRROR] fixes clown suit datum runtime

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43484
----------------------------
ahem fuck jannies

### CODE REVIEW

**Review by yoyobatty — APPROVED** [review]

**Comment by Jujumatic** [comment]
```code/modules/clothing/under/jobs/civilian.dm:126:error: /datum/component/squeak/bikehorn: undefined type path```

**Comment by yoyobatty** [comment]
The push Travis build is not using the latest master to compare this build to so it fails, it's the pr Travis we care about.

**Comment by Jujumatic** [comment]
is there any way we can get travis push to update then...

**Comment by yoyobatty** [comment]
No, I'll just merge it

**Pull request merged**
