### PR TITLE
Power Gloves

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Added Power Gloves, for 8TC. They zap people, using power from whatever power line you're standing on. (not) UNLIMITED POWAH!!!
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
it'd be cooler if the effects of the shocks changed with how much power was actually in the engine
so, you know
it doesn't have to be 12 TC and it encourages engies to actually set up the engine instead of releasing it

**Comment by Manly-Dwarf** [comment]
yeah i dunno this item is kinda boring in its current state
it has the potential but its not being utilized, its just another traitor item that people will use for maybe a couple of seconds and will forget about

**Comment by TrickyDickRichard** [comment]
this is NOT the stun gloves, so it is NOT epic

**Comment by ghost** [comment]
> it'd be cooler if the effects of the shocks changed with how much power was actually in the engine
> so, you know

the damage does -- this uses the same proc as being electrocuted by a grille

**Comment by karmaisblackandbluepilled** [comment]
We don't have that /tg/ "fix" to shocks limiting max damage to 90 yeah? So in theory you could instakill someone with this? If so, +1.
Otherwise, no.

**Comment by ghost** [comment]
@karmaisblackandbluepilled looking at the code, it's capped so it can't insta-kill. but you'd require some serious power-fu to reach said cap.

**Comment by karmaisblackandbluepilled** [comment]
that is fugging gay, I should do a pr to remove the cap
also
Capture

**Comment by ghost** [comment]
The cap is 195.

**Comment by karmaisblackandbluepilled** [comment]
oh, that's basically death anymore. I thought it was like /tg/ that capped it to 90

**Comment by ghost** [comment]
how about u make it able to "charge"  metallic surfaces,  airlocks,  walls,  items making them shock you when interacted with and throw weak tesla beam when thrown water over?? 
also animated lightning-y overlay ala freon or blood but a gif

**Comment by diegoxt45** [comment]
i like the power glove, it's so bad.

**Comment by mkikt4743** [comment]
meh there is too many traitor items and not enough traitors using them, also this is a one-hit kill if you set up engine right, -1

**Comment by ghost** [comment]
marking as DNM until i rework these

**Comment by AnthonyJNgo** [comment]
+1 for the idea and concept, going to deny PR since you're actively working on it. Just make a new PR and reference this one when the time comes.

**Pull request closed without merging**
