### PR TITLE
Ports air-turfs subsystem from Citadel

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

:cl: deathride58
tweak: Active turf processing is now its own subsystem.
/:cl:

## About The Pull Request
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/7509 nice

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
if it works

**Comment by yoyobatty** [comment]
Been tested, will be worth it

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 265560b95ab40f7bb315342bbdde8109f276dd95
Pull Request: 45ac37aff4a328b21151268872d4384a9806c446
Server: 56a4521021db782d9c2d4e6b490c4c4d3cd1a071

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: d41998c59f63249a3afceed5ec6a21d89342b536
Pull Request: 882dbea9b4754aeb808c38a66ebcd78387d71fcf
Server: 89a47853bc4c816228cdaf6744c7a02008acf7d7

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 3000452717e9eaf3152e0280c0a0d8393255861c
Pull Request: 882dbea9b4754aeb808c38a66ebcd78387d71fcf
Server: f7d46e683ec8cf2ed7186755da30d0f51110ef39

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 3000452717e9eaf3152e0280c0a0d8393255861c
Pull Request: 882dbea9b4754aeb808c38a66ebcd78387d71fcf
Server: 16bd4d6f35c089500686e67f9667100449567dc7

**Comment by epicss13gamer** [comment]
EWWWWWWWWWWWWWWWWWWW GET THE FUCK OUT CITADEL PLAYER HAHA YOYOBATTY IS A GAY CITADEL FURRY HOW ELSE WOULD HE KNOW ABOUT IT YOYOBATTY CITADEL PLAYER CONFIRMED  
2019

**Comment by epicss13gamer** [comment]
EWWWWWWWWWWWWWWWWWWW GET THE FUCK OUT CITADEL PLAYER HAHA YOYOBATTY IS A GAY CITADEL FURRY HOW ELSE WOULD HE KNOW ABOUT IT YOYOBATTY CITADEL PLAYER CONFIRMED
2019

**Comment by epicss13gamer** [comment]
EWWWWWWWWWWWWWWWWWWW GET THE FUCK OUT CITADEL PLAYER HAHA YOYOBATTY IS A GAY CITADEL FURRY HOW ELSE WOULD HE KNOW ABOUT IT YOYOBATTY CITADEL PLAYER CONFIRMED
2019

**Comment by epicss13gamer** [comment]
EWWWWWWWWWWWWWWWWWWW GET THE FUCK OUT CITADEL PLAYER HAHA YOYOBATTY IS A GAY CITADEL FURRY HOW ELSE WOULD HE KNOW ABOUT IT YOYOBATTY CITADEL PLAYER CONFIRMED
2019

**Comment by epicss13gamer** [comment]
EWWWWWWWWWWWWWWWWWWW GET THE FUCK OUT CITADEL PLAYER HAHA YOYOBATTY IS A GAY CITADEL FURRY HOW ELSE WOULD HE KNOW ABOUT IT YOYOBATTY CITADEL PLAYER CONFIRMED
2019

**Comment by epicss13gamer** [comment]
EWWWWWWWWWWWWWWWWWWW GET THE FUCK OUT CITADEL PLAYER HAHA YOYOBATTY IS A GAY CITADEL FURRY HOW ELSE WOULD HE KNOW ABOUT IT YOYOBATTY CITADEL PLAYER CONFIRMED
2019

**Comment by epicss13gamer** [comment]
EWWWWWWWWWWWWWWWWWWW GET THE FUCK OUT CITADEL PLAYER HAHA YOYOBATTY IS A GAY CITADEL FURRY HOW ELSE WOULD HE KNOW ABOUT IT YOYOBATTY CITADEL PLAYER CONFIRMED
2019 AND NOW HES DELETING MY CONFIRMATION COMMENTS WOW LMAOOOOO

**Comment by epicss13gamer** [comment]
EWWWWWWWWWWWWWWWWWWW GET THE FUCK OUT CITADEL PLAYER HAHA YOYOBATTY IS A GAY CITADEL FURRY HOW ELSE WOULD HE KNOW ABOUT IT YOYOBATTY CITADEL PLAYER CONFIRMED
2019 AND NOW HES DELETING MY CONFIRMATION COMMENTS WOW LMAOOOOO

**Comment by epicss13gamer** [comment]
EWWWWWWWWWWWWWWWWWWW GET THE FUCK OUT CITADEL PLAYER HAHA YOYOBATTY IS A GAY CITADEL FURRY HOW ELSE WOULD HE KNOW ABOUT IT YOYOBATTY CITADEL PLAYER CONFIRMED
2019 AND NOW HES DELETING MY CONFIRMATION COMMENTS WOW LMAOOOOO

**Comment by epicss13gamer** [comment]
EWWWWWWWWWWWWWWWWWWW GET THE FUCK OUT CITADEL PLAYER HAHA YOYOBATTY IS A GAY CITADEL FURRY HOW ELSE WOULD HE KNOW ABOUT IT YOYOBATTY CITADEL PLAYER CONFIRMED
2019 AND NOW HES DELETING MY CONFIRMATION COMMENTS WOW LMAOOOOO

**Comment by ghost** [comment]
Constructive criticism and feedback, positive or negative, is 100% allowed.

Constantly shitting up PRs, or spamming, is not allowed.

**Comment by ghost** [comment]
Seriously this is almost as bad at posting crap a PR for the sole purpose of "tg bad huehuehue"

**Comment by DON-KARMA** [comment]
>porting from citadel

write your own code instead of stealing furry code idiot

**Comment by ghost** [comment]
@DON-KARMA most of ss13 is stolen code ya nimrod

**Comment by karmaisblackandbluepilled** [comment]
after all, all your code is stolen karma

**Comment by yoyobatty** [comment]
Gotta love how the community has devolved so hard it leaks out into the one place we can atleast pretend to be professional.

**Comment by ghost** [comment]
#### Test Merge Removed

**Pull request merged**
