### PR TITLE
PDA Overhaul 2.0

### PR DESCRIPTION
**Pull request by TungstenOxide**
🆑
tweak: Added a few html snippets to change the font of the PDA
tweak: Added a few html snippets to remove bullet points and underlines from PDA menus
tweak: Made all PDA icons transparent so that the color change would actually affect them
add: some PDA icons
add: option to cycle through three different fonts for the PDA
add: option to change color to literally whatever you want
/🆑

[why]:
Cleaning up the PDA and making it look a little nicer and more authentic. So, A E S T H E T I C . Also, added some customization options. HMU if you have a suggestion for a new font.

### CODE REVIEW

**Comment by j-mie** [comment]
picture please :)

**Comment by TungstenOxide** [comment]
Sure thing, I just have to fix my build after whatever the hell happened last night.

**Comment by TungstenOxide** [comment]
@JamieH Here's a gif.

https://imgur.com/a/yz5P6

**Comment by ghost** [comment]
Not modular

**Comment by GuyonBroadway** [comment]
He's trying to merge this upstream now, may have to close this PR soon enough.

**Pull request closed without merging**
