### PR TITLE
Syrup

### PR DESCRIPTION
**Pull request by Spankmaster1066**
[Changelogs]: # Adds "lean" chemical
Adds drinking glass sprite for lean
Adds ogg for lean drinking (perhaps should be changed to local only)
Adds lean sprite

[why]: # So a nigga can sip

### CODE REVIEW

**Comment by KayeArray** [comment]
a very lean pr

**Comment by ghost** [comment]
i was gonna say "please fix the changelog" until i saw the conflicting files and then the amount of commits.

how

**Comment by Spankmaster1066** [comment]
I'm not sure what's going on here.

**Comment by Spankmaster1066** [comment]
why is this happening to me :(

**Comment by praisenarsie** [comment]
@Spankmaster1066 update your repo, smelly boy

**Comment by KayeArray** [comment]
gonna go ahead and close this so spank can make a new pr when he's ready

**Pull request closed without merging**
