### PR TITLE
Adds lots of nice plants to the map.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
add: Nanotrasen has received reports that the crews mental state has reached unacceptable levels of instability and has taken steps to do something about it. We could have spent money on professional psychiatrists to help all of you resolve your mental health issues but we instead spent about a tenth of that on a bunch of artificial plants and plants make everyone less stressed right?
/:cl:

[why]: Back in ye olde days of hippie we had a shittone of potted plants all over the station and they looked real nice. I just put a bunch of "random" plants in various spots so every round there will be different flowers all over the station.

Plus you can pick them up and hide under them a shit which is neat. 

Pics

image
image
image
image
image
image
image
image
image

This isn't a complete set of pictures but you get the general idea.

For the most part they are in various corners, dotted around places that are supposed to be for people and there is at least one in every office, bar the captain who gets three.

### CODE REVIEW

**Comment by PopNotes** [comment]
I like the idea but there's a pretty big issue with plants, never mind the fact that they're fairly haphazardly placed here (they should really only ever sit in corners)

They make hiding way, way too easy with the way they work. Infinitely moreso than lockers. This is just overall bad for everybody involved. Now on the other hand if you wanted to add Goonstation style plants that you can shake for goodies and sort-of-kind-of hide behind by walking over them, THAT I would approve.

**Comment by Blute1** [comment]
remove the plants in front of tool storage, bar shouldn't have any plants, its a bar not a restaurant. remove the ones in front of the bridge side windows, i'd lessen the escape ones as well

**Comment by Blute1** [comment]
like no offense but what were you thinking putting them here lol

**Comment by PopNotes** [comment]
trying to avoid agreeing with spacedong is difficult, so I'll just say 'yeah okay'

the other issue is that there's just way too many, there shouldn't be more than one or two in sight at a time and it seems like here they're just peppered throughout the station carelessly

**Comment by Spankmaster1066** [comment]
If you stand behind them you should stick out a bit yeah.

**Comment by KayeArray** [comment]
Please revise their placement, this is way too haphazard and random.

**Comment by Sarcalogo** [comment]
>inb4 this gets merged before my sole PR does even though it has been open for 3 days and is literally just a minor fix
>then I have to redo the whole thing because MAP CONFLICTS.

**Comment by dreamcrab** [comment]
i like the idea but not a lot of the placements

**Comment by ghost** [comment]
perhaps make plants that hang off walls

**Comment by GuyonBroadway** [comment]
Nah pot plants were just a nice little Hippie thing from wayback. Sure I need to tone them down but one or two per room per department would be nice. With a few extras in public areas so people can solid-snake their way out of a sec chase... also I need to fix my conflicts too.

**Comment by GuyonBroadway** [comment]
heck imma close and redo this because _confligds :DDDDDDD_

**Pull request closed without merging**
