### PR TITLE
[MIRROR] Cleans up the README

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/33172
--------------------
added some https
removed some double spaces
replaced an outdated map (tgstaton2) with BoxStation in the maps section

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Need opinions on how this looks

**Comment by praisenarsie** [comment]
go ahead

**Comment by praisenarsie** [comment]
im da king of the readme

**Comment by praisenarsie** [comment]
>>>>>>>HEADMIN APPROVAL FOR A README

**Comment by ghost** [comment]
all this needs is a second set of eyes to ensure it's functional

**Comment by JohnGinnane** [comment]
Can I get someone else to approve then? Don't want to self merge changes even this small

**Review by KayeArray — APPROVED** [review]

**Pull request merged**
