### PR TITLE
[MIRROR] [s] Fix lockboxes not actually being locked

### LINKED ISSUE #38369: You can open and take items out of locked secure briefcases
1.Hold briefcase with one hand
2. Select opposite empty hand
3. Click on briefcase
4. See contents/take items out of briefcase (can't put anything in)

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/38376
--------------------
:cl:
fix: Lockboxes are now actually locked again.
/:cl:

Fixes #38369.

### CODE REVIEW

**Comment by Jujumatic** [comment]
wait i fixed 4 conflicts and all this pr changes is one line

:what:

**Review by Carbonhell — APPROVED** [review]

**Comment by Pyko1** [comment]
you prolly fixed them wrong way out

**Comment by Carbonhell** [comment]
Yea because in another pr i just said fuck it and resetted storage.dm
This pr is good now,let travis do its job

**Comment by Jujumatic** [comment]
i mean the code checks out now so like it should be fine

**Pull request merged**
