### PR TITLE
Clowns can now move at full speed without losing their honor!

### PR DESCRIPTION
**Pull request by ghost**
H O N K

### CODE REVIEW

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by dreamcrab** [comment]
fuck off idiot you just died as a clown

**Comment by Blute1** [comment]
lol

**Comment by ghost** [comment]
Build finished.

**Comment by ghost** [comment]
IC in OOC?

**Comment by praisenarsie** [comment]
I DED?

**Comment by GuyonBroadway** [comment]
If you need to move at full speed just to survive as a clown you are not a good clown.

**Review by GuyonBroadway — APPROVED** [review]
Code is technically ok.

**Comment by ghost** [comment]
im just impatient

**Comment by dreamcrab** [comment]
close this retarded shit

**Comment by ghost** [comment]
what the fuck is this its about time i pay attention to this github nonsense, this affects us all and seeing faggots like you putting in these changes that are NOT necessary at all is fucked up. NO to this, GIT GUD as the clown

**Comment by SplergeBucket** [comment]
RETARDED AND UNROBUST

**Comment by Pyko1** [comment]
No, clowns are meant to be slow, and to dunk people who think they can mess with the clown just because he is a bit slower and louder than others.

**Comment by KayeArray** [comment]
no

**Comment by ghost** [comment]
sinful

**Comment by Dinopeaks** [comment]
-1

**Comment by Dinopeaks** [comment]
GTFO

**Comment by praisenarsie** [comment]
????????

**Pull request closed without merging**
