### PR TITLE
Band-Aid fix for HF blade until I actually get around to adding more stuff to it

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Manly Dwarf
tweak: HF Blade now costs 9 TC. May be reverted once the HF Blade actually gets that more complex stuff added.
/:cl:

## Why It's Good For The Game

Band-Aid fix for the sleeping carp + noslips combo until I actually get around to adding more stuff to it.
I dunno who decided to make NoSlips 2 TC, by the way. Might be the next lazy PR I put out. If it was me, please kill me.

### CODE REVIEW

**Comment by cris5311** [comment]
Why not increase noslips instead or am i retarded?

**Comment by Manly-Dwarf** [comment]
@cris5311 give it a moment

**Comment by WarRage333** [comment]
no slips + thermals are a no-brainer, makes other choices look bad

**Comment by Manly-Dwarf** [comment]
@WarRage333 give it a moment

**Comment by NautilusViper** [comment]
tbh make the carp mask 6tc instead

**Review by AnthonyJNgo — APPROVED** [review]
Nothing to really review.

**Pull request merged**
