### PR TITLE
Maintenance Longface Lair

### PR DESCRIPTION
**Pull request by carlopault**
## Changelog
:cl: Carlospaul
add: New maintenance area in the top right of the station: the Longface Lair. 
/:cl:

image

## Why It's Good For The Game
New stuff is exciting for players.

### CODE REVIEW

**Comment by Punkinguy** [comment]
+1 its funny, just make sure to make it connected to its own APC
also +7,886 −127,282

**Comment by MrEpicSax** [comment]
+1 because it benefits me

**Comment by Timmeye** [comment]
+1 but why is there a crab in space

**Comment by carlopault** [comment]
> +1 but why is there a crab in space

lol random crab funny poopoo

**Comment by wheezl** [comment]
+1 if the dildo is removed, they're supposed to be unique so you can build the dragon dildo shelf if you collect all of them. adding a duplicate dildo ruins it

**Comment by carlopault** [comment]
> +1 if the dildo is removed, they're supposed to be unique so you can build the dragon dildo shelf if you collect all of them. adding a duplicate dildo ruins it

If I remove the dildo then what can be there instead. It wouldn't be a coom corner without a coom object.

EDIT: I have got it.

**Comment by karmaisblackandbluepilled** [comment]
-2 he shilled on interhippie too what a n

**Comment by Punkinguy** [comment]
> -2 he shilled on interhippie too what a n

banned 4everever

**Comment by yoyobatty** [comment]
You didn't map merge reee

**Comment by AnthonyJNgo** [comment]
+3 once you take care of what pyko and batty mentioned. Extremely impressed that you have finally gotten to the point where you were able to push the PR.

Refer to the documentation on wiki about map merger, it is pretty easy to set up and then you won’t have to worry about it again.

**Comment by carlopault** [comment]
> I think you messed up with the starlight in the north wall of your new area.
> Not to mention ugly doublewall.
> Also mapmarge.

Fixed all this. https://github.com/HippieStation/HippieStation/pull/12637

**Comment by yoyobatty** [comment]
Fixed in other pr.

**Pull request closed without merging**
