### PR TITLE
Clockpod for the centcomm supplypod launcher for admemes

### PR DESCRIPTION
**Pull request by DullUnlimited**
**higher quality adminbus**

stuff changed:
tgui\src\interfaces\centcom_podlauncher.ract
_DEFINES\cargo.dm
supplypods.dmi

picture:
https://i.imgur.com/Qzx8H8A.png

### CODE REVIEW

**Comment by DullUnlimited** [comment]
also ignore the first bottom log i fixed that shit about the upload

**Comment by Manly-Dwarf** [comment]
Clock Cult is the most popular gamemode not in rotation.

**Comment by MaterialisticThings** [comment]
+1

**Comment by AnthonyJNgo** [comment]
If this replaces the current pod we have, -1. If this is **in addition to** the pod we have then +1 merge after Batty approves.

**Comment by Majick1** [comment]
+1 as an option yeah

**Comment by DullUnlimited** [comment]
it adds bro not replace

**Comment by ghost** [comment]
I will now seize power from @yoyobatty by approving this PR and merging it.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
