### PR TITLE
Suit Sensors start on [Bounty from Higitus!]

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl: zamolxius sponsorized by Higitus/Old Man
tweak: tweaked suit sensor starting position. It starts on, as Nanotrasen intended.
balance: rebalanced suit sensors. They now start on the maximum position.
/:cl:

### CODE REVIEW

**Review by ghost — APPROVED** [review]
code is good

**Comment by ghost** [comment]
@HonkBot remove dnm bitch

**Comment by ghost** [comment]
Plus uno

**Comment by Toxici11i** [comment]
-1 ewww nooo

**Comment by Toxici11i** [comment]
i will reiterate that this nerfs roundstart killing as a traitor and just requires you to stunbaton, or 357 and cremate instead

**Comment by ghost** [comment]
@Toxici11i just strip lol.

Anyways, this PR hung around for a bit too long so I'm just going to merge it. If anyone objects, please direct all complaints to suckmyweewee@mailinator.com

**Comment by Toxici11i** [comment]
yeah bro.. @HideAndSeekLOGIC just merge this then...
https://github.com/HippieStation/HippieStation/pull/12344
its old..

**Pull request merged**
