### PR TITLE
[MIRROR] [READY] [Gamemode Bounty] Assimilation

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40296
--------------------
:cl: Kierany9
add: A new gamemode called Assimilation.
add: Several probably-inhuman creatures wielding psionic powers, known only as Hivemind Hosts, have appeared onboard the station and must assimilate as many crew members as possible. Assimilated crew serve as vessels for the Host to use their powers through (and on), and as a Host gains vessels, they gain new abilities.
remove: Vessels are not antagonists. Assimilation does not convert crew in any way.
add: Assimilated crewmembers can escape this nightmare by either getting a mindshield implant or by dying. Mindshielding vessels will reveal the identity of whoever assimilated them. Mindshielded crew are initially protected, but should a Host get strong enough, they can break these implants with ease.
add: Nothing is stopping Hosts from working together, but as their hives grow, so does the incentive to backstab. At 8 vessels, Hosts can probe the minds of crew and discover the identity of any other Hosts who have assimilated them, and at 18, they can steal every single vessel from a captured enemy Host.
tweak: Assimilation requires 25 players roundstart.
/:cl:

# PR is complete and ready to merge

## For the code-illiterate

- [x] Gamemode logic
- [x] Objectives
- [x] Cool powers
- [x] (Coder) Sprites
- [x] More cool powers that may or may not get added
- [x] Admin logging
- [x] Whatever the maintainers want done/fixed

### Another conversion mode?
No. Assimilated crew do not become antagonists, nor does it grant them any benefits. Assimilation only serves to fuel the power of and conflict between the roundstart antagonists.

### What objectives do these antagonists get?
- Assimilate X crewmembers OR Have X assimilated crewmembers escape on the shuttle
- Assimilate a crewmember(more likely than usual to be an implanted one) OR Kill/Maroon a crewmember
- Escape

### What powers do these "Hive Hosts" get?
All Hive Hosts begin with four powers, **Assimilate Vessel** allows them to add a crewmember within four tiles to the hive after standing still for ten seconds(and the crewmember needs to stay still for the last three). The power is undetectable, making it very safe to use. **Release Vessel** works the same way as Assimilate does, except it's instant and removes a hive member from the hive. **Hive Sight** allows them to use the eyes of an assimilated crew member, and **Neural Shock** knocks an assimilated target out for a short while, although the effectiveness of this power decreases with distance.

Later on, Hosts will unlock **Repair Protocol**, which allows them to absorb brain power from their vessels to heal brute, burn, brain and clone damage, ~~**Cerebellic Pulse** lets them move members around with effectiveness decreasing with distance~~, **Induce Panic** causes anybody in sight to hallucinate, drop everything or start shooting/whacking/hugging everybody in the room, **Network Invasion** lets them find out the identity of any other hive hosts connected to a crewmember, although this backfires if used against a host, **Mind Control** grants total control over a vessel for a short period of time, that grows rapidly with hive size and **Distortion Field** causes hallucinations (and later stamina damage) to everybody surrounding a vessel. 

Finally, **Bruteforce** destroys implants and nanites inside mindshielded personnel, **Telekinetic Field** is a stronger Forcewall, **Mass Assimilation** lets them steal an enemy host's vessels should you figure out their identity and capture them, and **Medullary Failure** causes a vessel to  ~~keel over and die~~ suffer a heart attack.

I've got a couple more in mind (that may or may not upset the entire balance of the game) but I'd like to see how this plays out as is first.

### Wow, that seems OP. What's stopping mass murderbone?
You lose your powers if you dip below the required hive size, the cooldowns are kind of long, many powers have a channelling time, and there are a grand total of two powers that affect non-assimilated personnel, so these powers are best used for other causes.

### What are you even trying to do with this mode?
A different take on conversion modes and stealthy antagonists with a large dose of espionage. Hosts have very little power against those they haven't assimilated, meaning the number one priority is to fill up the hive, both for the objective and for power in general, meaning they'll want to stay somewhat under the radar until unlocking at least Induce Panic. They also rely far more on information to survive than other antagonists, and are given the means to obtain it with powers such as Hive Sight and Network Invasion. Vessels are not antagonists, meaning that unlike standard conversion modes, there is no "Crew VS Enemies" dynamic that always crops up, in general crew will only end up involved in the mess if they happen to be a shared vessel between two hosts.

### Can I see your codersprites
image
coder/10

## For maintainers
You may or may not want to tear your hair out reviewing this. I am sorry.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
This... sounds pretty uninteresting.
Like I'm not gonna sit here and say it's boring but don't we already have Shadowlings in the game?
smug

**Comment by GuyonBroadway** [comment]
This isn't like shadowlings based on what I saw, it's more like uplink but people are the wi-fi routers. 

Basically the "assimilated"(hacked) people provide power to fuel and are a vector for assimilator powers. They are mostly unaware they've been assimilated(hacked) until the asssimilator(brainhacker) uses their powers.

**Comment by Manly-Dwarf** [comment]
So it's Devils, but even more boring?
smugg

**Comment by GuyonBroadway** [comment]
Dunno about boring, devils was boring because it was easy to validhunt but there was no incentive for the crew to fight the devil. 

Here the crew have a reason to not want to be assimilated but they might not even know they HAVE been assimilated.

Like a real hacker you gotta slip in undetected and shit.

**Comment by Manly-Dwarf** [comment]
Still sounds better as a midround antagonist than its own god damn gamemode.

**Comment by praisenarsie** [comment]
@Kawaii-Big-Boss Try it before you judge it.

**Review by yoyobatty — APPROVED** [review]

**Comment by yobob591** [comment]
We tried it and it sucked

Basically nobody even knew they existed the entire round

**Comment by praisenarsie** [comment]
You're autistic.

**Comment by Carbonhell** [comment]
>try it before you judge it
>Tries it, sucks
>Lol ur autistic
what...?

**Comment by GuyonBroadway** [comment]
To be fair you'd need to run a gamemode on rotation for a week or so before people understand its depths.

**Pull request merged**
