### PR TITLE
[DNM] External Authentication 2: Electric Boogaloo

### PR DESCRIPTION
**Pull request by ghost**
:cl:
server: Added external authentication, so you can login even when the BYOND hub is down! Just use the "Register/Update-Account" verb in the OOC tab!
/:cl:

you can login just using a password prompt, or by using the special fancy smhancy vapor-auth-client for autologin.

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
lifeweb added authentification and now karma can't crash it, coincidence I think not
+1

**Comment by AnthonyJNgo** [comment]
I hosted a server privately on my desktop without a connection to the internet and Karma was not able to crash it. Coincidence? I think not. +1.

Seriously unironic +1 we could use this in case hub has issues.

**Comment by ghost** [comment]
This is held up due to https://github.com/MCHSL/extools/issues/28

**Comment by AnthonyJNgo** [comment]
All good, as long as it is being worked on.

**Comment by ghost** [comment]
@AnthonyJNgo it's effectively done, but it crashes because of extools bug

**Pull request closed without merging**
