### PR TITLE
Hotel Kitchen Changes

### LINKED ISSUE #11174: Locker at Hotel is locked and unopenable by regular staff access
This is at the kitchen of the hotel, the Meat fridge, and the Refridgerator, I had to get an admin to open them for me. and there is nothing even strong enough to brute the things open.

### PR DESCRIPTION
**Pull request by AnthonyJNgo**
:cl:
tweak: You're now able to actually open the fridges in the hotel kitchen, as well as the doors.
/:cl:

Edited the access requirements for the fridges and doors on the space hotel to allow people to actually enter and use the items. Fixes #11174

### CODE REVIEW

**Comment by Punkinguy** [comment]
+1 this is just ebic

**Comment by AnthonyJNgo** [comment]
MFW new desktop and I didn't install mapmerger on here yet. RIP.
Go ahead and vote on the idea, I will install mapmerger later and run it to fix the travis conflicts.

**Comment by Toxici11i** [comment]
nice failure to mpamerge

**Comment by carlopault** [comment]
+1

**Comment by yoyobatty** [comment]
>install map merger

oh boy

**Comment by Zyzarda** [comment]
No reason not to add this +1

**Comment by yoyobatty** [comment]
Is this getting fixed soon?

**Comment by cris5311** [comment]
+1
Epic

**Comment by Punkinguy** [comment]
please figs this or i will perma cringe

**Comment by mkikt4743** [comment]
yeah

**Comment by AnthonyJNgo** [comment]
Ugh ever since quarantine I've seen my output crash aaaaaaaaaaa (i'll get it done soon)

**Comment by mkikt4743** [comment]
c'mon c'mon

**Comment by mkikt4743** [comment]
*snap2

**Comment by yoyobatty** [comment]
closing for now

**Pull request closed without merging**
