### PR TITLE
removes mentors 

### PR DESCRIPTION
**Pull request by praisenarsie**
:cl: FROZENGUY5
admin: REMOVED MENTORS
/:cl:

[why]: code thinks mentor isholder sometimes (see the time where morty accidently activated The Ark as an observer mentor), newbies can just ask ooc or adminhelp, awful pink ooc color.

@dreamcrab
@Dudeinyourbackyard 
@Chnkr 
@mcbawbaggings (still an admin in me heart)
 
Fixes https://github.com/HippieStation/HippieStation/issues/4903

### CODE REVIEW

**Comment by JohnGinnane** [comment]
why

**Comment by ghost** [comment]
mentors are a good system, and are a way to drag people into becoming admins
it actually might be worthwhile making the snowflake mentor system of old hippie again

**Comment by praisenarsie** [comment]
it is indeed due a rewrite but who's willing to do it.

**Comment by Carbonhell** [comment]
What is this shit pr
Are you the new amari

**Comment by praisenarsie** [comment]
also someone remind to test this

**Comment by praisenarsie** [comment]
actually @McBawbaggings i could see how goon mentors work and see how they work. @Chnkr since you are one, do you know if goon mentors actually work good???

**Comment by Carbonhell** [comment]
Goon mentors are probably too different to be fit here easily. Best would be to rewrite the system in a similar way to admins,perhaps a mentor datum?

**Comment by tortellinitony** [comment]
Mentors used to have their own datum and then I made it so they just use the normal ranks system so you don't need a special way to manage them

**Comment by ghost** [comment]
rewrite rather than remove tbh

**Comment by Carbonhell** [comment]
-1. Mentors are a really good way to split ahelps and make admin work easier, aswell as seeing how potential future trialmins deal with users. Fix the bugs, rewrite them, but don't just straight out remove.

**Comment by earthmoonjune** [comment]
-1. Pretty much same reasons as carbon already said. denied.

**Pull request closed without merging**
