### PR TITLE
This is... the INFO WAR

### PR DESCRIPTION
**Pull request by ghost**
:cl:
soundadd: Traitors now get a more fitting introduction.
/:cl:

@Manly-Dwarf

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
that was a joke

**Comment by ghost** [comment]
don't let your memes be dreams

**Comment by NautilusViper** [comment]
I want this but only with a very small (2% or lower) chance to play instead of the normal traitor sound

**Comment by Majick1** [comment]
+1 for rng intro

**Comment by ExpAntique** [comment]
-1 this doesn't fit for traitor at all.

**Pull request closed without merging**
