### PR TITLE
Maybe fixes changelog generation??? at worst it updates it

### PR DESCRIPTION
**Pull request by Carbonhell**
as title says, let's pray

### CODE REVIEW

**Comment by Carbonhell** [comment]
hold on,somehow jamie got back in the changelog, sneaky fuck

**Comment by Carbonhell** [comment]
should be good,let's wait ol' travis-a

**Comment by praisenarsie** [comment]
HippieStation:master from Carbonhell:master

nice one

**Comment by Carbonhell** [comment]
honk

**Review by praisenarsie — APPROVED** [review]

**Pull request merged**
