### PR TITLE
Update manipulation.dm

### PR DESCRIPTION
**Pull request by mikolaj007**
## Changelog
:cl:
del: removed Thrower Circuit
/:cl:
## About The Pull Request

Removes Thrower circuits
## Why It's Good For The Game

because being able to hit someone 20 times with thrown hatchets in 6 seconds is bullshit
https://cdn.discordapp.com/attachments/321674575245082626/546670545026940928/unknown.png

### CODE REVIEW

**Comment by Jujumatic** [comment]
bye bitch :omegaLUL:

**Review by Jujumatic — DISMISSED** [review]

**Comment by Carbonhell** [comment]
+1, this is the worst circuit existing right now and it's painful how noone removed them yet

**Comment by yoyobatty** [comment]
I might propose having a cooldown, item limit, item size limit and increased power draw. Let's have it throw 1 item every 6-7 seconds and it must be the small/tiny weight size. Just because something is OP, doesn't mean you should remove it, simply take the time to nerf it so it's acceptable for everyone else.

**Comment by Carbonhell** [comment]
I like circuits, that's known. And i prefer nerfing or reworking things instead of removing them. But this is one of the few things that really cannot be reworked, and it's better off the game imo. I prefer the removal than the nerf, we've discussed any decent circuit that you could make with the thrower that isn't a ghetto pneumatic cannon and we couldn't find any.

**Comment by mikolaj007** [comment]
accidentally fucked with the code on this pull request instead of making a new branch
i am not very good with computer

**Comment by mikolaj007** [comment]
please delete, ill go remake this on its own branch before i fuck with this harder on accident while learning git.

**Pull request closed without merging**
