### PR TITLE
Unfucks vampires

### PR DESCRIPTION
**Pull request by mikolaj007**
## Changelog
:cl:
bal: vampires no longer get 5 units of blood for every 25 units they suck from a person
bal: they instead get 10 units of blood for every 10 units they suck from a person
/:cl:

## About The Pull Request
fixes the values on amount of blood sucked and removes the divide by 2 step which existed for some reason

## Why It's Good For The Game
vampires were nerfed hard after the previous PR, so i gotta fix that shit

### CODE REVIEW

**Comment by cris5311** [comment]
+1

that was a big fuckup

**Comment by yoyobatty** [comment]
It's a buffix

**Comment by Manly-Dwarf** [comment]
good buffix thank you
can we also speed up them suckin blood even more ok thanks

**Comment by mikolaj007** [comment]
> 
> 
> good buffix thank you
> can we also speed up them suckin blood even more ok thanks

in the original, you sucked 10 blood for every 25 blood the person lost
then, the speed of sucking got doubled, and you sucked 5 blood for every 25 blood lost
now its still double speed, but you now suck 10 blood for 10 blood lost, giving you more blood in less time when compared to the original

**Comment by Knifepony** [comment]
On /tg/ they would've nerfed it further to 1 unit per 50 units of blood
10/10

**Review by ghost — APPROVED** [review]

**Pull request merged**
