### PR TITLE
Gives the execution sword a suicide_act.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
add: Added a special suicide to the executioners sword. 
/:cl:

[why]: You could already target your own head for execution but it felt wrong for suiciding with it to not do anything.

### CODE REVIEW

**Comment by dreamcrab** [comment]
i dream of a day when every item has a custom suicide emote

+seppuku666

**Comment by ghost** [comment]
in fucking credible
+1

**Comment by ghost** [comment]
yeah +1

**Review by JohnGinnane — APPROVED** [review]
Looks good

**Review by ghost — APPROVED** [review]
Code OK

**Pull request merged**
