### PR TITLE
Makes the mechfab use the ore silo.

### PR DESCRIPTION
**Pull request by ghost**
🆑 zennerx
tweak: Exosuit fabricator now uses the ore silo.
fix: Ore silo runtime fixed.
/🆑

Closes https://github.com/HippieStation/HippieStation/pull/12571

Ejecting sheets actually works, and there's no runtimes.

### CODE REVIEW

**Review by yoyobatty — APPROVED** [review]
You tested ALL of it right?

**Comment by AnthonyJNgo** [comment]
Based

**Review by AnthonyJNgo — APPROVED** [review]
looks good to me

**Comment by AnthonyJNgo** [comment]
I reverted this because I can just merge battys pr instead

**Comment by Neotwr** [comment]
@AnthonyJNgo battys PR doesn't adds this function(mechfab using the ore silo), that PR just fix the ore silo runtime

**Comment by AnthonyJNgo** [comment]
@Neo-0 me big dumb

**Pull request merged**
