### PR TITLE
[Requires SQL update] Update to tg master

### PR DESCRIPTION
**Pull request by ghost**
FUCK

also @HonkBot seems to have fucked up a PR or two

### CODE REVIEW

**Comment by ghost** [comment]
Someone may need to recompile tgui

**Comment by ghost** [comment]
Should be ready now... I hope. No I do not plan to switch slings over to the new shadowwalk

**Comment by GuyonBroadway** [comment]
I dunno how to do the SQL shit but we kinda need to do this as honkbot has some issues and the more we put it off the more we risk outselves to "oh shit cyberboss refactored everything again, the madman!" and the harder an upstream will be.

**Comment by j-mie** [comment]
Think I finally fixed HonkBot, did a new PR @ #3003 

Thanks for your update tho

**Pull request closed without merging**
