### PR TITLE
Adds a shaft miner traitor item: Anti-gravity boots

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
add: Shaft miner can now buy a nifty pair of anti-gravity boots in their traitor uplinks.
/:cl:

## About The Pull Request
These do exactly what they say. In short, they make you float, so lava, chasms and floor chems simply ignore you. They come with a battery that have a limited use, so use wisely!

## Why It's Good For The Game
Miners could shell out some TC's to get a cheap way to walk across lava and chasms. The battery lasts around 5 minutes of continued use. Once it's out, the boots are pretty much useless, so use them wisely!

### CODE REVIEW

**Comment by Eagle-Eyess** [comment]
can these be used to get over things like lube as well?

**Comment by Eagle-Eyess** [comment]
+1 anyway

**Comment by yoyobatty** [comment]
I believe, but it doesn't remove your ground movement flags so it might not. I'll test to confirm

**Comment by Manly-Dwarf** [comment]
I would much rather this be a surplus crate item rather than a purchasable. I don't see how this really correlates to an item useful for miners outside of chasms and lava, and the potential for abuse is astounding when you make this an item that you can get every single round.
Seriously, jetpack + boots = win. If you can't slip, then that's even worse.

**Comment by yoyobatty** [comment]
Can't really add it to surplus without making it an uplink item unless I exclude it from every game mode

**Comment by Manly-Dwarf** [comment]
gimme the code and sprites and I'll just put it in my PR if you want

**Comment by k-k-karma** [comment]
chempiles ignore gravity

**Comment by yoyobatty** [comment]
Well I gotta fix that chempile thing

**Comment by Maroonenahmoron** [comment]
What about stilts? Walk over lava+chasms+chempiles, can still slip over stuff.

**Comment by cris5311** [comment]
+1

**Comment by Majick1** [comment]
You could make them lavaproof white shoes so they still ignore chempiles, +1 anyway

**Comment by ghost** [comment]
@Manly-Dwarf they have a battery and said battery is not refillable

**Comment by mikolaj007** [comment]
maybe a mining points item? i dont see myself spending TC's on this when the only utility it has is better mining.
its a strong mining item, but its comparable to buying a 10mm to shoot some goliaths

**Review by ghost — CHANGES_REQUESTED** [review]
Needs a
```
/obj/item/clothing/shoes/magboots/antigrav/get_cell()
    return cell
```
and
```
/obj/item/clothing/shoes/magboots/antigrav/emp_act(severity)
    cell.emp_act(severity)
    /* other emp cell acts should go here */
```

**Comment by yoyobatty** [comment]
> maybe a mining points item? i dont see myself spending TC's on this when the only utility it has is better mining.
> its a strong mining item, but its comparable to buying a 10mm to shoot some goliaths

@mikolaj007 these items gives abilities that you wouldn't ordinarily see from the mining vendor, plus they have huge potential to be very powerful so that's why I feel they should be a tator item.

**Review by ghost — APPROVED** [review]

**Comment by mikolaj007** [comment]
alright, i guess i dont know shit bout mining

**Pull request merged**
