### PR TITLE
[MIRROR] Changes eye blur to use byond 512 filters

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/41759
----------------------------
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: Blurry eyes now actually blur instead of an overlay.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Credit goes to @FlattestGuitar for the code.

Cool pic

https://img.spaceball.cf/HyB9rYbuF2.mp4

### CODE REVIEW

**Comment by ghost** [comment]
THANK YOU @yoyobatty FOR PRing this for me

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by HideAndSeekLOGIC** [comment]
awesome, +1

**Comment by HideAndSeekLOGIC** [comment]
awesome, +1

**Comment by ghost** [comment]
awesome, +1

**Comment by ghost** [comment]
no spamerino in my PRrino

**Comment by ghost** [comment]
Nice job sending my message 3 times, GitHub. Really appreciate it.

**Review by yoyobatty — COMMENTED** [review]
Code needs work

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
