### PR TITLE
Cool see-through portals

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Portals are now see-through!
/:cl:

https://cdn.discordapp.com/attachments/622163943510638602/635493839804825600/qrdMklMwth.webm
https://cdn.discordapp.com/attachments/622163943510638602/635492290475065353/ysvleE7qCx.webm

### CODE REVIEW

**Comment by yoyobatty** [comment]
I'm guessing this requires 513

**Comment by ghost** [comment]
yup

**Comment by diegoxt45** [comment]
this will kill the funny random portals with hand tp though....

**Comment by Manly-Dwarf** [comment]
we're on 513 now. can we merge this?

**Comment by ghost** [comment]
no

**Comment by ghost** [comment]
there's a byond bug: http://www.byond.com/forum/post/2533064

**Comment by Manly-Dwarf** [comment]
yo mama

**Comment by AnthonyJNgo** [comment]
Closing for now, reopen the PR when the byond bug is fixed.

**Comment by ghost** [comment]
Update server to 513.1506 and it's fine now.

**Comment by ghost** [comment]
dis is ready

**Review by yoyobatty — APPROVED** [review]
Simple and good

**Pull request merged**
