### PR TITLE
makes exo fabricator use ore silo, attempts to fix silo runtime

### PR DESCRIPTION
**Pull request by checkraisefold**
apparently ejecting sheets is broken, i have no idea why but the rest works and is frankenstein'd from tg's code

:cl: zennerx
tweak: Exosuit fabricator now uses the ore silo.
fix: Ore silo runtime fixed.
/:cl:

cool because like robotics is annoying as fuck without the ore silo
the exosuit fabricator currently requires manually putting in sheets of material each time you want to make something, so you have to run all the way to the protolathe and eject materials until you have just the right amount and then end up screwing it up and having to run back again
this solves that problem by just making the exosuit fabricator use the ore silo so it has all the materials at its disposal

also someone figure out why ejecting sheets is broke thanks

### CODE REVIEW

**Comment by checkraisefold** [comment]
1 ci check failed and it's not my fault and the other is just ci being broken

**Comment by AnthonyJNgo** [comment]
Can you elaborate on what this does, what it is meant to do, and what problem it resolves? Thanks in advance, just looked through code and it looks clean enough, I just skimmed it though.

**Comment by checkraisefold** [comment]
edited

**Comment by ghost** [comment]
+1

**Review by ghost — DISMISSED** [review]
Code is fine, provided that you tested it.

**Comment by checkraisefold** [comment]
reminder don't immediately merge this because it's fucked and runtimes whenever you eject sheets
here's the runtime idk why it is happening
`Runtime in machine_silo.dm,234: cannot read from list
  proc name: format (/datum/ore_silo_log/proc/format)
  usr: Zennerx/(Fridge Bashline)
  usr.loc: (Robotics Lab (174, 119, 2))
  src: exosuit fabricator: ejected 0x... (/datum/ore_silo_log)
  call stack:
  exosuit fabricator: ejected 0x... (/datum/ore_silo_log): format()
  exosuit fabricator: ejected 0x... (/datum/ore_silo_log): New(the exosuit fabricator (/obj/machinery/mecha_part_fabricator), "ejected", 0, "sheets", /list (/list))
  the ore silo (/obj/machinery/ore_silo): silo log(the exosuit fabricator (/obj/machinery/mecha_part_fabricator), "ejected", 0, "sheets", /list (/list))
  /datum/component/remote_materi... (/datum/component/remote_materials): silo log(the exosuit fabricator (/obj/machinery/mecha_part_fabricator), "ejected", 0, "sheets", /list (/list))
  the exosuit fabricator (/obj/machinery/mecha_part_fabricator): eject sheets(null, 10)
  the exosuit fabricator (/obj/machinery/mecha_part_fabricator): Topic("src=\[0x200a341];remove_mat=10...", /list (/list))
  Zennerx (/client): Topic("src=\[0x200a341];remove_mat=10...", /list (/list), the exosuit fabricator (/obj/machinery/mecha_part_fabricator))
  Zennerx (/client): Topic("src=\[0x200a341];remove_mat=10...", /list (/list), the exosuit fabricator (/obj/machinery/mecha_part_fabricator))
`
github breaks the line formatting when it's in a code block so whatever

**Review by ghost — CHANGES_REQUESTED** [review]
see above

**Comment by Maroonenahmoron** [comment]
Yes please, +1

**Comment by ghost** [comment]
https://github.com/tgstation/tgstation/pull/48976

**Comment by checkraisefold** [comment]
wtf i suck at using github command line let me test if this works locally and then i'm changing the title, also honkbot added config update for who knows

**Comment by checkraisefold** [comment]
oops I might've pulled from the wrong origin LOL

**Comment by checkraisefold** [comment]
i don't know why the config changed out of the blue, runtime didn't fix with the tg change, ejecting sheets still produces a runtime and doesn't eject them. someone else look at this please?
edit: config didn't change

**Comment by ghost** [comment]
there i did it better than you

**Pull request closed without merging**
