### PR TITLE
[MIRROR] Crew monitoring rework part 1: crew pinpointers

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/30117
--------------------
Crew monitoring consoles have been in a laggy, client-crashing state for a long time. Nobody has bothered to fix them, and it's safe to say nobody will bother fixing them in the foreseeable future. Maybe it's time we rewrite them.

This PR contains an alternative intended to replace one part of the console's functionality: crew pinpointers. A crew pinpointer is just a pinpointer that tracks maxed suit sensors. Crewmembers with their sensors below max can't be tracked.

If this gets merged, the next step will be to replace the consoles with a slimmed-down manifest that lacks a minimap. The consoles will show vitals, but position will be text-only. Use pinpointers to track crewmember position exactly.

Two pinpointers start in each full-size medical vendor. One starts in the detective's cabinet. 

They are painted blue.

:cl: Pubby
add: Crew-tracking pinpointers to replace laggy crew monitoring console functionality
add: Crew-tracking pinpointers in medical vendors and the detective's office
/:cl:

If anyone wants to argue balance before thinking: These provide less information than handheld crew monitors. If anything, this rework is a nerf.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
fak

**Comment by JamieH** [comment]
build this

**Comment by JamieH** [comment]
build this

**Comment by JamieH** [comment]
build this

**Comment by j-mie** [comment]
@MoreRobustThanYou This is broken, you shouldn't approve it until you fix it - you need to edit the HippieStation.dme file to include the changes made in the tgstation.dme file.

You'll see that a `Changes tgstation.dme` label was added - you need to make sure to mirror those changes to our DME.

**Comment by ghost** [comment]
you fixed the dme so ima merge this

**Pull request merged**
