### PR TITLE
[MIRROR] [Ready] Communal Resource Storage II

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/39118
--------------------
[Sponsored](https://tgstation13.org/phpBB/viewtopic.php?f=5&t=17661) by @ optimumtact. Based in part on #37901.

:cl:
add: The vault now contains an ore silo where the station's minerals are stored.
add: The station's ORM, recycling, and the labor camp send materials to the silo via bluespace.
add: Protolathes, techfabs, and circuit imprinters all pull materials from the silo via bluespace.
add: Those with vault access can view mineral logs and pause or remove any machine's access, or add machines with a multitool.
tweak: The ORM's alloy recipes are now available in engineering and science protolathes.
/:cl:

* [x] Fix #39232
  * [x] by allowing the silo to store plastic?
  * ~~biomass?~~
* [x] Componentize the remote material storage (current structure has too much duplication)
* ~~Consider adding exosuit fabricators to the linkage~~
  * Not in this PR, but if someone else wants to add this later, I can advise
* ~~Consider hiding exactly what is being printed (is this an issue in practice?)~~
* ~~Consider reducing ability to eject all sheets at a protolathe~~
  * ~~(?) Possibly return local storage and have the silo apportion materials~~
* [x] Handle the general case of off-station lathes rather than special-casing the golem ORM
  * [x] Give non-siloed protolathes limited storage again
* [x] Paginate ore silo logs
* [x] Make the ore silo constructible

----

* [x] Add ore silo machine
  * [x] Write a description
  * ~~Finalize sprite and effects~~
    * MrDoomBringer will be adding a sprite in a future PR
* [x] Mapping changes
  * [x] Place ore silo in vault
  * ~~Combine vault into Cargo warehouse~~
    * Deferred to avoid interfering with #39177 or any other remap which would leave something useful where the vault used to be
* [x] Retrieve materials from silo for R&D fabs
* [x] Remove material bins from R&D fab component parts
* [x] Send smelted materials from ORM to silo
  * [x] Refuse to smelt if there is no silo
  * ~~Remove ability to retrieve sheets from ORM~~
* [x] Send reclaimed materials from DA to silo
* [x] Send inserted materials from R&D fabs to silo
* [x] Send materials from stacking machines to silo
  * [x] Labor shuttle
  * [x] (?) Recycling
* [x] Automatically link mapload R&D fabs to silo
* [x] Allow linking machines to silo with multitool
* [x] Allow unlinking machines from silo UI
* [x] Allow putting access on hold without unlinking fabs
* [x] Log silo deposits and withdrawals, show in UI
  * [x] View log from QM PDA
* [x] Update R&D fab logic to handle disconnected silo
* [x] Update R&D fab UI to either
  * ~~disallow ejecting materials, or~~
  * [x] eject materials locally rather than at the silo
* [x] Allow ejecting materials from the silo UI
* [x] Add smelting designs from ORM to protolathes
  * [x] Finalize which departments get these recipes
* [x] Free golem ORM should either
  * ~~have its own silo, or~~
  * [x] not use silos, retaining old behavior

image

image

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
HOLY FUCKING MAP CONFLICTS BATMAN!!!

**Comment by GuyonBroadway** [comment]
As god as my witness i'm going to fucking well fix this PR if its the last PR I ever do! I've wanted this for so long!

**Comment by Carbonhell** [comment]
1)Strip Box/Meta/Delta/Omega/Pubby map changes (leave hippie ones in)
2) Compile tgui
and this can be merged

**Comment by Pyko1** [comment]
all the needed map changes are in https://github.com/HippieStation/HippieStation/pull/8404

**Pull request closed without merging**
