### PR TITLE
[MIRROR] Fixes pubby's missing tiles and a cleans a few other maps.

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40147
--------------------
Pubby was making use of quite a few icon_state floors in R&D and other parts of the map which no longer existed, so we had purple/black tiles. The other map change are to move asteroid plating into plating with asteroid sand decals since I'm trying to move us in that direction and will be removing those paths shortly.

:cl: WJohn
fix: Fixed pubby's bugged R&D tiles.
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
ok so the diff is different but all I did was copy paste tgs current to this PR so it should all be good.

**Comment by GuyonBroadway** [comment]
THERE ARE NO CONFLICTS!!! GOD DAMNIT GITHUB!!

**Review by GuyonBroadway — DISMISSED** [review]

**Comment by Carbonhell** [comment]
what are you approving? you destroyed this PR

**Comment by GuyonBroadway** [comment]
I didn't approve anything. I've been trying to fix this locally on and off for the past week but my github-fu is lacking.

**Comment by GuyonBroadway** [comment]
Oh right that approval.  That was a misclick.

**Comment by Carbonhell** [comment]
kek np, but i think you're better off just remaking the whole PR. It's easy, i can help you if needed. I just can't do it myself because i have local unfinished changes with my feature.

**Pull request closed without merging**
