### PR TITLE
513 compatibility

### PR DESCRIPTION
**Pull request by yoyobatty**
Makes 513.1490 byond work.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Comment by ghost** [comment]
This is from https://github.com/tgstation/tgstation/pull/47135

DO NOT UPDATE TO 513 YET.

**Review by ghost — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
Actually, don't merge this.

/tg/ only merged this to their `513` branch

**Comment by yoyobatty** [comment]
Big oof, I didn't even see those

**Comment by ghost** [comment]
Closed in favor of https://github.com/HippieStation/HippieStation/pull/12193

cuz I made it a branch on this repo so all maintainers can push to it

**Pull request closed without merging**
