### PR TITLE
Upon war deceleration, the code is auto set to red

### PR DESCRIPTION
**Pull request by ghost**
kinda makes sense

Alternative to #4641

### CODE REVIEW

**Comment by Sarcalogo** [comment]
No point at all. The Delta change exists purely so that greytiders do not fuck around with Security when there is a confirmed incoming nuke team. Red alert can be declared and is declared almost 100% of the time. You can't declare Delta. I also think this change is motivated purely by the fact that you are one of these greytiding shitstains.

I would also not be making code changes to a server you cannot play on (permanently) due to your ban.

**Comment by Pyko1** [comment]
I will have to remind that both delta and red have 5 shuttle call.

So it might need to be addressed...

**Comment by Sarcalogo** [comment]
No need to be addressed, as I said, Every time Nuke Ops declare war people immediately Red Alert anyway.

**Comment by Sarcalogo** [comment]
Also the Ops if they manage to log into a Comms console can just set it to green.

**Comment by ghost** [comment]
@Sarcalogo greytiders will fuck with sec no matter the code

**Review by ghost — APPROVED** [review]
Code OK

**Comment by PopNotes** [comment]
decelery

**Comment by Sarcalogo** [comment]
This PR was literally only opened because the person in question is a greytiding fuckwad (that is currently permabanned for it by the way) that knows they would get dunked and doesn't want it added. It contributes barely anything at all.  I'm going to fix the other PR and create a new one, this is just silly.

**Comment by ghost** [comment]
@Sarcalogo You don't need to remake your PR, the discussion can be moved here and changes can be made (since the PR came from the hippie branch)

**Comment by Sarcalogo** [comment]
@MoreRobustThanYou 
\>greytiders will fuck with sec no matter the code
Even if that is the case (and I dispute it, people won't greytide if they know they'll get executed for it) it means security doesn't have to deal with permabrigging/brigging someone and then having one of the other people on station with all access (everyone) just releasing them so they can fuck around some more. They can just jump straight to execution. And really what better time for Security to have reign over the full station? Syndicate just declared WAR on them.

**Comment by Sarcalogo** [comment]
@Chnkr 
If you mean changes to this PR, I don't think this guy is planning on changing anything. If you mean my closed one then nevermind.

**Comment by ghost** [comment]
@Sarcalogo Any maintainer can make changes to this PR

**Comment by JohnMcLaime** [comment]
But sac has a point.

**Pull request closed without merging**
