### PR TITLE
Emote sensor nanites!

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt
add: Emote sensor nanites. They can detect whenever you do a certain emote, and send a code when you do.
/:cl:

Yes, I tested this.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
>*wink
>explode

Nanites are going to be the new overpowered circuits by the end of this, aren't they?

**Comment by k-k-karma** [comment]
he wants to use it so he can use adrenal nanites even if he cant speak

**Comment by DaydreamPuppeh** [comment]
*snap

Spontaneously combusts

**Comment by ghost** [comment]
the best use for this is... FART SENSORS!

**Urist McNanites farts**
_You feel compelled to speak..._
Urist McNanites says, "TEE HEE I TOOTED!"



that is actually how i tested that this works

**Comment by Manly-Dwarf** [comment]
I was going to +1 this but after that description, I'm quite frankly terrified of this ever being added.

**Comment by ghost** [comment]
So that's a ++1 then!

**Comment by Lxtoofonea** [comment]
sure, seems cool, i love a good power game +1

**Comment by earthmoonjune** [comment]
sure, sounds neat +1

**Comment by ghost** [comment]
>ling adrenals were being heavily nerfed as part of the ling nerf reverts
>still insane amounts of resistance from the community, ended up being removed entirely

>this PR allows adrenals with little functional difference (which don't use up chemicals and have only a 2 min cooldown) to be put on any random person
>massive support for this, +1's everywhere

wat

**Review by yoyobatty — APPROVED** [review]
*deathgasp :^)

**Pull request merged**
