### PR TITLE
Adds "fist"

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
add: Wizards can now cast fist, punching with such ferocity that the first thing their fist collides with will be sent flying with such force that it cause a shockwave if they hit a wall and even moreso if they hit another person. 
/:cl:

[why]: People asked for it. It sounded like fun. 
https://youtu.be/P2NFpBdPlUc

### CODE REVIEW

**Comment by KayeArray** [comment]
looks fun +1

**Comment by ghost** [comment]
muscle wizard is a quality meme
+1

**Comment by praisenarsie** [comment]
#5000 and it's wasted on this.

**Comment by ghost** [comment]
>waste

u stop those words

**Comment by praisenarsie** [comment]
🗑

**Comment by PopNotes** [comment]
holy fuck that looks funny

**Comment by ghost** [comment]
amazing

**Comment by dreamcrab** [comment]
+998

**Comment by GuyonBroadway** [comment]
Hold off on merging this as some guy on tg is getting me a sprite.

**Comment by 2Dollarbill** [comment]
Quality meme +1

**Comment by ghost** [comment]
i cast +1

**Comment by GuyonBroadway** [comment]
@JohnGinanne  WHAT THE FUCK DID YOU DO TO MY PR?

**Comment by ghost** [comment]
Your PR needs to be updated to reflect the current state of the master branch, please update your PR and either (re)open it, or ask a maintainer to (re)open it.

**Pull request closed without merging**
