### PR TITLE
Thermite now leaves plating behind instead of a void to space

### PR DESCRIPTION
**Pull request by ghost**
:cl: REEEEEEEEEEEEEEEEEEEEEEEEEEE
tweak: Using thermite on walls no longes leaves a hole to space
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
chnkr, ninja said in irc that fix doesn't work

**Comment by praisenarsie** [comment]
so close

**Comment by KayeArray** [comment]
that was quick

**Comment by praisenarsie** [comment]
please?

**Comment by GuyonBroadway** [comment]
did you check this? Try 30u thermite on an r-wall.

**Comment by dreamcrab** [comment]
yes +98

**Comment by ghost** [comment]
Your PR needs to be updated to reflect the current state of the master branch, please update your PR and either (re)open it, or ask a maintainer to (re)open it.

**Pull request closed without merging**
