### PR TITLE
Adds monkey into rotation

### PR DESCRIPTION
**Pull request by ghost**
It's a hilarious mode, and it works, so why not?

:cl: Thefastfoodguy
add: Monkey is now in rotation
/:cl:

### CODE REVIEW

**Comment by dreamcrab** [comment]
first you want to get rid of lean because it makes black people and now you wanna add monkey

stay consistent please

**Comment by ghost** [comment]
@dreamcrab i hated lean because of the music mainly

**Comment by KayeArray** [comment]
So this is rev + zombies.

**NO thanks.**

**Comment by ghost** [comment]
@banthebantz No. Monkey virus takes time to take effect (can be cured). It's CREW vs PISSED OFF MONKEYS.

**Comment by ghost** [comment]
The few monkey rounds i've played were super fun

**Comment by PopNotes** [comment]
oh okay it's revs + zombie gotcha

**Comment by ghost** [comment]
no

**Comment by GuyonBroadway** [comment]
Xenos would be a better roundtype IMO.

it does what monkey does but better.

**Review by GuyonBroadway — APPROVED** [review]
Code is technically ok... sort of.

**Comment by Spacedong** [comment]
>jungle fever ever coming back

monkeys-laughing

**Comment by ghost** [comment]
Will reopen once https://github.com/tgstation/tgstation/pull/32431 is merged

**Pull request closed without merging**
