### PR TITLE
Blob Cuddling

### PR DESCRIPTION
**Pull request by ghost**
🆑 Thefastfoodguy
add: you can now erp with blobs
/🆑

### CODE REVIEW

**Comment by DinduStuffin** [comment]
-1
Same reasons as before. It'll encourage people who don't fight the blob to continue to not fight it, and will possibly entice people who do fight it to stop fighting it for some meme.

It'll encourage friendly cancer which is the kind of stuff that's already plaguing TF2. I don't think we need to take design lessons from Valve of all people.

**Comment by ghost** [comment]
honestly i'm indifferent to this
i like small fluff features and such since they give the game a nicer feel but "friendly" behaviours towards the blob is a bit iffy

**Comment by ghost** [comment]
ofc the blob can always send a blobbernaut to give the ERPer hugs

**Comment by PopNotes** [comment]
-1

**Comment by ghost** [comment]
-1 no

**Comment by DinduStuffin** [comment]
Sure they could but that means you have people intentionally making themselves easy bait for the blob to murder, effectively removing potential arms against the blob.

Terrible idea imo.

**Pull request closed without merging**
