### PR TITLE
[MIRROR] Replace area-wide fire overlay with reddening the lights

### LINKED ISSUE #35415: Remove the bad red overlay from fire alarms and replace them with emergency lights
firefox_2018-02-07_15-19-27
tldr remove the flashing red overlay from fire alarms and replace them with light tubes and bulbs turning into a red hue when the fire alarm goes off

@vuonojenmustaturska gave permission to make this ~~feature request~~ improvement request

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/38366
--------------------
:cl:
tweak: Fire alarms now redden all the room's lights, and emit light themselves, rather than applying an area-wide overlay.
fix: Fire alarms no longer visually conflict with radiation storms.
/:cl:

Fixes #35415.

|**Old Appearance**|**New Appearance**|
|-|-|
| space station 13 2018-06-08 141618 | ss13 superbox station 13 2018-06-08 141003 |
| space station 13 2018-06-08 141645 | ss13 superbox station 13 2018-06-08 141054 |
| space station 13 2018-06-08 141654 | ss13 superbox station 13 2018-06-08 141103 |
| space station 13 2018-06-08 142952 | ss13 superbox station 13 2018-06-08 143157 |

## Originals for reference
ss13 superbox station 13 2018-06-08 141239
ss13 superbox station 13 2018-06-08 141214

### CODE REVIEW

**Comment by Jujumatic** [comment]
this gives a way better ambience.

cool

**Comment by Jujumatic** [comment]
```_maps/map_files/HippieStation/hippiestation.dmm:5003:error: undefined type: /obj/machinery/firealarm/partyalarm
_maps/map_files/HippieStation/hippiestation.dmm:5004:error: invalid variable name: name
_maps/map_files/HippieStation/hippiestation.dmm:5005:error: invalid variable name: pixel_x
_maps/map_files/HippieStation/hippiestation.dmm:5008:error: unknown type
```
 FUCK SOMEONE FIX THIS RRRREEEE

**Comment by Jujumatic** [comment]
we can probably merge this while keeping party alarms

wtf even are party alarms?

do yall want to keep it or no?

**Comment by Pyko1** [comment]
party alarms are one of the greatest thing known by the fire alarm industry

**Comment by praisenarsie** [comment]
ayyy my feature request got merged

**Comment by praisenarsie** [comment]
i removed the party alarm from the map, if you want to re-implement it, be me guest. i just want this mirror merged.

**Comment by Carbonhell** [comment]
tg literally removing fun
wow

**Review by praisenarsie — APPROVED** [review]

**Pull request merged**
