### PR TITLE
Carbonhell now spawns with the proper face

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Kawaii-Big-Boss
add: Carbonhell now spawns like a proper italian.
/:cl:

[why]: # This time without life checks.
https://en.wikipedia.org/wiki/Pizza
https://en.wikipedia.org/wiki/Calzone
https://en.wikipedia.org/wiki/Spaghetti
https://en.wikipedia.org/wiki/Pasta
https://en.wikipedia.org/wiki/Benito_Mussolini
https://en.wikipedia.org/wiki/Armistice_of_Cassibile
https://www.theguardian.com/world/1943/sep/09/secondworldwar.italy
https://www.youtube.com/watch?v=czTksCF6X8Y

### CODE REVIEW

**Comment by LuisReyesX** [comment]
+1 should be merged ASAP

**Review by KayeArray — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
https://youtu.be/Y0umNlvpKBo

**Comment by praisenarsie** [comment]
no

**Comment by Manly-Dwarf** [comment]
killing self 4

**Pull request closed without merging**
