### PR TITLE
Dildos2

### PR DESCRIPTION
**Pull request by Eagle-Eyess**
:cl: EagleEyes
add: THEY have been added...
/:cl:
Part 2 of my plan returns stronger than before. Again I am adding 1 of each dildo to the map for a total of three. One in the secret chaplain room, one in curators office and 1 in the clowns locker.

image
image
image

This will finally allow plebs to receive the magnificent weapon without help from the gods. An item as memey as this NEEDS to be open to the public.
I'll kill those who use them for evil.

### CODE REVIEW

**Comment by Jujumatic** [comment]
Stop......

**Review by Jujumatic — APPROVED** [review]

**Comment by Lxtoofonea** [comment]
no, for the love of god no

**Comment by Jujumatic** [comment]
you gotta write it as a number.... kid 😏

**Comment by Eagle-Eyess** [comment]
seems like a +1 to me

**Comment by mikolaj007** [comment]
+1

**Comment by Majick1** [comment]
+1, curator office is a weird choice though

**Review by yoyobatty — APPROVED** [review]
You guys liked it enough

**Pull request merged**
