### PR TITLE
[MIRROR] Ban system and interface update

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/41176
----------------------------
Spiritual successor and extension to #17798, an almost entire rebuild of the SQL ban system backend and interface.
Bantypes are removed per #8584 and #6174. All bans are now 'role bans', server bans are when a ban's role is `server`. Admin bans are a column, meaning it's possible to ban admins from jobs.
Bans now have only an expiry datetime, duration is calculated from this when queried.
`unbanned` column is removed as it's superfluous, checking unban status is now done through checking `unban_datetime`. `unban_round_id` column added. Each `ip` and `computerid` columns rearranged so `ip` is always first, like in other tables. Bans now permit a null `ckey`, `ip` and `computerid`.

Ban checking is split into two procs now `is_banned_from()` does a check if a ckey is banned from one or more roles and returns true or false. This effectively replaces `jobban_isbanned()` used in simple `if()` statements. If connected a client's ban cache is checked rather than querying the DB. This makes it possible for a client connected to two or more servers to ignore any bans made on one server until their ban cache is rebuilt on the others. Could be avoided with cross-server calls to update ban caches or just the removal of the ban cache but as is I've done neither since I think it's enough of an edge case to not be worth it.
The second proc is `is_banned_from_with_details()`, this queries the DB for a role ban on a player's ckey, ip or CID and returns the details. This replaces direct queries in `IsBanned.dm` and the preferences menu.

The legacy ban system is removed.

The interfaces for banning, unbanning and editing bans have been remade to require less clicking and easier simultaneous operations. The banning and jobban panel are combined. They also store player connection details when opened so a client disconnecting no longer stops a ban being placed.

New banning panel:
banning
Key, IP and CID can all be toggled to allow excluding them from a ban.
Checking `Use IP and CID from last connection` lets you enter only a ckey and have the DB fill these fields in for you, if possible.
Temporary bans have a drop-menu which lets you select between seconds, minutes, hours, days, weeks, months and years so you don't need to calculate how many minutes a long ban would be. The ban is still converted into minutes on the DB however.
Checking any of the head roles will check both of the boxes for you.
The red role box indicates there is already a ban on that role for this ckey. You can apply additional role bans to stack them.

New unbanning panel:
unbanning
Unbanning panel is now separate from the banning panel but otherwise functionally the same.

Ban editing panel:
edit
Actually just a modified banning panel, all the features from it work the same here.
You can now edit almost all parameters of a ban instead of just the reason.
You can't edit severity as it's not really part of the ban.
The panels have been tested but I've not been able to get my local server to be accessible so ban functionality isn't properly confirmed. Plenty of testing will be required as I'd rather not break bans.
DNM pending schema changes by @MrStonedOne 
@nfreader 

:cl:
admin: Ban interface rework. The banning and unbanning panels have received a new design which is easier to use and allows multiple role bans to be made at once.
prefix: Ban search and unbanning moved to unbanning panel, which is now a separate panel to the old banning panel.
/:cl:

### CODE REVIEW

**Comment by yoyobatty** [comment]
That's a lot of web edits

**Comment by yoyobatty** [comment]
This is going to need a local test, a test merge + DB update before it gets merged.

**Comment by yoyobatty** [comment]
Big oof, was forcing humans into catbeasts due to `not` logic.

**Review by yoyobatty — APPROVED** [review]

**Comment by TDcoolguy300** [comment]
Merge something like this again without directly tellling me "HEY THIS WAS MERGED" With a link to it, and i'll fucking revert it

**Pull request merged**
