### PR TITLE
[MIRROR] Fixes misc. map issues

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/29386
--------------------
Fixes / corrects numerous incorrectly colored/orphaned/unconnected pipes.

Fixes / corrects numerous orphaned/unconnected wires.

Fixes / corrects missing APCs and the areas around orphaned APCs

Added missing air alarms + var cleanup.

Fixes #29408

### CODE REVIEW

**Comment by Carbonhell** [comment]
pr broke aaaa

**Comment by KayeArray** [comment]
ree

**Review by j-mie — APPROVED** [review]

**Comment by Carbonhell** [comment]
why did you approve no changes wot

**Comment by Carbonhell** [comment]
@JamieH this PR is bugged, what should we do

**Pull request closed without merging**
