### PR TITLE
[FREEZE] Manually merges /tg/ back onto hippie

### PR DESCRIPTION
**Pull request by ghost**
People keep breaking the game, so i had to do this again

- [ ] (re)fix the hippie map
- [ ] (re)merge the previously merged hippie pulls

### CODE REVIEW

**Comment by ghost** [comment]
I hope this fixes the Atom subsystem taking 4~ minutes to load

**Comment by ghost** [comment]
there's no game like a broken game

**Comment by GuyonBroadway** [comment]
https://youtu.be/DtRNg5uSKQ0

**Comment by ghost** [comment]
Going to be reopening this PR later as /tg/ reverted some things that are in this branch, expect a few more hours before this is fixed

**Comment by ghost** [comment]
@Chnkr I don't have to rebase my PRs again, right?

**Pull request closed without merging**
