### PR TITLE
[MIRROR] Adds the Chemistry Smoke Machine

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/30920
--------------------
[Link to Screenshot with UI](https://i.imgur.com/UTR4Ifv.png)

Chemists will now get a smoke machine board in their office. The smoke machine does exactly what it sounds like, makes smoke from whatever you dump into the machine. The range of the smoke is adjustable but larger range means greater chemical consumption. 

The possibilities are endless! Make a tricord smoker in the medbay lobby, marvel as everyone can get healing chems just by standing around the medbay, marvel further as everyone starts to OD on tricordazine and you have to flee from a lynch mob. Make yourself a space drug den in maint, or team up with the bartender to start the station's first aerosol bar. Or, god forbid, some less-than-honorable individuals fill the machine with space lube, teslium, skewium, cyanide, etc!

Chemistry has always been missing its full potential, because outside of [OP CHEM OF THE YEAR] your options for dispersing your product are lackluster. Grenades can take minutes to produce for 10 seconds of smoke and pills/patches just mean you're a glorified fridge stockboy. Plus nobody trusts a chemist distributing their goods in the field because you can never verify what they're giving you. The machine can be inspected by anyone to verify what is being pumped. For combat, it also opens the doorway to a whole new brand of tactics and lets chemistry unleash its full potential. 

:cl: Robustin
add: The Chemistry Smoke Machine! Chemist offices will have a board available should they choose to construct a smoke machine. The smoke machine will regularly produce smoke from whatever chemicals have been inserted into the machine. Designs for the circuitboard are also available at RND. 
/:cl:

It's been tested and everything looks good. The only thing left is for me to decide if Chemist's can lock the controls or not.

### CODE REVIEW

**Comment by Spacedong** [comment]
lmao

**Comment by KayeArray** [comment]
what's so funny bud
huh?
HUUUUH?
HUUUUUUUUUUUUUUUUUUUUUUUUUUUH?

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
By the way, for when https://github.com/tgstation/tgstation/pull/31522 gets merged, I fixed our docking port in this PR

**Comment by PopNotes** [comment]
hee hee

**Pull request merged**
