### PR TITLE
Adds mining mech + TG Windows,vents,scrubbers have been fully added.

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: Round start mining mech
add: More air vents (One side of a firelock had just a scrubber and the other just a vent in many areas)
fix: Did a final checklist and replaced all the old vents scrubbers and windows + repaired any deleted pipes from rebasing.
tweak: Little map cleanups and consistency checking.

/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Review by praisenarsie — APPROVED** [review]

**Pull request merged**
