### PR TITLE
new boomerang sprites (BY MR EPIC SAX)

### PR DESCRIPTION
**Pull request by ghost**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: wood boomerang, riot, and repeaterang have new sprites ALL by mrepicsax
/:cl:

## Why It's Good For The Game

Updates 3/5 of the newly added boomerangs with new sprites (the repeaterang also has a new animation)

dreammaker_jSuEIvgOqO

### CODE REVIEW

**Comment by SireTurret2** [comment]
terrible

**Comment by ghost** [comment]
🦼

**Review by yoyobatty — APPROVED** [review]
Good stuff

**Comment by carlopault** [comment]
-2

**Pull request merged**
