### PR TITLE
Antagonist tips

### PR DESCRIPTION
**Pull request by ghost**
image

:cl: Steamp0rt and Lunaman
add: Antagonists now have a mini-tutorial!
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
And by "antagonists" you mean "traitor", but this is quite nice.

**Comment by notoriousBIGGIOS** [comment]
+1

**Comment by cris5311** [comment]
+1

**Review by yoyobatty — APPROVED** [review]
Thank you Kanye, very cool.

**Comment by ghost** [comment]
I think this is good to merge. If you need to add any more tips you can add them to another PR.

**Comment by ghost** [comment]
damn me for not making it obvious that not all antags had tips yet

**Pull request merged**
