### PR TITLE
Refartcors butts!

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
fix: Butts can now fly off into the galaxy once more.
refactor: Buttcode is now more flexible ready for butt related traits. 
/:cl:

[why]: Buttcode was butts.

### CODE REVIEW

**Review by JohnGinnane — APPROVED** [review]
Looks good to me, did you test this?

**Comment by tortellinitony** [comment]
Can you do defines instead please?

**Comment by tortellinitony** [comment]
Nevermind I see what you did

**Comment by JohnGinnane** [comment]
I had the same thought myself haha

**Comment by GuyonBroadway** [comment]
I have some traits that modify these but didn't want to add them in this PR.

While closely related you should never ever see the refactor and feature tags in the same PR.

**Pull request merged**
