### PR TITLE
[MIRROR] Adds an dart-synthesizing dartgun for CMO/Chemist traitors

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35906
--------------------
:cl: Astral
add: Traitor CMOs and Chemists, for 12 TC, can now get a reagent dartgun, which is capable of synthesizing it's own syringes, but does so slowly, and can be easily identified as syndicate by anyone who isn't blind!
/:cl:

 
Reagent Dartgun: left, Syringe Gun: right

### CODE REVIEW

**Comment by KayeArray** [comment]
lmao wtf

**Comment by JohnGinnane** [comment]
this looks like fun

**Comment by Carbonhell** [comment]
basically a mini dart gun on steroids... Fucking tg

**Comment by Manly-Dwarf** [comment]
>Sprite is a shitty recolor even though we already have a sprite like this
>Barely an upgrade from the Dart Gun
>Goon feature rip-off (this is just the Goon syringe gun for traitor MDs over there)
>Ridiculously overpriced
>Science can already make something better than this, but for free.

I need to make /tg/ bingo card at this point, holy FUCK.

**Comment by GuyonBroadway** [comment]
this is actually a  copy of a goonstation item... bar perhaps the sprite.

**Comment by ghost** [comment]
12 TC is too steep.
The "utility" from this item comes from the fact it's easier to reload on the fly.
You get, 4 ammo max, 25 seconds between each new round. You cannot manually load it either.
All you supply is your deathmix of choice which is meant to be easier to use since you don't have to manually load each syringe and load it.

Also, from what I understand, it is still countered by thick material so don't bother using it as such.
And since it's easily identifible as a traitor item, it doesn't even have the advantage of stealth.
I think it should be around 5 TC or something.

**Comment by Carbonhell** [comment]
I would prefer this to be ingame only as adminspawnable material, instead of being in the uplink. Looks like total shit.

**Comment by Manly-Dwarf** [comment]
This:
>12 TC
>4 shots, you have to load in reagents manually.
>**25 seconds between each shot**
>Doesn't come with a deathmix already (cough cough lethal syringes)

Mini Energy Crossbow:
>12 TC
>1 shot, automatically reloads - nothing required
>2 seconds between each shot
>1 shot = instawin

I dunno, Bawb. Price sounds fair to me.
smug_high-res

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
