### PR TITLE
[MIRROR] Fixes space cat resting sprite

### LINKED ISSUE #16523: Space cats doing the lay down position have a dead icon
ss 2016-03-31 at 11 22 54

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/32957
--------------------
Fixes #16523

The resting animation used the dead one as a base so the helmet appeared smashed when the cat laid down.

🆑 ShizCalev
fix: Space cats will no longer have a smashed helmet when they lay down.
/🆑

image

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
build this

**Comment by GuyonBroadway** [comment]
What the fuck is wrong with this pr?

**Comment by ghost** [comment]
someone merged code that doesn't compile into master

**Comment by GuyonBroadway** [comment]
Check the jenkins logs, its some shitty "cannot find hippiestation.dme"

**Comment by ghost** [comment]
```
16:48:00 hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm:13:error: origin_tech: undefined var
16:50:00 hippiestation.mdme.dmb - 1 error, 0 warnings (11/22/17 4:50 pm)
```

**Comment by Pyko1** [comment]
errywing fine, besides jenkem travis

**Comment by GuyonBroadway** [comment]
I can;t even tell Jenkins to BUILD THIS so this one is fukt

**Comment by KayeArray** [comment]
build this

**Review by GuyonBroadway — APPROVED** [review]

**Comment by praisenarsie** [comment]
its fine, just merge it. either travis is retarded or someone retarded merged a pr with an undefined var.

**Pull request merged**
