### PR TITLE
Modularises disarm rework and keeps old version REVIEW WITH SCRUTINY

### PR DESCRIPTION
**Pull request by ghost**
This should add absolutely nothing to the game and is ideally nothing except a code rework. Please review with absolute scrutiny to make sure this is indeed the case.

Quick Rundown:
Constants and helper functions were kept since they are never used. The additions were all commented out using block comments with no newline, all for the sake of github not throwing out random merge conflicts.

### CODE REVIEW

**Comment by Jujumatic** [comment]
No fuck off

**Comment by Eagle-Eyess** [comment]
I like the idea of removing rng from disarming but I feel this will nerf it too much. -1

**Comment by Lxtoofonea** [comment]
-1, go away no

**Comment by yoyobatty** [comment]
I thought we liked removing RNG? Also if you want, list the stuff you wish to keep and I'll take out the rest.

**Comment by ghost** [comment]
wait, hold on. How is this a nerf? Disarms are now stronger than ever, not to mention more fair than ever. Did any of you even read the PR or even try the new disarms? God fucking damn it

**Comment by zamolxius** [comment]
this is trash

**Comment by DaydreamPuppeh** [comment]
-1

**Comment by ghost** [comment]
reopening this so I can modularise this lazy ass shit

**Review by Jujumatic — APPROVED** [review]
Fuck shoves I'll shove this up their peepee

**Comment by ghost** [comment]
if this fucks up it's all @Jujumatic 's fault

**Pull request merged**
