### PR TITLE
Adds 2 adminbus guns, Singulo and Tesla spawners

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
admin: Added a adminbus singularity and tesla spawner gun
/:cl:

## About The Pull Request
Basically title, singulo spawner makes a projectile that acts similar to a singularity in that it sucks everything and gibs whatever it touches, however it deletes like a normal projectile once it touches an object. The next thing is an adminbussed version of the tesla revolver in which it spawns the same projectile with a lot more energy and has the same flags as the tesla so it can and will blow up and kill everything it touches.

These are super lame/cool items which are sure to make round ends hilariously funny and chaotic. Just hope the crew doesn't get it as they are SURE to end the round very quickly whilst also 99% likely gibbing themselves in the process.

## Why It's Good For The Game
Good for badmin bussing I guess.

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by Manly-Dwarf** [comment]
what have you brought to this land

**Comment by mememanrino** [comment]
I AM THE GOD OF HELLFIRE

**Comment by Manly-Dwarf** [comment]
add a version that spawns a singulo right on top of you and kills you
does nothing else

**Comment by carlopault** [comment]
+1

**Comment by cb583** [comment]
shilled this in ooc -100000000
+1 for cool though

**Review by ghost — APPROVED** [review]

**Comment by AnthonyJNgo** [comment]
Lol, this is hilarious +1

**Pull request merged**
