### PR TITLE
Tgui next stuff (Sorry for the stupid amount of commits)

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
add: Tgui-next has been ported
/:cl:

## About The Pull Request
Ports tgui-next from TG

## Why It's Good For The Game
Super fast, robust, nice looking and extremely easy to use interface that doesn't take years to load, is actually maintained like crazy and is fucking modern. Enjoy.

### CODE REVIEW

**Comment by actioninja** [comment]
I really strongly suggest holding off on a port for now. tgui-next is still in pretty heavy development and the design practices and apis haven't fully stabilized yet.

**Comment by Manly-Dwarf** [comment]
which is why we should merge it! burn the server down!

**Comment by ghost** [comment]
@actioninja isn't /tg/ using it... in production?

**Comment by actioninja** [comment]
That's implying production isn't the testing ground on tg

More seriously, it's still getting a shitload of ui conversions, backend improvements, and new features. It's "production ready" in the sense that it works, has the needed functionality for existing uis, and isn't very buggy but it would be a huge pain keeping any kind of downstream up to date with how frequently things are being changed and added.

**Comment by ghost** [comment]
I mean, the mirrorbot would still be up if not for our playerbase which just repeats "tg bad"

**Comment by stylemistake** [comment]
Yes, there will be a bunch of major refactorings in the upcoming months, it might be a pain in the ass to keep in sync. But keep it up gaymers, tgui hype!

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 3000452717e9eaf3152e0280c0a0d8393255861c
Pull Request: 7696d9ff03f80c8091e64ed8f59063b48d5de476
Server: 09f9c78f78f7a6f05f843773f9acf2e8e466a469

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 3000452717e9eaf3152e0280c0a0d8393255861c
Pull Request: 7696d9ff03f80c8091e64ed8f59063b48d5de476
Server: 16bd4d6f35c089500686e67f9667100449567dc7

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: cfde98e5d448bda1fcaa4713c2bd1b303a7a2596
Pull Request: 39d67ccad91ec4fad4919785847907099e46e492
Server: ef0dac579199a7fa7cc23f772d457b7983e6bc2c

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: f5968a07101222fe480bece730b079d407540452
Pull Request: 39d67ccad91ec4fad4919785847907099e46e492
Server: b0f9139db3fd2317e881554a051ee0b7d5c77c10

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: dbc79ecbd0345cb332d1dcaf2809aae4cc155b30
Pull Request: 39d67ccad91ec4fad4919785847907099e46e492
Server: c15f78b5c46931132247be3b3ff8c8cf8d3d97f8

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
#### Test Merge Removed

**Pull request merged**
