### PR TITLE
you can now use 50 units of mutagen to mutate plant species 

### PR DESCRIPTION
**Pull request by RafRoq**
:cl:
now you need 50 mutagen or 100 uranium/radium to change plant species with 100% chance
:cl:

before it was 5 units of mutagen,10 uranium/radium for a 10% chance, 1/10 so makes sense making it 10x more, and because rng suck dick

### CODE REVIEW

**Comment by Carbonhell** [comment]
Yeah sure +1

**Comment by Carbonhell** [comment]
Fix the changelog btw

**Comment by TheMeatGod** [comment]
+1, makes sense

**Comment by Maroonenahmoron** [comment]
+1, shouldn't have to spam 5u and waste precious mutagen

**Comment by earthmoonjune** [comment]
Sure +1

**Comment by RafRoq** [comment]
@yoyobatty

**Comment by ghost** [comment]
@uBadush procs don't work like object definitions, you probably need to put the chemical amount check into the /tg/ proc.

**Comment by RafRoq** [comment]
@HideAndSeekLOGIC  you are right

**Review by Jujumatic — APPROVED** [review]
Sexy

**Comment by RafRoq** [comment]
I think this have enough head inputs and is working, free to merge

**Comment by Manly-Dwarf** [comment]
botany

**Comment by Carbonhell** [comment]
Code is clearly broken... You need to remove one indent from ..()

**Pull request merged**
