### PR TITLE
Revert genetics analyzer to old behavior

### PR DESCRIPTION
**Pull request by ghost**
:cl:
balance: Revert genetics analyzer to old behavior
/:cl:

### CODE REVIEW

**Comment by lunaman22** [comment]
+1

**Comment by NautilusViper** [comment]
what exactly is old behavior

**Comment by ghost** [comment]
@NautilusViper it shows up in chat rather than you needing to click through some nasty UI.

also no cooldown

**Comment by NautilusViper** [comment]
> @NautilusViper it shows up in chat rather than you needing to click through some nasty UI.
> 
> also no cooldown

boolin
+1

**Review by yoyobatty — APPROVED** [review]
Needs more votes

**Comment by cris5311** [comment]
+1
for obvius reasons

**Pull request merged**
