### PR TITLE
Sseth sounds

### PR DESCRIPTION
**Pull request by ExpAntique**
## Changelog
:cl: ExpensiveAntique
add: added round-end sounds from a hippie station review meme sseth made
/:cl:

## About The Pull Request
 Adds a couple of round-end sounds from this video: https://youtu.be/dqmimHrYeAM 
made by ssethtzeentach, spoofing this video: https://youtu.be/O1xXiUX30tU
the absolute lad even mentioned (slightly) more recent members of the mod team.
## Why It's Good For The Game
IDK, thought it was kinda funny to have these along with the classic lines, and out of all the youtubers to pull the rock away from our cave, sseth is kinda based tbqh.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
speedmerge

**Comment by ExpAntique** [comment]
> speedmerge

quick before the autists find out

**Comment by BarginMart** [comment]
YOU ARE WELCOME BTW

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by Lxtoofonea** [comment]
+1

**Review by yoyobatty — APPROVED** [review]

**Comment by yobob591** [comment]
+1 retard

**Comment by Majick1** [comment]
+1

**Comment by Jujumatic** [comment]
It's already merged STOP

**Pull request merged**
