### PR TITLE
Revert "Reverts atmospheric and computer icons."

### PR DESCRIPTION
**Pull request by ghost**
Reverts HippieStation/HippieStation#4904

@Chnkr and @JamieH both want no code standards? WE GOOD CODERS WON'T STAND FOR IT! WE NEED CODE STANDARDS!

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Hate to say it but the 24h rule only applies to balance changes as per
image

But I'll hold this PR to the same standards and if it gets a +3 or a -3 we can merge away lad.

**Review by GuyonBroadway — APPROVED** [review]

**Comment by ghost** [comment]
@GuyonBroadway can i have a discord invite link

**Comment by GuyonBroadway** [comment]
I can't give those out lad sorry.

**Comment by dreamcrab** [comment]
all you have to do is beg jamie for mercy and you will be allowed back

**Comment by ghost** [comment]
@dreamcrab I did SEVERAL times on IRC. I think jamie's offline now

**Comment by dreamcrab** [comment]
guess you will have to wait until tomorrow, use this time to reflect upon your past actions and how you can change your ways heading into the future

**Comment by ghost** [comment]
@dreamcrab you have perms to give me a discord invite, fucktard

**Comment by dreamcrab** [comment]
but you have not begged jamie to his satisfaction, that has nothing to do with me

now can you quit it with the name calling? this is the kind of thing i was talking about earlier

**Comment by ghost** [comment]
"HEY I'M DREAMCRAB I SUPPORT @JamieH's HYPOCRITICAL BREAKAGE OF CODE STANDARDS"

**Pull request closed without merging**
