### PR TITLE
Fixes car runtime at roundstart

### PR DESCRIPTION
**Pull request by Carbonhell**
:cl:
fix: Fixes runtime with the clown car at roundstart.
/:cl:

Also fixed a non-ordered entry in the dme

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
hol up mang this is all nano armour crap.

**Comment by Carbonhell** [comment]
I know? The nano defines, in particular NONE, was conflicting with a tg one for bitflags, so i renamed them all

**Comment by yoyobatty** [comment]
Jeez, I hope this doesn't mess with the new PR I'm working on. Porting component signals to the nanosuit to kill overrides.

**Comment by JohnGinnane** [comment]
Can they be undefined at the end of the file or are they used elsewhere? @Carbonhell @yoyobatty

**Comment by yoyobatty** [comment]
Keep the renames, if you like, undefined them

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
