### PR TITLE
Nerfs nanosuit armor block to 50% 

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
balance: Nanosuit no longer has 100% blocking with armor and energy left, it has been reduced to 50%.
balance: Nanosuit jumpsuit armor stats removed.
balance: Reduced limb damage morphine injection to 0.5u from 1u
del: Night vision goggles no longer force green vision.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

The reason why I feel this is necessary is simply because the armor mode is a load of shit. Combined with a shield and stun baton or esword, you're essentially unstunnable plus heavily resistant to all forms of attack. Reducing it to a 50% chance gives the crew a greater chance of taking on a robust wearer.

### CODE REVIEW

**Comment by Carbonhell** [comment]
Thank god +1

**Comment by Manly-Dwarf** [comment]
Yeah, shooting a guy five times with a taser and then hitting him twice with a stungun just to have him shrug it off and instantly oneshot you with hulk punches doesn't seem right in any way. It's not even like martial arts where it gives you downsides.

**Comment by ghost** [comment]
+1

**Comment by yoyobatty** [comment]
The armor is supposed to lose energy when shot with rounds. I didn't take it for account that a shield has a 50% block chance, so literally 50% of the time you would get hit which drained armor, then the other 50% you would just not get hit giving you enough time to recharge and not worry about your armor going out.

**Comment by lcass** [comment]
oh thank fuck this armour was so stupidly powerful, that being said give them non slip shoes instead otherwise they just get nerded by some dude with space lube.

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
