### PR TITLE
Hamon Martial Art

### PR DESCRIPTION
**Pull request by AnthonyJNgo**
:cl:
add: Added new things
/:cl:

## About The Pull Request

Adds a brand new martial art to the game, the Hamon martial art. The Hamon martial art consists of 5 different combos, each accomplishing different things. Disarm weapons from the hands of your opponents, use a hamon infused knee to drive the wind from their lungs, or finish them off completely with an overdrive. Currently only obtained via adminbus.

## Why It's Good For The Game

It's a new martial art. Once Pillarmen and Vampires are completed and merged I will modify this further to be their bane. Hamon should be the primary weapon against these antagonists. It is a new martial art and adds some content and nice references.

### CODE REVIEW

**Comment by AnthonyJNgo** [comment]
https://www.youtube.com/watch?v=EKAT3EGDAAk&feature=youtu.be

Code in action.

**Review by ghost — DISMISSED** [review]
good code, ignore the dme that was just a line endings thing

**Comment by cris5311** [comment]
+1

sure, why not

**Comment by ExpAntique** [comment]
+1

**Comment by Majick1** [comment]
+1 i'm about it, make vampire rounds more intense

**Comment by cb583** [comment]
+1, while we’re at it we should buff armstrong too

**Comment by Manly-Dwarf** [comment]
shiiizaaaaaa

**Comment by mikolaj007** [comment]
+1

**Comment by AnthonyJNgo** [comment]
Has enough +1s from others, marking this for batty to review then merge.

**Comment by biggiOS** [comment]
+1

**Comment by Knifepony** [comment]
JoJo references are good yes

**Review by yoyobatty — DISMISSED** [review]

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
