### PR TITLE
removes all traits, sets up the hippie specific files for writing our own

### PR DESCRIPTION
**Pull request by ghost**
:cl: McBawbaggings
del: All traits are removed. System isn't disabled and we're free to add our own.
/:cl:

People don't like the defined the traits here, no one is disabling it configwise but we can modularise it nicely anyway and do our own stuff.

Currently disables all traits but we can port about the ones we like or add future ones

### CODE REVIEW

**Comment by earthmoonjune** [comment]
yes +1

**Comment by Manly-Dwarf** [comment]
yee

**Comment by earthmoonjune** [comment]
the tg menace slowly crumbling down https://www.tenor.co/Mhoc.gif

**Comment by ghost** [comment]
+1, i think traits are really, really cool, but they just aren't for this server. at most, i would compromise for keeping only negative or neutral traits

**Comment by ghost** [comment]
as said, if you want some traits back, dump em in the right file and they'll be back
we can pick each exact trait we want here

**Comment by Manly-Dwarf** [comment]
yes

**Comment by GuppyLaxx** [comment]
YES PLEASE

**Comment by ghost** [comment]
+1

**Comment by JohnMcLaime** [comment]
But they are optional and positive ones mostly act like quality of life improvements and positive traits arent "even" with negatives: i.e. you get 1 point for having a bad aim with guns.
When you jump into locked locker, you have to click on it to open (running out of it wont work), that has lower offensive potential.

Tableclimbing one, i havent tested, but i presume that it still keeps the tableclimb stun the same, even if it halves it or something, you are still vulnerable to a couple of shots. Has a potential for cool gimmicks tho.

Self awareness, kinda useless for 2 points.

Nightvision makes fully dark areas less aids, basically it lets you see 2 tiles away - same as we could see prebase.

What are other worthy traits? There are 2 positive traits which affect your mood (which presumably affects time consuming actions), i wonder how potent they are, considering that negative traits are kinda heavy.

Neutral trait which reverses "food taste" mechanic is good too, since it lets you eat raw meat and organs with no penalties, but thats mostly good for murderboning and you cant predict when you will get antag.

It is hard to tell which negative trait is the least damaging one. Heavy sleeper isnt worth taking imo, having a longer knockdown (tho i dont know by how many % it is increased) from explosions (fueltank rng intensifies) and chems isnt worth it.

Anxiety one blocks your speech on random (provides a message beforehand, rip voice nade when you need it), can be pretty annoying, a;sp makes you stutter sometimes 

Probably it is one which makes everyones face unknown, since it does so only for examining (when you mouseover it still shows their name, havent tested on people without an id tho), besides you can still see their id on examine list and hear who exactly is talking.

**Comment by Carbonhell** [comment]
i fucking hate this traits system, it's a bad copy of goon's one and it's shit, unfun and powergamey af
i'd rather remove and forget it,but this is okay too i guess
+1,merging

**Review by Carbonhell — APPROVED** [review]

**Comment by ghost** [comment]
There is nothing wrong with the traits system, the default traits are just bad

**Comment by ghost** [comment]
we could add the accent stuff from goon since that's just fun fluff

**Comment by GuyonBroadway** [comment]
Again suggestion, iron butt. Your ass has less chance to fall off when farting.

**Comment by ghost** [comment]
iron lungs, screaming is louder

**Comment by Jujumatic** [comment]
better yet have it make screaming not cause oxyloss damage

**Comment by GuyonBroadway** [comment]
Actually this reminds me, I need to refactor buttcode somewhat.

**Comment by Pyko1** [comment]
Should prolly add the TG traits back, but add a var if any trait is eligible for roundstart or not.
And then disable them as a normal option, but still allowing them to be used elsewhere/adminbus if needed.

**Pull request merged**
