### PR TITLE
Added a server restart vote and an emergency shuttle call vote - also some vote tweaks

### PR DESCRIPTION
**Pull request by Jujumatic**
So after seeing all the complaints on the forum I decided to revert @JohnGinnane's #7552 and instead placed both options as votes. So now you can start a restart vote, or a shuttle call vote. The shuttle call vote calls an emergency shuttle, sets it as unrecallable and sets its timer to 5 minutes, to give traitors just enough time to collect their objectives and head off without making the ghosts have to wait much longer. I think this is a fair compromise for everyone so hopefully this should help make everyone happy. I left the restart server vote in because sometimes MC dies when the shuttle docks at CentCom and there's no admins to restart the server - also as a failsafe in case the shuttle at any point fucks up for whatever reason

:cl:
add: Added a shuttle call vote. This vote calls the shuttle with a 5 minute timer.
add: Added back the restart server vote.
tweak: Not voting no longer automatically counts as a continue when voting to restart the round.
/:cl:

### CODE REVIEW

**Comment by Jujumatic** [comment]
@HippieStation/maintainers pls review and @HippieStation/head vote pls

**Comment by Jujumatic** [comment]
Fuck I forgot to mention - in the restart vote, a no vote no longer automatically becomes a continue vote. The shuttle call vote also does this - so a no vote does not automatically mean do not call shuttle. This should address some issues of afk players we've had stopping votes.

**Comment by Carbonhell** [comment]
This will just let malicious players restart rounds more easily if stuf doesn't go their way.

**Comment by Jujumatic** [comment]
@Carbonhell only in lowpop rounds but at that point then voting is a problem regardless

**Comment by Carbonhell** [comment]
People are used to not voting meaning voting no. This way we'll have a lot of unneedeed restart votes, why is this even needed?

**Comment by Jujumatic** [comment]
Because when the server legitimately needs a restart and no admemes are on to restart, there's usually a ton of afk people. Hence it's nigh on impossible to restart the world when it's actually needed

**Comment by ghost** [comment]
hmmmmmmm

**Comment by Maroonenahmoron** [comment]
If people are used to not voting means no, make the vote come with a notification (with even sound) so people will know what to expect straight away what this does

**Comment by Pyko1** [comment]
definitely not a big fan of the no vote change.

**Comment by Jujumatic** [comment]
maybe if erik brought back the changelog this wouldn't be so big of an issue :DDDDDDDDDDDDDD

**Comment by ghost** [comment]
+1. If you're not in the round, you should not be able to drag it on. If someone murderbones out all but like one or two people and the dead majority minimizes the game, waiting for it to end, which happens during actual rounds a lot _which you goddamn headmongs would know if you ever played the game_, then no reset votes will pass, the people are simply not there.

**Comment by Jujumatic** [comment]
are you FUCKING FAGGOTS HAPPY NOW 
image

**Comment by Jujumatic** [comment]
IT EVEN PLAYS A SOUND WHEN THE VOTE HAPPENS AAAAAGH

**Comment by Jujumatic** [comment]
no.... no!!!!! the fucking upstream!!!!!!!!!!!!!!!!!!!!!!! RRRREEEEEEEEEEEEEEEEEEEEE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Kendrickorium55** [comment]
what a surprise carbon is against this. a guy who never plays, never admins, never polices the forum or discord, thinks that because of a few shitters, everyone should have to suffer. if admins were actually ON, this whole pull would be a nonissue.

-enable the call the shuttle vote after 25 minutes, have it be a red alert shuttle
-enable restart server vote after 40 minutes

or,

-make it so that the call the shuttle vote doesnt _restart the fucking shuttle countdown timer_

**Pull request closed without merging**
