### PR TITLE
Added suicide message for Officer's Sabre.

### PR DESCRIPTION
**Pull request by ngl42398**
[Changelogs]: 
add: Suicide Message for Officer's Sabre (impalement)
New folder in hippie/code/games/objects/items "melee"(to match a folder in the tg code)
code: 
/obj/item/melee/sabre/suicide_act(mob/user)
            user.visible_message("<span class='suicide'>[user] is impaling [user.p_them()]self with [src]! It looks like [user.p_theyre()] trying to commit suicide!</span>")
            return (BRUTELOSS)

[why]: Figured some dumbass captain might want to commit seppuku. Perhaps the shame of getting robusted is too much to live with.

### CODE REVIEW

**Comment by Blute1** [comment]
changelog is badly formatted, you don't need to list any folders you added, we can see them in files changed

**Comment by Blute1** [comment]
also, refrain from using your master branch, make a new branch for every PR you do

**Review by GuyonBroadway — DISMISSED** [review]

**Comment by GuyonBroadway** [comment]
Dis looks ok. but fix the changelog.

**Comment by ghost** [comment]
when you fix the everything, i'll give you the +1

**Comment by ghost** [comment]
@GuyonBroadway nice review, dude hasn't even added it to the DME

**Comment by JohnGinnane** [comment]
@Blute1 @ngl42398 

Having those changes isn't a bad idea, but for the changelog (what appears on the server when you log on) should be maybe kept to something simple like

:cl:
add: Added a suicide message for Officer's Sabre
/:cl:

**Review by JohnGinnane — CHANGES_REQUESTED** [review]
Need to include the .dm file in hippiestation.dme

Open up the .dme in dream maker, navigate to where the file is and then tick the checkbox and save. You'll need to commit that (changes to hippiestation.dme)

**Review by ghost — CHANGES_REQUESTED** [review]
See @JohnGinnane his review

**Comment by ghost** [comment]
old and the branch is fucked badly anyways

**Pull request closed without merging**
