### PR TITLE
Removes Floorlength Bedhead

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Manly-Dwarf
del: Nanotrasen has standards on you cutting your fucking hair. Enough is enough.
/:cl:

## About The Pull Request
I don't know when this hairstyle got added, but it looks terrible on its own, then you combine that with hair potentially being neon and you have people walking around as horrible blue carpets, usually with japanese names. No, enough is enough.

## Why It's Good For The Game
Makes it possible to play the game without getting your eyes sore.

It's not even funny, too. It's just terrible.

### CODE REVIEW

**Comment by Majick1** [comment]
+1, it looks even dumber on ghosts

**Comment by mikolaj007** [comment]
-1, improve not remove

**Comment by Manly-Dwarf** [comment]
"Improve a horrible looking sprite"
yeah okay
how about just use regular long hair because it encompasses the same end goal, except less obnoxious

**Comment by mikolaj007** [comment]
alright, i see that you are actually mad about this. 
the "improve not remove" was a shitty joke.
without actually joking, im gonna say that theres nothing wrong with variety and that the sprite isnt that bad to warrant removal in my opinion.

**Comment by Manly-Dwarf** [comment]
That is a very fair opinion to have, and I respect wanting customization options in the game, but I don't think there's a point to "having more" when the more just turns out to be terrible and obnoxious. It's more stuff just for the sake of having more stuff, with no filtering.
That's not ideal at all. Plus it just looks terrible

**Comment by DaydreamPuppeh** [comment]
Not a designer but +1. Also remove neon hair and women

**Comment by mikolaj007** [comment]
alright, i guess all art is subjective. im just gonna let votes settle this one.

**Comment by Manly-Dwarf** [comment]
okay that might be goin a bit far xenon

**Comment by DaydreamPuppeh** [comment]
Okay then at least remove neon hair.

**Comment by ghost** [comment]
-1 I want to know who to dismember and leave with no access in maint

**Comment by NautilusViper** [comment]
+1 retarded hairstyles begone
also force wild colors to be dye-only to give chemists something to do
proposal addendum: clowns cannot have normal hair colors, they must always have neon vomit hair

**Comment by GuyonBroadway** [comment]
But the baldness+blackness virus just doesn't have the same impact if I can't turn all the snowflakes into generic identical people.

**Comment by ExpAntique** [comment]
+1 every floor-length hairstyle should be purged.

**Pull request merged**
