### PR TITLE
new titlescreen

### PR DESCRIPTION
**Pull request by praisenarsie**
:cl: Frozenguy5
add: Added a new titlescreen!
/:cl:

licenses are in order :card_file_box:

### CODE REVIEW

**Comment by Jujumatic** [comment]
not even "welcome to hippie station"

fucking disgusting

auto denied >:(

**Comment by praisenarsie** [comment]
it's from goon but also /vg/, i took the /vg/ version

**Comment by Carbonhell** [comment]
what the fuck,no

**Comment by ghost** [comment]
this already shows up sometimes hmmmmmm



but also no

**Comment by praisenarsie** [comment]
@Dudeinyourbackyard no it doesn't?

**Pull request closed without merging**
