### PR TITLE
Craftable Rubber Ducks.

### PR DESCRIPTION
**Pull request by TheTrigg**
## Changelog
:cl: SharkboySarrador
add: Rubber duckies can now be made on the service protolathe. Release the quacken!
/:cl:

## About The Pull Request
Yeah. Needed research is clown technology, and requires plastic to make (To throttle duck spamming). Buildable only on service protolathe because.. Well, it doesn't really fit into any of the other departments. Maybe cargo, actually. Maybe.

## Why It's Good For The Game
Honk?

### CODE REVIEW

**Comment by TheTrigg** [comment]
(And now I hope I didn't fuck anything up on my first PR. Oh, the tension.)

**Comment by diegoxt45** [comment]
this is beat!'s code so it's probably fucked up as hell don't merge

**Comment by AnthonyJNgo** [comment]
I took a look at it and it looks okay codewise, but at the same time it is 12:30AM here so I don't want to give it a review until I can double check it and ensure it is clean code. With that said +1 for the idea since I can't really see this being game breaking.

**Review by ghost — APPROVED** [review]
Code looks good to me, doin a merg

**Pull request merged**
