### PR TITLE
Botany Tech Tree Fix

### PR DESCRIPTION
**Pull request by ProtozoaPrime**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
add: Added Botanical Engineering research node, now you can actually make the botany stuff!
refactor: Moved Floral Somatoray to Tool Designs rather than Weapon Designs
/:cl:

## About The Pull Request
This PR came about from me wanting a floral somatoray, and of course, being unable to find one, research one or anything. So I did a bit of digging, and low and behold, the techweb node was completely fucked. So I polished her up and actually added these things back into the game. 
Truly showcases the amount of players we have doing botany.

## Why It's Good For The Game
Fixes a tech node and pretty much a whole job -> plus two person botany is now no-longer the world's biggest pain in the ass. Oh yeah, I'm also open to feedback as to the costs of the things, I did some private-hosted testing and it seems fair.

### CODE REVIEW

**Comment by MrEpicSax** [comment]
+1 you are truly a blessing to all us botanists everywhere

**Comment by Timmeye** [comment]
if it actually works then +1

**Comment by yoyobatty** [comment]
Bro you didn't need to comment out the entire section just to repaste and change one variable. You can simply edit and put a single line comment as we can see who has changed it via git blame

**Comment by ProtozoaPrime** [comment]
No worries, thought it would be simpler in future just to move it to the .dm where the category belongs (in case anyone goes looking for it), but I'll certainly defer to your judgement.

**Comment by AnthonyJNgo** [comment]
Good contribution +3

**Comment by Punkinguy** [comment]
based pr +10000 accepted

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
