### PR TITLE
Makes snacks, cola cheaper, buffs IED

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
balance: IED's are stronger, greytide worldwide
balance: Cola and snack vendors are cheaper, enjoy greyshirts
/:cl:

## About The Pull Request
Title because greytide worldwide, fuck sec, fuck command, fuck heads of staff!!

## Why It's Good For The Game
Makes it more practical for tiders to enjoy snacks and cola plus blowing up security is fun.
Seriously, these things are weak as shit. Let's enjoy the chaos and see how an extra explosion variable tweaked is capable of ruining the lives of whoever, whenever.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
don't care +1000000
merge this ASAP

**Comment by ghost** [comment]
+1 yeet

**Comment by enthethan** [comment]
An actual buff? You can't do that sorry nig

**Comment by FantasticFwoosh** [comment]
Why are these together, i dont associate IED's with market price of chocolate. I would have redone the PR and focused on one or the other (and least seperated the commit). Both of these are a meh from me anyway.

**Comment by Manly-Dwarf** [comment]
>why are these together

fwoosh, have you ever made an IED? what's one of the things it requires?

**Comment by FantasticFwoosh** [comment]
> > why are these together
> 
> fwoosh, have you ever made an IED? what's one of the things it requires?

Soda can, welding fuel, wire, after that it gets fuzzy because EID's are a cheap trick in my book and hardly worth bothering with, id rather just break some glass and spear someone in the face for improv but thats my personal taste.

The point you're making is not lost on me but mechanically having **_both on the same git commit_** is bad practice, should there be a kneejerk reaction that gets IED damage reverted, you have to yank the pricing out too. Its lazy and cuts corners unnesecarily.

**Comment by yoyobatty** [comment]
Or you can just nerf the IED separately by editting 1 var.

**Comment by cris5311** [comment]
+1
speedmerge this shit

**Comment by Manly-Dwarf** [comment]
>EID's are a cheap trick in my book and hardly worth bothering with, id rather just break some glass and spear someone in the face for improv but thats my personal taste.

that's why this PR is being made
and no, the change isn't bad practice honestly. the goal is to also make them more accessible. there is an almost 0 chance that this will become too powerful for its own good because water+potass grenades are still just as available and have never been nerfed nor do I think they should.
if you want to revert this change for whatever reason, all you have to do is edit a single var. anyone can do that in web editor. using the "revert" button on something as small as this is for lazy lazies who should not be PRing shit.

personally if I wanted to change IEDs I would just change grenades so you can more reliably use them for damage and not get banned because you breached the station, but that requires new explosion code which after spiralbombs I never want to see again. never forgive never forget.

**Review by ghost — APPROVED** [review]

**Pull request merged**
