### PR TITLE
Removes ayy and syndie tech for advanced nanites, but multiplies their price by 10

### PR DESCRIPTION
**Pull request by JF260**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
balance:Removes ayy and syndie tech for advanced nanites, but multiplies their price by 10
/:cl:

## About The Pull Request
I added this pull request because mining without access isn't easy, and even if you can get access, it's pure rng whether or not you get the gear you're after. With my changes, it takes about the entire round to get just one of these, but if you want to get one faster, you can use the tachyon-doppler array or drink yourself into a stupor.

## Why It's Good For The Game
One of my largest issues with the game is that it has so much wasted potential in the code. Once I become better at coding, i'll see if I can harness things like traumas or martial arts, but this is a good place to start.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Code looks good, now to wait for headmin approval

**Comment by ghost** [comment]
Change this from add/del to balance in the changelog

**Comment by RafRoq** [comment]
If the cost end being too high to the point of uselessness would you reduce it ?

**Comment by ghost** [comment]
@uBadush I'd say this cost is enough for now. If it ends up being too low, ping me and I'll try to make a PR. Also, sorry I couldn't get on that extra chemicals PR you asked me to do, I'll try to do it tomorrow

**Comment by Manly-Dwarf** [comment]
This sounds like it could end up being a complete disaster.
But more fun than circuits, probably. As long as there's no antistuns.

**Comment by Maroonenahmoron** [comment]
+1, give nanites use that isn't barred by certain events

**Comment by Jujumatic** [comment]
Now remove ayy tech from alien surgery mode and we can make zombos every extended round :DDDDDD

**Comment by JF260** [comment]
> If the cost end being too high to the point of uselessness would you reduce it ?

**Comment by JF260** [comment]
> This sounds like it could end up being a complete disaster.
> But more fun than circuits, probably. As long as there's no antistuns.

I might add adrenals to hazard in a later PR, or make a new category for them, along with a new nanite so I can actually call them a category, and make it fittingly difficult to get.

**Comment by Carbonhell** [comment]
Dunno, I do not like nanites very much. I would rather prefer someone more experienced with them to see if this is balanced.

**Comment by GuyonBroadway** [comment]
On the one hand, military grade nanites are powerful as fuck, on the OTHER hand 75000 will take fucking AGES to get, like it would have been quicker to break into mining yourself and scour the place for an ayylamo ship.

**Comment by RafRoq** [comment]
Guyon is right 75k is retarded amount

**Comment by RafRoq** [comment]
And rounds don't last more than 30min in average

**Comment by JF260** [comment]
> On the one hand, military grade nanites are powerful as fuck, on the OTHER hand 75000 will take fucking AGES to get, like it would have been quicker to break into mining yourself and scour the place for an ayylamo ship.

**Comment by JF260** [comment]
> Dunno, I do not like nanites very much. I would rather prefer someone more experienced with them to see if this is balanced.

I've worked on them for a good amount of time, they're decent at healing and you can meme people that have them with codewords, but i think their full potential is only unlocked with the advanced nanites, but the issue is that they aren't all that good. While the surgery can permanently mindslave someone, with nanites,  you need to carefully code to keep yourself safe while preventing the nanites from overworking themselves. They should be more reliable to get.

**Comment by Lxtoofonea** [comment]
+1

**Comment by Jujumatic** [comment]
nanites are fun but pretty gimmicky unless you really know what you're doing. i think this is balanced because it'll allow you to unlock all the nanites but only if you're far into the round. however it might end up being unlockable too far into the round to be useful, only able to be used in extended rounds. but in that case it's a super easy number adjustment. just a matter of trial and error from here on out

**Comment by earthmoonjune** [comment]
+1

**Comment by cris5311** [comment]
-1

It seems like 75k and 100k is quite a lot, considering how short a hippy round is. I like the generall idea, but the points are too high.

**Pull request merged**
