### PR TITLE
Chicken Cubes and Cow Cubes

### PR DESCRIPTION
**Pull request by carlopault**
image
image

## Changelog
:cl:
add: Chicken and cow cubes. Sprites by Mr. Epic Sax.
add: Chicken and cow cubes are in the biogenerator. 
/:cl:

## About The Pull Request
I plan to put this shit in the Animal Husbandry room. The chicken cubes cost 200 in the biogenerator and cow cubes cost 500. 

## Why It's Good For The Game
More content good.

### CODE REVIEW

**Comment by MrEpicSax** [comment]
too cheap, make chicken cubes cost 2000 and the cow cubes 4000 _at least_

also H on the chicken box is giving me a stroke

**Comment by carlopault** [comment]
> too cheap, make chicken cubes cost 2000 and the cow cubes 4000 _at least_
> 
> also H on the chicken box is giving me a stroke

It isn't like I can make the chicken box have a C on it. 

**EDIT**: I made the chicken cubes cost 3,100 biomass and the cow cubes cost 4,100

**Comment by carlopault** [comment]
image

Add these infinitely better sprites, provided by Mr. Epic Sax.

**Comment by MrEpicSax** [comment]
+1 carlos made changes I like

**Comment by wheezl** [comment]
make them cheaper lol

**Comment by mkikt4743** [comment]
make em 2000 for cows and 1000 for chicken

**Comment by cris5311** [comment]
+1. no matter the cost

**Comment by carlopault** [comment]
made chicken cubes cost 2,100 and cow cubes cost 3,100

**Comment by carlopault** [comment]
made chicken cubes cost 200 and cow cubes cost 500.

**Comment by mkikt4743** [comment]
Yeah now speedmerge

**Comment by cb583** [comment]
shilled in dms -1

+1 for the idea though, once husbandry is done

**Comment by wheezl** [comment]
+1 price is good

**Comment by MrEpicSax** [comment]
Already voted but I'm gonna +1 it again because I can AND NO ONE CAN STOP ME

**Comment by byandaccount** [comment]
+1 i like the chef having a ample supply of different animals he can butcher, plus animal husbandry stuff sounds neat.

**Comment by AnthonyJNgo** [comment]
+3 and has enough votes, good change

**Review by AnthonyJNgo — APPROVED** [review]
LGTM

**Pull request merged**
