### PR TITLE
[MIRROR] Sign restructure

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34527
--------------------
Splits apart signs.dm into seperate files for plaques, maps / directions, warning signs, and department signs. Makes new paths to cut down the massive ass convoluted tree of everything. 

Corrected a couple missing periods and other grammar issues.

Also removed the old DreamStation map signs, since the map was removed well over a year ago.

### CODE REVIEW

**Comment by Carbonhell** [comment]
Needs map repathing

**Comment by Pyko1** [comment]
added files to hippiestation.dme

**Comment by Pyko1** [comment]
lets see if got all the sign changes.

**Comment by Pyko1** [comment]
now with 100% more sign fixes on hippiecentcom

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
