### PR TITLE
Dildos can now fit in asses

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
fix: Dildos can now fit in asses
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
no

**Comment by ghost** [comment]
-1

**Comment by WallaceShark** [comment]
-1.

**Comment by DinduStuffin** [comment]
-1
Whether we keep dildos or not I think this would encourage ERP and I'd rather not do that even ironically.

**Comment by PopNotes** [comment]
rip

**Pull request closed without merging**
