### PR TITLE
Ports thief gloves and changes stripping system (Old Hippie Port)

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Thief gloves may now be purchased from the traitor uplink under stealthy tools.
tweak: The equipment stripping system now works like it did on old hippie.
/:cl:

Ported thief gloves from citadel, which are pretty much the exact same thing as pickpocket gloves from pre-REEEEEbase hippie. Also changes the stripping system to be like on old hippie, also ported from shitadel. All credit to the original authors.

Relevant PR: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10787

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
time to see what the hell you changed

**Comment by karmaisblackandbluepilled** [comment]
+3 fuck it lol

**Comment by ghost** [comment]
Code has been tested on a local server.

**Comment by ghost** [comment]
REEEEEEEEEEEE why isn't honkbot auto adding tags anymore? This is an old hippie port.

**Comment by karmaisblackandbluepilled** [comment]
it's dead

**Review by yoyobatty — DISMISSED** [review]
Not the worst code I've seen

**Comment by MrEpicSax** [comment]
+1 very good

**Comment by carlopault** [comment]
dufuq is old stripping system. I have noticed many PRs that bring back "old" Hippie stuff. Why tf was this "old" and "based" Hippie stuff even removed if everyone liked it so much?

**Comment by karmaisblackandbluepilled** [comment]
it was removed because hippie rebased from its old codebase to tgcode

**Comment by ghost** [comment]
Holy shit, that's one way to make a quick edit.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
