### PR TITLE
Adds Hippie icon check

### LINKED ISSUE #4964: Brass Chairs have no sprites
In-Game report from critiasblue:
Server info: 24552 (Hippie Station)

>General description of the issue
Brass chairs have no sprite, making them invisible

>What you expected to happen
I built a brass chair out of brass and expected a chair to appear

>What actually happened
No chair appeared and I had to right click the ground to see if it appeared

>Steps to reproduce if possible
Make a brass chair

### PR DESCRIPTION
**Pull request by JohnGinnane**
This is something that's been on my mind for a while now. The current problem is that if we want to revert any tg icons (e.g. chairs or computers), we create a copy of the .dmi under the HippieStation folder and then do what we want. If tg adds icons to their file (new brass chair), and we don't reflect this change somehow then there's a chance that we end up with invisible objects

There's a lot of files changed because we're overriding a lot of icons, so I've broken this up into 3 separate commits so it's easier to follow:

1. Creating a new variable and proc that checks if icon state exists in the hippie icon file
2. Fixed some icons not being modularised
3. Replaced all instances of us overriding the `icon` var with us setting the `icon_hippie` var, which is used in the proc created in the first commit

If `icon`, `icon_state`, and `icon_hippie` are all defined then we check if `icon_state` exists in `icon_hippie` file. If it does then we set `icon = icon_hippie` and so we end up with our sprites

Here you can see what we now do **if we want to override tg's icons**
image

Here's the result:
image

Just so you know, here's the search I used to replace all those files:
image

:cl: JohnGinnane
fix: Most, if not all, invisible icons caused by our doing
code: Added a new proc which verifies if the hippie icon is there before override tg's icon
/:cl:

Fixes #4964

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Local coder slaves his life away to fix a server, is the coder we need but not the one we deserve.

**Comment by ghost** [comment]
would this be worthwhile integrating into the unit testing subsystem?
https://github.com/HippieStation/HippieStation/blob/1de2cd91ae5e6704cd86cab0e71eb6c45a2f9cc0/code/modules/unit_tests/unit_test.dm#L18

**Comment by JohnGinnane** [comment]
yes, but i have no idea how to do that, is there like a guide or example case?

**Comment by ghost** [comment]
https://github.com/tgstation/tgstation/pull/34642
https://github.com/tgstation/tgstation/pull/35478
https://github.com/tgstation/tgstation/pull/36466

**Comment by JohnGinnane** [comment]
So what exactly would we be testing for? If an icon state is present in the hippie icon file? I kinda intended this to avoid that altogether. Like with the brass chair example, we shouldn't need to add the /tg/ icon to our file because we don't want to override it, but we don't have to override chairs, so the chairs pass but the brass chairs fail and stick with the /tg/ icon. This makes it much more hands off when it comes to managing overriding /tg/ icons

**Comment by ghost** [comment]
my brain slow today and i haven't really looked at how your code works, i read it as a way to check if a file is missing iconstates and thought it would be an idea to have it work like chem unit tests to ensure PRs on the github would report missing icon things and such

**Comment by JohnGinnane** [comment]
Yeah that would cause a headache if /tg/ created new icons for something and we wanted to stick with the old ones, we'd have to make sure all the icon_states in the icon file were present in our hippie version, and we shouldn't need to do that much work if we don't need to

**Comment by ghost** [comment]
god bless you john

**Comment by ghost** [comment]
This is straight up 🔥

**Comment by JohnGinnane** [comment]
I'm gonna remake this because I messed up again with git, trying to resolve that conflict

**Pull request closed without merging**
