### PR TITLE
Add windows to AI core (better now)

### PR DESCRIPTION
**Pull request by Majick1**
## Changelog
:cl:
add: Added windows to the AI core south area
/:cl:

## About The Pull Request

Replaces reinforced walls in front of AI with windows, allowing lethal turrets to get through

## Why It's Good For The Game

AI is currently a free kill to anyone with a jaunt skill or toolbox and locker, once you get inside the walls you're untouchable. This should hopefully make it require some effort to take down the brain of the station.

### CODE REVIEW

**Comment by yoyobatty** [comment]
Please check to see if you accidentally added a pipe somewhere, I spent forever redoing all the maps pipes

**Comment by Majick1** [comment]
Is something fucked or just a note, shouldn't have touched pipes

**Comment by NautilusViper** [comment]
Should add blast doors to all three windows. Defense mode or offense mode.

**Comment by Majick1** [comment]
All three windows do have blast doors

**Comment by Manly-Dwarf** [comment]
Do you have any screenshots or somethin?

**Comment by k-k-karma** [comment]
ok now i can lethal the AI to death?

**Comment by yoyobatty** [comment]
Only if they don't drop the blast doors, even then you'd have to enter from the SMES side

**Comment by Majick1** [comment]
Right here @Manly-Dwarf https://imgur.com/a/FJGfT13

**Comment by NautilusViper** [comment]
> Right here @Manly-Dwarf https://imgur.com/a/FJGfT13

bruh........... how is the AI going to use the console or read the display when they're behind the windows...................................... smh......................................................................................

**Comment by Majick1** [comment]
Gotta fix that later, they don't come up on the item list for that tile so couldn't move them to top. Also they don't ever get used anyway because people just spam chat for AI requests.

**Comment by yoyobatty** [comment]
Ahahaha, that's what I was afraid of. Also, don't place them on windows or they will be floating forever when they break, try to put them on the wall near the entrance to the core with the command style door.

**Comment by mikolaj007** [comment]
i'd love a picture

**Comment by Majick1** [comment]
Put up pictures a few comments ago

**Review by AnthonyJNgo — COMMENTED** [review]
Move the consoles that are on the windows onto a wall by the entrance or something. Otherwise, +1, merge after what I said is done.

**Comment by Majick1** [comment]
Just gonna close it, it's still treating the consoles like they don't exist no matter what I do

**Pull request closed without merging**
