### PR TITLE
Xcom gun changes

### PR DESCRIPTION
**Pull request by Timmeye**
Lowers damage to 17, (was 20) makes the gun a lot cheaper and does minor polishing of the sprite
unknown
unknown
**Top is the new version, bottom is the old one!**

### CODE REVIEW

**Comment by AnthonyJNgo** [comment]
+3 no one uses it because it’s ugly.

**Comment by MrEpicSax** [comment]
+1 blessed

**Comment by karmaisblackandbluepilled** [comment]
+2 Destroy IL

**Comment by Zyzarda** [comment]
+1 very good balance and visual changes.

**Review by Zyzarda — APPROVED** [review]
Nothing but number changes, seems good to me

**Review by AnthonyJNgo — APPROVED** [review]
Lgtm

**Pull request merged**
