### PR TITLE
Fixes cryo rapidly draining reagents

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
fix: Fixes cryo rapidly draining reagents
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by ghost** [comment]
Build finished.

**Comment by Arzion5** [comment]
>Implying it's a fix

I recommend turning it into a tweak and then appropiately renaming the PR. Cryo's reagent system has been modified by a TG PR.

**Comment by ghost** [comment]
@Arzion5 no, as in, cryo was draining 1u per second

**Review by ghost — CHANGES_REQUESTED** [review]
tg changes need tagging, read the readme in the hippie folder

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by ghost** [comment]
@Chnkr WOOPS, didn't notice I changed the /tg/ file rather than hippie one!

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by Arzion5** [comment]
@MoreRobustThanYou I'm pretty sure that's the "supposed" change, one unit in cryo = one unit in the person in cryo

**Comment by ghost** [comment]
Build finished.

**Comment by ghost** [comment]
Build finished.

**Pull request closed without merging**
