### PR TITLE
[MIRROR] Randomized Station Time + Night Shifts

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35775
--------------------
:cl: Kevinz000 & Deathride58
experimental: Station time is now randomized [if enabled in game_options configuration]. Station time is 1:1 with realtime, compensating for server lag ofcourse because it's based on world.time but with a randomized offset added to it. Adminhelp tickets will be adjusted to compensate. Station time now also ticks faster, by a default of 24:1 so 1 hour real-time is 24 hours station-time. Subject to debate.
rscadd: A separate round time has been added to status panel. This will start at 00:00:00.
rscadd: Night shift lighting [if enabled in the same configuration] will activate between station time 7:30 PM and 7:30 AM. This will dim all lights affected, but they will still have the same range.
rscadd: APCs now have an option to set night lighting mode on or off, regardless of time.
/:cl:
Credits to @ deathride58 for the lighting range/coloration and idea.
Screenshots by @ deathride58 
Normal/daytime lighting
image

Night shift lighting
image

### CODE REVIEW

**Comment by ghost** [comment]
what in gods name

**Comment by GuyonBroadway** [comment]
Dis could be funny, especially if the CE can toggle station wide night mode from his office.

**Comment by ghost** [comment]
love it

**Comment by ghost** [comment]
especially for european lowpop times 
perfect

**Comment by Carbonhell** [comment]
Config can be toggled on later on, but this requires tgui to be recompiled

**Comment by JohnGinnane** [comment]
are we merging this? @Chnkr @Carbonhell @Pyko1

**Comment by ghost** [comment]
Yes

**Comment by JohnGinnane** [comment]
fuck it, we'll do it live

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
