### PR TITLE
Removes tgui from pool controller

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
tweak: Pool controller no longer uses TGUI.
/:cl:

Now just the cryo and then we no longer need to maintain our own TGUI. It is being replaced soon as well.

### CODE REVIEW

**Comment by earthmoonjune** [comment]
death of tgui feelsgoodman +1

**Comment by checkraisefold** [comment]
-1 tgui is cool

**Comment by Manly-Dwarf** [comment]
your opinion matters not

**Comment by checkraisefold** [comment]
yes it does because tgui is the best

**Comment by Manly-Dwarf** [comment]
no I mean your opinion doesn't matter because only GM and HA votes actually count

**Comment by earthmoonjune** [comment]
btfo

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
