### PR TITLE
new overlay for burning

### PR DESCRIPTION
**Pull request by ghost**
:cl: zamolxius & crazy russians
imageadd: added new graphical overlay for burning for humans
/:cl:

## Why It's Good For The Game
xNy5uNh

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
don't risk russian randy's rage

**Comment by yoyobatty** [comment]
Where did you get this from?

**Comment by karmaisblackandbluepilled** [comment]
What's randy gonna do? DMCA us? he barely gives a shit about his own game anymore

**Comment by ghost** [comment]
reviews required @head administration

**Comment by yoyobatty** [comment]
You mean @Designers

**Comment by mikolaj007** [comment]
+1, very cool
as long as we don't get sued or anything

**Review by ghost — DISMISSED** [review]
it's a crazy russian he ain't gonna sue or DMCA shit

**Comment by Majick1** [comment]
+1 will the lower tiers be ported as well though?

**Comment by ghost** [comment]
well sure theres a really orange one for the lighter burns but for now its just the regular one

**Comment by Manly-Dwarf** [comment]
honestly doesn't look very good if you ask me

**Comment by ghost** [comment]
now makes even light burning look cooler

**Comment by ghost** [comment]
> honestly doesn't look very good if you ask me

it looks more like the firestacks off a person are burning which is how it seems to work in this strange 2d dimension 

also need more @designers

**Review by ghost — CHANGES_REQUESTED** [review]
did you make light and normal burning use the same sprite?
idiot

**Pull request closed without merging**
