### PR TITLE
Handles the fluffe menace

### PR DESCRIPTION
**Pull request by ghost**
AGPL additional terms to the rescue!

### CODE REVIEW

**Comment by Carbonhell** [comment]
Personally this is not a problem for me, thus -1

**Comment by optimumtact** [comment]
`You may place additional permissions on material, added by you to a covered work, for which you have or can give appropriate copyright permission.`

You cannot give appropriate copyright permission for code you yourself did not contribute, so you're either getting signoff from everyone else who has contributed any live code to this codebase or you're illegally restricting the copyright terms we have placed on our work.

**Comment by k-k-karma** [comment]
It's not modifying terms, it's clarifying them under the readme

**Comment by optimumtact** [comment]
The AGPL license makes no mention of the word "git history" you're attempting to modify it and illegally restrict content provided to your repo by myself and many others.

I don't have a problem with you wanting attribution for changes, but this is not it chief.

**Comment by ghost** [comment]
@optimumtact hows' that ya nerd

**Comment by alexkar598** [comment]
Still violating section 10

**Comment by optimumtact** [comment]
I'm not a lawyer but I would advise against changing a copyright license without consulting one.

**Comment by alexkar598** [comment]
You may not impose any further restrictions on the exercise of the
rights granted or affirmed under this License. -section 10

**Comment by ghost** [comment]
@alexkar598 

` You may not impose any further restrictions on the exercise of the
rights granted or affirmed under this License.`

We're not restricting the rights granted or affirmed under this license, we're simply activating another clause of the license.

**Comment by alexkar598** [comment]
All other non-permissive additional terms are considered "further
restrictions" within the meaning of section 10. -section 7

**Comment by ghost** [comment]
@optimumtact would you be willing to activate clause 7.f upstream?

**Comment by alexkar598** [comment]
Orange,please come in contact with every single license holder ie,everyone who ever coded something in ss13 so we can make an additional term to make mrty happy?

**Comment by skull132** [comment]
If you want to avoid stuff like this in the future, and I've been ass blasted myself at a lack of accreditation a few times, then just write a full copyright and ownership statement at the top or bottom of every file. Or, if you make modules, into the module folder. **Removal of copyright and ownership notices is forbidden by AGPL**, ergo, your "authorship notice" would have to remain intact.

**Comment by alexkar598** [comment]
Please quote the license,no where except in the non activated additional terms it is mentioned.

**Comment by skull132** [comment]
> 4. Conveying Verbatim Copies.
> You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice; keep intact all notices stating that this License and any non-permissive terms added in accord with section 7 apply to the code; keep intact all notices of the absence of any warranty; and give all recipients a copy of this License along with the Program.

If you prefix or suffix this to all of your files:
> The AGPLv3 license
> 
> Copyright (c) whoever
>
> [License body]

Then it should be kept intact, per the above clause. And it includes an accreditation.

**Comment by alexkar598** [comment]
Ah yes but that is sublicensing the work to ignore the normal codebase license which could work but might make some maints refuse to merge

**Comment by k-k-karma** [comment]
no it's not

**Pull request closed without merging**
