### PR TITLE
Brings back the HoloParasites

### PR DESCRIPTION
**Pull request by ghost**
See title, See changes.
:cl: ErikHanson
add: Holoparasites have once again been added to the traitor uplink.
/:cl

### CODE REVIEW

**Comment by ghost** [comment]
sutando i like

**Comment by ghost** [comment]
Add a change log actually.

**Review by GuyonBroadway — APPROVED** [review]
Code is good. Add a changelog and ill mergw.

**Comment by tortellinitony** [comment]
@chnkr Fix conflicts and add changelog

**Comment by GuyonBroadway** [comment]
Fixing this PR at the request of @Chnkr

image

**Pull request merged**
