### PR TITLE
[MIRROR] Fixes some mapping issues with the Pubby SM

### LINKED ISSUE #43049: pubby station supermatter does not keep power during a blackout
## Round ID:

N/A

## Testmerges:

N/A

>go to any other station with a supermatter
>grid check
>engineering APC keeps it's power going

>go to the wiki
>"Shuts down all APCs stationwide for 30 to 120 seconds, **with the exception of Engineering**. Usually leads to stationwide looting once Assistants crowbar open airlocks.
Can be fixed early by hitting the APC's "Reset" button."

what

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43047
----------------------------

## About The Pull Request

Fixes a couple of mapping errors and small complaints people had on the Pubby SM:

- Cooling loop size has been reduced
- Layer manifolds start on top level instead of below the floor
- Emitters and Reflectors start anchored, positioning has been slightly changed
- Freezers have been rotated to connect to pipes properly
- Filters have been switched to critical filters to prevent the APC from shutting off during a grid check
- Heaters have been removed

Closes #43049 

## Why It's Good For The Game

Fixes errors and some complaints

## Changelog
:cl:
fix: Fixed a few mapping issues with the Supermatter on Pubbystation
/:cl:

### CODE REVIEW

**Comment by Jujumatic** [comment]
how do we like mass edit a certain string so we can quickly delete all instances of the conflict bullshit popping up

**Comment by Jujumatic** [comment]
ok nevermind cause there actually is stuff getting changed... ugh

**Comment by Jujumatic** [comment]
map diff bot works but travis keeps failing and i don't know why

it can't be an issue with the map as it got rendered properly

**Comment by Jujumatic** [comment]
can i just merge it, it's just that travis can't open the dmm for some reason, but everything else checks out

**Comment by yoyobatty** [comment]
Might be better to make upstream map fix PR.

**Pull request closed without merging**
