### PR TITLE
Alcoholics Anonymous anyone?

### PR DESCRIPTION
**Pull request by AliiTea**
:cl: Nexendia
tweak: enables two positive traits related to Alcohol and 1 negative trait.
/:cl:

[why]: why not?

This seems like something hippie would have just because it's hippie.

### CODE REVIEW

**Comment by mikolaj007** [comment]
+1 for alcohol tolerance
-1 for insanity
Not sure about drunken healing

**Comment by AliiTea** [comment]
Insanity is worth it, it only applies if you take it and it's another funny meme to add with the alcohol side as now you are a drunk who can function and heals but you are also fucking insane

**Comment by Manly-Dwarf** [comment]
Wait for economy before merging any of these, I'd say. Traits right now hardly have downsides, so getting a positive trait like this would be really easy.

**Comment by AliiTea** [comment]
insanity trait ree I guess I am retarded

**Comment by Lxtoofonea** [comment]
+1

**Comment by Carbonhell** [comment]
Can you specify what exactly the traits do please

**Comment by AliiTea** [comment]
One lets you heal while being intoxicated, the other allows you to drink more. Insanity well.. just makes you hallucinate 99% of the time.

**Comment by k-k-karma** [comment]
quirks are gay. no rp shit on hippie

**Comment by Carbonhell** [comment]
I don't really like traits which buff you anyhow, they will probs be abused
+1 for insanity
-1 for intoxicated and alcohol

**Comment by earthmoonjune** [comment]
neutral on this cause im not really a fan of traits as a whole.

**Comment by Jujumatic** [comment]
we want to keep traits neutral because powergaming is dumb and they will always find a way to abuse the system unless you make it completely non beneficial

**Comment by Carbonhell** [comment]
Denied.

**Pull request closed without merging**
