### PR TITLE
Actually give people a reason to vote

### PR DESCRIPTION
**Pull request by ghost**
yer opinion don't count if you don't submit a ballot

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
+1, but there should be a specific sound that plays when a shuttle call vote is made. Maybe do somethin like Goonstation and their map votes, and get quips from coders/admins saying "Shuttle call vote" or whatever

**Comment by ghost** [comment]
yeah i'd love sounds/quips for it lol

**Comment by WarRage333** [comment]
we had this in before and it was removed because every single vote passed

**Comment by Manly-Dwarf** [comment]
Every single vote passed because there were no restrictions on voting. You could do it roundstart, and the shuttle was not sped up/slowed down depending on the timer, nor could it be recalled.

**Comment by Jujumatic** [comment]
But there is literally a sound when you make a vote, it's the event sound that says "attention" and it says in huge text like font 25 that a vote has started

You can't go much more than that without it being extremely obnoxious

**Comment by ghost** [comment]
this needs a chance to actually pass on highpop, especially during _those_ rounds.

**Comment by Manly-Dwarf** [comment]
"attention" plays as a filler sound on every single random event, Jujumatic. Every time an admin makes a centcom report, it says "Attention, new command report created." Every time the round starts, it says "Attention, enemy communication intercepted."
Attention is used a lot. Plenty of players likely just tune it out.

**Comment by k-k-karma** [comment]
let's get pyko to scream at them

**Comment by yobob591** [comment]
+1 I usually treat it like this

**Comment by yobob591** [comment]
Get someone to scream vote now bitch

**Comment by DaydreamPuppeh** [comment]
+1. Make it pokemon go to the polls

**Pull request merged**
