### PR TITLE
NOW APPROACHING N***** STATION

### PR DESCRIPTION
**Pull request by ghost**
word censored to prevent github police from eating my ass

on turret's request

:cl:
soundadd: The arrivals shuttle welcome message is now more accurate
/:cl:

### CODE REVIEW

**Comment by SireTurret** [comment]
+1

**Comment by butilka4** [comment]
what have I've done

**Comment by Phrog42** [comment]
What have I've brought

**Comment by Manly-Dwarf** [comment]
Reverts part of Pyko AI for a lame joke.

**Comment by ghost** [comment]
pykoai is shit anyways

**Comment by Manly-Dwarf** [comment]
implying this isn't even worse

**Comment by karmaisblackandbluepilled** [comment]
+1 this is really good trust me brah

**Comment by Majick1** [comment]
Did we pay the licensing fee for the N word

**Comment by diegoxt45** [comment]
-1 this is fucking stupid

**Comment by ghost** [comment]
@diegoxt45 begone BR

**Comment by mikolaj007** [comment]
cant you make it a chance thing so that the voicelines change instead of a single one?

**Comment by GuyonBroadway** [comment]
Pettition to get pyko to yell "PERKELE!" and change it to "Now approaching **PERKELE** station"

**Comment by ghost** [comment]
just make it a roll to choose this or the pykoAI one or perkele station

**Comment by ExpAntique** [comment]
-1

**Comment by SireTurret** [comment]
the joke is lame now that I look at it

probably should be closed

**Comment by Manly-Dwarf** [comment]
no

**Comment by Phrog42** [comment]
cool

**Pull request closed without merging**
