### PR TITLE
remove separated from glow berry but add gaseous decomposition

### PR DESCRIPTION
**Pull request by RafRoq**
:cl:
add: added gaseous decomposition to glow berry
del: Removed separated chemicals from glow berry

:cl:

### CODE REVIEW

**Review by Jujumatic — APPROVED** [review]

**Comment by Jujumatic** [comment]
nice

**Comment by Maroonenahmoron** [comment]
No idea how this is canon for glowberries. Would make a whole lot of more sense if it came from a tobacco mutant.

**Comment by RafRoq** [comment]
Just because glowberry had separated before, but giving it to space tobacco might be nice

**Comment by Jujumatic** [comment]
needs head input

**Comment by RafRoq** [comment]
@Jujumatic  merge no one will bat an eye

**Comment by Carbonhell** [comment]
uh, sure? +1

**Pull request closed without merging**
