### PR TITLE
Credit Roll Removal

### PR DESCRIPTION
**Pull request by AliiTea**
:cl: Nexendia
del: Removed Credit Roll
/:cl:

### CODE REVIEW

**Comment by Memendia** [comment]
ihatemylife

**Comment by PopNotes** [comment]
instead of removing credit roll, move it to the lobby screen instead of being at round-end so it doesn't shit up the screen

**Comment by AliiTea** [comment]
Why is the credit roll needed in the first place?

**Comment by KayeArray** [comment]
i don't see the issue

**Comment by PopNotes** [comment]
like I said in the discord, it's a good idea implemented poorly

and why is it on the right side of the fucking screen fix that too

**Comment by AliiTea** [comment]
I am just going to let someone who knows what they are doing to do this shit

**Comment by ghost** [comment]
This does not even work.

**Comment by AliiTea** [comment]
@Chnkr and that is an unhelpful comment - Captain Obvious

**Pull request closed without merging**
