### PR TITLE
You can no longer make yourself immune to non-advanced viruses with a healing virus

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: Chugging a cold culture bottle is no longer a valid strat against fungal TB. Sorry, folks!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
@Manly-Dwarf

**Comment by ExpAntique** [comment]
+1

**Comment by karmaisblackandbluepilled** [comment]
-1 kono powergame da

**Comment by mikolaj007** [comment]
+1

**Comment by Manly-Dwarf** [comment]
+1 merge this already

**Pull request merged**
