### PR TITLE
Readds borg sprites and makes them selectable

### PR DESCRIPTION
**Pull request by funkynuggets**
cl:

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Added older cyborg sprites that you can choose either TG or older ones from.
fix: Inivisble cyborg statues. No longer you'll bump into invisible stuff in AI's sat.
/:cl:

## About The Pull Request

Changes robots.dmi to add older sprites, and robot_modules.dmi so you can select them.

## Why It's Good For The Game

Variety for the borgo boys. Why should those service lads get all the sick different icons?

Readds old school borg sprites. I didn't want to make a full blown PR as this was only to fix the cyborg statues that were invisible, but to make it actually worth a PR, you can now select the non-snowflakey ass borg sprites.

### CODE REVIEW

**Comment by TheMeatGod** [comment]
+1 sure

**Comment by Jujumatic** [comment]
modularise this shit rrrEEEEEEEEEEEEE

**Review by Jujumatic — DISMISSED** [review]
MODURALISE RRREE

**Comment by funkynuggets** [comment]
> 
> 
> MODURALISE RRREE

modulation complete

**Comment by Manly-Dwarf** [comment]
No thanks. I think the looks of borgs are fine as is, besides Security.

**Comment by funkynuggets** [comment]
> 
> 
> No thanks. I think the looks of borgs are fine as is, besides Security.

This doesn't remove their looks, just adds in the old borg looks from pre tg, and whatever other sprites were lying around unused/from old code so you can choose between them, just like how the service borg works I personally think while the sprites are alright, they're fucking ugly for what are supposed to be low budget robots that you put prisoners into. You telling me that they can transform into completely different things like some powerranger things? I loved the old sprites because it was literally "okay, engineer dude, here's a hardhat and a hazard vest, go fix shit"

**Comment by Jujumatic** [comment]
so how exactly does this thing work? how do you get to change your borg icon?

**Comment by funkynuggets** [comment]
> 
> 
> so how exactly does this thing work? how do you get to change your borg icon?

The same way service borgs change their sprites. When you chose a module, it'll pop up a little window and ask what sprite you wish for. Selecting it makes it permanent, until you get a module change.

**Comment by Jujumatic** [comment]
Excellent. I'll assume you tested it?

**Comment by funkynuggets** [comment]
> 
> 
> Excellent. I'll assume you tested it?

Of course, checked every single sprite to make sure they worked.

**Review by Jujumatic — DISMISSED** [review]

**Comment by Jujumatic** [comment]
just need some more headmin input and we can shove this into the rest of our cestpool of code

**Comment by Lxtoofonea** [comment]
+1

**Review by Carbonhell — DISMISSED** [review]
Modularize the dmi in the way i explained to you in DMs.

**Comment by Carbonhell** [comment]
+1

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Review by yoyobatty — APPROVED** [review]
Code looks good.

**Pull request merged**
