### PR TITLE
Re-adds old zippo icons

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
imageadd: Re-adds old zippo icons
/:cl:

## About The Pull Request
This adds the old zippo sprite.

## Why It's Good For The Game
It looks so cool.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
yes

**Comment by Carbonhell** [comment]
yes

**Comment by Carbonhell** [comment]
i don't see any dmi change, how does this work

**Comment by Carbonhell** [comment]
yeah i don't think this works. Did you test it?

**Comment by yoyobatty** [comment]
No, carbon, the header coder made a git branch and didn't bother to tes-OF course I tested it.

**Comment by yobob591** [comment]
+1 spicy

**Comment by DaydreamPuppeh** [comment]
Absolutely +1

**Comment by Jujumatic** [comment]
image

kid... 🤔

**Comment by yoyobatty** [comment]
The current TG file still has the old zippo icons. Why would you imply that I didn't test it.

**Comment by Jujumatic** [comment]
bc u big peepee..

**Review by Jujumatic — APPROVED** [review]

**Pull request merged**
