### PR TITLE
Removes roundstart clown car

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
del: The clown car has been cast into oblivion. 
/:cl:

[why]: Because fuck clown car.

### CODE REVIEW

**Comment by k-k-karma** [comment]
+1, wanted to do this but didn't have the time

**Comment by Lxtoofonea** [comment]
+99999999 FUCKING GET IT OUT

**Comment by deatht1** [comment]
-1 Git Gud

**Comment by Manly-Dwarf** [comment]
If I recall, this was already voted on by headmins.
+1 any way.

**Comment by GuyonBroadway** [comment]
There's one on metalake too, you can kill that one and all.

**Comment by ghost** [comment]
+111111111111111

**Comment by ghost** [comment]
also, @yoyobatty, mapmerge this, else you might have duplicate dictionary keys. they won't cause problems, but could possibly lead to weird conflicts in the future

**Pull request merged**
