### PR TITLE
Minesweeper huge performance fix

### PR DESCRIPTION
**Pull request by Jujumatic**
I bet you 5$ that it was browse_rsc that made the browser lag to shit.

I will actually bet money if anyone challenges me.

Testmerge candidate as I can't actually see if this gives a performance boost as I am working on a local server to test this shit.

Basically what this will do is store the html icons in the arcade machine so they will only ever be searched for once. This means it won't look through files on every browser update so it should be way faster as it is just loading the images stored on the arcade machine itself, so they are already loaded into memory in a sense

## Changelog
:cl:
fix: The Minesweeper browser should actually respond pretty quickly now
/:cl:

### CODE REVIEW

**Comment by yoyobatty** [comment]
Now THIS is how you do icons.

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 56dde8e0a294177493140e839ebce7b0aea8ab16
Pull Request: 74404856c57d41952f1ddcc3206afdeab3b3aa5f
Server: 8f00c73c1450046f8a1224494a1526c2d007ffc9

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 56dde8e0a294177493140e839ebce7b0aea8ab16
Pull Request: 74404856c57d41952f1ddcc3206afdeab3b3aa5f
Server: 5b5a92c0a5774546b4feb9c53b50523e885367b3

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 56dde8e0a294177493140e839ebce7b0aea8ab16
Pull Request: ec565c0721d49e8a095c9e3fb325e7d3f6c25648
Server: e54252e4c680d02e94d2e7666f687530ab1cd1da

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 56dde8e0a294177493140e839ebce7b0aea8ab16
Pull Request: ec565c0721d49e8a095c9e3fb325e7d3f6c25648
Server: 5677517bc69d2b749b1a1ce7c9e7ae5d06fd4e26

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: ace48bffc13068db2d13502767f4de3e556eecc9
Pull Request: ec565c0721d49e8a095c9e3fb325e7d3f6c25648
Server: 40f9adafea1406ccc7a0c949daff1a725e3fa558

**Comment by Jujumatic** [comment]
it works super well!!! now merge pls

**Review by yoyobatty — APPROVED** [review]

**Comment by ghost** [comment]
#### Test Merge Removed

**Pull request merged**
