### PR TITLE
DildosPhase2

### PR DESCRIPTION
**Pull request by Eagle-Eyess**
:cl: EagleEyes
tweak: The sins of the past come back to wreck havoc on the present... 
/:cl:
Phase 2 of 3 of plan dildo commences as I add in 1 of each dildo to the map for a total of three. One in secret chaplain room, one in curators office and 1 in the clowns locker. If these get added to the map next phase will be adding dildo based weaponry...
dildo 1
dildo 2
dildo 3

### CODE REVIEW

**Comment by tortellinitony** [comment]
delete

**Comment by Eagle-Eyess** [comment]
so ill add you down as a +1 then alright.

**Comment by ghost** [comment]
Slippery slope boyo...

-1

**Comment by ghost** [comment]
-1 i will end you

**Comment by Pyko1** [comment]
should be in maintloot spawner

**Comment by biggiOS** [comment]
+1 omegalul

**Comment by Carbonhell** [comment]
if bruce and tfw don't want it,i don't wanna go against them

**Comment by Eagle-Eyess** [comment]
That didn’t seem to be a problem the last pr...

**Comment by nalarmg** [comment]
Code is fine. Up to the heads on whether this is desirable.

**Comment by Carbonhell** [comment]
Sorry,but sadly this is denied. Considering making a feature suggestion and discussing a possible implementation (lavaland lust ruin perhaps?).

**Pull request closed without merging**
