### PR TITLE
Atmos adjacency subsystem revival (Test merge)

### PR DESCRIPTION
**Pull request by yoyobatty**
Test merge mirror of https://github.com/tgstation/tgstation/pull/43447

### CODE REVIEW

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 4ffa92dfc8ee2e4612d9cbbbc0e0d3aa228e0adb
Pull Request: 4494b387fb4ec937d7aeeb362ce15dd4417e6f08
Server: ec196a39b28b29a83f4df546d34c128c10c286ce

**Comment by vuonojenmustaturska** [comment]
@yoyobatty did it explode

**Comment by yoyobatty** [comment]
I haven't actually seen what it looks like yet and what did you mean by explode ?

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: ce668cc759a4e0bc53fdf81231ac74a2a600841f
Pull Request: 4494b387fb4ec937d7aeeb362ce15dd4417e6f08
Server: b6571182f8bac6892fd2a73ff5148ee6f2f16995

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 148f24648e3908643036062b1e33156fc6803365
Pull Request: 4494b387fb4ec937d7aeeb362ce15dd4417e6f08
Server: 14b327b3a847c40508acb226ccd1cbfd57fa8004

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: e570fb5e00f943c9b9bd83d81da265cbf0156719
Pull Request: 4494b387fb4ec937d7aeeb362ce15dd4417e6f08
Server: b13be121780329fd29fc0cd429d7afbd4108e814

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: e6407636f5dfc87b424d3253983008347a74fd01
Pull Request: 4494b387fb4ec937d7aeeb362ce15dd4417e6f08
Server: 09add4d6926fd3ff89ce749b6bda51c6c84c85c8

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 0bd02b9a55d765dffc417d26f138a9ea2a99d622
Pull Request: 4494b387fb4ec937d7aeeb362ce15dd4417e6f08
Server: 93ade7b479db9b6a3485381fe4527cbb2b8cf053

**Comment by ghost** [comment]
#### Test Merge Removed

**Pull request closed without merging**
