### PR TITLE
[MIRROR] [READY] New clown traitor item: The clown car

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/39317
--------------------
:cl: Floyd / Qustinnus (Credits to KMC for the sprites)
add: The Clown Car, your 18TC clown-only solution to asshole co-workers
add: Regular car implementation (makes it easier to add more cars if someone actually feels like adding those)
/:cl:

Credits to Goon ofcourse, they had the OG idea.

I've been wanting to add this for a while, and now I have. The clown car is a vehicle you can use if you're a traitor clown to run people over, shove them into your compact trunk, and take them for a ride. If you drive into any walls however, you and everyone you kidnapped, fall out of the car, leaving you somewhat vulnerable.

It also comes with a lube-defense mechanism(tm) which has a 1/3 chance to drop some lube if someone decides to shoot at your sweet ride.

You can also honk your horn or drop all of the drivers if you would like to.

video: https://streamable.com/9b5ww

also i created this while being slightly tired so theres probably still some oversights, as always

TODO:
- [x] Add something to vehicle/sealed that allows you to pick up things you drop inside of them without kicking out the occupants.
- [x] more funny gimmicks
- [x] balance (im bad at this so i might need help with this :^))
- [x] test (>implying)

### CODE REVIEW

**Comment by Carbonhell** [comment]
god bless floyd holy shit finally

**Comment by GuyonBroadway** [comment]
This was merged the night before I come back from holiday. Its a sign, fear my return.

**Comment by ghost** [comment]
the video is out of date btw it just sucks faggots up now instead of just knocking them over

**Comment by ghost** [comment]
+1

**Comment by GuyonBroadway** [comment]
just need to let travis do its thang....

**Comment by GuyonBroadway** [comment]
WOOO ITS REDDY!!

**Review by GuyonBroadway — APPROVED** [review]

**Pull request merged**
