### PR TITLE
[MIRROR] Fixed randomly generated diseases infinitely looping in New()

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/38472
--------------------
Closes #38455

### CODE REVIEW

**Comment by praisenarsie** [comment]
@Jujumatic since you love viruses, do this pr :^)

**Comment by Jujumatic** [comment]
awe fuck bye

I'll do it this weekend

**Comment by Jujumatic** [comment]
this should be fixed up now @HippieStation/maintainers please review

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
i have a bad feeling about this

**Pull request merged**
