### PR TITLE
[MIRROR] Objective refactor

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40220
--------------------
Objectives are no longer stored on mind only antagonists or teams.
Also various cleanups.
That's all. Next step is removal of explicit owner so they're stateless but that's another PR.

### CODE REVIEW

**Comment by yoyobatty** [comment]
This is going to need work.

**Comment by yoyobatty** [comment]
Note that this is going to still require more work, even if the build passes. @carbonhell think you could handle this?

**Comment by yoyobatty** [comment]
I reference all the hippiestation stuff @steamport01

**Comment by ghost** [comment]
@yoyobatty You did it wrong. YOU DON'T ADD OBJECTIVES TO `all_objectives`!

You take away `mind.objectives` references, as objectives are datum antag based, now

**Comment by yoyobatty** [comment]
Yeah, I figured that out shortly after. You're going to need to work on this.

**Comment by ghost** [comment]
HOW????

**Comment by Carbonhell** [comment]
Steamp0rt is not a maintainer lol, he cannot do this anyhow, this is the maintainers' job

**Comment by ghost** [comment]
Lol

**Comment by Carbonhell** [comment]
This is essential. Prioritize this over all mirrors.

**Comment by steamp0rt** [comment]
This isn't even hard

**Comment by ghost** [comment]
This isn't even hard

**Comment by ghost** [comment]
Fixed branch: https://github.com/steamp0rt/HippieStation-1/tree/upstream-merge-40220

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
