### PR TITLE
[MIRROR] Small code improvement pass on crayons

### LINKED ISSUE #6005: spray cans broken?
In-Game report from pyko:
Server info: 25963 (Hippie Station)

could not see my sprays on walls.

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40233
--------------------
I was searching for something else and clicked on a crayon search result by accident.

:cl: Naksu
code: crayons now have about 10% less shitcode
/:cl:
Fixes #6005

### CODE REVIEW

**Comment by Carbonhell** [comment]
i guess this is the time i finally rework gang crayon shitcode

**Comment by Carbonhell** [comment]
i mean if anyone else wants to, do it

**Comment by Carbonhell** [comment]
I cannot deal with this. Someone do it,please.

**Comment by GuyonBroadway** [comment]
It'll have to wait till the weekend.

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
