### PR TITLE
[MIRROR] Removes the action button from chem implants

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/36021
--------------------
Sorry i heard you like to powercreep with stuff you can make with one chem macro every round?

:cl: Improvedname
fix: chem implants can no longer be self triggered
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Oh hey, neat. Apparently this got reverted when we rebased.
It's gone again.

**Comment by WarRage333** [comment]
how do you activate them now?

This is also stupid since dental implants exist

**Comment by Manly-Dwarf** [comment]
Dental Implants got nerfed, these didn't.

**Comment by JohnGinnane** [comment]
Made redundant by https://github.com/HippieStation/HippieStation/pull/6896

**Pull request closed without merging**
