### PR TITLE
Clown AoE Brainmelter

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
add: Some evil bastard at syndicate R&D has been giving their clown agents bike horns that cause brain damage.
/:cl:

[why]: It was requested rather heavily in this thread on the forums. [https://hippiestation.com/threads/clown-aoe-retardifier.6590/](url)

### CODE REVIEW

**Comment by ghost** [comment]
I like it, maybe add a bit of CONFUSION on it for a bit more grief.

**Comment by GuyonBroadway** [comment]
I could do that, but IIRC one of the things set out in the thread was that the clown would be in the area and suddenly everyone is retarded before they knew what was up.

**Comment by ghost** [comment]
Oh shit, it's a stealth brain damage retarder? That makes it even fukken better holy shit.
+1

**Comment by GuyonBroadway** [comment]
It literally looks like a golden bike horn and there is nearly no way to tell if it's a brain melter or not. 

Also it's 5tc. Buy four and hand them out to random crewmembers for extra fun.

**Review by j-mie — APPROVED** [review]

**Pull request merged**
