### PR TITLE
A more robust null rod revert (plus chappy traitor monk-fu)

### PR DESCRIPTION
**Pull request by NautilusViper**
## Changelog
:cl: NautilusViper
balance: Null Rod skins are back to their old (fun) selves, fixing what could be perceived as bugs (not being able to wear fedora etc) in the process. The Null Rod no longer possesses antimagic capabilities. Rather, antimagic has become an inherent gene in chaplains. The downside: No more sweaty captains dumpstering wizards by having a rod on their belt. The upside: Chappy is FUCKING INVINCIBLE to sorcerer tomfoolery, even if they drop their null rod.
imageadd: Dark Blessing has had a visual touch-up to Pious Gold from Changeling Red. This will theoretically result in fewer screeching bald men from toolboxing innocent chaplains to death.
add: Monk Manual is now a Chaplain-exclusive traitor item for six telecrystals.
/:cl:

## About The Pull Request
This got fucking messy.

## Why It's Good For The Game
Null Rod skins were fun and the Baw's nerf made them not fun. As with all nodrop items, delimbing the chaplain will allow you to take his Null Rod for yourself. Null Rods having antimagic was admittedly abusable as anyone could fit it in their pocket to fuck over wizards, so the chaplain having that capability instead is more fitting.

Also the Monk Manual was loads of fun, but blatantly overpowered as a rod skin. It deserves to be in the game in some form.

### CODE REVIEW

**Comment by yoyobatty** [comment]
That's what manly wanted

**Comment by ghost** [comment]
this is great

**Comment by yoyobatty** [comment]
Didn't realize Chaplain actually didn't have an antimagic trait.

**Comment by Zyzarda** [comment]
Change the skins to do something or remove them please

**Comment by NautilusViper** [comment]
yeah that's literally what this PR does

**Review by yoyobatty — DISMISSED** [review]

**Comment by Manly-Dwarf** [comment]
I still don't like the Chaplain reskinning his null rod. None of it is even religion themed besides the God Hand, which is just a reused wizard sprite. They don't do anything interesting besides the Mummy Staff any, too.

Also nodrop weapons that [deal the same damage as a spear](https://github.com/HippieStation/HippieStation/blob/8c0f35a433a0fee53b84d513fe50187c6a570627/code/game/objects/items/holy_weapons.dm#L175), please stop.

EDIT:
You didn't fix nodrop anti-magic, did you? Make the Chaplain anti-magic instead of his null rod.

**Comment by NautilusViper** [comment]
> I still don't like the Chaplain reskinning his null rod. None of it is even religion themed besides the God Hand, which is just a reused wizard sprite.

Tell me exactly how often Chaplains actually fucking roleplay their religion. Even ignoring that, you have the claymore (knights templar), dark blade (ingame nar'sie cultists), chainsaw sword and hammer (warhammer 40k), atheist's fedora (hilarious), and the pitchfork (satan). I think you're seeing things the way you want to see them.

> Also nodrop weapons that [deal the same damage as a spear](https://github.com/HippieStation/HippieStation/blob/8c0f35a433a0fee53b84d513fe50187c6a570627/code/game/objects/items/holy_weapons.dm#L175), please stop.

Nodrop is a trade-off. You lose all utility in one hand slot for a strong weapon. It's also not a weapon with blockchance like the staves or the claymore, so one water puddle, stun baton, thrown soap, krav maga sweep, et cetera will put you down. If "DAMAGE EQUALS BEST" were true, nobody would ever buy the stechkin or edagger.

**Comment by Manly-Dwarf** [comment]
Nobody does buy the stetchkin or edagger from what I see, so that's kind of moot. They get them from surplus crates, sure.
Even if Chaplains don't roleplay their religion, and those few items, you still have other crap like the arm chainsaw (not 40k), high-frequency blades, dark blessing which has caused more ahelps than I can count, energy cutlass, the katana and probably more. None of those are religion themed nor a reference to a religion from another media/franchise.

Losing utility in one hand isn't a very huge deal, we've always had people slicing off their arms or using riot shields with no problem. Antimagic cripples wizards, so put that on a Captain with nodrop and they've nulled the Wizard's main strength. Same goes for Cult and other modes, but at least they get a sword to slice the thing off with.

**Comment by NautilusViper** [comment]
> Nobody does buy the stetchkin or edagger from what I see, so that's kind of moot. They get them from surplus crates, sure.

If it's only surplus crates that people get them in then they must have some insane weighting.

> Even if Chaplains don't roleplay their religion, and those few items, you still have other crap like the arm chainsaw (not 40k), high-frequency blades, dark blessing which has caused more ahelps than I can count, energy cutlass, the katana and probably more. None of those are religion themed nor a reference to a religion from another media/franchise.

So yeah, some of the null rod skins are unfitting. I don't disagree. You said that God Hand was the only other fitting skin for the null rod and it isn't. More over, it kind of doesn't really matter all that much that all rod skins aren't ROLEPLAY FRIENDLY, because there are options if you're the type of person who wants to do that. If you want to remove the dark blessing from the list of skins because it causes ahelps, then I guess that wouldn't be that big a deal?

> Losing utility in one hand isn't a very huge deal, we've always had people slicing off their arms or using riot shields with no problem. Antimagic cripples wizards, so put that on a Captain with nodrop and they've nulled the Wizard's main strength. Same goes for Cult and other modes, but at least they get a sword to slice the thing off with.

It's a pretty big deal. Only the powergamiest of powergamers regularly sacrifice an arm JUST for the sake of not being able to be handcuffed and passively using a shield in that state becomes impossible, plus it's really irritating only having one arm. Riot shields can be dropped/placed on your back and the telescopic shield can be collapsed and stored if you need to use your other hand, assuming you have both, whereas nodrop items don't get that leisure, so it's a poor comparison. A nodrop shield would be an apt comparison, but the blue and red shield staffs aren't nodrop. Believe it or not, I agree with you that the Chaplain himself should be antimagic, so if you'd like to help me figure out a way to do that I'm down to remove antimagic from the nullrod. Fun skins will have to stay, though.

**Comment by Manly-Dwarf** [comment]
Simple, antimagic chaplain. No antimagic nullrods.
Remove the Dark Blessing.
Then sure, I'd support this PR, but shit like the arm chainsaw is just lame and I'd rather it be used elsewhere.

**Comment by NautilusViper** [comment]
> Simple, antimagic chaplain. No antimagic nullrods.
> Remove the Dark Blessing.
> Then sure, I'd support this PR, but shit like the arm chainsaw is just lame and I'd rather it be used elsewhere.

Pretty sure Chainsaw arm is a direct Evil Dead reference which is... something. I do have an idea I want to implement that goes against that though. What say the default null rod skin has the bonus of being the only rod skin that possesses antimagic? That way there wouldn't be any worry about powergaming captains carrying antimagic god hands or shield staves.

**Comment by Manly-Dwarf** [comment]
That just defeats the purpose of re-adding the null rod skins and making them special again, because now you're removing one of the most powerful things for the Chaplain himself to have.
There's no fear of it if the Chaplain, as he is a holy man, is always immune to the magic of a Whizzard. If Chaplains end abusing this and powergaming, I'll come up with something.

**Comment by ghost** [comment]
agreed,  the holiness comes from inside the chaplain not from his big black rod.

**Comment by bigbluebeaker** [comment]
+1 this is a low-rp server so I'm naturally against taking away fun stuff in the spirit of immershuns. make chappy great again

**Comment by NautilusViper** [comment]
I'm still not entirely sure how to give chaplains permanent antimagic. I'm still figuring all this out. Hang tight.

**Comment by ghost** [comment]
something like the afterspawn proc or smth

**Comment by NautilusViper** [comment]
I'm feeling like I should be doing something similar to #11129 but antimagic ain't a mutation 🤔

**Comment by ghost** [comment]
@NautilusViper antimagic is a component. use AddComponent

**Comment by NautilusViper** [comment]
I'm going the unnecessarily difficult route.

**Comment by NautilusViper** [comment]
This was painful, but I might have figured it out.

**Comment by NautilusViper** [comment]
Chaplain made sorcery-proof, time to see if I can't un-sorcery-proof null rods.

**Comment by NautilusViper** [comment]
I think I'm finally ready to call this shit donezo. Chaplain always dispels magic, the null rods do everything they used to without dispelling magic. Last step is to appease Dorf by reskinning the Dark Blessing so anyone who kills the chaplain for using it can be branded a brainlet.

**Comment by Manly-Dwarf** [comment]
Thanks. I'll go ahead and pass this a +1 once you're done with the dark blessing.

**Comment by NautilusViper** [comment]
I did reskin the dark blessing. It's not the removal you wanted, but it's something.

**Comment by NautilusViper** [comment]
what

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
