### PR TITLE
Tasertron sprite

### PR DESCRIPTION
**Pull request by SireTurret**
## Changelog
:cl: Turret
imageadd: unghagunh i stoopid
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
did you literally just CREATE THE FILE instead of deleting the old one

**Comment by Manly-Dwarf** [comment]
you stupid idiot

**Comment by SireTurret** [comment]
> did you literally just CREATE THE FILE instead of deleting the old one

whats wrong

**Comment by SireTurret** [comment]
i see whats wrong

**Comment by SireTurret** [comment]
here u go

**Review by Manly-Dwarf — APPROVED** [review]
ok no code no problem

**Comment by Manly-Dwarf** [comment]
agtragragrahh

**Pull request merged**
