### PR TITLE
Fixes right arms

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

### CODE REVIEW

**Comment by tortellinitony** [comment]
What's causing it?

**Comment by yoyobatty** [comment]
Fucking tg

**Comment by danhibiki** [comment]
This is not on tg

**Comment by yoyobatty** [comment]
Yeah, well it's fixed.

**Pull request merged**
