### PR TITLE
rock hit loot here go!

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: loot rock hit station for good loot!
/:cl:

@Wheezl

### CODE REVIEW

**Comment by wheezl** [comment]
+1 loot rock good

**Comment by karmaisblackandbluepilled** [comment]
+3
the moment this gets merged I'm making a pr that adds more random shit to the loot table

**Comment by Zyzarda** [comment]
+2 random loot is fun

**Review by Neotwr — APPROVED** [review]

**Comment by carlopault** [comment]
+2 for the grace for the might of our lord

**Comment by MrEpicSax** [comment]
+1 Another blessed Steamport x Wheezl PR

**Comment by FantasticFwoosh** [comment]
You merged it before you even removed the watermelon and misc stuff from the icons, you're going to give me a negative art reputation or a excellent standing ovation from hippie players :facepalm: 

Suggestion for the inevitable follow up PR, watermelon meteors split into edible watermelon slice chunks, & cosmic b_balls contribute to loot or just drop b-balls and harlem globetrotter uniforms/unusual loot out of the pool for being rarer.

**Pull request merged**
