### PR TITLE
Tiny map fixes

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
fix: Cargo conveyor belts now work and levers face correct direction (Tested with shuttle)
fix: Lighting in singulo/tesla setup wasn't lighting up due to the area
fix: Area string for science apc
fix: Cable powering russian apc was not connected
fix: Replaced those closests in chapel with coffins :)
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by Jujumatic** [comment]
@yoyobatty could you show the before and after for each area cause the map bot is being dumb :(

**Comment by yoyobatty** [comment]
Basically the singulo room will now be lit up by the wall lights instead of being full bright and the cargo conveyors face correctly.

**Comment by Jujumatic** [comment]
great. now i would merge this but the upstream still isn't done :'(

**Comment by Jujumatic** [comment]
fixes coffins as well :O

**Review by Jujumatic — APPROVED** [review]
FUGG YES

**Pull request merged**
