### PR TITLE
Fixes a long overdue oversight in taser bolt charge cost.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
balance: ON a full charge the hybrid taser and HoS gun can now shoot 8 times, up from 5.
/:cl:

[why]: Back when I was doing the stuns rework my ethos was "about four punks on a full clip of charge if you land every shot" For whatever reason, it getting overwritten or I forgot or something, this is not the case. This fixes this oversight.

### CODE REVIEW

**Comment by PopNotes** [comment]
I would really prefer it that the shot count was 6, so you could tase three people instead of four on a full charge. Alternatively, give the HoS' gun the 8 charges and keep the taser at 6 so it would be a worthy sidegrade to the captain's laser.

**Comment by Sarcalogo** [comment]
People who never play Security trying to balance Security. I invite you to play Sec Officer only for a week.

**Review by JohnGinnane — APPROVED** [review]

**Comment by ghost** [comment]
6 sounds like it could be good
either way it goes +1

**Comment by KayeArray** [comment]
+1

**Comment by ghost** [comment]
ye sure +1

**Comment by GuyonBroadway** [comment]
Das a +3,

**Comment by Blute1** [comment]
revert this, it did not follow policy

**Comment by Blute1** [comment]
nevermind

**Pull request merged**
