### PR TITLE
AsteroidStation

### PR DESCRIPTION
**Pull request by praisenarsie**
Since the default hippiestation map is getting boring. I've decided to add the revived AsteroidStation that /tg/ sadly closed.

Credits to @CorruptComputer for the entire, original map!

:cl: CorruptComputer, FrozenGuy5
add: Adds AsteroidStation!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
i'd say since the work is pretty substantial and it's not already from /tg/, you should mention the author's name in the changelog too

**Comment by praisenarsie** [comment]
forgot, thanks for reminding

**Comment by CorruptComputer** [comment]
Oh wow, this is cool! I've been trying to update it some more, but I've been super busy with work and school lately. How close is the Hippie code to tg? I've honestly never played on Hippie and don't really know the differences.

**Comment by JohnGinnane** [comment]
It's pretty close but we've tried to keep our changes in separate files to avoid conflicts/issues

**Comment by praisenarsie** [comment]
Yeah, we aren't much different from /tg/ apart from different sprites, different minor features, etc. One of our maintainers (@banthebantz)  got the idea by porting AsteroidStation considering we are tempted to add new maps since box every round can get boring.

**Comment by praisenarsie** [comment]
Closed since mcbaw made a pr #7493

**Pull request closed without merging**
