### PR TITLE
Add 'micro chemical synthesizer' circuit

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Micro chemical synthesizer circuit! It can make chemicals... in circuits!
/:cl:

I should really make it so it can produce less chemicals. If anyone has a better list of chems, post it in the comments.

### CODE REVIEW

**Comment by Majick1** [comment]
Maybe stick to medical chems, or simple mixtures that don't require heating

**Comment by cris5311** [comment]
+1

Chems are good.

**Comment by AnthonyJNgo** [comment]
-1 unless someone can convince me otherwise, I feel like mixing the two most powerful departments should not be a thing.

**Comment by ghost** [comment]
@AnthonyJNgo did you forget about the fact science has a Chem dispenser

**Comment by WarRage333** [comment]
As i said in the coder copter, if you like circuits and you don't want them to be removed YOU DON'T WANT THIS.

Retards will abuse it to no end.

**Comment by Carbonhell** [comment]
> As i said in the coder copter, if you like circuits and you don't want them to be removed YOU DON'T WANT THIS.

**Comment by ghost** [comment]
how about i nerf it. alot.

**Comment by Majick1** [comment]
Then why add it, maybe keep it on the shelf for now but a feature that's so weak it's not worth the effort to use won't really be fun

**Comment by AnthonyJNgo** [comment]
Denied.

**Pull request closed without merging**
