### PR TITLE
Increase Captain's sabre hit speed by 25%

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
balance: Captain's sabre hit delay reduced from 8 to 6 ticks.
/:cl:

[why]: It feels too weak at the moment, and since tg nerfed delimbing, it has been made redundant by almost any other sharp weapon.

### CODE REVIEW

**Comment by Eagle-Eyess** [comment]
oh cool you went with my idea. +1 hopefully this still makes it different from other weapons that it’s still optional.

**Comment by ghost** [comment]
this is a really good tweak,  imaginative

**Comment by JohnGinnane** [comment]
how did /tg/ nerf delimbing?

**Comment by yoyobatty** [comment]
Delimbing is based on a formula that mainly considers the amount of damage a weapon inflicts.

**Comment by ghost** [comment]
+1

**Comment by yoyobatty** [comment]
If you want a graph plotting the the damage values here it is:
Black is the original 
Green is delay reduced to 6 ticks
and Red is original delay but 18 damage
X axis is time in ticks and Y axis is damage
image

**Comment by JohnGinnane** [comment]
this graph is satisfactory

**Comment by yoyobatty** [comment]
> this graph is satisfactory

Hang on, refresh, I mixed it up the graph.

**Comment by Manly-Dwarf** [comment]
>Since /tg/ nerfed delimbing

Why do this instead of just bringing back what made the sabre cool and fun?

**Comment by yoyobatty** [comment]
Hmm, that would involve increasing sword damage. Things are a bit more complicated that just "bringing back what made it cool and fun".

**Comment by HippieBartels** [comment]
+1

**Comment by Carbonhell** [comment]
I do not like this at all. The sabre has always been used by comdoms to delimb whoever was slightly against them, making it more powerful seems dumb. But since everyone is in favor of it, i guess +1. I think this will end badly and will need a revert anyway.

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
Have you tested this?

**Comment by yoyobatty** [comment]
Yes sir. Works perfectly.

**Pull request merged**
