### PR TITLE
Makes colossus vocal cords a force to be reckoned with

### PR DESCRIPTION
**Pull request by Jujumatic**
Simple change here, I just adjusted the cooldowns on the vocal cords to make a person able to use them frequently enough to be considered dangerous, or a very useful asset in the right hands. I think the voice of god is very cool but with cooldowns like that it's very impractical and not worth the effort required to get them. This should make them actually useful. There's already plenty of counters to voice of god so even more reason to make it at least potentially dangerous.

I would have modularised these changes but since it works off defines I'd have needed to copypaste all of the code to a hippie version, which would be pretty unnecessary I think.

:cl:
balance: Reduced the cooldowns on voice of god massively. Now you can use them frequently enough to be feared (or worshipped) like the god you are.
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
lol piss off

@Carbonhell @Pyko1 @t-f-w @Dudeinyourbackyard  reopen if you actually approve this pr for some reason

**Comment by GuyonBroadway** [comment]
This didn't even have the chance to get a code review or so much as a -1 form a mentor.

**Comment by Jujumatic** [comment]
:(

**Review by praisenarsie — APPROVED** [review]

**Comment by Jujumatic** [comment]
bump this needs headmin input pls

**Comment by Carbonhell** [comment]
not sure honestly, i'd prefer someone who has knowledge on voice of god to speak on this, personally i've never used it

**Comment by WarRage333** [comment]
To get the item you have to fight one of the hardest mobs in the game, you can 'cheese it' but that requires time, and for all the effort spent, the voice is... pretty underwhelming...

**Comment by Koffheatalt** [comment]
I've played shaft miner for over 200 hours and believe me when i say that collusus is one of the hardest fucking mobs to defeat. It's not something that you do easily. It has a shotgun attack that can instantly kill you if you aren't carefull and your body will disintegrate on death. Even if you manage to defeat it, you still gotta do surgery to actually use the item and THEN when you can finally use the voice of god you gotta wait fucking 2 minutes for each time you say something like "stop" or "sleep". Yes, the 3 second stun is pretty powerfull, but only if you combine it with something like a kinetic accelator with the illegal upgrade and the 2 damage upgrades, it's not good enough on its own.

 I personally think 20 seconds for the stun is too short, but it could definitely be something like 60 seconds without being overpowered. The other meme commands shouldn't have a cooldown though, or a very short one at worse.

**Comment by Jujumatic** [comment]
@HippieStation/head input plx

**Review by KayeArray — APPROVED** [review]
bad idea but ok

**Comment by Carbonhell** [comment]
again, i have never used VoG so i would prefer to abstain,i have zero idea how powerful it is right now and how this PR improves it

**Comment by Jujumatic** [comment]
@HippieStation/head needs input pls

**Comment by Carbonhell** [comment]
+1 i guess

**Comment by Pyko1** [comment]
seems a bit excess buff to me

**Comment by ghost** [comment]
agreed tbh,  this only serves to help the small percent of people who actually search,  find and kill the colosus

**Comment by Pyko1** [comment]
I mean free golems can usually faceroll shit, and i dont really want colossus vocal cord freegolems rolling around station killing everyone.

**Comment by Jujumatic** [comment]
The colossus does 25 full armour penetration brute damage. Also there's no way a golem can fight the colossus because you need to be VERY fast to dodge the bullet hell. You can't shield it or block it in any way, and even if you somehow could, it's on par with the japanese arcade boss fight bullet hells anyway. So good luck.

**Comment by GuppyLaxx** [comment]
@Jujumatic sand golems fam, they essentially nullify death bolts.

**Comment by Jujumatic** [comment]
Nobody plays sand golem though?? Also how does it even nullify death bolts

**Comment by GuppyLaxx** [comment]
no but you can make sand golems really easily, they literally steam roll through a lot of lavaland
sand golems have a 0.25 brute modifier and completely nullify bullets

**Comment by Jujumatic** [comment]
death bolts don't count as bullets though iirc. also besides that this means sand golems need a nerf, instead of keeping vocal cords so weak it's essentially useless

**Comment by Jujumatic** [comment]
there's no point keeping a feature so powerless that it's not worth the effort, just because of a single snowflake case that wrecks most lavaland mobs anyway. besides that it sounds OP as fuck in general, so no thanks

**Comment by earthmoonjune** [comment]
+1

**Comment by praisenarsie** [comment]
WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Pull request merged**
