### PR TITLE
Creates a summon bees spell for wizards.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
add: Some bastard druid has taught the space wizard federation how to conjure bees!
/:cl:

image

Now you can fully live out the dream of re-creating Magic Missile, loud negra Rainbow Ride, BEEEEEES in ss13.

Summon bees has a 30second CD and summons four bees, each upgrade lowers the CD by five seconds and summons two extra bees.

### CODE REVIEW

**Comment by PopNotes** [comment]
Now who you gonna call? wicky wicky BEES
Now who you gonna call? You don't wanna see my BEES
If you ever wanna see my bumrush, BREAKOUT, before you get BEES
At the WOW WOW

**Comment by Arzion5** [comment]
Are they friendly to the wizard? Should make them friendly if they aren't. Either way, I'm fully supporting both PRs now

**Review by ghost — APPROVED** [review]
LGTM

**Comment by PopNotes** [comment]
there is literally no reason to not merge this

**Comment by GuyonBroadway** [comment]
Well it MIGHT be unbalanced, during testing I saw a fair few skewium and initropidril bees so it could become very powerful.  Then again I can nerf it easy peasy.

**Comment by GuyonBroadway** [comment]
It could also just be luck of the draw.

**Comment by ghost** [comment]
+1

**Comment by GuyonBroadway** [comment]
Sadly coders/maintainers don't count for jack shit bar opinion for admins to consider. Then again its good because it means that all changes must be verified by people who understand the game, as opposed to the old "codebase/playerbase" separation that /tg/ has.

**Comment by GuyonBroadway** [comment]
Sadly coders/maintainers don't count for jack shit bar opinion for admins to consider. Then again its good because it means that all changes must be verified by people who understand the game, as opposed to the old "codebase/playerbase" separation that /tg/ has.

**Comment by ghost** [comment]
why double post

**Comment by GuyonBroadway** [comment]
image
Puttin this here as an official plus1.

**Comment by tortellinitony** [comment]
Sprites?

**Comment by ghost** [comment]
i like the idea but this seems like, incredibly powerful?

**Comment by KayeArray** [comment]
yeaaaah so ummm that's a 10? second cooldown for (4 + spell_level * 2) which is 10 bees at level one.

this could be real powerful if chem rng is on your side

**Comment by GuyonBroadway** [comment]
@tortellinitony there isvan existing sprite for a bee object. I just used that.

As for balance reasonsbI could easily tweak it

**Comment by ghost** [comment]
@GuyonBroadway ima fix the conflict, gimme a sec

**Comment by GuyonBroadway** [comment]
I hit the wrong button. Anyway the logic for bee summoning looks a bit funny. On purchase it summons four bees on a 30 second cooldown. Upgraded once it summons six bees on a 25 sec cd. Upgraded twice 8 bees on a 20 sec cd. Then 10 on 15 sec then 12 on 10 sec.  I could easily tweak the number of bees or thr cd.

How about starts at 5 bees and only increases by 1 per spell rank? Or summons six bees and no increase at all?

**Comment by doobiedoo23** [comment]
yes

**Comment by ghost** [comment]
that's a +1 from bard and +1 from doobie, gonna merge.

**Pull request merged**
