### PR TITLE
Create lists

### PR DESCRIPTION
**Pull request by Shdorsh**
Adds a circuit that can join 2 lists

[Changelogs]: # Added a circuit that lets you merge 2 lists

:cl: join list circuit
add: A circuit that joins lists
/:cl:

[why]: # Added a circuit that lets you merge 2 lists, which was otherwise unthinkable, especially for bigger lists, giving more possibilities to the ones who like to craft circuits.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Not a dm file.
Change this to lists.dm and make sure it's ticked in hippiestation.dmb

**Comment by JohnGinnane** [comment]
@Shdorsh did you test this?

**Comment by Carbonhell** [comment]
You didn't pr this to tg too right? Anyway  +1

**Review by yoyobatty — APPROVED** [review]
Code looks good, make sure it's tested and get headmin input

**Comment by Shdorsh** [comment]
Been tested on my homeserver, works.

**Review by Carbonhell — APPROVED** [review]

**Comment by ghost** [comment]
+1

**Comment by tortellinitony** [comment]
+1

**Pull request merged**
