### PR TITLE
Kills triple virus stack

### PR DESCRIPTION
**Pull request by mikolaj007**
## Changelog
:cl: Mideanon
balance: You can now only have 1 advanced disease at once
/:cl:

## Why It's Good For The Game
because triple stack heal viruses are op
beating someones shit for a minute shouldnt let them get up the moment you stop stunning them.

### CODE REVIEW

**Review by Jujumatic — APPROVED** [review]

**Comment by Jujumatic** [comment]
needs head input

**Comment by Manly-Dwarf** [comment]
this is one advanced disease at a time, mind you

**Comment by Jujumatic** [comment]
Exactly why it needs head input, it's a balance change

**Comment by Jujumatic** [comment]
I mean fuck yeah change the description aaaaaaaa

**Comment by RafRoq** [comment]
wasnt the limit always 1 wot

**Comment by funkynuggets** [comment]
I thought you couldn't stack them? but sure +1

**Comment by TheMeatGod** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Pull request merged**
