### PR TITLE
Adds max Character limit to the Shuttle call reason

### PR DESCRIPTION
**Pull request by xTrainx**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
tweak: The shuttle cannot be called if you give a reason bigger than the max allowed limit, set as 112 as of this pull request
/:cl:

## About The Pull Request
This is mostly made to prevent what i assume is woody got wood copy pasta from spamming everyone's screens, addressing issue #8371, feel free to give me my shekels

## Why It's Good For The Game
It stops shuttle grifers

### CODE REVIEW

**Comment by AnthonyJNgo** [comment]
Can you remove the edit you made to the roundstart shuttle delay, and submit that as a separate PR?

**Comment by AnthonyJNgo** [comment]
Actually, heck, it's just a config option, it's fine.

**Review by AnthonyJNgo — APPROVED** [review]
lgtm
Would like to wait for @yoyobatty to review as Travis isn't going green for me.

**Comment by xTrainx** [comment]
that was just so i didnt have to wait 20 minutes to test lol

**Comment by carlopault** [comment]
-2 character limits are gay

**Comment by xTrainx** [comment]
it is literally a bounty pr

**Comment by AnthonyJNgo** [comment]
Pinging @yoyobatty or @Pyko1 for that other review before this is pushed.

**Review by yoyobatty — APPROVED** [review]
Seems fine

**Pull request merged**
