### PR TITLE
[MIRROR] Add support for auto admin when ran in single user mode

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/36075
--------------------
address is null in single user mode, but we didn't support that because address has been null because of a byond bug, but now that this is a config we don't have to care since its off in production.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
why is our proc so different?

**Comment by JohnGinnane** [comment]
because https://github.com/HippieStation/HippieStation/pull/6885

**Comment by JohnGinnane** [comment]
@Chnkr this is ready. I copied tg's version of client_procs and then added our mentor code back in. They also had a slightly different query being run but it looks like it just replaced a var with `world.internet_address`

**Comment by ghost** [comment]
Looks fine

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
