### PR TITLE
Animal Husbandry in Hydroponics Maint

### PR DESCRIPTION
**Pull request by carlopault**
image

## Changelog
:cl: Carlospaul
add: Added Animal Husbandry room in Botany maint. 
/:cl:

## About The Pull Request
Protozoa is making cow cubes, rabbit cubes, and chicken cubes along with breeding for cows and rabbits so you can have a stable source of milk and rabbit meat (meat). 

**EDIT:** I forgot to mention that I also included an assistant spawn location at the fancy table and a botanist spawn location in the animal husbandry room

## Why It's Good For The Game
Because coom. For now it will just have chickens because you can feed them and they lay eggs, so egg supply. I hope all of service can access the room because I just copied the Service Hall door and renamed it.

### CODE REVIEW

**Comment by AnthonyJNgo** [comment]
-3, make it a proper botany expansion to be honest, have it connected and shit.

**Comment by FantasticFwoosh** [comment]
Chickens lay natural cubes (eggs), so maybe we  should use incubators instead (edited because i was incoherently babbling). Nice bandaid to paying cargo for animals instead because public-garden got wrecked or the map just didn't provide it.

**Comment by carlopault** [comment]
image
I made changes, and added a second maintenance door to the holodeck control room in the top left. It starts with 1 chicken since it can birth more, I think.

**Comment by mkikt4743** [comment]
gapple

**Comment by mkikt4743** [comment]
gapple roundstart kinda op I feel but whatever otherwise botnis never grow them

**Comment by carlopault** [comment]
> gapple roundstart kinda op I feel but whatever otherwise botnis never grow them

what does golden apple do? I thought it was just some fancy apple

**Comment by FantasticFwoosh** [comment]
> 
> 
> > gapple roundstart kinda op I feel but whatever otherwise botnis never grow them
> 
> what does golden apple do? I thought it was just some fancy apple

Grind down into reagent gold/extract the gold gene, which i think there was a reaction with frost oil/protolathe to convert them to gold bars but that could be a /tg/ thing. You can sell the seeds for immediate cash because its *supposed to be* a mutation plant.

But yeah i agree, unnessecary, put a loot-drop list() with gapple weighted as more rare on that table if you could.

**Comment by MrEpicSax** [comment]
Fuck me it's just a golden apple.

Mutations are piss easy to obtain, we're talking gapple roundstart ~1-2 minutes ez including prep. The roundstart gapple is only "kinda op" if you have a bleed in your brain and don't know how to play botanist efficiently.

The real issue here is how terribly accessible this whole area is. Botany is already vulnerable enough without you giving some murderous greytiding fuck a backdoor into the heart of it and it's newly added facility. Please address this.

**Comment by carlopault** [comment]
image

I removed the windows. There is now a cow and 2 chickens in the room, you can milk the cow with a bucket. Replaced the flooring in Service Hall and removed the gapple. Expanded the animal husbandry room 1 tile up.

**Comment by MrEpicSax** [comment]
+1 looks better to me

**Comment by karmaisblackandbluepilled** [comment]
add the gapple back and it's a +3 from me

**Comment by mikolaj007** [comment]
+1, finally something else to do other than gacha

**Comment by karmaisblackandbluepilled** [comment]
+3

**Comment by carlopault** [comment]
I am gonna add a chicken cube box and a cow cube box to Hydroponics somewhere if the cow cube and chicken cube PR and this PR gets merged.

**Comment by cris5311** [comment]
+1

**Comment by wheezl** [comment]
+1 a good start we can tweak shit later, botany buffs are great

**Comment by byandaccount** [comment]
+1 having something else to do while your growing plants is great, plus being able to supply the chef with eggs n meat as a botanist sounds pretty cool.

**Comment by carlopault** [comment]
> +1 having something else to do while your growing plants is great, plus being able to supply the chef with eggs n meat as a botanist sounds pretty cool.

Dont forget you can milk the cow with a bucket

**Comment by AnthonyJNgo** [comment]
My requested change was made, changing my vote to +3, this has enough votes now.

**Review by AnthonyJNgo — APPROVED** [review]
LGTM!

**Pull request merged**
