### PR TITLE
[MIRROR] Crab Rockets

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35959
--------------------
:cl: Iamgoofball
add: Look sir, free crabs!
/:cl:

Crab Rockets are now orderable as a drop pod only purchase.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Man you guys have done a really shitty job of keeping Cargo up to date.

**Comment by JohnGinnane** [comment]
why is there so many more changes??

**Comment by praisenarsie** [comment]
because we missed a pr

#6890

**Comment by JohnGinnane** [comment]
thanks homie

**Review by JohnGinnane — DISMISSED** [review]

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
