### PR TITLE
[MIRROR] [Ready][?] Robustin's cult nerf, back from the dead.

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/39717
--------------------
:cl: Robustin, Subject217 and Carbonhell
add: Any non-cultist can now strike a (filled) soulshard with a bible to purify it. Purified shades have a unique appearance and will be eager to get revenge on the cult. Bibles can be printed in the library.
balance: Juggernauts have 25% less HP and 35% less projectile reflection.
balance: Cult mirror shield is slightly easier to break, has less illusions, and has -33% throwing distance.
balance: The EMP blood spell has -1 light and heavy radius.
balance: The revive rune now requires 3 sacrifices per revive, it still starts with one "freebie" revive. Giving "souls" to AFK/Catatonic cultists remains free of charge.
balance: Twisted Construction now has a channel time with added noise/effects when used on doors. It also hurts you slightly more to use.
balance: You can now only hold 1 blood spell without an empowering rune and 4 with one.
/:cl:

I really liked these changes, and I was sad to see it go unmerged. I played this version of cult several times during test-merges and it fixed a lot of the issues. I've put most of Robustin's changes in here.

As far as balance is concerned in retrospect given the small changes in the past few months, I reviewed them all, and I don't believe that the changes in this PR need any modification. Willing to continue tweaking Cult as necessary.

On the Bastard Sword: It's a really weird unintuitive item that a lot of people complain about. Naksu told me to remove cult's ability to make it, so that's what I've done. Cult in general is filled to the brim with bloat items that do something slightly differently without being very valuable so it's not a great loss.

### CODE REVIEW

**Review by yoyobatty — DISMISSED** [review]
Code looks good

**Comment by GuyonBroadway** [comment]
Gonna need some headmin input on this imo.

**Comment by Carbonhell** [comment]
goddamnit i thought cult was fine
uhh we need some player input aswell

**Comment by Eagle-Eyess** [comment]
-1 cult is fine. Being revealed as cult is a huge problem. No other antag, besides nuke ops and wiz, have a perma antag reveal and at least nukies and wizards have the option to stealth. The only change I kinda like is the soul shard one with the Bible. That seems cool.

**Comment by Manly-Dwarf** [comment]
`balance: Once the blood cult reaches 20% of the active player population, they will receive a notice that the cult is "rising" - and after a moderate delay the eyes of all existing and new cultists will be permanently red. Examining a cultist with uncovered eyes will confirm their supernatural appearance.
balance: Once the blood cult reaches 40% of the active player population they will receive a warning and after a moderate delay will glow red, permanently revealing the identity of existing and new blood cultists.`
Nope, fuck you.

**Comment by ExpAntique** [comment]
Where do i begin with this shitty grudge-code...

1. Bloody bastard sword is not OP, and shouldn’t be removed. It’s only available to the cult leader, and while it is a very strong melee weapon, it has no ranged capabilities and requires two hands to wield. A stungun and a quick drag can effectively take a bastard sword out of the fight.

2. The twisted construction change is stupid. You already need to wait to build with runed metal, and converted buildings are weak as fuck. Also the damage it does already puts you from blue to green and so on so what’s the point in making it do more?

3. >“You can now only hold 1 blood spell without an empowering rune and 4 with one.” 
 
 Why?

 4. >balance: Once the blood cult reaches 20% of the active player population, they will receive a notice that the cult is "rising" - and after a moderate delay the eyes of all existing and new cultists will be permanently red. Examining a cultist with uncovered eyes will confirm their supernatural appearance.
 
 What the fuck. Literally the whole point of cult is to hide in the shadows and strike when they have the upper-hand. This will literally ruin the stealth of cult entirely, and it completely uneeded.

 Everything else i mentioned is either stupid or unnecessary. In conclusion, fuck off.

**Comment by JohnGinnane** [comment]
@Carbonhell this is one of those PRs that we apparently don't want but will be awkward to mod out of the code..

**Comment by Carbonhell** [comment]
@JohnGinnane lies

**Comment by Carbonhell** [comment]
@t-f-w @fluxcapacitor1337 is it good now

**Comment by ghost** [comment]
+1

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
