### PR TITLE
Hiveminds now require 20 players in dynamic

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: Hiveminds now require 20 players to be considered in dynamic
/:cl:

### CODE REVIEW

**Comment by Toxici11i** [comment]
+1 fuck hivemind, buggy ass gamemode which gives you objectives higher than the current popcount unless its 15pop+

**Comment by Toxici11i** [comment]
also consider reducing the amount of hosts needed to unlock new tiers of shit

**Comment by cris5311** [comment]
+1
fucking hive giving me 11 obj with 8 people on station, 2 of which have a mindshield

**Comment by Manly-Dwarf** [comment]
+1

**Comment by ghost** [comment]
+1, merging

**Review by ghost — APPROVED** [review]

**Pull request merged**
