### PR TITLE
[MIRROR] Christmas

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/33690
--------------------
:cl: Kor
add: During Christmas you will be able to click on the tree in the Chapel to receive one present per round. That present can contain any item in the game.
/:cl:

Inspired by what goof did for baystation years ago.

Also removed the tree revenge event (dont want to destroy the present spawner) and lowered the santa coming to town event chance so not every single round for a week has a wizard in it.

### CODE REVIEW

**Comment by xTrainx** [comment]
well, box will be moved during christmas so...

**Review by ghost — APPROVED** [review]

**Comment by JohnGinnane** [comment]
@Chnkr what's this error about?

**Comment by JohnGinnane** [comment]
Just gonna restart this build to see if it's fixed

**Comment by cacogen** [comment]
pull this

**Comment by xTrainx** [comment]
we were much to late, christmas is ruined

**Pull request closed without merging**
