### PR TITLE
Make non-kidnapping clown cars not stun

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt
tweak: The roundstart clown car no longer stuns you for 4 seconds
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
What a completely pointless PR.
If you want to change the roundstart clown car, how about reduce its armor? Make it not spray lube on hit? Make it not explode on destruction outside of annihilating the dumbass Clown?
Those are the most abuse-able features of the whole thing. The stun is hardly anything.

**Comment by ghost** [comment]
4 seconds is still enough for the clown to fuck you over.

**Review by Carbonhell — DISMISSED** [review]

**Comment by Carbonhell** [comment]
Not sure about the change itself. I haven't witnessed problems ingame but i've not been very active. Waiting for more opinions, abstaining for now

**Comment by HippieBartels** [comment]
+1 I've personally abused the clown car one round and it is way OP right now.

**Comment by Eagle-Eyess** [comment]
+1

**Comment by ghost** [comment]
+1, the clown car is way too easy to abuse right now. Repeat kidnappings aren't even difficult to do as well.

**Comment by MrWankman** [comment]
Coming from the perspective as both a nigger driving the car and someone who's been it's victim I'd say a few things. First is that it's the funniest clown meme lately because of how much it quickly turns into a salt farm especially by people who don't know you can leave the car anytime. Second is that the stun is only bad if you are in a hurry to get something or go somewhere because you can almost instantly leave as it is. Third is that this is the first time I saw security actually jailing and perma-ing people(clowns) despite how much they wanted to just execute them. 
-1 It's a good meme and makes security actually do something lol

**Comment by ghost** [comment]
@MrWankman you can't leave the car at anytime, BECAUSE YOU'RE STUNNED FOR THE FIRST 4 SECONDS

**Comment by MrWankman** [comment]
Oh what's four seconds really? lol Really tho no body every decided to nerf stun from mop and water because the solution was to steal the mop and beat the janitor. Same solution happens here with the clown car and the clown.

**Comment by ghost** [comment]
Anyone can steal mops but only the clown can drive the clown car

**Comment by MrWankman** [comment]
Anyone can destroy clown car with ease. Just don't let the clown get in which is easy.

**Comment by ghost** [comment]
@MrWankman yes, but then it kills anyone nearby when it explodes

**Comment by MrWankman** [comment]
Well that is the risk for punishing the clown, and worst I seen the explosion do to someone is crit the clown and just injure others.

**Comment by ghost** [comment]
And possibly crit innocents in the clown car too.

**Comment by Lxtoofonea** [comment]
just remove it

**Comment by earthmoonjune** [comment]
roundstart clown car is being removed from the map so this is pointless now

**Pull request closed without merging**
