### PR TITLE
Fixes issue where tesla coils and rods don't show that they're bolted…

### PR DESCRIPTION
**Pull request by asskek**
Fixes issue where tesla coils and rods don't show that they're bolted down upon examine. 

#6395

### CODE REVIEW

**Comment by ghost** [comment]
shit, i just realised this to_chat() won't work properly
do
`to_chat(user, "It is fastened to the ground.")`

**Comment by Pyko1** [comment]
should really pr this to upstream

**Comment by ghost** [comment]
also probably change "ground" to "floor" for consistency :-DDD

**Comment by JohnGinnane** [comment]
thank you

**Review by JohnGinnane — APPROVED** [review]

**Comment by ghost** [comment]
thank god

**Comment by JohnGinnane** [comment]
fuck it, I'll do it upstream at some point

**Pull request merged**
