### PR TITLE
Reverts myself

### PR DESCRIPTION
**Pull request by ghost**
fuck you all

### CODE REVIEW

**Comment by ghost** [comment]
image

**Comment by dreamcrab** [comment]
wat

**Comment by Blute1** [comment]
lol

**Comment by praisenarsie** [comment]
mrty, get some sleep. 🛌

**Comment by ghost** [comment]
i neede sleepyes

**Comment by dreamcrab** [comment]
Amari's Journal. October 12th, 1985: Dog carcass in alley this morning, tire tread on burst stomach. This server is afraid of me. I have seen its true face. The streets are extended gutters and the gutters are full of blood and when the drains finally scab over, all the vermin will drown. The accumulated filth of all their sex and murder will foam up about their waists and all the coders and admins will look up and shout "Save us!"... and I'll whisper "no."

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
enough bullshit

**Pull request closed without merging**
