### PR TITLE
Mining Outpost Rework [WIP]

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl: zamolxius
tweak: remade the mining outpost in a more compact way that also brings less used rooms such as the kitchen or the infirmary into the spotlight more.
/:cl:

image

as compared to the old one 
image

still undergoing changes

@yoyobatty i shall require a map vibe check so i dont accidentally fuck something up

### CODE REVIEW

**Comment by ghost** [comment]
Is the gulag escape path still there?

**Comment by ghost** [comment]
more exactly? i dont know about it. there's a place in the far north of the gulag island where there's only a 1 tile lava gap if thats what you mean

**Comment by ghost** [comment]
@zamolxius ok good, just wanted to make sure that was sitll there

**Comment by GuyonBroadway** [comment]
Consider putting the Mining Ripley down there so we don't have to map it in to every station.

**Comment by ghost** [comment]
image

**Comment by Neotwr** [comment]
add another dock, for public mining
in this space, if you want
image

**Comment by ErwinSnowden** [comment]
> add another dock, for public mining
> in this space, if you want
> image

we don't have public mining on hippie, unless that's something you're planning to add.

**Pull request closed without merging**
