### PR TITLE
Prevents farting from doing damage outside of their ass-fall-off condition, adds a log to the attack log.

### PR DESCRIPTION
**Pull request by TDcoolguy300**
:cl: Fixes farts from doing damage unless they actually fall off, adds a combat log for it.
fix: Farts no longer randomly cause damage unless the ass actually falls off.
admin: If your ass slaps someone when it falls off, it's now logged in the combat log.
/:cl:

[why]: It just prevents fart spam from doing MASSIVE DAMAGE without the ass actually falling off.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
I accidentally managed to crit a player by farting on them.
This all isn't logged either, so merge this NOW

**Comment by TDcoolguy300** [comment]
Hang on, going to throw on a combat log because why not

**Comment by bardofrage** [comment]
+1 ofc

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
ready?

**Comment by Carbonhell** [comment]
also in the changelog, logging should be admin: not add:, it isn't really a feature but rather a fix for admins tbh
no need for heads +1s here

**Comment by TDcoolguy300** [comment]
Ready

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
