### PR TITLE
Changes holochips to real wads of cash (digitalizable)

### PR DESCRIPTION
**Pull request by ghost**
[Guidelines]:download (1)

## Changelog
:cl: zamolxius
imageadd: added some new cash icons
/:cl:

## Why It's Good For The Game
looks WAY better than that trashy holochip, little plastic shit

### CODE REVIEW

**Comment by ghost** [comment]
Give me feedback

**Comment by Jujumatic** [comment]
Hey the different colours are cool though I think the 1 bill looks a bit thin

**Comment by mikolaj007** [comment]
+1

**Comment by Manly-Dwarf** [comment]
Obligatory https://www.youtube.com/watch?v=ULeDlxa3gyc

**Comment by ghost** [comment]
thicker now @Jujumatic

**Comment by Jujumatic** [comment]
@zamolxius can i see the thicc version now

**Comment by ghost** [comment]
its basically a layer of the black edge pixels under the 1 dollar bill to make it thicker @jujumatic but I'll make a screen shot in like 5 hours bro

**Comment by mikolaj007** [comment]
already gave my +1, but this is 25 days old

**Comment by Majick1** [comment]
+1 just merge

**Review by ghost — APPROVED** [review]
yeet

**Pull request merged**
