### PR TITLE
Replay system

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/yogstation13/Yogstation/pull/7070

🆑 Originally by monster860 and asd, ported by Steamp0rt
add: Everything that happens gets logged to a replay file
/🆑

### CODE REVIEW

**Comment by boodaliboo** [comment]
wow stealing from yogs :(

**Comment by Quartich** [comment]
> wow stealing from yogs :(

Not sure if ironic but lol

**Review by yoyobatty — APPROVED** [review]

**Comment by ynot01** [comment]
> > wow stealing from yogs :(
> 
> Not sure if ironic but lol

please ignore him

**Comment by ghost** [comment]
boodaliboo 6 days ago
wow stealing from yogs :(

gay guy gay guy gay guy

**Pull request merged**
