### PR TITLE
Makes shotguns better

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl:
add: I used the shotgun. You know why? Cause the shot gun doesn't miss, and unlike the shitty hybrid taser it stops a criminal in their tracks in two hits. Bang, bang, and they're fucking done. I use four shots just to make damn sure. Because, once again, I'm not there to coddle a buncha criminal scum sucking faggots, I'm there to 1) Survive the fucking round. 2) Guard the armory. So you can absolutely get fucked. If I get unbanned, which I won't, you can guarantee I will continue to use the shotgun to apprehend criminals. Because it's quick, clean and effective as fuck. Why in the seven hells would I fuck around with the disabler shots, which take half a clip just to bring someone down, or with the tazer bolts which are slow as balls, impossible to aim and do about next to jack shit, fuck all. The shotgun is the superior law enforcement weapon. Because it stops crime. And it stops crime by reducing the number of criminals roaming the fucking halls.
/:cl:

### CODE REVIEW

**Comment by SireTurret** [comment]
+1

**Comment by ghost** [comment]
I'm actually serious about getting this merged.

**Comment by MaterialisticThings** [comment]
+1

**Comment by ghost** [comment]
**+1**

**Comment by cb583** [comment]
+1

**Comment by GuyonBroadway** [comment]
Please use the escape characters to make this into a paragraph as opposed to one big long line.

Otherwise it goes of the side of the screen and nobody can read the meme.

**Comment by ghost** [comment]
I'll redo the formatting.

**Comment by TrickyDickRichard** [comment]
+1

**Review by ghost — DISMISSED** [review]
yes

**Review by ghost — APPROVED** [review]
ooga booga

**Comment by diegoxt45** [comment]
what does this actually do lol

**Comment by TrickyDickRichard** [comment]
it changes the description of the riot shotgun chudbrain

**Comment by ExpAntique** [comment]
+1

**Comment by ghost** [comment]
fun fact: this won't show up ingame on riot or combat shotguns. they both override the `desc`.

**Comment by TrickyDickRichard** [comment]
you could have said that before

**Comment by ghost** [comment]
i JUST realized it

**Comment by ghost** [comment]
Well fuck. I'm going to have to make another PR. This was meant to effect the riot shotgun only, and I'm not sure how I didn't notice this before.

**Pull request merged**
