### PR TITLE
PEE PEE, POO POO

### PR DESCRIPTION
**Pull request by ghost**
[YOU GUYS VOTED FOR IT](https://hippiestation.com/threads/poll-to-see-if-we-should-add-pee-pee-poo-poo.7638/), I CODE IT!

:cl: Amari Ray
add: PEE PEE POO POO
/:cl:

### CODE REVIEW

**Comment by Pyko1** [comment]
Just need someone to sprite for it

**Comment by ghost** [comment]
@Pyko1 that stupid WW2 server has all the sprites I could ever need for peepee poopoo

**Comment by dreamcrab** [comment]
this isnt happening unless its under my very specific guidelines which i have detailed in my original ass update post

**Comment by Pyko1** [comment]
shush @dreamcrab you do not understand the real pee pee poo poo

**Comment by dreamcrab** [comment]
-52345 close this garbage it is never getting passed

**Comment by KayeArray** [comment]
-1, there is only one man who can truly do poo poo and it is neither you nor teamstab

**Comment by ghost** [comment]
@dreamcrab be open minded rather than pushing your worse idea

**Comment by ghost** [comment]
**IDEA: WE TESTMERGE THIS AND SEE HOW THE PEOPLE WHO ACTUALLY MATTER, THE PLAYERS, LIKE IT?**

**Comment by dreamcrab** [comment]
literally never going to happen

**Comment by ghost** [comment]
@dreamcrab You realize you're basically saying "Fuck the players, i'm going with my own horrid agenda", right?

**Comment by ghost** [comment]
we already test merged the monkey PR and the idea was terrible and abuseable
no

**Comment by ghost** [comment]
@McBawbaggings This isn't monkeys. This is even more balanced (you can't shit unless your well fed, shitting drains nutrition, pissing drains "bladder")

**Comment by dreamcrab** [comment]
never 

going

to

happen

**Comment by ghost** [comment]
@dreamcrab fuck off

**Comment by ghost** [comment]
closing because headmins are massive fucking cucks

capture

**Comment by Iamgoofball** [comment]
remember: this guy coded poo

**Comment by Incomptinence** [comment]
a true hero

**Comment by SpaceJohn413** [comment]
why

why the fuck is this PR a thing

ss13 is dead

**Comment by optimumtact** [comment]
wtf headadmins dont' even care, rreeee, this is what facism looks like

**Comment by Pyko1** [comment]
This is why separation of code and admins is vital!

**Comment by Panduzzy** [comment]
The mad lad actually coded it.
(Enjoy this shitty sprited poo i did in five minutes)
https://mega.nz/#!eoxmmI6Q!cnFEscUG6R1Sp0-XrEJILJPygqr1NKirZpnHbvQOh_k


Edit - Welll shiiieeeeet, there goes my five minutes

**Comment by praisenarsie** [comment]
th- uh- the pr is closed...

**Pull request closed without merging**
