### PR TITLE
Adds Sopa de Macaco

### PR DESCRIPTION
**Pull request by ghost**
:cl: McBawbaggings
add: Added Sopa de Macaco. Made with a bowl, 10 water and monkey meat.
/:cl:

Uma delicia.

### CODE REVIEW

**Comment by ghost** [comment]
You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by KayeArray** [comment]
monkey cube soup when

**Comment by ghost** [comment]
Already exists:
https://github.com/HippieStation/HippieStation/blob/2ec79b40144fa45541096ea7946421af553750de/code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm#L37

**Comment by ghost** [comment]
uma delicia +1

**Comment by JohnGinnane** [comment]
Restarting build because Travis took too long

**Comment by 81Denton** [comment]
UMA

**Review by JohnGinnane — APPROVED** [review]

**Comment by earthmoonjune** [comment]
me like mompkey soop +1

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
Why did this take 12 days even

**Comment by ghost** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
