### PR TITLE
Reverts chem heater, stock computer, others icons.

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
imageadd: Switched back to the old stock computer, chemical heater, lightbulb box, quantum relay, auto announcer, and solar computer icons.
/:cl:

closes #4916

### CODE REVIEW

**Comment by Carbonhell** [comment]
yESSS

**Comment by KayeArray** [comment]
+1 lol

**Comment by ghost** [comment]
👍 There is only one major issue that i see with this.

TG will continue to add new machines/boards that require a unique sprite, these sprites are in the "new" format.

How do we expect to handle this?

**Comment by tortellinitony** [comment]
if it's a completely new machine then who cares, this is just for the traditional look of things we've already had and don't want changed

**Comment by dreamcrab** [comment]
+10

**Comment by GuyonBroadway** [comment]
this mix and matching will start to clash sooner or later.

**Comment by tortellinitony** [comment]
yeah that's why we're changing them back so it clashes less

**Comment by dreamcrab** [comment]
this game is a huge mishmash of sprites from different people and always has been, i dont mind at all

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
what dreamcrab said
+1

**Comment by ghost** [comment]
i don't like the new sprites.
the old sprites are inconsistent (and always has been) but they tend to be pretty clear in what they look like, which i think is better design

**Comment by ghost** [comment]
+1

**Comment by GuyonBroadway** [comment]
Well thats a +3.

**Pull request merged**
