### PR TITLE
[MIRROR] Gives the Centcom Podlauncher back it's old, sexy, chad UI. Also, prevents all tgui tooltips from FUCKING BLOCKING CLICKS REE

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42911
----------------------------

basically it fixes the underlying issue that caused [this abortion of a PR to exist](https://github.com/tgstation/tgstation/pull/41821)

image

## About The Pull Request
improves centcom podlauncher UI by reverting it to the good old state while removing the issues it had with tooltips blocking shit

## Why It's Good For The Game
makes admins happy

## Changelog
:cl: MrDoomBringer
fix: The centcom podlauncher UI no longer looks like shit
fix: Tooltips will no longer stay around if you hover over them (which would lead to them blocking shit underneath)
/:cl:

### CODE REVIEW

**Comment by Jujumatic** [comment]
merge conflicts popping up but there's no conflict...?

**Comment by k-k-karma** [comment]
there is, you need to rebuild tgui again

**Comment by Jujumatic** [comment]
why is this fucking conflicting, i rebuilt everything and it didn't change anything

**Comment by Jujumatic** [comment]
fuck fuck fuck

**Review by Jujumatic — APPROVED** [review]

**Pull request merged**
