### PR TITLE
Remaps sing to fix the no-sing power bug.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
fix: THe Singularity now generates power, this now works because the radiation collectors are in the containment area much like the tesla coils. As an added bonus there are now 8 radiation collectors as opposed to six so the sing will end up generating far more power than the tesla.
add: In order to facilitate this new space based setup an extra hard-suit has been added to engineering. 
/:cl:

It might look odd but this is how pubbystation fixed the issue and they have the same tesing setup we have.

image

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
o-fuck (exit guyon)

**Comment by GuyonBroadway** [comment]
Well this is significantly better but its still terrible.

**Comment by ghost** [comment]
just save the map as is, drop it out, reset the file, prepare map and map merge after dragging and dropping the new version

**Comment by GuyonBroadway** [comment]
I also notices that this setup needs another grounding rod or two else shit blows up if you decide to use the tesla.

**Comment by GuyonBroadway** [comment]
wowie its still shit.

**Comment by GuyonBroadway** [comment]
hold up, its still producing shit all power.

**Comment by GuyonBroadway** [comment]
ok this went shit, time for plan B.

**Pull request closed without merging**
