### PR TITLE
various map changes

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: # mostly in maint, also adds a weed poster to the botanist backroom, various maint additions such as switchblade in the old location, expanded arrivals maint, secret lizard lynch remnants. has secrets. @yoyobatty please review and feed me back. Wrestling room north of ghetto chem

:cl: zamolxius
add: Added maint/map additions ( weightlifting room, ghetto botany with chickens, arcade room which also has a fakewall in arrivals maint, secret lizard lyncher crevice, enlarged chapel maint, added a new tunnel to science maint with a fakewall to evade pursuers, little shack with inflatable door replica katana and a buckler, cuban pete hat beyond the toxins testing site, wrestling ring at escape)
balance: switchblade in maint, nothing else major. uhh weightlifting room has a pizza box because you gotta eat big to get big
fix: slightly fixed the lack of good maint
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

if this has the step_x shit again i know how to fix

dd31a771092d4e09b6a1aa689f1eec55
f587debb3d5aad07bd2647bc3cf69b09
647f3358b08f3af267d96559f1293e98
4b023ba220de67e3af9389a83ff3a381
a74288dc00de4816761b76ea2b95b4d2
576246b9b85dde014c1c38819f149eae
370bc1846c3dad4e458a908a3d504fe3

### CODE REVIEW

**Comment by ghost** [comment]
this is ready for review and merge if it checks and etc @Carbonhell

**Comment by Dinopeaks** [comment]
map bot is broken you will need to post pics of the things you did

**Comment by ghost** [comment]
done

**Comment by Dinopeaks** [comment]
you made a rage cage in chapple?

**Comment by ghost** [comment]
yes

**Comment by JohnGinnane** [comment]
I really like these changes

**Comment by earthmoonjune** [comment]
ye sure +1

**Comment by Jujumatic** [comment]
these changes are awesome though what's up with the chapel one?

**Comment by ghost** [comment]
it's a wrestling ring @jujumatic plus slightly expands the chapel maint, just slightly.

**Comment by Jujumatic** [comment]
a wrestling ring in the same room that you place bodies into caskets and send them into space?

**Comment by ghost** [comment]
we had it before iirc, pre rebase

**Comment by Jujumatic** [comment]
*shrug* i like the whole thing anyway, ya dun good

**Comment by Carbonhell** [comment]
+1

**Comment by ghost** [comment]
5b6b2b24e3cef6689f4698afaae742d9

**Comment by GuyonBroadway** [comment]
Prebase the "maint garden" had about 7 full size botany trays. and both types of botany vending machine. along with the Biogenerator. 

It was neat.

**Comment by ghost** [comment]
47b0c16dfd8e4973e214c74d04ae9735

**Comment by yoyobatty** [comment]
Looks great, I just personally think it needs more cleanable decals and posters + garbage, it is maint after all. Other than that, great job m8.

**Comment by Pyko1** [comment]
not really big fan of having the wrestling ring in chapel, otherwise looks good.

**Comment by yoyobatty** [comment]
I agree with pyko, the wrestling wring is very out of place. If you want ideas for putting it somewhere, check out deltastation, it will be in the map files.

**Comment by ghost** [comment]
b5510e1334adc9b802f7e50fe2854632
thats a replica katana btw
278fc651ee9c266eff4d06d25d32c614
1d97546d6c3641d21542dc5c30e25f07

**Comment by ghost** [comment]
@yoyobatty

**Comment by ghost** [comment]
every time i open it i end up adding something more

**Comment by yoyobatty** [comment]
Looks better, I would be down to merge this.

**Review by ghost — CHANGES_REQUESTED** [review]
Not map merged as of yet.

**Comment by ghost** [comment]
remade here https://github.com/HippieStation/HippieStation/pull/7586

**Pull request closed without merging**
