### PR TITLE
Carbonhell now spawns with the proper attire.

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Changelogs]: # 

:cl: Kawaii-Big-Boss
tweak: Carbonhell now spawns with the proper attire.
/:cl:

[why]: # 
https://en.wikipedia.org/wiki/Pizza
https://en.wikipedia.org/wiki/Calzone
https://en.wikipedia.org/wiki/Spaghetti
https://en.wikipedia.org/wiki/Pasta
https://en.wikipedia.org/wiki/Benito_Mussolini
https://en.wikipedia.org/wiki/Armistice_of_Cassibile
https://www.theguardian.com/world/1943/sep/09/secondworldwar.italy
https://www.youtube.com/watch?v=czTksCF6X8Y

### CODE REVIEW

**Comment by ghost** [comment]
+1

**Comment by KayeArray** [comment]
>check on life
funny joke but no

**Comment by Manly-Dwarf** [comment]
killing self 3

**Comment by Manly-Dwarf** [comment]
also nobody noticed the stealth merge I did lmao

**Comment by DaydreamPuppeh** [comment]
I noticed

**Comment by Pyko1** [comment]
-1 you think a cook attire is proper to someone who cooks corn potato pizza?

**Comment by Manly-Dwarf** [comment]
That's a good point. Will reupload with updates.

**Pull request closed without merging**
