### PR TITLE
Shuttle be gone

### PR DESCRIPTION
**Pull request by Eagle-Eyess**
:cl: EagleEyes 
del: Shitty shuttle removed
/:cl:
(This is how you format a changelog)
the rather large shuttle was never a good thing for the server, only really ever helped the antags get ez kills for little work. No reason to have this be a thing anymore.

You wanna take the shuttle by force? you better work for it.

### CODE REVIEW

**Review by Jujumatic — APPROVED** [review]
weird diff but it checks out

**Comment by k-k-karma** [comment]
NO MAN PLEASE IT TOOK ME LIKE 5 SECONDS TO MAKE THIS

**Comment by k-k-karma** [comment]
> weird diff but it checks out

thats because it's a revert pr

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by yoyobatty** [comment]
Fix your changelog, put del: behind it and put your name after cl:

**Comment by Lxtoofonea** [comment]
+1

**Comment by Zyzarda** [comment]
+1

**Comment by Manly-Dwarf** [comment]
+1 ok you can merge this now
destroy shuttle

**Pull request merged**
