### PR TITLE
[MIRROR] Equalizes Roundstart Mining Options (Removes some Advanced Scanners and Explorer Webbings)

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/38153
--------------------
:cl: Cobby
del: Removed Advanced Mining Scanner from roundstart voucher kits.
del: Removed Explorer Webbing from all voucher kits besides the shelter capsule pack.
/:cl:

Advanced Mining Scanner was removed to allow other packs to compete. When people are taking packs explicitly for the scanner, then it should probably be gated. If the lesser one is so trash then a separate PR can be made to remove the lesser and make the advanced be the default.

Explorer Webbing was removed for the very same reason, especially considering lockers come with shelter capsules basically making this choice a noob trap. Now you have to explicitly choose for the extra storage roundstart.

I've checked but if you are _filled with determination_ you can try to see if I overlooked anything by taking conscript for yourself lol.

This is, imo, a more sane way than #38123 which tried to arms race with other packs rather than just removing the offending items that made the select kits so desirable (that weren't related to the actual purpose of the kit, gotcha's get out).

Before I get the "resonators suck" flood, that's not my problem. It's not like they were being used anyways, people were just taking the kit for the desired items (hint: not the resonator) and just leaving it at base lol. This PR will have minimal effect on resonator **usage** (if such exists outside of golems). Hopefully someone can buff the poor thing.

Closes #38197

### CODE REVIEW

**Review by yoyobatty — COMMENTED** [review]
No.

**Comment by WarRage333** [comment]
fuck off with these ''balance changes''

**Comment by GuyonBroadway** [comment]
We can merge this safely as I've already overidden the mining voucher rewards in another PR so we won't get the balance changes.

Also interestingly, we didn't update a recent change tg made to GIVE the crusher kit an advanced scanner.

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
I'll go ahead and merge it then.

**Pull request merged**
