### PR TITLE
Fix damp rag smothering

### PR DESCRIPTION
**Pull request by ghost**
Code causing them to not work: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/code/modules/reagents/reagent_containers/glass.dm#L44-L49

:cl: steamp0rt
fix: Smothering with damp rags works again
/:cl:

### CODE REVIEW

**Review by yoyobatty — DISMISSED** [review]
Why isn't this modularized/have comments indicating hippie edits?

**Comment by ghost** [comment]
@yoyobatty this was a webedit. will fix.

**Comment by ghost** [comment]
ok it's modularized

**Comment by ghost** [comment]
@yoyobatty modularized and compiling now.

**Review by ghost — APPROVED** [review]

**Pull request merged**
