### PR TITLE
Fatty Update

### PR DESCRIPTION
**Pull request by SireTurret**
## Changelog
:cl: Turret
add: People now appear bigger when they eat too much.
/:cl:

## About The Pull Request

Self-explanatory.
## Why It's Good For The Game

Self-explanatory 2.

### CODE REVIEW

**Comment by TrickyDickRichard** [comment]
yes +1

**Comment by ghost** [comment]
holy fuck +1

doea this get removed if u get skinny again or can you just get repeatedly fatty and skinny using lipozine to become BIG CHUNGUS

**Comment by SireTurret** [comment]
> holy fuck +1
> 
> doea this get removed if u get skinny again or can you just get repeatedly fatty and skinny using lipozine to become BIG CHUNGUS

if it's bugged you can probably become BIG CHUNGUS

**Comment by SireTurret** [comment]
imma drop the ball on the gibbing part since its stupid

**Comment by Manly-Dwarf** [comment]
For obvious reasons, no.
Having to create extra sprites for fatasses and conversely punishing people for eating too much just makes everything more tedious. Makes coding more tedious, make spriting more tedious, makes the food system even more tedious.
Give me one good reason why this PR should not be closed immediately, because this isn't even the Goon implementation of fatasses either (i.e the ideal implementation)

**Comment by Manly-Dwarf** [comment]
"its funny" is not a reason because it's not as funny as the goon implementation

**Comment by SireTurret** [comment]
> For obvious reasons, no.
> Having to create extra sprites for fatasses and conversely punishing people for eating too much just makes everything more tedious. Makes coding more tedious, make spriting more tedious, makes the food system even more tedious.
> Give me one good reason why this PR should not be closed immediately, because this isn't even the Goon implementation of fatasses either (i.e the ideal implementation)

we don't need sprites for fatties, we can just rescale them

also what's the goon implementation of fatasses

**Comment by ghost** [comment]
but dwarf,  this is not making anything require more spriting,  it just warps the sprite

**Comment by Manly-Dwarf** [comment]
"we can just rescale them"
what a horrible idea lol
goon actually uses sprites and has a ton of jokes. you're so fat, jumpsuits instantly burst when you put them on. people can't push your fat ass out of the way. people attempting to pull you slows them down a ton. you're blubbering and worthless
if you just wanna rescale it then it's a lame cop-out

**Comment by SireTurret** [comment]
This code doesn't even work anyway.

**Comment by Manly-Dwarf** [comment]
candy ass

**Comment by SireTurret** [comment]
> "we can just rescale them"
> what a horrible idea lol
> goon actually uses sprites and has a ton of jokes. you're so fat, jumpsuits instantly burst when you put them on. people can't push your fat ass out of the way. people attempting to pull you slows them down a ton. you're blubbering and worthless
> if you just wanna rescale it then it's a lame cop-out

unfortunately my dumb ass is unable to copy (steal) goon's system of fatties, so I guess until someone else wants to implement it fatties will remain the same

**Comment by SireTurret** [comment]
thats given if we don't get DMCA'd by goon if someone tries to do that

**Comment by Manly-Dwarf** [comment]
goon won't DMCA you for using their open source code release
our chat and other features are directly lifted from goon's

**Comment by SireTurret** [comment]
are their fatty system in the release though

**Comment by Manly-Dwarf** [comment]
pretty sure but it won't work at all with the current code. you'll have to "backport" it.

**Comment by SireTurret** [comment]
gay

**Pull request closed without merging**
