### PR TITLE
Re-adds strange room, moves the forge, adds autolathe into testing lab.

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: Moved the forge into construction room
add: Added connectors to scrubbers and portable airpumps in arrivals
add: Added back the old strange room pre 2017 rebase
del: Removed ghetto chemistry
balance: Adds higher sec access to gulag shuttle maint airlock
fix: Fixed a broken pipe and catwalks
/:cl:

[why]: Fuck you karma.

### CODE REVIEW

**Comment by yoyobatty** [comment]
@t-f-w @bardofrage @Lxtoofonea

**Comment by TheMeatGod** [comment]
+1 Forge always felt awkward where it was

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by earthmoonjune** [comment]
+1 but you better bring back south east ghetto chem or i'll get my squad and gat yo ass

**Comment by RafRoq** [comment]
-1 bring back gheto Chem or I will have to steal chemistry Chem dispenser every round again

**Pull request merged**
