### PR TITLE
[EXTREMELY WIP] Magic system

### PR DESCRIPTION
**Pull request by ghost**
# VERY WIP. WILL NOT BE DONE FOR QUITE A BIT. PROBABLY WON'T TAKE AS LONG AS PILLARMEN

Untitled Diagram

**Core (all) Magic**
----
 - If you're off by so many "ingredients" (depends on how complex the magic is), you get a misfire. It's a variant of the magic's effect, but always negative and usually harmful or violent.  
 - A non-wizard casting magic will slowly result in "residual energy" buildup. This is unnoticeable... until it starts killing you HARD. Luckily, residual energy dissipates rather fast, depending on multiple factors.
 - If you're smart, you can redirect the misfire's effects towards someone else, or trick someone else into taking the misfire.
 - Effects will react to antimagic. This means _actual antimagic_, like adamantite golems, not holy antimagic like the Chaplain. It'll either be just nullification of the effect, or if the spell's more complex or powerful, an ***amped*** misfire.  
 - Magic will naturally "reject" some people. This is usually bad for the rejected person. So no, telehulks can't cast ~~fireball~~ arcane barrage.

**Symbolistic Magic**
----
 - Based around writing words (or maybe symbols) on paper.
 - The most powerful form of magic.  
 - More powerful spells will require writing on and binding multiple pieces of paper together.  
 - The randomly generated words will usually be a mix of Latin and English.

**Ritualistic Magic**
----
 - Based around setting up physical "rituals" -- like cult runes.  
 - Cults will use a form of this.
 - The flow of energy and the "traits" that said energy picks up through "layers" determines the spell.  
 - Traits are determined by what items are in the "layer".
 - A layer is just a hollow square X amount of tiles from the center.
 - 3 types of manifestation: Binding, Manifesting, and Casting.  
 - Binding will bind the magic to an object in the center.
 - Manifesting will just activate the spell in the center of the ritual.
 - Casting will allow the user to call upon the magic. Can have 1 use, can have many uses.

**Invoking Magic**
----
 - The weakest form of magic. Pretty much like symbolistic magic, but involves saying words out loud rather than writing them down.
 - Wizards will use this normally. This will take the place of most of the normal wizard spells.

### CODE REVIEW

**Comment by epicss13gamer** [comment]
AMARI RAY, MORE LIKE AMARI GAY HAHAHAHAHA

**Comment by ghost** [comment]
I'd prefer discussion be at least slightly on-topic

**Comment by notoriousBIGGIOS** [comment]
+1

**Comment by Toxici11i** [comment]
+1, good idea and has the RNG chance of fucking blowing your ass up whenever you try to tide too hard with magic

**Comment by Toxici11i** [comment]
also i cant wait for RNG damage on magic missile as the magic potential is randomised every round - see nukies getting tapped by greys hue

**Comment by diegoxt45** [comment]
+1

**Comment by ghost** [comment]
no. the only RNG will be roundstart generation.

I plan to make nothing afterwards rng-based!

**Comment by JessHorserage** [comment]
+1, this looks fucking amazing

**Comment by DaydreamPuppeh** [comment]
The magic buildup seems familiar to me

**Comment by ghost** [comment]
@DaydreamPuppeh hm?

**Comment by Manly-Dwarf** [comment]
this is a very high quality idea
hopefully it pans out well

**Comment by JessHorserage** [comment]
Thanks for doing this by the way, if the infra is good, might even bait in some new minor pulls for a bit of magic in areas.

**Comment by ghost** [comment]
flow tree example

**Comment by ghost** [comment]
what is this @steamp0rt

**Comment by mememanrino** [comment]
ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn +1

**Comment by carlopault** [comment]
+1, this is epic.

**Comment by ErwinSnowden** [comment]
Anime man, add a way to attain heaven with stands. Would be cool. of course it'd have to be RnG.

**Comment by ErwinSnowden** [comment]
> The magic buildup seems familiar to me

It's like a certain bay-subsidiaries "technomancer" instability buildup, or say, genetic instability from goonetics. Also idea, can use symbolism to represent a stand arrow somehow and create the supervirus that gives guardians.

**Comment by Toxici11i** [comment]
confirmed ded

**Comment by Manly-Dwarf** [comment]
wtf reopen this

**Comment by DaydreamPuppeh** [comment]
Fuck you steamp0rt you lazy fuck

**Comment by TrickyDickRichard** [comment]
reopen it now bich

**Pull request closed without merging**
