### PR TITLE
Attempt to fix the pAI buys.

### PR DESCRIPTION
**Pull request by TungstenOxide**
cl:tweak: Flipped two lines

pAI software is able to be bought twice, meaning that a user could pay double the ram simply for clicking twice. I don't have a way of testing this theory, since I'd need another player to pick up and use the pAI after I kill myself and become one. Maybe if it's added to the pAI before the cost is subtracted, it won't be purchased twice.

### CODE REVIEW

**Comment by ghost** [comment]
worth taking this change upstream if the issue is inherited from /tg/ itself

**Comment by TungstenOxide** [comment]
I'll check, although I'd like to test this before introducing it upstream.

**Comment by TungstenOxide** [comment]
Yup, it's the same way upstream as well, but since this is difficult to test, I think we should just apply it to hippie station until we know it works.

**Comment by ghost** [comment]
fair enough

**Comment by j-mie** [comment]
Testmerged

**Comment by TungstenOxide** [comment]
Has anyone had the chance to test it? I was at dinner.

**Comment by j-mie** [comment]
best to make this change upstream: https://github.com/tgstation/tgstation - i think it's a /tg/ bug.

**Comment by TungstenOxide** [comment]
Alrght.

**Pull request closed without merging**
