### PR TITLE
Energy Based Weaponry Rework | Gauss Rifle [Awaiting-Merge] [OLDBASE-PORT] [Modular]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## Energy Based Weaponry Rework 

This is a port of my old framework from before the rebase occurred however heavily modified to fit TG's new base, I'll be listing out the key differences and changes as they're pretty relevant. 

ORIGINAL PR: https://github.com/HippieStationArchive/HippieStation13-1/pull/2505

Processes and functions can be checked out by coders. They are designed to make creating multistate energy weapons easy, and more efficient.

This also fixes the bug where sprites bug out when thrown.
Example:
https://i.imgur.com/kEY4rHb.gifv

Core changes:

So first off, the old system worked like this:
image
It took one of the bars, and filled the sprite. This meant that when throwing it the bar sprite would not rotate and was a total waste of resources. Fairly simple.
What I have done is changed it to use whole bars. Like the laser gun. However now it can be set to different modes.
image
Thus causing less lag, because you don't need to draw as many sprites. And fixing the rotation problem as the sprites are directly part of the main overlay. It is now much easier to add in a multifunction gun, all you need to do is add in the declare of the gun, set multistate to true and you are good. Inhand sprites are processed automatically too.

Updated sprites:
Pulse rifle:
image
https://i.imgur.com/Nc5GrB7.gifv

Pulse carbine:
image

Pulse pistol:
image

Ion rifle:
image
image
image
image

- The legacy system still functions fine.
- Updated guns to have a colour changing charge meter.

## Gauss Rifle
You didn't think I wouldn't give you a demo gun of the new system did you?
So I've decided to port the old gauss rifle, except now it's even **BETTER**. Lets get right into it.
image image
- It has 3 modes: Low power, medium power and OVERDRIVE.
- It has a cell rated to 30k and a 50 rod ammo cap. It is re loadable and rechargeable.
- It has a special suicide act.
- It is reloaded using rods.

**Mode types:**
- Low power
This is the lowest setting, and does 20 damage and can shoot through windows. Fairly unremarkable. Rods are destroyed after shooting.
- Medium power
This is your inbetween death setting. It does 35 dablage. It acts like the rod gun from old hippie. To summarise it embeds the rods fired into the person. Epic. Rods can be picked up if they hit something that isn't embeddable and can be pulled out of people via the standard embed removal system.
- OVERDRIVE
This setting is the most powerful. At the foundation it does 45 dablage. The gauss rifle overcharges it's capacitor bank to fire an overwhelmingly powerful shot however they takes a second to charge. This shot will dismember legs and arms on impact at a 80% chance. It has a 10% flat chance to decapitate and a 15% chance to disembowel someone.  If you miss and shoot a wall or something not a mob it will spawn a "broken rod" which can be welded back into a normal rod. SIMPLE_ANIMALS will be o b l i t e r a t e d if below 10 hp. Fuck you punpun for all those times you've robusted me. 
- Suicide
This will simply decapitate the target.

This weapon is available in R&D.
**R&D stats:**
- Required nodes: emp_adv and adv_weaponry
- Research cost: 2500 G
- Materials: MAT_SILVER = 8000, MAT_URANIUM = 8000, MAT_GLASS = 12000, MAT_METAL = 12000, MAT_GOLD = 10000
- Department: Security

**Demo:**
https://www.dropbox.com/s/ppb8mmkh9qkoruy/kVOxiq53dk.mp4?dl=0

Bug fixes:
- Fixed sprite breaking when throwing weapons.
- Fixed stungun sprite not updating when charging.

To-do: 
- [x] Intense testing.
- [x] Modularize.
- [x] Add to R&D
- [x] Final testing!

## Changelog
:cl: Gandalf2k15
add: Added a new energy framework for making energy based guns.
add: Gauss rifle! It's back.
tweak: Sprite processing is slightly different.
fix: Fixed the sprite bug when throwing weapons.
fix: Fixed stungun sprite not updating when charging.
fix: Fixed self charging eguns and some eguns not updating when empty.
imageadd: Updated all existent sprites to use the new framework.
refactor: Heavily modified and streamlined previous rework code.

/:cl:

## About The Pull Request
See above.

## Why It's Good For The Game
It makes creating energy weapons with multiple settings a lot easier and fixes the glitchy sprites.

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Also need to post pictures of all the sprites. Which is why its WIP.

**Comment by NautilusViper** [comment]
I noticed that stun guns don't change their sprite properly as they recharge, that should probably be included in this PR

**Comment by Gandalf2k15** [comment]
I have fixed that too. I spent a good 5 hours going through every current Sprite and updating it

**Comment by Gandalf2k15** [comment]
Fixed the stungun sprite now.

**Review by ghost — COMMENTED** [review]
i'd prefer this modularized but the other maintainers would be like "HGTOW LOL LOL" even tho HGTOW is doomed to fail due to lack of active maintainers (like i barely see the other maintainers online on friggin Discord)

fuck HGTOW

**Comment by Manly-Dwarf** [comment]
[You're gonna make me murder you in your sleep, lad.](https://github.com/HippieStation/HippieStation/pull/11696)

**Comment by Gandalf2k15** [comment]
That PR wont be effected because the legacy system still exists. And your energy.dmi is different from the one modified in here, so dinnae worry lad, that PR ain't going to be bothered.

**Comment by NautilusViper** [comment]
> i'd prefer this modularized but the other maintainers would be like "HGTOW LOL LOL" even tho HGTOW is doomed to fail due to lack of active maintainers (like i barely see the other maintainers online on friggin Discord)
> 
> fuck HGTOW

this

**Comment by Gandalf2k15** [comment]
Explain please

**Comment by ghost** [comment]
modularizing code is the process of attempting to keep most/all code OUTSIDE of the normal `code` folder, and in the `hippiestation` folder.

HGTOW  (hippie going their own way) is the stupid /tg/ split thing,

**Comment by Gandalf2k15** [comment]
Commited gauss rifle, check the PR for the information! I'll upload a video soon.

**Comment by Gandalf2k15** [comment]
Alright here's the demo of the gauss rifle:
https://www.dropbox.com/s/ilc0gbqgoh5dgfe/kVOxiq53dk.mp4?dl=0

**Comment by Gandalf2k15** [comment]
Hnnnngh full demo: https://www.dropbox.com/s/ppb8mmkh9qkoruy/kVOxiq53dk.mp4?dl=0

(ignore the insta decap, prob statement was broken, fixed now.)

**Comment by Gandalf2k15** [comment]
This has now been modularized. Thank fuck.

**Comment by Manly-Dwarf** [comment]
good work
also I like how back on the original PR I joked about how those random guns will nerf changelings lol

now to re-add the legendary gib gun

**Comment by Gandalf2k15** [comment]
I am very very glad hippie is less balanced obsessed now. It allows for SO much more fun.

**Comment by Gandalf2k15** [comment]
Added Gauss to research nodes, please see the R&D section of PR for more information.
All targeted steps have been completed.
I'm now moving on to final testing and should be complete within the next few hours.

**Comment by Gandalf2k15** [comment]
Updated balance on gauss rifle: dismember now 80% chance.

**Comment by theworldo** [comment]
+1

**Comment by Gandalf2k15** [comment]
Final testing completed, bug fixes uploaded. Small 3 person play test complete. New decap chance for head/chest is 10% so it is balanced. Removed pinning to walls.

This PR is now awaiting review.

**Comment by AnthonyJNgo** [comment]
Someone that actually knows git commands and properly labels their PR? What is this, my birthday? Big +1 to this PR.

**Comment by Gandalf2k15** [comment]
Final changes applied.

**Review by ghost — APPROVED** [review]
ok

**Pull request merged**
