### PR TITLE
Gives mime and clown maint access

### LINKED ISSUE #2108: CLOWNS AND MIMES ARE MISSING MAINT ACCESS
[Autistic honking]

### PR DESCRIPTION
**Pull request by Carbonhell**
:cl: 
fix: Fixes clown and mime lacking maint access.
/:cl:

Fixes #2108

### CODE REVIEW

**Comment by tortellinitony** [comment]
No :-1:

**Comment by ghost** [comment]
No

**Comment by Carbonhell** [comment]
no what, it's not a feature, it was like this on old hippie too lmao

**Review by j-mie — APPROVED** [review]

**Comment by j-mie** [comment]
They had access before.

**Pull request merged**
