### PR TITLE
adds a screwriver to oldstatioin

### PR DESCRIPTION
**Pull request by xTrainx**
:cl: xTrainx
add: a new ruin who is identical to oldstation but with a screwriver
/:cl:

[why]: # i honestrly think they forgot to add one when they made the map, and its kinda needed to make new machinary. only other way to make them is spawning a drone and ask it to kindly give you the screwdriver and thats terrible

### CODE REVIEW

**Comment by Pyko1** [comment]
if its an tg oversight should prolly make this PR on TG

**Comment by Blute1** [comment]
>helping tg

😕 😂

**Comment by ghost** [comment]
There are two options for this PR

1) Upstream this
2) Create a new ruin specifically made for Hippie and include that in the `dme`

**Comment by xTrainx** [comment]
took option 2

**Comment by xTrainx** [comment]
ok

**Comment by xTrainx** [comment]
@Pyko1 is it ok now?

**Comment by ghost** [comment]
sweet +1

**Comment by ghost** [comment]
I'd prefer if you'd do this upstream really, i don't see why we should maintain a completely extra map for just one screwdriver

**Comment by praisenarsie** [comment]
why didn't i close this years ago

**Pull request closed without merging**
