### PR TITLE
[MIRROR] The wiki button now asks what page you want to be taken to

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/29813
--------------------
ported from paradise

:cl: More Robust Than You
tweak: The wiki button now asks what page you want to be taken to
/:cl:

### CODE REVIEW

**Comment by tortellinitony** [comment]
not gonna work with our wiki

**Comment by GuyonBroadway** [comment]
We might as well redirect to the tgstation wiki these days anyway

**Comment by PopNotes** [comment]
maybe we should mirror the /tg/ wiki

**Comment by ghost** [comment]
https://wiki.hippiestation.com/index.php?search=stuff

that works for me?

**Pull request closed without merging**
