### PR TITLE
Old Hippie Port: Saying "rouge" now gives you brain damage (and a random trauma)

### PR DESCRIPTION
**Pull request by Jujumatic**
We used to have this thing which gave you brain damage if you said rouge, not sure why it got taken out. Now it gives a trauma too, cause you're a fucking idiot

## Changelog
:cl:
add: "Rouge" is not a proper word. Just try saying it. I dare you.
/:cl:

### CODE REVIEW

**Comment by earthmoonjune** [comment]
+1

**Comment by RafRoq** [comment]
why would anyone say rougue

**Comment by ghost** [comment]
The Khmer Rouge?

**Comment by Jujumatic** [comment]
a lot of people say rouge

**Comment by yoyobatty** [comment]
Should look for prefixes otherwise dumb players who mean to say red in French will get a random trauma only curable by surgery which is pretty annoying.

I'd also like to point out that magic traumas aren't curable and special shouldn't be included in this either.

**Comment by Jujumatic** [comment]
Who the fuck is going to just randomly say red in French 

Magic traumas are extremely rare to get in the first place, and special even more so with this phrase. Might as well put it in for lols

**Comment by yoyobatty** [comment]
People abused it by getting others to ask what the colour red was in French, which although funny, shouldn't justify punishing. Add a prefix detector for stuff like 's and is, randomly refering a word out of context doesn't warrant gaining incurable traumas.

**Comment by Jujumatic** [comment]
that was the whole gimmick of making rouge give you brain damage though

**Comment by Carbonhell** [comment]
I do not remember if people actually liked this or not. I do not think they liked it.

**Comment by mikolaj007** [comment]
I dont think its funny.
Put it when people dab or smth

**Comment by TheMeatGod** [comment]
Make it so saying “bet” gibs you instantaneously

**Comment by Jujumatic** [comment]
> Make it so saying “bet” gibs you instantaneously

maybe not gib but possibly throw you across an entire room

**Comment by TheMeatGod** [comment]
Nah now it should just permaban you

**Comment by Jujumatic** [comment]
Makes 8 colossus' spawn all around you, exactly 1 tile away from you to shoot you with 64 death bolts instantly

**Comment by TheMeatGod** [comment]
Puts a hit out on you irl, you now have 2 days to live
Also catbans you for a few hours

**Comment by Jujumatic** [comment]
Makes you do an irl blj to warp out of existence

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by k-k-karma** [comment]
image
https://discordapp.com/channels/276455180852264960/276456582500319244/552154332972187660

**Pull request merged**
