### PR TITLE
[DO NOT MERGE] Guyon are you okay

### PR DESCRIPTION
**Pull request by ghost**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: ninjanomnom, actioninja
add: Adds smooth movement, which should make movement more smooth.
/:cl:

## About The Pull Request

This PR implements 'smooth movement'. It should ideally make combat more consistent.

I'd like to point out this still needs heavy testing.

## Why It's Good For The Game

I don't know.

### CODE REVIEW

**Comment by ghost** [comment]
based, was looking at this

**Comment by karmaisblackandbluepilled** [comment]
what exactly is this

**Comment by ghost** [comment]
@karmaisblackandbluepilled checkout this branch on your hippiestation repo and try it out. Works best with 513.

**Comment by diegoxt45** [comment]
what this do mane

**Comment by DON-KARMA** [comment]
sounds stupid

**Comment by GuyonBroadway** [comment]
Sir you got your title wrong.

It's "Annie, are you OK?"

-1, critical PR labelling failure, maintainers please close.

**Comment by Manly-Dwarf** [comment]
YOU'VE BEEN STRUCK BY, A SMOOTH
A SMOOTH CRIMINAL

fuck you guyon i thought of it first

**Comment by Manly-Dwarf** [comment]
also no I do not like this, as it removes the 0fps setting

**Comment by ghost** [comment]
@Manly-Dwarf 0fps defaulted to 20, this makes it default to 60.

**Comment by karmaisblackandbluepilled** [comment]
+1 i guess lol

**Comment by Manly-Dwarf** [comment]
0fps where the game has none of that smoothing is the best though

**Comment by ghost** [comment]
@Manly-Dwarf can always set it to 20 manually

**Comment by Manly-Dwarf** [comment]
that's a sin!

**Comment by yoyobatty** [comment]
Make sure this has the latest commits and stuff

**Comment by Toxici11i** [comment]
> also no I do not like this, as it removes the 0fps setting

retard 0fps makes it server FPS, which is by default 20

**Comment by KingTerrytheTerrible** [comment]
this casues motion sickness

**Comment by mkikt4743** [comment]
wtf is 0fps...

edited: Removed the slur, keep comments appropriate please. - AJN

**Comment by Toxici11i** [comment]
> wtf is 0fps...

0FPS sets your game client FPS to the FPS the server is running at (default 20).

edited: quoted a previous comment that was not quite appropriate. - AJN

**Comment by AnthonyJNgo** [comment]
We need some video of this in action, and more details.

**Comment by mkikt4743** [comment]
@AnthonyJNgo my friend this is hippie station we say what we want, don't remove slurs

**Comment by SireTurret** [comment]
> @AnthonyJNgo my nigga this is hippie station we say what we want, don't remove slurs

idiot github can block you and us

**Comment by mkikt4743** [comment]
ah I see

**Comment by AnthonyJNgo** [comment]
We need an update on this.

**Comment by yoyobatty** [comment]
Closing since no updates and it's not known to be updated with tg's stuff.

**Pull request closed without merging**
