### PR TITLE
[MIRROR] Chemisty recipe macros

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34149
--------------------
Ripped from @ Iamgoofball's PR

:cl: More Robust Than You
add: You can now save chemistry recipe macros
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
This is goofball code as copied by amari. DNM till a maintainer has a chance to test it works.

**Comment by praisenarsie** [comment]
if it got past tg then it should be fine

**Comment by GuyonBroadway** [comment]
Thats no fukken garuntee these days.

**Comment by praisenarsie** [comment]
dnm, bug upstream, will merge if a fix is made

**Comment by KayeArray** [comment]
i am utterly shocked

**Comment by praisenarsie** [comment]
here's the bug if you were wondering: https://github.com/tgstation/tgstation/issues/34188

**Comment by Carbonhell** [comment]
Jesus christ
Can we remove this the moment it gets merged
Tia

**Comment by JohnGinnane** [comment]
image

**Comment by JohnGinnane** [comment]
For real though cool feature

**Comment by ghost** [comment]
the actual benefit that current powergamers get isn't huge but it lowers the barrier of entry of powergaming
i dunno if that's actually a more organic way to handle powergaming since it solves a problem by making the playing field more level or if it just encourages a few more people to be fun sucking in their chem abuse

**Comment by tortellinitony** [comment]
Honestly, since they aren't saved on world reset I don't think this is that bad

**Comment by RobustAndrun** [comment]
Skewium for dayssss

**Comment by praisenarsie** [comment]
fuck this, i've played with this upstream and it works. i bet the issues upstream aren't real because they probably spelt the chemid wrong or some shit.

will merge unless a maintainer disagrees for some (stupid) reason

**Review by praisenarsie — APPROVED** [review]

**Pull request merged**
