### PR TITLE
Manual upstream PR for techwebs

### PR DESCRIPTION
**Pull request by ghost**
- [x] Update the map
- [x] Ensure the code compiles
- [x] Ensure some of the hippie boards, and changes are available in the new RD thing

### CODE REVIEW

**Comment by ghost** [comment]
@Chnkr did you really just open a PR that did the same mine does, except mine compiles?

**Comment by ghost** [comment]
and then proceed to close mine?

**Comment by ghost** [comment]
>thinking because someone fucks up one time, they're completely incapable of ever doing it right again

**Review by KayeArray — APPROVED** [review]
he tested it

**Comment by xTrainx** [comment]
this was a mistake

**Pull request merged**
