### PR TITLE
Readds the circuit lab

### PR DESCRIPTION
**Pull request by ghost**
Finally that room contains useful stuff now

capture

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Put the experimentor board, and parts in a crate somewhere please.

**Review by ghost — APPROVED** [review]
Looks good

**Comment by Blute1** [comment]
was the circuit update even added?

**Comment by ghost** [comment]
yes

**Comment by KayeArray** [comment]
yeah alright

**Comment by Pyko1** [comment]
personal toolvendor for science?
OP, think of the yellow gloves!

**Comment by Pyko1** [comment]
eww, even round start autolathe, even not like science already had practically access to every job gear anyways.

**Comment by KayeArray** [comment]
lol how'd I not notice that, retracting my support until it is gone

**Comment by Pyko1** [comment]
a box of donkpockets and a microwave too, so i guess no need to go to chef, like ever?

A donut box might had been appropriate, but a personal snack  vender, 2 pizzas and a box of donkpocket and a microwave is going to keep whole science fed.

I see no reason for science to be a round start autismfort with rwalls and shutters and everything to last for a round,

**Comment by Pyko1** [comment]
nope, 2 boxes of donkpockets, why?

That 1 room has literally more room in it then rest of the departments have together at round start.

**Pull request closed without merging**
