### PR TITLE
Fix some flag BS

### PR DESCRIPTION
**Pull request by ghost**
:cl:
fix: You should now hopefully display the correct flag in OOC
fix: Added China and Poland to the OOC flag sprites
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
hahahahahahah

**Comment by yoyobatty** [comment]
Woweee @steamp0rt , I asked if you tested it. But here we are again, for the 100th time, steamport fixes it AFTER it's been merged and tested.

**Comment by ghost** [comment]
I did test it. I did not, however, have time to test it on every possible country

**Comment by yoyobatty** [comment]
I'm busting your balls. Are you for SURE it works?

**Comment by ghost** [comment]
I changed my client.country to Taiwan to test this. Yes.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
