### PR TITLE
Chapel Magic Item Storage

### PR DESCRIPTION
**Pull request by carlopault**
image

## Changelog
:cl: Carlospaul
Added: Chapel Magic Item Storage
/:cl:

On MetaLake, the Chapel has this small room in the chaplain's office that contains a smoke book and soul shard, along with the flash of holy water and nullrod. I based this PR off of that small room. 

## Why It's Good For The Game
The chaplain is the magic user of the station. A chaplain should have access to various magical items instead of just his silly null rod and holy book. 

Items in the room: 
- Null rod
- Flask of holy water
- **Purified soul shard** (REPLACED)
- Lesser smoke spell book
- **Haunted magic eight ball** (REMOVED)
- Ratvar's Boots of Deceleration (they make you walk slow)
- _mysterious old shard_ (ADDED)

### CODE REVIEW

**Comment by Neotwr** [comment]
chaplain cant use smoke...

**Comment by carlopault** [comment]
> chaplain cant use smoke...

say sike right now

**Comment by Neo-0** [comment]
uhhhhh 
image

**Comment by Fikou** [comment]
hmm today i will give chaplain a free antag item that's used for ghost communication and an antag checker when he already has one of the most robust weapons on station and can counter wizards and cultists

**Comment by MrEpicSax** [comment]
+1 for raw uncensored chad chaplain dominance

-1 for poor balance and incentivizing chaplain even further as a go to power-gaming freak.

**Comment by karmaisblackandbluepilled** [comment]
>Medbay Defib. Wall Mount
bruh?

**Comment by yoyobatty** [comment]
Good job, placing a wall right next to glass

**Comment by carlopault** [comment]
I fixed all the bad shiet. I rebalanced the items in the room and removed that garbage glass.

**Comment by AnthonyJNgo** [comment]
Just to clarify, what items will this give Chaplain again?

**Comment by carlopault** [comment]
> Just to clarify, what items will this give Chaplain again?

This will give the chaplain: Ratvar's Boots of Deceleration, lesser smoke spell book, and the mysterious old shard (1 use soulshard, at least I think it is 1 use. Last time I used it was way back when I played on TG), along with his null rod and holy water flask.

**Comment by yoyobatty** [comment]
Update screenshot

**Comment by carlopault** [comment]
Going to close and reopen this PR because I am 99% sure the map is broken. 
image

**Pull request closed without merging**
