### PR TITLE
Adds special attacks

### PR DESCRIPTION
**Pull request by KayeArray**
:cl: banthebantz
add: Added special attacks to certain weapons, experiment and find them
add: Special attacks are executed by toggling the special action and attacking normally
add: Special attacks typically cost stamina
/:cl:

[why]: Fixed the issues caused by tony's file reorganisation and added a sound effect
former pr: https://github.com/HippieStation/HippieStation/pull/3621

### CODE REVIEW

**Review by j-mie — APPROVED** [review]

**Comment by KayeArray** [comment]
dew it

**Comment by PopNotes** [comment]
I do have one last request for these if possible

**Comment by PopNotes** [comment]
any chance we could see a dedicated hotkey for specials?

**Comment by KayeArray** [comment]
I don't think actions have hotkey support

**Comment by j-mie** [comment]
+1 from Me, Bard and TFW.

Merging

**Pull request merged**
