### PR TITLE
NO MORE LEAN PILES

### PR DESCRIPTION
**Pull request by ghost**
NOT ALL HEROES WEAR CAPES

:cl: Thefastfoodguy
fix: Lean can no longer turn into chempiles
add: In unrelated news, NanoTrasen reports that there have been a 75% drop in black people population!
/:cl:

### CODE REVIEW

**Comment by Arzion5** [comment]
Misleading changelog, better changelog would be "Lean can no longer turn into chempiles", otherwise people would assume that lean chempiles still do exist but they can no longer turn you black, which can further lead people into thinking that it retains the druggy effects, the song and the like.

**Comment by bardofrage** [comment]
+1

**Comment by KayeArray** [comment]
-1 Misuse of the blacklist. Lean is neither OP nor potentially crash inducing.

**Comment by ghost** [comment]
@banthebantz Yes but it's incredibly ear-rapey, annoying, and 99% of players hate it

**Comment by KayeArray** [comment]
Then address these issues by fixing Lean itself rather than reducing it's potential for delivery.
Cap it's drugginess effect and add a delay before it turns you black.

**Comment by ghost** [comment]
@banthebantz yes, but not even chugging charcoal can stop stepping through 2 dozen piles of lean to get to medbay

**Comment by dreamcrab** [comment]
-5 im with banthebantz

we should fix lean itself not something else

**Comment by KayeArray** [comment]
That's not an excuse for not fixing Lean. The amount of drugginess it gives is broken and the fact it turns you black and starts playing music on the first tick is also stupid. I'd rather see the drug fixed rather than hidden away

**Comment by ghost** [comment]
can we just make it so chempiles apply chems via TOUCH rather than INGEST?
then just make it so lean is INGEST dependent

i think chempiles are a bit iffy atm but I think this is a more elegant solution rather than blacklisting it

**Comment by Pyko1** [comment]
Jsut make shoes 100% protect from direct ingest of chems.
And then have acid/fire based piles have a mechanics of breaking shoes.

**Comment by Pyko1** [comment]
And different shoes have different protection against fire/acid.

**Comment by KayeArray** [comment]
I was thinking of an absorbance var myself that determines whether a chemical can absorb through touch or not.

And then changing the reaction to a TOUCH with the amount based on shoes.

Of course transfer rate would have to be buffed a little because 1u of touch does absolutely jack shit even with facid and dizinc.

**Pull request closed without merging**
