### PR TITLE
Readds Liberation Stations to CentCom

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Readded Liberation Stations to CentCom
/:cl:

@wheezl

### CODE REVIEW

**Comment by wheezl** [comment]
+1 USA

**Comment by MrEpicSax** [comment]
+1 Another based pr

**Comment by carlopault** [comment]
where will they be at specifically?

**Comment by ghost** [comment]
> where will they be at specifically? 

look at mapdiffbot

**Comment by carlopault** [comment]
+2 looks good to me

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
