### PR TITLE
Add a config option for replay subsystem.

### PR DESCRIPTION
**Pull request by ghost**
shuts karma up. also he's right, this has legit concerns for cpu/ram usage.

add `ENABLE_DEMO` to hippiestation config on the server

### CODE REVIEW

**Comment by KingTerrytheTerrible** [comment]
I SAID REDUCE THE INIT TIME IT CAN LITERALLY HOLD THE SHITTY SERVER UP RIGHT NOW

**Comment by karmaisblackandbluepilled** [comment]
-1 dumb and retarded

**Comment by KingTerrytheTerrible** [comment]
move some shit OUT OF INIT WHEN ITS NOT REQUIRED TO BE IN INIT

**Comment by ghost** [comment]
@KingTerrytheTerrible if it's disabled, it won't init at all. It'll return before initting.

**Review by yoyobatty — APPROVED** [review]

**Comment by KingTerrytheTerrible** [comment]
> 
> 
> I SAID REDUCE THE INIT TIME IT CAN LITERALLY HOLD THE SHITTY SERVER UP RIGHT NOW
>>IT CAN LITERALLY HOLD THE SHITTY SERVER UP RIGHT NOW

**Pull request merged**
