### PR TITLE
Vamps, shadowlings, etc are now immune to Fluxitis

### PR DESCRIPTION
**Pull request by ghost**
OOF

### CODE REVIEW

**Comment by Swagile** [comment]
ICK OCK !!!!

**Comment by Spankmaster1066** [comment]
kidna cool

**Comment by KayeArray** [comment]
# Omae wa, mou shindeiru.

**Comment by KayeArray** [comment]
also dumb snowflake solution for an overpowered admin virus

**Comment by Swagile** [comment]
wtf why delete my comments you nigger jew faggot

**Pull request closed without merging**
