### PR TITLE
[MIRROR] [READY]New Side Antagonist: Space Dragon

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42551
----------------------------
## Changelog
:cl:
add: Space Dragon Mob
add: Space Dragon Antagonist Event
/:cl:
## About The Pull Request
This pull adds a space dragon mob (subsidiary of the Ash Drake) and a corresponding antagonist and event for it to spawn in.  The space dragon appears as a purple variation of the Ash Drake, but has a number of notable differences:
- Has 250 health
- Does 35 damage, between the lesser ash drake's 30 and the ash drake's 40
- Moves as fast as a space carp
- Does not shoot fire in a cone, but instead solely in a straight line (this fire goes a tad further than the ash drake's)
- No collision damage (moving into various objects won't damage them)
- No swooping attack, but instead has a tail sweep attack.  Alt-clicking will use it, and will knock all upright mobs down around the space dragon in a one-block radius.  The space dragon also spins around when it uses it as a visual indicator.  It also has a cooldown like the swoop, but it is slightly shorter (200 to 150)
- Shares the resistances of the Ash Drake and other megafauna, so it is resistant to lasers by 50%.

The mob spawns where carp are allowed to spawn, and is instructed on it's controls.  It's explained that it has been informed of whom the leader of these invaders into the space dragon's claim are, and the dragon is tasked with killing that person.   The person selected will always be one of the Heads of Staff, and if for some reason there are no heads of staffs available for choosing, a random crewmember will be chosen instead. When they spawn, a unique announcement also plays, alerting the crew that the dragon has spawned.

## Why It's Good For The Game
I firmly believe more variety in antags is always a good thing when it comes to this game, and people enjoy playing as an ash drake and fighting them, so having a variation of it as an antag should be add an enjoyable experience.  While it has potential to wreck parts of the station, a well-coordinated crew should be able to limit it's mobility due to it's low health pool, forcing it to play conservatively when the crew pressures it.

On another note, I'm completely open to any suggestions or corrections to this, as this is my first project working with SS13, with hopefully more to follow.

### CODE REVIEW

**Comment by ghost** [comment]
Thank you tg, very cool

**Comment by Manly-Dwarf** [comment]
TODD

**Comment by DaydreamPuppeh** [comment]
This is a ridley reference I think

**Comment by GuyonBroadway** [comment]
It's a reference to a lot of things including he-man and pokemon.

**Review by ghost — APPROVED** [review]
The changes worked, nice

**Pull request merged**
