### PR TITLE
Build-a-stand stuff

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Added 3 new stand types
add: Predator, which can track down anyone, with just a blood drop or fingerprint.
add: THE HAND, which can turn a shoot-out into a punch-out.
add: Frenzy, which can make any situation look like a Florida Man headline
add: Range F stands are now anchored to their owner.
admin: Admins can now ban people from becoming holoparasite.
/:cl:

### CODE REVIEW

**Comment by ExpAntique** [comment]
+1 ok

**Comment by SireTurret** [comment]
+1

**Comment by SireTurret** [comment]
oh wait

**Comment by ghost** [comment]
gifs of the new stuff, minus Predator, in action:
Hydm4SqNYA
7gvTPsUMFF
1KlD9rtTYX

**Comment by ghost** [comment]
sadly I can't embed MP4s or WebMs in github, so you can't hear the cool sounds

**Comment by cris5311** [comment]
+1

not too much of a fan of all the jojo stuff but eh its better having it than not

**Comment by ghost** [comment]
Finally... admins can now ban people from becoming holoparasite.

**Review by yoyobatty — APPROVED** [review]
Works right?

**Comment by ghost** [comment]
yep

**Comment by Manly-Dwarf** [comment]
This has enough designer +1s, I'll be chiming in one too.
Merging.

**Pull request merged**
