### PR TITLE
Give more information about zombie infected patients

### PR DESCRIPTION
**Pull request by ghost**
#10862

:cl: Mideanon and zamolxius
add: Give more information about zombie infected patients when using a health analyzer
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
image
extra space behind "Head surgery" is fixed

**Comment by Majick1** [comment]
You should already be able to see romerol with the reagent scanner, this seems more handholdy than it needs to be

**Comment by ghost** [comment]
you dont see infection though afaik

**Comment by Majick1** [comment]
It shouldn't need to though, seeing they have a tumor then switching mode on the scanner is already simple enough

**Comment by AnthonyJNgo** [comment]
+1 also closes #10862

**Comment by mikolaj007** [comment]
+1

**Comment by mkikt4743** [comment]
+1

**Comment by Toxici11i** [comment]
+1, current symptoms of romerol can literally be caused by half of the current chems in existence

**Comment by ghost** [comment]
+1, it's nice to know

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
travis said the build failed, what in the goddamn

**Pull request merged**
