### PR TITLE
[MIRROR] Fixes some things not using log_world

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/27073
--------------------

### CODE REVIEW

**Comment by ghost** [comment]
@JamieH the fuck is this

**Comment by GuyonBroadway** [comment]
Could it be that we already made these changes?

**Comment by ghost** [comment]
>tgstatio

Is the bot bugged?

**Comment by KayeArray** [comment]
drunk code

**Comment by GuyonBroadway** [comment]
Looking over the original PR and the mirror that citadels bot(which is a copy of our bot) made it seems that we are the only ones with a problem.

**Pull request closed without merging**
