### PR TITLE
Added new sounds to the jabroni outfit

### PR DESCRIPTION
**Pull request by Jujumatic**
Yeah just added 5 new screams to the jabroni outfit cause somebody wanted me to do it lol

:cl:
add: Added new screams to the jabroni outfit.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
love this.  can you make a short video showing the sounds or smth?

**Comment by Jujumatic** [comment]
if you go check out the files changed, you can view raw on the sound files and if you save them in your computer, you can play them from there

**Comment by Jujumatic** [comment]
fuck - i think the upstream broke ALL alternate sounds. not even ushankas are working

**Comment by ghost** [comment]
@JohnGinnane alternate screams allegedly broken?

**Comment by Carbonhell** [comment]
sure +1

**Comment by biggeOS** [comment]
+1 gachiBASS Clap

**Comment by ghost** [comment]
+1

**Comment by JohnGinnane** [comment]
Will look at sounds this weekend

**Comment by Pyko1** [comment]
sure +1

**Comment by Jujumatic** [comment]
@HippieStation/maintainers need a review and pls merge whenever possible

**Review by GuyonBroadway — APPROVED** [review]
Code is good

**Comment by GuyonBroadway** [comment]
has +1's, merglederging

**Pull request merged**
