### PR TITLE
[Work In Progress] Surplus Only Items + Syndicate Party Crate

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Changelogs]:
:cl: KawaiiBigBoss
add: Added the Syndicate Party crate, which is functionally similar to the surplus crate. It sets aside a random amount of TC for Surplus Only items and then spawns the items it can afford at random, alongside the regular traitor items.
add: Added a myriad of Surplus Only traitor items. These only spawn inside of Surplus Crates and Party Crates.
del: Commented out some code in the /tg/ uplink_item file. If there are any bugs, you know where to look.
add: Added the Monkeyman's Wristbands, a Surplus Only item that combines the wrath of the Sleeping Carp scroll and the Gloves of the North Star - then doubles it! An item for the DB nerds in the discord.
add: Added the Donksoft C20-r to the Surplus Only items. Comes with an ammo box!
add: Adds the Grudgecoder, a Surplus Only item functionally similar to the Execution Sword - except much more humiliating to the victim. Also works pretty well as an actual weapon.
add: Adds the ROCKET PUNCH, a Surplus Only item which is about as dumb as it sounds. Quite powerful if you knock someone into a wall!
add: Adds Lightning in a Box. It's a bunch of birdseed in a box.
/:cl:

[why]: The Surplus Crate is a lot of fun, but it feels like it's lost a lot of its flair with the introduction of so many traitor items that it's more fun to experiment with what you can purchase rather than what you can get in a crate. More people generally just go for the emag rather than the surplus crate because the emag gives them all the fun they could want without having to worry about random-ness.
This is a "fix". There will be more items to come in the future which I have planned out, but for now I'll just add the 5 items I've already coded alongside the main functionality.
**None of these items can be purchased from the uplink. They are ONLY available in Surplus Crates or Party Crates.** This is both a way to (artificially) spice up the items that can appear in the crate while also making the crate more enticing, as you can get a bunch of ridiculous combos or otherwise stupid items from the crate that are intended to be as fun as possible _rather than just efficient_, unlike a lot of the items currently in the uplink.

For those who want to add items to the Surplus Only list, simply put your item in the party category. The crates will do the rest.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Yes, this was tested and works. No crashes.

A huge thanks to JohnFG, McBawbaggings, Guyonbroadway, TDCoolguy (Gregg) and CarbonHell for helping me make this a reality. This code was a nightmare.

**Comment by ghost** [comment]
This code is a pretty big nightmare to look at, not sure why all these procs are mirrored

**Comment by ghost** [comment]
I'd suggest, that instead of mirroring `initialize_global_uplink_items` you just create a new item, let's call it `party spawner` that just creates the crate on the spot, instead of having to do all of the things you did just now

**Comment by Manly-Dwarf** [comment]
Procs are mirrored because whenever I tried to add to the global uplink items list, it would tell me that I couldn't do that and fail to compile.
There's no modular way to do this, unfortunately.
Remember, the Surplus Crate spawns these items too - not just the party crate.

**Comment by ghost** [comment]
There is no need to modify the global uplink items list at all

1. Create a new item that will spawn the crate
2. Add a new set of items e.g. `/obj/item/party/dildo`
3. Make the crate look for subtypes of `/obj/item/party` and spawn `x` of them

**Comment by ghost** [comment]
Also you can remove items from the global list after the global list has been created, which is something I'd prefer rather than mirroring the file

**Comment by JohnGinnane** [comment]
@Kawaii-Big-Boss lets do the fix like what erik said

**Comment by Manly-Dwarf** [comment]
@JohnGinnane who erik?
is chnkr erik?

**Comment by praisenarsie** [comment]
erak eequalz chunkr

**Comment by Manly-Dwarf** [comment]
I'll be out of town for a little while, so I'll work on this again when I come back.

**Comment by Manly-Dwarf** [comment]
@praisenarsie Put "Do Not Merge" on this, please.

**Comment by Manly-Dwarf** [comment]
Dis be dead yo

**Comment by JohnGinnane** [comment]
why

**Pull request closed without merging**
