### PR TITLE
Fixes changelogs, holy shit, that was easy!!

### PR DESCRIPTION
**Pull request by yoyobatty**
You're all fired @HippieStation/maintainers

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
You're all fired @HippieStation/maintainers

**Comment by ghost** [comment]
I'm at work nig nog

Also, I'll wait for Travis first

**Review by ghost — APPROVED** [review]
Yeah nah not reading all of that

**Comment by ghost** [comment]
You committed to master, didn't you

**Pull request merged**
