### PR TITLE
Department Cards

### LINKED ISSUE #9894: Heads of Staff don't get their departmental card
Heads of staff don't get departmental card spawned in their backpack / wherever they are supposed to spawn.

This cuts off any way to access their department budget.
QM start with the cargo one in their inventory.

Possible related thing, heads start with a tablet computer in their inventory which may somehow block the card from spawning in there.

### PR DESCRIPTION
**Pull request by AliiTea**
:cl: Nexendia
fix: Heads of Staff now spawn with their departmental budget cards.
/:cl:

No idea why it wasn't there to begin with when the files were created. _*shrug*_

But this fixes it... I _think?_

Closes #9894 

[Issue related to PR here](https://github.com/HippieStation/HippieStation/issues/9894)

### CODE REVIEW

**Comment by k-k-karma** [comment]
nice catch

**Comment by AliiTea** [comment]
Tested locally and code compiled, spawned in as Captain then HoS and they both had the cards inside backpacks and they functioned I assume perfectly.

**Comment by ghost** [comment]
dude this is really well done didnt expect  this

**Comment by AliiTea** [comment]
Lmao I forget how to read the Travis build but how tf did it fail :joy:

**Comment by AliiTea** [comment]
_Dont Merge_ have to redo as it isn't modularized.

**Comment by k-k-karma** [comment]
this is modularized you fuck

**Comment by AliiTea** [comment]
Ya sure?

**Comment by AliiTea** [comment]
Isn't it supposed to be in Hippiestation/Hippiestation/code not Hippiestation/code

**Comment by k-k-karma** [comment]
it is

**Comment by AliiTea** [comment]
Then it isn't currently modularized and I need to redo it when I get home

**Comment by AliiTea** [comment]
Am dumb

**Comment by AliiTea** [comment]
awesome

**Comment by BlueNothing** [comment]
Should these spawn in the corresponding lockers, or on the heads?

**Comment by AliiTea** [comment]
I can always go back and make it spawn in the lockers but for now at least they are in.

**Pull request merged**
