### PR TITLE
[MIRROR] Makes some get_step(..., 0)s use get_turf(...)

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34120
--------------------
preprocessor magic #32733

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
I was gonna say how this mirror is boitched but we allready had some of the changes the upstream PR made, what the actual fuck?

**Comment by praisenarsie** [comment]
guyon are you ok, the mirror doesn't look botched to me

**Comment by GuyonBroadway** [comment]
check the files changed in this PR and the files changed in the original pr.

**Comment by JohnGinnane** [comment]
bruh they're the same

**Comment by GuyonBroadway** [comment]
BITCH 2: SON OF BITCH I CLICKED THE WRONG LINK.

**Review by GuyonBroadway — APPROVED** [review]

**Comment by praisenarsie** [comment]
butthurt coder gets awesomely trolled by github epic style HD 1080p

**Pull request merged**
