### PR TITLE
Nerf anti stuns

### PR DESCRIPTION
**Pull request by GuyonBroadway**
Port of https://github.com/HippieStation/HippieStation13/pull/475

### CODE REVIEW

**Comment by tortellinitony** [comment]
You've done this very poorly.

**Comment by GuyonBroadway** [comment]
Its a mostly direct port of something I made on live. Bar a few changes based on how the codebase has changed with regards to to_chat(). If you can spot any fixes, do let me know.

**Comment by ghost** [comment]
Just remove it

**Comment by tortellinitony** [comment]
As you can see there are already conflicts. This is what I mean by you've done this poorly. Instead of editing files, change them by making one in the hippiestation folder and changing the hippiestation.dme. Instead of deleting files, just remove them from the hippiestation.dme. I think it is necessary we do this with all of the chemistry files anyway.

**Comment by GuyonBroadway** [comment]
Working on this new branch is a little confusing and it's be nice if there was a checklist or a guide on what to do as I'm not %100 sure how you want to move forward with it. I'll make the changes next chance I get.

**Comment by j-mie** [comment]
@GuyonBroadway https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md

**Comment by GuyonBroadway** [comment]
closing and deleting branch, started again and did it right.

**Pull request closed without merging**
