### PR TITLE
Being chaplain is now a viable strat against wizards

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: The chaplain is now anti-magic.
/:cl:

Why: There's not many ways to counter a murderboning wizard. So here's one.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
No. You know exactly why.

**Comment by ghost** [comment]
actually i don't

**Comment by Manly-Dwarf** [comment]
The Chaplain isn't the only person who can use the null rod. Ask yourself why this is a problem.
I'd rather just the chaplain himself, as he is a holy man, be immune to magic.

**Comment by ghost** [comment]
Good point.

**Comment by ghost** [comment]
@Manly-Dwarf changed

**Comment by Manly-Dwarf** [comment]
okay +1

**Comment by mikolaj007** [comment]
-1, if wiz is rampaging and theres no chaplain, you're kinda fucked
Make em both anti-magic or keep the null rod

**Comment by yobob591** [comment]
+1, maybe chaplains will do something other than silently be killed/not even exist every round

**Comment by Manly-Dwarf** [comment]
@mikolaj007 Wizard is meant to be an incredibly powerful antagonist who can take on pretty much anyone in a one-versus-one situation and come out without a scratch. In order to catch the wizard, you need to jump him at a bad time and stun him, steal his staff, or grab a buddy and dump buckshot into him.
The only real issue I have with the gamemode right now are some spells being useless (Eruption) and fireball being way too useful.

If you give the null rod anti-magic, you essentially give whatever powergaming RTA-using captain on the station complete immunity to the Wizard's spells, which is his only advantage against the crew. No.

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by WarRage333** [comment]
Just hold the null rod nigga

**Comment by ghost** [comment]
anyone can hold the null rod... plus nullrod is holy, not antimagic

**Comment by k-k-karma** [comment]
null rod is already antimagic

**Comment by ghost** [comment]
@k-k-karma Show me in the code.

**Comment by ghost** [comment]
no mention of TRAIT_ANTIMAGIC in either of these:

https://github.com/HippieStation/HippieStation/blob/master/code/game/objects/items/holy_weapons.dm
https://github.com/HippieStation/HippieStation/blob/master/hippiestation/code/game/objects/items/holy_weapons.dm

**Comment by k-k-karma** [comment]
image

**Comment by ghost** [comment]
Oh

**Pull request closed without merging**
