### PR TITLE
Bullets now cause blood splatter

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Guns now cause blood splattering
tweak: Blood splatter should behave a bit better
/:cl:

## About The Pull Request
Title and video below.

## Why It's Good For The Game
https://i.imgur.com/XhrEqvw.gifv

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
oh god i'm fucking cooming aaarahrharhghghhg +1

**Review by ghost — DISMISSED** [review]

**Comment by ghost** [comment]
YEET

**Comment by ghost** [comment]
+1 I'll see if I can make further improvements once it's in.

**Comment by carlopault** [comment]
blood + 1

**Comment by yoyobatty** [comment]
Actually don't merge asap, I need to tweak 1 more thing

**Comment by ghost** [comment]
Will it send out multiple blood sprays with buckshot hits? That could cause issues with shit like the bulldog if it does.

**Comment by yoyobatty** [comment]
Yeah and it doesn't have problems for any shotgun or rifle.

**Comment by Toxici11i** [comment]
+1 allah bless you, we can finally see if its suicide or murder

**Review by ghost — APPROVED** [review]

**Pull request merged**
