### PR TITLE
adds emergency EVA suits to lockers around the station

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: adds emergency EVA suits to lockers around the station

:cl: zamolxius
add: Added emergency EVA suits
balance: added emergency EVA suits
/:cl:

[why]: https://forums.hippiestation.com/viewtopic.php?f=14&t=279

c0e44d35e327da31aad855913a1ae205
a60eeb42894cddeab397246f1c69de54
5ac6a3cdc8d32facf30d163a96cc969f
f8a0a6d51dedaad50096e5ef6cd37ca2
193355154f773c1efa6f024f51ca772b
cd45fd1a40d43e8dbb52bf1db1f4968f
9771a188751662204cbdb6c161abf068

### CODE REVIEW

**Comment by JohnGinnane** [comment]
https://www.youtube.com/watch?v=Iph84L4xJL4

**Review by JohnGinnane — APPROVED** [review]
Code looks good to me

**Comment by Jujumatic** [comment]
just my opinion here - could you make it so instead it has random chance of being in a locker? i think the static spawns should be left for the emergency pods and then leaving them unlocked would be better than just making static spawns for emergency spacesuits

**Comment by ghost** [comment]
id also need to modify the spawning rate for other items too, dunno

**Comment by dreamcrab** [comment]
im not entirely opposed to the idea but they need to be in certain spots and there cant be too many of them

eva suits are locked away behind access for a reason

lets talk this one out and maybe we can work something out

**Comment by ghost** [comment]
there are 3 in arrivals, 1 in escape, 4 in maint, 1 in security currently

**Comment by ghost** [comment]
arrivals having highest density

**Comment by ghost** [comment]
nah, https://github.com/HippieStation/HippieStation/pull/7762 makes this obsolete

**Pull request closed without merging**
