### PR TITLE
Reverts perfluorodecalin BUT it no longer mutes

### PR DESCRIPTION
**Pull request by Jujumatic**
fuck oranges aaaaaaaa

brings everything back from perfluoro cause "muh mute toxin" ided is stupid reason to destroy the entire chemical as it was known

update: removed the mute effect from perfluoro but everything else has been brought back

## Changelog
:cl:
balance: Perfluorodecalin is now restored to its former glory! To make up for this however, it no longer mutes
/:cl:

### CODE REVIEW

**Comment by Carbonhell** [comment]
Wasn't this reverted in the mirror pr? We -1ed it

**Comment by Carbonhell** [comment]
https://github.com/HippieStation/HippieStation/pull/10568

?

**Comment by Jujumatic** [comment]
it was not

**Comment by Jujumatic** [comment]
look at the diff in the pr, there's nothing changed

**Comment by Manly-Dwarf** [comment]
Honestly, nah.
The reasons for destroying Perfluoro were totally valid. It was a lame instant nerf, but did anyone really enjoy perf+neuro while it was around? A 5 minute stun coupled with a long mute?
We just need Trekchem back. Port some chems and recipes over to Trekchem, keep the addiction systems and whatsit to stop Hyperzine, and we're golden. No more patches, no more perfluoro, all the tricord.

**Review by ghost — DISMISSED** [review]
code seems good

**Comment by RafRoq** [comment]
Isn't Neuro already nerfed ? Perfluorodecalin at now is useless It need a buff or a revert

**Comment by RafRoq** [comment]
There is no reason to chose perfluorodecalin over sabultamol

**Comment by Carbonhell** [comment]
I'm not confident with this chem, but I remember people complaining about it being too powerful. Abstaining, but more on the -1 side.

**Comment by RafRoq** [comment]
It was "overpowered" because people used the mute aspect as tool to kill, but the state it is now is useless

**Comment by earthmoonjune** [comment]
-1

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by Eagle-Eyess** [comment]
-1 no reason for it to mute in the first place.

**Comment by Jujumatic** [comment]
Ok seeing as this isn't going through what about reverting perfluoro to its former glory *but* it has no mute effect

**Comment by Eagle-Eyess** [comment]
That’s fine

**Comment by Jujumatic** [comment]
Hi guys can you re-vote as I have now removed the mute effect

**Comment by Eagle-Eyess** [comment]
+1

**Comment by Carbonhell** [comment]
Seems more fair. +1?
Also what's "return FINISHONMOBLIFE(M)"?
You sure you don't need to call ..()?

**Comment by Jujumatic** [comment]
calling ..() will call all of tg's shit for perfluoro meaning we'll get double oxygen healing *and* the toxin damage. we just want to call our own processing and that's it

**Comment by Jujumatic** [comment]
FINISHONMOBLIFE just completes the processing tick @Carbonhell

**Comment by Jujumatic** [comment]
could i get a review and another vote on this, currently on 1.5 votes now

**Comment by Manly-Dwarf** [comment]
Still no. Perfluoro muting you was as a trade-off to its amazing oxygen healing. It just so happened that most people started using it as a ghetto mute toxin.

**Comment by cris5311** [comment]
+1, finally perf isnt uselss

**Comment by mikolaj007** [comment]
i never really used it before or after the redesign +0

**Comment by Majick1** [comment]
+1, would have been fine with the mute honestly, maybe we can find a different tradeoff if it gets overused

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
