### PR TITLE
Map edits to AI core, Turbine room, and grav generator

### PR DESCRIPTION
**Pull request by Majick1**
## Changelog
:cl:
map: made AI core more robust
/:cl:

## About The Pull Request

-Added windows with shutters to replace the reinforced walls south of the AI
-Added cameras to turbine room for more coverage
-Rewired the gravity generator room to work with the new wiring system

## Why It's Good For The Game

AI is currently a free kill to anyone who trips into the core, this should make it less trivial to remove it from the round. Also gives AI a way to get the turbine going when there's no engineers.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
post screenshots or -1

**Comment by Majick1** [comment]
Grav gen: https://cdn.discordapp.com/attachments/276456582500319244/593104611188146189/unknown.png

AI core: https://cdn.discordapp.com/attachments/572468589488111617/592490187687329853/unknown.png

**Comment by Manly-Dwarf** [comment]
extra door + shutters is kinda dumb. shutters are super tanky, the one in the AI core in particular is (or used to be) invincible so if those are the same then shoo
this also doesn't fix how easy it is to just fuck the AI's shit. the south side being so exposed and easy to thermite is what makes the AI easy to kill, not the shutters
you could just shut off the APC using a cheap EMP nade and the same job would be accomplished. in fact a bunch of people already do this.

**Comment by Majick1** [comment]
What 99% of people do is just cut down the south walls and just shoot in, since unless you have a heads up you won't be able to hear them until they're cutting the SMES. That or someone can just teleport in front of you and be free from any danger for no cost until their cooldown is up. I can cut the shutters on the side doors but there needs to be an actual effort required to disable the defenses instead of ignoring them, EMP nades are fine since they're supposed to hardcounter silicons

**Review by ghost — CHANGES_REQUESTED** [review]
Just a tip: incase you don't know, the best way to fix map conflicts is to make a copy of your map, `git checkout --theirs map_file`, then copy/paste your map changes from the copy on top of the new one.

**Comment by Majick1** [comment]
Alright, I got rid of those shutters @Manly-Dwarf

**Comment by mikolaj007** [comment]
+1, sounds good

**Review by ghost — DISMISSED** [review]

**Comment by ghost** [comment]
+1

**Comment by lunaman22** [comment]
-1 i hate the ai sat since you can't penetrate it without bombs or reflector vest

**Comment by Majick1** [comment]
Rewired the TEG, smart wiring broke it

**Comment by AnthonyJNgo** [comment]
+1, next time you post screenshots toggle the area so we can see the map. Also a zoomed out picture would be nice also in the future.

**Review by yoyobatty — APPROVED** [review]

**Comment by Majick1** [comment]
don't let this go stale please

**Pull request merged**
