### PR TITLE
Temp fix for fire extinguishers not damaging slimes - if still needed

### PR DESCRIPTION
**Pull request by Jujumatic**
This is to fix slimes not getting damaged correctly by fire extinguishers if it's still needed - but apparently the fire extinguishers are working correctly now. Will test it now that I managed to update my branches, mostly/

### CODE REVIEW

**Comment by JohnGinnane** [comment]
btw i tested this extinguisher on a monkey cube on the server this morning and it was still broke so I'm a lil confused I'll have to look into it further

**Comment by JohnGinnane** [comment]
Tested again on local copy, neither monkey nor slime reacted to extinguisher. Going to test on tg code and see if upstream issue or no

**Comment by JohnGinnane** [comment]
yep, works fine on /tg/ for both issues

**Comment by JohnGinnane** [comment]
So the cause is us removing 10 units of water, and adding in 10 units of cryogenic fluid. It's a little hard to tell but when you use the extinguisher it creates 5 "water effects" and transfers 1 unit of the regeants of each of these effects. So you have 0.8 water and 0.2 cryogenic fluid.

**Comment by JohnGinnane** [comment]
Still working on this. Tried 60 units for extinguisher (50 water, 10 cyro) with a transfer rate of 1.2 into each affect (so 1 water, 0.2 cryo per effect) but no luck

**Comment by JohnGinnane** [comment]
Oh yeah, I did some testing last week. The issue is cryo fluid freezes all the water in the extinguisher and the water changes into a solid so when you use it on items it doesn't call the appropriate proc because it's no longer a liquid

**Comment by Jujumatic** [comment]
perhaps we could fix this by having the proc get called even if the water is classed as a solid? not sure how easy that would be to do though

**Comment by JohnGinnane** [comment]
@Jujumatic gonna close this as narsie has a PR up that technically fixes it but undoes our code

**Pull request closed without merging**
