### PR TITLE
Ports Browser Passthrough from Yogstation

### PR DESCRIPTION
**Pull request by ghost**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: monster860 and HideAndSeekLogic
add: You can now play the game while interacting with browser windows (e.g. Uplinks, Machines). Not input windows, however.
/:cl:

## About The Pull Request
Ports https://github.com/yogstation13/Yogstation/pull/7001

Also unintentionally lints the tgui.js file (shhhh)

We'll need to rebuild tgui.

## Why It's Good For The Game

Speedmerge this, maintainers.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Comment by ghost** [comment]
can this be ported to tgui-next?

**Comment by ghost** [comment]
Most likely, let me look at that in a bit (while). Might be better as a second PR.

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: d8eff4c4d8e878e1d4643a78fc330e18e1e706d6
Pull Request: 93f8802306f76064ba1f45c9b13761bf11adf045
Server: 2a9b40556b2cb0159ae503e34328e63e5505b032

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: abe21323364090ba3d5278d0c4e8a97a0706011b
Pull Request: 93f8802306f76064ba1f45c9b13761bf11adf045
Server: edb72c2e8b0aa882fad1c027c04a2c3dcdcb1bcc

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 4b2fe4b33dbcd40b26ba8d724c67b4e9921109cc
Pull Request: 93f8802306f76064ba1f45c9b13761bf11adf045
Server: 2f15da032cde7c8e7e2c257611c535204d4d3180

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 919b78c0eb7eb04135bd258231707739395a2af4
Pull Request: 93f8802306f76064ba1f45c9b13761bf11adf045
Server: 3f8e575b1f1c9d26b97247c15d24e039e4fef000

**Comment by ghost** [comment]
Yeet

**Comment by yoyobatty** [comment]
So wait, did you recompile tgui? It's in /tgui/build_assets.bat, install dependencies first and make sure you've got python installed

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: a34b5f8a7e52cce30c13d8a43fc201ab66773c64
Pull Request: 93f8802306f76064ba1f45c9b13761bf11adf045
Server: 2c80538037b8f0349ad83db420306efabc2f2831

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: c4600e28bd2f68519125579a7e887868d4d788b4
Pull Request: 93f8802306f76064ba1f45c9b13761bf11adf045
Server: b1f6d18ed6a4539d5f22525b2d179b13fe2194d0

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: a97e86b86723ece1b0053a9210f56ea312eb91c2
Pull Request: 93f8802306f76064ba1f45c9b13761bf11adf045
Server: 7c44eb1331caa639cfa759e7303d74a207f39335

**Comment by ghost** [comment]
@yoyobatty I did this today (sorry for the wait) and tested out the feature.

I ran `install_dependencies.bat` until `build_assets.bat` completed. I assume that's the right way to do it, but if it wasn't I'd like to know how to do it right.

It seems like everything works mostly as intended, although there are several things I'd like to point out:
1. There's a tiny bit of lag when you mouse over a button with a description or click it. I'm not sure if this is client-side or server-side, however.
2. Sometimes, keys get held when you click out of the menu. It seems like if you mouse over enough buttons and spam clicks something undesirable like that happens.
3. You can't hold alt to walk while in a menu without Windows screaming at you

I'm going to try to get this to work for tgui-next, since I love the new tgui-next interfaces.

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: b2fa887f0dad81c8f7df1b3259b89ad11071c242
Pull Request: 93f8802306f76064ba1f45c9b13761bf11adf045
Server: 3309cd90b090a63e5d61efb6087994a595087320

**Comment by ghost** [comment]
I got it to compile for tgui-next. Now, all I have left to do is testing and merge conflict resolution. The latter I'll do right before merging, however.

EDIT: Pinging @steamp0rt because it seems like he'd have a great nut at this

**Comment by ghost** [comment]
did a bit of rudimentary testing, tgui-next works and very wonderfully too.

**Comment by ghost** [comment]
@yoyobatty ping me when you want this merged and I'll fix up the conflicts. No point doing much when tgui-next is updated every three minutes.

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by OmegaShoots** [comment]
This broke being able to use ctrl f to find text in a menu, as it now just inputs the fart command.

**Comment by ghost** [comment]
@OmegaShoots I don't really know what I'd do to fix that

**Comment by ghost** [comment]
@steamp0rt 

please, approve so I can merge.

**Comment by ghost** [comment]
fuck it, I'm merging this.

**Comment by ghost** [comment]
or rather, let's port that other PR

**Pull request closed without merging**
