### PR TITLE
Reverts Energy/Disabler speed.

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: Manly Dwarf
balance: Disabler is now the speed it was before some clown decided to speed it up four times.
/:cl:

[why]: 
The point of speeding up ballistic projectile was to buff them! Don't buff disablers too, you absolute clown!
IDIOTS
Who merged this?!

### CODE REVIEW

**Comment by earthmoonjune** [comment]
thank you for slowing these down you NONFOOL

**Comment by earthmoonjune** [comment]
+1 if its not clear

**Comment by AnthonyJNgo** [comment]
I would +1 for a slight speed nerf. I think before it was too slow to be honest. Stuns should be decent weapons to use so people don't just go straight for lethals every time ((security)).

**Comment by Manly-Dwarf** [comment]
The point was to speed up ballistic lethals so they weren't as crappy in comparison to lasers, disablers, and tasers.
Speeding them ALL up just made Security have the edge again, defeating the point entirely.

**Comment by AnthonyJNgo** [comment]
Fair argument, +1.

**Comment by Manly-Dwarf** [comment]
I wouldn't mind lasers being the same speed/faster than disablers, but NOT the same speed as ballistics.

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by RafRoq** [comment]
i think removing all speed is bad i like the way it is now but if you really want to nerf it keep it at least x2 or x3

**Comment by RafRoq** [comment]
disablers were slow as fuck that it made impossible to chase and shoot someone

**Comment by GuyonBroadway** [comment]
I'd like to rework disablers/tasers to have distictions and what with the limb paralysing thing maybe thats possible... but today is not the day for that.

**Comment by Carbonhell** [comment]
Sure +1

**Comment by Manly-Dwarf** [comment]
merge dis

**Pull request merged**
