### PR TITLE
[MIRROR] The great floor tile purge

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40065
--------------------
Basically:

This turns all of these into floor decals, much like we did with warning lines. This gives us far more flexibility when mapping, letting us make any combination of colors and no longer be restricted by airless tiles having pretty much no colored tile support. This also largely cuts down on the hugely bloated floors.dmi to make it a bit more manageable. 

White colored floor tiles may appear as too bright initially, but I have some planned changes to floor tiles in general in the relatively near future. Besides that, everything should look mostly the same. 

:cl: 
refactor: Refactored floor tiles to use decals like warning lines do.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
oh GAWD

**Comment by Carbonhell** [comment]
hmm i wonder who's gonna fix this

**Comment by yoyobatty** [comment]
Cancer. Considering closing this.

**Comment by ghost** [comment]
???
there's a fucking script "turf2decals"
just load the branch and run the script and map merge??

**Comment by Carbonhell** [comment]
>considering closing this
you can't close something just because it looks hard to fix yoyo what the fuck

**Comment by yoyobatty** [comment]
It's not a script though, it's a .txt file.

**Comment by Carbonhell** [comment]
You just load the txt file in the script that was merged recently and you do not have to do anything else. I guess i'll do it

**Comment by yoyobatty** [comment]
Wait, that's easy then, is it update_paths.py?

**Comment by Carbonhell** [comment]
I am dealing with this but there are some issues,dnm

**Comment by Carbonhell** [comment]
mapdiff bot died but the map's fine so fuck it

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
