### PR TITLE
Fixes arclumins grave.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
I'm not even going to put a changelog on this one, this should have been a thing from the start...

Arc was the man who helped me into ss13 coding, I basically owe all the memes I ever made to him.  He was the craziest bastard and the most magnificent spessmen. 

The sprite is OK but Arclumin was OUR DUDE! Above all else we should not be leavign space for "future dead coders" because we all hope that it never happens again. At least not in our memory, and the memorial to the dead is no place for any kind of message or politics. Its our way of remembering and thanking our dear departed arclumin, the memester who poured his soul into our  shittly little fringe game, and we were better off for it.

Rest in peace buddy, you were one of the best.

### CODE REVIEW

**Comment by KayeArray** [comment]
this is on the map then??

**Comment by GuyonBroadway** [comment]
The "tomb of the unknown employee" _(thank you very fucking much Remie you fucking bitch/bastard/vtol-airshitter)_ is already on centcom, I just renamed it.

**Comment by KayeArray** [comment]
but this is a new object

**Comment by GuyonBroadway** [comment]
its not. https://github.com/HippieStation/HippieStation/blob/27e4596befb785dd2db7f75a7cd2a28f91cd8b68/code/game/objects/structures/memorial.dm

**Comment by KayeArray** [comment]
wtf why did they keep that typepath lol

**Comment by KayeArray** [comment]
fast merging because this is the most important fix

**Review by KayeArray — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
Goof Coded it because he was a buddy of Arc's and Remie and others bitched.

**Pull request merged**
