### PR TITLE
Fixes undeleted queries in GeoIP subsystem

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by yoyobatty — DISMISSED** [review]
I think this will work, just wait until travis is done for good measure.

**Comment by Manly-Dwarf** [comment]
>continuous-integration/appveyor/pr — AppVeyor build failed
continuous-integration/travis-ci/pr — The Travis CI build failed
continuous-integration/travis-ci/push — The Travis CI build failed

**Comment by ghost** [comment]
lmao it failed due to the dynamic fix PR (which didn't even have Travis/Appveyor run on it for some reason)

**Comment by ghost** [comment]
there, problem fixed

**Pull request merged**
