### PR TITLE
Fixes hippiestation and metalake toxins burn chamber

### PR DESCRIPTION
**Pull request by Neotwr**
## Changelog
:cl: Neowt
add: RnD departamental protolathe in MetaLake has been replaced with a protolathe.
fix: Fixed toxins burn chamber in MetaLake and HippieStation.
/:cl:

## About The Pull Request
this PR fixes HippieStation and MetaLake toxins burn chamber, by replacing wall mounted igniter with a floor mounted igniter. I also replaced rnd departamental protolathe in MetaLake with a normal protolathe.

## Why It's Good For The Game
bugs ins't good

### CODE REVIEW

**Comment by SireTurret** [comment]
well hello there brazilian

**Comment by Neotwr** [comment]
hi

**Comment by SireTurret** [comment]
i don't think the igniter is a bug, no. metalake's protolathe is not a bug either, it's just that we don't update it because we don't have the pop to play on it.

**Comment by niggazumi** [comment]
bruh please i need to make my trit bombs please merge

**Comment by Manly-Dwarf** [comment]
everyone from Beat! looks like they played Gaia Online
it's a horror show

**Comment by diegoxt45** [comment]
we should close source to dab on beat!

**Review by ghost — DISMISSED** [review]
ayyy mapdiffbot works again

**Comment by yoyobatty** [comment]
Needs approval from designers since it's a feature

**Comment by ghost** [comment]
This is kinda a bugfix because the wall-mounted igniters are very buggy and unreliable. They're not functionally different and this PR is already a week old, so I'm going to merge.

But before I do, @Neo-0 did you remember to connect the igniter to the buttons?

**Comment by Neotwr** [comment]
yes, they are connected and I tested locally, the floor igniter already has the same id

**Review by yoyobatty — APPROVED** [review]
I'll merge since metalake is hardly used.

**Pull request merged**
