### PR TITLE
Old pulse sound

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## Changelog
:cl:
soundadd: Reverted the pulse rifle sound back to the good old sound.

/:cl:

## About The Pull Request
This reverts the sound of the pulse rifle destroy setting back to the 2016 version which was much better.

## Why It's Good For The Game
Makes your experience much better. The pulse rifle should sound like death.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
I wanted to do this but decided against it because I remember it being ear-splittingly loud

**Comment by Manly-Dwarf** [comment]
also I just got used to modularized code and now you're just gonna remove the soundfile like this and replace it
it's for the greater good but it will drive me and future coders mad when they see the modularized code and question why it's even here

**Comment by Gandalf2k15** [comment]
The sound isn't overly loud, it's the same as the current one, just with more bass.

**Comment by ghost** [comment]
you are incredibly based

**Comment by NautilusViper** [comment]
oh fuck this is so much better

> also I just got used to modularized code and now you're just gonna remove the soundfile like this and replace it
> it's for the greater good but it will drive me and future coders mad when they see the modularized code and question why it's even here

hgtow is a bad idea and the sooner we ditch it the better

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by yoyobatty** [comment]
This is a very stale and messed up PR, closing.

**Pull request closed without merging**
