### PR TITLE
Added a new special scream

### PR DESCRIPTION
**Pull request by Jujumatic**
Hi guys, just added a new scream that can pop up rarely for stupid memery purposes. Let me know what you think

## Changelog
:cl:
add: Added a new special scream that can occur rarely
/:cl:

### CODE REVIEW

**Comment by mikolaj007** [comment]
sweet christ
make it prob(1) prob(1)

**Comment by Jujumatic** [comment]
:what:

**Comment by mikolaj007** [comment]
make it 1/10000
1/100 is too often

**Comment by Jujumatic** [comment]
that would be prob(0.1) 😢

**Comment by Jujumatic** [comment]
wait wtf why 1/10000 jesus fuck lol

**Comment by DaydreamPuppeh** [comment]
Whats the scream

**Comment by Manly-Dwarf** [comment]
-1

**Comment by Jujumatic** [comment]
@daydreampuppeh go to the ogg file, view raw and save as. Then you can play it on your computer

**Comment by Jujumatic** [comment]
Hey there #designers could you send a vote on this pr thanks

Head designer don't cuck me again please

**Comment by Manly-Dwarf** [comment]
-1 still

**Comment by mikolaj007** [comment]
-1

**Comment by Majick1** [comment]
-1, earrape and not even deep fried

**Comment by NautilusViper** [comment]
suggestion: [this instead](https://www.youtube.com/watch?v=Xbf3QxmBC10)

**Pull request closed without merging**
