### PR TITLE
Replaces server restart with force shuttle call

### PR DESCRIPTION
**Pull request by JohnGinnane**
:cl: JohnGinnane
admin: Changed the "vote restart" functionality to force call the shuttle (cannot be recalled), rather then restarting within 30 seconds
/:cl:

People upset at getting killed call the vote, sometimes just to spite the tators. Sometimes they're right and sometimes they're wrong, but with this it means the tator has a define time frame to complete his objectives rather than just outright restarting the whole game after 30 seconds

Fixes https://github.com/HippieStation/HippieStation/issues/7515

### CODE REVIEW

**Comment by Jujumatic** [comment]
But does this also stop a no vote counting as a continue

**Comment by JohnGinnane** [comment]
Voting "no" will mean you don't want the shuttle
Voting "yes" will mean you do want the shuttle
Not voting is unchanged, and I'm not going to change this. Vote-restart isn't a tool to be used when "am dead pls restart xD"

**Comment by Jujumatic** [comment]
The votes are already hard enough to get through even when the round has ended and mc has died because of the auto continue votes. Without that being changed, I have a feeling a lot of people will be upset by this.

**Comment by Manly-Dwarf** [comment]
This could be resolved by not having lazy administration with a few new admins that we'll burn out in a couple of weeks.

But I'm not too sure about this. The shuttle breaking at round-end, for instance, can only be resolved by a vote restart if there's no admins on. On top of that sometimes antags will delay the round as much as possible, and with 90% of the server dead I doubt people want to wait another 15 minutes of fuckall happening while an antag taunts everyone in deadchat about how robust they are because they emagged into the armory on a no-sec round.

On the other hand, yes, a lot of people do it out of spite - but that seems to be something that could be fixed by, I don't know, having an actual antag token system that rewards them with tokens when the server is force restarted? You know, what usually happens already? Or just banning the people who do it.

It feels a tid pointless, and it causes more issues than it fixes.

**Comment by JohnGinnane** [comment]
>The shuttle breaking at round-end, for instance, can only be resolved by a vote restart if there's no admins on.

Eh, we think this might actually be the cause of the shuttle breaking, but we need to look into it more. Admins being on fixes this though

>On top of that sometimes antags will delay the round as much as possible

You cannot recall this shuttle, so this isn't relevant here

>On the other hand, yes, a lot of people do it out of spite

This is the primary reason for this, even meme votes could potentially get passed

>something that could be fixed by, I don't know, having an actual antag token system that rewards them with tokens when the server is force restarted

I'm not necessarily disagreeing with this but a token system isn't what this PR is for

>it causes more issues than it fixes.

What issues does this cause?

**Comment by JohnGinnane** [comment]
>The votes are already hard enough to get through even when the round has ended and mc has died because of the auto continue votes

Yeah I really want to test this and see what causes this to happen because I believe runtimes were happening when a vote took place or ended when shuttle was in transit or landed at centcomm, not sure on the specifics but something fucky is definitely going on. This PR isn't to do with that though, and in those cases vote restart is still broke as far as I know

**Comment by Manly-Dwarf** [comment]
>What issues does this cause

I just explained what issues it causes. You're reducing the players' ability to restart the round immediately with a 15 minute wait button, and passing votes already is a pain in the ass.

>Eh, we think this might actually be the cause of the shuttle breaking, but we need to look into it more. Admins being on fixes this though

Keywords being "admins being on". If there aren't admins on, restart is the only way for players to immediately end the round when things such as the shuttle runtiming, all the comms consoles mysteriously missing, everyone being bathed in fire, etc. cause the round to either refuse to end or be a boring slog that nobody wait through. In other wrods, you're removing the ability for players to end the round when everything goes sour, and while this is abused from time to time, I almost never see it actually pass out of spite. For instance;

In all of my time murderboning I've never had a restart vote pass against me. Don't even say "that's hyperbole" because it's not. I've seen plenty of people try, and plenty of people fail. On top of that, if players are able to pass votes out of spite, that likely means there's no admins on to begin with so the antagonist could have delayed the round forever anyhow with no repercussions.

Honestly, I see this as more of an "admins are lazy" issue than a "coders need to fix this" issue. If this is becoming a rampant issue, then admins should start banning people who started the votes like they used to. Punishing everyone for the actions of one dickhead doesn't seem right.
I hate to sound really hostile against this, but it just feels like the easy option to fix a bigger issue. Sorry if I'm coming off like a prick, but as I explained this isn't something coders should be touching in my opinion.

**Comment by JohnMcLaime** [comment]
People passed it multiple times against me.

**Comment by JohnGinnane** [comment]
>If there aren't admins on, restart is the only way for players to immediately end the round

I wonder if we can find some sort of compromise but let me address some of the points:

>things such as the shuttle runtiming

Vote restart bugs out as well, as I said before I think this is related to voting while shuttle is being used

>all the comms consoles mysteriously missing

If there's no comm computers then the shuttle is auto called for 25 mins, but if some shitter decides to use one of the boards to constantly recall then yeah, but this change will still end the round in this case, because they won't be able to recall the shuttle

>everyone being bathed in fire

Remember, the shuttle is still called and cannot be recalled. If this scenario happens then the round will end eventually

>you're removing the ability for players to end the round when everything goes sour, and while this is abused from time to time, I almost never see it actually pass out of spite

Not exactly. I am removing the ability for players to end the round in 30 seconds, but I am giving them the ability to end the round as if the shuttle was called. And "when everything goes sour" is not the only time it's called. Just now one of the players I killed started a vote within 60 seconds of being killed. The vote was close, but didn't pass. He was later cloned. I have seen it pass and Roma has seen it pass.

>Don't even say "that's hyperbole" because it's not

You're right, it's not hyperbole, but it is your experience. It has definitely happened to me and I'm sure there are others that it has happned to. Don't forget that this basically extends the duration before the round is restarted.

>On top of that, if players are able to pass votes out of spite, that likely means there's no admins on to begin with so the antagonist could have delayed the round forever anyhow with no repercussions.

See above points. The functionality is changed to **call an un-recallable shuttle so that tators have a finite amount of time to stop fucking around and complete their objectives**

>Honestly, I see this as more of an "admins are lazy" issue than a "coders need to fix this" issue

I agree but unfortunately we don't have admins on at all hours

>Punishing everyone for the actions of one dickhead doesn't seem right

I also agree with this but I'm reworking the ability so it can't be abused as much

>Sorry if I'm coming off like a prick, but as I explained this isn't something coders should be touching in my opinion.

No worries, we both feel very strongly about this though so it's understandable

**Comment by JohnGinnane** [comment]
can we get some @HippieStation/head input though, because KBB and I are both just players

**Comment by praisenarsie** [comment]
WE ALREADY HAVE A FUCKING LABEL FOR ADMINISTRATION AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by JohnGinnane** [comment]
@praisenarsie calm down HOMEY

**Comment by Carbonhell** [comment]
the fuck is a sunflower issue
also sure +1 but no votes should still count as a no imo

**Comment by earthmoonjune** [comment]
+1

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
why isn't this merged dammit

**Comment by Jujumatic** [comment]
guys...?

https://forums.hippiestation.com/viewtopic.php?f=14&p=1180#p1180

**Pull request merged**
