### PR TITLE
Adds shark people

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
add: Shark people are now a playable race.
/:cl:

https://vgy.me/c0wyx5.png

Shark people come from an ancient water planet where everything is a water creature that somehow has legs and can breathe air instead of water.

**to do**

- [ ] Meat

- [ ] Teeth

- [ ] Better icons?

- [ ] Screams

### CODE REVIEW

**Comment by ghost** [comment]
this is literally uncanny valley tier
no thank you

**Comment by FuryMcFlurry** [comment]
low grade sprite, needs more sharktail head attachments

**Comment by tortellinitony** [comment]
I just found these online, you can make a better one

**Comment by FuryMcFlurry** [comment]
no thank you.

**Comment by GuyonBroadway** [comment]
At least get a custom scream sound.

**Comment by GuyonBroadway** [comment]
Also code is good, but it needs head input.

**Comment by j-mie** [comment]
I mean, more custom Hippie fluff is always good IMO.

**Comment by tortellinitony** [comment]
there is a scream sound, I'll add that soon

**Comment by tortellinitony** [comment]
Original PR https://github.com/HippieStationCode/HippieStation13-1/pull/1997

**Comment by Carbonhell** [comment]
no
NO
 ---N
 N O N
 ---N

**Review by ghost — APPROVED** [review]

**Comment by FuryMcFlurry** [comment]
If you guys are seriously going to consider adding this. Let me atleast make them look good. Meaning im going to make them look more like zoras from the latest zelda game. You fine with this?

**Comment by ghost** [comment]
oh jesus christ no
no -1

**Comment by KayeArray** [comment]
the slippery cum stained slope

**Comment by tortellinitony** [comment]
make them look whatever looks good

**Comment by oprayx77** [comment]
literally only if they're valid like cats

**Comment by doobiedoo23** [comment]
no

**Comment by Carbonhell** [comment]
2 heads and 2 gms no… closing this,sorry mate

**Pull request closed without merging**
