### PR TITLE
Map updates again

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: Added old maint bar
add: Plasma glass windows and security cameras inside atmospheric pressure rooms
add: Different, more robust AI core
add: Shutters to AI chamber entrance
tweak: Fixed the camera outside mime office being right on the door
add: Camera outside the particle accelerator in engineering
tweak: Upgraded the APC in Atmospherics to a 10k because it is the first APC to burn out
at loss of power + set enviro and equipment to default on so station gets air if the battery saver turns
tweak: Genetics APC is now unlocked by default incase of power failure + set enviro to default on so cloning will still work on low power
fix: Engine monitor works again
add: Old shop front maint by engineering
add: Connector ports to starboard and port emergency storages for refilling air canisters
add: Navigation beacons to AI sat

/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Old maint bar is cool as fuck. Period. Also our previous AI core design sucked ass so it's better. Atmospherics needed the upgrade as well considering it's the life support of the station. So ya, hopefully you guys enjoy this.

image

image

image

image

image

### CODE REVIEW

**Comment by ghost** [comment]
oh yes! now remove the atmos maint south of viro and put the chem lab in it!

and maybe add some maint slums!

**Review by GuyonBroadway — DISMISSED** [review]
Code looks ok

**Comment by dreamcrab** [comment]
yaaaaaaa

**Comment by ghost** [comment]
fix changelog

**Review by GuyonBroadway — APPROVED** [review]

**Comment by ghost** [comment]
Your Fix/Feature pull request delta is now above zero (1). Feel free to make Feature/Tweak/Balance PRs.

**Pull request merged**
