### PR TITLE
Makes detectives closet and office more secure

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
balance: Detective offices doors are stronger like the rest of security
tweak: Detectives' office window grill is shocked
balance: Detective's cabinet is stronger
/:cl:

## About The Pull Request
What it says in the cl and title.

## Why It's Good For The Game
https://github.com/HippieStation/HippieStation/issues/11906

Apparently everyone thought it needed to be done, I'm just here, delivering the deeds.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
would still prefer the dets office being relocated but fine whatever
it was getting powergamed every round by robutticists and fartmos techs

**Comment by Manly-Dwarf** [comment]
also if this gets in the way of your great christmas PR and freon getting merged then -∞

**Comment by enthethan** [comment]
Personally I think dets office should be relocated to the unused room that's next to gulag

**Comment by yoyobatty** [comment]
I supposed I could renovate that office to fit the detective

**Comment by ghost** [comment]
+1 to this PR and anything else which makes the revolver harder to get

**Review by ghost — APPROVED** [review]

**Comment by diegoxt45** [comment]
just make the det office next to the lawyer office

**Comment by Maroonenahmoron** [comment]
+1 for now, move office to a better location later.

**Comment by yoyobatty** [comment]
Will re-do this for a better idea you guys suggested.

**Pull request closed without merging**
