### PR TITLE
[MIRROR] Adds BSQL

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/38323
--------------------
:cl:
server: Added BSQL.dll and updated libmariadb.dll for non-blocking SQL support. See https://github.com/tgstation/BSQL for instructions on building for non-windows systems
/:cl:

BSQL ~uses the [libmariadb non-blocking API](https://mariadb.com/kb/en/library/non-blocking-api-reference)~ runs queries in separate threads to allow us to start queries/connections and check up on them later as opposed to blocking the entire game. SSdbcore has been folded over the BSQL DMAPI so that it works the same as before, only changes are in dbcore.dm. ~~Calls that used to block will now sleep.~~

Eventually we can make the whole stack use an async pattern to cut out the lag. The 4 query execution functions (Execute/warn_execute/NextRow/MassInsert) now include an `async` parameter which will sleep the proc for it's duration instead of blocking.

BSQL.dll was built on release configuration from the v1.3.0.2 tag
libmariadb.dll was built on release configuration from the 3.0.2 tag of https://github.com/MariaDB/mariadb-connector-c (We could potentially get away with not changing this but I'm not familiar with how .libs work in terms of relocation or what version we're currently using)

The exact same binaries can be found here: https://github.com/tgstation/BSQL/releases/tag/v1.3.0.2

TODO:

- [x] Test with tg schema
- [x] Finish writing BSQL README.md
- [x] Test live (HAHAHA GET FUCKED ME)
- [x] Test live more

### CODE REVIEW

**Comment by Carbonhell** [comment]
Need #8095 to be resolved prior to merge this

**Comment by yoyobatty** [comment]
@Carbonhell which files to we need to add into qdel queries? Should I just manually add them in based off of what the qdel query PR did?

**Comment by ghost** [comment]
Fixed merge conflict to reflect this:
https://github.com/tgstation/tgstation/blob/master/code/controllers/subsystem/dbcore.dm#L191

**Review by JohnGinnane — DISMISSED** [review]
Problem on https://github.com/HippieStation/HippieStation/pull/8196/files#diff-8a5a6764887bcdff55aea0eb807a2f00R191

Needs to be the same as https://github.com/tgstation/tgstation/pull/38323/files#diff-8a5a6764887bcdff55aea0eb807a2f00R191

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
