### PR TITLE
Enables upgrading and supercooling servers to produce more points.

### PR DESCRIPTION
**Pull request by xTrainx**
🆑
tweak: you can now upgrade servers to generate points faster
tweak: servers will now generate more point when colder
/:cl:
 
Servers will now produce 33% more points per tier of parts, double with triphasic scanners. They also linearly produce more points the colder they are, double at the lowest possible temperature. This can stack to a maximum of 4x point generate rate. The default, round-start point generation has not been changed.

Active servers must be cooled in order to function, at room temperature they will not generate any points at all. Additionally, servers now utilize cooperative computing; the points generated are a sum of the active research servers. You won't generate more points by making more servers, however if any actives servers are not upgraded or poorly cooled you will generate less points proportional to the state of the servers.

For example, 1 default server at the normal temperature of a freezer will generate 2,500 points a minute. So will 2, or 10 under the same conditions. 1 server in such a state, and 1 sitting at room temperature will generate 1,250 points per minute; the poorly cooled server will bog down the other server as they try to work together. One fully upgraded server and one normal server will generate 1.5x as many points as normal. And so on.

I would change it such that building more servers generates more points, but Kor explicitly forbade that and closed the last PR which did exactly that. If you want that to work, change his mind.

-Buggy123

i just stole this PR, see if people here would merge it

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Gosh darn it why would you close this?

**Comment by xTrainx** [comment]
i realized it adds a gameadmin to the config

**Comment by GuyonBroadway** [comment]
The config means jack shit.

**Comment by GuyonBroadway** [comment]
this needs fixing.

**Comment by xTrainx** [comment]
i'l make my own pr for this and make it modular then

**Pull request closed without merging**
