### PR TITLE
Brings back spiked metal bat. and metal bat pre-rebase sprite

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: # Brings back old spiked baseball bat and metal baseball bat sprites, tweaked to fit current baseball bat shape. And the old spiked baseball bat. resprites the tg derived baseball_bat/ablative to our pre-rebase metal bat sprite.
:cl: zamolxius
add: spiked baseball bat
imageadd: added old baseball bat and metal bat icons and inhands.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
pre-rebase sprites

964f07469e210ffbe79bfc4e2b02b893

a24cee3cc87fff7ee531919bfb883c98

pre-rebase feature @Carbonhell

### CODE REVIEW

**Comment by TrickyDickRichard** [comment]
gud

**Comment by JohnGinnane** [comment]
So you've modularised the icons which is great, but if you spawned/created a baseball bat with spikes, does it still use the /tg/ sprites or does it use ours? If it's the former then I can help you fix that, it's pretty straightforward

**Comment by ghost** [comment]
we don't have spiked bats yet,  im planning on it, this is just preemptive

**Comment by Pyko1** [comment]
sure +1

**Review by JohnGinnane — APPROVED** [review]
Code looks good

**Comment by earthmoonjune** [comment]
yes +1

**Comment by ghost** [comment]
bump

**Comment by JohnGinnane** [comment]
@zamolxius we have conflicts with icon files :(

If you copy your icons out, then get the latest version of the conflicted files, then copy your icons back in

**Comment by ghost** [comment]
i made a new pr

**Pull request closed without merging**
