### PR TITLE
[MIRROR] Unassumes moth genders

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34702
--------------------
invalid arg for that proc. they don't have gender sensitive names.

Fixes #34728

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Pardon me sir what is this nonsense and why does it require a 70 line fucking file?

**Comment by Pyko1** [comment]
because the moth shit is not merged around here

**Comment by praisenarsie** [comment]
>70 line

it's 69 lines!!!

**Comment by Pyko1** [comment]
adding this all to the initial moth mirror

**Pull request closed without merging**
