### PR TITLE
makes holoparasites cost less

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl: zamolxius
tweak: tweaked holoparasite's TC price from 18 to 12, as you usually get retards anyways and it's too huge of a liability to cost 18 TC when you can get multiple syndicate bombs
/:cl:

### CODE REVIEW

**Comment by DaydreamPuppeh** [comment]
I'm not too sure about this. A holoparasite can be incredibly powerful.

**Comment by mikolaj007** [comment]
its not powerful enough to take up 90% of one's TC

**Comment by Manly-Dwarf** [comment]
Lazy PR. -1
Actually make holoparasites worth it rather than just reducing the price. Last time they were 12 TC pretty much everyone just got combo items with them and made them annoying as hell to deal with.

also I was already on fixing them, you're stealing my job you hack fraud 👺

**Comment by ghost** [comment]
its not lazy,  it's *cost effective*. 
How could one make holopara worth it?  Its more of a person problem. There are also a bit too many types of holoparasites when most arent even used.  Id say standard + chaos + support + ranged are the only necessary ones.

**Comment by k-k-karma** [comment]
if it isn't 12tc, how am I supposed to get the rapid punching gloves

**Comment by Manly-Dwarf** [comment]
@zamolxius holoparasites as a whole right now need a lot of touching up on if you ask me. Just lazily changing the price fixes nothing about them being a boring, buggy mess that depends on roundstart suicides right now.
also yes I agree with you, the unnecessary dumb holoparasites like the lightning one need to be removed. especially because the lightning one is laggy as all hell

**Comment by ghost** [comment]
how about each holopara giving the owner a passive bonus?  The chaos one makes you unable to be set aflame,  how about standard giving you either fist of the north star punching speed or innate armor?  ranged lets you evade ranged bullets or something, support something like no oxyloss in crit?

**Comment by Manly-Dwarf** [comment]
noooooo
How about, I dunno, giving the Standard Holoparasite more to do? Make it easier for him to punch people? Let him stop time? Star Finger? Maybe even let the user stop time if the holoparasite is currently inside?
Ranged, make the snare better. Traps. Anything.
Get inventive! This is jojo code, time to get funky.

also
>ranged lets you evade bullets

goes from top tier holoparasite to "why would you buy anything other than this"

**Comment by ghost** [comment]
are particle effects feasible?  
[[[ MENACING]]]  on stando manifest

**Comment by Manly-Dwarf** [comment]
Of course they are.
I could probably do stuff like that, honestly. Dunno how much time you have on your hands but I was already working on a holoparasite fix for a little while now.

**Comment by ghost** [comment]
im bottom of the barrel coder dont take me into consideration

**Pull request closed without merging**
