### PR TITLE
Gang can now buy stando powah for 150 influence.

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Added stand tarot card to gang. Buyable for 150 influence.
/:cl:

image

### CODE REVIEW

**Comment by SireTurret** [comment]
stands are used too much already

**Comment by ghost** [comment]
ok how about fish stands then

**Comment by ghost** [comment]
the holocarp standos

**Comment by cb583** [comment]
-1 tbh, gangs win a lot already and adding stands kinda messes with the theme

**Comment by ghost** [comment]
> -1 tbh, gangs win a lot already and adding stands kinda messes with the theme

well gangs win in any case as they steamroll the security shitters. not that we have a lot of them. can always make them more expensive

**Comment by karmaisblackandbluepilled** [comment]
wtf -1 this has nothing to do with gangs

**Comment by ErwinSnowden** [comment]
> wtf -1 this has nothing to do with gangs

yes it does.

**Comment by diegoxt45** [comment]
-1 lmao no

**Comment by waterwater1212** [comment]
maybe a secret rare gang with giorno's pink jacket thing as the uniform, and purchasable stands. good tihnking sips you're a genius

**Comment by ghost** [comment]
If you change it to a stand arrow I'll +1

**Comment by ghost** [comment]
@karmaisblackandbluepilled uncultured swine

**Comment by ghost** [comment]
@MrHardDrive they're sacrificing like ten guns for a single stand. Pretty sure the only reason you'd want this is style points

**Comment by Toxici11i** [comment]
+1 for epic giorno memes. 150 influence is a FUCKING LOT - realistically, if your going to buy this you will have to have nearly everyone converted, and tag most of the station and wait. otherwise, its not viable to buy. still, would be an epic meme

**Comment by ghost** [comment]
why is diego trying to +1 stuff again? they aren't a designer or a GM/HA.

**Comment by diegoxt45** [comment]
> why is diego trying to +1 stuff again? they aren't a designer or a GM/HA.

ok retard

**Comment by ErwinSnowden** [comment]
Might want to up the price on the stand arrow since it's 3~ stands in one, also this is going to introduce requiem into alot more rounds.

**Comment by ghost** [comment]
@ErwinSnowden 
stand arrow has a 50% chance of literally disintegrating you. Plus, 150 influence is a stupidly high amount.

**Comment by Manly-Dwarf** [comment]
no

**Comment by ErwinSnowden** [comment]
> no

yeah ok pubbie, why can't we have jojo in gangs?

**Comment by TrickyDickRichard** [comment]
> > no
> 
> yeah ok pubbie, why can't we have jojo in gangs?

because that's fucking retarded

**Comment by ghost** [comment]
@Manly-Dwarf as I said, if it's a stand arrow it will disintegrate half the gangies who try to use it. Plus, you gotta realise how unreal 150 influence is - you're better off buying a good twenty surplus rifles and going on a rampage.

**Pull request closed without merging**
