### PR TITLE
[MIRROR] Disables battle royale mode

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/41902
----------------------------
:cl: Denton
fix: The MultiZ test map is no longer the default map.
/:cl:

Speedmerge would probably be a good idea or every server is gonna end up like Terry:
capture

### CODE REVIEW

**Comment by yoyobatty** [comment]
Gee, git is being dumb, who woulda guessed.

**Review by yoyobatty — APPROVED** [review]

**Comment by k-k-karma** [comment]
sorry, didn't realize you were using this?

**Comment by yoyobatty** [comment]
Yeah, we still need to remove the _map file, git diff thinks master is up to date even though it isn't.

**Comment by yoyobatty** [comment]
Actually fuck it, i'll web edit

**Pull request closed without merging**
