### PR TITLE
[MIRROR] Adds nothing

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42596
----------------------------
## About The Pull Request

This pull request adds nothing at all.

## Why It's Good For The Game

It's a small addition that adds more nothing.

## Changelog
:cl: Nervere & kevinz000
add: You can now carry on as you were as nothing was actually added.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Thanks guyon, I almost had a heart attack that hippie was going to get fetish content

**Comment by yoyobatty** [comment]
Nice, merge it.

**Comment by GuyonBroadway** [comment]
What fetish content? There is nothing here.

**Comment by ghost** [comment]
existential dread is my fetish

harder daddy, I need more nothing

**Comment by waterwater1212** [comment]
> existential dread is my fetish
> 
> harder daddy, I need more nothing

!

**Comment by Jujumatic** [comment]
make sure to squash and merge so this commit never comes up ever again

**Review by Jujumatic — APPROVED** [review]
looks just perfect :agony:

**Pull request merged**
