### PR TITLE
BEHOLD, HANGED MAN!

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Added reflective holoparasites. They can only manifest while reflecting through an object. Examine the glowing green object in order to be able to see it, lest it stab you!
/:cl:

[Vid of invisibility in action](https://img.steamport.xyz/Y8U8vnb2DN.mp4)

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
is cool

**Comment by Majick1** [comment]
+1, looks good

**Comment by lunaman22** [comment]
+1 i hate the current stands this seems like a cool gimmick

**Comment by Lxtoofonea** [comment]
+1, looks cool

**Review by AnthonyJNgo — APPROVED** [review]
Does what it says it does. Any bugs, lynch steamport.

**Pull request merged**
