### PR TITLE
changes some sounds to be like the old ones again

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Shutters will now make sounds when opened and closed!
add: Some old ambiance files were put back, nostalgia!
/:cl:

### CODE REVIEW

**Review by KayeArray — APPROVED** [review]

**Comment by Spacedong** [comment]
cool real nice

**Comment by praisenarsie** [comment]
OPTIONAL NAME HERE

**Comment by KayeArray** [comment]
mystery coder making the server great again

**Comment by praisenarsie** [comment]
chnkr needs less 7 alts

**Comment by KayeArray** [comment]
good+1

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
Yeeeees!

**Comment by dreamcrab** [comment]
very cool very swag +634

**Pull request merged**
