### PR TITLE
Adds some new alternate screams and new clothes

### PR DESCRIPTION
**Pull request by JohnGinnane**
[Changelogs]: Changed how the screams are handled slightly. Now when any item is equipped or dropped, all screams are reindexed. This means you don't need to worry about handling it yourself. You can just add the `alternate_screams` list and it's ready to go.

I have added the following:

* Cardborg helmet - Cyborg scream
* Xeno helmet - Alien scream
* Clown mask - Screams replaced with laughing
* Mime mask - Doesn't many any noise when screaming
* Monkey mask - Monkey scream
* Ushanka - A nu cheeki breeki iv damk
* Cosby sweater - With the zipping and the zopping
* Robbie suit - The Number One meme suit from oldcode, with up to 15 unique sounds!
* Zoot suit - The classic pimp outfit
* Toad hat - aaaaaaaaa

:cl: JohnGinnane
add: Added Cosby sweater back in. Can be found in maint
add: Added Robbie suit back in. Four can be found in AutoDrobe in theater
add: Added zoot suit back in. One can be found in ClothesMate and one in AutoDrobe
add: Added new Toad hat, found in ClothesMate. Shout out to simpleflips
add: Added custom screams for cardborg helmet, xeno helmet, clown mask, mime mask, monkey mask, and ushanka!
/:cl:

### CODE REVIEW

**Comment by JohnGinnane** [comment]
@HippieStation/maintainers @HippieStation/coders this is ready for review

@HippieStation/head this is also ready for review))

**Comment by JohnMcLaime** [comment]
Add some to balaklava too please.

**Comment by JohnGinnane** [comment]
what sorts?

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=8iTKfmwSr8U

**Comment by JohnGinnane** [comment]
Not sure what the changes were to the blastco stuff, I was only adding in old and new icons

**Comment by ghost** [comment]
+1 yes

**Comment by JohnGinnane** [comment]
thanks fam

can other @HippieStation/head 🅱️ls give input

**Comment by ghost** [comment]
pretend im a head and take +1 and merge now for the good of all
okay thanks

**Comment by GuyonBroadway** [comment]
You get yo sweet ass back here and THEN your +1 might count.

**Comment by JohnGinnane** [comment]
image

I cannot self-merge

**Comment by ghost** [comment]
bepis :-DDDD

**Comment by ghost** [comment]
bebin  :    -    D D

**Comment by dreamcrab** [comment]
yeaaaaaaaaaaaa +67+77+

**Review by ghost — APPROVED** [review]

**Pull request merged**
