### PR TITLE
Adds stuff back to botany from pre-rebase and fixes a couple of bugs around Gaia

### PR DESCRIPTION
**Pull request by cacogen**
:cl: cacogen
add: Added a bunch of stuff back to the botany vending machine from pre-rebase (e.g. saltpetre, diethylamine)
add: Added recipes from pre-rebase back to the biogenerator (e.g. unstable mutagen and the other botany chemicals, jackets, bats, belts)
balance: Plant DNA manipulator production speed limitation starts at 7 instead of 9 now
fix: Gold gaia overlay on botany trays is no longer overwritten by the plant overlay
fix: Pills and produce now transfer all their reagents to hydroponics trays before deleting. Trays now truly only require 20u of earthsblood to become self-sustaining (before it was over two times that by accident)
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 

I originally had a novel here but I think it was taking this too seriously. Chemists suck, making botanists rely on the biogenerator is a good balance between forcing them to rely on chemistry and having mutagen available in the NutriMax roundstart. I've doubled the cost of mutagen in the biogenerator since pre-rebase because when I was testing this I thought it was too easy to make.

The chemicals like saltpetre and diethylamine in the NutriMax and biogenerator compensate for how gimped the plant DNA manipulator is without science now.

A lot of this stuff was taken from https://github.com/HippieStationCode/HippieStation13-2/pull/318 so credit goes to @KittyKathy

### CODE REVIEW

**Comment by ghost** [comment]
Kitty Kathy only ported my botany freeze feature, I didn't make any of those other changes. It's pretty much all accredited to Kitty.

**Comment by ghost** [comment]
That being said, I'm okay for these changes.

**Comment by cacogen** [comment]
probably should've asked you first, i didn't even end up porting that

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
`That being said, I'm okay for these changes.` OK merging

**Pull request merged**
