### PR TITLE
[MIRROR] Language datums; removes the talk wheel

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/25333
--------------------
:cl: coiax
add: Adds seperate languages to the game. Now Ratvarian, Drone, Machine, Swarmer, Human (now called Galactic Common), Slime and Monkey are separate languages. Each languages has its own comma prefix, for example, Galcom has the ,0 prefix, while Ratvarian has the ,r prefix. If you don't understand a language when it is spoken to you, you will hear a scrambled version that will vary depending on the language that you're not understanding.
experiment: This does not change who can understand what.
del: Removed the talk wheel feature.
add: Clicking the speech bubble icon now opens the Language Menu, allowing you to review which languages you speak, their keys, and letting you set which language you speak by default. Admins have additional abilities to add and remove languages from mobs using this menu.
/:cl:

#25496 Basic framework stolen from bay, but most of the actual code I've written myself.

- Removes the quick talk wheel, no one seems to use it.

- **This does not introduce any new languages, or any player accessible species specific languages.**

- People do not speak with multiple languages at once, they only speak one
- `languages_spoken` and `languages_understood` merged into the `languages` list var, with ability to speak being dealt with by the `can_speak_in_language` proc.
- Drones can only speak Drone, Cogscarabs can only speak Ratvarian, and AIs can't speak Common if they're Ratvar.
- All silicons can speak EAL (or encoded audio language), which sounds like booping and beeping.
- Slime language, although present, isn't spoken by anyone outside of pAIs.
- A language datum can define a way that it is obfuscated if someone cannot understand, generally by generating a message made up of random syllables.

### WIP progress goals

- [x] pAIs will universal translator will be able to understand and speak all languages
- [x] People will be able to select what language they speak in by default
- [x] Actually modify say code to use the ,x prefix system for specifying which language you talk in.
- [x] Work out how languages over the various hive minds work.

### Testing related bugs

- [x] AIs make strange noises over their radios
- [x] pAIs make strange noises over their radios
- [x] The Announcement System makes strange noises over the radio.
- [x] When the AI talks over the radio, it is named "TABI (AI Eye)" (FOR OBSERVERS ONLY, which helped solving the bug)
- [x] Holopad holograms just make strange noises
- [x] The supermatter just makes strange noises when it's alarming
- [x] Medibots just make strange noises (dammit, fucking radios, check the rest of the bots while I'm there)
- [x] MMIs make strange noises
- [x] Surprise surprise, universal recorders don't fucking work
- [x] Fixed carbons being able to speak languages that they didn't know, but that their tongues COULD speak.

Then once this system is fairly stable, we can talk about additional extensions, such as sign language, machine language for silicons, and languages for ash walkers and golems.

image

LANGUAGE MENU

### CODE REVIEW

**Comment by JohnGinnane** [comment]
This is pretty big PR

**Comment by JohnGinnane** [comment]
@JamieH need thoughts on this

**Comment by JohnGinnane** [comment]
image

need to fix reject files

**Comment by j-mie** [comment]
build this

**Review by j-mie — APPROVED** [review]

**Pull request merged**
