### PR TITLE
Fixes reagent floors, make reagent refinery upgrade-able

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: Adds reagent refinery circuit board
add: Allows reagent refinery to be upgraded to decrease processing time and increase ingot output
fix: Fixed reagent floor tiles opening space when crowbared 
fix: Fixed null icons on reagent floor tiles
admin: Adds logging for heating and vaporizing reagent floor tiles
tweak: Reagent refinery has an examine description showing processing stats
/:cl:

[why]: This needed to be done a long time ago.

### CODE REVIEW

**Comment by DaydreamPuppeh** [comment]
What does upgrading it do? Reduce matetial cost and increase speed?

**Comment by yoyobatty** [comment]
Updated changelog to say what it does

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Pull request merged**
