### PR TITLE
Adds sexy green intercoms

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
imageadd: Adds sexy green intercoms
/:cl:

they're animated, too!
smexy

### CODE REVIEW

**Comment by PopNotes** [comment]
animation preview **B**roke

**Comment by doobiedoo23** [comment]
old intercoms are better

**Comment by PopNotes** [comment]
yeah I hate to say it and I know how much nobody wants to hear it but

intercoms are one of those sprites that doesn't NEED a rework, like cameras

**Comment by KayeArray** [comment]
very true but the colour change is nice.

this is a very subjective change

**Comment by Carbonhell** [comment]
-1 sorry but some icons are iconic imo and i'd rather prefer them to not change, and it seems like people agree with me

**Pull request closed without merging**
