### PR TITLE
Roundstart Honkbot

### LINKED ISSUE #12604: Add a roundstart Honkbot that patrols the station
Honkbots are neat and not often seen.

### PR DESCRIPTION
**Pull request by carlopault**
## Changelog
:cl: Carlospaul
added: New roundstart honkbot. 
/:cl:

Associated feature request: https://github.com/HippieStation/HippieStation/issues/12604

Speedmerge this.

### CODE REVIEW

**Comment by mkikt4743** [comment]
yeah

**Comment by MrEpicSax** [comment]
+1 yes

**Comment by AnthonyJNgo** [comment]
+3, needs more votes.

**Review by AnthonyJNgo — APPROVED** [review]
Looks good.

**Comment by wheezl** [comment]
+1

**Comment by Punkinguy** [comment]
+1

**Pull request merged**
