### PR TITLE
Adds renamer circuit

### PR DESCRIPTION
**Pull request by Carbonhell**
:cl:
add: Adds the renamer circuit, feed it a string, pulse it and it'll rename the assembly it is in.
/:cl:

[why]: Useful for tcomms circuits and such.

### CODE REVIEW

**Review by GuyonBroadway — APPROVED** [review]
Looks ok to me.

**Comment by bardofrage** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Comment by BlueNothing** [comment]
Wow, this sounds OP. Kidding! I think it'll be pretty cool.

**Comment by Carbonhell** [comment]
Ready to merge.

**Pull request merged**
