### PR TITLE
Remove nanite program limit

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt
tweak: You can now have UNLIMITED nanite programs!
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
>Nanites have antistuns
>Said antistuns have yet to be removed
>Let's buff Nanites!

ni

**Comment by ghost** [comment]
@Kawaii-Big-Boss with the major disadvantage that an EMP can make said anti-stuns start eating your flesh

**Comment by Manly-Dwarf** [comment]
>justifying antistuns

NI

**Comment by Lxtoofonea** [comment]
I think that would be fine +1

**Comment by Eagle-Eyess** [comment]
-1 the limit is fine. It gives a balance to them

**Comment by yskefunky** [comment]
no please never -1

**Comment by bardofrage** [comment]
-1, the last thing we need is lag.

**Comment by Lxtoofonea** [comment]
i resend my +1, i now give it a -1, no more lag, lag is very bad

**Comment by yoyobatty** [comment]
This has -2, going to close this.

**Pull request closed without merging**
