### PR TITLE
Adds basic chems to underused plants

### PR DESCRIPTION
**Pull request by RafRoq**
copied a good refused pr from tg https://github.com/tgstation/tgstation/pull/42590

:cl:   Botany Chem Tweaking
tweak: adds sulfur to onions
tweak: add liquidgibs to meatwheat
tweak: add oxygen to space tobacco
tweak: add carbon to tower caps
tweak: add iron/aluminium to steel caps
tweak: add ethanol to moonflowers
tweak: add nitrogen to cabbage
tweak: replace corn oil in sunflowers with regular oil
tweak: add sodium to red beets
tweak: add 5 hydrogen to grass
:cl:

### CODE REVIEW

**Review by Jujumatic — DISMISSED** [review]

**Comment by Jujumatic** [comment]
these are such tiny amounts of chemicals though, i don't even think it'll do anything significant

**Comment by RafRoq** [comment]
i will review the balance then

**Comment by RafRoq** [comment]
@Jujumatic but the idea is not to make stronger but give more small stuff to do

**Comment by RafRoq** [comment]
thats all @Jujumatic free to approve wont change anything anymore

**Review by Jujumatic — APPROVED** [review]

**Comment by Jujumatic** [comment]
needs head input

**Comment by Lxtoofonea** [comment]
+1

**Comment by Jujumatic** [comment]
still needs just one more +1

**Comment by funkynuggets** [comment]
why not +1

**Comment by Carbonhell** [comment]
sure +1

**Review by Jujumatic — APPROVED** [review]

**Pull request merged**
