### PR TITLE
THIS WILL BE THE LAST TIME YOU SEE ME (BUTTERFLY KNIVES)

### PR DESCRIPTION
**Pull request by KayeArray**
:cl: banthebantz & popnotes
add: Added normal and syndicate butterfly knives, these nasty weapons pierce armour and do bonus backstab damage
add: Traitors can purchase the energy butterfly knife for 12tc which does a whopping 80 backstab damage
add: Crew can create normal butterfly knives through the crafting menu, these do 30 backstab damage
/:cl:

[why]: fun weapon with a fun gimmick

video: https://www.youtube.com/watch?v=iPKDjHhfUro

### CODE REVIEW

**Comment by ghost** [comment]
does the backstab set the move modifer properly?
otherwise you could chain like backstabs together without a click delay

**Comment by KayeArray** [comment]
not sure what you mean by move modifier but the backstab is limited by normal click delay as it is called on attack

**Comment by ghost** [comment]
okay good,
i'd remove the harm intent requirement to be honest.
intents should be used when the item can be used in different ways. this is a backstabby hurt and thingy weapon and that's that.

**Comment by ghost** [comment]
are you meant to be unable to attack yourself on harm intent?
i can't do the backstab, eye stab or regular slice on myself while on harm intent.

**Comment by KayeArray** [comment]
well i added the harm intent requirement so you have the option to stab normally instead

and as for the hit yourself thing yes I am aware of it, returning backstab to normal attack didn't work so it just returns nothing

**Comment by ghost** [comment]
personally i can only see the harm intent requirement being more hassle than its worth.
if you can backstab with the weapon then you should do it.
I'd at least make it so only help intent prevents backstab if you want that functionality kept in but i can only see people getting upset over "wtf i no backstab...."

**Comment by tortellinitony** [comment]
photos

**Comment by KayeArray** [comment]
alright now only help intent will stop backstabs

**Comment by KayeArray** [comment]
https://www.youtube.com/watch?v=iPKDjHhfUro

**Comment by Carbonhell** [comment]
>80 backstab damage
>"fun gimmick"
Lol no

**Comment by KayeArray** [comment]
and why not?
it costs 12tc, is melee only and is a loud obvious weapon that does less damage than an esword if you fail to backstab

**Comment by ghost** [comment]
i honestly don't see anyone getting kills with this using the backstab, it seems way too unreliable
thus it's a gimmick weapon which i'm willing to see in the game

**Comment by PopNotes** [comment]
Trip people, buckle them to chairs and go at their back with the knife

New meta?

Honestly tho, I wouldn't know how to do this, but make it so that you can get backstabs so long as you're on any of the three tiles behind someone. I want to see real(TM) spies doing sick trickstabs.

**Comment by Carbonhell** [comment]
>way too ureliable
>backstab checks only the dir
>you can effectively run in circle and deal 80 damage
Come on goddamn. -1

**Comment by KayeArray** [comment]
>melee only
>less reliable than a revolver which is now cheaper
>obvious on and off sound
>obvious sprite
>what is a stun baton
>what is disarm

**Comment by PopNotes** [comment]
>backstab checks only the dir

yeah like I said, make backstab range the _three_ tiles behind someone, like in this handy dandy visual guide I made

clicc

**Comment by KayeArray** [comment]
that does buff it though

**Comment by GuyonBroadway** [comment]
Ok so here are some ideas that  would make it a little less revolver 2.0.

Ok first and foremost, make it so you can't backstab a guy who is on the floor, otherwise this means you can stun&stab people faster than they can type "HELP".

Secondly, lower the bonus damage on the antag version to 60. This way if you get stabbed in the back twice you are dead but if you turn around you can take two more hits giving you a chance to get that disarm in and maybe survive.

**Comment by PopNotes** [comment]
>Ok first and foremost, make it so you can't backstab a guy who is on the floor, otherwise this means you can stun&stab people faster than they can type "HELP".

Agree, being able to stab downed people would be shitty, especially with my 'backstab range' suggestion.

>Secondly, lower the bonus damage on the antag version to 60. This way if you get stabbed in the back twice you are dead but if you turn around you can take two more hits giving you a chance to get that disarm in and maybe survive.

Eh. Yeah, sure, why not. If by some miracle this turns out to be too significant of a nerf from the original version, it's a simple change to make it stronk again.

**Comment by KayeArray** [comment]
you can't backstab people on the floor, unconscious people or dead people

Really idk about lowering the bonus damage, it's still reduced by armour and is a really awkward melee attack
, people will probably just ignore it and go for the esword if i do that.

**Comment by KayeArray** [comment]
also backstab does suffer terrible damage falloff up against armour. basic sec armour + jumpsuit reduces it to 48, riot suit reduces it to 32

**Comment by PopNotes** [comment]
Give it more armor penetration, then.

**Comment by GuyonBroadway** [comment]
Giving sec ONE extra hit before death is fine IMO.

**Comment by GuyonBroadway** [comment]
You could stab, stab, step back and throw the knife.

**Comment by PopNotes** [comment]
Oh yeah, and the traitor version should probably have a different inhand sprite to differentiate it from the edagger.

**Comment by KayeArray** [comment]
i would but i suck at inhands

**Comment by PopNotes** [comment]
I know, I'm fantastic

**Review by GuyonBroadway — APPROVED** [review]
Code is ok. Needs headmin approval but right now the code is ok to merge.

**Comment by FuryMcFlurry** [comment]
Please dont make these craftable.  Maybe add them for gang or something.

**Comment by Pyko1** [comment]
Correct me if I'm wrong, but when you have any other intent than help, and you run against people they get pushed and turn towards the dir they are pushed?

**Comment by KayeArray** [comment]
@FuryMcFlurry Not a bad idea if any others have objections
@Pyko1 No dir change from what I see, they just get pushed along.

Also just going to note that me and a friend had a fight with the traitor variant to see how easy it is to get backstabs in the heat of the moment, in a several minute long scuffle in the hallway we probably got about 2 trickstabs between us and several lifetimes worth of damage from just regular stabby stabby.

**Comment by FuryMcFlurry** [comment]
My fear with these being craftable is empowering graytide. They need plasteel and scapel and it will cause shitters to break into medbay or cargo for a scapel, and EVA and engineering for plasteel.

**Comment by calzilla1** [comment]
Make a genuine one for the spy bundle that does 100 damage

**Comment by ghost** [comment]
you can already craft chainsaws that need circular saws and plasteel.
i mean, it's one of those things greytides should steal from medical to do but it's not really a thing?

**Comment by GuyonBroadway** [comment]
I think at worst it will just be some neat toys for bored cargonians.

**Comment by PopNotes** [comment]
also you can print scalpels from an autolathe so


yeah

**Comment by Pyko1** [comment]
Even tho the scalpel makes no sense as a part for this, as you surely you cant mean its the blade for this as scalpel blade is like less than an inch long.

A kitchen knife would make a lot more sense to me.

**Comment by KayeArray** [comment]
I went with the scalpel because the sprite makes the blade look long and pokey

**Comment by KayeArray** [comment]
why was this closed?

**Comment by PopNotes** [comment]
rly tho

**Comment by Carbonhell** [comment]
Shit i thought baw -1ed this
My bad,anyway i don't like this a lot,waiting other heads to voice their opinions

**Comment by ghost** [comment]
im in support of this pretty gimmicky thing, +1

**Comment by GuyonBroadway** [comment]
This has approval from two heads, merging.

**Comment by bardofrage** [comment]
I am in support of it as well, even though it's already being merged, +200

**Pull request merged**
