### PR TITLE
[MIRROR] the correct plasma cutter balance change

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40431
--------------------
:cl:imsxz
balance: plasma cutter blasts no longer have a pressure penalty, but do 1/4 their old damage
/:cl:

Call this an "i ded pls nerf" situation but god damn the only things i've felt more bullshitted by than plasma cutters are the fuckin RNG getting a grenade exploded out of my hand and playing vs unsynced borgs as a rogue AI. Nothing else feels quite as unfair as getting demolished by 15 people all holding 2 advanced plasma cutters, meanwhile the god damn stations actual armory of lethal gear is collecting dust because they're entirely outclassed by cutters against quite a few common threats.

That said, this PR isn't the best change, but neither was tlal's or the other guys. In my opinion, the simplest change that would keep their original purpose(godlike mining tools) while toning down their combat ability would be to just keep their damage really low in general and keep them exclusively made for their mining abilities.

reason kinetic accelerator is fine and not in jeopardy of nerf PR: mostly limited, theres reasonable ways to print more but you cant get them by the hundreds with. 40 brute damage/1.6s with no pressure penalty, 70 brute damage/1.6s generally. Can't be dual wielded effectively.

reason adv cutters are retarded: first mining load can generally print 50-60 adv cutters, more if RND bothered to upgrade anything(most miners end up upgrading their own shit if science doesnt). 28 brute/1s generally, 56/s when dual wielded.

in 3 seconds, an adv cutter can do 168 damage, KA can do 140 at best. Combine this with the fact that you can easily supply every crewmember+crewmembers dog with 2 adv cutters each, shit like blob/xeno(near space most of the time) and other large threat antags that end up getting obliterated by this garbage that they cant even prevent because god knows at least 3 people are dual wielding them already and probably the cargo staff too.

obligatory salty powergamer is mad they cant powergame against this item etc etc 

closes #40383
closes #40324

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
This needs admin aproval.

**Comment by Carbonhell** [comment]
They aren't used enough to pose such a problem. Just merge this and we'll revert if needed.

**Comment by earthmoonjune** [comment]
^

**Comment by Maroonenahmoron** [comment]
Not enough people use plasma cutters outside of mining here... but I can see how much damage they can do, enough to delimb other players. +1

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
