### PR TITLE
Gives nukie reinforcements 25 TC

### PR DESCRIPTION
**Pull request by ghost**
prevents stupid 0 IQ nukie teams from botching themselves because they died 5 minutes in and all the reinforcement has is a pistol and 6 pistol mags.

### CODE REVIEW

**Comment by mememanrino** [comment]
>warops
>buy a reinforcement
>steal his TC, give him a C-20r bundle and tell him to grab a hardsuit (this would cost, all in all, 5 for the reinforcement, then 14 for the bundle. one reinforcement is 19 telecrystals.)
>repeat this four more times, giving you five well-equipped nukies ready to tear ass at the lowly cost of **95 FUCKING TC**
>rush into station and use your companions as hilariously cheap meatshields

**Comment by enthethan** [comment]
change the numbers a bit maybe make the reinforcments cost more or something

**Comment by Manly-Dwarf** [comment]
lol no

**Comment by Manly-Dwarf** [comment]
try letting them select a bundle or something instead, but otherwise merely having another nukie as backup is powerful on its self
also don't edit the no_crystals like that you fuck

**Comment by ghost** [comment]
so basically just make reinforcements spawn with a beacon that can spawn a bundle? like what would the bundles be?

**Comment by Manly-Dwarf** [comment]
the bundles that are already available probably
bulldog bundle?

**Pull request closed without merging**
