### PR TITLE
Makes baseball bats non-conductive

### PR DESCRIPTION
**Pull request by mikolaj007**
## Changelog
:cl: Mideanon
balance: you dont get shocked when hitting powered grilles with baseball bats anymore
/:cl:

## About The Pull Request
Baseball bats are made of wood, not a traditionally conductive material

## Why It's Good For The Game
Gives some reason to do botany in perma brig and it kinda makes sense

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Code looks good, now to wait for admin feedback

**Review by ghost — DISMISSED** [review]
Yep

**Comment by mikolaj007** [comment]
fixed the metal and spiked bat also being non-conductive

**Comment by k-k-karma** [comment]
5 fucking megawatts will certainly go through fucking wood

**Comment by ghost** [comment]
@k-k-karma I'm now grateful I was never on during rounds you were an engineer

**Comment by GuyonBroadway** [comment]
The problem with making it easier to escape perma in this way is that now sec will just execute people.

**Comment by Carbonhell** [comment]
Can't the coefficient be a number between 0 and 1? Maybe set it pretty low but not 0

**Comment by Jujumatic** [comment]
i thought you hated rng @Carbonhell

**Comment by Carbonhell** [comment]
That isn't rng, it would just make the shocks do less damage,or atleast i think so

**Comment by k-k-karma** [comment]
> @k-k-karma I'm now grateful I was never on during rounds you were an engineer

why

**Comment by DeltaFire15** [comment]
Cause thats not how physics work

**Comment by DaydreamPuppeh** [comment]
Electricity can travel through wood if the voltage is high enough

**Comment by Jujumatic** [comment]
Now make the wood crack, splinter and explode with a high enough voltage bc muh immersion

**Comment by ghost** [comment]
@k-k-karma who the fuck dumps 5MW into the wires

**Comment by Pyko1** [comment]
any decent engineer who wires the engine directly to the grid to ensure station and assistants trying to break in are receiving enough power.

**Comment by Jujumatic** [comment]
needs head input

**Comment by Lxtoofonea** [comment]
+1, wood does not conduct electricity. re

**Comment by k-k-karma** [comment]
YES IT DOES 5 FUCKING MEGAWATTS WILL CERTAINLY GO THROUGH PUNY FUCKING WOOD IF IT CAN FUCKING ARC THROUGH AIR WHICH IS ONE OF THE BEST INSULATORS

**Comment by Jujumatic** [comment]
But it won't be able to pass through sawdust aka your brain :gachi:

**Comment by k-k-karma** [comment]
wow.. we've found the perfect insulator you guys!!!!!!!! call nasa quick!!!!!!!!!

**Comment by TheMeatGod** [comment]
Karma is right, air has a higher resistance and less conductivity than wood

**Comment by Jujumatic** [comment]
needs another +1

**Comment by Jujumatic** [comment]
by those means the bat would fuckken explode when it touches the grill then. realism it EXPLODES THE ENTIRE STATION HURR HURRR

**Comment by k-k-karma** [comment]
ok so we cant give any realism to it at all because if we give it full realism it might blow shit up so no realism whatsoever

**Comment by funkynuggets** [comment]
I'd be okay with this if you made it so the bat fucking disintergrated after a couple of hits, just because like gay bb said this would make escaping perma real fuckin trivial

**Comment by Carbonhell** [comment]
Again. Can't the coefficient be a number between 0 and 1?If yes, that would make more sense. -1 to just removing any conductivity.

**Comment by TheMeatGod** [comment]
What carbon said, -1 to removing conductivity entirely

**Comment by earthmoonjune** [comment]
-1 for karma freaking out

and for actual balance i guess

**Comment by DaydreamPuppeh** [comment]
-1

**Comment by yoyobatty** [comment]
Since you didn't amend the changes, this is getting closer.

**Pull request closed without merging**
