### PR TITLE
[MIRROR] Removes the gang gamemode

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/26816
--------------------
Alright, so where do I start with this?
Gang is a gamemode that in theory would add fights between factions, but in practice it's just a rev with a different objective(dominate the station instead of killing the revs).
The mode is not maintained or has improved for the last year, and I honestly doubt it will change anything.

If anything, this mode should be reworked from scratch other than being rev 2.0.

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
**I disagree with this sentiment!!**

**Comment by GuyonBroadway** [comment]
With the Go Ahead from two Headmins and a Game-Master I am closing this PR until further notice.

**Comment by ghost** [comment]
Just to say, players like gangs so we'll keep them. Fuck off /tg/ balance, at least make a fucking changelog entry about removing an entire gamemode too. Not every player is gonna look at the commit history and see the removal of gangs.

**Comment by GuyonBroadway** [comment]
https://github.com/tgstation/tgstation/pull/26816

Gangs needs work for sure but there's lots of good ways to change it up, it's gonna take effort and doing things the lazy way will hurt us later down the line.

**Comment by ghost** [comment]
That being said, it may be a better idea to merge /tg/ content as long as it's functional and rebuild anything we want to keep in the hippiestation folder in order to stay as up to date as possible with /tg/.

**Pull request closed without merging**
