### PR TITLE
star trek redshirts (now with functionality)

### PR DESCRIPTION
**Pull request by Eagle-Eyess**
:cl: EagleEyes
add: redshirts now cause 500% more death. Can you survive a shift with it on?
/:cl:

redshirts in the holodeck now will have more dmg done to the wearer of the shirt.

added challenge to players looking for one

### CODE REVIEW

**Review by Jujumatic — APPROVED** [review]

**Comment by Jujumatic** [comment]
Would be funny if we added some star trek screams to this as well

**Comment by Eagle-Eyess** [comment]
as long as we dont get sued

**Comment by Jujumatic** [comment]
We'd already get sued for calling them trek shirts so lol what's a little more going to do

**Comment by Lxtoofonea** [comment]
+1 i am always for some hard mode

**Comment by Jujumatic** [comment]
needs 1 more vote

**Comment by ghost** [comment]
needs 1 more vote come on...

**Comment by CasualStation** [comment]
+1

**Comment by Majick1** [comment]
+1

**Comment by Manly-Dwarf** [comment]
This should have been merged a long time ago, honestly. +1.

**Comment by mikolaj007** [comment]
the only problem is that stuff removed from holodeck disappears. +1

**Comment by ghost** [comment]
has two head votes so gonna merge

**Pull request merged**
