### PR TITLE
Add guillotine to the game

### PR DESCRIPTION
**Pull request by JohnGinnane**
Doing this again as I made a mistake

The guillotine is now in the game. You buckle someone to it and you can only see their little head. If you interact with it with the harm intent, you will drop the blade after 3 seconds. Any other intent will unbuckle them.

I have put the guillotine in the courtroom and you can unwrench it to move it around. I also added some lights because that room was dark:

image

Pics:
image
image
image

Vids:
https://streamable.com/34nnl
https://streamable.com/cduz6

Clapping:
https://streamable.com/yz55a
https://streamable.com/qakpo

:cl: JohnGinnane
add: A guillotine has been added to the game. If the blade isn't dull, will decapitate humans like a hot knife through butter. Use a whetstone to sharpen it
/:cl:

Credit to Gumner for the sprites

### CODE REVIEW

**Comment by ghost** [comment]
+5

**Comment by 81Denton** [comment]
IT GOES IT GOES IT GOES IT GOES

**Comment by praisenarsie** [comment]
ZIGGO ZIGGO ZIGGO ZIGGO

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
+1 and code seems ok, have you tested it?

**Pull request merged**
