### PR TITLE
Glue (From Bee)

### PR DESCRIPTION
**Pull request by carlopault**
## Changelog
:cl:
add: Superglue bottles can now be purchased from a traitor's uplink under the "devices" category. Superglue is a 1 use thing that makes any item undroppable. Make sure not to use it on an item in your hand.
/:cl:

## About The Pull Request
Purple Package told me to import this

## Why It's Good For The Game
Sticky

### CODE REVIEW

**Comment by byandaccount** [comment]
+1 hell yeah boi

**Comment by MrEpicSax** [comment]
+1 perfect addition. Can't wait to glue 4 shield to my four arms

**Comment by yoyobatty** [comment]
How about you try to make cleaning the item gets rid of the no_drop trait?

**Comment by yoyobatty** [comment]
2tc? Seems a bit strong for something that basically gives no drop

**Comment by carlopault** [comment]
> 2tc? Seems a bit strong for something that basically gives no drop

It is 2tc on bee, do you think it should be 3tc

**Comment by carlopault** [comment]
I'll keep it at 2 tc for now, and wait to see if it is OP. If there is one thing players know how to do, it is complain

**Comment by AnthonyJNgo** [comment]
Wouldn't this be kind of OP with eswords or something similar? I guess you sacrifice stealth if you superglue yourself. Lets test this and see how it goes, we can always change TC amount later.

**Review by AnthonyJNgo — APPROVED** [review]
lgtm wait for @yoyobatty to review also before merge

**Review by yoyobatty — APPROVED** [review]
Not the best code but it works

**Pull request merged**
