### PR TITLE
Revert "Cool see-through portals"

### PR DESCRIPTION
**Pull request by yoyobatty**
Reverts HippieStation/HippieStation#12196

Test-merge only

### CODE REVIEW

**Comment by ghost** [comment]
If this works, I'm going to wear amari like a boot.

**Review by ghost — CHANGES_REQUESTED** [review]
IF YOU'RE CRASHING, GET A FUCKING CRASH DUMP

https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm

**Review by AnthonyJNgo — COMMENTED** [review]
Updating our server software before it was stable was a bad idea, remind me to keep that in mind next time. Being one of the few people on beta hurts my soul.

Code is technically correct.

**Comment by ghost** [comment]
byond bug solved

**Pull request closed without merging**
