### PR TITLE
[MIRROR] Radiation rework and subsystem

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/30909
--------------------
:cl: ninjanomnom
refactor: Radiation has been completely overhauled.
add: A new radiation subsystem and spreading mechanics.
add: Walls and other dense objects insulate you from radiation.
add: Geiger counters now store the last burst of radiation so you can view it at your leisure or show it to someone. Examine it.
add: Geiger counters can check mobs for contaminated objects. Scan yourself before you leave to make sure you aren't carrying dangerous radioactive items.
soundadd: Geiger counters have realistic sounds and the radiation pulse spam in chat has been replaced.
balance: Radiation is more deadly and causes burns at high intensities, WEAR YOUR RADSUITS.
balance: However residue radiation is far slower acting and kills you with toxin.
balance: Engineering holosigns have a light amount of radiation insulation.
balance: Rad collectors are nerfed. No more supercharging with pressurized plasma. No more collector spam either.
balance: Engine output is a lot more stable as a result of collector changes.
balance: Monkeys need more rads and take more time to turn into gorillas.
tweak: Over 100% on the DNA computer means your subject is now taking damage.
/:cl:

The goal of this is to remove snowflake applications of radiation and make it act realistically. With this system radiation can be insulated and it also now obeys the inverse square law. Overall this is a buff to radiation.

TODO:
- [x] Write the basic systems
- [x] Add radiation insulation to various turfs and structures
- [x] Find and convert all snowflake usages of radiation damage
- [x] Finish up radiation contamination
- [x] Reduce resource usage (Might need to do more)
- [x] Fix runtimes
- [ ] Remap supermatter chambers (Will be done when the code is approved)
- [x] Test and balance

Issues:
- [x] ~~The SM gas interactions don't work well with power scaling~~ Fixed with some tweaks
- [x] ~~Contaminated tiles are building up rads when they shouldn't be~~ Bad use of log()
- [x] ~~Figure out exactly why the range gets so high (more insulation maybe?)~~ See above
- [x] ~~The high end is too high and the low end too low for mobs to handle well~~ Rewrote mob rad handling
- [x] ~~Genetics radiation needs to be fixed~~ Rad damage is matched with the others
- [x] ~~Mobs aren't getting toxin damage~~ Bad return

### CODE REVIEW

**Comment by KayeArray** [comment]
it's a doozy

**Comment by GuyonBroadway** [comment]
well it got morrored perfectly its probably just the tgstation.dme

**Comment by KayeArray** [comment]
good jambread

**Review by KayeArray — APPROVED** [review]

**Comment by KayeArray** [comment]
ready to merge? HNNNNNNNNNNNNNNGGGGGGGGGGGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by GuyonBroadway** [comment]
Time to roll traitor RD, use the chasschem uranium and some conveyor belts top make an object irradiation machine and leave radioactive paper all over the station.

**Comment by KayeArray** [comment]
no one saying otherwise so

**Comment by yoyobatty** [comment]
Daaaamn, looks sick, good job!

**Pull request merged**
