### PR TITLE
Nerfs charge time on nanosuit

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
balance: Nerfs nanosuit recharge delay time
fix: Nanosuit charge was not fully draining and his been fixed.
/:cl:

## About The Pull Request
This fix was game breaking.

## Why It's Good For The Game
Nanosuit can recover too fast after doing a move that depletes charge, also decided to nerf EMP recover time to a more fair value.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
I forgot Nanosuit even had charge. Is this necessary?

**Comment by yoyobatty** [comment]
It increases the wait time to start recharging after you do something that uses power. It's a slight nerf for the NS.

**Comment by earthmoonjune** [comment]
+1

**Comment by Lxtoofonea** [comment]
+1

**Comment by DaydreamPuppeh** [comment]
+1

**Review by Jujumatic — APPROVED** [review]

**Pull request merged**
