### PR TITLE
Reduces the price of combat and hazard nanites slightly, and adds adrenaline burst under combat nanites

### PR DESCRIPTION
**Pull request by JF260**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
balance: Slightly reduces combat and hazard nanite prices
add: Adds back "Adrenaline Burst" under combat nanites
/:cl:

## About The Pull Request
I made this pull request because, finally seeing my code in game, i decided it shouldn't take more than a tritium nuke to get combat nanites. I added back adrenals because I don't like wasting code, and it gives combat nanites something other than brutally killing people who contract them. Plus, 2 minute cooldown, so it cant be all that bad. If anyone would like, I could lengthen the cooldown or increase the nanite consumption rate to balance them.

## Why It's Good For The Game
More content, more easily available.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
code is good, need to wait for admeme feedback

**Comment by ghost** [comment]
@JF260 I fucked up and merged your PR accidentally. Can you re-PR this?

**Comment by Carbonhell** [comment]
I don't like adrenaline stuff. It isn't wasted code, it was a bad feature which we don't need. -1

**Comment by DeltaFire15** [comment]
Are they really though? They don't counter that many things, and also cost a fuckton of nanites

**Comment by DeltaFire15** [comment]
Also, how about you fix metabolism nanites and defib nanites first?

**Comment by Jujumatic** [comment]
^^ defib nanites especially, i want a stupid self defib meme please

**Pull request merged**
