### PR TITLE
Add the Interdimensional Sword

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Wizards can now buy the Interdimensional Sword for 3 spellpoints. It sets mobs on fire, crushes walls, rips up pipes, and destroys objects. And looks super cool.
/:cl:

Sprites by @Crysoskis
animation: https://cdn.discordapp.com/attachments/505482538182115329/567810807413342238/output.webm

### CODE REVIEW

**Comment by ghost** [comment]
sword? it's just a vaguely cross shaped shit. Destroys everything with a really small cooldown for it's effect, sounds like some poorly thought out piece of shit honestly

**Comment by ghost** [comment]
@zamolxius i'm trying to get a sprite, calm down. and the cooldowns were suggested by Mideanon.

**Comment by mikolaj007** [comment]
id price it at 2 per level or increase damage.
rod form does *mostly* the same amount of terrain damage but crits people instantly and that costs 3 per level.

**Comment by Manly-Dwarf** [comment]
weaker than fireball because it costs more and has a longer cooldown

**Comment by ghost** [comment]
@Manly-Dwarf yeah but fireball doesn't instantly destroy any object or wall it passes over

and unlike rodform, you can't escape this by resting

**Comment by mikolaj007** [comment]
@steamp0rt 18 damage + burn but 100% hitchance vs crit with 99% hitchance unless they are the robustest mofos around

**Comment by ghost** [comment]
yeah but who gets hit by an off-screen fireball

**Comment by mikolaj007** [comment]
let my try that again:
-Fireball: deals lots of damage, stuns, sets on fire, 6-2 seconds cooldown, 2 cost
-Rod form: destroys lots of shit, crits prople unless they are 100% made of robust, 25-10 seconds cooldown, 3 cost
-Sword: deals 18 damage + fire stacks,  destroys shit really good, 25-10 second cooldown, 3 cost

**Comment by ghost** [comment]
I'm going to buff the sword to give it a 35% chance to dismember a random limb

**Comment by Lxtoofonea** [comment]
might be strong or week, or need some changes but i'm always up for more choices, even if it is a bad choice. Not sure if this will be or not, getting mixed messages from the comments but it seems fine to me.
+1

**Comment by ghost** [comment]
https://cdn.discordapp.com/attachments/505482538182115329/567810807413342238/output.webm

github doesn't support webm :(

**Comment by ghost** [comment]
Peek 2019-04-18 19-10

**Comment by Manly-Dwarf** [comment]
How far is the range of this again

**Comment by ghost** [comment]
@Manly-Dwarf 17 tiles by default, although it can be turned down alot (probably needs to be).

Currently working on a better animation

**Comment by ghost** [comment]
i reduced length to 9. still vareditable, just incase any madlads want to slice the station in half.

**Comment by Carbonhell** [comment]
Sounds too op as it is right now.

**Comment by ghost** [comment]
@Carbonhell what would be needed to make it less op? i'd like to avoid getting rid of the wall/object destroying. plus the new animation made it slightly dodgeable.

**Comment by ghost** [comment]
https://img.steamport.xyz/sword-animation.webm (can't embed webm :( )

**Comment by ghost** [comment]
portal sword

**Comment by ghost** [comment]
also i bumped length back up to 11

**Comment by Manly-Dwarf** [comment]
Seems better now. +1

**Pull request merged**
