### PR TITLE
[MIRROR] Exotic Corgis 2 Electric Boogaloo 

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/39319
--------------------
🆑 Fluffe9911 (Credit to KMC for coding help and cheese20 for the idea!)
add: Exotic Corgi Crate to cargo
add: New type of corgi called Exotic Corgi that has a completely random color
/🆑
Based off this pr https://github.com/tgstation/tgstation/pull/38276
I really liked cheeses idea but since the original pr got reverted decided to redo it so now the exotic corgi is its own type of dog so hopefully it should look slightly less like it ate a crayon also no talking corgi so the maintainers don't get angry hope I did this right!

### CODE REVIEW

**Comment by Carbonhell** [comment]
Whole file conflicts, may require a file reset to tg

**Comment by praisenarsie** [comment]
fuck you oranges

**Review by JohnGinnane — APPROVED** [review]
@Pyko1 some of the changes aren't on tg, did you do some grammar fixes?

**Review by Jujumatic — APPROVED** [review]

**Comment by Jujumatic** [comment]
going to leave this branch open in case anything needs to be changed, everything looked fine to me tho

**Pull request merged**
