### PR TITLE
[MIRROR] Plushie relationships!

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/33184
--------------------
:cl: CosmicScientist
add: You can make plushies kiss one another!
/:cl:

Missed opportunity/inspiration:
#32615
#32918
@ MoreRobustThanYou   ❤️ 
@ optimumtact I did what you said; sought approval from myself and here I lay.

We require more plushies and this is how barring some tribble trouble!

Also corrected one smidge of grammar that triggered me so terribly.

plushie relationship
Who the babby inherits type from should be a 50/50.

I would like to thank MSO and another coderbus denizen, whose name unfortunately escapes me, for making this possible.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
holy fuck

**Comment by GuyonBroadway** [comment]
[Laughter Stops]

**Comment by ghost** [comment]
really no happy skeleton

**Comment by GuyonBroadway** [comment]
On the _plush shide_ we don't have any plusies on our map so this will never be an issue.

**Comment by JohnGinnane** [comment]
I guess we have to add this anyway I think?

**Comment by ghost** [comment]
cucked by tg yet again

**Review by JohnGinnane — APPROVED** [review]
the most reluctant approval

**Pull request merged**
