### PR TITLE
Reverse Bear Trap is now only 1 TC, no longer job exclusive

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Changelogs]: 

:cl: KawaiiBigBoss
tweak: Reverse Bear Trap is now available for everyone, and costs only 1 TC
/:cl:

[why]: Executioner's Sword is the Reverse Bear Trap, except faster, funnier, louder, and for every single job.
This thing should be 0 TC, but Carbonhell got scared.

### CODE REVIEW

**Comment by ghost** [comment]
ye +1 test it out n sheit and is all good

**Comment by ghost** [comment]
image

truly, a man ahead of his time

**Comment by Manly-Dwarf** [comment]
wrestle with git

**Comment by Manly-Dwarf** [comment]
PR works, everything's gucci.

**Comment by Carbonhell** [comment]
+1 merging

**Review by Carbonhell — APPROVED** [review]

**Comment by ghost** [comment]
Your Fix/Feature pull request delta is currently below zero (-1). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
