### PR TITLE
Undos bombs not fitting in bags

### PR DESCRIPTION
**Pull request by ghost**
:cl: McBawbaggings
tweak: Tank Transfer Valves now fit in bags again.
/:cl:

Got asked in coderbus to undo this change and modularise it.
I don't think gating carrying bombs behind Bags of Holding is a great solution to fixing bombs being strong, and also that bombs have always been the peak of power in SS13.
I'd rather see bombs have lower impact on destruction than made more annoying to use.

### CODE REVIEW

**Comment by Pyko1** [comment]
+1

If bombs are an issue I would rather see the explosion size recipe nerfed, so you need to be more exact on cooling/heating/mix to reach bomb cap

**Comment by JohnGinnane** [comment]
do we actually need head input for a change that was kinda forced on us via upstream merge? This is standard play for us..

**Comment by Manly-Dwarf** [comment]
+1 garbage balance that was forced on us via upstream merge

**Review by JohnGinnane — APPROVED** [review]

**Comment by Pyko1** [comment]
Id say we do need head input as anyone could otherwise "revert" any upstream that is not to their liking when others still like it

**Comment by JohnGinnane** [comment]
Hmmmmmmmmmmm I guess so...

**Comment by ghost** [comment]
@Pyko1 issue isn't fixed by making bomb max cap harder to get, since if it's "too strong" then people will figure it out and you're back to square one

if the issue is that they're too strong, make them less strong as babyproofing as it sounds
if they destroy too much, put less TTVs in science so you get less destruction or make the max cap smaller

**Comment by JohnGinnane** [comment]
Still though this is a shit balance because it doesn't suit our server at all, similar to taking more damage when in space

**Comment by Pyko1** [comment]
could prolly even make reaching the bomb cap require upgraded freezers, along with tanks leaking their temp to room slowly.

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
+1

**Comment by ghost** [comment]
+1 I'll allow  you to merge this

**Comment by ghost** [comment]
Your Fix/Feature pull request delta is currently below zero (-1). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
