### PR TITLE
Fix cable cuts + smart cable icons

### PR DESCRIPTION
**Pull request by yoyobatty**
Mirror of:
https://github.com/tgstation/tgstation/pull/45319
https://github.com/tgstation/tgstation/pull/45351
https://github.com/tgstation/tgstation/pull/45352

Read those for changelog, if wanted I can revert the cable sprites.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by diegoxt45** [comment]
gee, another r/tgstation mirror with little to no double checks, watch this PR break the server

**Comment by yoyobatty** [comment]
I did test it, no runtimes, no issues with charging or power flow. I hardly imagine touching cables is going to "break the server" as you've suggested.

**Comment by Manly-Dwarf** [comment]
might be worth mirroring the PR that fixes cables not being eaten to the singulo
still the new sprites look horrible, outline is too thick, I'll look into seeing if I can revert them to the pre-smart cable appearance after this is merged.

**Comment by yoyobatty** [comment]
Be my guest, they don't look that much different than the current ones.

**Comment by yoyobatty** [comment]
Also, this does fix the singulo not eating cables properly.

**Comment by Manly-Dwarf** [comment]
good stuff

**Comment by yoyobatty** [comment]
Closes in favour of: https://github.com/HippieStation/HippieStation/pull/12254

**Pull request closed without merging**
