### PR TITLE
[MIRROR] [Ready] The Virtual Reality Hub

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42879
----------------------------
## About The Pull Request

VR sleepers now lead to the VR Hub, a place with a bunch of portals that lead you to other areas, or just has chill stuff like a bar. Includes portals to all the old vr maps, the megafauna training simulator map, a soon to be minecraft map, and my crappy game runner where you run away from falling tiles and fight to be the last person to survive. Merges murderdome and syndicate trainer into the vr hub map so they spawn every time with vr. Recall portals now can have multiple exits to support the old vr waypoint system from the hub. Also moves a lot of stuff around in the files to make it more organized. There's now also a ghost role that can access VR as well with infinite spawns.

VR NOW HAS A CONFIG OPTION SO ENABLE IT OR VR WILL NOT WORK.

## Why It's Good For The Game

Being a ghost is boring for most people, it's nice to have a place for people to hang out rather than just leave the server. This is also a nice place where people can put gamemodes they're testing or other fun little minigames that can't be main gamemodes. VR currently is not used by really anyone so I don't see anyone getting bothered by this PR as well.

[vr hub vfinal i dont even care anymore whatever (current version showcase)](https://www.youtube.com/watch?v=3E484ekd540&feature=youtu.be)

## Changelog
:cl: Joe Berry
add: The VR hub is now open, VR sleepers now lead to the same main area every time, where you can access all of the VR content from.
add: A VR connection from another station has now opened, ghosts can now access VR as a ghost spawn.
add: A new VR game, runner, run endlessly away from the dark tiles forming behind you and be the last one standing.
tweak: The vr megafauna arena portals now have multiple exits on every corner so you don't spawn on top of a megafauna and die immediately as often now.
config: Added a virtual reality config option to enable or disable the VR hub map.
fix: Wormholes can no longer teleport to every single portal in the game.
/:cl:

### CODE REVIEW

**Comment by Maroonenahmoron** [comment]
To prevent metacommunications with ghosts and players there should be a thing where whoever signs in from the station doesn't have their real name visible for ghost users. Stations users should be able to freely examine each others names otherwise.

**Comment by Majick1** [comment]
+1 more ghost shit besides hotel and adminbus

**Comment by ghost** [comment]
@yoyobatty is there anything special that needs to be done for config changes?

**Review by yoyobatty — APPROVED** [review]
Looks good. I'll update config once it's merged.

**Pull request merged**
