### PR TITLE
Readds Null Crates

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Manly Dwarf
balance: Re-added Null Crates after some discussion.
/:cl:

## Why It's Good For The Game

all right fine
you can have your precious canvas bag

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
So apparently that "caveat" that I was looking for that made nulls less annoying?
That already existed as a var. You could blacklist items from the nullcrates.

Why none of us knew this before, I have no idea. But there, now we can make it so you can't get 50,000 holoparasite e-chainsaw nanosuit ebows.

**Comment by ExpAntique** [comment]
+1

**Comment by sagaty13** [comment]
+1

**Comment by Majick1** [comment]
+1 speedmerge, make cargo great again

**Review by ghost — APPROVED** [review]

**Pull request merged**
