### PR TITLE
Explosion stun rebalance

### PR DESCRIPTION
**Pull request by yoyobatty**
Mirror of: https://github.com/tgstation/tgstation/pull/45819

About The Pull Request
This PR replaces RNG based Unconscious() in /mob/living/carbon/human/ex_act() with Knockdown() that scales with the target's bomb armor.
It also removes a block of reagent explosion code which is superfluous since ex_act() handles the effects already.

EXPLODE_DEVASTATE
Old: 0% to 100% chance for the target to get gibbed instead of taking 500 brute damage. This probability scaled off bomb armor, which means that even with 99 bomb armor you could still get gibbed.
New: Targets with less than 50 bomb armor get gibbed instead of taking 500 brute damage.

EXPLODE_HEAVY
Old: 20% to 100% chance to get KOd for 20 seconds, with the probability scaling off your bomb armor.
New: 2 second KO with a 4 to 20 second knockdown that scales off your bomb armor. The 2 second KO is there so that you can follow up after hitting targets like wizards and ninjas.
Notes: EXPLODE_HEAVY causes 120 combined damage against players with no bomb armor, which sends them into crit. This might be worth adjusting in another PR, as some explosions (like fireball) cause extra damage.

EXPLODE_LIGHT
Old: 0% to 100% chance to get KOd for 16 seconds, with the probability scaling off your bomb armor.
New: A 0 to 16 second knockdown that scales off your bomb armor.

TODO:

 Replace all prob() instances with scaling based on bomb armor
 Scale knockdown off bomb armor
 Add a small amount of Unconscious()
Why It's Good For The Game
Even small explosions render players unconscious for a long time, which leads to them effectively becoming one hit kills. This is only ever fun for the attacker and makes explosives a headache to balance, as seen by the recent mech rocket and fireball rebalances.

Replacing the unconsciousness with knockdown still reduces mobility a bit, but doesn't make every explosion a potential game over.
Removing RNG and replacing it with scaling based on bomb armor also makes for better gameplay IMO.

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
+1

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
+1, explosions are stupidly strong because of the blindstun KO thing

**Comment by GuyonBroadway** [comment]
It's telling that syndie minibombs make more reliable stun grenades than flashbangs did.

**Comment by ghost** [comment]
anyways, I really don't care what head admins think because they're probably going to agree this is a good change.

**Comment by GuyonBroadway** [comment]
This coulda done with a changelog.

**Comment by ghost** [comment]
Think yoyo ported the changelog

**Pull request merged**
