### PR TITLE
Mr. Meeseeks fixes

### PR DESCRIPTION
**Pull request by tortellinitony**
- New icon by @FuryMcFlurry
- Reduced cooldown if a meeseeks is not spawned
- Reduced time for a meeseeks to be polled for from ghosts
- Removed pai restriction from ghosts

### CODE REVIEW

**Comment by FuryMcFlurry** [comment]
oh god no

**Review by GuyonBroadway — APPROVED** [review]
Code is good but this could use a +1 from a head me(seeks)thinks.

**Comment by tortellinitony** [comment]
this doesn't need head input, it's a fix

**Comment by Pyko1** [comment]
new icon is not a fix at least

**Pull request merged**
