### PR TITLE
Sleeping no longer heals you out of crit

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Manly Dwarf
del: hahahah you can no longer heal yourself in crit by sleeping. suckers!!! beg me for mercy!!!
/:cl:

## About The Pull Request
designer opinions do not matter, this is a code oversight

## Why It's Good For The Game
code oversight

merge

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Laughs at #10698

**Review by ghost — APPROVED** [review]

**Comment by enthethan** [comment]
liberals absolutely devastated by this

**Comment by ghost** [comment]
the absolute state of hippie

**Comment by Manly-Dwarf** [comment]
devastated!

**Pull request merged**
