### PR TITLE
Cloning fix

### PR DESCRIPTION
**Pull request by mikolaj007**
## Changelog
:cl: Mideanon
add: AutoCloning is back
/:cl:

## About The Pull Request
autocloning works again

## Why It's Good For The Game
orange man bad

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
i'd really appreciate it if you did like ```// hippie -- edited this``` next to your changes

ik we're supposed to be detached from /tg/ but anyone who thinks that's gonna last is dumb

**Comment by lunaman22** [comment]
oranges is a tranny, spread the word
+1

**Comment by cris5311** [comment]
+1
a retard move to remove it in the first place

**Comment by biggiOS** [comment]
+1
oranges is a tranny, spread the word

**Comment by ExpAntique** [comment]
+1

**Comment by Manly-Dwarf** [comment]
autocloning was a bad feature and this is just a kiefer buff
that said plain removal is for losernerds who sniff turds

+1?

**Comment by Majick1** [comment]
+1 it's already locked behind science upgrades, and I still haven't broken the habit of prescanning myself at roundstart when playing medbay

**Comment by mikolaj007** [comment]
jeez
just realised i fucked up a bunch. gonna fix real quick

**Comment by mikolaj007** [comment]
finally

**Review by ghost — APPROVED** [review]
lgtm i guess

**Comment by Manly-Dwarf** [comment]
time to have indestructible kiefers again

**Pull request merged**
