### PR TITLE
Add 'advanced type locator' circuit

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Added the 'advanced type locator' circuit. It can locate things based on their BYOND type.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Tested. Works as expected.

**Comment by Majick1** [comment]
+1 science man good

**Comment by Carbonhell** [comment]
This is a straight buff from the advanced locator... A bit too OP

**Comment by AnthonyJNgo** [comment]
So you can literally track any item in the game? Yeah, no.

**Comment by ghost** [comment]
@AnthonyJNgo only if it's in view. And on the ground.

**Comment by Hate9** [comment]
@AnthonyJNgo is it really too much to ask to be able to track any item in the game **as long as it's within view and on the ground**? That seems really minor to me.

**Pull request closed without merging**
