### PR TITLE
small ministation update

### PR DESCRIPTION
**Pull request by wheezl**
## Changelog
:cl:
tweak: changed the position of a couple of lights in cargo. some minor qol changes
fix: fixed an issue with the arrival shuttle overlapping part of maintenance
/:cl:

### CODE REVIEW

**Comment by carlopault** [comment]
sounds good to me

**Review by Pyko1 — APPROVED** [review]

**Comment by yoyobatty** [comment]
image

bruh this guy be killing mice

**Comment by carlopault** [comment]
> image
> 
> bruh this guy be killing mice

I think someone mentioned mice spawning too much

**Comment by Pyko1** [comment]
I actually recall that you dont even need to add the mice manually, pretty sure there is a mechanic to random spawn them in maint now.

**Comment by Pyko1** [comment]
https://github.com/HippieStation/HippieStation/commit/f30163b365feeb5bbc0bce5df4b5f069227f080b

**Pull request merged**
