### PR TITLE
Adds boxstation supermatter and port engineering

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: Box station supermatter + atmos hookup
add: Port Engineering which houses our singulo/tesla
del: Removed old singulo/tesla for the supermatter
balance: AI core door is no longer immune to everything but mechs and very high damage weapons.
adds: more air scrubbers and vents in appropriate locations in science
adds: lcass chem pressure chamber and centrifuge in chemistry

/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

I asked and I delivered.

image

image

image

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
is anything here fucking invincible you cheap swine

**Comment by JohnGinnane** [comment]
oh god yes pls i love map changes

**Review by JohnGinnane — DISMISSED** [review]

**Comment by JohnGinnane** [comment]
@yoyobatty did you do this up from scratch or?

**Comment by Pyko1** [comment]
While I do like the map changes, but I recall we had issues with people dragging SM around, you might want to ensure its anchored. Also didn't we actually nerf it to be the smaller shard at some point for some reason?

**Comment by Jujumatic** [comment]
but but i like my tesla :(

**Comment by JohnGinnane** [comment]
tesla is still there, it's moved to port side, see screenshots

**Comment by Jujumatic** [comment]
OHHHHH HELL YEAH 3 ENGINES

**Comment by Jujumatic** [comment]
+999999999999999999999999999999999999999999999999999

**Comment by yoyobatty** [comment]
I fixed that fucking AI door kawaii and I'm 100% sure that the supermatter is anchored. Also yes this was made from scratch using hippiestation 2016 as a reference.

**Comment by praisenarsie** [comment]
@yoyobatty conflicts

**Comment by praisenarsie** [comment]
also now add a teg and antimatter

:^)

**Comment by ghost** [comment]
i like TEG and i find it fun, but i worry people will AI proof atmos roundstart (which isn't allowed) and claim it under the whole "just optimising TEG engine"

antimatter is also kinda fun but stupidly OP so you can instantly fry people by wiring it into the grid without much effort, it's also on par with a supermatter explosion but without the hallucinogenic properties

everything else is coolio though

**Comment by KayeArray** [comment]
this is very good

**Comment by yoyobatty** [comment]
@praisenarsie what is the merge conflict?

**Comment by praisenarsie** [comment]
Conflicting files
_maps/map_files/HippieStation/hippiestation.dmm
fun time map conflicts 4 u

**Comment by praisenarsie** [comment]
@McBawbaggings AME is a maxcap, SME is triple that btw.

**Comment by yoyobatty** [comment]
@maintainer @admin can someone review, please?

**Review by GuyonBroadway — APPROVED** [review]
Well it LOOKS mapmerged so....

**Review by praisenarsie — APPROVED** [review]

**Comment by Pyko1** [comment]
welp, merged with no one even giving support to it...

**Pull request merged**
