### PR TITLE
disables pickup animations

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: 

:cl: zamolxius
fix: disables pickup animations
/:cl:

[why]:   people dont like them

### CODE REVIEW

**Comment by Jujumatic** [comment]
did u tested this

**Review by Jujumatic — APPROVED** [review]

**Comment by ghost** [comment]
yes, tested

**Comment by Carbonhell** [comment]
The people have spoken, +1

**Comment by praisenarsie** [comment]
what are pickup animations

**Comment by ghost** [comment]
pickup animations may really make the game more intuitive for newcomers though, I'm apprehensive on the potential consequences...

**Comment by earthmoonjune** [comment]
+1

**Comment by GuyonBroadway** [comment]
Personally I like idea of pickup animations but would like it if it was much faster.

**Comment by GuyonBroadway** [comment]
Also change the changelog from fix, this is a removal, a much wanted one but code standards damnit.

And don't you fukken give me that "it fixes this shit animation lel" u little shit!

**Comment by praisenarsie** [comment]
ah shit, whatever changelog doesn't matter that much

**Pull request merged**
