### PR TITLE
Adds an ending cinematic after THE SNAP happens

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Adds an ending cinematic after THE SNAP happens
/:cl:

https://cdn.discordapp.com/attachments/617093319209779200/617717058536341504/W2bTyBpyf0.webm

thanos

### CODE REVIEW

**Comment by Majick1** [comment]
+1

**Comment by notoriousBIGGIOS** [comment]
+1

**Comment by AnthonyJNgo** [comment]
Dude, nice.

**Comment by ghost** [comment]
woulda added Mist Furor to the CL, he animated the nuke dusting, but I forgot to ask for his ckey/github name

**Pull request merged**
