### PR TITLE
Nukie reinforcments can now choose a kit upon spawn

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Nukie reinforcments can now choose from several kits upon spawn
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
increase price to 30 TC

**Comment by Manly-Dwarf** [comment]
also give them some shitty nukie spacesuit (NOT hardsuit) so they can still follow the mates

**Comment by ghost** [comment]
i mean, they still can get nukie hardsuits from the ships? i've never seen a roundstart nukie team with 6 nukies in a LONG while.

**Comment by cris5311** [comment]
+1

Seems like a nobrainer that it hasnt been done before

**Comment by enthethan** [comment]
> also give them some shitty nukie spacesuit (NOT hardsuit) so they can still follow the mates

give them the slow syndie space suits not hardsuits

**Comment by ghost** [comment]
@Manly-Dwarf cost increased

**Review by yoyobatty — APPROVED** [review]
Get +1's and I'll merge

**Comment by Manly-Dwarf** [comment]
+1

**Comment by notoriousBIGGIOS** [comment]
approve

**Comment by ExpAntique** [comment]
+1 okay

**Comment by Manly-Dwarf** [comment]
ok

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by MaterialisticThings** [comment]
+1

**Pull request merged**
