### PR TITLE
Readds Blob Gamemode

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
add: Blob gamemode
/:cl:

I know ya'll miss blob!

### CODE REVIEW

**Comment by tortellinitony** [comment]
hell yea

**Comment by ghost** [comment]
yes i tested this, it works

**Comment by ghost** [comment]
"yes i tested this, it works"

famous fucking last words

**Comment by GuyonBroadway** [comment]
Its more checking that Spacedong ever does.

**Comment by ghost** [comment]
don't you need to add it to the config (which hippie can only change)

i mean, i like blob but players ruin blob

**Comment by ghost** [comment]
@McBawbaggings Yes, but this is also adding the gamemode code back

**Comment by ghost** [comment]
@McBawbaggings also it works, as in, I fired it locally, enabled Debug Game, forced blob, enabled blob pref, and force started the game. Guess what, I spawned as a blob

**Comment by ghost** [comment]
are you serious you phaggot, you dont even play the game outside of hoping to become antag and now you want to screw us all over by adding this piece of shit why in gods name

**Comment by ghost** [comment]
@fluxcapacitor1337 i miss the gamemode :(

**Comment by ghost** [comment]
it's better than Abductor **game**mode. Abductors suck when they're a gamemode

**Comment by ghost** [comment]
abductors dont suck, as a matter of fact they need to get fixed as just one operating abductor team is not enough, two teams should spawn as default

**Comment by ghost** [comment]
@fluxcapacitor1337 abductors is a boring ass gamemode

**Comment by ghost** [comment]
DONT ADD THIS GAME MODE

**Comment by ghost** [comment]
remove abductor mode

**Comment by ghost** [comment]
DO NOT ADD BLOBS

**Comment by Spankmaster1066** [comment]
I'm 100% fine with blob as game mode but can we make the occurrence rate like 1/100? We should have stuff like meteor,virus outbreak (GBS and stuff) etc as available round types but just very low rate of occurence.

**Comment by Manly-Dwarf** [comment]
Blob was the shittiest gamemode on the planet.

Nobody ever fought against the Blob because doing so was incredibly boring, and if the Blob reached mid-game it became pretty much unstoppable.

It was removed for a good reason. We don't need more controversial, shitty gamemodes.

**Comment by ghost** [comment]
Like he said, it was removed for a reason. The players just wouldn't gang up together anymore and fight it, so it just lead to really boring rounds where nothing happens and woop suddenly its over because it took a quarter of the station.
Moreover, it snowballs way too easily, and with chemblobs, they could roll a ridiculously powerful chem and kill everything easily, or make it extremely inconvenient trying to fight it.
It's just not fun as a gamemode by itself.

**Comment by JohnMcLaime** [comment]
Stop readding trash gamemodes for git points you bitch

**Comment by Pyko1** [comment]
I see no reason to not add this.

If nothing else it can be made 0 weight so it can be forced if wanted, even with actual weight it should be ok if it was rare enough occurance.

**Comment by tortellinitony** [comment]
yeah we have ragin mages and stuff no reason not to add it

**Comment by Spankmaster1066** [comment]
I hate deleting working pieces of code. We should make blob and other round types like (meteor/disease/monkey) a very low chance. What if we made it in a 1/100 chance, and if it pings it goes through a list of the lesser known/enjoyed round types like the ones I just named and then randomly selects one of them? That way we aren't clogging up the round selections with a lot of them, it's just a tiny chance that one will be selected from a list.

**Comment by ghost** [comment]
spank is correct in saying this and I agree with him

**Comment by KayeArray** [comment]
no it was removed for a reason as a large portion of the playerbases of both servers hate it

i don't see any issue considering it's still a midround antag

**Comment by bardofrage** [comment]
Yeah, blob doesn't really work here.

**Pull request closed without merging**
