### PR TITLE
Adds roundstart bees to botany

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Botany now has roundstart bees.
/:cl:

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by Toxici11i** [comment]
+1 buffs botnis massively

**Comment by wheezl** [comment]
+1, merge it

**Comment by ghost** [comment]
speedmerge

**Review by ghost — APPROVED** [review]

**Comment by xTrainx** [comment]
-5/10, you ruined botany forever

**Pull request merged**
