### PR TITLE
Adds a nebula background to parallax

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
add: Added a nebula background to space
/:cl:

## About The Pull Request
What the title says
dreamseeker_3LUDYAaGWK

## Why It's Good For The Game
Fancy effects add immersion.

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
+3 when are you adding the eye of terror

**Comment by Zyzarda** [comment]
+2 badass

**Comment by karmaisblackandbluepilled** [comment]
wait actually how would you add new layers?

**Comment by yoyobatty** [comment]
see code

**Comment by karmaisblackandbluepilled** [comment]
i looked at it before i asked this, i just don't understando it

**Comment by earthmoonjune** [comment]
+1

**Review by Neotwr — APPROVED** [review]

**Pull request merged**
