### PR TITLE
Makes the thanos wardec sound more noice.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: Guyonbroadway
soundadd: SNAP.... Noice
/:cl:

## Why It's Good For The Game
It's pretty noice.

### CODE REVIEW

**Comment by ghost** [comment]
very based

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by mikolaj007** [comment]
what's the difference between this one and the one we already have?

**Comment by GuyonBroadway** [comment]
Listen right to the end of the new one and all will become clear

**Comment by mikolaj007** [comment]
well, i don't really see why/why not, so im just gonna do a chad move known as +0

**Review by ghost — APPROVED** [review]
fuck it

**Comment by GuyonBroadway** [comment]
_noice_

**Pull request merged**
