### PR TITLE
Hazard and military nanites cost and path change

### PR DESCRIPTION
**Pull request by WarRage333**
I did a test run, you can unlock military around minute 19 and hazard around minute 22~ if you don't research anything else but go straight for this.

## Changelog

:cl:

balance: Hazard and Military nanites now require advanced weaponry node before they can be researched, but their price was reduced.

/:cl:

## Why It's Good For The Game

It's actually usable now.
Hazard is kinda iffy with mind control but i say test it and see what happens.

### CODE REVIEW

**Comment by bigbluebeaker** [comment]
+1

**Comment by mikolaj007** [comment]
+1

**Comment by ghost** [comment]
As someone who is somewhat familiar with nanites, +1. None of this is strong enough to be locked behind Ayy tech.

**Comment by Majick1** [comment]
+1

**Comment by AnthonyJNgo** [comment]
+1 will label for Batty to review, then merge.

**Review by yoyobatty — DISMISSED** [review]

**Review by yoyobatty — DISMISSED** [review]

**Review by yoyobatty — APPROVED** [review]

**Comment by ghost** [comment]
The check passes, the error is something to do with artefact sizes

**Pull request merged**
