### PR TITLE
Adds autosurgeon to protolathe

### PR DESCRIPTION
**Pull request by xTrainx**
[Changelogs]: 
add:Adds autosurgeon to the protolathe, requiring biological technology 7, engineering 5, magnets 5, and programming 5, so its very advanced, also requires a lot of metal, and some silver
[why]: theres never any surgeon ready to give you some of the more advanced implants, so you need to metabuddy up with someone for that kind of thing.

### CODE REVIEW

**Review by KayeArray — CHANGES_REQUESTED** [review]
This needs to be modular

**Review by KayeArray — DISMISSED** [review]
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

**Comment by ghost** [comment]
No.

**Comment by KayeArray** [comment]
You need to uninclude the other file still.

**Review by ghost — APPROVED** [review]
Code is good

**Comment by doobiedoo23** [comment]
no

**Comment by tortellinitony** [comment]
I wouldn't mind this

**Comment by KayeArray** [comment]
-1 Sci don't need more buff and this is just an unnecessary addition for lazy nerds who can't be bothered to insert their own bullshit implants themselves.

**Comment by ghost** [comment]
@banthebantz you do realize, with self surgery, ONE implant can take 5+ minutes if you're unlucky, right?

**Comment by ghost** [comment]
No.

**Pull request closed without merging**
