### PR TITLE
Vampires can't succ the chaplain anymore

### PR DESCRIPTION
**Pull request by ghost**
:cl:
balance: The chaplain's blood is holy poison to a vampire!
/:cl:

### CODE REVIEW

**Comment by Majick1** [comment]
Would this be transferred to anyone who gets mutated into the chaplain, can see this cucking vamp pretty hard if so

**Comment by ghost** [comment]
It'll affect anyone who is holy -- aka if they're immune to spells, they'll also cuck vamps

**Comment by Manly-Dwarf** [comment]
chaplain is becoming the job that you pick if you just want immunity to some antagonists
I wish he had something to do other than hope admins will read prayers, and not blow him up.

**Comment by sagaty13** [comment]
-1 stop giving chaplain buffs hes already immune to lots of shit
I agree with dwarf, and whenever I pray a gimmick admins blow me up or call me a gay nerd that wants to roleplay, like what the fuck

**Comment by cris5311** [comment]
-1

**Comment by AnthonyJNgo** [comment]
-1, and also KBB I am working on a chaplain rework.

**Pull request closed without merging**
