### PR TITLE
Lowers the point cost of Time Erasure

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: Time Erasure only costs 4 points now.
/:cl:

Why did this cost 6 points?!

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
-1 lmao it's op as shit

**Comment by ghost** [comment]
@karmaisblackandbluepilled how?

**Comment by Manly-Dwarf** [comment]
it costs 6 points because it can save your ass pretty reliably

**Comment by ErwinSnowden** [comment]
> it costs 6 points because it can save your ass pretty reliably

Almost all of the good stand abilities can do the same thing, I believe explosive has retained its explosive punches, if it hasn't, it still has the ability to make the door you just went through into a bomb that can instacrit your foe. This ability is useless when cuffed and can only be used for sneaking up on people and evasion. Also it's very limited unlike the other abilities where it has a cooldown of 60-120 seconds depending on potential iirc. Frenzy can make you impossible to hit and superspeedy for any evasion, yet it's one of the cheaper abilities.

**Comment by diegoxt45** [comment]
-1 time erasure is really good, if you want to buff it make it 5 points

**Comment by Toxici11i** [comment]
+1 lol, time erasure is the worst standtype

**Comment by Toxici11i** [comment]
Im going to quantify my above comment, time erasure is literal shit. it provides little to no advantage other than creating two very obvious fakes (examine) and clicking, and allowing you to move, invisible at normal speeds. That is not the best of le epic stands. Having it 4 points would be fine. Explosive also massively outclasses any other standtype, maybe except healing, abso and pocket dim. This is because you can put the explosive on a soap, slip somebody on it and instantly kill them

**Comment by ErwinSnowden** [comment]
why was this closed? give Time Erasure premonition of events then.

**Comment by diegoxt45** [comment]
> Im going to quantify my above comment, time erasure is literal shit. it provides little to no advantage other than creating two very obvious fakes (examine) and clicking, and allowing you to move, invisible at normal speeds. That is not the best of le epic stands. Having it 4 points would be fine. Explosive also massively outclasses any other standtype, maybe except healing, abso and pocket dim. This is because you can put the explosive on a soap, slip somebody on it and instantly kill them

are you actually braindead

**Comment by Manly-Dwarf** [comment]
this hasn't gone anywhere in over a month. closing.

**Pull request closed without merging**
