### PR TITLE
[MIRROR] Gibs now rot and generate miasma

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/41782
----------------------------
:cl: coiax
add: Gibs will now rot if not cleaned, and produce small amounts of miasma, approximately
equal to a quarter of a corpse.
/:cl:

Miasma is fun. Gives the janitor more of a reason to do work. It will only become
dangerous if you have a lot of gibs in a small space. So better keep those Hopline shutters
open.

### CODE REVIEW

**Comment by Jujumatic** [comment]
next step dwarves

**Comment by danhibiki** [comment]
So if I’m a botanist and I spam blood tomatoes, am I now valid because it degenerates into miasma?

**Comment by JohnMcLaime** [comment]
Change of plans, we valid hibiki.

What does miasma do though?

**Comment by Maroonenahmoron** [comment]
A disgusting but fresh idea. Make them different from fresh gibs though. +1

**Comment by ghost** [comment]
miasma stinks and has a chance to make you sick with minor diseases @johnmclaime

**Comment by TheMeatGod** [comment]
Interesting, +1

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
