### PR TITLE
Lowers rev player requirement from 30 to 18

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
tweak: Rev pop requirement has been reduced to 18 players
/:cl:

## About The Pull Request
We rarely if not never see about 30 players, I feel like 18 is a very fair number.

## Why It's Good For The Game
Allows this gamemode to actually be rolled and encourages some tension and hostile rounds now and then.

### CODE REVIEW

**Comment by carlopault** [comment]
+1

**Comment by mkikt4743** [comment]
yeah

**Comment by cris5311** [comment]
+1
rev is fun

**Comment by carlopault** [comment]
+1 again because I can

**Comment by MrEpicSax** [comment]
+1 a very chad move

**Comment by Maroonenahmoron** [comment]
+1, as long as there's like 3-4 heads as a perquisite

**Comment by Punkinguy** [comment]
+1 last time ive played rev was last year

**Comment by yoyobatty** [comment]
Recommended enemies is 3 so should fit the boot.

**Review by Neotwr — APPROVED** [review]

**Pull request merged**
