### PR TITLE
Fixed corazone, made lacking a heart give you a heart attack under most circumstances

### PR DESCRIPTION
**Pull request by Jujumatic**
I'm not exactly sure why this isn't a thing, I swear it was a thing in the past. Both here and on TG, removing your heart had no consequences. This will make a heart pretty much as essential as a liver or brain, as it *should* be. On top of this I fixed corazone so that it actually functions correctly.

:cl:
add: Not having a heart now means you will instantly have a heart attack, unless you meet special conditions
fix: Fixed corazone, it should correctly stop heart and liver failure correctly now
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
cant wait to grab an innocent little clown and rip his heart out on ian's bed in church to please the administration automobile God

**Comment by Jujumatic** [comment]
i love travis freaking out for no reason

**Comment by Carbonhell** [comment]
is this an issue only related to us or does tg also have it?

**Comment by Carbonhell** [comment]
?

**Comment by Cyprex** [comment]
Also affects tg, fixed by https://github.com/tgstation/tgstation/pull/38828

**Comment by Carbonhell** [comment]
Thank you @Cyprex 
Closing this one then

**Pull request closed without merging**
