### PR TITLE
You can now interact with assemblies without removing them

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: You can now interact with circuits in assemblies without removing them, from the assembly menu
/:cl:

good for mmi tanks

### CODE REVIEW

**Comment by ghost** [comment]
Tested, it works.

**Comment by Lxtoofonea** [comment]
+1

**Comment by Carbonhell** [comment]
I swear i remember someone implementing this already, weird

**Comment by Carbonhell** [comment]
@shdorsh wasn't this implemented already anyhow by you? Or am i getting confused

**Comment by Carbonhell** [comment]
Anyway +1

**Comment by Shdorsh** [comment]
You know, the modularization was quite messy and it broke a few things, so we need to watch out for a few bugs here and there that sneaked in. Gets a +1 from me.

**Comment by Shdorsh** [comment]
Also, atmos mixers seem to have a problem that I'll need to unbug, but I'm currently waiting for my other PRs to be done, don't want to have too many things going on at once.

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
