### PR TITLE
[MIRROR] Mi-go

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/33050
--------------------
:cl: Armhulen
add: Mi-go have entered your realm!
/:cl:

Creatures are now a netherworld inhabitant, but that's just pathing.

 ### MI-GO!
First created by HP Lovecraft and perfected in CDDA, they are crustation alien mimics! obtainable through xenobio at the moment but I may have plans for them later. They mimic noises of all kinds, most of them are just honking, gas, glass, et cet. Some of them might really scare you though, one being a dimension tear. But those are really rare, promise.

### CODE REVIEW

**Comment by praisenarsie** [comment]
DNM this, license is possibly incompatible and is possibly get reverted upstream

edit: sprite's license is possibly incompatible

**Comment by KayeArray** [comment]
lol wtf

**Comment by praisenarsie** [comment]
alright, /tg/ just has to credit them somewhere and it's fine

**Comment by praisenarsie** [comment]
alright, /tg/ just has to credit them somewhere and it's fine

**Pull request closed without merging**
