### PR TITLE
[DNM] Revert "[MIRROR] Revert "Bandaid for the TGS4 Linux trusted mode bug""

### PR DESCRIPTION
**Pull request by Carbonhell**
Reverts HippieStation/HippieStation#10789
Probably the cause of the end round crashes. DNM, i am testmerging it till we find a reliable solution

### CODE REVIEW

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: c7d6d37d87b1b2330c111237f1fd9fc818059036
Pull Request: cb601095ec1bb0db84555186e59b1e1be2792353
Server: 4cc6f14935298e13fb586a26f936e320d7017c10

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: c7d6d37d87b1b2330c111237f1fd9fc818059036
Pull Request: cb601095ec1bb0db84555186e59b1e1be2792353
Server: ef86ca96796b68614221f9df6598ea4e77dc3f6b

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 0a67a687965fba62f35c06231ed718ba0d31b70b
Pull Request: cb601095ec1bb0db84555186e59b1e1be2792353
Server: 15918a6e72a74a55f63f06eeb315717a007963be

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 0c237a34ba86826e4a1365e34b536e6212e15ff3
Pull Request: cb601095ec1bb0db84555186e59b1e1be2792353
Server: 8aeff8d3ee62a5c9ffe970d822653e7e7ed24b1a

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 0c237a34ba86826e4a1365e34b536e6212e15ff3
Pull Request: cb601095ec1bb0db84555186e59b1e1be2792353
Server: 9a44baaae7a31428dbec15fd4ee8c0e17aa1d28c

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: bd7002772d5d5029693459f827752c6bd87b1a5d
Pull Request: cb601095ec1bb0db84555186e59b1e1be2792353
Server: 2166617efc87d15ba130b78fece5200a24aef243

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: bd7002772d5d5029693459f827752c6bd87b1a5d
Pull Request: cb601095ec1bb0db84555186e59b1e1be2792353
Server: 5c66b216a240b09c2d0e57e47c0e465e747fc791

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: e9916481127cd239a63ebef6844fd5d03643e45a
Pull Request: cb601095ec1bb0db84555186e59b1e1be2792353
Server: d8dfa6f8f35fa464932cdee5ed1b07bf2cb5e724

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by Carbonhell** [comment]
who tf removed it

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: afbb8bd515e7d0a3519938639e834328f1f23c68
Pull Request: cb601095ec1bb0db84555186e59b1e1be2792353
Server: a9a72e32fb087d956ecb5cbc80fbf92402a4d852

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by Carbonhell** [comment]
Gonna just merge this, and revert when it isn't needed anymore.

**Pull request merged**
