### PR TITLE
reworks and enables fusion

### PR DESCRIPTION
**Pull request by KayeArray**
:cl: banthebantz & as334 
add: Reworked and re enabled plasmic fusion, have fun atmos techs!

/:cl:

[why]: it was a fun little project for atmosians that got removed because it kept breaking everything or something, now it should be harder to do but more interesting when you do it and stuff.

tell me if this needs to be modularised or not, I decided not to because it's technically just a change of an already existing thing and idk how this works yet

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Yes it needs to be modularized so that if /tg/ ever change the same file we don't get conflicts.

**Comment by tortellinitony** [comment]
Can you please explain what this is and what it does?

**Comment by KayeArray** [comment]
pump enough thermal energy jobbers into a mix of plasma and carbon dioxide of a purity equal to or exceeding 90% and fuse it into nitrogen and oxygen generating large quantities of thermal energy and radiation.




it's for atmos techs

**Comment by tortellinitony** [comment]
OK, and please explain how this affects bomb making and the turbine engine. I assume you have tested it?

**Comment by KayeArray** [comment]
bomb making it likely doesn't affect too much because thermal energy scales with the amount of gas you have so even a super hot tank mix is unlikely to spontaneously fuse without exploding first. 

fusion could present interesting prospects for skilled bomb makers I'm sure

turbine engine it affects it positively if someone goes through the effort of setting this up, it works better with rad collectors though

**Comment by KayeArray** [comment]
need to modularirairsarz

**Pull request closed without merging**
