### PR TITLE
MetaLake: MetaStation for hippie

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
add: The MetaLake map
/:cl:

basically it's MetaStation, except it has lcasschem shit and a pool

lcass
pool
bar 
bar
maintchem

### CODE REVIEW

**Comment by calzilla1** [comment]
F R E E Z E

**Comment by ghost** [comment]
this is a new map, not new code

**Comment by praisenarsie** [comment]
still should be closed, i thought you knew what a freeze was.

**Comment by ghost** [comment]
@MoreRobustThanYou You need to remake this PR, your commit history is completely fucked up.

**Comment by ghost** [comment]
@Chnkr Actually, I think this is the only PR without a fucked up commit history
capture

**Comment by ghost** [comment]
but yeah @Chnkr this one has a clean git history

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Stale and Merge conflicts

**Pull request closed without merging**
