### PR TITLE
[MIRROR] [READY]MultiZ stuff - tile atmos, movement backend, falling backend, etc etc - Electric boogaloo

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40428
----------------------------
- [x] Basic multiZ mob movement procs (Observers can always move)
- [x] Open space, showing what things are below it, and everything that entails. No complex support for dynamic generation just yet.
- [x] Decide how openspace should look :/
- [x] Atoms falling through open space (NO MOB SUPPORT/DAMAGE/ANYTHING YET.)

//CANCELLED FOR ANOTHER PR - [ ] Being able to see upwards? Downwards is going to be handled by open space.
- [x] MultiZ tile atmospherics - EDIT: Working demo! https://puu.sh/B7mUs/3f6274740f.mp4
- [x] Bugtest the heck out of this trainwreck.

### CODE REVIEW

**Comment by silicons** [comment]
Hey guys, besure to fix my fuckup where I ticked forcemap multiz debug!

**Comment by ghost** [comment]
thanks dude

**Comment by k-k-karma** [comment]
no it'll be funny

**Comment by ghost** [comment]
YOU IDIOT THAT'S NOT WHAT YOU WERE SUPPOSED TO DO @k-k-karma

**Comment by yoyobatty** [comment]
File content got duplicated a bunch

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
