### PR TITLE
update permissions

### PR DESCRIPTION
**Pull request by Atlas48**
makes the file like every other in the folder

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
tweak: Updated file permissions, every other file in the directory apart from this one has the same permissions, this bugged me, so I changed it.
/:cl:

## Why It's Good For The Game
Makes it ever so slightly less annoying to work in the directory.

### CODE REVIEW

**Comment by yoyobatty** [comment]
Who the fuck is this weeb?

**Comment by ghost** [comment]
image

what the hell

**Comment by Atlas48** [comment]
every other file had those `100644`, that one didn't, so I changed it.

**Comment by ghost** [comment]
@steamp0rt why the hell did you close this I thought you merged it

**Review by ghost — APPROVED** [review]

**Pull request merged**
