### PR TITLE
[MIRROR] Adds meat donuts

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40145
--------------------
:cl:
add: NTs crack archeo-gastronomers have discovered a long lost recipe for a meat based donut.
/:cl:

You thought it was delicious puff pastry. BUT IT WAS I, MEATO, who entered your lips.

### CODE REVIEW

**Comment by ghost** [comment]
-1

**Review by ghost — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
@steamp0rt your -1 is worthless here.

**Comment by ghost** [comment]
@GuyonBroadway  i don't care this is heresy

**Comment by Carbonhell** [comment]
Disgusting... But i do not like donuts either so

**Review by Carbonhell — APPROVED** [review]

**Comment by Kawaii-Big-Boss** [comment]
lol I didn't actually get gitmuted you nerds I'm just deleting my comments really fast

**Pull request merged**
