### PR TITLE
Adds FIST!!

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
add: Wizards who lift can now cast FIST. Punch someone so hard they fly back and explode if they hit a wall, and even more if they hit another person.
/:cl:

FIST
I
S
T

### CODE REVIEW

**Comment by ghost** [comment]
i cast **_fist_** +1

**Review by JohnGinnane — DISMISSED** [review]
🆒

**Comment by JohnGinnane** [comment]
Fixed the conflict caused by my crossbow

**Review by JohnGinnane — APPROVED** [review]
Still 🆒

**Comment by KayeArray** [comment]
+1

**Comment by ghost** [comment]
Same as the old PR, my opinion hasn't changed
+1

**Comment by JohnGinnane** [comment]
Just need one more vote

**Comment by Spankmaster1066** [comment]
This has 3 +1's, merge it

**Pull request merged**
