### PR TITLE
Gulag Gourmet

### LINKED ISSUE #9591: gulag food is disgusting and makes you puke continously, cant even feed
[Round ID]: # (If you discovered this issue from playing HippieStation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**) 32548
[Round ID]: # (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

### PR DESCRIPTION
**Pull request by ProtozoaPrime**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Added old and rusted variant of beans to sustenance vendor
add: Added some disgusting chips to sustenance vendor
imageadd: added oldbeans sprite to hippiestation/icons/obj/food/food.dmi
imageadd: added prisonchips sprite to hippiestation/icons/obj/food/food.dmi
/:cl:

## About The Pull Request
Food for da hungry, hungry boys in the gulag that won't make them immediately throw up.
 
Resolves #9591 

## Why It's Good For The Game
More food is pretty epic, plus I put a reference in there too. Also starving prisoners, while hilarious and realistic, doesn't make for a fun experience. Because we all know how much we hate the eternal pain of  **walking slowly**.

### CODE REVIEW

**Comment by ghost** [comment]
I want to -1 just because the actual fix for this is to remove the taste system altogether.

**Review by AnthonyJNgo — APPROVED** [review]
Code looks good, needs some more votes before merge.

**Comment by AnthonyJNgo** [comment]
+3 from myself, good submission.

**Comment by carlopault** [comment]
+1 when do we add poo and pee

**Pull request merged**
