### PR TITLE
Brings back mutagen nerf

### PR DESCRIPTION
**Pull request by tortellinitony**
Removes ability to provide hulk and dwarf.

### CODE REVIEW

**Comment by KayeArray** [comment]
why dorf?

**Comment by ghost** [comment]
Pretty sure dwarf provides an additional strength boost.

**Comment by KayeArray** [comment]
Uhhhh no it doesn't, mutagen vape is completely nonviable once you remove hulk so just leave it at that, no need for an additional check for dwarfism.

**Review by ghost — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
Mutagen vaping for powers is dumb anyway. A ghetto version of doing a thing should not be easier than doing it the right way.

**Pull request merged**
