### PR TITLE
[MIRROR] [READY] Making corpses rot and create miasma

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/39735
--------------------
[Changelogs]: # Soooo, I added a gas named miasma, which comes from rotting corpses, hoping to give atmos and virology a little bit more depth. It has a tiny chance to create a pretty non-hostile disease. If you want to bargain, I can set the chance even lower so it doesn't occur too much.

:cl: Shdorsh
add: A gas named miasma, that has a ridiculously low chance of infecting people with a very basic and benign disease
add: A gas reaction to remove miasma
tweak: Corpses emit a gas named miasma
tweak: Air alarms detect and automatically are set to scrub miasma
/:cl:

[why]: # Giving a little bit more depth to both atmos and viro, especially giving viro an incentive to work on vaccines for diseases and corpses to be either cloned earlier or removed/ stored properly in morgue/coffins/body bags or just plain burned.

Here's the gif: 
miasmanew

### CODE REVIEW

**Comment by Shdorsh** [comment]
glad to see this in here

**Comment by GuyonBroadway** [comment]
Gonna need some admin input methinks.

**Comment by Shdorsh** [comment]
Yeah, it is a somewhat big change in game mechanics after all.

**Comment by Eagle-Eyess** [comment]
I don’t think this is a very good change for hippie. Dead bodies is too common which will lead to more cremated bodies permanently killing dudes... -1

**Comment by GuyonBroadway** [comment]
Eagle "If they start to smell they can burn in hell" Eyes

**Comment by Shdorsh** [comment]
To its defence, last time I locked myself up in cloning with like 10 bodies or so, I'd not even get enough to smell it, but it did make me slightly sick after waiting long enough.

**Comment by ghost** [comment]
yeah, most people won't have access to cremator and will either space it or put it in a locker somewhere

**Comment by ghost** [comment]
can you also make the rotting corpses emanate a transparent purple smoke that lasts like 1 minute?

**Comment by Shdorsh** [comment]
wouldn't that be a little bit too extreme?

**Comment by Shdorsh** [comment]
i already forgot about the idea to make zombies produce miasma, as it would just needlessly buff them

**Comment by ghost** [comment]
we don't run moodlets so the disgust factor of miasma does nothing pretty much

**Comment by Shdorsh** [comment]
Huh, seems like it'll be pretty negligeable aside from maybe that one or other occasional disease.

**Comment by ghost** [comment]
worst case scenario, we can override `rot()` to just `return` so bodies don't decompose
that way we shouldn't have broken gases that /tg/ expand upon

**Comment by Shdorsh** [comment]
Wouldn't that make miasma entirely ungettable and therefore the pr pmuch uselss except for adminbus purposes? The idea was to give atmos and viro a little bit more depth after all.

**Comment by ghost** [comment]
yes it would, but it would be a way to disable a feature if the headmins don't want it without breaking /tg/ compatibility over it
frankly this PR doesn't really have much impact if we don't run moodlets outside of disease anyway so i don't think it will be an issue

**Comment by ghost** [comment]
does try_to_infect check for bio resist? would this make bio gear actually viable for medical to deal with bodies to contain disease?

**Comment by Shdorsh** [comment]
Yeah, it does check. In the original PR I was asked to change to try_infect(), as it takes that into account.

Still, the best defense to miasma is just to not breathe it in and use internals.

**Comment by ghost** [comment]
-1

**Comment by ghost** [comment]
just pile em all in one morgue tray, it's not that hard.

**Comment by Carbonhell** [comment]
I dont get the hate behind this. tg blasted it already anyway, I think it would make no difference even if it gets inside.
+1, i guess

**Comment by Manly-Dwarf** [comment]
dear god no, why
I like the idea of rotting bodies and whatnot and giving medical doctors or the janitor more incentive but please no stop what are you doing

**Comment by GuyonBroadway** [comment]
I dunno, maybe people will drag bodies to the mourge now as opposed to leaving them in the hallway.

Also means you could find bodies hidden in maint if you just follow your nose.

**Comment by Shdorsh** [comment]
We can always try it out for a few rounds and see how it impacts gameplay. That way we're sure it doesn't do crazy stuff.

**Comment by Carbonhell** [comment]
Honestly, let's just get this in. If it's shit,it takes two lines to disable. We need feedback, it's an entirely new system which needs testing.

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
