### PR TITLE
[MIRROR] Repaths /obj/item/weapon to /obj/item

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/29929
--------------------
Crappy bloat typepath with literally 1 var and 1 override that should probably be on /item. Merges items.dmi and weapons.dmi

`git grep -l "obj/item/weapon/" | xargs sed -i -b 's/obj\/item\/weapon\//obj\/item\//g'`

### CODE REVIEW

**Comment by PopNotes** [comment]
oh boy here come infinite conflicts

**Comment by KayeArray** [comment]
yep this is a shitstorm

**Comment by ghost** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Pyko1** [comment]
cant we like just close this and do what he did?

**Comment by Pyko1** [comment]
and then rinse and repeat on hippie modules

**Comment by Cyberboss** [comment]
That's honestly for the best

**Comment by GuyonBroadway** [comment]
@Cyberboss If you have the time I'd like to know how you did this so I can try it for myself.

Was it as simple as entering that command into git command line?

**Comment by Cyberboss** [comment]
Yes it was

**Comment by Cyberboss** [comment]
After that, just clean it up to compile

**Comment by GuyonBroadway** [comment]
Whelp, hold mah beer cus here fukken goes.

**Comment by ghost** [comment]
hold on guyon, do we have any open PRs that do anything with obj/weapon classes or anything?
it'd probably be better to merge those PRs first then do the big thing

**Comment by GuyonBroadway** [comment]
As far as I am aware we actuall have no hippie based PR's going at the moment, and any /tg/ upstream pr's either account for this or can be fixed via web editor.

**Comment by ghost** [comment]
aight coolio

**Comment by GuyonBroadway** [comment]
@Cyberboss One more thing regarding the icon files, did you use another console command for that? Cus I see /tg/ merged the item and weapon icon files and I didn't see it explained in the pr.

**Comment by Cyberboss** [comment]
Right, that was a bit more involved. I used dmitool's merge function with an empty base dmi (needs 1 junk icon_state because dmi memes). The command was `java -jar empty.dmi items.dmi weapons.dmi items_and_weapons.dmi`

**Comment by Cyberboss** [comment]
Also did a find replace in the codebase for all references to the old icons and switched it to the new icon

**Pull request closed without merging**
