### PR TITLE
[MIRROR] Replaced body zone magic strings with defines

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/36507
--------------------

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Oh god...

**Comment by Manly-Dwarf** [comment]
DO NOT MERGE OH CHRIST

**Comment by GuyonBroadway** [comment]
we're going to have to fix this at some point... Hooo boy.

**Comment by JohnGinnane** [comment]
I can use regex to fix later

**Comment by JohnGinnane** [comment]
oh man I hope this doesn't actually mess up the other files considering how many this changes

**Comment by JohnGinnane** [comment]
Gonna do a separate PR after this, to apply the same changes to our files because I think we should make use of this

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
