### PR TITLE
Floor cluwne bug fixes

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
tweak: Fixed floor cluwne disappearing when you're in a closet, it now busts open said closet and stuns you.
balance: Floor cluwne drags it's victim at twice the previous rate.
fix: Fixed floor cluwnes breaking when you dragged their victims away
fix: Fixed floor cluwnes not paralyzing you when attacking.
fix: Fixed floor cluwnes having the hole in floor animation loop forever.
fix: Fixed cluwning not working.
fix: Fixed clientless floor cluwne victims not properly being eaten when dragged underneath the floor.
fix: Fixed floor cluwne making your HUD red permanently.
/:cl:

[why]: All of these things mentioned in the changelogs were causing severe quality of life issues for floor cluwne. Outdated code is also a factor here, so I hope I caught everything from observing and playing around with them on the server. The hiding in locker to avoid capture was also an annoying factor that made the victim easily able to avoid their inevitable capture by one of these. That being said I'd also like to mention that you can still go into space or off station to escape which is intended. The dragging speed increase was simply because the previous speed was painfully slow and not quite as dramatic. I wanted to avoid turning this into a balance thing as much as I could but then the PR wouldn't have been as effective in resolving all of its major issues and annoyances.

### CODE REVIEW

**Comment by G-erma** [comment]
is the floor cluwne like the "???" Cluwne mask thing that spawns and in spams earrape while breaking everything and spreading lube?

**Comment by Manly-Dwarf** [comment]
+1

**Comment by fluffe9911** [comment]
You sir are a saint!

**Comment by yobob591** [comment]
+1 honks of hell

**Comment by Maroonenahmoron** [comment]
Fix floor cluwne. +1

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by Carbonhell** [comment]
Yeah sure +1

**Comment by TheMeatGod** [comment]
Fuck yeah +1

**Comment by fluffe9911** [comment]
I would make the message for when its dragging you out of the closet ...edih tnac uoY by the way since thats one of its things is that it speaks backwards

**Pull request merged**
