### PR TITLE
Adds infiltrators to dynamic mode

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Roundstart infiltrators are now possible (yet uncommon) in Dynamic
fix: Nukies should now spawn the proper number of ops
tweak: Infiltrators can no longer buy carp masks, HF blades, or Armstrong kits
/:cl:

### CODE REVIEW

**Comment by cris5311** [comment]
+1
Infiltrators are fun

**Comment by Majick1** [comment]
+1 Solo ops on highpop sucks, as does uncreative nugget clickspam

**Comment by Manly-Dwarf** [comment]
Infiltrators are just worse Ops. They might work better in Dynamic due to them not being a round-ender, but you better maintain them and ensure they don't suck, or else I'm going to remove them.

**Comment by ghost** [comment]
yeah but i don't know if anything's wrong with em cuz i haven't seen em happen in months

**Comment by MaterialisticThings** [comment]
+1

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
