### PR TITLE
Revert "Clown AoE Brainmelter"

### PR DESCRIPTION
**Pull request by ghost**
Reverts HippieStation/HippieStation#1969

```
[11:04 PM] tortellini tony: also holy shit why did the bikehorn get merged
[11:04 PM] tortellini tony: low effort PR
[11:04 PM] tortellini tony: like no offense but it was literally reused bikehorn code that gives 10 braindamage along with the flip emote
```

I agree

### CODE REVIEW

**Comment by Carbonhell** [comment]
we need a gun that changes a random clothing piece of the victim into the clown version

**Comment by GuyonBroadway** [comment]
I mean the code is fine but yeesh, "it's shit" isn't really very descriptive.

**Comment by ghost** [comment]
what's wrong with a silly gimmick for traitor clowns?
not everything in the uplink has to be utterly viable.

you haven't lived until you use 50TC crates exclusively.

**Comment by Kendrickorium55** [comment]
exactly what is wrong with this other than "I don't like it"?

clown horn that retards people is hilarious, leave it alone

**Comment by ghost** [comment]
@McBawbaggings it has no logging

**Comment by GuyonBroadway** [comment]
@Chnkr you coulda just asked...

**Comment by tortellinitony** [comment]
Shit change that was added without any thought. I think saying "it's shit" is perfectly descriptive. I wanted to see what people actually requested on the forum be made, this is not what the OP sounded like

**Comment by ghost** [comment]
If it's pissing people off, it's doing its job. All it needs is logging and that extra illegal tech.

**Comment by GuyonBroadway** [comment]
Which is happening here
https://github.com/HippieStation/HippieStation/pull/2003

**Pull request closed without merging**
