### PR TITLE
Adminbus STUFF!! Powergamer funny meme grenade holy shit!! Blow up all fuel tanks!!!

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
admin: Added in an admin only spawnable nade that causes fire, acid and explosions.
admin: Added a verb that lets you blow up all fuel tanks on the current z level
/:cl:

[why]:  I thought that explode all fuel tank verb was funny and this meme nade is something I've made in game many times, I just wanted to actually code it into the game so I don't need to remake it everytime to demonstrate it's insanity.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
+1

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by yobob591** [comment]
yes +1

**Comment by TheMeatGod** [comment]
+1

**Comment by Pyko1** [comment]
Should had prolly mentioned that big change how chempiles work on topic, as well as actually have that as its own PR since the adminbus fun commands and that are completely unreleated.

**Comment by k-k-karma** [comment]
OH yeah

**Comment by k-k-karma** [comment]
what

**Comment by Carbonhell** [comment]
What is the purpose for the blow all welding tanks? It seems abusey as fuck, not a verb admins should have since chances are they will get punished for using it. In the exceptionally rare case it is needed, admins can use SDQL.

**Comment by yoyobatty** [comment]
See, maybe I should add this under a hidden verb so it can't be abused..

**Comment by Carbonhell** [comment]
Just use a sdql call, should be something like
CALL boom() ON obj/structure/reagent_dispensers/fueltank IN world;

**Comment by Carbonhell** [comment]
-1

**Comment by Lxtoofonea** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Comment by yoyobatty** [comment]
@k-k-karma Why did you close this? It has more than enough votes from HA's and GM's

**Comment by Carbonhell** [comment]
I'm still of the opinion that admin verbs should let you do stuff that would otherwise take too much time with current tools, and those verbs are unneeded and cannot really be used to make players have fun anyhow. -1
As i said,in the extremely rare case you need to blow all tanks,  you can do so with the sdql query i made some comments above. I would rather prefer if admins started messing with sdql more so they could do some pretty fun tricks (even from discord)

**Comment by TheMeatGod** [comment]
Why is this still open?

**Comment by DaydreamPuppeh** [comment]
Why was this closed. It had enough votes

**Comment by k-k-karma** [comment]
yoyo didnt want to fix his code

**Pull request closed without merging**
