### PR TITLE
[MIRROR] Makes report issue handle null round IDs and server names

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34124
--------------------
For them git version people

### CODE REVIEW

**Comment by Pyko1** [comment]
wee elp!

Maybe just close?

**Comment by Carbonhell** [comment]
@pyko1 sorry why? Was it reverted?

**Comment by Pyko1** [comment]
I recall our issue report was hippiecode, but then again we can just swap to tg, cant be that bad now can it?

**Comment by Pyko1** [comment]
even tho this needs you to have github account instead of using honkbot?

**Comment by ghost** [comment]
Please do not replace the issue reporter

**Comment by Pyko1** [comment]
so close this

**Comment by Carbonhell** [comment]
Our interface file is mirrored. We can merge this to avoid conflicts,i think
After fixing the existing conflicts thats it

**Comment by Pyko1** [comment]
oh yeah, they must be just some ancient edits.

This file should not even be checked on our .dme?

**Comment by Pyko1** [comment]
yeah only got #include "hippiestation\interface\interface.dm"
so fix and merg

**Comment by Pyko1** [comment]
over written with up to date TG file, the actual file is unchecked on hippiestation.dme

So its just to fix future conflicts and does not affect anything.

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
Waiting travis

**Pull request merged**
