### PR TITLE
[MIRROR] Combat/Stun (slip) overhaul staging, mobility flags, adds crawling

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/39967
--------------------
Aiming to implement the framework oranges has detailed in https://tgstation13.org/phpBB/viewtopic.php?f=10&t=19102
Moves canmove to a bitflag in a new variable called mobility_flags, that will allow finer grain control of what someone can do codewise, for example, letting them move but not stand up, or stand up but not move.

Adds Immobilize()d status effect that freezes movement but does not prevent anything else.
Adds Paralyze()d which is oldstun "You can't do anything at all and knock down).
Stun() will now prevent any item/UI usage and movement (which is similar to before).
Knockdown() will now only knockdown without preventing item usage/movement.
People knocked down will be able to crawl at softcrit-speeds
Refactors some /mob variables and procs to /mob/living.
update_canmove() refactored to update_mobility() and will handle mobility_flags instead of the removed canmove 

:cl:
rscadd: Crawling is now possible if you are down but not stunned. Obviously, you will be slower.
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
This just adds crawling while knocked down by certain things. Its actually not that huge of a change.

**Comment by yoyobatty** [comment]
This should compile correctly.

**Comment by yoyobatty** [comment]
Jesus christ, more shit

**Review by yoyobatty — APPROVED** [review]

**Comment by ghost** [comment]
this is amazing, crawling lets you crawl over water and possibly lube, and also crawl under plastic drapes

**Comment by Carbonhell** [comment]
Wouldn't this conflict somehow with our current crawling?

**Pull request merged**
