### PR TITLE
Super powered toolbox

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: The artistic toolbox now has a super power.
/:cl:

### CODE REVIEW

**Comment by Punkinguy** [comment]
-1 useless and unfunny, only 14 year old redditors would find this funny

**Comment by ghost** [comment]
I don't think you belong here. Try this server instead: https://github.com/tgstation/tgstation

**Comment by Punkinguy** [comment]
> I don't think you belong here. Try this server instead: https://github.com/tgstation/tgstation

ok redditor

**Comment by ghost** [comment]
Actually, this is also an old hippie port. Only reason I thought of it.

**Comment by karmaisblackandbluepilled** [comment]
Don't do this, it will nuke our codebase again.

**Comment by Punkinguy** [comment]
lmao

**Comment by mkikt4743** [comment]
quarian more like queerian lmao

**Comment by ExpAntique** [comment]
-1

**Pull request closed without merging**
