### PR TITLE
 adds a cow and 2 chickens into an expanded service backroom

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: expands the service backroom and adds 2 chickens and 1 cow for sustainable feeding of the masses
:cl: zamolxius
add: Nanotrasen has shipped 2 chickens and 1 cow in the service backroom to prevent stationwide famine
/:cl:

[why]: 

8ca71361874d9e01108e50a2232797aa

### CODE REVIEW

**Comment by ghost** [comment]
oh, and this also removes a blob spawnspot

**Comment by ghost** [comment]
honkbot remove [do not merge] right now

**Comment by Carbonhell** [comment]
very nice, i wanted this back since we lost it from the old old rebase ayy, is there any feature suggestion about this? if yes,mark it as resolved by writing: "Closes #issuenumber" in the PR description

**Comment by JohnGinnane** [comment]
Same I really wanted it back, but as a room joining botany and kitchen but this is good too. I think I might have put up a suggestion a while ago, I'll check

**Comment by JohnGinnane** [comment]
Nope, guess I didn't log it

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
i dont like it, will remake

**Pull request closed without merging**
