### PR TITLE
Removes Thrower circuit

### PR DESCRIPTION
**Pull request by mikolaj007**
## Changelog
:cl:
del: Removes Thrower Circuit
/:cl:

## About The Pull Request

Removes thrower Circuit

## Why It's Good For The Game

because being able to hit someone 20 times with thrown hatchets in 6 seconds is bullshit
https://cdn.discordapp.com/attachments/321674575245082626/546670545026940928/unknown.png

I already made this before, but i didnt know github and added some more commits accidentally.
this time its on a branch.

### CODE REVIEW

**Review by Carbonhell — APPROVED** [review]

**Comment by RafRoq** [comment]
Don't

**Comment by Carbonhell** [comment]
+1

**Comment by Carbonhell** [comment]
I asked for this, and i love circuits. This one in particular is crap and it's most of the reason as for why people hate circuits.

**Comment by Maroonenahmoron** [comment]
+1, little counterplay and crits within seconds.

**Comment by TheMeatGod** [comment]
+1 Literally what maroon said

**Comment by earthmoonjune** [comment]
+1

**Pull request merged**
