### PR TITLE
Removes the fucking horrible gay music from Lean

### PR DESCRIPTION
**Pull request by ghost**
WHAT THE FUCK THIS IS RAPE AGAINST MY EARDRUMS, I'M SUING!!!!

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Its not even THAT loud but you could turn it down a bit by chaining 50 to say 30.

**Comment by ghost** [comment]
@GuyonBroadway NO GET RID OF IT, I HATE EVERYTHING ABOUT THAT SHIT SONG

**Review by GuyonBroadway — APPROVED** [review]
technically ok.

**Comment by ghost** [comment]
@GuyonBroadway OR IF YOU REALLY HAVE A HORRIBLE TASTE IN MUSIC, ADD AN OPTION TO DISABLE IT

**Comment by Spacedong** [comment]
from a gameplay perspective, trying to be sneaky in a stealthy game doesnt really bode well with having some nigger music blasting out your body for some reason

**Comment by ghost** [comment]
no this is fucking funny
don't remove it

**Comment by KayeArray** [comment]
i dont see the issue

**Comment by ghost** [comment]
6 SECONDS OF SIPPIN ON LEAN IS TOO MUCH FOR MY SPACEMEN EARS

**Comment by dreamcrab** [comment]
-5

if you wanna be stealthy dont sip the drank, we have changes coming to chempiles hopefully that address the issue with everyone becoming leaned up

**Comment by ghost** [comment]
Gonna do a better version of this

**Pull request closed without merging**
