### PR TITLE
[MIRROR] Properly adds a Janitor ERT

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42659
----------------------------
## About The Pull Request

Does what the title basically says, adds a Janitor ERT for admins to use.
There are two types of janitors, normal ones and heavy duty ones:
* Normal janitors just get the stuff that you'd expect janitors to get, a mop, a bucket, some cleaning grenades and yadi-yadi-yada.
* Heavy duty janitors get a fancy wicked chem sprayer which contains space cleaner and regenerates some of it on it's own and can contain more juice, BUT it can't be refueled in any other way, so if the crew gets their hands on it, there won't be a lubeopocalyspe.

## Why It's Good For The Game
As I said before, I've seen admins use these, and it's a shame there isn't a preset for it, hence this PR.

## Changelog
:cl: Vile Beggar
add: Central Command now has access to a janitorial ERT. Be wary of the heavy-duty ones!
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Quality PR.

**Review by yoyobatty — APPROVED** [review]

**Comment by yoyobatty** [comment]
I like

**Comment by waterwater1212** [comment]
looks good bro i support this good job honkbot

**Comment by Manly-Dwarf** [comment]
The icons for several items here do not work @yoyobatty

**Comment by Manly-Dwarf** [comment]
This is probably because the PR is a pile of garbage, even if it is funny.
People are reporting bugs on https://github.com/tgstation/tgstation/pull/42659 too.

**Pull request merged**
