### PR TITLE
Removes kitty ears from the on-station vending machines.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
del: Nanotrasen would like to remind you that we pay you to work, not prance around wearing cat ears and being a faggot. We have removed this silly little dress-up game from your costume vendors. GET BACK TO WORK!
/:cl:

Because anime cancer.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Improve not remove? :^)

**Comment by ghost** [comment]
no stealing the kitty ears as abductor is fun.

**Comment by ghost** [comment]
+1

**Comment by GuyonBroadway** [comment]
I'm, improving the vending machines by tweaking its contents ::::^^^))))

**Comment by JohnGinnane** [comment]
Does this mean they're no longer acquirable in any way?

**Comment by bardofrage** [comment]
+1

**Comment by ghost** [comment]
-1

**Comment by Carbonhell** [comment]
+1
*+1*
**+1**
***+1***

**Comment by Blute1** [comment]
why is this PR not instantly merged yet???
+1

**Comment by ghost** [comment]
Garithos held me at gun point to approve

**Comment by ghost** [comment]
PLEASE PR THIS BEFORE GARITHOS ENDS MY LIFE

**Comment by GuyonBroadway** [comment]
even if it gets a +3 it REALLY should be open for 24hrs... so we can harvest the salt.

And ya'know it might be codestandards and all that.

**Comment by Chocodaemon** [comment]
Sure, I'll take the bait.

Costume Vendors are more for the clowns and mimes, who are the literal laughingstocks of the station (sometimes). Why specifically remove this from the vendor when other items fit the same criteria you made up as well?

**Comment by GuyonBroadway** [comment]
Because you would not respond like this if I removed any other item from the autodrobe.

**Review by KayeArray — APPROVED** [review]

**Comment by JohnGinnane** [comment]
>removing items to generate salt

image

**Comment by ghost** [comment]
faggot

**Comment by CeSiumShark** [comment]
Choco, you're not even part of Hippie. You contribute to /TG/ instead. Why do you care so much about us removing some shit that your community forced us over with? Especially when it's cosmetic shit that encourages retards to act like retards? Anyone can break into the costume wardrobe.

The fact that you could've used any other profile picture, and you choose a cat eared anime retard, proves that your opinion is not valued here.

Please leave!

**Comment by CeSiumShark** [comment]
It's funny how Citrus, a /TG/ user, also voted -1 on it. Why is /TG/ getting involved?

**Comment by ghost** [comment]
bait lads, ignore!

**Comment by Anonmare** [comment]
Scared?

**Comment by CeSiumShark** [comment]
Shut up furry

**Comment by praisenarsie** [comment]
angrylookingcatdudeguythingisitevenaguynobodyreallyknows

**Comment by KayeArray** [comment]
sticks and stones may break my bones but you can never revert me

**Comment by praisenarsie** [comment]
budahthegreatangryoverlord

**Comment by Kraseo** [comment]
imagen

**Comment by Spess-Rando** [comment]
Choco's avatar is mouse eared, not cat eared.

**Comment by ghost** [comment]
attention all of you catgirl faggots, I have relatives from not so far back that were Nimibian tribesman. They happen to have fought lions just to become warriors. I don't know what you know about lions but they aren't like your average cat. I bet you would absolutely **** your...self if you ever saw a real life lion, especially if you were only holding a sharpened stick and you were naked. Come talk to me when some of your family members have gone on the Zambutu bibjano; A.K.A. the trial of life. Until you have done half the **** that they have maybe you shouldn't even talk to me like this. I know you think you're hard and **** but guess what, you aren't. Now go grow some Namibian genes and we'll talk about this **** for real.

**Comment by CeSiumShark** [comment]
attention all of you catgirl faggots, I have relatives from not so far back that were Nimibian tribesman. They happen to have fought lions just to become warriors. I don't know what you know about lions but they aren't like your average cat. I bet you would absolutely **** your...self if you ever saw a real life lion, especially if you were only holding a sharpened stick and you were naked. Come talk to me when some of your family members have gone on the Zambutu bibjano; A.K.A. the trial of life. Until you have done half the **** that they have maybe you shouldn't even talk to me like this. I know you think you're hard and **** but guess what, you aren't. Now go grow some Namibian genes and we'll talk about this **** for real.

**Comment by HippieBartels** [comment]
+1 fuck furries and weebs

**Comment by CeSiumShark** [comment]
this is already merged u belgian boy

**Comment by SplergeBucket** [comment]
hel yea

**Comment by ghost** [comment]
this is the shit i live for

**Pull request merged**
