### PR TITLE
[MIRROR] Gives Nar-Sie a new summon sound

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/29450
--------------------
:cl: The /tg/ code burglary Co.
soundadd: Tg liked Popnotes Nar-sie sounds so much they nabbed them and now they are in the base code as well as our own which is confusing also can I get sandwich?
/:cl:

# All credit for the sound goes to @ PopNotes from [HippieStation](https://github.com/HippieStation/HippieStation/pull/2364). I take no credit for it.

[Here's ](http://puu.sh/wHm7V/92992edbcd.wav)what it sounds like.
I asked in Coderbus if this violated the freeze, and was told that it didn't. Please tell me if it does.

### CODE REVIEW

**Comment by PopNotes** [comment]
lmao

**Review by tortellinitony — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
Should we delete the changelog as it would be confusing? I mean we already have this, it would be a bit dumb for a changelog saying we added something we already have (and have a changelog for)

**Comment by ghost** [comment]
we don't, it got denied

**Comment by ghost** [comment]
SCRATCH THAT I'M RETARDED

**Comment by PopNotes** [comment]
This is an attempt to mirror something we already have lmao

**Comment by GuyonBroadway** [comment]
You know what, Imma just tweak the CL and mergificate dis.

**Pull request merged**
