### PR TITLE
Wheel chair badminbus

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
admin: Wheel chairs can now have their movement speed VV'd by admins.
/:cl:

[why]: Admin tried to modify the movement speed, turns out, it was hardcoded, so I fixed that.

### CODE REVIEW

**Comment by ghost** [comment]
running in the nineties

**Comment by ghost** [comment]
+1

**Comment by Eagle-Eyess** [comment]
“Danka my hardhatted friend” +1

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
+1

**Pull request merged**
