### PR TITLE
Automatic changelog compile via github actions

### PR DESCRIPTION
**Pull request by Neotwr**
## About The Pull Request
Makes changelog compile automatic so you don't have to push a button everyday

This compiles the `.yml` changelog files in `html/changelogs` and then commit it to master

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
we already have automatic changelogs

**Comment by Neotwr** [comment]
this compiles them automatic

**Comment by Manly-Dwarf** [comment]
what

**Comment by Manly-Dwarf** [comment]
bro we don't have to push a button for our changelogs either

**Comment by Neotwr** [comment]
ugh don't you have to use a .bat file to compile all changelogs?

**Comment by ghost** [comment]
We use a script with TGS4

**Comment by Neotwr** [comment]
oh god, Im closing then

**Comment by ghost** [comment]
@steamp0rt why is TGS4 as good or better than github actions?

**Comment by Neotwr** [comment]
@steamp0rt Don't you still need to run this script manually?

**Comment by ghost** [comment]
@Neo-0 no

**Pull request closed without merging**
