### PR TITLE
[MIRROR] Fixes SCP-294 overlay problems

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35996
--------------------
:cl: MoreRobustThanYou
fix: SCP-294 should no longer have overlay problems
/:cl:

Why: This had been broken since it's been added and oranges keeps closing MRTY's prs, I'm pulling the fix from his branch so it actually goes through.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
@tortellinitony this changes a json file so I'm not sure if we need to do anything before merging this?

**Comment by Pyko1** [comment]
looks like its missing files

**Comment by JohnGinnane** [comment]
probably could just recompile tgui

**Comment by GuyonBroadway** [comment]
We'll need to recomp tgui but we should do that after we merge a lot of this shit.

**Review by GuyonBroadway — APPROVED** [review]

**Comment by praisenarsie** [comment]
no recompile tgui always after merge ya wee shit

ALSO FUCKING DELETE THE BRANCH

**Pull request merged**
