### PR TITLE
[MIRROR] [READY][PAID CODE] economy PR

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40312
--------------------
# latest changes
paystand -> machine you have to build
id cards silent except to holder
reclaiming account via account ID on empty idcard
changing job on ID card changes paycheck
departmental budget ID cards that allow direct access to your budget spawning on all head roles
use ID inhand if it doesn't have an account to set an account ID
use ID inhand if it DOES have an account to extract money in cold, hard cash

# rest of PR

You see This Guy?
thatguy
With the power of **CAPITALISM AND ECONOMY**, you too could be This Guy.

Supplementary Video:
https://www.youtube.com/watch?v=B3uk5bJcyM8

Recommended Reading:
https://www.newyorker.com/humor/daily-shouts/l-p-d-libertarian-police-department

:cl: Iamgoofball/Beesting12, Paid Code
experimental: After being sued by the Space Labor Committee for workers' right violations, Nanotrasen has decided to abide by Galactic Minimum Wage policies.
experimental: The station is now capitalist.
experimental: Crews will be paid every 5 minutes based on their job at the start of the shift, and departments will gain money by doing what they're supposed to.
experimental: Use your ID in hand to create a Pay-station to charge from.
/:cl:

Supplementary pictures:
https://file.house/xsRf.png
https://file.house/tunc.png
https://file.house/HhgB.png
https://file.house/J4u8.webm
https://file.house/xk7X.webm

todo list:

- [X] Setup economy subsystem
- [X] Setup accounts
- [X] Setup paychecks
- [X] Setup job specific pay info
- [x] Make vending machines use money
- [x] Allow slamming cash into ID card to put it in your bank account
- [x] Add Pay-stations for players to charge with
- [x] Allow vending from your department for free
- [x] Make Cargo budget == cargo points
- [x] Make Security budget increase from alive crewmbers vs dead crewmembers, dead hostile mobs, and redeemed gulag points
- [x] Make Science budget increase from researching tech, raising slimes, and exploding bombs.
- [x] Make Medical budget increase based on health of alive crewmembers
- [x] Make Service budget increase from crew mood being high
- [x] Make Engineering budget increase from maintaining high Structural Integrity
- [x] Civilian Budget
- [x] ???
- [x] Profit

### CODE REVIEW

**Comment by Carbonhell** [comment]
this is probably broken to hell, let's wait and see if tg dishes out some fixes or maybe disable this completely

**Comment by Iamgoofball** [comment]
@Carbonhell it's fine, goof seal of approval

**Comment by Manly-Dwarf** [comment]
I personally have no issue with the economy. In fact it could add a lot to the game that isn't already there (and also gives the syndicate money briefcase a reason to exist.) and potentially expand upon jobs that truly have nothing to do, like Chef.

Just uhh, let's change all of it. $50 for a clean needle might be funny to a heroin addict but a lot of these prices feel too samey, and also generally double digits when they don't need to be that huge.

**Comment by HippieBartels** [comment]
No thanks

**Comment by Iamgoofball** [comment]
>Just uhh, let's change all of it. $50 for a clean needle might be funny to a heroin addict but a lot of these prices feel too samey, and also generally double digits when they don't need to be that huge.

Remember, dep. vendors only cost money if you're NOT in the department.

A medical doctor will see "syringe (FREE)" when using it.

Only costs money for assistants.

also, remember, everyone but assistants and clowns/mimes make double digits by default

**Comment by Carbonhell** [comment]
huh that sounds like a good idea
honestly i'd be up to see how it goes,but i wanna be fully sure everyone agrees since it's a pretty big change. Plus it'd be also nice if it could stay up for some days, just incase a bad bug shows up.
+1

**Comment by ghost** [comment]
let's try this out +1

**Comment by biggiOS** [comment]
yes please +1

**Comment by GuyonBroadway** [comment]
If we merge this imma red-do the roundstart clown-car such that it does not scoop up on bump, only the clown can get in for free and the clown can set a fee, to get into the car people have to pay the fee.

The clown car will become the station taxi.

**Comment by Eagle-Eyess** [comment]
sure +1

**Comment by Lxtoofonea** [comment]
+1

**Comment by bardofrage** [comment]
Hell ye

**Comment by JessHorserage** [comment]
If it's gay for hippie balance -∞ other than that eh +1

**Comment by GuyonBroadway** [comment]
We've wanted economy for a while now andbI think the system has much potential, we should start coming up with ways to enhance this where we can.

**Comment by DaydreamPuppeh** [comment]
+1. Maybe the chef will finally do their job

**Comment by Carbonhell** [comment]
Wait what is this conflicting with?

**Comment by yoyobatty** [comment]
Can I merge now?

**Review by yoyobatty — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
Not if I merge it first.

**Comment by Carbonhell** [comment]
The line changes aren't equal, what were the diffs?

**Comment by GuyonBroadway** [comment]
Just some strange but fixable conflicts.

You know how sometimes we get empty conflicts? It was like the bot put in one of those and then github wrapped a real conflict around it.

**Pull request merged**
