### PR TITLE
Removes unmaintained vending changes

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
fix: Vending machine icons back to normal.
/:cl:

Cleared out unused files

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
This is probably for the best

**Comment by Pyko1** [comment]
yeah time to learn teegee ui for vendor shit

**Review by GuyonBroadway — DISMISSED** [review]

**Review by ghost — DISMISSED** [review]

**Comment by ghost** [comment]
CCCCCOOONNFFFFLLICCTTTTSSS

**Comment by ghost** [comment]
Just do vending TGUI upstream, @tortellinitony

**Review by ghost — DISMISSED** [review]

**Comment by praisenarsie** [comment]
@tortellinitony conflicts

**Comment by GuyonBroadway** [comment]
Can you fix these conflicts ASAP? Vendings R broke.

**Review by praisenarsie — APPROVED** [review]

**Pull request merged**
