### PR TITLE
Stops giving players brain damage for talking about colors

### PR DESCRIPTION
**Pull request by tortellinitony**
Newsflash: "rouge" is a real word! I don't see how it makes any sense at all to punish players for misspellings, anyway. Not only that, but this has the potential to create lag if someone spams "rouge" over and over.

### CODE REVIEW

**Review by GuyonBroadway — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
Code is "good" but this needs head input as the previous change was head approved.

**Comment by mlgdatboi** [comment]
The rouge thing would be good if it gave less briandamage

**Comment by PopNotes** [comment]
this is why nobody likes your PRs, tony

**Comment by Pyko1** [comment]
the whole rouge pr was shit, either remove it, or add the same 60 braindamage to any and all common typos.

Not to mention it got speed merged and with only 1 head giving opinion.

**Comment by Pyko1** [comment]
also does not braindamage already make you shout rouge, thus giving you even more braindamage?

**Comment by Pyko1** [comment]
and there is the voodoo doll antag item that you can use to force people say rouge

**Comment by Arzion5** [comment]
It's not an antag item, it's a lavaland loot item

**Comment by Pyko1** [comment]
its a wizard summon at least
and at somepoint at least we had it for cmo

**Comment by Pyko1** [comment]
Not to mention people cheesing it by having rouge as name or agent id

**Comment by GuyonBroadway** [comment]
It was approved by way of one head and three GA's, GA's count as 1/3, thee GA's and one head is a +2.

**Comment by Pyko1** [comment]
It was but should at least give option for heads to give opinion if they want, instead of speedmerging things as soon as it has +2, especially if only 1 head has given their consent.

Also werent GA votes meant to be more of a tiebreakers anyways?

**Comment by Arzion5** [comment]
In all honesty, it's fun as a joke. Maybe remove it for now but turn it into some server toggleable that gives brain damage for multiple misspellings?

**Comment by j-mie** [comment]
+1 on this

**Comment by ghost** [comment]
+1
I didn't have the chance to say my piece on the previous one but I was probably more against it rather than for it. But I think people are starting to realise this sort of code is silly in design in terms of the actual game.

**Comment by ghost** [comment]
-1

**Comment by DinduStuffin** [comment]
+1

too much abuse potential and from what I'm hearing it's already being abused. Anything that adds a learning curve or something to make it harder for newer players to get used to -- intentionally or unintentionally -- beyond shit that explains rules or supports it is bad.

**Pull request merged**
