### PR TITLE
Vending icons.

### PR DESCRIPTION
**Pull request by tortellinitony**
vs. pre-rebase
http://i.imgur.com/a8QDLLp.png

in-game
https://vgy.me/kSE5Jc.png

These will replace the current /tg/ ones:
https://camo.githubusercontent.com/9de26fbe3f9208a6f5466254e91ebf9c2705a73d/687474703a2f2f692e696d6775722e636f6d2f426e49677a68682e706e67

### CODE REVIEW

**Comment by ghost** [comment]
I really don't like these tbh

**Comment by j-mie** [comment]
Honestly, I'd rather keep our old ones

Edit: When I say "old ones" I mean these:
image

**Comment by BeeSting12** [comment]
I dont play here so take my opinion with a grain of salt but the old ones are better tbh.

**Comment by trifornt-tinfornt** [comment]
They're ugly as shit. Old ones are better.

**Comment by PopNotes** [comment]
These are vastly better than the old ones

**Comment by j-mie** [comment]
These are better then what we have in-game right now, so let's roll with them for now.

**Review by j-mie — APPROVED** [review]

**Pull request merged**
