### PR TITLE
[MIRROR] [READY] The war on stun based combat, Phase I: Fuck ranged stuns

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42930
----------------------------

## About The Pull Request

Nukes the hybrid taser from orbit. Everywhere that spawned it now provides a disabler instead. Standard sec issue? Disabler. Armory? Disabler rack.
Want something with more punch? Beg the warden for a shotgun or an energy gun.
The hybrid taser itself has not been removed from the codebase.
Also removes the stun from the advanced energy gun so it doesn't just become the late game secret powerhouse.
Hoslaser keeps it, but only gets three shots instead of five.
The ebow has been COMPLETELY RUINED as well. See the changelog for details I'm too lazy to copypaste.

## Why It's Good For The Game

Fuck stun based combat.
Sec still have their stunbatons, collapsible batons still exist, pepperspray still exists, flashbangs still exist. but now any fight involving sec or anyone who has robusted a sec officer will be less ranged instastun bullshittery.

## Changelog
:cl:
balance: New NT regulations have replaced the standard issue hybrid taser with a pure disabler.
balance: Also fuck the stun mode on the advanced energy gun who thought that was a good idea.
balance: The hos's laser can only fire three taser shots instead of five.
balance: Energy crossbows have been reworked. They no longer paralyze, but instead heavily blur vision, apply a huge burst of stamina damage, and knock you on your ass for one second. Two shots is enough to down someone from stamina crit on both the mini and large versions. The blur lasts for 10 seconds.
balance: The price of the mini ebow has been reduced to 10TC to compensate for this weaker effect.
tweak: The ED-209 is now built with a DRAGnet and fires netshot instead of taser bolts.
balance: Stunshells can no longer be produced in any lathe.
balance: The "pacifier" mech taser can no longer be built.
/:cl:

### CODE REVIEW

**Comment by k-k-karma** [comment]
fucking christ tg

**Comment by yoyobatty** [comment]
I personally disagree with removing tasers exclusively because our tasers deal stun damage so they aren't 1 hit ranged stun batons. Ebows, meh, they aren't really used and can be easily countered. I do like the use of the dedicated disabler, but it's something cargo can order.

**Comment by Jujumatic** [comment]
"I know what it's like to lose. To feel so desperately that you're right, yet to fail nonetheless. It’s frightening. Turns the legs to jelly. I ask you, to what end? Dread it. Run from it. Destiny arrives all the same. And now, it's here. Or should I say, I am."

**Comment by optimumtact** [comment]
@yoyobatty when did hippie make tasers do stun damage? thats pretty woke

**Comment by yoyobatty** [comment]
Go to hippiestation/modules/projectiles and just look for energy.dm or w/e and check the history.

Edit: Hold on, I meant to say stamina damage, it's 60 per hit and 50% chance of dropping all items in your hand.

**Comment by mikolaj007** [comment]
i checked history out of curiosity
at least jan 2017
prolly earlier, but thats the moment the new hippiestation/code file got created

**Comment by yoyobatty** [comment]
That was our first TG rebase when jamie took over for a year

**Comment by mikolaj007** [comment]
so before the rebase @optimumtact

**Comment by Manly-Dwarf** [comment]
@optimumtact our entire stun system is mostly stamina based now, most instant stuns as well as antistuns have been removed.
lethals are also lightning fast so you have a reason to use them over stuns

**Comment by optimumtact** [comment]
interesting

**Comment by RafRoq** [comment]
if you merge it give disabler speed buff back

**Comment by Manly-Dwarf** [comment]
We ain't mergin shit

**Comment by Zyzarda** [comment]
yes god PLEASEEE

**Comment by funkynuggets** [comment]
NO GOD NO

**Comment by TheMeatGod** [comment]
-1 gay

**Comment by earthmoonjune** [comment]
no this is useless

**Comment by ghost** [comment]
how can tg be so shit

**Comment by DaydreamPuppeh** [comment]
-1

**Comment by yobob591** [comment]
-1 because not relevant to our stuncombat

**Comment by Eagle-Eyess** [comment]
-1 wtf...

**Comment by Jujumatic** [comment]
actually this is a lot scarier than it actually is, it'll be surprisingly easy to modularise all of this bullshit out

**Pull request closed without merging**
