### PR TITLE
ZA WARUDO!

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Added a Station-wide Timestop for wizards, THE WORLD!
add: 1 second per spellpoint put into THE WORLD.
add: It also comes with the CHECKMATE spell, which allows you to throw your kitchen knife collection at your enemies.
/:cl:

### CODE REVIEW

**Comment by lunaman22** [comment]
+1
STANDO NO POWA

**Comment by biggiOS** [comment]
nice
+1

**Comment by Manly-Dwarf** [comment]
This better have an amazingly long cooldown or some form of startup.

**Comment by Majick1** [comment]
Yeah, what's the CD before people vote.

**Comment by ghost** [comment]
the cooldown for the spell is 90 seconds. i feel like that's a good balance between "spammable" and "so long it's useless"
and with a full 10 spellpoints, or 10 seconds
you still only get time to run from, say, medbay lobby to cargo
or unload your knives into 1 and a half people
or toolbox a single person to crit

**Comment by Majick1** [comment]
+1 then, seems alright as long as the round doesn't drag too long, still expect someone to spam it as often as possible on day 1 because they want to make a point

**Comment by Manly-Dwarf** [comment]
remove bag of knives
add checkmate spell instead
or I can add it for you
smug

**Comment by ghost** [comment]
> add checkmate spell instead

wtf is that

**Comment by diegoxt45** [comment]
> > add checkmate spell instead
> 
> wtf is that

it's the move where dio stops time and throws a bunch of knifes. basically guaranteing their death. unless you're jotaro

**Comment by ghost** [comment]
so i should basically add arcane barrage but it's knives?

**Comment by diegoxt45** [comment]
fuck i'm really bad at explaining it watch this: https://www.youtube.com/watch?v=mO4z_2J2mmU
skip to around 2:22 minutes

**Comment by ghost** [comment]
how is that any different from arcane barrage but with knives? is it it just the _amount_ of knives?

**Comment by diegoxt45** [comment]
i think kbb meant by stopping time for a brief second and a bunch of knives just appearing all around the guy who got caught

**Comment by diegoxt45** [comment]
i think we need kbb's input in this tho

**Comment by biggiOS** [comment]
designer idea: make checkmate like an arcane barrage that has lower damage but slightly pierces armor and applies slight bleeding per dagger

**Comment by Manly-Dwarf** [comment]
k +1

**Comment by AnthonyJNgo** [comment]
This needs to be test merged.

**Comment by Manly-Dwarf** [comment]
no it doesn't it's a wizard spell
why does this need testmerging

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 8e22dd7f8e0d57c9ecb2019dd49709279d3c034f
Pull Request: 50e9cb45e2e7dac73a44c077137bb712748a7bdb
Server: 42d328ec9d7e116cc3b5f6682d2a25e3ea838427

##### Comment
vivadel is dumb

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 8e22dd7f8e0d57c9ecb2019dd49709279d3c034f
Pull Request: ad303c8d2753091fecea65434a1fd6ea6fe4ff90
Server: 3493c927ce65949cce022d0a3cba964b92519d4e

##### Comment
this is why I said the cooldown needed to be immense. also wtf why put checkmate on a two minute cooldown? 1 minute is extreme enough

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 8e22dd7f8e0d57c9ecb2019dd49709279d3c034f
Pull Request: 6ecdbc3bf2338215ce0272a44709b6b82a32eb78
Server: fe4c7bdf923d750fc536c8502a016ba08a36adf6

##### Comment
talking is a free action

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: d8d64afff91595d10522c1bb713bd33573fe9b61
Pull Request: 6ecdbc3bf2338215ce0272a44709b6b82a32eb78
Server: 5fa680789c230a0a46288be2ee1aec59d09c2250

##### Comment
talking is a free action

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: d8d64afff91595d10522c1bb713bd33573fe9b61
Pull Request: 6ecdbc3bf2338215ce0272a44709b6b82a32eb78
Server: 25510209971defcf93e0c1a2ac64f014ec42ffbb

##### Comment
talking is a free action

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 15b014c2c143c675564359292aafb5221eb29454
Pull Request: 9eaa6abff6b05757647bc94e6a30a52eb8af8bca
Server: f5c3a9e7480a27a8a90dbbf81e8923a4a6063014

##### Comment
steam's ports

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 9bf2c62463c3bd5b4f5062016a66dff8da27d223
Pull Request: fc6b1ca846e09597094d352442946737cdbe396d
Server: 1a4c29f1d287e617243c0030809ebb3399dfaf94

##### Comment
ok

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 9bf2c62463c3bd5b4f5062016a66dff8da27d223
Pull Request: fc6b1ca846e09597094d352442946737cdbe396d
Server: ccfb70a20c712d40a9d2a14d17c13b8c337b83dc

##### Comment
ok

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 72e72e24825f69dc8cfa86a36db3a9577043fe3e
Pull Request: fc6b1ca846e09597094d352442946737cdbe396d
Server: 4c659a75acdb4032c0951b768d9d2dd50e78b2c9

##### Comment
can we merge this already I mean there's not much left that needs to be done besides adding a staff_req maybe

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 72e72e24825f69dc8cfa86a36db3a9577043fe3e
Pull Request: 36f801637d1e334926183a0642849751610db19a
Server: 472ce7fa8d70296e12e68c175967b9cf10a42994

##### Comment
can we merge this already I mean there's not much left that needs to be done besides adding a staff_req maybe

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 4705fd9e7ae76fea77ac58bc62456e73152df7f4
Pull Request: 36f801637d1e334926183a0642849751610db19a
Server: ae9a7a0a76f9d9fece3506fe2efa31e37e6a80f9

##### Comment
can we merge this already I mean there's not much left that needs to be done besides adding a staff_req maybe

**Comment by ghost** [comment]
should be ready

**Comment by AnthonyJNgo** [comment]
@steamp0rt Conflicting files: hippiestation/icons/obj/projectiles.dmi

**Comment by ghost** [comment]
oh poopoo

**Comment by ghost** [comment]
@AnthonyJNgo fixed

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 7b5f3102b0b1a98563759da88f2bbe079b2a0d34
Pull Request: b0f66fba2e9a421ed0fa6045ef4dab202ea69745
Server: 63ddf60ff3c7af7d07cf178b5149dbcd27161c43

##### Comment
dumb vivadel

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 4859b9b3103432e2578263f3f6ded68784272451
Pull Request: b0f66fba2e9a421ed0fa6045ef4dab202ea69745
Server: dbc6bcaaf389ef64cb5d01cc8eb55255815cdff8

##### Comment
dumb vivadel

**Comment by Manly-Dwarf** [comment]
time to merge this

**Comment by ghost** [comment]
#### Test Merge Removed

**Pull request merged**
