### PR TITLE
Map Changes

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: CE now has a separate privacy shutter button for their office.
add: Added privacy doors to RD, CMO, CE and HOS offices.
add: Toxins room can now be locked down from RD office.
add: Engineering windows now have lockdown doors.
tweak: Changed the doors to the aforementioned offices from glass to solid.
tweak: Engineering lock down doors moved to behind the first door.
tweak: Anchored o2 lockers in Engineering.
tweak: Atmospheric gas chamber air injectors now default to max.

/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

The privacy shutters create more security for heads of staff. 
Solid doors on heads of staff offices create more privacy.
The engineering lock down changes prevents people from entering Engineering through the foyer and CE office if CE office is locked down. 
Toxins lab gets set on fire almost every round so a lock down will ensure great security for the Research Divison.
O2 lockers keep getting spaced everything the airlock gets opened.
Atmospherics should be slightly less clogged now as the gas chambers will fill up quicker due to the air injectors being maxed..

### CODE REVIEW

**Comment by DinduStuffin** [comment]
These all seem really nice. The pics you posted in coderbus while mapping didn't seem to have any errors.

+1

**Comment by ghost** [comment]
If you can provide final screenshots here for the sake of convenience, it'd be greatly appreciated.

**Comment by yoyobatty** [comment]
image

image

image

image

image

image

image

image

Final version has solid doors on CE and HOS offices.

**Comment by Thelolswat** [comment]
Holy fuck yes

Also add one for chemistry plez

**Comment by ghost** [comment]
It certainly doesn't seem bad, though it could possibly lead to minor balance issues in terms of map movement.
For the sake of seeing its effects, +1

**Comment by ghost** [comment]
Good shit +1

**Review by ghost — CHANGES_REQUESTED** [review]
You forgot to mapmerge.

**Pull request closed without merging**
