### PR TITLE
[MIRROR] Late join antagonists will try to target late join players

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/31560
--------------------
To address some concerns in this thread: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=13322

### CODE REVIEW

**Comment by KayeArray** [comment]
Needs head input.

**Comment by ghost** [comment]
tbh this is more of an issue on higher rp servers since people are less willing to try and roll antag and such
we don't get an awful lot of latejoiners and traitors can murderbone anyway????

**Review by ghost — APPROVED** [review]

**Comment by MoreRobustThanYou** [comment]
OH FUCK

**Comment by KayeArray** [comment]
ooooooooooooooooooooooooh well

**Comment by DinduStuffin** [comment]
fuck no
please fucking no

**Comment by GuyonBroadway** [comment]
If I'm reading this right what it actually does is tries to set latejoin antag assassin objectives to target latejoin players.

**Comment by DinduStuffin** [comment]
Oh, I somehow thought this meant it'd try to make latejoiners more likely to become antag or something.

If all it does is just give them a bigger pool of people to have as objectives, I'm fine with that.

**Pull request merged**
