### PR TITLE
adds new laugh sounds

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl: AdeptMechanicus
soundadd: added 2 laugh sounds
/:cl:

https://cdn.discordapp.com/attachments/276456582500319244/652518641132372011/laugh03.ogg
https://cdn.discordapp.com/attachments/276456582500319244/652518649768443943/laugh04.ogg

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
???

**Comment by ghost** [comment]
but why

**Comment by ghost** [comment]
they sound too bland

**Comment by yoyobatty** [comment]
Get it approved or it's gonna get closed

**Review by waterwater1212 — APPROVED** [review]
good merge

**Comment by AnthonyJNgo** [comment]
Did you rip these from the Joker movie? I hope not. Anyways, this seems like a harmless change, and the laughs are actually pretty good quality (hopefully not movie quality).

**Review by AnthonyJNgo — APPROVED** [review]
Pretty simple stuff here, everything looks good to go.

**Pull request merged**
