### PR TITLE
BRINGS BACK TTS

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: TTS IS BACK
/:cl:

**Requires**: [Mimic TTS](https://github.com/MycroftAI/mimic1), mediainfo (`apt install mediainfo`)

### CODE REVIEW

**Comment by Punkinguy** [comment]
+1

**Comment by SireTurret** [comment]
OUR LAWYERS SAY: "YES!"

YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!YES!

**Comment by Manly-Dwarf** [comment]
Post a video of TTS working. Are you sure you're willing to maintain this, you're sure it's not going to break shit?

**Comment by ghost** [comment]
https://cdn.discordapp.com/attachments/276455180852264960/617809383237353475/Gk4nQkaXvr.webm

**Comment by ghost** [comment]
and yes i can confirm this works

**Comment by notoriousBIGGIOS** [comment]
+1 ebin

**Comment by karmaisblackandbluepilled** [comment]
+1 ebic

**Comment by MrHeroKong** [comment]
Heck yes +1

**Comment by AnthonyJNgo** [comment]
I need batty to review this.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
