### PR TITLE
Removes Cancer

### PR DESCRIPTION
**Pull request by SireTurret**
[Guidelines]: # Yes

## Changelog
:cl:
del: Removed Steamp0rt from the gauntlet credits, replaced him with a based brit instead.
/:cl:

## About The Pull Request

Yes

## Why It's Good For The Game

Yes

### CODE REVIEW

**Comment by DaydreamPuppeh** [comment]
+1. Though I would recommend a feature that also removes him from the code. Make code that specifically removes him yknow.

**Comment by SireTurret** [comment]
Mad?

**Comment by DaydreamPuppeh** [comment]
Faggot

**Comment by ghost** [comment]
sorry bud, removing attribution is a violation of the AGPL :smug:

**Comment by SireTurret** [comment]
your mum

**Comment by diegoxt45** [comment]
obviously +1

**Comment by TrickyDickRichard** [comment]
+1

**Comment by sagattyy** [comment]
+1

**Pull request closed without merging**
