### PR TITLE
Fixes all pods

### PR DESCRIPTION
**Pull request by Dinopeaks**
fixes all pods so that they go to the right place and all launch so them tator can get away alive!

[Changelogs]: # just made the pods work not much else they all just spawn and fly when needed no more broken pods 

:cl: optional name here

fix: fixed a few things

/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
well it seems the mapmerger dun goofed
also conflicts for some reason

**Comment by Dinopeaks** [comment]
how did the mapmerger dun goof

**Comment by GuyonBroadway** [comment]
Well the changes are several thousand lines long, Unless you remapped the whole of engineering that shouldn't happen.

**Comment by Dinopeaks** [comment]
i had to delete one pod but that is it

**Comment by GuyonBroadway** [comment]
Then this was not map merged properly.

**Comment by Dinopeaks** [comment]
what can i do to fix this or is there nothing

**Comment by GuyonBroadway** [comment]
Map conflicts are often a pain in the arse to fix. There are many things you could try but the most straightforward would be to just close the PR, make sure your repo is up to date, and remake it from scratch.

It might sound like "effort" but to guide you through the process of not remaking it will probably take much longer for a small change like this.

**Comment by Dinopeaks** [comment]
yea now that i know what i am doing it will take like 20 mins to reset up 
just close it

**Pull request closed without merging**
