### PR TITLE
[MIRROR] Techwebs update: Syndicate technology, adds console graphical/list toggles, fixes materials not being able to be put in

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/33393
--------------------
all uplink items now can unlock syndicate tech.
decloner moved to syndicate tech, which now contains that, large ebows, cyborg illegal upgrades, and suppressor.
Fixes #33321

### CODE REVIEW

**Comment by ghost** [comment]
so i can drop a 1 tc item with syndie stuff to unlock energy crossbows?

gee bill, how come your codebase is allowed to buff antag science even more?

**Comment by ghost** [comment]
Two Entire Syndicate Hot Dogs

**Comment by JohnGinnane** [comment]
@McBawbaggings @Dudeinyourbackyard want revert of this?

**Comment by xTrainx** [comment]
something something cargo null crate

**Comment by JohnGinnane** [comment]
Welp I think this has to be merged to keep up to date. I'm not 100% how much this messes with our general gameplay but people are welcome to nerf it or something

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
