### PR TITLE
Revert "The PR that makes medborgs actually useful without needing mid-game research."

### PR DESCRIPTION
**Pull request by ghost**
Reverts HippieStation/HippieStation#12554

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
what does this do

**Comment by Punkinguy** [comment]
-1

**Comment by mkikt4743** [comment]
why revert it? seems fine, works fine, is cool -1

**Review by Neotwr — CHANGES_REQUESTED** [review]
update your PR's body using the appropriate template explaining Why It's Good For The Game

**Comment by ghost** [comment]
This isn't one of those PRs. I've asked the head maintainer to approve these, except the one that needs fixed, as a personal favor. I'm pulling my work out of this codebase.

**Comment by carlopault** [comment]
-2

**Pull request closed without merging**
