### PR TITLE
you can now black list reagents from strange seeds using can_synth_seeds

### PR DESCRIPTION
**Pull request by RafRoq**
had to edit a tg file to implement this, created a new proc: get_random_reagent_id_seeds(), created a new var: can_synth_seeds
:cl: uBadush
code: created a new var for reagents to black list reagents from strange seeds only
:cl:

@Jujumatic everything you wanted is here minus modularization of the tg line

### CODE REVIEW

**Comment by Jujumatic** [comment]
:)

**Review by Jujumatic — APPROVED** [review]

**Comment by Manly-Dwarf** [comment]
honestly I don't like this constant snowflake blacklist code
if we gotta keep blacklisting shizzle then maybe there's a problem with the way all of this is designed?????? i dunno mang

+1 i guess whatever it'll make carbonhell take a shower

**Comment by RafRoq** [comment]
What do you mean manly

**Comment by Jujumatic** [comment]
needs votes

**Comment by earthmoonjune** [comment]
+1

**Comment by Jujumatic** [comment]
@headmin ?

**Comment by Jujumatic** [comment]
headmins?

**Comment by Jujumatic** [comment]
fuck it has 1.5 im just putting it in

**Pull request merged**
