### PR TITLE
[MIRROR] Cargo Update: Nanotrasen Supply Drop Pods!

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/33436
--------------------
# [awww yeaah binch](https://user-images.githubusercontent.com/29008542/33801297-e0ab33c8-dd24-11e7-9a9b-1dd853b5a0ad.png)

- Adds the Bluespace Drop Pod , an experimental Nanotrasen railgun-launched supply drop. Ordered from a "Express Supply Console", this will ensure the fastest possible route for any ordered supply. 
~~- Every map barring Omegastation now has an express cargo console located in the Quartermasters office.~~
-The board is now obtainable through RnD, rather than having the console spawn on maps.

- Boxstation and Pubbystation have been given warehouse area defines.

image

:cl: MrDoomBringer
add: Added the Bluespace Drop Pod, a Nanotrasen delivery system designed for maximum delivery speed. Supplies can be ordered at an Express Supply Console **(researchable from RnD)** for twice the cost, but at ~1/40th of the delivery time! Please note, the Drop Pods move pretty fast. It might be smart to stand back from their landing zone.
/:cl:

### Video of it in action: https://gfycat.com/AlarmingIcyGroundhog

**For too many years, Cargonia has been oppressed, depressed, and re-pressed, by the slow and cumbersome movement of the supply shuttle. After hours of begging and pleading around on coderbus, I can present to you the ultimate cargo utility.** 

- This update adds room for a certain level of progression with cargo, allowing for extra money to be spent on extra-fast delivery times. The drop pod itself picks a random, unblocked turf in the cargobay, then crashes down upon it, creating a small explosion and damaging some tiles. 

  - The explosion exists to act as a secondary act of balance: the drop pod is intended to be used for a few VIP deliveries. Ordering in bulk will still require use of the shuttle, unless you are prepared to fix the shit out of an explosion-riddled cargo.

image

- Because of the nature of the mechanic, it is very easy to spend a lot of money _very_ quickly. For this reason, a separate console was created: so that it could be placed in the safety of the Quartermaster's office, away from the sausage fingers of incompetent greyshits and rookie cargotechs.

- [The people crave this shit, yo. I'm a coder of the people.](https://i.imgur.com/TQHTUjK.png)

- **Why does it shoot in, explode, then teleport out? Why not teleport in then out?**
  - Because, just like a hand-teleporter, the drop pod has a beacon at Centcom or wherever, but not at the station. Thus, the railgun (located on a nearby warehouse station or some shit) gets it to the station, and bluespace technology sends it back. duh

-Because the board is now printable from the cargo-lathe, a QM-ID lock has been added to prevent greyshits from stealing a board or abusing the console too easily.

### This is my first non-sprite PR so please rip my code a new asshole

bonus: sprites are nonfinal and subject to change. I've been thinking of [some different styles?](https://i.imgur.com/LMC9qX8.png)
Current sprite is based on mining shelter pallet. Not sure why I chose that.

edit: emagging now allows the destination to be anywhere on the station, rather than just cargobay. Can be reset by multitooling the board(so it doesn't just ruin cargo)

edit: now has a QM-ID lock
edit: The express console  now longer spawns on maps. Rather, it's board is now unlockable through RnD, printable from the Cargo Protolathe

### CODE REVIEW

**Comment by Pyko1** [comment]
On a quick glance the map changes look like they can be just copypasted over as our areas should be identical around there.

**Comment by Pyko1** [comment]
not sure why the packs conflicted, unless there were some undocumented hippie changes, or pack datums in a wrong place.

They are now gone tho.

**Comment by Pyko1** [comment]
The map changes are prolly easier to do on an another PR after this is merged.

**Comment by Pyko1** [comment]
welp something wrong with typepath, and cant fix now.

**Comment by Pyko1** [comment]
welp, seems to work now.

Someone else check my upstream hijacks.

**Comment by Pyko1** [comment]
Basically just fixed merge conflicts (possibly removed some undocumented hippie cargo changes), and added the files to hippiestation.dme

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
