### PR TITLE
Created supermannitol, more powerful version of mannitol that cures severe traumas

### PR DESCRIPTION
**Pull request by Jujumatic**
Changed this up after some feedback, you need to make this using 1 plasma, 1 uranium and 1 mannitol.

This is a more potent form of mannitol that cures brain damage faster, cures minor traumas and cures severe traumas, with an OD limit of 30. if you OD, enjoy lol

### CODE REVIEW

**Comment by praisenarsie** [comment]
lol just get a doctor

**Comment by JohnGinnane** [comment]
let's get @HippieStation/head input

**Comment by praisenarsie** [comment]
again it takes like 2-3mins at most to do surgery it's not that long, don't make the game easier

**Comment by JohnGinnane** [comment]
i'm not for or against this but closing pr because "lol just get a doctor" isn't cool

**Comment by Jujumatic** [comment]
>doctors in hippiestation
LOL

>doctors in hippiestation that will actually do surgery on people
LMFAAOOAOOOO

**Comment by JohnGinnane** [comment]
Having thought about it though I prefer if there wasn't a shortcut to fix traumas, but my vote means nothing 🤷‍♂️

**Comment by Jujumatic** [comment]
A simplified version would be good

**Comment by Jujumatic** [comment]
Adjusted the mannitol to only have a 1% chance to cure severe traumas, maybe that helps a bit.

**Comment by Manly-Dwarf** [comment]
@praisenarsie fuck off

besides that, I like it. Doctors barely exist on the station and usually when they take you into surgery they'll either be hilariously incompetent, anesthetize you and then forget, or be changelings. also thanks to a certain, stupid PR self-surgery isn't as efficient any more, since you'll "finish... just about!" and deal huge damage to yourself.

Mannitol doesn't really have a downside/overdose effect, though. So you could in theory just chug a shitton of mannitol and be immune to brain traumas.

**Comment by JohnGinnane** [comment]
which kinda makes brain traumas useless

**Comment by Manly-Dwarf** [comment]
ye, but it's either a useless feature or a detrimental feature. I'd go with useless any day. Besides we can always give mannitol an overdose in the future

**Comment by JohnGinnane** [comment]
or we could not completely neuter a (already rare-to-get) feature..

**Comment by Manly-Dwarf** [comment]
yeah but you're ugly

**Comment by JohnGinnane** [comment]
FYI, this PR makes this one: https://github.com/HippieStation/HippieStation/pull/7452 kind of one sided. There's no risk with pumping yourself full of mannitol and so people can get themselves a virtually free imaginary friend

**Comment by Jujumatic** [comment]
what if i added an overdose limit of say, 30? and if you reached that OD limit you'd start taking lots of brain damage instead?

**Comment by Manly-Dwarf** [comment]
Most mannitol pills are 50u, last I remember.

**Comment by Jujumatic** [comment]
right, OD limit of uuuhhh 55? idk doesn't seem like a lot of people would even reach that

**Comment by Jujumatic** [comment]
changed this whole thing up, come take a look

**Comment by Carbonhell** [comment]
No, a chem to make something that exists right now just easier to deal with seems boring. -1
Closing

**Pull request closed without merging**
