### PR TITLE
Added 2 variants of instant bear to traitor uplink

### PR DESCRIPTION
**Pull request by Arzion5**
:cl:
add: Added instant bears to traitor uplink! These aggressive bears can be summoned under the "Badass" section and is useful in escaping from a dangerous situation or distracting people.
tweak: The syndicate has accidentaly misplaced bears into their syndicate crates. Syndicate crates have a very rare chance of containing hostile bears.
/:cl:

Gimmicky and fun item for traitors.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
hahaha yes

**Comment by Spankmaster1066** [comment]
I like it a lot but 1 TC is pretty cheap to summon a huge bear. they're hard to kill, maybe make it 2/4

**Review by ghost — DISMISSED** [review]
change to 2 and 4 TC

**Comment by Arzion5** [comment]
Actually, the bear has 60 health, which translates to 3 laser shots or 4 circular saw hits. The combat bear has twice the health.

**Comment by KayeArray** [comment]
Considering the bears will target the traitor as well I don't see any pressing balance concerns.
However I don't like the idea of this appearing in the surplus crate.

**Review by KayeArray — DISMISSED** [review]

**Comment by Arzion5** [comment]
I'll push a change to remove bears from the surplus crates if they somehow end up breaking the cargo shuttle

**Comment by tortellinitony** [comment]
Make it just an "instant Russian bear" where you have a bear plushie, but instead of adding water, you add vodka.

**Comment by Arzion5** [comment]
I'll make a PR for that at another time

**Comment by ghost** [comment]
Sure +1

**Comment by dreamcrab** [comment]
Make it just an "instant Russian bear" where you have a bear plushie, but instead of adding water, you add vodka.

^^^^^^^^^^ 1 million times this, i will say yes when this exists

**Review by ghost — COMMENTED** [review]
code is ok

**Comment by ghost** [comment]
stale.

**Pull request closed without merging**
