### PR TITLE
Upstream merge redo

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

I think this will work.

### CODE REVIEW

**Comment by yoyobatty** [comment]
Welp, I've fixed the tools having their executable permissions being removed, but now nothing compiles.

**Comment by k-k-karma** [comment]
the race is still on, coming for your ass boy

**Comment by yoyobatty** [comment]
Honestly, at this point if you can get it done by tomorrow, I would be more happier.

**Comment by ghost** [comment]
add `require_near = TRUE` to holotool when you merge https://github.com/tgstation/tgstation/commit/15532fae2889a6944686e604098524e7e654400b

**Comment by Jujumatic** [comment]
Creating system restore point...

**Comment by Jujumatic** [comment]
Ok Mommy told me it's my turn to press the merge button :))

**Review by Jujumatic — APPROVED** [review]

**Pull request merged**
