### PR TITLE
75% of players want peepee poopoo

### PR DESCRIPTION
**Pull request by ghost**
ook ook

whuy

:cl: Thefastfoodguy
add: Monkeys can now throw shit at you
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
no

**Comment by KayeArray** [comment]
mfw

**Comment by PopNotes** [comment]
no merging until it's called monkey residue

**Comment by tortellinitony** [comment]
stop

**Comment by Blute1** [comment]
mfw

**Comment by Blute1** [comment]
put reagents in the reagent locations????

**Comment by dreamcrab** [comment]
i already said the only way poo is getting added is if you do it the way outlined in the ass update

no no no

**Comment by blobbernaut** [comment]
i will destroy you if this is merged

**Comment by ghost** [comment]
This was already closed last time, let's not do this again

**Pull request closed without merging**
