### PR TITLE
Sets shadowling probablity to 2.75

### PR DESCRIPTION
**Pull request by ghost**
We rarely reach the required pop anyways

:cl: Thefastfoodguy
tweak: Shadowling is 1.375x more likely to roll
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
i don't think probabilities can be floats?

**Comment by ghost** [comment]
in that case, could we just like, multiply all the possibilities by 10?

**Comment by Pyko1** [comment]
I thought we cant actually change the config that the server uses directly?

**Comment by Pyko1** [comment]
aka if want to do it it has to be done with server access.

**Comment by ghost** [comment]
Config is not changed trough Github, please get in touch with @HippieStation/head to change this

**Pull request closed without merging**
