### PR TITLE
Readds stocks

### PR DESCRIPTION
**Pull request by JF260**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Added two stock exchange consoles in cargo.
/:cl:

## About The Pull Request
I opened a suggestion for this, and it was approved, but noone coded it, so I took things into my own hands. Disclaimer: This is my first attempt at code, and it seems everything works, but just be warned its amateurish and might be bugged. The suggestion is here: https://github.com/HippieStation/HippieStation/issues/10496
## Why It's Good For The Game
See the suggestion.

## Double Edit: Looks like I need to make a new pull request to pull this one, cya later space cowboys

### CODE REVIEW

**Comment by k-k-karma** [comment]
Have you fixed the bugs where stocks can give cargo infinite money?

**Comment by k-k-karma** [comment]
also what did you delete in the map

**Comment by Jujumatic** [comment]
seems he edited the map and didn't run that weird bat file to fix whatever's in the map

**Comment by JF260** [comment]
> Have you fixed the bugs where stocks can give cargo infinite money?

Thats something we can do once stocks exist again. I'm not quite experienced enough for it yet, but should this pull request be merged, i'll see if I can find someone capable.

**Comment by JF260** [comment]
> seems he edited the map and didn't run that weird bat file to fix whatever's in the map

I know I edited the main post for this already, but to my knowledge, fixed.

**Comment by k-k-karma** [comment]
> > Have you fixed the bugs where stocks can give cargo infinite money?
> 
> Thats something we can do once stocks exist again. I'm not quite experienced enough for it yet, but should this pull request be merged, i'll see if I can find someone capable.

fix this or i close the pr

**Comment by JF260** [comment]
> how about, we first make this at least modular?

I UNFUCKED IT

**Comment by k-k-karma** [comment]
it's not modular yuet

**Comment by JF260** [comment]
> it's not modular yuet

what do you mean, the only changes outside of the hippie folder are hippiestation.dme and hippiestation.dmm, both of which pyko said i could edit without making it not modular

**Comment by k-k-karma** [comment]
are you fucking thick? look at the diff

**Comment by JF260** [comment]
> are you fucking thick? look at the diff

oh wait fuck i need to switch the repository, brb

**Comment by JF260** [comment]
> are you fucking thick? look at the diff

fuck imma have to delete this and make a new one

**Comment by JF260** [comment]
> > are you fucking thick? look at the diff
> 
> oh wait fuck i need to switch the repository, brb

Done https://github.com/HippieStation/HippieStation/pull/10684

**Comment by k-k-karma** [comment]
-

**Pull request closed without merging**
