### PR TITLE
[MIRROR] Emagged clown cars now come with siege-tank mode.

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40190
--------------------
:cl: Floyd / Qustinnus (thx to mrdoombringer for sprite + idea)
add: The clowncar now comes with an inbuilt cannon that can be activated by emagging its circuits
fix: cars can only kidnap if they have the CAN_KIDNAP trait
fix: removes a dot too much in a to_chat in clown car actions
/:cl:

lol i'll run out of screen space for all these buttons soon
https://streamable.com/yq17r

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
This needs admin approval.

But I highly doubt any of them will say no.

**Comment by earthmoonjune** [comment]
+1

**Comment by Carbonhell** [comment]
worried.jpg
eh sure, +1

**Comment by Maroonenahmoron** [comment]
Hilarious. +1

**Comment by GuyonBroadway** [comment]
Oh snap, the +1s

**Review by GuyonBroadway — APPROVED** [review]

**Pull request merged**
