### PR TITLE
Lavaland atmos, but I cherry-picked it edition

### PR DESCRIPTION
**Pull request by ghost**
closes #11840

### CODE REVIEW

**Comment by lunaman22** [comment]
what did you change

**Comment by ghost** [comment]
i used `git cherry-pick` instead of copy-paste

**Comment by lunaman22** [comment]
what's it do, i might use this to steal good shits later

**Comment by optimumtact** [comment]
please make sure you attribute this change in the changelog or I will be forced to send a DMCA request MRTY

**Comment by lunaman22** [comment]
sure, we'll credit our resident coder ninjanomnom, why wouldn't we, after all he did all of the work.

also steamport you fucking idiot

**Comment by ghost** [comment]
@optimumtact i cherrypicked the auto-changelog too, incase you were too blind to notice.

**Comment by optimumtact** [comment]
thanks MRTY

**Comment by lunaman22** [comment]
oh yeah i forgot to +1 this lmao

**Comment by biggiOS** [comment]
blus juan

**Comment by 88scheming88** [comment]
+1 im back bitches

**Comment by ghost** [comment]
+1 i guess

**Comment by Majick1** [comment]
+1 again, just carry over the votes from the other one

**Comment by cris5311** [comment]
+1 for the same reason I +1ed the other one

**Comment by AnthonyJNgo** [comment]
I'll testmerge this tonight.

**Review by yoyobatty — APPROVED** [review]
I mean, this technically is tg code so why not.

**Pull request merged**
