### PR TITLE
[MIRROR] Adds corpse flowers

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/44322
----------------------------
## About The Pull Request

Corpse flowers are a type of plant that produces a very strong and terrible smell, hence the name. To represent this it produces a decent bit of miasma overtime 12-32 times as much as a corpse that scales with the stats of the seed. Its not as much as it sounds, I play tested, ran the numbers, and set constraints to make it hard yet not terrible to maximize production on.

- The harvest works the same as starthistle to reinforce the idea that it needs to be planted to produce miasma and that it is easier to make more of the plant
- The plant mutates from starthistle and starthistle no longer mutates into harebells as harebells natural spawn anyway
- The miasma production only starts when it is about to bloom
- Miasma production only works around normal pressure
- The speed goes off yield and the pressure constraints off potency
- The plant isn't the most potent for antag use due to the fact that you can just harvest it to stop it
- Cargo and Science point values have been lowered to a fourth of what they used to for miasma (which is still pretty high in my opinion)
- Miasma mining will be easier to setup but require more maintenance than monkey room strats
- Its worth noting since it inherits from starthistle it shares its same base long lifespan and high endurance

Multiple trays will be required for decent output so either 1. The botanists commit their department to it 2. atmos/sci takes over garden and is capped at 6-8 trays (what I see happening) or 3. The atmos/sci builds additional trays which is time consuming to the point where the output and setup time is close to monkey rooms

All of these use cases require maintaining the atmosphere constraints and plant needs so that would be additional time cost to consider

If anyone thinks the sprites are bad and wants to make more I wouldn't mind

## Why It's Good For The Game

Creates a new botany plant that goes in a different direction in overall design for variety

## changelog
:cl: Granpawalton 
add: Added a new plant called the corpse flower that produces miasma while it is harvestable
tweak: Harebells no longer mutate from starthistle
balance: miasma's science and cargo point values have been reduced by 75%
/:cl:

### CODE REVIEW

**Comment by mikolaj007** [comment]
+1, sounds good. sure, it nerfs miasma a bit, but adds something interesting to botany.
killing fuckloads of monkeys wasnt really worth the money anyway. i did that once and it sucked generally

**Comment by WarRage333** [comment]
I don't know what happened to miasma but i didn't see it for a few month(s?) now.

**Comment by mikolaj007** [comment]
nothing happened, people just dont usually leave corpses in high enough density to generate it

**Comment by Majick1** [comment]
+1 looks pretty well thought out

**Comment by MaterialisticThings** [comment]
+1 Pretty cool

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
