### PR TITLE
Holotool can be used to pulse and cut wires

### PR DESCRIPTION
**Pull request by xTrainx**
[Changelogs]: # fixes holotool
tweak: pulsing and cutting wires now checks if you have a holotool in hand

[why]: # holotools are incomplete because they cant be used to h4xx0r the door, vendors and whatnot, mostly because of how it is designed. not only that, but the time it takes to change the holotool current tool is a bit of a put off for some people, so this change is aimed to fix those in regard of wire cutting and pulsing, by making it so the holotool can be used to both cut and and pulse, no matter the holotool current state (also i have no idea how to make it so it checks the current tool)

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
How about adding comments next to the lines you added saying ```//HIPPIECODE```... also can you add checks to make sure they're probably set on wirecutters / multitool

**Comment by ghost** [comment]
Just remove the holotool, it's a bunch of garbage really

**Comment by xTrainx** [comment]
how do i vars

**Comment by ghost** [comment]
> how do i vars. -xTrainx

**Pull request closed without merging**
