### PR TITLE
The Floor Cluwne

### PR DESCRIPTION
**Pull request by KayeArray**
:cl: banthebantz
add: Nanotrasen would like to once again remind the crew that there are no entities living underneath the station floor.
/:cl:

Have a very spooky Halloween.

Adds a floor cluwne mob which stalks and torments victims before dragging them underneath the floor to be eaten or cluwnefied.

It's an adminbus mob that can be spawned with a special verb.

### CODE REVIEW

**Comment by Arzion5** [comment]
I would like to see floor cluwnes added to the game because the potential for F U N is pretty big.

**Comment by tortellinitony** [comment]
Does it have the sweet animation that goonstation has? Can players control it?

**Comment by KayeArray** [comment]
It has a floor opening animation.
It cannot be player controlled.

**Comment by Arzion5** [comment]
Dropped

**Comment by tortellinitony** [comment]
I'd prefer it to be optionally player controllable, but I can see how that would be difficult

**Comment by GuyonBroadway** [comment]
I think the mob itself is neat enough to give a go. We could work on making it player controlled at some point later.

**Comment by Arzion5** [comment]
Undropped

**Comment by KayeArray** [comment]
I'll do player controlled in another PR because it'll pretty much have to be a completely rewritten version

**Comment by TungstenOxide** [comment]
+1 sounds spooki af

**Review by j-mie — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
!KONH !KONH

**Pull request merged**
