### PR TITLE
[MIRROR] Ports far too many haircuts and beards.

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43564
----------------------------
inb4 snowflake
Ports some hairstyles, mainly from vore and bay.

Variety is the spice of life.

Changelog
:cl:
add: Adds far too many haircuts.
add: Adds a decent amount of beards.
/:cl:

### CODE REVIEW

**Comment by k-k-karma** [comment]
bot forgot the DMI, lol

**Comment by Manly-Dwarf** [comment]
Bot has forgotten the dmi a thousand times, Karma. Janitor ERT is missing sprites, Plasmamen are missing sprites, we're missing so many sprites.
We need an upstream sprite merge.

**Comment by k-k-karma** [comment]
why have i just only been informed of this

**Comment by Jujumatic** [comment]
Because your retarded ass was saying the bot was already merging the sprites themselves

**Comment by k-k-karma** [comment]
> Because your retarded ass was saying the bot was already merging the sprites themselves

yeah and you fucking told me it was dipshit

**Comment by ghost** [comment]
jesus christ

**Comment by mikolaj007** [comment]
Nothing wrong with variety

**Comment by Jujumatic** [comment]
>yeah and you fucking told me it was dipshit

Yes please quote me on where I said that please

**Review by yoyobatty — DISMISSED** [review]

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
