### PR TITLE
Makes Neovgre brassy

### PR DESCRIPTION
**Pull request by Arzion5**
:cl:
imageadd: Neovgre now looks like it is made of brass.
/:cl:

A simple recolor, it is now looks more consistent with the clock cult.

dreamseeker_2017-11-11_09-50-14
dreamseeker_2017-11-11_09-50-56
dreamseeker_2017-11-11_09-51-22
dreamseeker_2017-11-11_09-51-46

### CODE REVIEW

**Comment by dreamcrab** [comment]
dope shit but how does it look on the clock cult tiles? im worried that it might be hard to see maybe

**Comment by Arzion5** [comment]
In theory, it shouldn't be difficult to see because it is both outlined and also more detailed. I will update on how it looks like.

**Comment by dreamcrab** [comment]
i dont foresee it being an issue but i just wanna make sure yaknow

**Comment by ghost** [comment]
yes please
the purple colour scheme is cool but isn't consistent with cluck colt

**Comment by ghost** [comment]
make a screenshot of it on the ratvar tiles and i'll 1+ it

**Comment by Arzion5** [comment]
Reebe tiles
dreamseeker_2017-11-11_11-06-34
Clockwork tiles/Summoned Rat'var tiles
dreamseeker_2017-11-11_11-07-01

**Comment by ghost** [comment]
peeerfect +1

**Comment by dreamcrab** [comment]
+66
36366

**Comment by ghost** [comment]
looks kinda ugly tbh

**Comment by GuyonBroadway** [comment]
Clock-cults colour scheeme is typically brassy light and darks for the bulk of metal and red/deep orange for the highlights and important bits. try changing the yellows back to the reds of the original and see how it looks.

**Comment by PopNotes** [comment]
wait isn't this my recolor

**Review by ghost — APPROVED** [review]

**Pull request merged**
