### PR TITLE
Upstream merge

### PR DESCRIPTION
**Pull request by ghost**
this is the right branch

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Code looks OK

**Comment by GuyonBroadway** [comment]
why is there no "build this" for travis?

**Review by GuyonBroadway — APPROVED** [review]
looks Oke

**Comment by GuyonBroadway** [comment]
I'm going to try something a sec.

**Comment by GuyonBroadway** [comment]
YEEESSSS!!!

IT WORKS!!

**Comment by GuyonBroadway** [comment]
mergeldergle code approvey

**Pull request merged**
