### PR TITLE
Temp fix for fire extinguishers not damaging slimes

### PR DESCRIPTION
**Pull request by Jujumatic**
Working on fixing fire extinguisher code, I'm leaving this PR here so others can help out. If I did this correctly I've marked some pages of code that should be checked to make sure everything is fine. If they're not marked yet I'll mark the files with a new line or something when I can.

### CODE REVIEW

**Comment by Jujumatic** [comment]
Possible idea - 
```
/*
 *	Water reaction to a mob
 */

/datum/reagent/water/reaction_mob(mob/living/M, method=TOUCH, reac_volume)//Splashing people with water can help put them out!
	if(!istype(M))
		return
	if(method == TOUCH)
		M.adjust_fire_stacks(-(reac_volume / 10))
		M.ExtinguishMob()
	..()
```
I may be able to add water to always affect a slime and call the apply_water proc whenever they are exposed to any water - then it *should* call that every time the slimes get in contact with the fire extinguisher's spray. It may also be able to damage slimes by merely spraying them with water, which seems like the intended design to begin with. Thoughts?

Also I seem to be unable to put that code into a code block, plis help me figure out how to do that

**Comment by Jujumatic** [comment]
Ok, progress! 

Made apply_water work whenever a slime gets into contact with any water whatsoever, fixing fire extinguishers not damaging them and also making water beakers a viable tactic to killing slimes, albeit much less efficient than spamming the fire extinguisher. Monkey cubes are still broken though. Plis help

For the apply_water to be called with the beaker, you'd need to throw the beaker directly at the slime so it splashes onto them rather than going on turf, which would call apply_water anyway. So it may have also fixed a potential issue with water beakers not doing anything to slimes when thrown at them?

**Comment by Jujumatic** [comment]
I've decided to not mess with the code any further as I can't seem to figure out what's causing monkey cubes to not expand. However this should fix fire extinguishers and apply damage to slimes correctly. Will create an issue report for monkey cubes in the meantime. This PR can be merged now.

**Comment by JohnGinnane** [comment]
multiline codeblocks use three of this: `

so you do 
\```
hello world
\```
and it looks like
```
hello world
```

**Comment by JohnGinnane** [comment]
I'll have a look this tomorrow/this weekend see if I can find the cause

**Comment by JohnGinnane** [comment]
I've done some testing and found that the extinguisher does work on slimes

**Comment by JohnGinnane** [comment]
I also tested the monkeys and there's a system in place to stop you spawning multiple monkeys on a single turf, so you have to use extinguisher on a turf that only contains one monkey cube

**Comment by Jujumatic** [comment]
@JohnGinnane It didn't work for me even when there was only 1 monkey cube on the turf

**Comment by Jujumatic** [comment]
Wait what why did that merge just undo the scream trait. ugh

**Comment by Jujumatic** [comment]
This thing is completely fucked and being retarded so I'm closing this PR and reopening a new one

**Pull request closed without merging**
