### PR TITLE
glass hatchets [do not merge]

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: # adds glass hatchets made out of 1 wrench, 1 cable cuffs and 1 glass shard
:cl: 
add: glass hatchet
imageadd: added the glass tomahawk sprite from /vg/station btw thanks /vg/
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
#
it's cool

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Thanks for the PR "optional name here" ;¬)

Also this looks awesome

**Comment by ghost** [comment]
hehehe just didnt bother its in dev also the sprites are ripped from /vg/station i asked for permission on their discord and they said sure tho.

**Comment by JohnGinnane** [comment]
Ah, that's handy. How does this compare to the botanist hatchet? Or the fireaxe?

**Comment by ghost** [comment]
the stats are exactly the same as of the botanist hatchet, its just ghetto-makeable.
accepting any feedback for tweaks tho. i wanted to try adding more bleed but dunno

**Comment by praisenarsie** [comment]
could give it the caltrop component

**Comment by praisenarsie** [comment]
when it chops logs, the glass should break instead of chopping the log

**Comment by ghost** [comment]
its space glass, if it can withstand the pressure of vacuum it should withstand some little hardened cellulose cilinders, it's pointy should distribute force

**Comment by JohnGinnane** [comment]
i want this in because more greytide weapons the better

**Comment by praisenarsie** [comment]
sorry nope john, approval system

**Comment by JohnGinnane** [comment]
))

**Comment by JohnGinnane** [comment]
@HippieStation/head input please

**Comment by earthmoonjune** [comment]
cool idea. +1

**Comment by praisenarsie** [comment]
stale, apparently doesn't work, i might work on this in the future but for now

close

**Comment by JohnGinnane** [comment]
@praisenarsie are you doing this

**Comment by praisenarsie** [comment]
nope

**Pull request closed without merging**
