### PR TITLE
[MIRROR] Removes pre-scanning

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/41731
----------------------------
:cl:
del: You can no longer pre-scan in the cloner
/:cl:

Edited:

Scanning reduces the consequences of death to a far more minor level than is reasonable. Its effect on the game is to reduce tension by making scanned crewmembers immortal while cloning still stands, thus making the game generally more boring.

Scanning also opens up the issue of post-scan knowledge, which is especially problematic given tgstation's usual stance on RP knowledge restriction. Post-scan knowledge cuts down the variety of stealth antag playstyles, and as such makes the game more boring yet again.

It makes the game more boring, so it should be removed.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Nice /tg/ grudgecode.

**Comment by yoyobatty** [comment]
We're killing this asap btw.

**Comment by tortellinitony** [comment]
holy fuck they merged it! People were SUPER opposed to this on /tg/

**Comment by ghost** [comment]
lmao how grudgeful,  typical idiot kids getting pwned and nerfing things justifying that its for the greater good n shit,  how gay

**Comment by Jujumatic** [comment]
kill this gay asap

**Comment by ghost** [comment]
44 thumbs down.

**Comment by ghost** [comment]
Upstream is gonna revert and remove auto cloning which is the right decision to make here.

**Comment by k-k-karma** [comment]
oh my fucking god it's a complete rework too so it'sgoing to be a pain to modularize out

**Comment by earthmoonjune** [comment]
one of the gayest prs to ever grace github as a whole

**Comment by AnthonyJNgo** [comment]
-1 for prescan removal and -1 for autocloner removal.

**Comment by ghost** [comment]
just mirror the old cloning.dm file and untick the new one, it's easier

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
