### PR TITLE
[Ready] adding some (tame) mining circuitry

### PR DESCRIPTION
**Pull request by Shdorsh**
Done it for beestation first, now I'm here: BeeStation/BeeStation-Hornet/pull/1456

The station's main goal is to be a plasma mining facility near an asteroid, so circuits should come in handy aswell. I've been thinking of making this for a while, hope you like it.
Why It's Good For The Game

Hopefully adds more interaction between the different parts of the station. A thing that should be noted though is that most assemblies and integrated electronics break when exposed to the harsh conditions of an ash rain, so I am not really worried about it being too imbalanced.
Changelog

🆑
add: A scanner circuit that can analyze 1 rock at the same time, working with a reference given by a sensor.
add: A drill circuit that can mine a rock (only the ones found on the asteroid ofc) on its own. It can only mine 1 rock at the same time and it takes some time to do so.
/🆑

### CODE REVIEW

**Comment by MrEpicSax** [comment]
+1 Kind of redundant but sounds nifty

**Comment by Shdorsh** [comment]
You could actually keep one around and mine 1 additional tile passively. It is still slower than a regular pickaxe, but if you dislike spamming the click-button, I guess it's cool.

Edit: Also mmibots might like to have some mining capabilities, tho being an mmibot on mining is a bit risky.

**Comment by karmaisblackandbluepilled** [comment]
Hmm, could I make a swarm of bots to mine perhaps?
+3

**Comment by Shdorsh** [comment]
With too much time on your hand yeah sure, but they probably won't survive the next ash storm or end up in lava with the limited pathing options or use up more of the iron you are mining for the resources than needed. I guess you could try building a few mechanisms to cover all the tiles around you and have aoe mining, tho plasma cutters would still be better.

**Comment by carlopault** [comment]
+2 sounds nifty

**Comment by earthmoonjune** [comment]
+1

**Review by Neotwr — APPROVED** [review]

**Comment by MrEpicSax** [comment]
bump, merge when

**Pull request merged**
