### PR TITLE
Adds our hippie_toggles and ports SOUND_TTS to it

### PR DESCRIPTION
**Pull request by Carbonhell**
So that we don't have to worry about tg's and it should also resolve the problem of some people having it off by default (could've been fixed by previous john's pr,shrug)
Also removes a random wild shadowling global var which i have no clue why it was still there.
From now on, to make new toggles you can use "hippie_toggles"
To save and load preferences, hippie_pref_load and hippie_pref_save
And hippie_dat_replace isn't only useful for loadout now, it can be used to add any kind of html to any pref tab
:cl:
add: Hippie toggle preferences. Now it'll be easier for us to add new toggle options. First example is SOUND_TTS, next one will be footsteps.
fix: Fixes some people having tts off by default. It has been toggled on for everyone, you can toggle it off in OOC preferences if you do not like it.
/:cl:

### CODE REVIEW

**Comment by Carbonhell** [comment]
dnm

**Comment by Carbonhell** [comment]
Ok yeah, for the preference, it's loaded and then this is called
/proc/sanitize_integer(number, min=0, max=1, default=0)
since we're using default as initial(hippie_toggles), it will start with SOUND_TTS enabled. Although that's the behaviour that it should've had before too so...shrug.

**Comment by Carbonhell** [comment]
i'm dumb
toggles			= sanitize_integer(toggles, 0, 65535, initial(toggles))
it was capped at 16 bits,that's why our pref kept being ignored
so yeah this fixes it.

**Comment by ghost** [comment]
I know some of these words.

+1

Greetings,
Fluxcapacitor1337
Head Administration

**Comment by ghost** [comment]
i know the best words

**Comment by Carbonhell** [comment]
This is ready but not tested, and i need to add a changelog

**Comment by Carbonhell** [comment]
changelog added,just needs testing now,

**Comment by Carbonhell** [comment]
Can be merged.

**Comment by Carbonhell** [comment]
Travis is not passing due to an unrelated bug caused by a merged mirror. It's solved,the PR should be fine.

**Review by GuyonBroadway — APPROVED** [review]
Looks OK, if this explodes, blame the entirety of Italy.

**Pull request merged**
