### PR TITLE
Adds a real protolathe 

### PR DESCRIPTION
**Pull request by xTrainx**
[Changelogs]: # 
:cl: xTrainx
add: A real protolathe to rnd
del: A Fake protolathe in rnd
/:cl:

[why]: # https://hippiestation.com/threads/add-the-non-departmental-protolathe-board-back.8246/page-2 accepted suggestion

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
and now we play the "salty tg hamfist nerffaggots" coming in and bitching.

**Comment by Carbonhell** [comment]
Idea already accepted, although you forgot to mapmerge. Dont forget next time pls

**Review by tortellinitony — CHANGES_REQUESTED** [review]
Mapmerge and fix conflicts

**Comment by ghost** [comment]
No.

**Comment by praisenarsie** [comment]
fuck off, don't try to remove new rnd

**Comment by GuyonBroadway** [comment]
Accepted forum suggestion by way of headcoder Carbonhell

**Comment by Carbonhell** [comment]
idea is already accepted, but there's a map conflict,pls fix

**Comment by praisenarsie** [comment]
the suggestion was shit in the first place because the person either can't accept change or is a 12 year old powergamer.

stop trying to remove techwebs, it's fucking stupid and you're just encouraging the scientist powergame rage

**Comment by Carbonhell** [comment]
no, it isn't encouraging powergame rage,it's giving scientists actual rewards for their job, why shouldn't they be able to use what they develop,it's fucking retarded

**Comment by praisenarsie** [comment]
except they can use what they develop? they can just go to the other departments and say, "mind if i use your protolathe"

jesus christ it's like player and player interaction is rare these days

oh wait

**Comment by Carbonhell** [comment]
that isn't what actually happens though, they either break in or they just don't give a fuck and give up, plus noone was against the idea in the suggestion thread other than pyko,you could've posted your opinion in it before smh

**Comment by ghost** [comment]
if the issue is science can print broken shit through it, then it's an issue with science being powercreeped to fuck

i apperciate the removal of the easter egg hunt gameplay from tech webs, but it's a big band aid solution to the powercreep of science recipes

**Comment by praisenarsie** [comment]
> jesus christ it's like player and player interaction is rare these days

i don't check the suggestions subforum, i don't even check the forums at all but in very rare cases i do. either way this pull request is trash and you are making techwebs incredibly redundant if this goes through.

**Comment by ghost** [comment]
This change is terrible, and anyone who thinks it's a good idea to add more powercreep to R&D should go play on /tg/ instead.

**Comment by GuyonBroadway** [comment]
Actually this undoes a hamfisted tg balance change that was very unpopular with our player base. This pr keeps techwebs and departmental lathes but lets sci use all the cool gadgets they spend time unlocking.

**Comment by Pyko1** [comment]
also -1

**Comment by Pyko1** [comment]
the whole unlocked proto was that made sci power creep.

**Comment by Carbonhell** [comment]
Techwebs was made to let departments be able to make good stuff related to them, it was never meant to limit scientists and what they could do, it was like this before and players want it back, if there is a specific issue with a recipe it can be just made harder to get...

**Comment by Pyko1** [comment]
also this isnt even the "approved" suggestion, it was a board on tech storage not a full machine on RnD

**Comment by ghost** [comment]
Maps with diff:

<details><summary>hippiestation</summary>

Old | New | Status
--- | --- | ---
 |  | Modified

</details>
<br>Last updated from merging commit a636f0b5877a3a4be201098f4605cee78508d71c into dbabd8c147298a033ab702557ff413e34d2f48ef

**Comment by ghost** [comment]
the single board is okay in tech storage
but just the machine being there is nah

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Cyberboss** [comment]
@MapDiffBot

**Comment by Carbonhell** [comment]
I would be okay with the full protolathe but it seems like others are against it
Just put the protolathe board inside tech storage then

**Comment by tortellinitony** [comment]
Pretty sure security gets a full protolathe, which makes sense because science can't make guns without security access anyway.

**Comment by Pyko1** [comment]
protolathes are soon obsolate anyways. https://github.com/HippieStation/HippieStation/pull/6987

**Comment by Pyko1** [comment]
outdated and conflicting

**Pull request closed without merging**
