### PR TITLE
Blacklists neurotoxin from state changes

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
balance: Neurotoxin can no longer be forged into ingots/weapons
/:cl:

[why]: This shit is op.

### CODE REVIEW

**Comment by RafRoq** [comment]
do it

**Comment by mikolaj007** [comment]
please no

**Comment by yoyobatty** [comment]
Sorry, but I think we all agree that insta stun daggers that require no skill to make should be removed.

**Comment by k-k-karma** [comment]
it's just a shittier stunbation, real issue is syringe guns. although i'd make it restricted to longswords as the dagger inhand is too hard to see

**Comment by mikolaj007** [comment]
Like poster above said
if im not getting a knife, im getting syringes or stun batons.
Even then, a knife takes more time than getting a stun baton, and its weaker

**Comment by yoyobatty** [comment]
Isn't that the point of those items though? The process of nerfing syringe guns will follow, but stun batons are designated weapons for stuns, so you can exclude that from this argument.

**Comment by RafRoq** [comment]
knife is not weaker than stunbaton, knife has no cooldown or limit of use

**Comment by Manly-Dwarf** [comment]
do it
+1

**Comment by WarRage333** [comment]
Rework neurotoxin instead

**Review by GuyonBroadway — APPROVED** [review]
Code is ok but i want the headmins to weigh in thier +1s.

**Comment by bardofrage** [comment]
Absolutely +1

**Comment by earthmoonjune** [comment]
+1

**Comment by Shdorsh** [comment]
+18

**Comment by DaydreamPuppeh** [comment]
+1

**Pull request merged**
