### PR TITLE
Upgrades Soymilk

### PR DESCRIPTION
**Pull request by ghost**
:cl: McBawbaggings
tweak: Recent intel from Central Command suggests that "Soy Milk" may cause autism when drank in large doses.
/:cl:

Memes.
It could use more FUN though, please suggest shite.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
I had the idea of if you overdosed on soy it would turn you into a woman

**Comment by JohnGinnane** [comment]
holy shit you did it

**Comment by JohnGinnane** [comment]
did you test this?

**Comment by ghost** [comment]
I find the NUMALE thing more amusing which is why I went for it instead.
And mostly tested, there was a bug where "Balding" was meant to be "Balding Hair" but it seemed to work fine on the initial test.

**Comment by ghost** [comment]
Double checked, balding hair is now applied correctly.
WORKING AS INTENDED but probably could use more MEMES.

**Comment by bardofrage** [comment]
Great realism update, would highly recommend merging. +2

**Comment by KayeArray** [comment]
add special attack to soylets where they can suck everything in on screen and gib/destroy anyone containing soy
add a soylet check on life that has a probability to pick from a list of funny nu male quotes

**Comment by Pyko1** [comment]
+1

**Comment by ghost** [comment]
Gimme quotes for the SOYLETS

**Comment by Pyko1** [comment]
Milk is murder?

**Comment by JohnGinnane** [comment]
is this ready it's been 2 days

**Comment by Carbonhell** [comment]
+1

**Comment by ghost** [comment]
+1

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
