### PR TITLE
Map updates for wheezl

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Ministation has an update and uses proper emergency shuttle
/:cl:

## About The Pull Request
Title

Old:
image

New:
image

Difference:
image

## Why It's Good For The Game
Everyone likes map updates

### CODE REVIEW

**Comment by yoyobatty** [comment]
Map diff got cut off sorry

**Comment by carlopault** [comment]
+2 little improvements/polish is good

**Comment by wheezl** [comment]
+3

**Comment by byandaccount** [comment]
+1 lookin gud champ

**Comment by MrEpicSax** [comment]
I may be late to the party but +1 anyway kek

**Pull request merged**
