### PR TITLE
Adds new map to hippie server

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: wheezl
add: Adds ministation2020 to the server
/:cl:

## About The Pull Request

New made made by wheezl, enjoy

image

## Why It's Good For The Game

New map fun

### CODE REVIEW

**Comment by carlopault** [comment]
Can players vote for map change

**Comment by carlopault** [comment]
+2

**Comment by byandaccount** [comment]
+1 lookin gud bro

**Comment by yoyobatty** [comment]
Yes, I will have to set that but yes

**Comment by Zyzarda** [comment]
+2 more maps good, boxstation stale and uninspired

**Comment by neetdev** [comment]
+1

**Comment by wheezl** [comment]
+3

**Comment by carlopault** [comment]
> +3

you can't +3 your own PR. That's cheating

**Comment by wheezl** [comment]
it's not my pr it's yoyo's

**Comment by carlopault** [comment]
> it's not my pr it's yoyo's

oh yeah

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
♥

**Comment by AnthonyJNgo** [comment]
Based

**Review by AnthonyJNgo — APPROVED** [review]
Map changes

**Pull request merged**
