### PR TITLE
Revert "Reverted /tg/'s double space damage"

### PR DESCRIPTION
**Pull request by ghost**
Reverts HippieStation/HippieStation#4753

JEEZ A GRUDGECODE PR GOT MERGED THAT FAST. GET A SPACESUIT, ASSHAT

### CODE REVIEW

**Comment by JohnGinnane** [comment]
homey, that PR was a revert of a /tg/ thing: #4751 

It wasn't discussed at all, and it's a big change

**Comment by dreamcrab** [comment]
why are you so retarded amari

**Comment by ghost** [comment]
> It wasn't discussed at all, and it's a big change

/tg/ pulls are merged, always, regardless of their balance implication.

**Comment by ghost** [comment]
Local Man Literally Does Not Have Enough Brain Processing Power To Distinguish Friend From Foe

**Comment by Blute1** [comment]
>     /tg/ pulls are merged, always, regardless of their balance implication.

thats fucking stupid

**Comment by Blute1** [comment]
>JEEZ A GRUDGECODE PR GOT MERGED THAT FAST. GET A SPACESUIT, ASSHAT

can you ever like not be a fucking sperg christ you represent the server when youre a maintainer

**Comment by Arzion5** [comment]
3 heads approved it, what do you mean it's grudgecode? The damage reduction PR was immediately made after the original PR was made

**Comment by Pyko1** [comment]
should had given the double damage more than 1 round tho, and wait the 24 hours before merge as the revert was technically a feature.

**Comment by Pyko1** [comment]
I mean every time there is something new people test it, this time it was deadler space, and everyone made sure to do holes just to see how deadly it is.

**Comment by ghost** [comment]
we merge /tg/ code because if we don't the pr mirrorer system breaks and we have to do manual upstream merges that can go wrong and also add a lot of stuff making it hard to review

**Comment by ghost** [comment]
@McBawbaggings we have to do manual upstream merges either way, the PR Mirror bot sucks ass

**Comment by ghost** [comment]
@MoreRobustThanYou bullshit, there are a lot of things that "just work" with the mirror bot, sure there are some pulls that need some love, but without it there would be a lot more pain and effort

**Comment by PopNotes** [comment]
build this

**Comment by KayeArray** [comment]
no

3 -1s closing

**Pull request closed without merging**
