### PR TITLE
[MIRROR] Removes the multiverse and its sword

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/30283
--------------------
We have enough TDM variants/admin memes and this is one of the weakest. It's currently holding up the gang removal, which is ironic considering gang has actual gameplay while this mode has none.

See #27872 for more rationale.

:cl: Pubby
del: The multiverse sword is toast
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)

### CODE REVIEW

**Comment by j-mie** [comment]
build this

**Comment by j-mie** [comment]
build this

**Comment by Arzion5** [comment]
Don't merge this >:(

**Comment by ghost** [comment]
build this.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Merge or no?

* only used for murderboning
* admin only
* uses fucking gang code (which is horrid)
* i hate it

**Comment by Arzion5** [comment]
Delet this PR

**Pull request merged**
