### PR TITLE
[MIRROR] Added chemical reaction unit tests

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35478
--------------------
Added a unit test for misspelt chemical IDs in chemical reaction datums, and a unit test for chemical reaction conflicts. Travis will fail because there will be two recipe conflicts until #35479 or a similar PR is merged.

To avoid having to redo a very large number of recipes, possible reactions that require a more extreme temperature will now be chosen over reactions that require a less extreme temperature. For example:

The recipe for carbon dioxide requires carbon and oxygen, and a temperature of at least 777.
The recipe for bicaridine requires carbon, oxygen and sugar, and a temperature of at least 0.
If you add carbon to a reagent container that contains sugar and oxygen, if the reagent temperature of the mixture is 777 or above, the carbon dioxide recipe will always be chosen, because the carbon dioxide recipe has a more extreme temperature requirement.

No mixture should ever have some possible reactions that require cold and some that require heat. If there are ever a combination of reactions that this could happen for, the unit test will catch it.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
neat

**Comment by JohnGinnane** [comment]
I've added a 400K required temp to our sparky chem so it passes the unit test. I think maybe @HippieStation/head should vote on this

**Comment by Carbonhell** [comment]
Ok from me

**Comment by JohnGinnane** [comment]
image

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
