### PR TITLE
Sepia timestop now makes the user immune

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: Whoever does a sepia timestop is now immune to the timestop again.
/:cl:

### CODE REVIEW

**Comment by lunaman22** [comment]
+1

**Comment by biggiOS** [comment]
+1 based and jojokepilled

**Comment by Manly-Dwarf** [comment]
I like the idea of a timestop grenade but it's kinda worthless when it also stops your time, and all of your projectiles, and everything else.

Sure, +1.

**Comment by WarRage333** [comment]
based

**Review by enthethan — COMMENTED** [review]
speedmerge this i died to a nanonigger because it timestopped me aswell skree

**Review by AnthonyJNgo — APPROVED** [review]
lgtm

**Pull request merged**
