### PR TITLE
Moves mining ripley plasma cutter to vending

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: Guyonbroadway
del: The roundstart mining ripley no longer has a chance to spawn with a plasma cutter or diamond drill.
add: You can now exchange your roundstart mining voucher for a plasma cutter, welding tool and welding goggles. 
/:cl:
As per things highlighted in https://github.com/HippieStation/HippieStation/issues/4685 I decided to make the mining ripely plasma cutter a mining vendor choice.

The mech now has No RNG components but miners can use their mining token instead.

### CODE REVIEW

**Comment by bardofrage** [comment]
This is a cool idea

**Comment by ghost** [comment]
too bad you fucking suck bard

anyways This is a cool idea

**Comment by Swagile** [comment]
this is good

now we just need the option to buy the handheld cutter for use by normal miners and miners are finally self sufficient and don't have to beg too much

**Comment by GuyonBroadway** [comment]
Making miners TOO self sufficient means nobody will ever do R&D because why bother if you never get to do anything with it.

**Comment by Swagile** [comment]
you can still get bluespace backpacks and satchels (ore carriers) from RnD, as well as upgrades to your guns and a advanced plasma cutter

the normal cutter just cuts down the amount of time that a miner spends getting ores drastically; and you still need to put ores into the ORM for points to be self sufficient

**Comment by xTrainx** [comment]
sounds gucci +1

**Comment by JohnMcLaime** [comment]
You barely ever get shit from mining, half of the time they do deliver something, it is just 5 sheets of each mineral or some crap,

Miners are already self sufficient, i considering that it is better to go roundstart mining for ripley and faster access to mining and taking rnd boards from nearby storage to make your own rnd. Pros of this strat is that you get rnd in "safe" location, get ripley ~first. Cons is that you have to fuck around with autolathe for machinery parts and run to hack/drill into tech storage for boards and get metal, but then the good stuff about techwebs is that rnd basically progressess on its own over time, other con is that shitty scientists can waste rnd points on some crap like medical branch (overpriced/bloated with pointless tech requirments due to tg's retardation), but then even if do join as scientist, you arent safe from some other faggot, engineering for example, from wasting your rnd points though rnd console of other department.

Add mining conscription id upgrades to sci? To rds locker, since pins are already there.

Do vouchers (?) only spawn on miners? HOP's locker used to have them long time ago, maybe add them back to it too.

**Review by ghost — APPROVED** [review]

**Pull request merged**
