### PR TITLE
[FIXED] Add :feelsoldman: in icons 

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl:
add: :feelsgood: in emoji.dmi as :feelsoldman:
/:cl:
## About The Pull Request
PR for the feature : https://github.com/HippieStation/HippieStation/issues/11975

## Why It's Good For The Game
Ask Biggi

### CODE REVIEW

**Comment by ghost** [comment]
don't we use `hippiestation/icons/emoji.dmi`?

**Comment by ghost** [comment]
Probably let me change that tommorow

**Comment by PortalVector** [comment]
My bad i did changed emoji.dmi i just wrote "icons" in PR, i'm a idiot.

**Comment by AnthonyJNgo** [comment]
The pepe feelsoldman is the best feelsoldman.

**Comment by ghost** [comment]
Now it should be good

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
