### PR TITLE
you can now blacklist reagents from strange seeds using can_synth_seeds

### PR DESCRIPTION
**Pull request by RafRoq**
had to edit a tg file to implement this, created a new proc: get_random_reagent_id_seeds(), created a new var: can_synth_seeds
:cl:
created a new var for reagents to black list stuff from random seeds only 
:cl:

### CODE REVIEW

**Review by Jujumatic — DISMISSED** [review]

**Comment by Jujumatic** [comment]
Sexy

**Comment by Jujumatic** [comment]
I do believe that you can already blacklist reagents with the can_synth var though, it happens with the scp coffee machine and pisses me the fuck off cause you can't spawn romerol or admin chem

**Comment by Maroonenahmoron** [comment]
This will be useful if something new comes along and breaks the game if someone grabs the reagent in a strange seed. +1

**Comment by RafRoq** [comment]
Yes you can block by using can_synth 
But you remove it from some other stuff too like vent clog event

**Comment by Jujumatic** [comment]
Pretty big oversight if that's the case lol

**Comment by RafRoq** [comment]
Still a good idea to separate it from other stuff

**Review by Jujumatic — CHANGES_REQUESTED** [review]
Remove the entire random reagent proc seeds file as we don't need to make separate files to identify where procs are, just copy paste the proc into seeds.dm (our hippie version of seeds.dm that is). Also copy all of the code that TG uses to make the strange seeds and that runs the proc to generate the reagents list, and put all of that code into seeds.dm. as long as you don't call ..() only our hippie version will be run, so put all the code to generate reagents for strange seeds into the hippie version and work from there

**Comment by RafRoq** [comment]
I'm sure if I copy a already existing proc byond will give me an error I have done this before, I asked carbon he told me to edit a TG file and comment a justification

**Comment by RafRoq** [comment]
ok this turned into a mess

**Pull request closed without merging**
