### PR TITLE
Silicons can now see blood runes and daggers

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: Silicons can now see blood runes and daggers
/:cl:

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
-1 fuck silicons and fuck ai's
ruining muh fun

**Comment by Manly-Dwarf** [comment]
stupid tg change
+1

**Comment by Majick1** [comment]
Split on this, I'm alright with daggers but AI seeing runes could ruin the gamemode. Maybe if he can only see them inside his shell and not with the camera eye

**Comment by Manly-Dwarf** [comment]
"Split on this, I'm alright with daggers but AI seeing runes could ruin the gamemode."
Just cut the fucking camera? We put up with the AI dealing with runes for years. What the fuck?

**Comment by Toxici11i** [comment]
why the fuck was this even hidden from AI/borgs in the first place, I dont remember this ever having a PR on multiple servers and it was incredibly gay
+1 to revert /tg/ ided

**Comment by Majick1** [comment]
If AI was able to see runes before, then why was it removed? If it's an issue we've worked past then sure

**Comment by ghost** [comment]
> If AI was able to see runes before, then why was it removed? If it's an issue we've worked past then sure

because tgstation

**Comment by JessHorserage** [comment]
+1, for fucks sake tg.

**Comment by AnthonyJNgo** [comment]
+1, silly TG nerf.

**Comment by carlopault** [comment]
+1

**Review by yoyobatty — APPROVED** [review]
Has enough +1's

**Pull request merged**
