### PR TITLE
[MIRROR] Moths can now eat clothes

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/39350
--------------------
[Changelogs]:

:cl:
add: Moths can now eat clothes.
/:cl:

[why]: I thought it sounded funny and really just wanted to see if I could code something abstract like this. Provides extremely little nutritional value, it's just funny.

Apparently Hippie made this exact change as a PR 3 days ago. I didn't know but I also don't care.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
We already did this.

**Comment by ghost** [comment]
it was closed for the reason of keeping races cosmetic
this needs to be modularised

**Comment by JohnGinnane** [comment]
Does it need to be modularised? I thought we were gonna merge it? @Carbonhell

**Comment by Carbonhell** [comment]
pretty sure it was denied?

**Comment by Carbonhell** [comment]
yeah, code needs to be disabled for us. Unless @Dudeinyourbackyard and @t-f-w want it

**Comment by ghost** [comment]
it was DENIED
RE-DENY

**Comment by JohnGinnane** [comment]
can we merge this as-is? if we suddenly see a lot of moths we can nerf/mod/remove it

**Comment by Carbonhell** [comment]
Included in #8626 (but disabled)

**Pull request closed without merging**
