### PR TITLE
DWARVES

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Dwarves
server: Make sure Dwarves don't lag the server.
/:cl:

## About The Pull Request
GO TO THE DWARFCORD
THIS PR IS NOT COMPLETE, DO NOT MERGE

## Why It's Good For The Game
DWARVES

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
It was inevitable.

**Comment by Maroonenahmoron** [comment]
This will definitely be the next big break that will give dead players something to do. +1

**Comment by funkynuggets** [comment]
https://www.youtube.com/watch?v=8M7pL6ucR9A

you know whats up +1

**Comment by earthmoonjune** [comment]
rip this i guess

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by Eagle-Eyess** [comment]
+1

**Comment by Jujumatic** [comment]
so uh, how is this going

**Comment by Manly-Dwarf** [comment]
a single tear

**Comment by FantasticFwoosh** [comment]
I have sprites if you want extra fluff, and stuff from goof's original project. I also made some of the clothing and weapon sprites. Else you'll have to bother militares from /tg/

**Comment by Manly-Dwarf** [comment]
Sure thing, mate. Thanks.
I'm not working too hard on this because I just have a lot on my hands.

**Comment by earthmoonjune** [comment]
lazy headmin.....

**Comment by lunaman22** [comment]
+1 fug lavaland

**Comment by Wilchenx** [comment]
is this the cool reddit pr?

**Comment by Wilchenx** [comment]
when is it going to be merged 🤗

**Comment by SireTurret** [comment]
as soon as it's done

**Comment by Manly-Dwarf** [comment]
go away redditors
this PR is mostly just a passion project on the side that we haven't picked up on in forever, as we've been too distracted with more important stuff
if you want the other big changes just go to the forum to find the sec overhaul

**Comment by SireTurret** [comment]
:mistake:

**Pull request closed without merging**
