### PR TITLE
Fix vampire mesmerize not full stunning

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt
fix: Fix vampire mesmerize not full stunning
/:cl:

Got messed up by stun rework

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
The stun rework was a mistake and should have never been merged.

**Comment by Lxtoofonea** [comment]
well said kbb, +1

**Comment by ghost** [comment]
@Kawaii-Big-Boss crawling memes are worth it tho

**Comment by Lxtoofonea** [comment]
maybe only crawl whale you are resting, not disarmed.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
