### PR TITLE
Fixes nanosuit causes runtime errors from overrides

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
fix: Runtimes were being thrown by afterattack and possibly other proc overrides in nanosuit.dm when the source was a non-human. This has been corrected.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Review by Jujumatic — DISMISSED** [review]
I don't really see how some of this will fix the runtimes but it's worth a shot I guess, code looks moreorless fine

**Comment by JohnGinnane** [comment]
A few things:

1. These runtimes were caused by people attacking non-humans is that right? Your overrides extend a lot of afterattacks to check if recipient is wearing suit and if so to kill the cloak. Is there not a single proc you could check that would be called when someone takes damage? Let me know if you've search already
2. Were you able to get these runtimes when testing locally? And are these gone with these changes?
3. Why did you remove https://github.com/HippieStation/HippieStation/pull/8310/files#diff-6c1d35e7c2e2f7d7210ba57409c92740L986

**Review by JohnGinnane — DISMISSED** [review]
looks good

**Comment by yoyobatty** [comment]
Essentially I want it so any form of attack will cause cloak to cancel, regardless if it does damage or hits. Also I played as a drone and clown Borg to verify if the issue returned and it seems to have disappeared. The start processing removal line was redundant because equipped called it. It's just to ensure that it starts the autorefill process once it's actually on your tank slot.

**Comment by Carbonhell** [comment]
You added this before using user.stuff
if(ishuman(user))
+		var/mob/living/carbon/human/H = user
the H var is pretty pointless considering user is typecasted as human already, you could make this better if you just made the argument mob/user instead of mob/living/carbon/human/user

**Comment by yoyobatty** [comment]
Does this look better? @HippieStation/maintainers

**Review by Carbonhell — APPROVED** [review]

**Comment by Jujumatic** [comment]
this good to merge then?

**Comment by yoyobatty** [comment]
Yeah, I think I got everything.

**Comment by yoyobatty** [comment]
@HippieStation/maintainers merge whenever please

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
