### PR TITLE
Adds a fun button for wizards that want to go LOUD

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Wizards can now buy a BIG RED BUTTON, which, when pressed, broadcasts a certain song for the entire crew to hear.
/:cl:

https://www.youtube.com/watch?v=havhaDYh0Sc

### CODE REVIEW

**Comment by WarRage333** [comment]
Id say cut down the file to 30 seconds for the retards that don't know how to stop sounds

**Comment by ghost** [comment]
natural selection at it's best

**Comment by Manly-Dwarf** [comment]
-1

**Comment by ghost** [comment]
@Manly-Dwarf but why

**Comment by SireTurret** [comment]
No. Bad. Really bad. This is a 6 minute long shitty earrape which makes the wizards even more annoying. Just make the wizards able to wear a special wife beater which has the same scream sounds and will have some armor patched ontop of it.

**Pull request closed without merging**
