### PR TITLE
Moves detective office beside lawyers

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
tweak: Detectives office is now beside the lawyers with strong doors
balance: Detectives cabinet is stronger
tweak: A vacant office is now available for lease where the det's office used to be
/:cl:

## About The Pull Request
What it says on the title, this was heavily demanded so here it is.

Detectives office:
image

Old office, now vacant:
image

## Why It's Good For The Game
Detectives office is in a terrible spot that's an easy target for anyone to swipe their stuff and makes playing the detective less comfortable since it's in a spot of large activity without the backup of security. I hope this PR tends to that.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
NOT SECURE ENOUGH
but this placement is better as the new vacant office is right next to cargo, where they'd want it to be

**Comment by yoyobatty** [comment]
Maybe I should swap the walls to reinforced too?

**Comment by Manly-Dwarf** [comment]
det's office doesn't need to be THAT secure. if you're gonna go that far there's no reason to have the window there

**Comment by ghost** [comment]
Maybe the window in the vacant office should be a reinforced table instead. I want more shop memes.

**Comment by Manly-Dwarf** [comment]
table with windoor
and maybe have the door be a cargo door instead of eng

**Comment by yoyobatty** [comment]
Well you'll notice it previously had reinforced, I just never ported it

**Comment by yoyobatty** [comment]
I updated those things

**Comment by zipzipzapityzoo** [comment]
not secure enough +1

**Comment by zipzipzapityzoo** [comment]
do we still get catchy tunes when we enter

**Comment by yoyobatty** [comment]
yes sir

**Comment by TrickyDickRichard** [comment]
10/10 more department segregation is more better

**Review by ghost — APPROVED** [review]

**Comment by danhibiki** [comment]
+1 for segregation

**Comment by danhibiki** [comment]
+1 for segregation

**Comment by danhibiki** [comment]
+1 for segregation

**Comment by MaterialisticThings** [comment]
+1 makes much more sense to have detective's office up at sec

**Comment by carlopault** [comment]
We are focusing on dets office yet the bees in botany dont have their own room yet. +1 to this anyway

**Pull request merged**
