### PR TITLE
Makes veil disable camera lights (and have a 10% chance of disabling a camera)

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
balance: Veil now disables camera lights
balance: Veil has a 10% chance to disable a camera temporarily.
/:cl:

AI shouldn't be able to insta-kill shadowlings with no counter besides cutting cams

### CODE REVIEW

**Comment by ghost** [comment]
another one pulls the code
and another one done and another one done
another one pulls the code

so what, could AIs fuck over slings with camlights or something too easily?

**Comment by ghost** [comment]
@McBawbaggings yup. Was talking about how slings was yesterday on OOC, apparently a sling got fucked by fucking camlights.

also one time on yogs, AI killed me with camlights, too.

**Comment by tortellinitony** [comment]
Veil disables camera lights, no? It should if not

**Comment by ghost** [comment]
@tortellinitony wouldn't it just automatically reenable, since it doesn't.

**Comment by ghost** [comment]
Ok, I changed it. now it disables camera lights, and has a 10% chance of disabling a camera

**Comment by MoreRobustThanYou** [comment]
```hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm:76:error: retunF.brightness_on: bad instruction```
wat

**Comment by ghost** [comment]
oh I see. woops.

**Review by tortellinitony — APPROVED** [review]

**Comment by ghost** [comment]
Conflict should be fixed

**Pull request merged**
