### PR TITLE
Casschem Improvements and Rebalances

### PR DESCRIPTION
**Pull request by KayeArray**
:cl: banthebantz
balance: Numerous casschem recipes have had their ratios improved to be less annoying
balance: Kelotane recipe now results in 3 parts and Impedrezene has been buffed
balance: Several hard to make chems have been tweaked and buffed
balance: Plasmic Fusion is now 3x easier to initiate
balance: The smoke machine can no longer create turfchems
fix: Fusion now works again and Emittrium has been fixed
/:cl:

### CODE REVIEW

**Comment by PopNotes** [comment]
It's Good:tm:

**Review by tortellinitony — DISMISSED** [review]

**Comment by KayeArray** [comment]
putin input

**Comment by ghost** [comment]
Yes +1

**Comment by dreamcrab** [comment]
100% yes fuck smoke turf chems so hard +80085

**Comment by Spacedong** [comment]
smoke machine is still fucking ass because smoke code is garbage and its too overpowered, you just plug a beaker in and boom it makes smoke out of it, you should have to take the time to make grenades to do this, as was originally intended see PR here 
https://github.com/HippieStation/HippieStation/pull/4367

**Review by ghost — APPROVED** [review]
Yes please

**Pull request merged**
