### PR TITLE
Adds mute mentor function to player panel and other stuff

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
admin: Admins now have the ability to mute mentors
fix: Nanosuit and hulk punching spamming has been fixed
fix: Cluwne bans should apply round start
/:cl:

## About The Pull Request
Also includes:
https://github.com/tgstation/tgstation/pull/48477
https://github.com/tgstation/tgstation/pull/48459
https://github.com/tgstation/tgstation/pull/48422
https://github.com/tgstation/tgstation/pull/48379
https://github.com/tgstation/tgstation/pull/45866

This also refactors hulk code which fixes hulks spam punch ability.
I've also included that same refactor to nanosuit since it was affected as well.

## Why It's Good For The Game
Mentors can finally be muted by admins if they decide to be annoying or metacomm.
Also some orbiting fixes/tweaks that make orbiting smoother.

### CODE REVIEW

**Comment by Toxici11i** [comment]
seperate these two prs

**Comment by ghost** [comment]
Fix your changelog.

**Comment by yoyobatty** [comment]
Thanks tips

**Review by ghost — DISMISSED** [review]

**Comment by enthethan** [comment]
dont let pee men have the ability to mute me bro...

**Review by ghost — DISMISSED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
