### PR TITLE
Adds Sharplipium

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl:
add: Added Sharplipium! It makes you slash instead of punch. It's made with silver, iron, ephedrine, and space drugs!
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Make a recipie for this + synthflesh + strange reagent and call it "Armbladinite" and it gives you an armblade for as long as you have some in your system. It's not an issue with lings because those fucks have been confined to gay gamemode jail.

**Comment by Maroonenahmoron** [comment]
Iron and silver makes sense, not sure about ephe and space drugs though... was thinking more like smart foaming agent or another drug like crank

**Comment by mikolaj007** [comment]
maybe make it increase damage?

**Comment by SharpenLimited** [comment]
fuck off gayon........................... sharplipium is an epic and cool name ++1 absolutely allowed in this server hell yeah brother

**Comment by ghost** [comment]
sharplipium sounds like it's got something to do with fat (lipids)

**Review by AnthonyJNgo — APPROVED** [review]
Looks like it is just a fluff change, doesn't affect damage or anything, only displayed actions. Cool.

@steamp0rt Add it to the chemistry wiki page please.

**Pull request merged**
