### PR TITLE
Engraved messages no longer give off light

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: Engraved messages no longer give off light
/:cl:

### CODE REVIEW

**Comment by mikolaj007** [comment]
-1

**Comment by ghost** [comment]
+1
let us engrave on floor with welder but it wont keep between rounds and has no color. no popup just custom name. if you write "elbereth" mobs wont attack you on it

**Comment by ghost** [comment]
@mikolaj007 got a reason?

**Comment by TrickyDickRichard** [comment]
+1 they're annoying

**Comment by Toxici11i** [comment]
+1 banes of nightmares, people with the mental disability which burns oyu in light and literally any mobs like statues and 173

**Comment by mikolaj007** [comment]
i think they look nice with the light
but i guess that's just my opinion

**Comment by diegoxt45** [comment]
why

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
