### PR TITLE
[MIRROR] Assmos part 1, #2

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/30791
--------------------
This still heavily a WIP, but I wanted to put it up for code-feedback and because it makes it easier for me to keep track of, as well some design input. 

- [x] Add first set of new gases

- [x] Add reactions for synthesizing new gases

- [x] Rework fusion into something not broken

- [x] Add the higher tiers of gases

- [x] Add sprites for new gases

- [x] Add in-body effects for new gases

- [x] Remove Freon, give its properties to other gases.

- [x] Copious bug and balance testing.

- [x] Add new gases to air alarms and filters.

- [x] Move reaction constants to defines.

:cl: as334
   rscadd: Massively Expands Atmospherics.
   rscadd: New gases have been added:Brown Gas, Pluoxium, Stimulum, Hyper-Noblium and Tritium
   rscadd: Brown gas is acidic to breath, but mildly stimulation.
   rscadd: Stimulum is more stimulating and much safer.
   rscadd: Pluoxium is a non-reactive form of oxygen that delivers more oxygen into the bloodstream.
   rscadd: Hyper-Noblium is an extremely noble gas, and stops gases from reacting.
   rscadd: Tritium is radioactive and flammable.
   rscadd: New reactions have also been added.
   rscadd: Fusion. Plasma will fuse when heated to a high thermal energy, with tritium as a catalyst. Make 
               sure to manage the waste products.
  rscadd: Brown gas formation: Heat oxygen and nitrogen.
  rscadd: BZ fixation: Heat Tritium and Plasma.
  rscadd: Stimulum formation: Heated tritium,plasma,bz and browns.
  rscadd: Hyper-Noblium condensation: Needs nitrogen and tritium at a high heat. Cools rapidly.
  rscdel: Freon has been removed. 
  rscadd: Water vapor now freezes the tile it is on when it is cooled heavily.
   /:cl:

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Comment by ghost** [comment]
Fun time.

**Comment by dreamcrab** [comment]
we can try it out and revert it if it ends up being insanely broken, why not? +420

**Comment by GuyonBroadway** [comment]
this probably conflicts with Bantz version of fusion.

**Comment by KayeArray** [comment]
actually codewise I don't believe it should because fusion is modular and uses its own seperate defines

**Comment by KayeArray** [comment]
This does remove freon though so that change needs to be mirrored to our map for sure

**Pull request closed without merging**
