### PR TITLE
Grey Bull rebranding

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]:

:cl: zamolxius
tweak: changed grey bull's name to reuben blast
/:cl:

[why]:

### CODE REVIEW

**Comment by ghost** [comment]
bump

**Comment by DaydreamPuppeh** [comment]
Yes please +1

**Comment by ghost** [comment]
this is ready

**Comment by yobob591** [comment]
+1 please

**Comment by earthmoonjune** [comment]
sure +1

**Comment by Lxtoofonea** [comment]
+1, i like dis

**Comment by Maroonenahmoron** [comment]
+1 okay

**Comment by TheMeatGod** [comment]
+1 reubenCUMBLAST

**Pull request merged**
