### PR TITLE
Reverts No-Slips and Thermals back to their 2015 state.

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Manly Dwarf
balance: No-Slips are now 3 TC brown shoes that cannot be chameleoned.
balance: Thermal Imaging Goggles also cannot be chameleoned, and look like regular mesons at first.
tweak: Thermal Imaging Goggles are now considered a stealthy tool rather than a device (they'll be found in stealthy tools, not devices and tools)
/:cl:

## Why It's Good For The Game
Death to safe traitor options.
Remember back when you couldn't just run around with your traitor gear on at all times, because people might get suspicious, or because they were so obviously traitor gear that you'd get mugged on sight?
Yeah, well, we shoved chameleons on everything. Even no-slips. Fuck you.

No-Slips being 2 TC is a terrible idea. They're so cheap that they can combo into any murderbone loadout, and even then, nobody can tell that you're wearing no-slips until it's too late.
It would make sense if the advanced magboots still didn't slow you down while active, but they don't, so those days are over.

Thermals are already very good, and they used to be 6 TC. Making them cheaper and adding chameleons makes them safe, disguise them as sunglasses or sechuds and nobody will flash you any way.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Proof this is how it worked way before ass update (this is when the chainsaw was first added, which was close around ass update aka the 2016 rebase)

No-Slip Brown Shoes:
https://github.com/HippieStationArchive/HippieStation13-1/blob/9e4cff1c2b1837ecd3cdb713298b0b3ab6fb70d6/code/datums/uplink_item.dm#L418

Thermals:
https://github.com/HippieStationArchive/HippieStation13-1/blob/9e4cff1c2b1837ecd3cdb713298b0b3ab6fb70d6/code/datums/uplink_item.dm#L499
(note: they were just red mesons even back then, though I can make them appear like mesons if this is too harsh in the designer's opinions)

**Comment by Majick1** [comment]
+1, red mesons is about where they should be, and we're never going to agree on no slips so let's just go with good enough for now

**Comment by lunaman22** [comment]
-1, change thermals to be chameleond to hud types and go to 3tc brown noslips instead

**Comment by Manly-Dwarf** [comment]
3TC brown noslips isn't happening
but I'm gonna make the thermal imaging goggles look like green mesons, yes

**Comment by MaterialisticThings** [comment]
-1 I like them being able to be chameleon but the price is good

**Comment by Manly-Dwarf** [comment]
Thermal goggles now look like mesons instead of being red goggles

**Comment by MaterialisticThings** [comment]
+1 I CHANGE MY MIND

**Comment by NautilusViper** [comment]
say no to 4tc noslips, say yes to 3tc noslips

**Comment by Manly-Dwarf** [comment]
3 TC still seems a bit too cheap, are you sure?

**Comment by NautilusViper** [comment]
It seems fair to me considering that when this gets merged brown shoes will automatically result in random searches.

**Comment by Manly-Dwarf** [comment]
Held a "vote" in the designer channel, 3 TC noslips it is I guess.

**Comment by ExpAntique** [comment]
+1 noone cares about brown shoes anyway, and if you do good on you.

**Comment by Manly-Dwarf** [comment]
how did this already get a fuckin conflict

**Comment by biggiOS** [comment]
+1

**Comment by AnthonyJNgo** [comment]
+1, headmin approved, g2g for merge.

**Pull request merged**
