### PR TITLE
Holotool

### PR DESCRIPTION
**Pull request by Zyzarda**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Zyzarda
tweak: Holotool's HUD change menu is now a radial
/:cl:

## About The Pull Request
Changes the holotool's HUD setting change option to open the radial menu instead of creating a separate window.

### CODE REVIEW

**Comment by Lxtoofonea** [comment]
sure, +1

**Comment by Manly-Dwarf** [comment]
Shilled their PR in staff-bicycle.

**Comment by TheMeatGod** [comment]
+1

**Comment by ghost** [comment]
can i give a +1 as the guy who ported holotools

**Comment by earthmoonjune** [comment]
no you cant loser

+1

**Comment by DaydreamPuppeh** [comment]
+1

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
