### PR TITLE
Un-uglification PART UNO

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt
imageadd: Reverts the uglification brought upon the codebase by tortellinitony.
/:cl:

### CODE REVIEW

**Comment by danhibiki** [comment]
Little vague no?

**Comment by ghost** [comment]
@danhibiki this gets rid of our shitty computer sprites

**Comment by ghost** [comment]
but they're amazing holy shit fuck off with your 3/4 perspective,  we've had players come and compliment the classic sprites as they prefer them

**Comment by ghost** [comment]
I prefer the current computer sprites. -1.

**Comment by Manly-Dwarf** [comment]
You should really learn how to use suggestions before making these dumb shitpost PRs. This way we can come to a conclusion that makes everyone happy instead of just wasting your time doing this nonsense.
Also no. Our older sprites from 2015 were the best. These ones are fine, but unmaintained, things like the bounty console are not ported at all.

The NEW sprites are genuinely awful. They're fine from a design standpoint, but they're 3/4 which causes them to clash horribly with everything else. It's the same reason why we don't use the chem dispensers, from a design standpoint the sprite is in fact better, but's 3/4.

**Comment by ghost** [comment]
Another chapter in the Amari Ray vs KBB saga...

**Comment by Carbonhell** [comment]
less UNO

**Comment by praisenarsie** [comment]
I found a better sprite.

**Comment by ghost** [comment]
@zamolxius No, they're old and ugly.

**Comment by DaydreamPuppeh** [comment]
The new ones I personally believe are overdesigned

**Comment by ghost** [comment]
no your brain is underdesigned

**Comment by GuyonBroadway** [comment]
They detract from the game neat retro-sci-fi aesthetic and look out of place being blocky white against a setting of mostly grey.

**Comment by Manly-Dwarf** [comment]
lmao you reacted with thumbs up and all that other shit on your own PR
good job amari

**Comment by Lxtoofonea** [comment]
Na, I wanna be a special snowflake

**Comment by ghost** [comment]
somebody deny this!!!

**Comment by yskefunky** [comment]
no lol -1

**Comment by bardofrage** [comment]
-1

**Comment by danhibiki** [comment]
-3 headmin vote bye

**Comment by earthmoonjune** [comment]
-1

**Comment by GuyonBroadway** [comment]
The headmins have given their -2, please convince them otherwise if you wish this re-opened.

**Pull request closed without merging**
