### PR TITLE
undisables hippiestation

### PR DESCRIPTION
**Pull request by praisenarsie**
who

### CODE REVIEW

**Review by KayeArray — DISMISSED** [review]
fucking lol

**Comment by Carbonhell** [comment]
if it's default what's voteweight for,there?

**Review by KayeArray — APPROVED** [review]

**Comment by praisenarsie** [comment]
carbon, just so its not easy to vote in omega

p.s. travis is cool

**Comment by JohnGinnane** [comment]
motherfuck this might explain why i cant open the map

**Pull request merged**
