### PR TITLE
Re-added ghetto chem below viro maint (Redo of previous PR)

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: Readded ghetto chemistry below virology
fix: Fixed some overlapping pipes
/:cl:

[why]:

### CODE REVIEW

**Comment by bardofrage** [comment]
plus uno

**Comment by yoyobatty** [comment]
@tfw

**Comment by DaydreamPuppeh** [comment]
Isn't there a ghetto chem above the forge? Anyway +1

**Comment by earthmoonjune** [comment]
yes......
+1

**Comment by Lxtoofonea** [comment]
yes pls +1

**Pull request merged**
