### PR TITLE
Added all-star to the ai vox... uh oh

### PR DESCRIPTION
**Pull request by Jujumatic**
You can now play the ai vox all-star song by typing in "allstar". That's pretty much it. Yeah.

:cl:
add: Added all-star to the ai vox. Just make sure you don't spam it too much, or else!!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
what happens when:
allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar allstar

**Comment by Jujumatic** [comment]
admins get to finally use their vox ban ability

**Comment by praisenarsie** [comment]
i'm fucking really tempted to click that close button

**Comment by Jujumatic** [comment]
course you are, it's you. now fuck off.

**Comment by JohnGinnane** [comment]
>i'm fucking really tempted to click that close button

So am I but that would be unfair bias. Need @HippieStation/head input on this

**Comment by Carbonhell** [comment]
I am so fucking tempted to click that close butto-
Oh wait, i can
Jokes aside what's wrong with this, if it's just a new song why is it bad

**Comment by GuyonBroadway** [comment]
You know how AIs spam vox_login 20 times ? Yeah that but the version of smashmouth as sung by the HL1 Vox.

This adds the whole song as an AI vox word.

**Comment by JohnGinnane** [comment]
>if it's just a new song why is it bad

it's a dead meme

**Comment by JohnGinnane** [comment]
my bad

**Comment by JohnGinnane** [comment]
@GuyonBroadway @Carbonhell is it possible to add a cooldown to certain works in vox? That way we can add a cooldown of like 5 mins or something like that

**Comment by Jujumatic** [comment]
maybe we could add like a "special" category to the ai vox and put ai_login and this in there, and put them with a variable cooldown depending on what is used

**Comment by praisenarsie** [comment]
pranked

**Comment by Jujumatic** [comment]
awe fuck bye

**Review by ghost — APPROVED** [review]
code is fine

**Comment by Carbonhell** [comment]
iunno it seems pretty meh, rather add each word as a vox so the ai has to actually write it and the system won't be prone to spamming?

**Comment by earthmoonjune** [comment]
^

**Comment by Jujumatic** [comment]
i'll see if i can add a cooldown or some shit to specific words. i still want to keep the song in its entirety but then make like a 5 minute cooldown before being able to use it again

**Comment by ghost** [comment]
yeah and keep in mind ic rule enforcement is far superior to ooc rule enforcement

**Comment by Kendrickorium55** [comment]
+1, bring back original vox_login please

**Review by KayeArray — APPROVED** [review]

**Comment by Carbonhell** [comment]
news?

**Comment by praisenarsie** [comment]
closing this, just reopen it when you figured out a way to make it cooldown or whatever

**Pull request closed without merging**
