### PR TITLE
Readds stocks 2: Actually works edition

### PR DESCRIPTION
**Pull request by JF260**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Adds two stock consoles in cargo
/:cl:

## About The Pull Request
This is a fix for my previous pull request, https://github.com/HippieStation/HippieStation/pull/10682
You can check that one out for the details of my failures at valid code, but i've now made it modular and unfucked the map with the bat files.

### CODE REVIEW

**Comment by yoyobatty** [comment]
This is not how you do it at all. You didn't even map merge hippiestation.dmm. You also just copypasted a ton of rendundant code instead of doing simple overrides/addons. You've actually gone and overwritten entire code just to change/add a few lines.

**Comment by JohnMcLaime** [comment]
It just works

**Comment by earthmoonjune** [comment]
fc5

**Comment by earthmoonjune** [comment]
+1 for if/when this is working

**Pull request closed without merging**
