### PR TITLE
Tweaks gamemode probabilities.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
Because holy fuck even on highpop we are getting long streaks traitorlings or some variant in thereof.

We did something like this pre rebase so as to get a little more game-mode variety. 

Don't merge this as the changes would be made to the config file directly.

Also don't change them just yet as we should discuss how to re weight them first.

### CODE REVIEW

**Comment by ghost** [comment]
Traitor is one of the best modes IMO. It's not quite bullshit like lings but it's a solid choice. I'd keep it at 4.
Traitor+Changeling makes changeling too often. Bumping up traitor and reducing traitorchan keeps the mostly traitor but sometimes ling balance better.
Double agents is bad since it's just traitor but worse. Reduction is good.
I don't mind rev buff since they usually end relatively fast despite not being huge on rev.
Everyone likes nuke ops at high pop so that's a good change.
Did we really have clockcult disabled or what? Is there some default value it was using?
Malfunction is probably my third favourite mode (After nukies and traitor) so I approve. It gets a good sense of paranoia with man versus machine.

**Comment by j-mie** [comment]
```PROBABILITY TRAITOR 4
PROBABILITY TRAITORCHAN 1
PROBABILITY DOUBLE_AGENTS 2
PROBABILITY NUCLEAR 3
PROBABILITY REVOLUTION 2
PROBABILITY SHADOWLING 2
PROBABILITY GANG 3
PROBABILITY CULT 1
PROBABILITY CLOCKWORK_CULT 1
PROBABILITY CHANGELING 2
PROBABILITY WIZARD 3
PROBABILITY MALFUNCTION 2
PROBABILITY BLOB 1
PROBABILITY RAGINMAGES 0
PROBABILITY MONKEY 0
PROBABILITY METEOR 0
PROBABILITY EXTENDED 0
PROBABILITY DEVIL 0
PROBABILITY DEVIL_AGENTS 0
```

is live

**Comment by GuyonBroadway** [comment]
The github config file and the live server config file are different IIRC.

In any case, I did push down all changeling/traitor modes in general just because they are a little diluted due to duplicate modes. 

Then again it was worse when we had king of the disk.

**Comment by KayeArray** [comment]
PROBABILITY RAGINMAGES 4

**Comment by ghost** [comment]
the git repo should probably have the updated version then. I think the current one is okay in that regard. We just must be unlucky to get traitor and ling as often as we do.

**Comment by KayeArray** [comment]
traitor is most greatest game mode

**Comment by GuyonBroadway** [comment]
I think the cult modes could be pushed up to two personally so they happen more than once a week.

**Comment by Uqualm** [comment]
Traitor should not have a lower probability than Nuke Ops. That seems kind of ridiculous if you ask me. Traitor should have the highest probability, just raise the other ones.

**Comment by Uqualm** [comment]
>Double agents is bad since it's just traitor but worse. Reduction is good.

/tg/ has reworked double agent entirely, may not want to reduce that until you've tried the new one out.

**Comment by GuyonBroadway** [comment]
Even with the changes, on hippie it will just boil down to standard traitor just with knowing where one other traitor is and that one is coming for you.

**Comment by Carbonhell** [comment]
What's needed here exactly? Btw i had an idea, if i remember correctly there's a secondary database holding some game info like round info, the feedback db right? Couldn't we add the total player amount at roundstart to the table and base the gamemode values on those values? So that they'd always be the good number thanks to some sort of formula we can develop,like average total players - constant

**Comment by j-mie** [comment]
Make an issue for this if it's still an issue, we use the configs on the server - not on Git.

**Pull request closed without merging**
