### PR TITLE
[MIRROR] Adds guillotine

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/36540
--------------------
Hi,

@ Armhulen suggested I put this upstream so here it is!

This adds a functional guillotine to the game. You buckle someone to it and you can only see their little head. If you interact with it with the **harm** intent, you will drop the blade after 3 seconds. Any other intent will unbuckle them.

You can craft a guillotine with the following:

Tools:
* Screwdriver
* Wrench
* Welder

Materials:
* 20 Wood planks
* 3 Plasteel
* 10 Cable coil

You can unwrench (1 second delay) it to move it around. If someone is executed, then anyone (alive) in the vicinity applauds. I've added some sound effects for clapping, it sounds like a single person clapping, but when it's played over a few times with varying pitch it actually sounds pretty good

I also added some lights to the courtroom because that room was dark

Pics:
image
image
image
image

Vids:
https://streamable.com/34nnl
https://streamable.com/cduz6

Clapping:
https://streamable.com/yz55a
https://streamable.com/qakpo

:cl: JohnGinnane
add: A guillotine has been added to the game. Can be crafted. If the blade isn't dull, will cut through human necks like a hot knife through butter. Use a whetstone to sharpen it if it becomes dull.
/:cl:

Original PR: https://github.com/HippieStation/HippieStation/pull/6714 (I remade because I messed up with the git)

**Credit to Gumner for the sprites**

### CODE REVIEW

**Comment by JohnGinnane** [comment]
neat

**Comment by Manly-Dwarf** [comment]
Overpowered. Why isn't this behind techwebs?
smug_high-res

**Comment by ghost** [comment]
+1

**Comment by JohnGinnane** [comment]
\>voting on mirrors

**Comment by JohnGinnane** [comment]
need to remove the original one and update hippiestation.dme, something i can do tomorrow

**Comment by JohnGinnane** [comment]
image
image

**Comment by JohnGinnane** [comment]
image

**Comment by JohnGinnane** [comment]
@Carbonhell this is ready

**Review by Carbonhell — DISMISSED** [review]

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
