### PR TITLE
Fixes shadowling bugs

### PR DESCRIPTION
**Pull request by ghost**
* shadowlings can now pull people (including when going through walls via shadow-walking)
* you can now make people shadowlings via traitor panel
* you can now select shadowlings in game prefs
* shadowlings now actually render

no changelog cause shadowlings haven't even been pushed to the server yet

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
>Shadowings can drag people through walls.

I'm sorry... Come again?

**Comment by ghost** [comment]
@GuyonBroadway did you not see the new shadowling shadow walk ability? Basically shadowlings can move fast in the dark, and go through walls _only if it is dark on the other side_ (a simple flashlight on the other side is enough to stop a shadowling). Shadowlings can drag people with em. Of course, people will still suffocate inside walls....

**Comment by ghost** [comment]
Ok should be merge ready. They can't pull people through walls unless you change ALLOW_PULL_THROUGH_WALLS from 0 to 1.

**Comment by GuyonBroadway** [comment]
Could you get me a vidya of the new ability? Also shadow walk needing shadows sounds fun. As does dragging people into darkness.

**Comment by ghost** [comment]
i actually had one on the original post: https://streamable.com/lfs7x

**Review by tortellinitony — APPROVED** [review]

**Pull request merged**
