### PR TITLE
adds outdated byond warning

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Change the message

**Comment by Cyberboss** [comment]
WE HAVE CONFIGS FOR THIS!

**Comment by Spankmaster1066** [comment]
This is a useful PR but shouldn't we make the message like "You are running on an older version of Byond. Please update your Byond client or you may experience bugs"

**Comment by Cyberboss** [comment]
YOU ABSOLUTE MEMES: https://github.com/HippieStation/HippieStation/blob/master/config/config.txt#L345

CLOSE THIS

**Comment by Carbonhell** [comment]
Facepalm

**Pull request closed without merging**
