### PR TITLE
[MIRROR] Beret Resprites Mk. II

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43543
----------------------------
Old:
OldBeret
BeretOld
BeretOldNorth
BeretOldWest

New:
NewBeret
BeretNew
BeretNewNorth
BeretNewWest

:cl:
imageadd: Adds new sprites for all berets.
imageadd: Adds the sprites for the archaic and vintage berets.
imagedel: Removes old sprites for all berets.
add: Adds the archaic and vintage berets, the vintage one being the current one and the archaic one being the one from 2014.
add: Adds the vintage and archaic berets to the autodrobe.
/:cl:

Commits FuCK

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
ok

**Comment by Jujumatic** [comment]
what do you guys think, is this ok?

**Review by Jujumatic — APPROVED** [review]

**Comment by Manly-Dwarf** [comment]
yes it's okay and my opinion is the only one that matters, merge

**Comment by ghost** [comment]
good shit, merging

**Pull request merged**
