### PR TITLE
[MIRROR] Removes ketrazine

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35216
--------------------
bye felicia

:cl: oranges
del: removes ketrazine
/:cl:

### CODE REVIEW

**Review by tortellinitony — APPROVED** [review]

**Comment by tortellinitony** [comment]
op tg chemical, good riddance

**Comment by praisenarsie** [comment]
head input my ass, this looks good on paper but bad in game

**Comment by ghost** [comment]
>this looks good on paper

what universe do you come from where boring to make overpowered chemicals available to anyone with enough autism is good on paper

**Comment by praisenarsie** [comment]
this universe

**Comment by GuyonBroadway** [comment]
It was basically meth+, everything wrong with antistuns exemplified.

It was boring to make but any autist could do it.

It had downsides you could counter with merely a little thought.

It negated the primary combat mechanic of the game rendering you immune to it.

It was basically a "do this every round or be at a strict disadvantage" so anyone who did won every fight and anyone who didn't could go fuck themselves.

**Pull request merged**
