### PR TITLE
NullCrate price change

### LINKED ISSUE #10024: Change Null_Crate cost to 10k
TG gutted every single way of obtaining money for cargo fast.

I legit never see people buy those.

### PR DESCRIPTION
**Pull request by AliiTea**
:cl: Nexendia
tweak: Price change on the Null Crate from 20k to 10k

/:cl:
I don't know why it added more lines even tho I didn't touch em _ohwell_, compiles and works locally.
redid pullrequest cause of an error in the last one and I like fresh clean requests.

Closes #10024

[Issue related to PR here](https://github.com/HippieStation/HippieStation/issues/10024)

### CODE REVIEW

**Review by Jujumatic — APPROVED** [review]

**Comment by Jujumatic** [comment]
great, now we need headmin input

**Comment by bardofrage** [comment]
+1

**Comment by Manly-Dwarf** [comment]
No.
Free surplus crate, buff to emag.
No.
Address mining sucking ass and Cargo sucking ass right now instead of buffing emag.

**Comment by AliiTea** [comment]
@Kawaii-Big-Boss why don't you fix mining and cargo sucking ass then??

**Comment by DaydreamPuppeh** [comment]
+1, though I would prefer a better way to earn money to lowering the price

**Comment by ghost** [comment]
let us sell cuffed people with a mind/ckey on the emagged cargo shuttle for 10k a person and hellbind them when it happens,  but it takes 5 minutes to launch the shuttle with a person inside

**Comment by AliiTea** [comment]
@Kawaii-Big-Boss I actually played mining last night and I thoroughly enjoyed it.. I didn't deal with any of the mobs as I am weak as fuck against them..

I'm not sure what the issue for mining is.. could you further eleborate on why it sucks ass?

**Comment by WarRage333** [comment]
I assume he means the tg ore export nerf which is funking cancer

**Comment by AliiTea** [comment]
Haven't played in forever or kept up on any code changes, what exactly is the export nerf.. I assume it's in regards to the ore processor in cargo

**Comment by mikolaj007** [comment]
+1

**Comment by AliiTea** [comment]
can this get merged already?

**Comment by AliiTea** [comment]
bumpity bump

**Comment by TheMeatGod** [comment]
+1

**Pull request merged**
