### PR TITLE
removes bees, adds bee crate to botany

### PR DESCRIPTION
**Pull request by ghost**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Added a bee crate to botany, containing all the standard cargo bee crate shit except the suit, as the lockers contain some.
del: Removed the 2 functional nests from botany.
/:cl:
image
image

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
+1 wasn't there a pr for this already

**Comment by ghost** [comment]
yeah but i closed it coz steamp0rt made an almost identical one. dont know what happened after

**Comment by Maroonenahmoron** [comment]
+1, fuck those bees.

**Comment by GuyonBroadway** [comment]
the current bees are bugged RN IIRC. If you take the queen out and put it back in you get a bazillion bees.

**Comment by GuyonBroadway** [comment]
By current I mean the "premade" beeboxes botany currently has.

**Comment by FantasticFwoosh** [comment]
Bees are supposed to be population controlled with the insta-kill flyswatters which the crate provides, also besides dealing extra damage to your non-human insectoid co-workers. anyway :+1:

**Comment by ghost** [comment]
MERGE bitch

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
