### PR TITLE
Re-adds our missing vending loot changes.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: Guyonbroadway
add: Happy cluwne masks are back in the autodrobe premium section, as are soft gloves.
del: Cat ears are removed from the vendors again, fuck off furfags. 
/:cl:

When we undid our snowflake as fuck vending machine mirror we forgot to re-add these in a less snowflake way.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Beat me to the punch.

**Comment by Manly-Dwarf** [comment]
Also this is technically a bugfix PR, so this should be quick merged.

**Review by JohnGinnane — APPROVED** [review]
yee

**Comment by JohnGinnane** [comment]
this might explain why the new hat i added can't be found 🤔

**Comment by Pyko1** [comment]
I wonder if we could easily add/remove entries from that list without having to mirror the whole list.

**Comment by JohnGinnane** [comment]
Perhaps on the initialise() we could just do LAZYADD(Vendor List, Our Item) so the original code can remain the same and then our code just adds our items when the pack is created if you get me

**Comment by ghost** [comment]
yee plus one

**Comment by Manly-Dwarf** [comment]
https://www.youtube.com/watch?v=q6EoRBvdVPQ

**Pull request merged**
