### PR TITLE
Nerfs meth/black powder/superboom smoke

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt
balance: Attempting to make black powder, superboom, or meth smoke will simply blow up in your face now. Once.
/:cl:

Alternative to #10260

### CODE REVIEW

**Comment by ghost** [comment]
Praise

**Comment by k-k-karma** [comment]
THATS NOT EVEN WAHT THE PR IS ABOUT CUNT AND YOU FORGOT SUPERBOOM

**Comment by Lxtoofonea** [comment]
yes do it

**Comment by yoyobatty** [comment]
What

**Comment by ghost** [comment]
@yoyobatty explosive smoke has a tendency to crash the server by creating fucktons of explosions. so instead of that happening, this'll just make one explosion happen, and delete the rest of the reagent

**Comment by ghost** [comment]
+1 boiiii
Good PR, nice nerf

**Comment by Shdorsh** [comment]
+1, do it plz

**Comment by Maroonenahmoron** [comment]
Let’s give this a try. +1

**Review by yoyobatty — APPROVED** [review]

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by bardofrage** [comment]
Pluso Uno

**Comment by ghost** [comment]
2 l8

**Pull request merged**
