### PR TITLE
Bucklebombs

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Manly Dwarf
add: You can now buckle people to syndicate bombs and nukes.
/:cl:

## About The Pull Request
Why not? They have to be handcuffed first.

## Why It's Good For The Game
If you can't tell why this is a necessary feature, then you're a brainlet.

Unfortunately this doesn't fix the issue of people "standing up" while buckled (icon bug), nor does it actually make it so it takes the full 90 seconds to unbuckle yourself. That would require refactoring the code, for both the former and the latter. Dunno why it's not just a var.

### CODE REVIEW

**Comment by Majick1** [comment]
Only if you can buckle yourself to the bomb and still throw it

https://imgur.com/1jr3GmE

**Comment by cris5311** [comment]
+1

not a brainlet

**Comment by NautilusViper** [comment]
give nukies extra round-end victory text if the captain is buckled to the nuke when it goes off

Syndicate Major Victory!
_Humiliation!_

**Comment by ghost** [comment]
I'm going to quickly delete this PR's version of the dme. Thanks, line endings

**Review by ghost — APPROVED** [review]

**Comment by Manly-Dwarf** [comment]
going to rewrite and update this later.

**Pull request closed without merging**
