### PR TITLE
Enables the /tg/ Nightmare event

### PR DESCRIPTION
**Pull request by ghost**
Now there's a chance for a ~ghetto sling~ Nightmare to spawn in maint!

### CODE REVIEW

**Review by KayeArray — APPROVED** [review]

**Comment by dreamcrab** [comment]
wtf is a nightmare

**Comment by Spacedong** [comment]
nO

**Comment by ghost** [comment]
@dreamcrab basically gay shadowlings... except the only powers they have is a shitty armblade and a jaunt that immediately throws them out whenever they go on a lit tile

**Comment by Pyko1** [comment]
Definitely should be enabled.
Even if shit, we can always make the weight 0 so an admin needs to trigger it.

**Pull request closed without merging**
