### PR TITLE
Re-adds directly attaching assemblies to chem grenades

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
add: You can once again attach igniter assemblies to chem nades.
/:cl:

## About The Pull Request
Basically /tg/ is lame and so are their nerfs, so we're doing it the right way this time.

## Why It's Good For The Game
Good enough for everyone.

### CODE REVIEW

**Comment by MrEpicSax** [comment]
+1

**Comment by karmaisblackandbluepilled** [comment]
was this even a nerf?
+3

**Comment by ghost** [comment]
it wasn't a nerf, it was just a rework/refactor.

are we really at the point where "players are too stupid to do new thing" = nerf?

**Comment by karmaisblackandbluepilled** [comment]
yeah, higher complexity ususally is a nerf

**Comment by ghost** [comment]
> yeah, higher complexity ususally is a nerf

this isn't higher complexity, it's just "you do this a slightly different way now"

**Comment by karmaisblackandbluepilled** [comment]
old good new bad

**Comment by AnthonyJNgo** [comment]
Old good, new bad +3

**Review by AnthonyJNgo — APPROVED** [review]
LGTM

**Pull request merged**
