### PR TITLE
Removes roundstart bees

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
del: Removes round start because they were lagging the server to death
/:cl:

## About The Pull Request
What it says.

## Why It's Good For The Game
No more lag.

### CODE REVIEW

**Comment by ghost** [comment]
just add bee cubes

**Comment by karmaisblackandbluepilled** [comment]
-1 move one to the back room and remove the other

**Comment by Manly-Dwarf** [comment]
if it's causing lag then remove it

**Review by ghost — APPROVED** [review]

**Comment by cris5311** [comment]
+1 if something like bee cubes gets added

**Comment by ghost** [comment]
+1, keep it commented out until it's fixed. It doesn't need anything added as a compromise if it's not a permanent removal, especially if it's causing lag.

**Comment by yoyobatty** [comment]
Seems to be fine now

**Pull request closed without merging**
