### PR TITLE
Makes the floor cluwne message ...edih tnac uoY for consistency sake 

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑 fluffe9911
tweak: Makes the floor cluwne message ...edih tnac uoY for consistency sake 
/🆑

### CODE REVIEW

**Comment by k-k-karma** [comment]
It's only reversed when the floor cluwne honks, this is more serious

**Comment by fluffe9911** [comment]
Im pretty sure every single line the floor cluwne has the text is reversed seems a bit weird for this to be the outlier

**Comment by k-k-karma** [comment]
i think it's stupid that it does that in the first place because i have to put it into fucking indianreversetextonline.com instead of reading it normally, this doesn;t make it look spookier just annoying

**Comment by fluffe9911** [comment]
*shrug*

**Pull request closed without merging**
