### PR TITLE
Re-adds Fatlip

### PR DESCRIPTION
**Pull request by Arzion5**
This mistake has gone uncorrected for too long. Special thanks to TDCoolGuy for helping me.
:cl:
soundadd: Fatlip has been re-added to the lobby music list
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
))

**Comment by PopNotes** [comment]
+1 speedmerge

**Review by GuyonBroadway — APPROVED** [review]
Needs headmin approval but if a maintainers +1 means anything you have it.

**Comment by bardofrage** [comment]
sure why not +1

**Comment by ghost** [comment]
+1

**Comment by j-mie** [comment]
@Arzion5 @McBawbaggings @PopNotes @GuyonBroadway @bardofrage 

Apreciate your effort here Arzion but this PR is wrong for a couple of reasons:
1) You didn't add the file to the [round_start_sounds.txt](https://github.com/HippieStation/HippieStation/blob/master/strings/round_start_sounds.txt) file, so it'll never get played
2) You didn't run the audio file through this tool: https://github.com/HippieStation/LobbyMusic - The tool is here to reduce the size/volume of all lobby music... The track is the size of 3 lobby tracks that have been ran through the LobbyMusic tool. It's also much lounder then the other lobby tracks.

Because I'm a nice person I downloaded the file and ran it through the tool for you, all you need to do is remake this PR, delete the old track and add this one instead: https://share.jamiehankins.co.uk/ShareX/2017/08/FatlipWhatsUpFatlipLyricsEeuNg86JcE.ogg

You also need to put this: `hippiestation/sound/lobby/FatlipWhatsUpFatlipLyricsEeuNg86JcE.ogg` into the [round_start_sounds.txt](https://github.com/HippieStation/HippieStation/blob/master/strings/round_start_sounds.txt)

**Comment by GuyonBroadway** [comment]
remember kids, don't homebrew beer and code (or 90 mins of eathworm jim 2 music, thats bad too)

**Comment by Arzion5** [comment]
Never knew it would be much more complicated than that. I'll try to remake the PR, thanks Jamie!

**Pull request merged**
