### PR TITLE
Catbeasts are now pacifist

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: Catbeasts are now pacifist. Let the games begin.
tweak: The "Cats aren't allowed to fight back" rule is gone. Take this as you please.
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Add a changelog saying that the rule is also removed

**Comment by ghost** [comment]
what rule

**Comment by ghost** [comment]
Give them clumsy too, just so we have less cases of catbanned players dragging people around for half an hour

**Comment by Manly-Dwarf** [comment]
get this one out of the way first, we can discuss clumsy later

**Comment by Manly-Dwarf** [comment]
although yes they should be clumsy

**Comment by ghost** [comment]
No reason not to bundle it in with this PR

**Comment by Toxici11i** [comment]
clumsy doesnt stop dragging, more the usage of guns and cuffs. i would recommend trialing this by itself, before increasing the restrictions

**Comment by Manly-Dwarf** [comment]
they were clumsy pre-rebase though

**Comment by ghost** [comment]
Clumsy does prevent dragging in the sense that you can just walk away if you're not cuffed. Also, it's funny when people with clumsy cuff themselves, but I don't get to laugh at it too much anymore because clowns know not to cuff people without visiting genetics first.

**Comment by Manly-Dwarf** [comment]
[That was removed.](https://github.com/HippieStation/HippieStation/pull/11129)

**Comment by Manly-Dwarf** [comment]
I'm just going to merge this for now and see how it goes. Discussion for Clumsy will have to come later

**Comment by SireTurret** [comment]
gay change

**Comment by Manly-Dwarf** [comment]
resign

**Comment by SireTurret** [comment]
ok im resigning

**Pull request merged**
