### PR TITLE
Adds cool turrets and random reagent beaker

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
admin: Added the shocker and throwing turret for adminbus fun!
fix: Acid processing no longer adds 100's of overlays by accident
add: Added a random reagent beaker, self explanitory, for badmins only
/:cl:

## About The Pull Request
The changelogs sum things up here pretty well. 

The thrower turret is literally just a turret that will throw whatever variable you set it to be, be it floor tiles, humans, or sulfuric acid beakers, it will try to throw it. Shocker turret is basically a static tesla that lacks the exploding machine tesla flag, it's essentially a tesla coil from command and conquer games so it might be cool for some end or mid round adminbus memes!

The random reagent beaker is pretty self explanatory, spawn one in, it has a random reagent of all reagents, including non-synthesizable ones. Maybe make the thrower turret spawn one and it will cause havoc on the station? 

## Why It's Good For The Game
Fun admin stuff.

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
hrnghh i wonder how I can persuade people to add this to be buildable by stationfa uh station people too

+3

**Comment by Punkinguy** [comment]
+1, tyme to bus!

**Comment by cb583** [comment]
+1, gimme the loot

**Comment by cris5311** [comment]
+1

**Review by Neotwr — APPROVED** [review]

**Pull request merged**
