### PR TITLE
[MIRROR] adds bamboo and  fixes sugarcane

### LINKED ISSUE #44170: Sugar Cane not present in seed dispenser
This is a pretty simple issue.  Sugar cane seeds are not loaded into the seed dispensers.  Some of the maps don't even have sugar cane crops in botany to get seeds from.  Should be a relatively minor fix.

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/44192
----------------------------
:cl:
add: bamboo which can be used to build punji sticks/ blowguns available as a sugarcane mutation or in exotic seed crate (instead of banana seeds)
fix: sugar cane is available at the mega seed vendor
/:cl:

closes: #44175
fixes:#44170

### CODE REVIEW

**Comment by mikolaj007** [comment]
+1

**Comment by Majick1** [comment]
+1

**Comment by AnthonyJNgo** [comment]
This is really cool for obvious reasons. I could see bamboo being used for crafting also.

**Comment by JessHorserage** [comment]
+1

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
