### PR TITLE
@johnginnane is a liar

### LINKED ISSUE #7260: Upgrading the RnD protolathe with manipulators makes the price of things go up instead of down
In-Game report from warrage:
Server info: 27493 (Hippie Station)

>General description of the issue
FUCK

>What you expected to happen
SHIET

>What actually happened
This acutally does not happen on TG something didn't get merged or some shit i dont knowwwwwww

>Steps to reproduce if possible

FFFFFUUUUUUCKKKKKKKK

### PR DESCRIPTION
**Pull request by praisenarsie**
:cl: Frozenguy5
fix: Fixed RnD machinery making stuff more expensive when you upgrade it.
/:cl:

Fixes #7260 

~~@pyko1 said he added the fix to the upstream merge or a different pr but apparently did not.~~

john did it

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
herr de derr

**Review by GuyonBroadway — APPROVED** [review]

**Comment by praisenarsie** [comment]
NEVERMIND @JohnGinnane "FIXED" the coefficient even though he just fucked it.

**Comment by JohnGinnane** [comment]
oh FUCK

**Comment by JohnGinnane** [comment]
I thought it looked familiar

**Comment by praisenarsie** [comment]
https://github.com/HippieStation/HippieStation/commit/c71bc844dac81d90cb1a32324b4b49853b051fb5

BUSTED

**Comment by JohnGinnane** [comment]
https://github.com/tgstation/tgstation/pull/36253/files#diff-8cbb2eb36bdf4fc0d1c33c7d8dbad898R80

explain me pls

**Comment by JohnGinnane** [comment]
I was trying to mimic /tg/ code

**Comment by Manly-Dwarf** [comment]
JohnGinnane how could you?

**Comment by JohnGinnane** [comment]
>I was trying to mimic /tg/ code

**Comment by Manly-Dwarf** [comment]
>mimicking /tg/ code

JohnGinnane how could you?

**Comment by praisenarsie** [comment]
https://github.com/HippieStation/HippieStation/pull/7067

"i was trying to mimic tgcode"

**Comment by praisenarsie** [comment]
https://github.com/tgstation/tgstation/blob/78bfbbdd093d009ad2e76ee917a9c39f0e945f3c/code/modules/research/machinery/_production.dm#L80

_"""i was trying to mimic tgcode"""_

**Comment by JohnGinnane** [comment]
im retarded

**Comment by praisenarsie** [comment]
mistakes happen anyway

:)

**Comment by WarRage333** [comment]
you nibbas work fast

**Comment by JohnGinnane** [comment]
image

nani ?!

**Comment by praisenarsie** [comment]
you are already dead

**Pull request merged**
