### PR TITLE
ChemistryChanges

### PR DESCRIPTION
**Pull request by Eagle-Eyess**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: EagleEyes
add: Added new area to chemistry to hold the molecular reassembler (and some uranium to operate it) and the bluespace recombobulator (and a bulespace crystal to operate it). Also a window near the  door of surgery was now placed to allow people to look in.
del: Surgery observation was the only thing intended to be completely removed since it offers little service anyway.
/:cl:

[why]: # this will allow chemistry to finally be able to actually create every chemical in lcass instead of only science

### CODE REVIEW

**Comment by JohnGinnane** [comment]
\>chemist powergamer buffs chemistry

**Comment by Eagle-Eyess** [comment]
Maybe but give me one reason chemistry shouldn’t be able to create every chem but give that power to science instead?

**Comment by JohnGinnane** [comment]
No I agree, it doesn't make sense that chemistry doesn't have all the equipment

**Comment by yoyobatty** [comment]
You have a merge conflict that is probably the result of making this before the TEG change was added. You'll have to map merge this with a backup of the latest map file. Also post pics

**Pull request closed without merging**
