### PR TITLE
Re-add BlastCo

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: BlastCo has been readded. Instead of an armory, it's now a choosable kit.
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Strider MGL?

**Comment by Manly-Dwarf** [comment]
also why is it broken into parts rather than just being the full kit like blastco is supposed to be

**Comment by karmaisblackandbluepilled** [comment]
+1
when are you readding the AK-477

**Comment by ghost** [comment]
@Manly-Dwarf /shrug

i guess i can put it back into a full thing but i forgot what the full thing was

**Comment by GuyonBroadway** [comment]
If I remember right the full kit was about x5 hardsuits, rollerskates, stryder mgl's, ammo+spare ammo, a handful of bomb beacons, a couple bags of x4, about 4 minibombs per operative, a small arsenals worth of c4 and a macrobomb implant for every operative.

**Comment by cris5311** [comment]
+1
boom

**Comment by mkikt4743** [comment]
3 bombs and a detonator for demo? seems a bit op, how much TC does this thing cost?

**Comment by ghost** [comment]
@mkikt4743 200

**Comment by mkikt4743** [comment]
I see

**Comment by mkikt4743** [comment]
+1

**Comment by Manly-Dwarf** [comment]
I still think I'd prefer old blastco but something's usually better than nothing.

**Comment by GuyonBroadway** [comment]
Ye at least add the styrder back tho.

**Comment by ghost** [comment]
Strider added to the "Rush B" kit, along with extra nades

**Comment by Maroonenahmoron** [comment]
+1, dealing with highly explosive nukies is a good challenge.

**Review by ghost — APPROVED** [review]
Seems like this code was good and *tested*

**Pull request merged**
