### PR TITLE
Allows pool temp and drain to be activated by silicon and admins without hacking (READY)

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: Pool drain and temp can now be adjusted by badmins and silicons without need to be hacked
Admin: Pool log is now under game instead of say
/:cl:

[why]: I'm at work so I'm doing web-edits. This also includes maintaining the code.

### CODE REVIEW

**Comment by ghost** [comment]
Finally.

**Comment by yoyobatty** [comment]
No input at all from anyone else?

**Comment by Manly-Dwarf** [comment]
oh uhh yeah
it's ok i guess

**Comment by yoyobatty** [comment]
@t-f-w @HippieStation/maintainers

**Comment by earthmoonjune** [comment]
sure +1

**Comment by Manly-Dwarf** [comment]
-1

**Comment by Lxtoofonea** [comment]
+1 sounds good

**Comment by mikolaj007** [comment]
+1

**Review by Jujumatic — APPROVED** [review]
whew

**Pull request merged**
