### PR TITLE
Adds cool huds

### PR DESCRIPTION
**Pull request by ghost**
RQ5DIE7MBh
image

:cl:
add: Added a HUD for dominator placement
add: Added a HUD for guardian range.
/:cl:

### CODE REVIEW

**Comment by diegoxt45** [comment]
+1 but the guardian range is too ugly

**Comment by WarRage333** [comment]
Very nice

**Comment by Manly-Dwarf** [comment]
+1 but the guardian range is too ugly

**Comment by ghost** [comment]
gif is 1 MB too big to upload on discord or github, sooo: https://files.catbox.moe/31e3qh.gif

**Comment by Manly-Dwarf** [comment]
better I guess

**Comment by yoyobatty** [comment]
That's sick

**Comment by AnthonyJNgo** [comment]
Nice.

**Pull request merged**
