### PR TITLE
MetaLake: MetaStation for hippie

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
add: The MetaLake map
/:cl:

basically it's MetaStation, except it has lcasschem shit and a pool

lcass
pool

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
needs a maint chem lab.

**Comment by ghost** [comment]
maintchem

(i also added an alien brain in here, too)

**Comment by ghost** [comment]
bar 
bar

**Comment by ghost** [comment]
box or gtfo 👎

**Comment by GuyonBroadway** [comment]
A new map means new gameplay possibilites and tactics. 👍

**Comment by j-mie** [comment]
Waiting on: http://www.byond.com/forum/?post=2289986

**Comment by doobiedoo23** [comment]
when are we doing this

**Comment by ghost** [comment]
when byond is unfucked

**Comment by j-mie** [comment]
Commit this without the changelog please.

**Comment by j-mie** [comment]
build this

**Pull request closed without merging**
