### PR TITLE
Makes nanosuit use cell.use() proc

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
code: Nanosuit cell charge is handled by proper procs within cells.
/:cl:

[why]: This is mainly so I can track the cell use on the blackbox tally but hey, code improvements never hurt.

### CODE REVIEW

**Comment by yoyobatty** [comment]
I'll probably split up the redundant code so I both use `cell.give()` and `cell.use()`

**Comment by yoyobatty** [comment]
Hang on gotta test to be sure

**Comment by yoyobatty** [comment]
Done !

**Review by GuyonBroadway — APPROVED** [review]
Wow this looks a lot more sensible

**Pull request merged**
