### PR TITLE
Protolathe printed power cells spawn with full power

### PR DESCRIPTION
**Pull request by Oiobi7**
:cl: Oiobi7
tweak: Power cells printed from the protolathe once again spawn fully charged.
/:cl:

All the great quality of life changes we've seen to research and what the fuck is this? It makes printing cells a gigantic pain in the dick.

### CODE REVIEW

**Comment by Dinopeaks** [comment]
for the love of god it can take a long time for them to charge if not full half full

**Comment by Jujumatic** [comment]
autolathe power cells spawn in fully charged, therefore protolathe ones should too

**Review by GuyonBroadway — APPROVED** [review]
looks ok.

**Comment by Carbonhell** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Pull request merged**
