### PR TITLE
[MIRROR] Remove infectability from xeno nest lavaland ruin

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43616
----------------------------
At request of @nervere, see https://tgstation13.org/phpBB/viewtopic.php?p=489435#p489435

closes #43619 

:cl: JJRcop
del: Live facehugger eggs and dead facehuggers removed from xeno lavaland ruin.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
-1 who tf wants this

**Comment by yoyobatty** [comment]
-1 no no no no no

**Comment by ghost** [comment]
tbh i hate xenos but i don't want this

**Comment by Maroonenahmoron** [comment]
I've seen so many people get infected before some other poor sap chestbursts onto lavaland, trying to reach the station but just ends up camping inside of the mining station.

Going to go with the flow here and +1 this, no live facehuggers/eggs in lavaland for people to dick around or self-antagonize with.

**Comment by mikolaj007** [comment]
Im gonna agree, nerf xenos first

**Comment by cris5311** [comment]
-1, Xenos are cool and spice things up

**Comment by ghost** [comment]
gonna give this a few more days then close this, if you don't want this then vote

**Comment by Majick1** [comment]
-1, there's quicker and easier ways to self-antag, this is just cutting features for the sake of it

**Comment by bigbluebeaker** [comment]
-1

**Pull request closed without merging**
