### PR TITLE
Fixes ghosts ctrl-click on autodoc

### LINKED ISSUE #12176: Ghosts can ctrl-click on the Autodoc IX and it BEEPS
Reproduction: Have someone on an ongoing surgery inside it. Ctrl-click as a ghost. BEEP.
Now spam click. The little influence your vengeful spirit can exert on the material realm is able to deafen people through the fourth wall.

Now this.. This is power.

https://cdn.discordapp.com/attachments/404474216730066947/632393216288751616/life-is-pain.mp4

### PR DESCRIPTION
**Pull request by Neotwr**
## Changelog
:cl: Neotw
fix: Fixed autodoc making beep beeep bep when a ghost ctrl click it
/:cl:

## About The Pull Request
Fixes #12176

### CODE REVIEW

**Comment by Toxici11i** [comment]
-1 this is funny

**Review by yoyobatty — APPROVED** [review]

**Comment by ghost** [comment]
awww this was funny

**Comment by shedowtnt** [comment]
yeah it was

**Comment by Neotwr** [comment]
revert it if you want

**Pull request merged**
