### PR TITLE
Un-nerfs that shitty r&d nerf tg hamfisted in for better R&D parts.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
balance: R&D parts now cost less like they used to.
/:cl:

LETS TAKE THE WAITING GAME THAT IS TECHWEBS CURRENTLY AND ADD EVEN MORE WAITING!

HOW FUN!

HOW RIVETING!

WHAT A TOTALLY WELL THOUGHT OUT AND PLANNED CHANGE TO THE PROBLEM PAT OF R&D FOR A VERY GOOD REASON.

I'M SURE THIS WILL MEAN THE ALREADY WELL STAFFED AND DILIGENTLY MANNED R&D DEPARTMENT WILL BECOME EVEN MORE POPULAR AND GET BE DONE MORE RELIABLY WITH THIS ADDITION OF A LITERAL 20 MINUTE WAIT!

### CODE REVIEW

**Comment by tortellinitony** [comment]
You know there are ways to get points other than just waiting around, right?

**Comment by JohnGinnane** [comment]
Can we get some votes on this?

**Comment by Pyko1** [comment]
Not really feeling like this is needed -1

**Comment by WarRage333** [comment]
Max caps give like 6k points

industrial tech costs 7.5k points then another 7.5 for high efficency its fucking GAY, every other department (mostly) has everything on the get go, why does science have to suffer so much

**Comment by GuyonBroadway** [comment]
remember that the machine produces about 3.1K points a min so you'll be just waiting for a good 8 mins just to get a little furthur up the tech tree.

Gee whizz isn't waiting 8 mins fun?

**Comment by JohnGinnane** [comment]
@GuyonBroadway 8 minutes doesn't seem to long but I don't play science very often so idk if it's too longer in the context of playing RnD science..

**Review by JohnGinnane — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
That's jsut 8 mins for the points for these things alone, factoring in all the intermediary steps and its more like 14.

And if people say "well go do something else" WHY EVEN BOTHER HAVING R AND FUCKING D IF YOUR SUGGESTION IS TO GO DO SOMETHING ELSE?  MIGHT AS WELL JUST ADD A DIRECT FUCKING TIMER TO EVERY FUCKING ITEM FOR ALL IT MATTERS.

**Comment by JohnGinnane** [comment]
image

**Comment by JohnGinnane** [comment]
https://www.youtube.com/watch?v=xzpndHtdl9A

**Comment by JohnGinnane** [comment]
We need more @HippieStation/head input as it's only pyko at -1

**Comment by tortellinitony** [comment]
R&D is really quick now, and if the round is really short, then the miners aren't gonna get you much so the expensive technology is unimportant anyway. This doesn't seem necessary -1

**Comment by Jujumatic** [comment]
R&D is really quick when you have to wait 8 minutes to get some actually decent tech, and another 12 to get betterish tech which is still pretty useless?? When rounds will usually last 30 minutes? 🤔 🤔 

And that's not even talking about the points needed to get the now nerfed and completely useless X-ray gun... thing

**Comment by Manly-Dwarf** [comment]
R&D is so quick that nobody does it, compared to back in the day where if you were robust enough you could set up systems to start pumping out items. Even in rounds where there are Scientists, techwebs only really gets going if the round managed to last longer than an hour and Science was never murderboned.

Do you people ever even play the game? Oh wait, you don't.

**Comment by praisenarsie** [comment]
wait didn't we buff rnd's point generation, now you are complaining it's 2quick.

i need to factcheck myself, one moment.

**Comment by praisenarsie** [comment]
oh nevermind i'm retarded, i never checked what this did.

yeah i don't care what you guys think

**Comment by Carbonhell** [comment]
+1, timelock is always a bad idea imo

**Comment by ghost** [comment]
i'll always say that adding a timelock to powercreep doesn't solve the powercreep
we shouldn't have the science department be gated to be slow just because it has nasty murderbone guns, that hurts every other facet of tech webs

**Comment by JohnGinnane** [comment]
I remember talking to Roma about RnD having OP weapons and he asked what weapons, since they were removed, so are there any OP guns in RnD with techwebs???

**Comment by WarRage333** [comment]
Xray was nerfed into the ground, there's lots of stuff a smart man can use that is Op in rnd, but that's like saying a guy who broke into the armory and stole the guns is op, except you can't access the armory until the force wall which gets removed 20 to 30 minutes into the round is out of the way

I didn't see anyone make 90% of the stuff you can research, but 80% of the blame lies in science losing the omnilathe

**Comment by 2Dollarbill** [comment]
+1, Science nerfs due to powergamers is a no go for me.

**Comment by ghost** [comment]
plus
one

**Comment by JohnGinnane** [comment]
does this have all the votes it needs now?

**Comment by Pyko1** [comment]
seems like it

**Pull request merged**
