### PR TITLE
Test merge LINDA Bug fix

### PR DESCRIPTION
**Pull request by yoyobatty**
Test merge to fix an ancient fire bug. 

https://github.com/tgstation/tgstation/pull/43326

Need to see how this works live.

### CODE REVIEW

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 6b4a394ef379b544a84b066af08749fdf548b2a3
Pull Request: 152fbf845805c2d96d2021f22c46be84bdb6169c
Server: 1965227e3257b594e9bf6248c8575d3ad6583974

**Comment by Fox-McCloud** [comment]
It means that once a fire tile spread, it's most likely going to make the fire catch on.

Sometimes you'll notice where a single turf just stays on fire for a while, but nothing else catches on it, or where it lights, but immediately goes out (obvious when you plasma flood a small area and toss a welder into it).

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 7b0b91d019ec48f709d8252cd29118506c5f1a0c
Pull Request: 152fbf845805c2d96d2021f22c46be84bdb6169c
Server: 5dca9da792d5f4122f042e62b8f1531a6f7d3c6d

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 0e6c08160e3c1d431d98ea3c2d4d0bb146023a9e
Pull Request: 152fbf845805c2d96d2021f22c46be84bdb6169c
Server: 0d8c869b73612db53c203e0b4ff54c513a72f809

**Comment by ghost** [comment]
#### Test Merge Removed

**Pull request closed without merging**
