### PR TITLE
[READY] Adding a new Circuitry UI and removing unneeded color limitation

### PR DESCRIPTION
**Pull request by Shdorsh**
[Changelogs]: # Made circuits and assemblies have an infinitely better UI. Pics gonna be posted soon, you wait.

:cl: Shdorsh
tweak: Making circuits look not eye-cancery and easier to navigate.
tweak: Also removes the color check, so you can color your assembly all kinds of colors
/:cl:

[why]: Because circuits are finally modularized. Thank god. Pics are coming up in a sec.

Edit: Pics are up and it's good to go as soon as Travis gives us the go signal.

image
image

### CODE REVIEW

**Comment by Shdorsh** [comment]
It's done and ready.

**Comment by ghost** [comment]
brilliant

**Comment by yskefunky** [comment]
very nice +1

**Review by yoyobatty — APPROVED** [review]
@t-f-w @Eagle-Eyess good idea?

**Comment by Eagle-Eyess** [comment]
Not gonna lie I specifically didn’t + or - 1 since I don’t have much experience with circuits... but if it makes the UI better than why not +1

**Comment by Shdorsh** [comment]
It's been approved for 2 days now, I've tested it on my homeserver. Can we merge this yet, plz?

**Review by Lxtoofonea — APPROVED** [review]
The code seems fine

**Comment by k-k-karma** [comment]
Has enough to merge

**Comment by danhibiki** [comment]
+1 or 2 headmins confused if toof is ok with it

**Comment by earthmoonjune** [comment]
+1

**Comment by Lxtoofonea** [comment]
+1

**Pull request merged**
