### PR TITLE
[MIRROR] Brain Traumas

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/31727
--------------------
:cl: XDTM
add: Brain damage has been completely reworked!
remove: Brain damage now no longer simply makes you dumb. Although most of its effects have been shifted into a brain trauma.
add: Every time you take brain damage, there's a chance you'll suffer a brain trauma. There are many variations of brain traumas, split in mild, severe, and special.
add: Mild brain traumas are the easiest to get, can be lightly to moderately annoying, and can be cured with mannitol and time.
add: Severe brain traumas are much rarer and require extensive brain damage before you have a chance to get them; they are usually very debilitating. Unlike mild traumas, they require surgery to cure. A new surgery procedure has been added for this, the aptly named Brain Surgery. It can also heal minor traumas.
add: Special brain traumas are rarely gained in place of Severe traumas: they are either complex or beneficial.
However, they are also even easier to cure than mild traumas, which means that keeping these will usually mean keeping a mild trauma along with it.
add: Mobs can only naturally have one mild trauma and one severe or special trauma.
balance: Brain damage will now kill and ruin the brain if it goes above 200. If it somehow goes above 400, the brain will melt and be destroyed completely.
balance: Many brain-damaging effects have been given a damage cap, making them non-lethal.
del: The Unintelligible mutation has been removed and made into a brain trauma.
del: Brain damage no longer makes using machines a living hell.
add: Abductors give minor traumas to people they experiment on.
/:cl:

WIP because i need to flesh out more traumas in the list, but the mechanics are in place.

As always i'm open to suggestions for changes and, obviously, more trauma ideas.

Closes #27330

### CODE REVIEW

**Comment by ghost** [comment]
i was actually in the shower 5 minutes ago thinking how there's seems to be an effort issue to gamify every system in SS13

brain damage is a simple system that doesn't need fucking about with, it's simple enough to do the job without being absolutely crucial.
the fact we need to do surgery to fix it when even getting mannitol is tough enough is bad, the fact that it can kill you now (although probably rare) isn't helpful either

ss13 is best when it's a means for fun, rather than deep engaging gameplay. it's always been very broad but with little depth but adding this depth that exists only to have depth instead of being fun isn't good

**Comment by Pyko1** [comment]
this will totally ruin fedora tipping meta.

**Comment by ghost** [comment]
i'd rather not have this system, but if we do actually integrate it, we need to ensure all of our braindamage causing effects are capped like in this PR

**Comment by GuyonBroadway** [comment]
Alternatively I can remove the death effect on brain damage.

**Comment by Jujumatic** [comment]
Hue hue I made an account just to comment on this. 

Also my apologies for the following text wall.

I think this is a really interesting idea and I really want to test it out if it gets merged, but I'm quite concerned at severe traumas requiring brain surgery to fix. I feel that it might be really tedious to do, considering that surgery is extremely rare as it is. Also from what I've seen, the only way you're really going to be killing someone from brain damage is with impedrezene spam.

 You'd end up killing people from raw brute damage before killing them from brain damage in 90% of cases. If severe traumas are really as rare as stated, then I would like to test out the system with brain surgery being required for severe traumas. 

I think it would need some tweaks and fixes here and there as I already see some potential issues arising from this system, but as I said I would personally love to at least try it out. From the way it's based it doesn't seem likely that you'd get problems from this system unless you were deliberately trying to get brain damage. I was first completely opposed to this system but after looking deeper into it, I can say I would personally like to have it merged, at least as a test kind of thing.

**Comment by praisenarsie** [comment]
just letting you know guys this was tested on tg via testmerge

**Comment by Jujumatic** [comment]
I did a little bit of testing with this mechanic on tgstation, since hippie has been down for a few hours. What I realised is that you actually NEED to have severe traumas being curable via surgery, or else you would potentially be stuck with really bad traumas if trying to keep a superpower. SO if you want to make severe traumas curable via mannitol, you'll need to make them curable via surgery too or else superpowers will be practically impossible to keep.

**Comment by XDTM** [comment]
Special traumas go in the severe trauma slot, and are really easy to heal away if you try to cure a minor trauma with mannitol. So no risk of having both a severe and a special, but you will need to live with a minor trauma to keep a power.

**Comment by Jujumatic** [comment]
Ok in that case it would be fine to move severe traumas to only requiring mannitol to fix, because if looking for superpowers it wouldn't be an issue then

**Comment by Jujumatic** [comment]
Apologies for posting so many times. What I've found is that even when edging the line to brain death, it still tends to take quite a few ticks of brain damage before applying a severe trauma. On top of this the only way to reach such a high level of brain damage to get such severe traumas, is with the use of chemicals (as every item and weapon that can do brain damage is capped to a limit of how much brain damage it can get a person up to). So unless you're purposefully trying to give yourself traumas, or you get extremely, EXTREMELY unlucky, there's practically no chance that you'll get a trauma requiring brain surgery in your average round or even if getting beaten up by a weapon that causes brain damage. You will still get some mild traumas, but even then it can take a bit to get those even at high levels of brain damage and those are very easily healed by mannitol. You only need to take 5-10 units of mannitol to take off a mild trauma. So I don't think this system can be easily abused by shitters hoping to make people's lives a living hell, if at all.

**Comment by Pyko1** [comment]
the specials have absolutely beautiful code, my CTRL+c CTRL+v appendage is itching.

**Comment by Jujumatic** [comment]
Also realistically the only way you're going to be dying from brain damage is by drinking way, way too much impedrezene. So to add on what I was saying before, since it's so difficult to get traumas anyway it's even more difficult to get killed from brain damage. If someone wants to kill another person they can go about it much faster and far more efficiently by just beating them with a toolbox for example.

**Comment by Pyko1** [comment]
I mean we have fedoras that give you braindamage just for pressing a tip action button with no caps atm.

**Comment by Pyko1** [comment]
and used to have 50 braindamage for saying rouge

**Comment by Jujumatic** [comment]
Just cap them both at a certain amount of brain damage then and it should cause no problems

or alternatively remove 200 brain damage causing death, but then you'd have the problem with fedora tipping and typing rouge causing really bad traumas. so better to just cap it.

**Comment by GuyonBroadway** [comment]
the clowns traitor bike horn COULD do it but you'd need to honk a guy 20 times.

**Comment by Jujumatic** [comment]
I just talked with the guy who actually made all the code for this thing, and he's made some changes. So if this is to be implemented we will also need to add in the new changes which has just been put on the tgstation's github if I remember correctly

**Pull request closed without merging**
