### PR TITLE
Adds a perfectly normal wife-beater

### PR DESCRIPTION
**Pull request by ExpAntique**
## Changelog
:cl: ExpensiveAntique
add: a wife-beater has been added to the game, and is now available for purchase at the ClothesMate
soundadd: added some very alpha sounds
/:cl:

## About The Pull Request

I added a wife-beater to the game that you can purchase from the ClothesMate, that has some very special alternate screams.

Coded by BiggiOS/Dungeon Master, who is the true alpha for helping me make this

## Why It's Good For The Game

This is without a doubt the best thing I have coded, and probably will be for the rest of my natural life.

### CODE REVIEW

**Comment by yoyobatty** [comment]
Pics?

**Comment by ExpAntique** [comment]
> Pics?

https://media.discordapp.net/attachments/563460129257947146/601491593853141013/unknown.png

**Comment by TrickyDickRichard** [comment]
good thing gumner's shitty sprite didnt get in amirite fellas

**Comment by ExpAntique** [comment]
https://youtu.be/Wt1OzDzNvzw

**Comment by Manly-Dwarf** [comment]
make vivadel spawn with it roundstart

**Comment by theworldo** [comment]
:smug_seiko:

**Comment by 88scheming88** [comment]
+1

**Comment by TrickyDickRichard** [comment]
btw +1 add please

**Comment by LucasOCastro** [comment]
Make it a traitor item:
Instant addiction to alcohol and tobaco. Extra damage (specially against females) and the ability to break doors open with unarmed melee. Perfect for actually beating wifes.

**Comment by TrickyDickRichard** [comment]
> Make it a traitor item:
> Instant addiction to alcohol and tobaco. Extra damage (specially against females) and the ability to break doors open with unarmed melee. Perfect for actually beating wifes.

but thats not the joke

**Comment by ExpAntique** [comment]
REVIEW AND MERGE THIS **NOW**

**Review by ghost — APPROVED** [review]
yeah sure

does this have a headmin +1?

**Pull request merged**
