### PR TITLE
Shadowlings are no longer affected by gravity

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
tweak: Shadowlings are no longer affected by gravity
/:cl:

### CODE REVIEW

**Comment by PopNotes** [comment]
I'm not sure how to feel about this.

**Comment by Arzion5** [comment]
Sounds fun, but doesn't that make them move really fast?

**Comment by ghost** [comment]
@Arzion5 they already move really fast in dark. this just makes them unaffected by no grav. It's not like they can go into space, starlight hurts em.

**Comment by Arzion5** [comment]
I'll +1 then

**Comment by DinduStuffin** [comment]
-1
Thralls are just gonna destroy/disable the generator every round or near every round

**Comment by tortellinitony** [comment]
I don't see why they need this

**Comment by ghost** [comment]
@tortellinitony because when grav dies, as a sling, you constantly get stuck in the middle of a hallway while moving, you can't drift.

**Comment by j-mie** [comment]
"-1
Thralls are just gonna destroy/disable the generator every round or near every round" thisssss

**Comment by Arzion5** [comment]
Thralls are affected too. Any sling that knows his two cents would know that it is counter-intuitive to force their thralls to disable the gravity. Not only do potential victims become faster than the shadowling near walls and solid objects, but their thralls can get stuck floating too.

**Comment by ghost** [comment]
nah
they still have human form so they should be gravity based

**Comment by j-mie** [comment]
closed in favor of #3683

**Pull request closed without merging**
