### PR TITLE
Adds Gatfruit as a botany only traitor item

### PR DESCRIPTION
**Pull request by mikolaj007**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Traitor botanists can now buy Gatfruit
/:cl:

## About The Pull Request

Adds Gatfruit to the uplink for traitor botanists. it costs 20TC and its a plant that grows .357 revolvers
matures extremely slowly, but still twice as fast as xenobio gatfruit
roughly 8-9 minutes until first harvest on a private server. 

## Why It's Good For The Game

More options for a traitor botanist

### CODE REVIEW

**Comment by k-k-karma** [comment]
make it 20, infinite 60 damage is bullshit

**Comment by mikolaj007** [comment]
alright, done

**Comment by cris5311** [comment]
+1
Gatfruit for all (traitor) botanists!

**Review by ghost — DISMISSED** [review]

**Comment by JessHorserage** [comment]
+1, 20 is perfect for this, its ranged, it can be stacked to shit, and its on one of the best late game jobs.

**Comment by Manly-Dwarf** [comment]
>another fucking 20 TC traitor item

I like job-exclusive traitor items but come on mate, it just grows .357 revolvers? Come on!

**Comment by mikolaj007** [comment]
I mean, it was already in the game, i just added the option to buy them.
Also if you think it should be worth  less TC then ill gladly hear you out
I honestly believe it should be like 18 TC's but 20 is also balanced

**Comment by NautilusViper** [comment]
> make it 20, infinite 60 damage is bullshit

autolathe says hello, gatfruit isn't the problem



> I mean, it was already in the game, i just added the option to buy them.
> Also if you think it should be worth less TC then ill gladly hear you out
> I honestly believe it should be like 18 TC's but 20 is also balanced

20TC items should be either absolutely bonkers powerful or offer something/s that cover enough ground to be all you'll need to buy, gatfruit isn't either of those

**Comment by bigbluebeaker** [comment]
+1 let's do this

**Comment by cb583** [comment]
Definitely lower TC to 18. Otherwise +1

**Comment by mikolaj007** [comment]
alright, this is done. if gatfruit turns out to be too op, ill increase it to 20TC

**Comment by Majick1** [comment]
+1 looks good now

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
