### PR TITLE
[MIRROR] Various map fixes

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/41560
----------------------------
:cl: ShizCalev
fix: Fixed toxins mixing chamber not having an APC every map but Box
fix: Fixed Box's vacant commissary's APC not being wired.
fix: Fixed a couple areas that didn't have APC's on Meta, Delta, and Pubby.
fix: Split up a couple noncontiguous maintenance areas on Meta and Delta.
fix: Corrected some department maintenance access doors having the incorrect area on Meta and Delta.
fix: Cleaned up some stacked pipes on Delta's white ship.
fix: Added some missing cameras on Pubby
fix: Fixed cameras in medbay on Pubby not having the medbay network assigned.
fix: Fixed the bomb testing area on Meta and Delta being set to the mixing lab area instead.
/:cl:

### CODE REVIEW

**Comment by yoyobatty** [comment]
Oh boy, conflicts.

**Comment by k-k-karma** [comment]
It's catching up with the map files from earlier

**Comment by yoyobatty** [comment]
Yup, I know this, I still gotta fix it though which is a pain in the ass

**Comment by GuyonBroadway** [comment]
>Map conflicts



[**MAINTAINER SCREAM**]

**Comment by Jujumatic** [comment]
"These conflicts are too complex to resolve in the web editor"

scREEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Jujumatic** [comment]
fixed conflicts in #9910

**Comment by Jujumatic** [comment]
will leave the branch intact in case i botched anything up

**Pull request closed without merging**
