### PR TITLE
[MIRROR] Adds 10 new drinks, some food reagents and goofconomizes champagne

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43825
----------------------------

## About The Pull Request

This PR adds 8 new alcoholic drinks, 2 new nonalcoholic drinks and 3 new food reagents. It also integrates champagne into the goofconomy as a luxury item rather than just being dispenser swill.

## Why It's Good For The Game

This PR adds more variation to bartender play by introducing advanced drinks that require somewhat exotic reagents and often help from other departments.

## Changelog
:cl:
add: 8 new alcoholic drinks.
add: 2 new nonalcoholic drinks.
add: Packs of a novel artificial sweetener have been added to the kitchen vendor.
add: Bottles of trappist beer are now available at a premium price in the booze-o-mat.
add: Juicing parsnips now yields parsnip juice.
add; Maintenance peaches.
del: Removed champagne from the booze dispenser.
balance: Now everyone has to pay 200 credits if they want champagne from the booze-o-mat.
fix: Grape soda now cools you down like other sodas.
imageadd: Added new drink, bottle, vomit and peach can sprites.
/:cl:

### CODE REVIEW

**Comment by MaterialisticThings** [comment]
+1

**Comment by mikolaj007** [comment]
+1, we gotta update our wiki tho

**Comment by Majick1** [comment]
+1 more stuff good

**Comment by AnthonyJNgo** [comment]
+1.

**Review by yoyobatty — APPROVED** [review]
Should be good

**Pull request closed without merging**
