### PR TITLE
[MIRROR] Makes slime scanning more readable

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35274
--------------------
:cl: XDTM
tweak: Slime scanning now has a more readable output, especially when scanning multiple slimes at once
/:cl:

Fixes #35262 

slimescan

### CODE REVIEW

**Comment by JohnGinnane** [comment]
I thought we had our own version of this?

**Comment by JohnGinnane** [comment]
See https://github.com/HippieStation/HippieStation/pull/5301

**Comment by Pyko1** [comment]
might be worth changing back to tg scanner, since they have improved it quite a bit lately.

**Comment by xTrainx** [comment]
Agree, also tg added slime console button for scanning dropping potions, makin g #5301 obsolete

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
