### PR TITLE
[MIRROR] Adds vacant commissary to BoxStation, moves det office to sec

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/41291
----------------------------
[Changelogs]: #
:cl:
tweak: On BoxStation, there's a vacant commissary where detective office used to be. Detective office is now located where Law Office was, and Law Office has been moved to the adjacent Vacant Office B.
/:cl:

### CODE REVIEW

**Comment by Lxtoofonea** [comment]
tbh that room should be a shop

**Comment by yskefunky** [comment]
yeah sure +1

**Comment by Pyko1** [comment]
no need to +1 a mirror, especially when this only edits a map that we dont even use.

**Comment by yoyobatty** [comment]
The map file got fucked.

**Pull request closed without merging**
