### PR TITLE
ChemistryChanges

### PR DESCRIPTION
**Pull request by Eagle-Eyess**
:cl: EagleEyes
tweak: Chemistry has now been upgraded so it can fully master every chemical.
/:cl:

chemistry will now be able to make every chem, not just science

chemistry changes

### CODE REVIEW

**Comment by yoyobatty** [comment]
I would change the floor type in the lcass chem lab to something more suiting to medbay, right now it just looks like a gross copy-pasted version of the science chem lab.

**Comment by tortellinitony** [comment]
+1

**Comment by Dinopeaks** [comment]
-1 it will feed the dirty powergaming eagle!?!?!
image
 (joking +1)

**Comment by yoyobatty** [comment]
I've noticed that the camera tag in the lcass chem room is still named surgical observation, please change this. Also check to make sure you have correct access and names on the doors.

**Comment by lcass** [comment]
casschem +1) fuck yes

**Comment by Carbonhell** [comment]
sure looks nice,+1

**Review by Carbonhell — DISMISSED** [review]

**Comment by ghost** [comment]
+1 but remove the bed in front of the window, maybe add a chair if you'd like there - it just doesn't look right the way it is right now. iunno, just that the window kinda sucks there, not aesthetically pleasing.
or move the table with the straight jacket between the window on the right of the entrance to that room, make it so that the airlock to surgery has a window below and above

**Comment by earthmoonjune** [comment]
ye +1

**Comment by Carbonhell** [comment]
There seem to be changes unrelated to chemistry,mainly the disposal bin top-right near sec checkpoint,did you hook it up to the disposal system too?

**Comment by Eagle-Eyess** [comment]
The disposals bin was moved since it was in the way. It should be properly hooked up.

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
