### PR TITLE
[MIRROR] Heating chems now mix at the right temps

### LINKED ISSUE #38508: Meth (and maybe other chems) don't mix when heated
Issue reported from  Round ID: 89528 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

1. Put meth components in a beaker
2. Put chem heater to 374.
3. Chems don't mix
4. Put chem heater to 375
5. They now mix.

Meth is supposed to mix at 374, this might be some rounding issue?

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/38511
--------------------
fixes #38508.

### CODE REVIEW

**Comment by Jujumatic** [comment]
@HippieStation/maintainers what should we do with this? dunno if we should update our hippie version of this proc - ours is probably pretty outdated by now

**Review by yoyobatty — APPROVED** [review]
Just inclusion of an equals operator

**Comment by Jujumatic** [comment]
yeah but this needs to be ported to our hippie version of the proc doesn't it?

**Comment by yoyobatty** [comment]
not really, it literally is just making sure it's closer by 1 value. temp < 254 will check if it's 253 and below whereas <= 254 check if its 254 and below, this is very specific for chems like meth

**Pull request merged**
