### PR TITLE
YEAH LISTEN!!!

### PR DESCRIPTION
**Pull request by GuyonBroadway**
RECENT EVENT ON THE **HIPPIE** STATION HAVE LEFT ME VERY DISAPPOINTED OK!!

For lack of ambiguity's sake this just brings back the old "old man yells at server" soundfile we used to have.

### CODE REVIEW

**Comment by ghost** [comment]
quality +1

**Comment by ghost** [comment]
wrong folder

**Comment by Carbonhell** [comment]
Fixes #1658

**Comment by Carbonhell** [comment]
fix this REE

**Comment by GuyonBroadway** [comment]
I'll fix it just as soon as I finish work.

**Review by j-mie — APPROVED** [review]

**Pull request merged**
