### PR TITLE
[MIRROR] Logging system refactor and improvement

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/39521
--------------------
[Changelogs]: 

:cl: Logging refactor and improvement
code: All mob-related logs now include the area name and (x,y,z) position.
code: All logs that included an (x,y,z) position now also include the area name.
code: Standardized logging format of mob/player keys.
code: Telecomms logs are now included in the individual logging panel.
code: Fixed many other cases of logs being sent to either the individual logging panel or the saved log files, but not both.
refactor: The logging system has been refactored to contain less redundant code and to produce more consistent logs.
/:cl:

[why]:

The logging of positions and names/keys was inconsistent across the codebase, with several redundant implementations. All mobs names now use `key_name()` (moved from `unsorted.dm` to `_logging.dm`) and all locations use `loc_name()` (previously `atom_loc_line()` in `_logging.dm`).

Individual mob logging was separate from the global logging files, with duplicated code for some statements to send them to both logs, and several lines missing from either.

Redundant code from logging helpers has been refactored into the following functions:

- **`log_game()`, `log_say()`, `log_admin()`, etc.** These write to the relevant log file, with a timestamp and tag prepended to the message.
- **`atom/proc/log_message()`** Writes to the mob and client individual logs (if src is a mob), and also to the relevant log file through the above functions, adding `key_name(src)` and `loc_name(src)`.
- **`atom/proc/log_talk()`** Simple helper for user-provided inputs, since they were handled differently in several places. Calls `log_message()`.
- **`log_directed_talk()`** Helper for chat messages that are sent from one mob to one other mob (e.g. revenant whispers). Calls `log_talk()` on both mobs.
- **`log_combat()` (previously called `add_logs()`)** Helper for combat interactions, automatically adds the target's HP. Calls `log_message()` on both mobs.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
\>184 files changed
image

**Comment by yoyobatty** [comment]
Hopefully this compiles

**Comment by yoyobatty** [comment]
this requires replacing add_logs to the new system, someone do this please

**Comment by yoyobatty** [comment]
Once this build, everything will be ready.

**Review by yoyobatty — APPROVED** [review]
Ready to go !

**Pull request merged**
