### PR TITLE
Added a server restart vote and an emergency shuttle call vote - also some vote tweaks

### PR DESCRIPTION
**Pull request by Jujumatic**
So after seeing all the complaints on the forum I decided to revert @JohnGinnane's #7552 and instead placed both options as votes. So now you can start a restart vote, or a shuttle call vote. The shuttle call vote calls an emergency shuttle, sets it as unrecallable and sets its timer to 5 minutes, to give traitors just enough time to collect their objectives and head off without making the ghosts have to wait much longer. I think this is a fair compromise for everyone so hopefully this should help make everyone happy. I left the restart server vote in because sometimes MC dies when the shuttle docks at CentCom and there's no admins to restart the server - also as a failsafe in case the shuttle at any point fucks up for whatever reason.

How it looks: 
image

🆑
add: Added a shuttle call vote. This vote calls the shuttle with a 5 minute timer.
add: Added back the restart server vote.
add: A sound is now played whenever a vote is started
tweak: Not voting no longer automatically counts as a continue when voting to restart the round.
/🆑

### CODE REVIEW

**Comment by Carbonhell** [comment]
very cautious +1… if this gets merged i want you to make a revert if the change is not liked

**Comment by Jujumatic** [comment]
of course my dude

**Comment by ghost** [comment]
+1

**Comment by Jujumatic** [comment]
oh fuck no rust strikes back... help!

**Comment by TheOmn1** [comment]
+1 fixes a problem which should have been fixed a long time ago. Hopefully the server's health becomes a lot better now.

**Comment by earthmoonjune** [comment]
+1

**Review by praisenarsie — APPROVED** [review]

**Pull request merged**
