### PR TITLE
[MIRROR] Slimes can now pass through grilles because le slime

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/41381
----------------------------

:cl: Basilman
add: Slimes can now pass through grilles
/:cl:

[why]: # >iron mesh
>stops slime

shidfugkdugkd,xdhgks.

### CODE REVIEW

**Comment by danhibiki** [comment]
The buff literally no one asked for. Slimes don't need and being "jelly like" doesn't mean they can squeeze thru grilles. The argument of "but they should be able to" isn't a real strong one and the premise of buffing an already nasty mob doesn't seem appealing to me.

**Comment by yskefunky** [comment]
ehh. on the fence. on one hand it makes sense and they can't break grilles, but on the other hand why do slimes need a buff
i'll go with +1 for now, we can revert if nobody likes it

**Comment by yobob591** [comment]
slimes dont do much anyways, they arent exactly strong or even mediocre at fighting so why not give them this small buff which makes sense anyways +1

**Comment by danhibiki** [comment]
I am mistaken in assuming it takes only two monkeys to have a slime mate?

**Pull request merged**
