### PR TITLE
3 More parallax backgrounds

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: More parallax backgrounds have been added
/:cl:

## About The Pull Request
Title
dreamseeker_ChChioHo47
dreamseeker_FSucrldZ9h
dreamseeker_m3kPYGEvpP

## Why It's Good For The Game
Nice fancy backgrounds for immersion.

### CODE REVIEW

**Comment by Zyzarda** [comment]
+2 these are dope

**Comment by carlopault** [comment]
+2 these are dope

EDIT: just noticed that the 1st one looks lower resolution than the other two

**Comment by karmaisblackandbluepilled** [comment]
+3

**Comment by earthmoonjune** [comment]
these good +1

**Review by Neotwr — APPROVED** [review]

**Pull request merged**
