### PR TITLE
zombies are told to behave as zombies [ready]

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl: zamolxius
tweak: made it so zombies are told to behave like a zombie, and not like a reskinned human
/:cl:

## Why It's Good For The Game
people usually just go ask people to cure them, not knowing it's shit, 25TC goes to waste. might as well remove romerol if people just get themselves cured

download

### CODE REVIEW

**Comment by ghost** [comment]
+1 good PR

**Review by ghost — DISMISSED** [review]

**Comment by ExpAntique** [comment]
+1 friendly zombies are almost as bad as friendly wizards

**Comment by Zyzarda** [comment]
+1

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by Amelia0010** [comment]
consider giving them their own language so they *can't* ask to be cured

**Comment by AnthonyJNgo** [comment]
+1 for obvious reasons. It would also be nice if zombies could have a timer of some sort that shows how long until they come back to life.

**Comment by ghost** [comment]
download (2)
Notice: It's actually deciseconds (i edited it it's fine)

**Comment by ghost** [comment]
what the fuck did I do

**Pull request closed without merging**
