### PR TITLE
Pocket Dimension Rework

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Holopara Pocket Dimensions have been reworked!
add: Instead of simply teleporting you back and forth between a dimension, it now summons a "manifestation" of that dimension.
add: Standing in the manifestation, and de-manifesting it, will result in you being teleported to the dimension. This only affects the summoner and their holoparas, and what/whoever they're pulling.
add: While the dimension is de-manifested, the holopara can move it around, and re-manifest it wherever they'd like.
tweak: You will no longer crit inside the pocket dimension.
fix: You can now heal while in godmode.
add: Ghosts (or the summoner) can now examine a holopara to see it's stats
/:cl:

Some notes:
 * You still have godmode inside.
 * You still have to pull an object / neckgrab a mob to pull it in.
 * Pretty much the only nerf is that you can't instantly "zoop" out of a dangerous situation, unless you manifested the dimension beforehand.

https://streamable.com/uhnhu

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Requires BYOND 513

**Comment by ghost** [comment]
no it doesn't, it just uses the same filter as saboteur borg.

only the portal thing requires 513

**Comment by Manly-Dwarf** [comment]
Steamport speaks in riddles and lies.

**Comment by ghost** [comment]
i compiled and tested this on 512.

**Comment by AnthonyJNgo** [comment]
Cooldown for the teleportation around station should be slightly higher than wizard teleport in my opinion. You have two separate players with the ability to fight and teleport away from danger, that's pretty strong combo. Also, when picking a spot for the new teleport location does it show mobs that are on station, or just objects? This is like a stationwide xray/thermal vision honestly, just hit the spell scan the whole station, then cancel if you want

**Comment by ghost** [comment]
I made the cooldown 40 secs (jaunt is 30 seconds)

Also it shows the entire z-level

**Comment by ghost** [comment]
Find some way to make players in the pocket dimension immune to the effects of soft and hard crit as long as their in it. Being put into god mode means that you're unable to lose or gain health, which is mildly inconvenient when you're in hard crit.

**Comment by ghost** [comment]
@QuarianCommando done

**Comment by ghost** [comment]
Yeet

**Comment by ghost** [comment]
@QuarianCommando you can now heal in godmode

**Comment by Manly-Dwarf** [comment]
ok its good +1 if you really need a number

**Comment by JessHorserage** [comment]
+1, steamport what the fuck, stop with the good github shit you cunt.

**Comment by AnthonyJNgo** [comment]
"I made the cooldown 40 secs (jaunt is 30 seconds)"

Make it 60 and +1 because this isn't a jaunt it's a straight up teleport.

edit: Actually just make it 45

**Comment by ghost** [comment]
@AnthonyJNgo done

**Review by AnthonyJNgo — APPROVED** [review]
Bet, looks good to me

**Pull request merged**
