### PR TITLE
Gives the advanced magboots a single point of slowdown while activated. 

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: Guyonbroadway 
balance: The Ce's Magboots now have a vary small amount of slowdown while active. They do not slow you down whatsoever while off.
/:cl:

[why]: A: They are basically free noslips and I feel it's bad to be able to get what is tantamount to antag gear right off the bat and B: Why does it have an on of setting if there is literally no reason to ever turn it off?

The Magboots along with the RTA(or HoS armour) and Teleshild make up the triumvirate of power-gamers and for good reason. They are noslips, not "like" or "similar to", they are nopslips with an off switch. 

In before "there's only ONE of them, its FINE to be OP!!" thats what they said about the owl hardsuit and that was basically antag gear too and oh look people went after that round after fucking round too!

This is hardly a massive nerf, you can still get over water and banana peels faster than most people on station and you could just turn the magboots off when you want/need to run at full speed and keep your eyes out someone trying to throw a slip. 

Or buy some damn noslips if you are a traitor.

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
image

Conclusive and scientific proof of their overpoweredness.

**Comment by ghost** [comment]
Yeah okay.

**Comment by PopNotes** [comment]
I dislike nerfing things that aren't genuinely overpowered because that makes the game boring, but I suppose this isn't _too_ bad.

**Comment by Carbonhell** [comment]
definitely +1, i remember there was the slowdown, why the fuck was it removed even

**Review by tortellinitony — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
@PopNotes You say the CE's magboots are not overpowered when they are mechanically better than noslips.  Noslips stop you from slipping but ce boots do that while making you immune to space wind and able to move freely in 0g with no slowdown.

**Comment by PopNotes** [comment]
I forget, when did something being good make it 'overpowered'? Are emags overpowered? Is the captain's sabre overpowered?

No, because things can be good without being OP.

**Comment by GuyonBroadway** [comment]
The Emag and Sabre provide situational utility where the magboots can be left on all the time with absolutely no downside and there is no better pair of shoes in game with the POSSIBLE exception of the Ka-Nada/blastco skates.

Why would anyone ever buy noslips when they can just nab the magboots?  There is literally no reason to choose noslips over magboots, they are bascially free tc for whomever wants to go get them. It's really bad to have traitor gear, or what is effectively traitor gear for free and available within five mins of roundstart. 

You don't even need an emag to get them, if you can get into the CE office you can get into atmos and use the fire axe to bust the locker open. 

It's used every round by anyone who wants to powergame because it is just flat advantage at no cost that does something that traitors would normally need to spend their TC on and then some. Nothing in the game does everything it does, not even the fucking shoes the deathsquad have.

I repeat IT IS STRONGER THAT ADMINBUS SHOES!!!

It is overpowered.

**Pull request merged**
