### PR TITLE
Public Wall-Mounted Defibrillator For Medbay

### PR DESCRIPTION
**Pull request by carlopault**
image

## Changelog
:cl: Carlospaul
added: A wall mounted defibrillator is now located within the Medical Bay for public use. 
/:cl:

Associated feature request: https://github.com/HippieStation/HippieStation/issues/12418

### CODE REVIEW

**Comment by MrEpicSax** [comment]
-1 that looks like shit

**Comment by carlopault** [comment]
Screenshot was taken in the map editor because I’m lazy. I will update it.

**Comment by Punkinguy** [comment]
-1 janky ass placement

**Comment by AnthonyJNgo** [comment]
I suggest getting rid of the no smoking decal three tiles away from it, and replacing that with the defib. +3 for the idea, waiting for you to change it and upload new screenshot.

**Comment by carlopault** [comment]
Updated the location. Look at the new image.

**Comment by Punkinguy** [comment]
Even jankier, place it next to chemistry

**Comment by carlopault** [comment]
> Even jankier, place it next to chemistry

I placed it there because this area is where all the healing happens. You're gonna want the guy you just defibbed right next to the cryo pods/sleepers.

**Comment by wheezl** [comment]
+1 I like viv's idea of replacing the no smoking sign with it. more noticeable there

**Comment by carlopault** [comment]
Updated the screenshot.

**Comment by MrEpicSax** [comment]
Wow he even took the time to give it it's own pretty little work area. What a guy.

Definite +1 from me now.

**Comment by AnthonyJNgo** [comment]
> 
> 
> +1 I like viv's idea of replacing the no smoking sign with it. more noticeable there

Heads get +3 by the way, GM's +2, GA's +1, babymins 0.5

**Comment by carlopault** [comment]
shit is broke and other files besides map are being changed, closing PR and fixing stuff

**Pull request closed without merging**
