### PR TITLE
Buffs the Energy Balisong's backstab damage.

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Kawaii-Big-Boss
balance: Energy Balisong now deals 125 brute on backstab.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

I really want the Energy Balisong to be an item worth its price, an item based around backstabs sounds like it'd be a lot of fun to use - but unfortunately it falls short.

The backstab can, obviously, only be used when you're behind someone. This is very hard to pull off in-game without stunning someone and tying them to a chair, and then going ham on their spine. If they see the balisong, they'll usually run away and unless you have a gun on you to stun them - you won't get that backstab. If you _do_ stun them, you can't backstab them unless they get tied to a chair. By that point they're most likely handcuffed and with any other weapon you could have killed them or at least crit them - particularly the Energy Sword.
If you want it to be sneaky and be an item that requires you sneak up behind co-workers who don't know how to examine you or click on a tile to look there, you'll be disappointed. You might kill an AFK cargo tech, a miner or a chef but you won't get the active crew who are usually smart enough to keep their distance.

Without the Backstab mechanic, you're paying for an item 4x the price of the Energy Dagger for only 2 extra brute damage. It's unfortunately underpowered and overpriced.

The crit-on-backstab would make the Energy Balisong's backstab at least a bit more worth it if you somehow manage to land it, and it would offset the fact that this item is barely better than the Edagger. However, until an item can properly combo with the Energy Balisong - I doubt we'll be seeing much of it.

### CODE REVIEW

**Review by JohnGinnane — APPROVED** [review]
code is 🆗

**Comment by WarRage333** [comment]
There was no point in using this one since the crafted one is nearly the same but this... makes it bullshit insane.

I'm not sure what to think, i want it, but when people start figuring out you can end a person in one hit then its gonna be a lotta salt

**Comment by Manly-Dwarf** [comment]
As I said earlier, you'd really have to catch someone off-guard to do that. Most people keep their distance and are constantly roaming the halls. Besides that, stuns are easier to get and will give you a similar effect of "guaranteed death".
An 8 TC item should reward you if you're willing to be sneaky and not use stuns, and somehow get a good backstab on someone - especially because you can't backstab them when they're stunned.

**Comment by JohnMcLaime** [comment]
You can basically do same (1 hit "kill" that is) with stunbatons, epipens and other trash whish deals a lot of stamina damage.

**Comment by Manly-Dwarf** [comment]
Yeah, hence why this thing's main gimmick requiring you to be behind someone and have that someone not be stunned for it to work is bogus.

**Comment by JohnMcLaime** [comment]
But adding another 1 hit kill item is going to make it worse, maybe buff it somehow else? Maybe make so you can dip it in chemicals, tho it would stil bel possible to 1 hit ko.

**Comment by Manly-Dwarf** [comment]
Not sure if that'll really fix the issue, since we have the arc forge that would effectively be the same.

**Comment by praisenarsie** [comment]
cockisong

**Pull request merged**
