### PR TITLE
Sets Devil gamemode as continous

### PR DESCRIPTION
**Pull request by xTrainx**
[Changelogs]: # Devils no longer ends at antag death

fix: Devils will no longer end at antag ends, and other rounds will not end when no devils are selected at mid round antag
[why]: # One of the major reason devil sucks is the way they suddenly end, unlike wizardss, they are not capable of taking the whole station on themselve, nor have anyway to prepare correctly before they can be killed, and also, round ends if the devil dies even when it can revive later on. also when this game mode gets selected after other antag dies, it ends the round inmidiatly, including tator rounds

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Please no.

Devils is an incredibly boring gamemode where the problem isn't necessarily the antagonists, but rather the crew that now has hulk and all-access. Potentially giving these magic-using people traitor or just having the round drag on while everyone starts smashing all the consoles is not a good idea.
Even /tg/ was wise enough to see that Devils was not a good gamemode to keep in rotation. Why would we want to prolong that?

**Comment by xTrainx** [comment]
you dont need hulk or all access if you want to destroy consoles, and the sin touched objective are all harmless to an extent, and most importantly, doesnt make you antag. Also those powers are gone with just hitting them with a paper, so they are not hard to deal with. 

If the issue was that, then eventually there will be a PR disabling Devil as a gamemode and even maybe it will be aproved, but until then, devil is not a game mode that was designed to be played on antag death, if anything, because of the bug of round end with devil dead when they could still revive. This PR aims to fix that issue, not whenever devils should stay or not

**Comment by ghost** [comment]
@xTrainx Actually, lawyer contracts KEEPS the devil powers, AND takes the soul away from the devils.

Also see: MULLIGAN ANTAGS FUCKING SUCK

**Comment by ghost** [comment]
This PR does nothing, the game configuration is not managed trough git, I've asked @bardofrage to get someone to update the server config to fix this.

**Pull request closed without merging**
