### PR TITLE
various security refurbishments 

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: zamolxius
add: Perma now has a prisoner outlet thing with conveyors a la old hippie map, the end of which is protected by a strong windoor
add: Added old isolation cell
add: perma prisoners have a tower-cap logs seed
add: isolation cell prisoner has a dakimakura to cuddle and hump
add: perma prisoners can now enjoy the warm glow of a flare in case of blackouts
add: perma now has a small, unconnected-to-the-rest-of-the-station maintenance
tweak: armory northern wall is now two R-walls thick
/:cl:

festive airstrip pi 2018-12-05 163434
festive airstrip pi 2018-12-05 163426
festive airstrip pi 2018-12-05 162019
disregard the lightning bug for the armory wall, it was an older screenshot before i edited the areas

### CODE REVIEW

**Comment by WarRage333** [comment]
Can we actually give perma proper hydro pots, i don't see any harm in that

**Comment by yoyobatty** [comment]
Plus hecking clf3 tiles at the end of that conveyor belt trap for whenever antags go on a perma run.

**Comment by ghost** [comment]
can also put a beepsky there on detain to get an excuse to up the escapee's punishment

**Comment by ghost** [comment]
058afd3c1ac2f35cb926ce11ef421d2c

**Comment by yoyobatty** [comment]
Also prisoners can crawl out to the conveyor belt's glass door, I would suggest adding a pod/blast door to the set of plastic flaps inside the cell area.

**Comment by ghost** [comment]
oh yes there's a strong windoor like from the armory right under the southernmost flaps but it didnt get caught on the screenshot
edit: i see what you mean, well it only incentivises using the isolation cell anyways

**Comment by Lxtoofonea** [comment]
+1, tbh i think we need to fully re design perma, but this works for now!

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by bardofrage** [comment]
+1

**Comment by Maroonenahmoron** [comment]
I can imagine all of the towercap bonfires being lit up by the rouge flare

**Comment by ghost** [comment]
there's also a very well hidden holodisk around so you can record yourself saying "FUCK YOU HOS" over and over on the holographic emitter

**Comment by AnthonyJNgo** [comment]
I'd like to request a larger solitary cell. Personally feel that the conveyer belt should be removed as it would be ridiculously easy to escape from. Conveyer belt on would stop it but if power went out you could just crawl out. If there's more than one permabrigged guy solitary wouldn't be a good option. The maintenance seems unnecessary. 2 rwalls for armory is ugly but it seems really fitting.

**Comment by ghost** [comment]
theyre old hippie features, except the rwall thing

**Comment by AnthonyJNgo** [comment]
You know the metal shutters that lock down brig? Maybe add one of those to the conveyer, in the middle? It'd be a lot more secure and HoS/Captain could open it to deposit prisoners and close afterwards.

Otherwise +1

**Comment by ghost** [comment]
yes im adding blast doors

**Comment by ghost** [comment]
conveyorperma
permaproper
permamaint
isolation

**Comment by ghost** [comment]
2307e238373b34e30f8ad47883d9d323
the blast door starts closed

**Comment by ghost** [comment]
@bardofrage @t-f-w feedback pl0x

**Comment by mikolaj007** [comment]
Why does the conveyor lead outside perma?

**Comment by ghost** [comment]
old hippie feature. also so the prisoners can sell vegetables to security for lenience and maybe to be let out

**Comment by Carbonhell** [comment]
the conveyor was used to transport items from outside to inside permabrig, without having to enter, in the old times
is it set like this?it shouldn't do the opposite

**Comment by ghost** [comment]
ooooh, it's from inside to outside lol. will redo [dnm]

**Comment by yoyobatty** [comment]
image
 
Long boring hallway = gross.

**Comment by ghost** [comment]
alright ill mess around with it

**Comment by ghost** [comment]
f81ca3e149ee15decdfd9eb185ffb1ca-png

**Comment by ghost** [comment]
ready for review

**Comment by ghost** [comment]
ready, why is check unsuccessful?

**Comment by RafRoq** [comment]
they need a spade

**Comment by ghost** [comment]
just wait for the plants to die then remove the corpse,  i barely use a spade as a botanist tbqh

**Comment by earthmoonjune** [comment]
+1

**Pull request merged**
