### PR TITLE
fixes butterdog spam

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: fixes butterdog spam #7597

:cl: zamolxius
fix: fixed carbon's cheap cuisine spam by sanitizing multiple inputs
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Review by Jujumatic — APPROVED** [review]
no more flooding the station with butterdog
 :(

**Comment by Jujumatic** [comment]
jesus fuck what are these travis errors, try pulling from hippiestation and pushing to this pr again

**Comment by ghost** [comment]
will do

**Comment by ghost** [comment]
@Jujumatic done

**Pull request merged**
