### PR TITLE
Modularised monkey cube cap and doubled it because le funny monkey xDDDD

### PR DESCRIPTION
**Pull request by Jujumatic**
Basically what the title says, just modularising the monkey cube cap in case TG ends up doing some retardation on it in the future and I doubled the monkey cube cap because le monkey spam is funy

:cl:
tweak: Doubled the monkey cube cap. Ooga booga!
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
it would be healthier to make it a config upstream but since you hate upstream :man_shrugging:

**Comment by Jujumatic** [comment]
upstreaming is ghey. also the config is pretty much there i just changed the value of maximum monkey cube autisms

**Comment by yoyobatty** [comment]
lelellelelele now lets spam gorillas xd

**Comment by Jujumatic** [comment]
can we pls i miss the gorilla spam with the dk music adminbus shit

**Comment by GuyonBroadway** [comment]
Once we merge the following (assuming we havent allready) this will be unecessary. https://github.com/tgstation/tgstation/pull/38165

**Comment by Jujumatic** [comment]
i'll close this when the mirror bot is up and we do yet another upstream to catch all the prs we missed during downtime, cause that pr just got merged like 24 hours ago. cause the bot is going to take like 5 years to bring up knowing erik's pace :D

**Comment by praisenarsie** [comment]
Closed in favour of https://github.com/HippieStation/HippieStation/pull/7623/files#diff-aa87b76a49b6f72a6edeab32a2105fd1R541

**Pull request closed without merging**
