### PR TITLE
You no longer need to take off your hardsuit/radsuit/whatever to heal

### PR DESCRIPTION
**Pull request by ghost**
I dunno when this got changed back, but it's annoying

### CODE REVIEW

**Comment by RafRoq** [comment]
-1

**Comment by AliiTea** [comment]
helllll no

**Comment by ghost** [comment]
it was like this before, wha'ts wrong?

**Comment by DaydreamPuppeh** [comment]
-1. This was one tg nerf I liked

**Comment by AnthonyJNgo** [comment]
It makes it very very easy to powergame. You don't have to worry about taking damage at all in a space or airless environment because you can just slap a brute or burn patch on through the suit. The way it is now you need to actually plan ahead, because if you remove your suit you will hardcrit and die. 

-1.

**Comment by ghost** [comment]
_removes hardsuit to put brute patch on in medbay_

_greyshit disarms and runs off_

**Comment by ghost** [comment]
@steamp0rt

*undoes helmet and targets head like a person who knows how to think*

*greytide runs up and gets robusted instead*

**Comment by ghost** [comment]
Other than that, this is a quality nerf (or buff, if you've ever had a chemist slap some death mix onto you)

**Comment by TheMeatGod** [comment]
-1, i liked this nerf

**Comment by ghost** [comment]
@HideAndSeekLOGIC good point... still tho, advanced hardsuit should actually have slowdown removed, else it's useless

**Comment by TheMeatGod** [comment]
Yeah can we get an advanced hardsuit buff

**Pull request closed without merging**
