### PR TITLE
Smoke machine board in tech storage.

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
tweak: Smoke machine is now a board available in tech storage.
/:cl:

Don't know why somebody added a fully assembled one at roundstart...even /tg/ doesn't have that.

Closes #4367

### CODE REVIEW

**Comment by KayeArray** [comment]
+1

**Review by KayeArray — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Code OK

**Review by praisenarsie — APPROVED** [review]

**Comment by PopNotes** [comment]
fair enough +1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
Since I think a headcoder's +1 also counts, i'm merging this with sadness

**Comment by dreamcrab** [comment]
+1000000000000000000

**Comment by ghost** [comment]
@dreamcrab your +1 or +1000000000000000000 doesn't mean shit. get headmin and then we'll talk

**Comment by dreamcrab** [comment]
uhh i am headmin

**Comment by ghost** [comment]
@dreamcrab what? what's your ckey

**Comment by dreamcrab** [comment]
teamstab

**Comment by ghost** [comment]
@dreamcrab i thought you were a GM or GA. but whatever, this is already merged

**Pull request merged**
