### PR TITLE
Taser Stun Reduction Test

### PR DESCRIPTION
**Pull request by ghost**
Let's take this for a spin.

Reduces taser stun time from 5 to 3. Still enough time to cuff a weakened target, but you'll have to go in and hit them with either a melee stun or krav maga pin otherwise. I have a whole, big ranged stun rework already written out, but I want to put this up to see both how the playerbase reacts and how it works in practice. I feel that even if this isn't something that we intend to keep, it should still be merged for a while to see if reducing ranged stun duration has a positive effect on combat so that the data can be used for future use.

### CODE REVIEW

**Comment by tortellinitony** [comment]
Please re-create the file to avoid conflicts.

**Comment by j-mie** [comment]
@tortellinitony Nah, edits like this should be fine.

Also please use the inline changelog system, not this one.

**Comment by ghost** [comment]
Sorry, haven't put anything up since before the rebase, I'll figure out the new changeling system tonight.

**Comment by ghost** [comment]
Can I get the DNM tag removed if Jamie is alright with it?

**Comment by ghost** [comment]
Closed due to a misunderstanding. No point running a short test on a code base that's not live.

**Pull request closed without merging**
