### PR TITLE
[MIRROR] Species types sources refactor, soviet and usa golem fix

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42523
----------------------------
There is now a bitflag that controls all the ways a species can be
selected from the different methods of changing species, xeno spawn,
pride mirror, magic mirror etc.

The soviet and capitalist golems are no longer selectable from the pride
or magic mirrors (just the badmin one)

interesting thing I found, androids and synths (including military
synth) are acheivable via xeno extracts!

:cl: oranges
balance: soviet and capitalistic golems no longer available from pride mirror
refactor: changed how species manage their source behaviours
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Soviet & Capitalist golems don't work on our side for some reason.

**Comment by Carbonhell** [comment]
Never saw a soviet golem so +1 i guess?

**Review by Carbonhell — DISMISSED** [review]

**Review by Carbonhell — CHANGES_REQUESTED** [review]
needs our species to be updated

**Comment by TheMeatGod** [comment]
+1

**Comment by Maroonenahmoron** [comment]
The two golems don't even have sprites. +1

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
