### PR TITLE
Wumborian fugu glands no longer work on stands

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by AnthonyJNgo** [comment]
+1 this is needed as a balance change before lowering cost for the other ability PR.

**Review by AnthonyJNgo — APPROVED** [review]
Do not merge until we get more votes. Code is fine though.

**Comment by Majick1** [comment]
+1 stands are already strong enough

**Comment by Maroonenahmoron** [comment]
+1, I don’t know who figured that out but it shouldn’t be an intended feature

**Pull request merged**
