### PR TITLE
[MIRROR] 512 experimental

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/31251
--------------------
What it says on the tin

http://www.byond.com/docs/notes/512.html

### CODE REVIEW

**Comment by PopNotes** [comment]
uh oh

**Comment by ghost** [comment]
@JamieH feel free to update the server

**Comment by ghost** [comment]
build this

**Review by ghost — APPROVED** [review]
ok whatever

**Comment by ninjanomnom** [comment]
Oh god you merged this into your master?

**Comment by ghost** [comment]
what were you supposed to do

**Comment by ninjanomnom** [comment]
image

**Comment by praisenarsie** [comment]
fuckin idiots

**Comment by KayeArray** [comment]
LMAO

**Pull request merged**
