### PR TITLE
many map fixes

### PR DESCRIPTION
**Pull request by Dinopeaks**
[Changelogs]: # fixes 2 of the map fixes links as follow
https://github.com/HippieStation/HippieStation/issues/7541

https://github.com/HippieStation/HippieStation/issues/7043

and adds the hedgehog to the map and it now will spawn in the cappys office 

:cl: optional name here
tweak: tweaked a few things
fix: fixed a few things
/:cl:

[why]: # this are small map fixes and changes that are quality of life and also small problems and add the hedgehog to the map

### CODE REVIEW

**Comment by JohnGinnane** [comment]
thank you ))

**Comment by Dinopeaks** [comment]
one small mistake so do not merge just yet

**Comment by Dinopeaks** [comment]
image

**Comment by Dinopeaks** [comment]
image
also made sure all pods will work as seen here

**Review by JohnGinnane — APPROVED** [review]

**Comment by Pyko1** [comment]
the upstream will revert this tho

**Comment by Pyko1** [comment]
since it does map changes

**Comment by Dinopeaks** [comment]
how do we fix this?

**Comment by Pyko1** [comment]
we just unfuck the upstream pr, and merge it
and then continue with map stuff.

Also the theater airalarm should had been fixed ages ago.

**Comment by Dinopeaks** [comment]
well umm i can't get you the map file if you need it until later

**Comment by Pyko1** [comment]
we should be able to recreate these fixes once we get the upstream done

**Comment by Dinopeaks** [comment]
well do what you need to but if you can't get the updated map i can get it to you at 2:30 EST

**Pull request merged**
