### PR TITLE
Antag hud for ghosts

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt
add: Ghosts can now have an antag hud, but they'll be unable to return to their corpse or be revived if they do so
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
do they also get denied any ghost roles,  drones,  etc?

**Comment by ghost** [comment]
no but i should do that

**Comment by ghost** [comment]
Done

**Comment by Carbonhell** [comment]
needs testing. I wouldn't be against the idea though, +1

**Comment by ghost** [comment]
i dislike the idea of players rage checking if someone who killed them is antag or not and thus fucking themselves over for cloning

**Comment by Carbonhell** [comment]
oh damn that's true, retracting my +1

**Comment by ghost** [comment]
On the other hand, it allows for observers to dogpile onto the antags, so they can actually watch some fun.

**Comment by ghost** [comment]
i don't really think that's been an issue, if you follow people in deadchat being salty, you find the murderbone antags, not only that you can just ask people in deadchat who is antag beforehand anyway

honestly if we didn't have ghost roles that people could technically meta with, and to give them the info easily with this, this would be okay for regular ghosts to have without fucking up their ability to clone

**Comment by ghost** [comment]
-1 nah

**Comment by ghost** [comment]
-1

**Comment by WarRage333** [comment]
Oh boy metagaming

**Comment by praisenarsie** [comment]
it's not happening, we have countless reports of metagame and metabuddies plus some people like switching to different ckeys *cough*. since this already has -2, closed unless carbon decides to give me the middle finger and say wait for -3!!!!! in which case, sorry carbon

**Comment by Carbonhell** [comment]
yeah mine was a -1 too so all good

**Pull request closed without merging**
