### PR TITLE
Upstrem2, the upperning [READY]

### PR DESCRIPTION
**Pull request by GuyonBroadway**
So we missed some shit out, imma updoot them here, it might fix our DB bugginess, who knows?

### CODE REVIEW

**Comment by JohnGinnane** [comment]
@GuyonBroadway let me know when you want this merged

**Comment by GuyonBroadway** [comment]
Ok this compiles and runs... I'll do some double checking to ensure nothing is overwritten but I think its ok.

**Comment by Carbonhell** [comment]
another? christ
hold off till tonight

**Comment by GuyonBroadway** [comment]
ok this is up to date, just gotta fix travis

**Comment by GuyonBroadway** [comment]
The is reado to go, one of the BIG change is the cargo points bounty system which replaces the stock market, cargo can now export a shopping list of items for points that keeps refilling.

Another change is how BoH bombing works, it creates a massive chasam area that sends people to another dimension with a tear in the fabric of reality in the middle. To escape they need to run to one of two ladders, one sends you somewhere randomly in space, the other sends you to lavaland. 

Another nice one is the printable anomaly neutralizer which is an easy way to neutralise anomalies and now R&D can decon spare anomaly cores for points.

Cargo can also get drop-pod beacons for their rapid crate delivery service.

**Comment by Jujumatic** [comment]
dude that BoH bombing sounds fucking awesome

**Comment by yoyobatty** [comment]
merg dis

**Comment by Jujumatic** [comment]
time to rippie hippie and redo all our nonmodular cancer

**Review by Jujumatic — APPROVED** [review]
fuck i needed to scroll through all of this on my phone

**Pull request merged**
