### PR TITLE
Krav Maga for Security

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: # This gives all of security (except the detective) krav maga.
:cl: Zamolxius
add: Krav maga implants for security
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

It was suggested and accepted.

https://gyazo.com/9331d3d898027e4595250ad5da185c0b

### CODE REVIEW

**Comment by JohnGinnane** [comment]
did you test this

**Comment by ghost** [comment]
will compile and run in a minute

**Comment by ghost** [comment]
doesn't work for some reason. also moods are enabled on my test server? is it a config thing?

**Comment by JohnGinnane** [comment]
Yeah it's a config thing although idk which one exactly (i also have it on and cba to turn off)

**Comment by JohnGinnane** [comment]
If you get runtimes in the dreamdaemon then post them in discord code channel so we can look at it

**Comment by ghost** [comment]
OH GOD I LEFT IT UNCHECKED IN THE DMB

**Comment by ghost** [comment]
yeah it works perfectly

**Comment by JohnGinnane** [comment]
neat

**Comment by JohnGinnane** [comment]
oh you'll want to push the changes to .dme so the server includes it as well

**Review by JohnGinnane — APPROVED** [review]
code looks good

**Comment by ghost** [comment]
okay cool, just need someone to remove the krav maga gloves from warden's locker then
+1

**Comment by JohnGinnane** [comment]
why? what if we leave them in there so there's some treasure for non-sec to plunder? Otherwise krav-maga will be almost always sec-only

**Comment by ghost** [comment]
alright, you make a good point, but do move them out of the warden's locker still, perhaps stick them in a locker in armory or on one of the racks

**Comment by JohnGinnane** [comment]
ye that sounds good

**Comment by ghost** [comment]
+1

**Pull request merged**
