### PR TITLE
[MIRROR] Clown Car balance changes

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40222
--------------------
:cl:
fix: The Clown Car can no longer move unrestricted in zero gravity environments.
/:cl:

This PR was done at the request of @ vuonojenmustaturska. I renamed entered.dm to sealed.dm because it's where the sealed subtype is defined and it's primarily used for procs specific to sealed. The balance changes were Naksu's idea. I definitely think not being able to move freely in space is a good change. I'm ambivalent about the TC, but the item felt like a gimmick that you should fully commit to like His Grace, and the free space movement + 4 TC space suit was a bit cancerous.

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
This pr is objectively shit by tg's own standards, its a mixing of a balance change and a fix, it was unpopular, it contains code changes that do nothing, everyone in the pr said why it was bad and not only did it get merged anyway, Oranges is closing any prs that revert some or part of it.

**Comment by HippieBartels** [comment]
Fuck this gay shit tbh

**Comment by Carbonhell** [comment]
which pr do we need to wait to merge this? @GuyonBroadway

**Comment by GuyonBroadway** [comment]
I want head input on this, the spacemoving was a bugfix but the price change is gay balance. Headmins give me your -1's.

**Comment by ghost** [comment]
-1 (price)

**Comment by Carbonhell** [comment]
fix must go in. Revert only the price, inside this pr if possible.

**Comment by Lxtoofonea** [comment]
-1

**Comment by earthmoonjune** [comment]
ye just revert the price

**Comment by Eagle-Eyess** [comment]
only price agreed -1

**Review by Carbonhell — CHANGES_REQUESTED** [review]
modularize you nib

**Review by Carbonhell — APPROVED** [review]

**Comment by Lxtoofonea** [comment]
+1

**Pull request merged**
