### PR TITLE
Maps an Antimatter Engine room into engineering

### PR DESCRIPTION
**Pull request by ghost**
An easy to set up engine, but dangerous if done wrong. I made the room big so you can add more cores by ordering them via cargo.

((YES I ADDED GRILLES TO THE WINDOWS AND LIGHTS TO THE ROOM AFTER THESE PICS!!))

ame_notsetup
ame_setup

:cl: thefastfoodguy
add: Engineering now has an Antimatter Engine!
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Well it looks nice únd mapmerged BUTT there is the small issue of not having put grilles under the windows.

**Comment by ghost** [comment]
@GuyonBroadway I fixed that (by using window spawners).

**Comment by KayeArray** [comment]
No I don't like this, the antimatter engine is an incomplete and boring engine. It has ugly horrible sprites, produces a fixed amount of power and has practically zero risk if you set the number right. And even if it does fail all it does is destroy itself in a maxcap explosion. The room you made is barebones as fuck and doesn't really add much to the map in and of itself.

**Comment by ghost** [comment]
@banthebantz It's supposed to be barebones, for maximum expansion room

**Comment by ghost** [comment]
>AME
Dangerous

It's just OP and uninteresting.

**Comment by ghost** [comment]
@McBawbaggings well one time the clown destroyed cargo by fucking with the AME

**Comment by ghost** [comment]
Think about it this way.
Singulo: Forces a shuttle call by destroying the station
Tesla: Forces a shuttle call by destroying the station
Shard: Forces a shuttle call for being a really big explosion and also being radioactive and making everyone trip out. You're also producing a burn mix which can be flooded into atmos or used to make bombs if you're savvy enough.
AME: Blows up like the shard but with none of the other effects and produces more power safely.

All engines are easy as fuck to sabotage, AME is no easier than any of the others.

**Comment by ghost** [comment]
@McBawbaggings:
AME: probably destroys the engineering SMESes and wiring, forcing a shuttle call due to power loss

**Comment by GuyonBroadway** [comment]
also this room has not atmos infrastructure.

**Pull request closed without merging**
