### PR TITLE
[MIRROR] [READY] reworked neurotoxin

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42507
----------------------------
## Changelog
:cl:
balance: neurotoxin doesnt insta stun but gives you limb paralysis overtime and heart attacks if it stays in for too long and it is also alcholic
/:cl:

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Code is good, but I want to wait for any feedback on this nerf

**Comment by GuyonBroadway** [comment]
Honestly neurotoxin has been the most anti-fun chem for years now and chemist mains have been massive fucking babies about any hint of a change to it.

N-Tox is so BS that we blacklisted it from being made into reagent weapons.

Maybe now it'll just be a fun bar drink as opposed to powergamer secret sauce.

**Comment by ghost** [comment]
I think this nerf makes it too weak though, that's the problem.

**Comment by GuyonBroadway** [comment]
Two points with regards to that

1: Good, again WE blacklisted it from the reagent forge because it was too strong. Any amount of this shit was a minimum 6 second stun and 5u stunned people longer than a fucking ebow. It being made weak is finally pushing chemistry crap back into fucking line.

2: It still fucks people the fuck up after this nerf. If its in thier system for more than 30 seconds, it paralyses limbs randomly which can eventually lead to total paralisys and constantly causes item drops. It also makes thier screen all druggy, does brain damage and is strong booze.
 This will render someone basically incapable of fighting and fuck them up but it's not an instant "gg u die now" chem.

**Comment by Jujumatic** [comment]
Not sure what to think, this gives you a heart attack after about 60 seconds

**Comment by GuyonBroadway** [comment]
Which is hard to do without bluespace syringes or multiple shots and really by the time you take 4 syringes from a chemist thats not bullshit chems, thats you being bad at video games.

**Pull request merged**
