### PR TITLE
[MIRROR] adds handholding

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/33831
--------------------
target arms while pulling
image
image

### CODE REVIEW

**Comment by JohnGinnane** [comment]
no

**Comment by JohnGinnane** [comment]
the absolute state of tg

**Comment by Swagile** [comment]
is this literally fucking real

**Comment by praisenarsie** [comment]
something something secret commit by oranges

**Comment by ghost** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by praisenarsie** [comment]
alright calm down chnkr

**Comment by cacogen** [comment]
"grabbed x by their hands" isn't exactly "holds x's hand". 

not that it matters now

**Pull request closed without merging**
