### PR TITLE
Holoparasites are now bound to mind

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Holoparasites now follow the user's mind -- meaning that if the user is mindswapped, the holoparasite will follow them into their new body.
add: Holoparasites will be revived if the user is cloned.
add: Monkeys and xenos can now have holoparasites too.
/:cl:

### CODE REVIEW

**Comment by ExpAntique** [comment]
+1

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by ghost** [comment]
wont this let you monkify and hang around in vents while your holopara snaks up on dudes and kicks their shit in. or worse interactions

**Comment by ghost** [comment]
also the holoparasites are in bloodstream

**Comment by TDcoolguy300** [comment]
🤔

**Comment by ghost** [comment]
-1 they're strong enough as is

**Comment by DaydreamPuppeh** [comment]
Does this mean that multiple personality can have multiple stands?

**Comment by ErwinSnowden** [comment]
Holoparasites are just stands which are bound to the soul and as seen when switched by Chariot Requiem, the users retained their stands. It only makes sense, unless say, someone sold their soul. Then they should lose their stand.

**Comment by ghost** [comment]
no holoparasites are little buggers in your bloodstream that use your energy to create a hardlight hologram

**Comment by Toxici11i** [comment]
+1, just because this fixes so many bugs related to stand arrows.

Also because having your holopara come back when cloned kinda makes sense since if anyone cares about jojoke lore holoparas are essentially the result of surviving an ayy supervirus

**Comment by ghost** [comment]
i am completely ignoring the ss13 lore and going with the jojo lore here

**Comment by ghost** [comment]
+1 cool jojo lore is cool.

One thing I'd like to add - pretty sure holoparasite users disintegrate on death, so cloning is already basically impossible.

**Review by ghost — APPROVED** [review]
This might be a bit much to test entirely but I assume you at least did a bit of rudimentary stuff here

**Comment by ghost** [comment]
yeah i tested with cloning and mindswap

**Pull request merged**
