### PR TITLE
Fixes map sparkers not working

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
fix: Fixes map wall mounted sparkers not working
/:cl:

## About The Pull Request
Title

## Why It's Good For The Game
Fix this dumb thing that was never addressed or code logic'd

### CODE REVIEW

**Comment by wheezl** [comment]
+3 thank u king

**Comment by ghost** [comment]
wheezl be like umm can u fix this 4 me coder slave 😅

**Comment by MrEpicSax** [comment]
+1 don't grab the switch

**Comment by carlopault** [comment]
+2 bug fixes should get automerged

**Pull request merged**
