### PR TITLE
Makes freon production less cancerous

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
tweak: Freon production has higher requirements and is formed at -20C now
tweak: Freon only freezes stuff when it's below 0C
/:cl:

## About The Pull Request
What it says in CL.

## Why It's Good For The Game
Freon currently can be produced by releasing plasma straight into the air. It will be produced when there's a fire, or anything, which ultimately puts the fire out and makes the area uninhabitable afterwards. This lowers the required temp to -20 celcius so it's still possible just needs to be cold.
Also freon doesn't freeze shit if it's too warm, which makes sense because freezing usually occurs at 0C and below, well for water at least. This doesn't hurt freon at all since the stuff you buy from canisters is already cold and it is already a reaction that gets colder when it reacts with nitrogen and general freon production now occurs at -20 so freon in general is not affected.

### CODE REVIEW

**Comment by Toxici11i** [comment]
I had no clue and still dont on how atmos works in terms of formation, thank you yoyo

**Comment by Manly-Dwarf** [comment]
this is why the toxiccode label exists
+1

**Comment by TrickyDickRichard** [comment]
very yes +1

**Comment by karmaisblackandbluepilled** [comment]
+1

**Review by ghost — APPROVED** [review]

**Pull request merged**
