### PR TITLE
Removes old hippie apc sprite

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
del: Removed hippie apc sprite fo goon sprite

Current: 
image

New: 
image

### CODE REVIEW

**Comment by ghost** [comment]
-1

das not it mane

**Comment by bardofrage** [comment]
+1, looks like an MS paint drawing.

**Comment by ghost** [comment]
no way,  its gay
-5

**Comment by TrickyDickRichard** [comment]
-1
with every sprite we change the looming threat of becoming a TG copy inches closer

**Comment by Jujumatic** [comment]
it's funny how you -1 this stuff as if you can exert any influence over the pr

image

**Comment by bardofrage** [comment]
The fact that it's from TG doesn't change the fact that it's simply a better looking sprite. Obvious that most people opposed don't like it simply because it's from TG.

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
better looking is subjective also keep in mind tg has a different self-opinion than we have they're more shitty and they do gay shit like balls meanwhile we got huge monkeys with lizard legs thing.  really the old APC sprite has nothing wrong why fix what's not broken.  the hippie APC sprite fits the game better than nu-tg sprite.  the hippie APC sprite is more visible than this one,  plus it has the classic feel when you see one in maint.  new tg sprites have way too many gradients and bluish colors instead of respectable straight-up conveying the information needed.  function over form (and the tg form is more shitty,  too) 
plus lets say you're walking in a dark maintenance tunnel,  the APC is like a light at the end of the tunnel.  the hippie sprite is way better as the tg sprite is dark by itself,  imagine how it's seen in maint,  plus the hippie sprite looks good in non-maint places,  too

**Comment by JohnGinnane** [comment]
is that a pasta?

**Comment by bardofrage** [comment]
The hippie sprite ( which i believe mcbaw said was from bay ) doesn't fit in at all with all of the other sprites in the game, and is noticeably less detailed.

**Comment by ghost** [comment]
its better though

**Comment by bardofrage** [comment]
for what reason

**Comment by ghost** [comment]
looks better and also detail=/=sprite quality
tg is adding sprites which look like shit but fit in with eachother (the 3/4 jew)

**Comment by JohnGinnane** [comment]
Just gonna try to address @zamolxius's points:

* _better looking is subjective_
Yes and no. "Better looking" is both subjective and objective. You can have an opinion about it but if it's doesn't provide the same information it's objectively worse, and vice versa with being better

* _really the old APC sprite has nothing wrong why fix what's not broken_
It's perhaps a little dated but it's not broken as you say

* _the hippie APC sprite is more visible than this one ... new tg sprites have way too many gradients and bluish colors instead of respectable straight-up conveying the information needed. function over form_
I agree with this a little. I think the /tg/ APC should have the lights be bright, while the case can have a gradient and be darker. The lights ARE the information and need to be easily identifiable

**Comment by ghost** [comment]
that sounds good just make the blue lights way more visible and make the casing a few shades lighter

**Comment by ghost** [comment]
yeah, blue on black contrast removes a lot of glance value
i also dislike how there's no longer a 1px gap between the main display and the power lights
having the power lights clearly separated by a different colour makes them easier to read

**Comment by Carbonhell** [comment]
Don't like it. Our sprite may be low quality but who gives a fuck, it's nicer. -1

**Comment by JohnGinnane** [comment]
@Carbonhell frig off

**Comment by Manly-Dwarf** [comment]
But these aren't even what Goon APCs look like. Goon APCs are literally plain white boards with singular lines, they don't have screens or anything like that. This isn't "changing us to Goon APC", this is "changing us to /tg/ APC"
Also nah. End the goonification of /tg/ and hippie.

**Comment by Pyko1** [comment]
No, the old APC sprite was was made as a hippie module to calm our autists.
If you change it, there will be no end to the autistic screeching.

-1

**Comment by McHatters** [comment]
I like it +1

**Comment by Carbonhell** [comment]
tbh seems like -1s win this one for now. Gonna wait some more days before closing tho

**Comment by Carbonhell** [comment]
Denied

**Pull request closed without merging**
