### PR TITLE
adds those weird songs erik asked me to

### PR DESCRIPTION
**Pull request by Carbonhell**
i have no clue wtf i'm actually adding

:cl:
soundadd: adds new lobby music by Hippie
/:cl:

[why]: he asked me

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Comment by ghost** [comment]
>Sonic CD
US ver
Past

aktually..... the past versions are universal and not even CD quality...
for real though, a lot of these are good choices

**Comment by ghost** [comment]
good

**Comment by ghost** [comment]
DNM!!!
files haven't been added to the roundstart lobby string song thing
https://github.com/HippieStation/HippieStation/blob/master/strings/round_start_sounds.txt

**Comment by Carbonhell** [comment]
why is thiS FUCKIGN SYSTEM SO FUCKING GAY GOD DAMN IT
why doesn't it just load all the files from the folder

**Comment by Carbonhell** [comment]
i refuse to add 100 entries to that fucking txt file
hold my beer, i'll get someone to fix this gay system

**Comment by Carbonhell** [comment]
thanks to mcbaw for the script used to make the .txt
you helped the shitty system, you should feel BAD

**Review by ghost — APPROVED** [review]

**Pull request merged**
