### PR TITLE
[WIP] Lcass machines stock part upgrade

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
tweak: Lcass chem machines now can have their stock parts upgraded to improve various features
balance: Lcass chem machine build requirements have been lowered
/:cl:

## About The Pull Request
I'm trying to make them like all types of machines you can find around the station. The next part of this PR is changing the examine description to give hints about their efficiency and capabilities.

## Why It's Good For The Game
Because we need science more involved in making cool stuff! But mostly because this has been needed for a while.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
This feels more like a forgotten feature than anything.
+1
we shouldn't need to vote on this

**Comment by Carbonhell** [comment]
Sure +1

**Comment by TheMeatGod** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Comment by Carbonhell** [comment]
Is this still WIP?

**Comment by yoyobatty** [comment]
Going to do one last test to make sure it's proper. Hold out for a bit.

**Comment by ghost** [comment]
@yoyobatty are those tests done?

**Comment by ghost** [comment]
@yoyobatty dood just tell us how the tests went and I'll merge it

**Comment by Jujumatic** [comment]
Stale, re-open if you still want to work on it

**Comment by yoyobatty** [comment]
Going to finish this up, sorry for the delay.

**Comment by funkynuggets** [comment]
Seems obvious, but +1

**Pull request closed without merging**
