### PR TITLE
Fixes loadout options not showing up.

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
fix: Fixes loadout not showing up in client preferences 
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by JohnGinnane** [comment]
based yoyo, i had this issue and could never make a loadout

**Review by JohnGinnane — DISMISSED** [review]
code looks okay, you tested it?

**Comment by yoyobatty** [comment]
pls don't merge

**Comment by yoyobatty** [comment]
Good to go!

**Comment by GuyonBroadway** [comment]
code looks good + tested

**Review by GuyonBroadway — APPROVED** [review]

**Pull request merged**
