### PR TITLE
[MIRROR] Fix old usages of trait introduced by the trait merge

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34894
--------------------
Fixes master build

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Awaiting merge of https://github.com/HippieStation/HippieStation/pull/6201 before this

**Comment by JohnGinnane** [comment]
build this pls

**Comment by JohnGinnane** [comment]
Don't actually need this PR

**Comment by Carbonhell** [comment]
Already done in another pr by @JohnGinnane ,closing

**Pull request closed without merging**
