### PR TITLE
The Economy Update:

### PR DESCRIPTION
**Pull request by AnthonyJNgo**
:cl:
add: Added new things
add: Added more things
tweak: tweaked a few things
balance: rebalanced something
imageadd: added some icons and images

/:cl:

**About the pull request, why it's good, and what it includes:**

This update aims to fix some issues that I had with Goofconomy. In my opinion these should have been added in the beginning, but it's whatever.  In this PR I will add ways for jobs to make money, related to doing their job; ways for anyone to make money, e.g. public garden, random tasks, etc; and I will balance prices station wide: e.g. a bag of jerky will not cost half of your paycheck if you are only a botanist.

I will continue to balance this after the initial release with some features that I think would make things better, but these three features listed above are good enough to bring some semblance of balance to our current extremely broken system.

**How will different jobs make money:**

Jobs will continue to have salaries, however there will be different levels of salary. Most jobs will have the ability to earn more money through various tasks.

The levels of salary are as follows:

Extremely high.
High.
Average.
Below average.
Horrid.

**Command:**

Captain: ExHigh.
HoS: ExHigh.
RD: ExHigh.
HoP: ExHigh.
RD: ExHigh.
CMO: ExHigh.

**Security:**
Warden: High + fines.
Detective: Above Avg.
Officer: Avg + fines.

**Engineering:**
Engineer: Above Avg + SMES + Solars.
Atmos Tech: Above Avg + Oxygen Output bonus.

**Science:**
Scientist: Above Avg + Slimes + Bombs.
Roboticist: Above Avg + borg shells + whoever gets borged.

**Medical:**
MD: Above Avg + fees.
Chemist: Above Avg + healing chem vendor.
Geneticist: Above Avg + every clone.
Viro: Above Avg + every isolated virus symptom.

**Service:**
Janitor: Horrid + trash vendor.
Bartender: Below Avg + unique drink one time + fees.
Cook: Below Avg + unique food one time + fees.
Botanist: Below Avg + crop payout one time.
Clown: Horrid.
Mime: Horrid.
Chaplain: Horrid + followers.
Curator: Avg + books.

### CODE REVIEW

**Comment by JessHorserage** [comment]
+1

**Comment by Majick1** [comment]
+1

**Comment by cris5311** [comment]
This needs quite a bit of work, even from the concept. 1. you said there is ExHigh, High, avg, below avg, and Horrid but about halve of all jobs are marked as "above average" which isnt one of the categories. Secondly making everyone pay differnt prices for the same shit is stupid, if you want assistants to be able to eat add a cheap alternative (like the one in the gulag but a tad better) to the station. But more ways to make money are a good idea if done right.

**Comment by AnthonyJNgo** [comment]
@cris5311 Hi, so the missing above average is just a typo, it was late at night. I'll edit it in a moment.

Also, prices for items will always be the same. What I meant was balancing prices, but everyone will pay the same price for the same item. Only salaries will be different. Hopefully that clears things up.

**Comment by cris5311** [comment]
In that case i think this would be a good addition to the game. I do miss the assistant on the list however.

**Comment by Lxtoofonea** [comment]
a few things, i want to have as few jobs only work on salary as possible, i think most of there money should be through bonces from doing there job. like the detective could get a large bonus from sec or crew hiring him to investigate someone or something. also economy is going to be half paying and half spending, the crew should have a HUGE number of useful and funny things to spend there money on, i dont doubt that that will happen, but i also think that crew to crew transactions should be ridiculously easy, like clicking on someone with your pda or examining them and clicking a button should allow you to transfer funds, very important that it is as easy as possible, but overall this is going to be an amazing addition to the game and fantastic for game health.

**Comment by cris5311** [comment]
You could make the payingbooth, but the size of a holdable item. The ID can create it and then you can just hand it over to get paid.

**Comment by FantasticFwoosh** [comment]
Subjective to earning money, the paystands on /tg/ never worked beyond a go-fund me donation booth and normally people are too un-cooperative to talk to barter. Restocking units for vendors (funds are split to be paid to related dept's on vendor type) are equally fiddly.

I believe that if you ever want to earn money through commerce, personally made and stocked vendors will allow assistants (scavenged maint goods), cargo (crates junk and excess) and service staff (Food/Drink) to earn credits by offering covenience, sort of like a MMO auctionhouse, balanced by what people produce & natural map assets.
> If George Melons finds a rare item in maintenance and instead chooses to auction/pawn it off to someone else in a vendor linked to their ID account, they stand to earn despite having horrific or non-existant wages.

**Comment by lunaman22** [comment]
+1 i think

**Pull request merged**
