### PR TITLE
Deletes Blastco remnants

### LINKED ISSUE #6902: Blastco needs to be removed
Since we are no longer using our own Centcom it needs to be removed from the Operative uplink and have the extra code removed.

### PR DESCRIPTION
**Pull request by tortellinitony**
No longer used.

closes #6902

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Why?

**Comment by Manly-Dwarf** [comment]
Why did you straight up delete the Blast Co. gear instead of reworking them into another item (e.g a crate full of the blast co. gear)?

**Comment by tortellinitony** [comment]
I didn't delete any of the gear.

**Comment by ghost** [comment]
Should just add it back to centcom

**Comment by Carbonhell** [comment]
-1, make it a crate or something

**Comment by Carbonhell** [comment]
wait the pr just remove unusued code, yeah go on but please also readd it as a buyable crate

**Review by ghost — CHANGES_REQUESTED** [review]
Please just modify our own centcomm again, it was never meant to be removed.

**Pull request closed without merging**
