### PR TITLE
makes gravity holoparasite 1 point cheaper

### PR DESCRIPTION
**Pull request by diegoxt45**
🆑
balance: gravity now costs 3 points.
/🆑

because 4 points is too much

this and the other 2 prs were supposed to be just 1 pr but i don't know how to add multiple commits

### CODE REVIEW

**Comment by yoyobatty** [comment]
You literally just right click and hit commit and type a message

**Comment by diegoxt45** [comment]
> You literally just right click and hit commit and type a message

can i get that in monky language

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by Manly-Dwarf** [comment]
+1

**Review by ghost — APPROVED** [review]

**Pull request merged**
