### PR TITLE
[MIRROR] Block OOC during cinematics

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/38846
--------------------
Then again the spam is usually funny.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
for reference we had issues with people going "wtf it was *X gamemode*" while the nuke was detonating because they thought the round was over

**Comment by ghost** [comment]
kinda seems like a non issue?
@Carbonhell should we override this or no?

**Comment by Carbonhell** [comment]
Override

**Review by yoyobatty — APPROVED** [review]

**Comment by Carbonhell** [comment]
>asks to override
>Silently merged
@yoyobatty REEEE DUDEA

**Pull request merged**
