### PR TITLE
Readds ghetto chem to biohazard disposals maint

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: Ghetto chemistry is now back in maint below virology.
/:cl:

[why]:  

image

I know @t-f-w wanted this

### CODE REVIEW

**Comment by Carbonhell** [comment]
Wasn't it abused while it was in?

**Comment by GuyonBroadway** [comment]
Not really, it just meant that people could make skewium without breaking into chemistry.

**Comment by TheMeatGod** [comment]
+1 Skewium was said in this thread

**Comment by yoyobatty** [comment]
I mean it's now in the south east maint, away from powergamey hang out spots near engineering/cargo maint, so hopefully it works better here.

Edit: I just remembered, I added carbonic fluoride as one of the emagged chems which is actually an easy to make lcass chem, and I downgraded the cell type so it can't simply be spammed for whatever chems you like.

**Comment by RafRoq** [comment]
merge im tired of having to break into chemistry or science

**Comment by yoyobatty** [comment]
Uh oh, I cucked my own PR

**Comment by ghost** [comment]
+1 we need more fetanyl and phlogiston with some impredezene for syringe guns yey

**Pull request closed without merging**
