### PR TITLE
Revert "[MIRROR] You can now buy double eswords from the uplink, but you can no longer use two eswords to construct them"

### PR DESCRIPTION
**Pull request by tortellinitony**
Reverts HippieStation/HippieStation#1115

I don't know if we want this or not

### CODE REVIEW

**Comment by ghost** [comment]
literally never understood why double eswords for 16TC was broken.
I think they're fine.

**Comment by tortellinitony** [comment]
This just makes it so you can't buy them on lowpop, and that you cannot disassemble it, etc...

I agree with it to be honest

**Comment by ghost** [comment]
Unless I'm super out of touch with modern eswords, I don't see the huge need for the nerf but keeping it in place does make harder to murderbone at low pop with them. I guess I'm okay with this change since it doesn't outright remove the mechanic unlike the previous attempt at the PR.

**Comment by GuyonBroadway** [comment]
My one worry is that they didn't add a double balded sword to the sith lord bundle meaning you are now stuck with two normal energy swords. 

Otherwise I agree with the idea of being able to balance both items independently.

**Comment by ghost** [comment]
That's a good point broadway. I'd just make it a double esword to keep the balance of that kit.

**Comment by GuyonBroadway** [comment]
The thing is the kit came with a mind slave implant, so the choice was to either make a dualie for yourself or give the spare to your "apprentice"

**Comment by KayeArray** [comment]
/tg/ fucked with the dual esword and buffed it a fair amount so I'd say this is fair, just fix the sith lord bundle first.

**Comment by ShadowDeath6** [comment]
@GuyonBroadway 
https://github.com/HippieStation/HippieStation/pull/1115/files#diff-c2965a61d869f900803d28cb234b7feeR94

**Comment by tortellinitony** [comment]
OK well I guess if the Sith bundle works, then nobody really minds. So someone can reopen this if they're REALLY MAD

**Pull request closed without merging**
