### PR TITLE
Adds Maintainer rank

### PR DESCRIPTION
**Pull request by ghost**
they can mentor and debug shit... but not much else

good for looking at runtimes after shit fucks up

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Code is ok but this is a BIG thing.

**Comment by GuyonBroadway** [comment]
Like we need to discuss this and gain full consent of the host, headmins AND headcoder for this.

**Review by GuyonBroadway — APPROVED** [review]

**Comment by ghost** [comment]
Config is not stored on git

**Comment by ghost** [comment]
yet it's useful to have our config be up to date with git's

**Comment by j-mie** [comment]
this is super abusable. we've had bad history with abusive coders/maintainers in the past and have kinda come to the conclusion that it's easier not to risk burning bridges by giving coders/maintainers ingame access.

runtimes are all stored in a text file per a round here: https://tools.hippiestation.com/parsed-logs/hippie/data/logs/2017/

happy to give access on a round by round basis for debugging but realistically you can do it locally.

**Comment by ghost** [comment]
very much what jamie said

**Comment by GuyonBroadway** [comment]
Another point is people with the coder rank come up as admins and get bitched at in ahelps to resolve ahelps but they aren't allowed to.

**Pull request closed without merging**
