### PR TITLE
Replaces wrestling kit with just the belt

### PR DESCRIPTION
**Pull request by tortellinitony**
Pointless to have a kit now.
:cl: Tortellini Tony
del: Traitors now buy the wrestling belt directly. Price increased.
/:cl:

### CODE REVIEW

**Review by KayeArray — APPROVED** [review]

**Comment by PopNotes** [comment]
This and the removal of the football set pretty much epitomize your "I cannot stand fun" attitude. -1 from me.

**Comment by Arzion5** [comment]
Actually, the belt CANNOT work without the kit. You can't use the wrestling martial art with the belt equipped without wearing the wrestling attire

**Comment by tortellinitony** [comment]
Yes you can...

**Comment by Pyko1** [comment]
i thought the whole idea of the kit was to be like pro wrazzling set, instead of herp derp stealth sports melee.

**Comment by tortellinitony** [comment]
The only reason I added the kit was to make it a kit to fit with the sports bundle. None of the items really do much, the belt is the only thing that's worth anything in it.

**Comment by ghost** [comment]
is there anything wrong with the set having fluff items?
granted, people can just get the stuff anyway from the pool area

**Comment by tortellinitony** [comment]
I don't like the idea of having a bunch of kits, really. I don't see why it should have a bunch of fluff when it used to be just sold as a belt (For 13 TC, mind you)

**Comment by ghost** [comment]
ye but that's like saying the dark sith set doesn't need the chaplain hoodie

it's nice its there because it adds to the theme of the set and encourages to use it

**Comment by tortellinitony** [comment]
yeah but you can't just buy the dark sith set outright, I don't like that the traitor uplink is becoming like the TF2 class choosing screen and I think the wrestling kit jams the belt into that archetype for no reason now

**Comment by Arzion5** [comment]
I've nerfed the TC price on the wrestling belt because it is not as powerful as it once was. It is now a HUD-button martial art that deals moderate damage with each ability.
Throw : Stuns you for a while during throwing spin then stuns the other person for 2 seconds after throwing said person.
Body slam : May deal either between 20 to 30 damage or 10 to 20 damage
Headbutt : Deals between 10 to 20 damage and makes someone unconscious for 2 seconds
Kick : Deals between 10 to 20 damage, if the person hits a wall they are stunned for 2 seconds
Drop dive : If you fail it, you get stunned for 6 seconds and get between 10 and 20 damage. Successfuly dropping on someone after you've had enough time to climb the table deals only between 20 and 30 damage and stuns them for 4 seconds.

In contrast, pre-rebase hippie wrestling had no HUD buttons but extremely damaging moves. It wasn't uncommon to drop from 100 to 50 or 40 health because of a powerful move.

**Comment by ghost** [comment]
# -1

**Comment by j-mie** [comment]
Not broken, no need to remove IMO.

**Pull request closed without merging**
