### PR TITLE
You now only get 15 of each mat from thanus wardec

### PR DESCRIPTION
**Pull request by ghost**
:cl:
balance: You now only get 15 of each mat from thanus wardec
/:cl:

Possible alternative/companion to https://github.com/HippieStation/HippieStation/pull/12007

### CODE REVIEW

**Comment by Majick1** [comment]
+1 this one, drop the other one

**Comment by Manly-Dwarf** [comment]
mad
-1 to both of these

**Comment by cb583** [comment]
-1

**Comment by ghost** [comment]
How about you just fix the OP shit you're trying to disable? If uranium rounds are that OP against Thanos, then they're OP in general. Just bump down the damage modifier on uranium bullets, and make penetration their primary use.

The whole forge system needs a rework anyway, so may as well drop this shit and get on it.

**Comment by ghost** [comment]
Uranium bullets aren't overpowered in normal play and this doesn't look like a good fix across the board.

I think I'll close this for the time being, reopen if you don't agree.

**Pull request closed without merging**
