### PR TITLE
Updates science from box station and adds nanite lab

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: Added nanite lab in eastern science maint.
add: Updated science from box station but re-added hippie style changes
del: Bluespace recomb and radioactive lcass chem machinery removed from science to make space.
tweak: Added a shower in the lcass chem lab in science.
/:cl:

[why]: 
The reason why I removed the bluespace and radio lcass machines were for a very specific reason. Chemistry got an update to include them and since it was essentially a copy a paste, it served the one in science as just an extra resource of free uranium and bluespace crystals on top of the lab already being capable of nuking the station alone. Chemistry should have always had these machines available from the get-go so the inclusion of them will serve as making chemistry more useful in the long run.
dreamseeker_2018-08-22_13-32-10
dreamseeker_2018-08-22_13-32-32
dreamseeker_2018-08-22_17-03-55
dreamseeker_2018-08-22_17-04-14

Updated pics. ^

### CODE REVIEW

**Comment by Carbonhell** [comment]
thank you

**Comment by Carbonhell** [comment]
Science maint with random floor and plating looks ugly as fuck, can't we just move the machinery in the same place with circuits?Or at most in testing lab,and leave the maint as it was before?

**Comment by yoyobatty** [comment]
The idea was to have it sort of blend the transition, if you like I can do some cosmetic tweaking and send you the results in discord.

**Comment by ghost** [comment]
please do the visual tweaking aye
otherwise +1

**Comment by yoyobatty** [comment]
Tweaks applied to original post

**Comment by JohnGinnane** [comment]
Is this ready? This looks great btw

\>subtle nerf to sci
a shekel for a good goy

**Comment by JohnGinnane** [comment]
Honestly I love these changes yoyo

**Comment by Carbonhell** [comment]
looks fine

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
