### PR TITLE
Buffs the Interdimensional Sword

### PR DESCRIPTION
**Pull request by ghost**
:cl:
balance: The Interdimensional Sword now deals a total of 25 damage, up from 17.5
balance: The Interdimensional Sword now has a higher chance to dismember.
balance: The Interdimensional Sword will no longer ignites things that it dismembers
balance: When the Interdimensional Sword does not dismember, it will impale the victim, set them on fire, and cause blood loss and bleeding.
/:cl:

### CODE REVIEW

**Comment by MaterialisticThings** [comment]
+1

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by Majick1** [comment]
-1 I don't think the wizard needs more buffs to damage right now, even if this one spell is garbage

**Comment by diegoxt45** [comment]
+1 yeah ok

**Comment by AnthonyJNgo** [comment]
This sounds like it is entering "fireball" territory to be honest, and we all know how strong fireball is.

**Comment by ghost** [comment]
@AnthonyJNgo i don't want it to stay in "pretty much useless" territory though

**Comment by Manly-Dwarf** [comment]
wizard crap

**Comment by Maroonenahmoron** [comment]
This is fine, god forbid if it gets any more buffed than this

**Comment by cris5311** [comment]
+1

**Comment by Dystarra** [comment]
+1 Sword as it stands now is kind of useless, the meta or whatever you wanna call it is just get timestop or go Thanus. It'd be nice to give motive to take some other shit.

**Comment by zipzipzapityzoo** [comment]
+1 feels very underwhelming to use

**Comment by ghost** [comment]
+1, this is wizard gear we're talking about.

**Comment by karmaisblackandbluepilled** [comment]
+juan

**Comment by Dystarra** [comment]
+1

While some people may whine that "wizard is OP", it's only because of the few spells that are basically the meta. It'd be nice to give more reason to take other things besides Thangus, or mindswap or summon spam.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
