### PR TITLE
[MIRROR] Adds the Tomb of the Unknown Employee

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/25003
--------------------
:cl: Every coder, player, and admin in Space Station 13
add: Adds the Tomb Of The Unknown Employee to Central Command,
add: Rest in peace, those who died after contributing to Space Station 13.
/:cl:

Ported from
https://github.com/HippieStation/HippieStation13/pull/450
with a sprite by @WJohn 
dreammaker_2017-03-11_17-59-52
http://abc30.com/traffic/3-killed-in-hwy-99-crash-in-merced-chp-says/1790559/

### CODE REVIEW

**Comment by Spacedong** [comment]
this changes sprites and other shiit from /tg/, remove this

**Comment by tortellinitony** [comment]
this pr was made by tg

**Comment by Iamgoofball** [comment]
yeah you guys already added this for ArcLumin in specific

**Comment by cacogen** [comment]
The sprite here is better than the one we're using. Should probably make a different pull replacing it with this one.

**Comment by Iamgoofball** [comment]
This is generalized for all coders, yours is specific for ArcLumin.

**Comment by ghost** [comment]
build this

**Comment by tortellinitony** [comment]
We need to add the file to hippiestation.dme

**Comment by cacogen** [comment]
so did we add this tomb in addition to the arclumin one? because the bodies are really stacking up.

**Pull request closed without merging**
