### PR TITLE
Adds tritium canisters to atmospherics and toxins

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
add: Adds tritium canisters to atmospherics and toxins
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
-1
make your tritium you fucking lazy cunt

**Comment by ghost** [comment]
@praisenarsie your -1 means nothing

**Comment by praisenarsie** [comment]
i know how to assmos and you don't, checkmate atheist.

**Comment by KayeArray** [comment]
idk LOL

**Comment by ghost** [comment]
Tritium is radioactive and flammable, it makes no sense to add this as a roundstart gas

**Review by ghost — APPROVED** [review]
Code OK. Needs @HippieStation/head approval

**Comment by KayeArray** [comment]
>radioactive
>flammable
yeah no -1

**Comment by ghost** [comment]
@banthebantz it'd be pretty hard to flood the station with it, it's main use is FUSIONNNNNN

**Comment by praisenarsie** [comment]
@MoreRobustThanYou again, make it.

**Comment by dreamcrab** [comment]
-1337 make it!!!!

**Comment by PopNotes** [comment]
this probably won't go through

**Pull request closed without merging**
