### PR TITLE
No more dumb foam!

### PR DESCRIPTION
**Pull request by ghost**
:cl:
del: Vent clog foam events should be NO MORE, because all they do is make everyone unhappy, cause lag, and last forever!
/:cl:

### CODE REVIEW

**Comment by SireTurret** [comment]
grudgecoding is bad

**Comment by ghost** [comment]
so is foam

**Comment by mikolaj007** [comment]
+1, foam is kinda fucked rn

**Comment by WarRage333** [comment]
It really adds nothing to rounds when more fun events could trigger

**Comment by Manly-Dwarf** [comment]
+1 speedmerge

**Comment by Maroonenahmoron** [comment]
It's too much foam. +1

**Comment by DaydreamPuppeh** [comment]
Admins can still activate it right?

**Comment by mikolaj007** [comment]
yes, it just decreases occurence, not straight up removal

**Review by cris5311 — APPROVED** [review]
+1, fuck that stupid foam

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
yeet

**Pull request merged**
