### PR TITLE
Pressing who verb now shows admin rank

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: Pressing who verb now will now show admin rank next to their name
/:cl:

[why]: Just so you know who's who.

### CODE REVIEW

**Comment by Lxtoofonea** [comment]
thanks yoyo, very cool

**Comment by Lxtoofonea** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Comment by yobob591** [comment]
+1

**Pull request merged**
