### PR TITLE
Open wire now OPENS THE DOOR.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
tweak: Open wire now OPENS THE DOOR.
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
That was fast, did you test it?

**Comment by bardofrage** [comment]
+1 assuming it works.

**Comment by ghost** [comment]
@GuyonBroadway No, but it should in theory worked.

Before, it opened ONLY if ```if(!A.requiresID() || A.check_access(null))``` passed, which means it opened only if the door didn't require special access (a guy without an ID could open it). I removed that check.

**Comment by GuyonBroadway** [comment]
test it anyway pls, juuust in case

**Comment by ghost** [comment]
Sure

**Comment by ghost** [comment]
it works, tested it on bridge door

**Comment by PopNotes** [comment]
change works but it makes cats invisible

**Comment by ghost** [comment]
Wat

**Review by GuyonBroadway — APPROVED** [review]
Code is good, needs another +1

**Comment by tortellinitony** [comment]
I remember this pissed a lot of people off last rebase when it was added back

**Comment by j-mie** [comment]
-1 I'm kinda against adding this back, it makes it way too easy to get through the station.

**Comment by GuyonBroadway** [comment]
I agree, streamlining greytiding goes against what greytiding is all about, namely being able to triumph despite you having nothing but maint access and the grey jumpsuit on your back.

**Comment by ghost** [comment]
i dunno, it does make a bit easier to access departments, but it does mean people aren't cutting power to doors to break in.

and currently, it's waaaay too easy to break into departments with guns and other shit, and that perma fucks the door and that is even worse imho

**Comment by Pyko1** [comment]
I think this is great, it does not fuck up doors, and is only a crowbar swing faster.
And its restricted to multitool that is slightly harder to get than wirecutters.

Also with this you can make voice/motion/health/signaler operated automatic doors.
Which i personally loved to make.

Now if this is too fastto break in, just add a restriction, like having to cut ai control wire to override.

**Comment by ghost** [comment]
> Now if this is too fastto break in, just add a restriction, like having to cut ai control wire to override.

wouldn't that encourage mass cutting of the AI wire

**Comment by Arzion5** [comment]
I like this PR. The current additional step of using a crowbar contributes absolutely nothing. Almost every single greytider has the equipment required to open doors anyway.

**Comment by tortellinitony** [comment]
just to make it clear, the wire currently does try to open the door, but if access is required then it will fail and make a buzz

**Comment by ghost** [comment]
New system is retarded, and doesn't actually stop anyone from breaking in, just bricks doors. I want muh voice activated door for muh rape dungeon.

**Comment by j-mie** [comment]
@QuarianCommando You can have that if you cut the ID wire first. You just have to cut the ID wire and then you can pulse open/close the door.

**Comment by ghost** [comment]
open the airlock

stop having it be closed

**Comment by j-mie** [comment]
Not enough +1s

**Comment by PopNotes** [comment]
This PR had a total score of +1 and Bruce never cast a vote, he needs to do so.

**Comment by PopNotes** [comment]
open the pull request
stop having it be closed

**Comment by Pyko1** [comment]
welp clearly at positive and not all votes casted

**Comment by DinduStuffin** [comment]
+1 yeah sure

**Comment by earthmoonjune** [comment]
+1 from me mang

**Comment by Arzion5** [comment]
+1, I am definitely not a greytider

**Comment by PopNotes** [comment]
+1 for the great flood

**Comment by j-mie** [comment]
I'm gonna server poll this.

**Comment by ghost** [comment]
getting stale

**Review by j-mie — APPROVED** [review]

**Pull request merged**
