### PR TITLE
Toxins 3.0

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Remapped toxins
/:cl:

Why: FOR POWERGAYMERS, BY POWERGAYMERS

### CODE REVIEW

**Comment by DaydreamPuppeh** [comment]
3.0 actually

**Comment by AnthonyJNgo** [comment]
+1 this looks nice and is a QOL thing.

**Comment by yoyobatty** [comment]
It's a little bland, maybe make it look more like a proper mad scientist lab

**Comment by lunaman22** [comment]
Now this does put a smile on my face.

**Comment by Majick1** [comment]
+1 it works

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
