### PR TITLE
[DNM, testmerge-only] Maptick

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/yogstation13/Yogstation/pull/7553

should hopefully reduce lagspikes

### CODE REVIEW

**Comment by KingTerrytheTerrible** [comment]
we don't need this, name one last time we had a lagspike

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Let the hate flow through you

**Comment by KingTerrytheTerrible** [comment]
> 
> 
> Let the hate flow through you

this is a terrible idea

**Comment by ghost** [comment]
@KingTerrytheTerrible we literally had lagspikes yesterday

**Comment by Toxici11i** [comment]
> @KingTerrytheTerrible we literally had lagspikes yesterday

didnt see that

also, >>>merging stuff from yog

oh boy here we go again

**Comment by ghost** [comment]
this doesn't work on linux rn, need to find out why

**Comment by Toxici11i** [comment]
so far hasnt had a visible affect ingame. If its taking up extra CPU and memory to do maptick, it currently isnt worth it.

**Comment by ghost** [comment]
@Toxici11i How would this take up extra CPU/memory? It simple just sets a global var, and the MC adjusts based on that var.

Do you even know what this is?

**Comment by Toxici11i** [comment]
> @Toxici11i How would this take up extra CPU/memory? It simple just sets a global var, and the MC adjusts based on that var.
> 
> Do you even know what this is?

no tbh and idc, its a yog feature.

However, do profile its effect on the MC.

**Comment by AnthonyJNgo** [comment]
"I don't know how this feature works, and I don't care what it's supposed to do, please remove it."

Quit clogging up the repo @Toxici11i , we need to testmerge this to find ways to optimize server performance.

**Review by AnthonyJNgo — COMMENTED** [review]
Everything looks fine, waiting on Steamport to finish debugging before I approve.

**Comment by Toxici11i** [comment]
> "I don't know how this feature works, and I don't care what it's supposed to do, please remove it."
> 
> Quit clogging up the repo @Toxici11i , we need to testmerge this to find ways to optimize server performance.

what so you mean reserving 20% of the tick time the mastercontroller gets just for maptick, and then adding a restrictor on the mc is to "improve server performance"

what the fuck, crashing the server will be even easier after this is merged


"Today we shall port yog content that restricts 20% of the MC just for maptick, oh and also, we will make the MC compensate for this by making it so it compensates by lowering the max tick limit haha..."
#define TICK_LIMIT_RUNNING (max(90 - MAPTICK_LAST_INTERNAL_TICK_USAGE, MAPTICK_MC_MIN_RESERVE)) 

fuck off this is a slime PR from yog

**Comment by ghost** [comment]
@Toxici11i I do not trust your judgement. Basically, maptick allows the MC's ticking to compensate for how much of a tick is used by BYOND's "SendMaps" function. The internal BYOND tick usage usually hangs around 15-20% on the live server, sometimes spiking higher.

I trust Asd's knowledge much more than your guesswork.

**Comment by KingTerrytheTerrible** [comment]
close this, lagspikes are apart of the BYOND experience. also asd has no knowledge

**Comment by carlopault** [comment]
that moment when I got this unmerged because I fucked around on zero pop

**Pull request closed without merging**
