### PR TITLE
Deletes Dildo.dm

### PR DESCRIPTION
**Pull request by Spankmaster1066**
[Changelogs]: #Removes the Dildos that nexendia put into the game. They are not even used, and if they were ever used it would be disgusting anyways. 

:cl: Spankmaster
del: Removed nexendia's dildos
/:cl:

[why]: # Read my other PR, they have to go. They're dangerous and wrong.

### CODE REVIEW

**Review by KayeArray — APPROVED** [review]

**Comment by KayeArray** [comment]
+1 useless bloat shit

**Comment by GuyonBroadway** [comment]
They are never used in game, we either add them to the map or delete them. I remain neutral but if nobody adds them to the map before the this PR gets +3 then they are gone.

**Comment by praisenarsie** [comment]
this pr will test whether the current headmins are 💩 or 🥇

**Comment by ghost** [comment]
No

**Comment by Spankmaster1066** [comment]
Hmmmm Well her's the thing:

**Comment by ghost** [comment]
remove this immediately

absolute fetish BULLSHIT

+1

**Comment by ghost** [comment]
yeah sure
+1

**Comment by ghost** [comment]
Yeah, let's just nuke it

**Pull request merged**
