### PR TITLE
Crab bans

### PR DESCRIPTION
**Pull request by ghost**
crab
:cl:
add: Added crab bans. They're like cat bans, but you're a crab.
fix: You can now G2G while catbanned if you're not a cat
/:cl:

you owe me one antag token, Turret

### CODE REVIEW

**Comment by SireTurret** [comment]
Scratch the unbanning part, but I'll give you a token if (((someone))) doesn't label this as some "stupid fucking shit" and this will actually get merged.

**Comment by ghost** [comment]
there is no "stupid fucking shit" label 😉

**Comment by mememanrino** [comment]
:crab: CLUWNEBAN IS REPLACED :crab:

**Comment by G-erma** [comment]
+1 instamerge this right now

**Review by yoyobatty — APPROVED** [review]

**Comment by Manly-Dwarf** [comment]
inb4 this breaks everything

**Comment by GuyonBroadway** [comment]
> there is no "stupid fucking shit" label wink

That's where you're wrong kiddo!

**Comment by ghost** [comment]
NOPE

**Comment by GuyonBroadway** [comment]
It's in the logs lad!

It cannot be hidden!

**Comment by Manly-Dwarf** [comment]
ok

**Pull request merged**
