### PR TITLE
gremlins can now ventcrawl

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
tweak: gremlins can now ventcrawl
add: gremlins now split into two smaller gremlins with half the health when sprayed with water
/:cl:

### CODE REVIEW

**Review by GuyonBroadway — APPROVED** [review]
cod is gúd

**Comment by ghost** [comment]
for me, it's choose between ventcrawl and buff to health. can't have both.

the splitting gremlins is p. gud tho

**Comment by ghost** [comment]
@Dudeinyourbackyard is that a +1 to everything else if health is set back to normal?

**Comment by ghost** [comment]
yes indeed

**Comment by ghost** [comment]
So that's a +2!

**Pull request merged**
