### PR TITLE
[MIRROR] Updates titanium and plastitanium floor sprites.

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/39723
--------------------
**EDIT: Updated slightly to be less eye catching.**

New titanium floors! The intent here was to reduce the eye strain that the current max saturation fuckbois have, and make some floor tiles people might actually consider using. Right now the options are still pretty limited with blue, yellow etc only coming in full tiles, and I expect this will remain so until an actual greyscale rework comes along that shrinks the file size down from its bloated 4,000 sprites to something more reasonable and modular. Decals, perhaps?

For comparison's sake, this is what our current shuttle tiles look like. Don't let familiarity cloud your judgement: https://i.imgur.com/VwpS2vc.png

Also, I added 5 damage states for these so they'll look much nicer when broken. More can be made in the future, if need be. Here they are in action: https://i.imgur.com/XH1jSVA.png
Note: The plastitanium floor's damaged icons are black because that's the default color. Red is just a subtype.

:cl: WJohnston
imageadd: Remade titanium and plastitanium floors to be less of an eye strain and something mappers might actually consider using.
/:cl:

### CODE REVIEW

**Review by JohnGinnane — APPROVED** [review]

**Comment by ghost** [comment]
this looks horrible,  that smooth shit

**Comment by JohnGinnane** [comment]
homie you can change it if you think it's bad

**Comment by praisenarsie** [comment]
oh my god i saw this in creative general and saw the floors were neat but the idiot spriter gave it more contrast and changed the style somewhat to remove the accidental swastika that was embedded into it

**Comment by praisenarsie** [comment]
the only good looking one there is the yellow tiles, the walls look like they were pillow shaded then the spriter rubbed it out

**Comment by JohnGinnane** [comment]
\>accidental swastika
that was no accident

but for real we have a `icon_hippie` var where you can override tg icons, I think APCs and machines use it

See here: https://github.com/HippieStation/HippieStation/search?utf8=%E2%9C%93&q=icon_hippie&type=

**Pull request merged**
