### PR TITLE
Fix holotool radial menus

### LINKED ISSUE #9589: as RD i used the holo tool and its radial menu wont go away.
Issue reported from  Round ID: 32472 (Hippie Station)

Reporting client version: 512

### PR DESCRIPTION
**Pull request by ghost**
copypaste

:cl: steamp0rt
fix: Fixed holotool radial menus
/:cl:

Fixes #9589

### CODE REVIEW

**Comment by yoyobatty** [comment]
But did you compile, go, start game, game panel, object, holotool, ctrl?

**Comment by ghost** [comment]
>spawning object via game panel

lol

**Comment by yoyobatty** [comment]
so did you test it?

**Comment by ghost** [comment]
doing so rn. do not merge yet

**Comment by ghost** [comment]
There we go, it works, tested. @yoyobatty merge plz

**Review by yoyobatty — APPROVED** [review]
That looks better

**Pull request merged**
