### PR TITLE
replaces the nerfed protolathe with a liberated one

### LINKED ISSUE #8919: [SUGG] Re-add omnilathe to RnD
[Title]: # Re-add omnilathe to RnD

[Implementation]: # Add the omnilathe back to reserach

[Why]: # Okay so now that RD's locker removed firing pins, can we have omnilathe back in science. Biggest fear of it was people were gonna print guns in science!!!, but now that's gone and you need to break into armory for those or order in cargo and break open crates. Anyone want to to say nay to and explain why a place that researchs things does not get to create them

[Resources]: # I'm not sure if any of the old computers remain in the code but the board for it should still be in the code, if the computers are removed just make the omnilathe craftable / spawned in RD's locker

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: # replaces the lathe in RnD with an omnilathe
Closes #8919 
:cl: zamolxius
add: Added an omnilathe to RnD
balance: the RnD lathe can now fabricate items from any department
/:cl:

[why]:

### CODE REVIEW

**Comment by ghost** [comment]
have my useless +1

**Comment by Eagle-Eyess** [comment]
+1 bring it back

**Comment by yoyobatty** [comment]
I like the idea, but can we please stop buffing science? It's literally miles ahead of any other department including security.

**Comment by ghost** [comment]
ill close it if you guys want

**Comment by ghost** [comment]
plz no

**Comment by WarRage333** [comment]
oh no not the science buff they will be able to make hologram projectors in science now and light replacers god forbid they make x-ray eyes after the miners bring ore back for once

**Comment by Carbonhell** [comment]
I mean, sure, +1. But I agree with yoyo, i want other departments to get some love after this.

**Comment by praisenarsie** [comment]
i thought techwebs was so great, i thought people will find cool ways to make research more interesting but alas no one got anything

@Carbonhell lmao implying scientists don't open up RnD after they have 1 billion mats, upgraded everything and everything unlocked
*sips* yup pre-rnd was a good time

**Comment by Carbonhell** [comment]
Pre-accepted due to the feature suggestion. Just fix it up and it'll go in.

**Comment by Shdorsh** [comment]
You could buff other departments with omnilathes, though the usefulness of it would be questionable, since it would normally fall out of their job's domain.

**Comment by ghost** [comment]
this one is ready

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
