### PR TITLE
Allows robotics console to blow up integrated circuit assemblies (WIP) 

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
add: RD's robotics console can now destroy integrated circuit assembles
/:cl:

## About The Pull Request
What the title says. It's kind of a work in progress aimed at nerfing circuits for the sake of what's right.

## Why It's Good For The Game
I shouldn't need to explain why circuits are OP.

### CODE REVIEW

**Comment by ghost** [comment]
yeah but then an antag can insta-dismember a guy with a simple flashlight circuit.

**Comment by WarRage333** [comment]
I like this. Just like amari said make it do no damage on destruction.

**Comment by yoyobatty** [comment]
It just calls qdel and creates sparks, no explosion

**Comment by ghost** [comment]
Still don't like this.

**Comment by mikolaj007** [comment]
explosion size based on complexity,size,whatever

**Comment by ghost** [comment]
this'll encoruage people to destroy/unscrew the console

**Comment by Carbonhell** [comment]
I agree with steamport. You said the issues with circuits are:
"Circuits can easily be used to mimick or surpass traitor items and require little to no resources and time to accomplish"
"Grenades are obselete, you can still use it to dupe chems automatically"
"They are easily abused to cause insanely easy suicide bots"
"Tcomm blockers"

I replied to you:
1)mimic traitor items?? Can you be more specific so i can try to help finding a good solution?
2)If you can still dupe chems, then your fix did not work, not circuits' fault.
3)Suicide bots? Again, be more descriptive, i already fixed the locomotion issue where drones went insanely fast
4)Turn a boolean var from on to off, so people who wanna use those circuits must go to tcomms to enable this usage.

This idea is shit, as i already said. It won't fix anything. -1

**Comment by yoyobatty** [comment]
Okay so your reply for 1 and 3 are basically demonstrating your lack of understanding of how circuits work. People can easily make bombs that when you scan someone, it follows them and you can also make wallmount bombs which is functional equivalent to x4. As for option 2, it also shows that you don't know the diff between the way beakers scooping chems and reagent circuit sucking up chems work. Beakers only get 5% of the reagents on the floor, circuits take all of them. The issue with duping via making frozen ingots is still an issue iirc.

**Comment by Carbonhell** [comment]
"People can easily make bombs that when you scan someone, it follows them and you can also make wallmount bombs which is functional equivalent to x4"
Again, i told you drones being insanely fast has been fixed. You can make a kamikaze drone as you said, but it is really slow. You have to stand still for quite a while to get caught.
Regarding wall mount bombs, what was the cause of the explosion? Reagents or atmos? If reagents were used, then you can achieve the same without circuits. If atmos, then yeah, those are the newest circuits and may still need tweaking. 
"Beakers only get 5% of the reagents on the floor, circuits take all of them. "
This is stupid. Why the fuck is this coded like this. The problem is that chem piles generate chems out of thin air, again, not circuit's fault...
Still a shit idea.

**Pull request closed without merging**
