### PR TITLE
Revert "Y E E T"

### PR DESCRIPTION
**Pull request by ghost**
Reverts HippieStation/HippieStation#12413

### CODE REVIEW

**Comment by Punkinguy** [comment]
+1

**Comment by karmaisblackandbluepilled** [comment]
what does this do

**Comment by mkikt4743** [comment]
why revert it, seems fine, works good, I can name my shotgun boom stick -1

**Review by Neotwr — CHANGES_REQUESTED** [review]
update your PR's body using the appropriate template explaining Why It's Good For The Game

**Pull request closed without merging**
