### PR TITLE
Clown's angry_hobo_swep

### PR DESCRIPTION
**Pull request by carlopault**
image

## Changelog
:cl:
add: The clown's toy crate now comes with an angry_hobo_swep that can be equiped on your feet or head. It has special screams. Sprited by Crunion (Shazbot). Inspired by https://steamcommunity.com/sharedfiles/filedetails/?id=158061274&searchtext=angry+hobo+swep
/:cl:

## About The Pull Request
No help from Neo, unusual.

## Why It's Good For The Game
Clown buffed again, mime left in the dark as usual.

### CODE REVIEW

**Comment by MrEpicSax** [comment]
+1, thanks Crunion

**Comment by neetdev** [comment]
+1

**Review by yoyobatty — APPROVED** [review]
I assume it works?

**Comment by OK-Computer-OK** [comment]
+1 I like clown stuff

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
