### PR TITLE
Adds embed chance to forged weaponry

### PR DESCRIPTION
**Pull request by Toxici11i**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Adds embed chance for forged weaponry
/:cl:

## About The Pull Request
 Adds embed chance for forged weaponry because this should have been considered originally.
30% for a dagger, 10% for a sword, 1% chance for a mace, 5% for a greatsword.

## Why It's Good For The Game
Forged weaponry currently has a 0% chance to embed, no matter the stats. This adds embed chance, meaning that thrown forged weaponry will behave in a more "realistic" manner.

### CODE REVIEW

**Comment by Toxici11i** [comment]
ill probably make a later PR that somehow factors in their sharpness to the embed chance, but I think that would be too powergame even for hippie (durr cringe radium warhammer with 20% embed chance) or something like that

**Comment by TrickyDickRichard** [comment]
it would make sense that a knife doesnt just bounce of off people when thrown sometimes

**Comment by diegoxt45** [comment]
sure? +1

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by Dystarra** [comment]
+1

I don't really understand why this wasn't a default thing to begin with. This really seems like something that should've even have to be checked.

**Review by yoyobatty — APPROVED** [review]

**Comment by cris5311** [comment]
+1
Does the chem still have an effect when the knife is ebeded? e.g. leaching or rads from uranium

**Comment by Toxici11i** [comment]
I got a notification about somebody commenting about over time effects, or AOE effects. It will NOT apply a constant amount of chem to their bloodstream, but effects like rads/lighting etc will be applied as they normally would.

I ((might)) make it so in a future PR very small amounts of the reagent are transferred to the object it is embedded in.

**Pull request merged**
