### PR TITLE
Fixes war op pop limit.

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: GuyonBroadway
fix: Nuke ops can now declare war at any time for a scaling amount of tc
/:cl:

[why]: John Ported the change when tg refactored antags into a module but forgot to set the pop limit.

### CODE REVIEW

**Comment by Pyko1** [comment]
Sounds nice.

Even tho, how many TC does the lone OP get on the minimum player amount for that mode?

**Comment by GuyonBroadway** [comment]
Well its 6tc per player based on what John set it to. I just disabled the player check so it works again like we used to have.

**Comment by ghost** [comment]
noice

**Review by JohnGinnane — APPROVED** [review]
my bad

**Pull request merged**
