### PR TITLE
Old DMAPI was used, now the correct one is used

### PR DESCRIPTION
**Pull request by Carbonhell**
We use tgs 4.0, not 3.0 ffs

### CODE REVIEW

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: c7d6d37d87b1b2330c111237f1fd9fc818059036
Pull Request: 5f06997919f7822e571d8e1e8490734059bd9d99
Server: ef86ca96796b68614221f9df6598ea4e77dc3f6b

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 0a67a687965fba62f35c06231ed718ba0d31b70b
Pull Request: 5f06997919f7822e571d8e1e8490734059bd9d99
Server: 15918a6e72a74a55f63f06eeb315717a007963be

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 0c237a34ba86826e4a1365e34b536e6212e15ff3
Pull Request: 5f06997919f7822e571d8e1e8490734059bd9d99
Server: 9a44baaae7a31428dbec15fd4ee8c0e17aa1d28c

**Comment by Carbonhell** [comment]
Works, merging

**Comment by ghost** [comment]
#### Test Merge Removed

**Pull request merged**
