### PR TITLE
[MIRROR] Adds new disabler sprites

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42977
----------------------------
:cl:
add: Disablers now have a new sprite and now can attach flashlights.
/:cl:

Whether or not we remove tasers, couldn't hurt to have a new disabler sprite.

Updated Image:
image

Sprite ported from Bay. Credit to the original creator + WJ for edits.

### CODE REVIEW

**Comment by Jujumatic** [comment]
This will need head input

**Comment by Manly-Dwarf** [comment]
Note that this PR is being done because /tg/ actually removed tasers.
That being said just fucking kill me right now with that sprite

**Comment by ghost** [comment]
@Manly-Dwarf probs better than the current disabler sprite

**Comment by Jujumatic** [comment]
do we keep this or no? headmins?

**Comment by Manly-Dwarf** [comment]
probably not

**Comment by funkynuggets** [comment]
ew wtf that's fugly as shit jesus christ

**Comment by funkynuggets** [comment]
we're supposed to be space mall cops not edgy tactical gamers

**Comment by TheMeatGod** [comment]
-1 gay

**Comment by earthmoonjune** [comment]
-1

**Comment by yoyobatty** [comment]
Modularise out.

**Comment by mikolaj007** [comment]
+1, i prefer this one over the one we have

**Comment by Majick1** [comment]
-1 slap a razer logo on that ebic gamer disabler too

**Review by yoyobatty — APPROVED** [review]

**Pull request closed without merging**
