### PR TITLE
Adds meeseeks box as a scientist traitor item

### PR DESCRIPTION
**Pull request by ghost**
:cl: Thefastfoodguy
add: Adds meeseeks box as a scientist traitor item for 18 TC
/:cl:

### CODE REVIEW

**Comment by KayeArray** [comment]
does this have unlimited uses?

**Comment by ghost** [comment]
Amazing

**Comment by tortellinitony** [comment]
I think it needs more testing before we implement it somehow. There are still a few tweaks I'd like to work out

**Comment by mlgdatboi** [comment]
definetly not op

**Comment by mlgdatboi** [comment]
its the same of having a golem

**Pull request closed without merging**
