### PR TITLE
[MIRROR] Ash Drake Combat Buff

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/40355
--------------------
:cl: Whoneedspacee
add: new arena attack where ash drake summons lava around you
del: removed old swooping above you, instead flies above you instantly
balance: ash drake now spawns temporary lava pools instead of meteors falling down
balance: ash drake takes twice as long to swoop down now that he instantly goes above you
balance: ash drake now moves twice as fast
balance: increases the odds of lava spawns in the lava pool attack
balance: increases fire line damage and decreases lava attacks direct damage
tweak: ash drake fire now shoots in the direction of the target
tweak: changes times of certain animations
tweak: changes sounds of meteor falling to lava creation
fix: a bug where ash drakes attacks did not damage mechs
imageadd: changes meteor icon to lava creation animation from lava staff
/:cl:

[why]: Ash drake is one of the easiest megafauna despite giving fairly better loot than others like legion. Also he's a fairly boring boss to fight since he spends most of his time in the air with attacks that can't really hurt you ever as long as you keep moving. I did this to make his fight more fun and less one dimensional.

before - https://youtu.be/SjEJ5A_3-pI?t=14m50s

after - https://www.youtube.com/watch?v=jqJM3xySxBg&feature=youtu.be

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Balance change, needs input IMO.

**Comment by Eagle-Eyess** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Comment by Carbonhell** [comment]
Didn't even know ash drake was a megafauna and not a normal mob lmao, +1

**Comment by DaydreamPuppeh** [comment]
-1 until we fix lag. He would become impossible with the current lag.

**Comment by Maroonenahmoron** [comment]
1+, only thing I would change is a little more delay on each of the fire prison's attacks

**Review by GuyonBroadway — APPROVED** [review]

**Pull request merged**
