### PR TITLE
Reduces Predator cost to 2 points

### PR DESCRIPTION
**Pull request by ghost**
so the brazillian will shut up

:cl:
fix: Predator now costs 2 points.
/:cl:

it's labeled as a fix because I never meant it to be 5 points -- i just copy/pasted and didn't bother changing the point amount

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
hahahahahahahah

**Comment by diegoxt45** [comment]
why don't you actually bother and see which other powers are overcosted as well you idiot

**Comment by diegoxt45** [comment]
WHY THE FUCK DOES GRAVITY COST 4 POINTS

**Comment by diegoxt45** [comment]
SCOUT COSTS 3 FUCKING POINTS????!!!!!

**Comment by Manly-Dwarf** [comment]
HAHAHAHAHAHAHAHAH

**Comment by Manly-Dwarf** [comment]
+1

**Comment by ghost** [comment]
yeah sure +1 might as well merge

**Pull request merged**
