### PR TITLE
513 stuff

### PR DESCRIPTION
**Pull request by ghost**
* Replaced all `lentext` calls with `length`
* Travis now builds against 513.1496

### CODE REVIEW

**Comment by yoyobatty** [comment]
Fix the lints

**Comment by ghost** [comment]
how about we like, not touch the linter rn, lol

**Comment by yoyobatty** [comment]
Does this break any of the items you've edited? I don't want another /tg/ mirror breaks the code...

**Comment by ghost** [comment]
@yoyobatty it ain't my fault if the original coders were dumb

shouldn't break anything, i checked all the original parent calls compared to the calls

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
