### PR TITLE
Makes mutations almost guaranteed to manifest

### PR DESCRIPTION
**Pull request by Arzion5**
:cl:
tweak: Mutations now have a 99% chance of appearing when you apply a Structure Enzyme buffer to someone via Genetics.
/:cl:

Would be fun, and it avoids having to blast people repeatedly with radiation from the SE buffer applying until they get the powers. I am aware that this is a possibly controversial PR, but I would like to see what the community thinks about this.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
wew lad this makes genetics really really overpowered. How does tgcode handle mutations now? Can I build up mutations like before (find xray, give to self, never lose, find next mutation, etc) or do they all need to trigger at the same injection?

**Comment by Arzion5** [comment]
Injections are temporary but guaranteed, which is useful for finding out the effects of a block. Scanner SE modification, however, is permanent. A power block is not active for as long as the threshold for that particular block is not achieved.

**Comment by tortellinitony** [comment]
hell no

**Review by ghost — DISMISSED** [review]
Code is fine, even though i'd very much like you get rid of the spacing between the /datum line and get_chance

**Review by KayeArray — CHANGES_REQUESTED** [review]
This spacing is horrible

**Comment by WarRage333** [comment]
With two geneticists its really really easy to manifest powers, alone a bit harder if you get unlucky.

I think its fine as it is.

**Comment by dreamcrab** [comment]
i dont believe this is necessary either tbh

**Review by ghost — DISMISSED** [review]
Ok it's fine now

**Comment by KayeArray** [comment]
meh it's controversial so -1

**Comment by 2Dollarbill** [comment]
I'd rather not buff genetics to be gorilla station 13 again, this is a bit too strong for genetics. Having the powers manifest easily is something I'd like to push forward but this? Nah, too much. -1

**Comment by ghost** [comment]
Your PR needs to be updated to reflect the current state of the master branch, please update your PR and either (re)open it, or ask a maintainer to (re)open it.

**Pull request closed without merging**
