### PR TITLE
new sprite for makeshift laser rifle thanks gorram_swangs  #12421

### PR DESCRIPTION
**Pull request by ghost**
does  #12421
## Changelog
:cl: Gorram_Swangs
imageadd: added new sprite for makeshift laser rifle
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
+1

**Comment by karmaisblackandbluepilled** [comment]
post an image of it 4head

**Comment by ghost** [comment]
image

**Comment by Manly-Dwarf** [comment]
antman

**Comment by karmaisblackandbluepilled** [comment]
-1, i liked the shitty wire version more

**Comment by Manly-Dwarf** [comment]
horrible taste

**Comment by diegoxt45** [comment]
can we get a comparison?

**Comment by diegoxt45** [comment]
if the image gmail sent IS the comparison  then they both look awful

**Comment by ghost** [comment]
ok zoomer

**Comment by TrickyDickRichard** [comment]
laser - Copy
this is the new one vs the old one

**Review by Manly-Dwarf — APPROVED** [review]
no code, no problem

**Comment by TrickyDickRichard** [comment]
merge :)

**Comment by diegoxt45** [comment]
ew the one new one looks terrible

**Comment by TrickyDickRichard** [comment]
you dont even play on the server anymore retard

**Comment by TrickyDickRichard** [comment]
+1 epic

**Pull request merged**
