### PR TITLE
More tgui next stuff

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/tgstation/tgstation/pull/47929
https://github.com/tgstation/tgstation/pull/47937
https://github.com/tgstation/tgstation/pull/47915

wpwC68GCF3

### CODE REVIEW

**Comment by yoyobatty** [comment]
At least give credit to the original pr and provide a description

**Comment by ghost** [comment]
@yoyobatty literally look at the commits, but ok

**Comment by yoyobatty** [comment]
No designer is going to look at them. That's like saying read someone's vin if you want to find out what car they drive.

**Comment by ghost** [comment]
ok.

here's the new stuff:
 - nuke tgui-next
 - mech bay power console tgui-next
 - implanter chair tgui-next
 - keycard auth tgui-next

**Comment by yoyobatty** [comment]
Test each one and make sure you can fully use the interface before I merge.

**Comment by ghost** [comment]
@yoyobatty Yep, they all work.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
