### PR TITLE
Selfchanging assemblies

### PR DESCRIPTION
**Pull request by Shdorsh**
[Changelogs]: # Adds  3 new circuits: one that lets you self rename your assembly, one that lets you change the description of the assembly to anything you put into the circuit and one that lets you change the color of your assembly. The assembly color is unlimited.

:cl: Shdorsh
add: renaming/redescribing/repainting circuit
/:cl:

[why]: More assembly functions, more stuff for people to toy around with. Now, don't go telling me that changing an assembly's color would be too unbalanced, especially those people who commented a few detailer color options out.

Edit: Before I forget: tested and working.

### CODE REVIEW

**Comment by Eagle-Eyess** [comment]
+1

**Comment by ghost** [comment]
awesome

**Comment by Hate9** [comment]
Hell yeah

**Comment by Hate9** [comment]
Ok, I like this, but it'd be really nice to be able to get the current color, name, and description, as well as setting them.

**Comment by Carbonhell** [comment]
Sure +1

**Comment by Shdorsh** [comment]
oh, you want to be able to get the current settings? sure, can do, I'll just un-ready this quickly

**Comment by Shdorsh** [comment]
Need to put this down for the upcoming circuit modularization

**Comment by Hate9** [comment]
@Shdorsh When is this getting picked up again? I was really looking forward to it.

**Comment by Shdorsh** [comment]
When university stops killing me with assignments. I'm literally drowning in it and some people in my group work are truthfully on strike due to the terrible planning of courses from our faculty, refusing to pick up their part. Means more work for me and a few more sleepless nights, nibbling away at my sanity.

**Comment by DaydreamPuppeh** [comment]
+1 I can't figure out circuits, but this seems awesome

**Comment by BlueNothing** [comment]
I have time, maybe I can look into porting it for you? I'll need some advice on the general sort of ways things would change due to the modularization, though, probably.

**Comment by Shdorsh** [comment]
Starting this weekend, I'll be back, get ready. I hope I didn't miss much in terms of new circuitry code.

**Pull request closed without merging**
