### PR TITLE
[MIRROR] Removes smugglers satchels

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42166
----------------------------
:cl: 
del: Smuggler's satchels have been removed from the game.
del: The Miracle ruin has also been removed from the game, because it was disabled and it used Smuggler's satchels.
/:cl:

Closes https://github.com/tgstation/tgstation/pull/42170
This item is broken in principle. It enables people to have access to things they should never have been able to acquire within a round. This item is never used for anything interesting, it is just used to get wizard spellbooks and captain's spares and weapons at roundstart in any round with no effort required. It circumvents any IC obstacle by hiding it behind the "random chance" of the satchel spawning. It doesn't matter how many times this item is "fixed" or nerfed, being persistent is bad on principle.

### CODE REVIEW

**Comment by bardofrage** [comment]
no..

**Comment by mikolaj007** [comment]
-1
satchels are balanced enough, considering you cant put the item you took back into a satchel.

**Comment by Manly-Dwarf** [comment]
Fuck off, /tg/.

**Comment by xTrainx** [comment]
i ded

**Comment by Shdorsh** [comment]
what's that miracle ruin i never heard about?

**Comment by mikolaj007** [comment]
A fake space tile containing a plasma rifle i think

**Pull request closed without merging**
