### PR TITLE
slightly buffs floor tiles

### PR DESCRIPTION
**Pull request by SireTurret**
yeah

## Changelog
:cl: Turret
balance: Floor tiles now deal a slightly bit more damage.
/:cl:

## Why It's Good For The Game

YEAH

### CODE REVIEW

**Comment by KingTerrytheTerrible** [comment]
now they take someone from full to crit in 9 instead of 10 throws, good job

**Comment by mkikt4743** [comment]
+1

**Comment by ghost** [comment]
15 or no balls

**Comment by Manly-Dwarf** [comment]
i mean 8's a good start, i'm okay with this

**Comment by enthethan** [comment]
Should deal 15 when thrown

**Comment by yoyobatty** [comment]
Ugh, this is a pretty unnecessary feature creep that doesn't really offer anything useful to the game other than supplementing an already commonly found item (it's literally floor tiles) and making it slightly more annoying and useful.

**Comment by ghost** [comment]
pre rebase port though....

**Comment by ghost** [comment]
Add the old hippie port tag motherfucker. Throw meta is coming back to fuck this shitty stun meta in the ass.

**Comment by yoyobatty** [comment]
But it ISN'T a pre-rebase port: 
image

**Comment by ghost** [comment]
no it isnt it should be 15 dmg.  also,  thats the first rebase isnt it? i believe the original hippie code didnt have stamina damage percentages

**Comment by Manly-Dwarf** [comment]
I have access to extremely old, 2015 hippiecode
and surely enough, floortiles had a throwforce of 10.

**Comment by yoyobatty** [comment]
We shall call him lyin' turret.

**Comment by Manly-Dwarf** [comment]
oldcode

**Comment by Manly-Dwarf** [comment]
oldcode sure was something

**Comment by SireTurret** [comment]
it was 10?? what

**Comment by SireTurret** [comment]
maybe it became 10 like very lately and the rebase was coming already

**Comment by ghost** [comment]
15 dmg or bust. make fire extinguishers 15 too
toolboxes tooo

**Comment by MrEpicSax** [comment]
Sounds dumb. Merge already.

**Review by AnthonyJNgo — APPROVED** [review]
Literally changing two values, not really anything to review here.

**Comment by AnthonyJNgo** [comment]
Oldcode port, let's goooooo +1

**Pull request merged**
