### PR TITLE
Visibility

### PR DESCRIPTION
**Pull request by ghost**
Look, I've been fucking with this for three hours. I absolutely cannot get this dumbshit ramadan stuff to get pushed seperately from my single alteration to world.dm. I've made a few branches, cloned the repo like 10 times. They're still there. I have no idea what to do. Can someone like shave that bit off? We need to try the visibility = 1. Someone showed me a more intricate fix from Artemis Station but it looked like their snowflake code, and this appeared to be what fixed it anyways. Pls help ok :D

### CODE REVIEW

**Comment by Uqualm** [comment]
Allahu akbar

**Comment by Uqualm** [comment]
This is the wrong github by the way.

**Comment by ghost** [comment]
Quarian, the ramadan is not supposed to be there. I intend to tweak Zeller's Congruence or something like it to make an algorithm to calculate both our new Ramadan Holiday and Easter more efficiently.

**Comment by dannno** [comment]
merge this

**Comment by SgtxRootbeer** [comment]
MERGE NAO

**Comment by dannno** [comment]
perfect

**Comment by Spankmaster1066** [comment]
Thank you for your support gentlemen.

**Comment by tortellinitony** [comment]
go away with your stupid ramadan that doesn't make sense

**Comment by Spankmaster1066** [comment]
Hey jackwagon # **_the point of this is to get the server back on the hub_**

**Comment by Pyko1** [comment]
I see this not getting denied by HA's, and go away is not a reason to close.

**Comment by ghost** [comment]
merge conflicts

**Comment by Spankmaster1066** [comment]
Can maintainers or w/e just cut my first two files off so it only edits world.dm?

**Comment by ghost** [comment]
No, fix it

**Review by ghost — APPROVED** [review]

**Review by tortellinitony — CHANGES_REQUESTED** [review]
Please refer to https://github.com/HippieStation/HippieStation/blob/master/.github/CONTRIBUTING.md#pull-request-process

This fails on several accounts.

**Comment by ghost** [comment]
oh wait this is the new repo, don't merge this

**Comment by Spankmaster1066** [comment]
I think Jamie just fixed the bool thing anyways, so this PR is now irrelevant. Ramadan is NOT ready for implementation, it's simply too powerful in its current form.

**Pull request closed without merging**
