### PR TITLE
new map: Hippie Land

### PR DESCRIPTION
**Pull request by ghost**
Untitled

### CODE REVIEW

**Comment by AnthonyJNgo** [comment]
Finally proper usage of PR draft.

**Comment by Timmeye** [comment]
epic, gamer.

**Comment by lunaman22** [comment]
+1 we need new maps

**Comment by ghost** [comment]
this'll probably take a few months since it's not my #1 priority

**Comment by Majick1** [comment]
Once the fusion engine is figured out and done we can just pass the file around to flesh out

**Comment by enthethan** [comment]
Bar with ragecage or yous gay lol

**Comment by ghost** [comment]
would like help with this as i'm a horrible mapper

**Comment by Majick1** [comment]
I can help some more, how far have you gotten

**Comment by ghost** [comment]
@Majick1 literally just the outline, the walls.

**Comment by Dinopeaks** [comment]
you need help i got time and am okay at maping

**Comment by ghost** [comment]
gladly accepting help

**Comment by Timmeye** [comment]
> gladly accepting help

I currently dont know how to map BUUUTTT I did make a mini station with its own air alarm and apc one round as a CE. Also I made submarines in barotrauma (a game like ss13).

**Comment by Majick1** [comment]
Maybe you could do some of the service departments to get some practice

**Comment by Timmeye** [comment]
> Maybe you could do some of the service departments to get some practice

So like how do I get the file to attempt to work on this map

**Comment by Majick1** [comment]
Go into files changed and grab the .dm file

**Comment by Timmeye** [comment]
Im new to GitHub which file and also how do I grab a file?

**Comment by Timmeye** [comment]
how do I grab the file?

**Comment by Timmeye** [comment]
I will try to help build the station if I have the file

**Comment by ghost** [comment]
We need maintenance, A LOT OF MAINTENANCE,

i mean there isn't a lot of maint corridors

**Comment by ghost** [comment]
how to get the file, for github noobs:

1. Files Changed tab
2. scroll down to HippieLand.dmm
3. Click the 3 dots, then View File
4. Click Raw
5. Ctrl+S, save hippieland.dmm somewhere in a copy of the Hippie repo

OR:

1. Click this for a download of this branch: https://github.com/HippieStation/HippieStation/archive/hippieland.zip

**Comment by Timmeye** [comment]
> how to get the file, for github noobs:
> 
> Files Changed tab
> scroll down to HippieLand.dmm
> Click the 3 dots, then View File
> Click Raw
> Ctrl+S, save hippieland.dmm somewhere in a copy of the Hippie repo
> 
> OR:
> 
> Click this for a download of this branch: https://github.com/HippieStation/HippieStation/archive/hippieland.zip

Thank you soo much, I will work on it tomorrow!

**Comment by Timmeye** [comment]
image
worked on atmos a little bit
Also I managed to fit the super matter in.
image

**Comment by Timmeye** [comment]
I dont wanna work on it anymore. How do I give you the file? it says I cant put it in.

**Comment by ghost** [comment]
just upload it anywhere. idc where. any website works.

**Comment by Timmeye** [comment]
I made a repository https://github.com/Timmeye/hippieland- but the map is in text form, can you convert it?

**Comment by Majick1** [comment]
Do you not have discord at all, was trying to avoid this conversation cluttering up the pr

**Comment by Timmeye** [comment]
I don't think anyone can finish this, it just too big and hippie usually isn't high pop or anything.

**Pull request closed without merging**
