### PR TITLE
[MIRROR] .38 no longer insta stuns

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/39891
--------------------
>inb4 limited ammo 

yeah its not like the seclathe prints the ammo and every detective and their mother have at least 7 speedloarders in their bag
>inb4 det nerf 

yeah det isnt supposed to be the elite officer which dies to a stun pod and then traitor LB kills everyone with a .38
>inb4 i ded

not an argument yet i didnt die from .38 
>inb4 useless now

1 shot slows down 2 shots and he is down 3 shots stuns an armored target maybe i should also lower the stamina dmg

### CODE REVIEW

**Comment by ghost** [comment]
pls nerf im ded

**Comment by Carbonhell** [comment]
@guyonbroadway

**Comment by HippieBartels** [comment]
lol stupid grudgecode

**Comment by GuyonBroadway** [comment]
Considering we overrided this elsewhere it might not do the anything whatsoever. Worst case scenario it just ups the damage to 25 which I can nerf.

**Comment by Manly-Dwarf** [comment]
Redundant PR. Also stupid /tg/ grudgecode.

**Review by yoyobatty — APPROVED** [review]

**Comment by yoyobatty** [comment]
I assume we've corrected the cancer?

**Comment by GuyonBroadway** [comment]
If anything that revolver is now les cancer from a tg perspective as it no longer stuns at all. It jsut does a flat 25 damage which is a little retarded but I've changed it to our revolver now.

**Comment by ghost** [comment]
-1

**Comment by GuyonBroadway** [comment]
What I mean to say is. This is ready, the th changes do not affect us.

**Review by Carbonhell — APPROVED** [review]

**Comment by Carbonhell** [comment]
Remember to strip stuff you remove from the changelog aye. I did it myself now

**Pull request merged**
