### PR TITLE
Voice of God: Fart & Scream Edition

### PR DESCRIPTION
**Pull request by ProtozoaPrime**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Added fart command to voice of god
add: Added scream command to voice of god
/:cl:

## About The Pull Request
Adds a fart command and a scream command to the Voice of God, it's an old-ish change I saw laying around that never quite got merged. I went the route of just putting it in TG code with the regular hippie comments, because dissecting these commands into the Hippie folder is too much work than what the change is worth. [Relevant Issue](https://github.com/HippieStation/HippieStation/issues/12230)

## Why It's Good For The Game
It fits the overall theme and attitude of the server, adds some fun times for the rare occasion people actually get this item, and is overall just pretty epic.

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
Who're you on the discord?
Also +1

**Comment by ProtozoaPrime** [comment]
I’m Protozoa#9730 on the discord

**Comment by AnthonyJNgo** [comment]
Funny addition +3

**Comment by MrEpicSax** [comment]
+1 I will make you all shid your pants

**Comment by carlopault** [comment]
+1

**Review by AnthonyJNgo — APPROVED** [review]
Looks good to me, good submission.

**Pull request merged**
