### PR TITLE
Removes football

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
del: Goodbye football kit, you won't be missed
/:cl:

I'm not allowed to touch most of the shitty uplink items, but I should be able to kill my own

### CODE REVIEW

**Review by KayeArray — APPROVED** [review]

**Comment by ghost** [comment]
uh sure but uh, what do you perceive the problems to be?

**Comment by tortellinitony** [comment]
it doesn't work really, i've seen it glitch people through walls

**Comment by tortellinitony** [comment]
I'm not fixing it

**Comment by Arzion5** [comment]
"You won't be missed"
Damn you, I already miss it

**Comment by tortellinitony** [comment]
I can pull up statistics to show that nobody uses it

**Comment by Arzion5** [comment]
I already miss it

**Review by j-mie — APPROVED** [review]

**Pull request merged**
