### PR TITLE
Reverted /tg/'s double space damage

### PR DESCRIPTION
**Pull request by JohnGinnane**
:cl: JohnGinnane
balance: Damage from low pressure is back to normal
/:cl:

Revert of #475. Modularised so if we DO decided to change it, it's easy

### CODE REVIEW

**Comment by Cyberboss** [comment]
I think just changing the /tg/ define is enough to prevent conflicts since you already merged it...

**Comment by dreamcrab** [comment]
yes very

**Comment by dreamcrab** [comment]
+9

**Comment by ghost** [comment]
ye

**Review by KayeArray — DISMISSED** [review]
Just change the /tg/ define, it will create far less conflicts than this

**Comment by KayeArray** [comment]
+1

**Review by KayeArray — APPROVED** [review]

**Comment by Pyko1** [comment]
should had waited for 24 hours really.

I mean it was working as intended and we gave it like 1 round?

**Pull request merged**
