### PR TITLE
[MIRROR] Makes stun baton two words

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43126
----------------------------

## About The Pull Request
Makes stun baton two words

## Why It's Good For The Game
I dunno, but this has bugged me for awhile

## Changelog
:cl: cacogen
spellcheck: Makes stun baton two words
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Heresy. Revert this PR.

**Comment by yoyobatty** [comment]
Causes a bug, wait for the fix.

**Comment by funkynuggets** [comment]
retard

**Comment by earthmoonjune** [comment]
delete this

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
