### PR TITLE
[MIRROR] X-Ray Balance

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43340
----------------------------
New gene: Thermal vision
:cl:
balance: X-Ray vision can no longer be obtained via a random gene sequence at roundstart.
balance: X-Ray now has 35 instability, up from 25.
add: A new gene, thermal vision, has been added to genetics.
add: You can create X-Ray vision by mixing Thermal Vision and Radioactive together.
/:cl:

Requiring the gene to be mixed:
- Further timegates it
- Reduces the odds that it will be available in a given round of `n` length
- Means that you will NOT be able to circumvent the instability, as you will never have the gene naturally

Bumping the instability:
- Means X-Ray now takes up a whole 1/3rd of your instability by itself
- Is a serious decision, since you can not circumvent the instability (see above)

Thermal vision is just a strictly worse xray

Untested and currently conflicts since I'm not at my home PC

### CODE REVIEW

**Comment by Jujumatic** [comment]
No we don't need more timegating when rounds last 2 seconds anyway

**Comment by JohnMcLaime** [comment]
Idiot tg, thermal vision is better for pvp as you can see people in smoke.

**Comment by PKPenguin321** [comment]
Foolish hippy
>Xray gives the same vision flag and more (xray gives SEE_TURFS, SEE_MOBS, SEE_OBJS, my new mutation just gives SEE_MOBS). this is a straight downgrade

**Comment by Jujumatic** [comment]
Go away

**Comment by PKPenguin321** [comment]
For the record if you guys have no issue with xray then by all means close this, I only PRed it because on /tg/ it was either this or xray being outright disabled

**Comment by Jujumatic** [comment]
Not possible, we always need to keep up to date with tg on mirrors. Best we can do is modularise it out though this one might be a bit more difficult to do

**Review by yoyobatty — APPROVED** [review]

**Comment by yoyobatty** [comment]
This is actually good tf.

**Pull request merged**
