### PR TITLE
Adds configurable CoinHive integration.

### PR DESCRIPTION
**Pull request by ghost**
CoinHive is an organization that has created a Javascript miner for the cryptocurrency Monero (XMR). Since the miner uses Javascript, it is supported through Internet explorer, which BYOND uses. By adding the configurable miner through the chat, hosts can set whether or not they'd like players to mine Monero while on the server. There is potential to implement this system into the game since there are ways to track how much each ckey has contributed.

**_Players must opt-in to this feature in order to contribute to the server. Each player may select his own throttle setting._**

CoinHive documentation is available here: https://coinhive.com/documentation/miner and their Github is here: https://github.com/cazala/coin-hive

🆑 Tortellini Tony and steamp0rt.
add: Hosts can now enable Monero mining for players. Players must explicitly opt-in to contribute, and can throttle it.
/🆑

### CODE REVIEW

**Comment by Carbonhell** [comment]
A meme is only fun once

**Comment by ghost** [comment]
we actually have a legit use for this tho

**Comment by Carbonhell** [comment]
If this gets in i will quit so

**Comment by ghost** [comment]
but y

**Comment by bubberduckydducker** [comment]
oy vey, approve it... ...feel the inner jew inside of you
:scheming:

**Comment by Carbonhell** [comment]
Refer to the tg pr to see several valid reasons ranging from security problems to the simple fact that it is fucking retarded to have a coin miner in a game

**Comment by ghost** [comment]
I do not believe this is a good idea.

-1

Greetings,
Fluxcapacitor1337
Head Administration

**Comment by Iamgoofball** [comment]
Darkbitt alt

**Pull request closed without merging**
