### PR TITLE
Can obtain Xenomorph Egg Sacks and Hive node with RND

### PR DESCRIPTION
**Pull request by mlgdatboi**
/:cl:
add:Obtainable Xenomorph organs via RND
/:cl:

This will allow players to get alien organs via RND without being too overpowered and requires you to find abductor items or Xenomorph organs to make more a shortcut to get this would be to deconstruct a drone shell and then any abductor tool go to science chem for plasma and a bluespace crystal then put it all in the RND machine you should be able to make two organs.

### CODE REVIEW

**Comment by mlgdatboi** [comment]
Requires some nerfing

**Comment by ghost** [comment]
no plz no

**Comment by GuyonBroadway** [comment]
Ok it seems you copied the whole R&D file, you didn't need to, you just needed to make a file with the same name in our folder and only put the datums you wanted to add and byond will sort it out for you.

**Comment by mlgdatboi** [comment]
@MoreRobustThanYou Lavaland also spawns about 8 aliens and eggs its not overpowerd at all

**Comment by mlgdatboi** [comment]
@GuyonBroadway Thank you for the response but im still confused people tell me that and when i delete it all they yell at me

**Comment by GuyonBroadway** [comment]
Ok so, R&D designs use datums, each individual design could be put anywhere in the code and it would work in the protolathe, we mimic the file paths in the hippie folder for sake of ease, all YOU needed to do was go to the existing medical_designs file that we put there and add the designs for the alien organs. 

Everything else is unnecessary, byond is a rather modular object oriented language, you can put lots of different objects anywhere in the code and they all work, no need to re-add things for the most part.

**Comment by ghost** [comment]
no, this is silly, giving people antag powers through non antag means is powercreep in definition

that being said, all you would have to do is instead of mirroring the entire file:
```
/datum/design/synth_xeno_sack
			name = "Synthetic Egg Sack"
			desc = "A synthetic xenomorph egg sack requires a hive node and a plasma vessel to work to work."
			id = "synth_egg_sack"
			build_type = PROTOLATHE
			req_tech = list("abductor" = 3, "biotech" = 2)
			materials = list(MAT_PLASMA = 1500, MAT_GLASS = 2000)
			build_path = /obj/item/organ/alien/eggsac
			category = list("Organs")

/datum/design/synth_hive_node
			name = "Synthetic Hive Node"
			desc = "A synthetic xenomorph hive node allows you to talk to aliens and allows you to use an egg sack."
			id = "synth_hive_node"
			build_type = PROTOLATHE
			req_tech = list("abductor" = 3, "biotech" = 2)
			materials = list(MAT_PLASMA = 2000, MAT_GLASS = 2300, MAT_BLUESPACE = 100)
			build_path = /obj/item/organ/alien/hivenode
			category = list("Organs")
```

put this code you wrote in the medical designs file

if the file is checked, it will just add these datums as new ones to add into science

**Comment by ghost** [comment]
your code is also too far indented, it should be 1 indent after the /datum/research/myscience thing

byond needs indentation or it gets confused

**Comment by mlgdatboi** [comment]
@McBawbaggings This requires shaft miners to actually do their work and you can already obtain xenos and xeno organs via lavaland this is actually harder to obtain

**Pull request closed without merging**
