### PR TITLE
Add Stand Arrow to Summon magic

### PR DESCRIPTION
**Pull request by ghost**
Summon magic is cancer, why not make it less terrible?

:cl:
add: Stand arrow can now appear in Summon Magic
/:cl:

### CODE REVIEW

**Comment by notoriousBIGGIOS** [comment]
+1 hue

**Comment by Manly-Dwarf** [comment]
-1 nue

**Comment by karmaisblackandbluepilled** [comment]
+1 seems good

**Comment by diegoxt45** [comment]
+1 make hibiki mad

**Comment by diegoxt45** [comment]
just merge this already

**Pull request merged**
