### PR TITLE
Kills HippieStation

### PR DESCRIPTION
**Pull request by ghost**
Goodbye vamps, goodbye slings, goodbye gremlins, goodbye oldgrab, goodbye trayshields, goodbye makeshift armor, goodbye shanks.

You guys don't deserve my contributions, with a retarded host and biased headmins.

I will close this PR provided that you promise from now on, _**ALL PRS WILL BE MERGED FAIRLY, AND ACCORDING TO THE STANDARD**_

### CODE REVIEW

**Comment by SplergeBucket** [comment]
no

**Comment by dreamcrab** [comment]
lmao

**Comment by SplergeBucket** [comment]
lol

**Comment by dreamcrab** [comment]
+1

**Comment by ghost** [comment]
what did he mean by this?

**Comment by SplergeBucket** [comment]
BEG US FOR MERCY

**Comment by Blute1** [comment]
images

**Comment by Iamgoofball** [comment]
lmao do you not know how the license works

**Comment by Blute1** [comment]
what are you talking about goof are you ok

**Comment by Iamgoofball** [comment]
mrty doesnt understand this isnt his code anymore

**Comment by Blute1** [comment]
it never was his code

**Pull request closed without merging**
