### PR TITLE
Fucking doubles the toxins bomb pointcap

### PR DESCRIPTION
**Pull request by Mastergodown**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Mastergodown

Bal: Doubles the pointcap. I dont see why not.

/:cl:

## About The Pull Request
Doubles the pointcap. Toxins mains should be rewarded for not dying for 10 minutes and making a nuclear bomb.

## Why It's Good For The Game
Hail the toxin mains

### CODE REVIEW

**Comment by Punkinguy** [comment]
+1, we can always reverse shit if it goes nuclear

**Comment by Mastergodown** [comment]
> +1, we can always reverse shit if it goes nuclear

It doesnt increase the bomb cap, it increases the toxins pointcap. When you explode the thing at the test site, points are capped at 50000 currently. So if you make a maxcap that wouldve selled at over 50000 points, it would only give you 50k. This makes it so it is doubled, therefore the you can get 100k from toxins instead of just 50k.

In other words, it doesnt increase how big the bomb can be, it just increases the amount of points you can get from it.

**Comment by Mastergodown** [comment]
fuck i fucked it up

**Comment by Mastergodown** [comment]
Ok I fucked it up, time to do over

**Pull request closed without merging**
