### PR TITLE
Stops idiotic wizards with polymorph staff from extending the round

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: Polymorph aliens will no longer prevent the round from ending.
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Wizard rounds don't end automatically when they die. They sometimes attempt for mulligan.

**Comment by sagaty13** [comment]
speedmerge

**Comment by enthethan** [comment]
+1 merge fast please

**Comment by AnthonyJNgo** [comment]
Big +1

**Review by Manly-Dwarf — DISMISSED** [review]
test

**Comment by ExpAntique** [comment]
+1

**Review by AnthonyJNgo — APPROVED** [review]
lgtm

**Pull request merged**
