### PR TITLE
[MIRROR] Adjusts vehicles to new movement delay

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/42273
----------------------------
:cl: SuicidalPickles
Fix: A few vehicles; secway, scooters/skateboards, and ATVs have been changed to the new movement delay speed.
/:cl:

at the moment they're all faster than the average spaceman's running speed.
fuck im terribad at this and accidentally made a new pr, meant to add these to the other one but whatever this works i guess

### CODE REVIEW

**Comment by k-k-karma** [comment]
fucking tgtards

**Review by yoyobatty — APPROVED** [review]
I thought this was the point but, okay.

**Comment by JessHorserage** [comment]
Did this fuck up speed potions?

**Comment by Jujumatic** [comment]
No, speed potions on vehicles got a huge nerf because it was impossible to catch an emagged sanicfast lawnmower annihilating the entire station

**Comment by JessHorserage** [comment]
Yeah, saw it.

**Pull request merged**
