### PR TITLE
Removes halloween races from roundstart

### PR DESCRIPTION
**Pull request by ghost**
:cl: McBawbaggings
del: Removed zombies, shadow people, spaceproof skeletons and cloth golems from roundstart selection during Halloween.
/:cl:

These races are not default and it's not good to have any roundstart race to be functionally different from the rest outside of AI laws and job roles. These races should never be considered as a sidegrade or upgrade from humans, but rather a stylish choice without them being heads. (I don't really object to head birds or skeletons but it's the norm for us)

### CODE REVIEW

**Comment by Spacedong** [comment]
what about the halloween event making people into them

**Comment by ghost** [comment]
-1

**Review by ghost — DISMISSED** [review]
PLZ NO

**Comment by KayeArray** [comment]
+1

**Comment by ghost** [comment]
Vampires and dullahans don't get black listed atm since they're not in our hippiestation.dmb at the moment and bantz advised to keep it like that.
If we enable them, same treatment should apply.

Spacedong:
https://github.com/tgstation/tgstation/pull/32087
"The Halloween main event no longer edits your race to zombie/skeleton (players get to pick from setup now)"

**Review by KayeArray — APPROVED** [review]
he tested it

**Pull request merged**
