### PR TITLE
 Moves all air supply pipes to piping layer 1

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: Moves air supply pipes to piping layer 1.
tweak: Remaps scrubbers and air supply pipes.
/:cl:

[why]: This needed to be done.

image

image

### CODE REVIEW

**Comment by yobob591** [comment]
NIGA +1

**Comment by bardofrage** [comment]
+1

**Comment by earthmoonjune** [comment]
+1

**Comment by Lxtoofonea** [comment]
+1

**Pull request merged**
