### PR TITLE
Mining Voucher In QM Locker

### LINKED ISSUE #9518: Mining Ticket in QM's and HoP's lockers
When I stopped playing, there used be two extra mining tickets in the QM's and the HoP's lockers. Now they're gone.
It's a shame, I really don't think there's anything to gain by removing them.

### PR DESCRIPTION
**Pull request by carlopault**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:Carlospaul
add: The quartermaster's locker now has a mining voucher within it. 
/:cl:

## About The Pull Request
Closes: https://github.com/HippieStation/HippieStation/issues/9518

## Why It's Good For The Game
Non-miners can raid QM's locker for the voucher to get decent start in mining.

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
+3

**Comment by cris5311** [comment]
+1

**Comment by mkikt4743** [comment]
+1

**Comment by MrEpicSax** [comment]
+1

**Comment by byandaccount** [comment]
+1 what if the qm want's to go mine? hell non-cargo staff could break into the locker and get a easy start in lavaland with it.

**Comment by AnthonyJNgo** [comment]
QM would spawn next to his locker so non-issue. The voucher is a really small buff anyways tbh, +3 harmless change really

**Review by AnthonyJNgo — APPROVED** [review]
lgtm

**Pull request merged**
