### PR TITLE
Bulk upstream April

### PR DESCRIPTION
**Pull request by JohnGinnane**
Everything works so far, but I will post daemon output

~~Also I can't remove items from butts just yet so I'm still trying to figure that out~~
I was able to get this sorted

A few PRs that make many many changes:
PR for the storage component: https://github.com/tgstation/tgstation/pull/36696
PR for /obj/item/device refactor: https://github.com/tgstation/tgstation/pull/37297
PR for uppercase slots: https://github.com/tgstation/tgstation/pull/37476
PR for renaming traits to quirks: https://github.com/tgstation/tgstation/pull/37646
PR for removal of stock market: https://github.com/tgstation/tgstation/pull/37414

compiling:
image

server output:
image

Output so far:
[server_log.txt](https://github.com/HippieStation/HippieStation/files/2019640/server_log.txt)

game:
image

### CODE REVIEW

**Comment by JohnGinnane** [comment]
I merged all of the tg commits before doing work on our code, so from commit "First Commit" (https://github.com/HippieStation/HippieStation/pull/7565/commits/dfce1888d20ce3ae44b686e59b71681ba4533357) onwards is our work

**Comment by Jujumatic** [comment]
oof it failed

**Comment by JohnGinnane** [comment]
yeah not sure why, it definitely compiles and runs. Still WIP though, and we can add recent merges that have gone in since

**Comment by Pyko1** [comment]
```
tgstation.mdme.dmb - 100 errors, 7 warnings (4/24/18 10:05 pm) (max count reached)
mv: cannot stat ‘tgstation.mdme.dmb’: No such file or directory
```

its using wrong .dme?

**Comment by Pyko1** [comment]
Should be fixed now. 
Also reverted readme, contributing and codeowners back to the hippie version.

**Comment by Pyko1** [comment]
oh yeah we need TGUI recompile on this too

**Comment by JohnGinnane** [comment]
Oh yeah good point

**Comment by GuyonBroadway** [comment]
We will rpobably need to re-fetch upstream commits and ocne thats done I can rebuilt tgui for you.

**Comment by JohnGinnane** [comment]
Butts are sorted, gonna pull latest commits

**Comment by GuyonBroadway** [comment]
And the award for best git comment taken out of context goes too...

**Comment by JohnGinnane** [comment]
Alright, that's the latest commits. Server starts but lots of errors. See OP for log

**Comment by JohnGinnane** [comment]
Okay, fixed a lot of those mapping errors

**Comment by JohnGinnane** [comment]
Okay, the game compiles and runs, there's one runtime to do with xeno butt's storage being changed, and I don't get why it's complaining. I would have expected the component to be initialized in time

Travis isn't happy but it might be related to this: https://github.com/tgstation/tgstation/pull/36858

**Comment by JohnGinnane** [comment]
@Chnkr https://travis-ci.org/HippieStation/HippieStation/jobs/372776908#L874 do we need to install this?

**Comment by JohnGinnane** [comment]
image

**Comment by JohnGinnane** [comment]
image

ah fuck

**Comment by Jujumatic** [comment]
awe fuck bye

**Comment by JohnGinnane** [comment]
I have updated the map to match ours, and then did the usual fixes (removed "device" and some old vars)

**Comment by GuyonBroadway** [comment]
Oh look map conflicts again.

**Comment by Dinopeaks** [comment]
just for you ;)

**Comment by JohnGinnane** [comment]
Updated upstream, I copied our map from repo and then removed stock exchange computers, See OP for server output

**Comment by JohnGinnane** [comment]
hm, probably shouldn't have taken our map from repo because I need to make fixed again, hold on

**Comment by JohnGinnane** [comment]
Okay, map is updated

**Comment by JohnGinnane** [comment]
okay it's complaining about a non-existant conflict ((

**Comment by GuyonBroadway** [comment]
closing this in favour of not fucked upstream

**Comment by JohnGinnane** [comment]
image

**Pull request closed without merging**
