### PR TITLE
[MIRROR] Disease antagonist

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35988
--------------------
:cl: 
add: Added a new mini antagonist, the sentient disease.
/:cl:

Closes #35954

Added a new mini antagonist, a disease that evolves new symptoms and powers. It gains points for infecting multiple people at the same time, and it can use those points to purchase symptoms. The overmind can jump between all infected hosts.

Right now the only non-symptom abilities are one to make the host cough, and one to make the host sneeze. The cough will try to infect people nearby the host, while the sneeze has a longer range, but can only infect people in front of the host. The cough and sneeze symptoms are different, can be purchased separately, and act like they do for regular diseases.

Evolution menu:
menu

Icons for the evolution menu, cough, and sneeze buttons:
buttons

Overmind and hud sprites:
hud

Roundend report:
report

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
That's actually pretty cool. We could make use of this

**Comment by Pyko1** [comment]
aww yis pandemic ss13 edition! TAKE THAT MADAGASCAR, NO US CLOSING PORTS NOW!

In before a random assistants sneezes in arrivals hallway, and the virologist bolts and emags all his airlocks.

**Comment by Pyko1** [comment]
https://github.com/HippieStation/HippieStation/blob/upstream-merge-35988/code/datums/diseases/_MobProcs.dm

looks like we actually have to do some work and account in our own changes.

**Comment by Pyko1** [comment]
now we wait

**Pull request merged**
