### PR TITLE
Create arithmetic

### PR DESCRIPTION
**Pull request by Shdorsh**
Adds a min and max circuit

[Changelogs]: # Added a min and a max circuit
:cl: Min and Max circuits
add: Added 2 circuits in arithmetic, notably min and max.
/:cl:

[why]: # This would have otherwise needed some massive circuiting to check for a max or a min in a circuit, which is a bit overkill for such a basic function.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Not a dm file.
Change this to lists.dm and make sure it's ticked in hippiestation.dmb

**Comment by Carbonhell** [comment]
Wasn't this done recently on tg?

**Comment by Carbonhell** [comment]
If your prs get merged on tg, they will be mirrored here too. Leave this open till then just in case tg denies it.

**Comment by ghost** [comment]
this file needs to be added to hippiestation.dmb
to do this, make sure the file you're adding has the tickbox checked on the left hand side of dream maker
next, force a compile and it should add the file to hippiestation.dmb
commit the updated version of hippiestation.dmb

**Comment by Carbonhell** [comment]
#8166

**Pull request closed without merging**
