### PR TITLE
Removes random roundstart hunger

### PR DESCRIPTION
**Pull request by ghost**
:cl:
balance: Hunger at roundstart is no longer random.
/:cl:

one spawn and im hungry

### CODE REVIEW

**Review by JohnGinnane — APPROVED** [review]
do we need head input

**Comment by Pyko1** [comment]
I actually kinda like the change as you used to be able to go average round with just a donut or 2 usually.
Now the chef at least has an excuse to live. So my opinion is -1 really.

**Comment by JohnGinnane** [comment]
Good point but do you think this will incentivise people to play chef? People can still raid vending machines

**Comment by Manly-Dwarf** [comment]
@Pyko1 Nobody eats the chef's food. They just eat the donuts, raid the vendors, or cook donk pockets.

The chef already has no incentive to do his job. He has no reason to be around.

**Comment by Pyko1** [comment]
yeah thats because hippie rounds are so short that that not even the crap food limits trigger. This at least makes him some what more usable, even still there are more than enough food around to grab to not slow down,

**Comment by Pyko1** [comment]
! mean you should easily survive to 1 hours at least with donut/donkpocket or even vendor food.
This change makes food at least take some part on our game play, and to be honest you should even need more really to make chef needed,

**Comment by Manly-Dwarf** [comment]
Hippie rounds are short and don't accommodate for certain /tg/ features? Might be a good idea to just remove them. _Oh wait_
Besides that, this doesn't change the chef's role. He never cooks food, the new cooking system sucks, and food is easily gained from vendors, donut boxes, or just donk pockets. You can still go entire rounds without having to ever check up in on hunger with the aforementioned items, and this PR was trying to "change" that.
All it proved to be was a nuisance. It doesn't add anything to the game, and the Chef runs off and dies every round or cooks pizza before getting bored.

**Comment by JohnGinnane** [comment]
Let's dispel the notion that our rounds are short. I've already pointed out that this isn't true. Depending on the time of day the round can range from 30 to 90 minutes so the argument "Hippie rounds are short" doesn't hold any water. See https://github.com/HippieStation/HippieStation/pull/5789#issuecomment-355950553 for average round for Nov 2017. It was 47 minutes

**Comment by JohnGinnane** [comment]
it's annoying to go hungry within minutes of starting but it sorta pushes for more chefs because otherwise they are redundant. Vending machines and donuts only provide a little nutriment so only buy a small amount of time

**Comment by Manly-Dwarf** [comment]
What the hell? No it doesn't. Eating a few donuts or a few packages of candy sends you on your way - with no problems. Just eat until you are "unwillingly" eating the candy.
Chef _never_ cooks food. A chef that actually sits around and makes food is about as rare as a Space Ninja.
Do you guys play even play the game?

**Comment by JohnGinnane** [comment]
image

(https://tools.hippiestation.com/stats/stats/jobs.php)

Chef is played as much as HoP and mime and I've definitely seen some of them cook food so please stop with the hyperbole

**Comment by Pyko1** [comment]
yeah but usually all the chef food is used by chef and one guy who just wants to eat everything.
And rest of the crew have just 1 junk food item.

The maximum -150 maximum food to prior should still be easily countered with junk food/donuts.

Even with the change it still does not make chef anyway needed. To me its a step to right direction and should actually add food buffs  that last for a while, except of course when did the chemists offer free stims?

**Comment by Manly-Dwarf** [comment]
Just because there are chefs doesn't mean they're cooking food. You don't see a HoP giving out access, you see him giving himself access or just fucking off. Chemists too, they don't function as a pharmacy - they just give themselves death chems and search for valids.
I've seen Chefs cook food too. I've also seen Space Ninjas. They're about as uncommon as each other. These statistics prove nothing.

**Comment by ghost** [comment]
BRING BACK OLDCOOKING
whatever though dont be hungry boys +1

**Comment by Carbonhell** [comment]
I'd rather prefer if chef food gave you some sort of "boost", instead of making people go hungry and get fucked since most of the rounds lack a proper chef and, as you can see, people didn't become chefs to fix the situation. Merging

**Pull request merged**
