### PR TITLE
[MIRROR] Manual compile in missing changelogs

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34088
--------------------
:cl:
fix: The changelog hadn't been updating. This has been fixed.
/:cl:

### CODE REVIEW

**Comment by JohnGinnane** [comment]
@Chnkr do we merge this?

**Comment by Pyko1** [comment]
just in case of triggerhappy maintainer.

**Comment by Pyko1** [comment]
also since changelogs are autogenerated, I see no reason to get upstream changes on the actual logs.

**Comment by JohnGinnane** [comment]
Yeah but it wasn't updating on their end so not sure what to do

**Comment by Pyko1** [comment]
well we have also broken our logs on our side as well on few occasions. I think it would be prolly best to close it, at worst we have some undocumented changes.

**Pull request closed without merging**
