### PR TITLE
[MIRROR] Removes Tech-Disk Exports

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35069
--------------------
:cl: Cobby
balance: Research done on-site is now Centcom property and can no longer be sold to the market.
:cl:

Reason: Technodes cost nothing except arbitrary points that passively generate. Cargo does not need a reliable way to get way over 100K points easily each round from nothing.

Once I take a look at the node numbers I may readd this if I don't ever get to Tycoon Cargo (tm).

also > 500 base money for a disk you can make with small amounts of metal and glass

epic.

I'll close this if someone can provides a reasonable alternative since I plan on bringing them back later on my terms anyways.

### CODE REVIEW

**Comment by xTrainx** [comment]
How about no

**Comment by Manly-Dwarf** [comment]
How about no

**Comment by DaydreamPuppeh** [comment]
Please no

**Comment by 2Dollarbill** [comment]
no.

**Comment by JohnGinnane** [comment]
@xTrainx @Kawaii-Big-Boss @DaydreamPuppeh @2Dollarbill you want this removed pls put up a revert or something

**Comment by ghost** [comment]
this can be modularised easily and kept independent of /tg/

**Pull request closed without merging**
