### PR TITLE
Fixes vamp mistform

### PR DESCRIPTION
**Pull request by ghost**
:cl: steamp0rt
fix: Vampire mistform should work properly
/:cl:

Was gonna wait til _upcoming vamp overhaul_ to fix this, but decided to go ahead and do so

### CODE REVIEW

**Comment by Carbonhell** [comment]
Did you test this? Why is mistform even ranged? Don't we have a special spell category for self spells?

**Comment by ghost** [comment]
@Carbonhell It's a subtype of ethereal jaunt

https://github.com/HippieStation/HippieStation/blob/master/code/modules/spells/spell_types/ethereal_jaunt.dm#L1

My guess is because range got changed, yeah, the bug happened

**Comment by Kierany9** [comment]
Is this a fix for mist form turning someone else into mist instead of yourself?

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
Either way, vamp overhaul is gonna do away with mistform

**Comment by ghost** [comment]
can you make it actually make you mist?  would be way better,  like legacy of cain vampires.

**Comment by GuyonBroadway** [comment]
@Kierany9 that shit _ALMOST_ saved my life once...

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
