### PR TITLE
[MIRROR] ports sprites from Endless-Horizon/CEV-Eris

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/28285
--------------------
# Ports a bunch of sprites from https://github.com/Endless-Horizon/CEV-Eris/tree/master/icons
(with their permission,thanks Bloodpriest!)

## medkits/tcomm/goonsprites are no longer part of the PR
**EDITED!** Picture below shows the majority of the sprites

1: Washing machine
2: Seed extractor , biogenerator
3: Microwave
4: Photocopier, binder
5: Powersink, forensic scanner 
6: Mechfab, autolathe, pipedispenser
7: Modular laptop
8: Rack, plasma/oxygen dispenser
9: Portable generators
10: Stacker, unloader (corner), furnace , unloader (corner 2), unloader
11: Stock parts (box_0-2,vbox_0-2)
12: Circuit imprinter, protlathe, analyzer, server, tdoppler
(13:) Charger

### CODE REVIEW

**Comment by ghost** [comment]
fuck yes

**Comment by Carbonhell** [comment]
Isnt that charger the same of the goon one

**Comment by ghost** [comment]
No

**Comment by GuyonBroadway** [comment]
I approve

**Review by j-mie — APPROVED** [review]

**Pull request merged**
