### PR TITLE
removes organ eating

### LINKED ISSUE #2449: You cannot insert organs into yourself
You will eat the organ and then it cannot be inserted. This needs to be fixed somehow.

### PR DESCRIPTION
**Pull request by ShadowDeath6**
fixes https://github.com/HippieStation/HippieStation/issues/2449

deep fry them or something

apologies if the code isn't up to standard, I used the online editor, but it's a simple enough change so I figured it wasn't necessary.

I'm also going to be gone for five days, any reviews or recommendations will be cleared up then.
feel free to close this pr if someone makes a better version

:cl: ShadowDeath6
rscdel: Removes the ability to eat organs that you could normally use in surgery.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
👎 No.

**Comment by Carbonhell** [comment]
+1. I hate seeing organs getting wasted due to this. Just deepfry them if you want to eat em.

**Comment by ghost** [comment]
@Carbonhell this does not fix the issue, nor does it fix it in a proper way.

**Comment by ShadowDeath6** [comment]
I'll just close it if it's not mergeable in its current state since I won't be able to edit it

**Pull request closed without merging**
