### PR TITLE
Gang-wide messages now show the name of who sends them

### PR DESCRIPTION
**Pull request by ghost**
> _Penis Gang Leader_: dom in cargo
> _Penis Gang Leader_: no let's dom in viro
> _Penis Gang Leader_: ur mom gay
> _Penis Gang Leader_: fuck you eat shit
> _Penis Gang Leader_: i'll blow you up you mofo

:cl: steamp0rt
tweak: Gang-wide messages now show the name of who sends them
tweak: Lieutenants can now be distinguished from the leader when sending gang messages
/:cl:

### CODE REVIEW

**Comment by Eagle-Eyess** [comment]
+1

**Comment by Manly-Dwarf** [comment]
Can you add an extra little widget or something so we know who the real gang boss is, instead of everyone being named "Leader"
Pre-Rebase it was "Waffle Boss" for the bosses and "Waffle Lieutenant #1" "Waffle Lieutenant #2" for the promoted gangsters.

**Comment by ghost** [comment]
Kinda out of scope

**Comment by Manly-Dwarf** [comment]
phooey

**Comment by ghost** [comment]
yeah please do what kbb said

**Comment by ghost** [comment]
yeah please do what kbb said

**Comment by ghost** [comment]
since the rank is also part of the gangsters identity

**Comment by ghost** [comment]
Fineeee

**Comment by ghost** [comment]
Done @zamolxius @Kawaii-Big-Boss

**Comment by Manly-Dwarf** [comment]
thanks bro

**Comment by ghost** [comment]
thanks bro

**Comment by ghost** [comment]
Good idea. Honestly all gang members should be able to communicate this way. We should make a lesser gang tool specifically for the underlings of the gang to use to communicate with the boss.

**Comment by Carbonhell** [comment]
tested?

**Comment by ghost** [comment]
Tested and working as intended.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
