### PR TITLE
[MIRROR]  Rebalances Chameleon Kits for lowpop

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34972
--------------------
:cl: Denton ShizCalev Kor Kevinz000 (original idea)
balance: Due to budget cuts, the shoes shipped with chameleon kits no longer prevent slipping. The premium version is unchanged and still sold separately.
balance: To compensate, the chameleon kit cost was lowered by 2 TC and the minimum crew limit removed.
/:cl:

Some time ago, chameleon kits were given a minimum player limit due to the noslips that come with them.
This PR removes the noslip ability from chameleon kit shoes, reduces the kit price to 2 TC and removes the player limit. Regular noslip shoes are still available and unchanged.

That way, lowpop tators can have disguises while highpop is unaffected, having the same total price for the old chameleon+noslips combo.

Code:
I created a shoes/chameleon/noslip subtype and moved the NOSLIP_1 flag to it. Also, I made sure that all other regular noslips refer to the new subtype.

### CODE REVIEW

**Comment by ghost** [comment]
-1

**Comment by GuyonBroadway** [comment]
Ur -1 means NOTHING when it comes to mirror prs

**Comment by Manly-Dwarf** [comment]
Fuck off, /tg/.

**Comment by JohnMcLaime** [comment]
This is good pr, this lame kit should be available at any pop, especially with lowered price due to noslips being removed from it.

**Pull request closed without merging**
