### PR TITLE
Upstream merge

### PR DESCRIPTION
**Pull request by ghost**
EUGHHHHHHHHH FIX FUCKING HONKBOT, IT'S NOT PROPERLY FUCKING MERGING COMMITS

closes #3345 and #3344

### CODE REVIEW

**Comment by KayeArray** [comment]
bullsquid attack sound.ogg

**Comment by GuyonBroadway** [comment]
>Files changed 427

The actual fuck, we missed like THREE prs!

**Comment by ghost** [comment]
FUCKING HONKBOT REEEEE

**Comment by GuyonBroadway** [comment]
All these conflicts, this can;t be right.

**Review by j-mie — APPROVED** [review]

**Pull request merged**
