### PR TITLE
Added a new chem to fix liver damage, and made balance changes to alcohol and livers

### PR DESCRIPTION
**Pull request by Jujumatic**
I have added a new chemical called iecure, it rapidly heals liver damage, purges alcohol from the system and heals toxin damage when the liver is failing (it never restores you to full health because it stops healing toxin damage once the liver is functional again). It has a similar recipe to oculine and the... other one that heals ear damage (Inacusiate?). I also modularised some things to make some balance changes to livers and alcohol, here are some changes I made:

- Reduced alcohol's sleeping time from 90 seconds to 10 seconds (whew lad this one was not fun)
- Reduced the amount of alcohol required to get liver failure
- Made the damage from liver failure vary more (it was fixed at 8 toxloss, now it does a random value between 1 and 8 toxloss to give the player more time to react)

:cl:
add: Added a new chemical that fixes liver damage and stops liver failure. Just make sure you're really quick on getting it!
balance: Reduced alcohol's sleeping time from 90 seconds to 10 seconds
balance: Reduced the amount of alcohol required to suffer from liver damage and get liver failure
balance: Changed the amount of damage liver failure gives so there's more time to fix the liver before imminent death
fix: Corrected a typo in the liver damage description in health scanners
/:cl:

### CODE REVIEW

**Comment by Jujumatic** [comment]
Review pls and headmin input

**Comment by Carbonhell** [comment]
sounds pretty cheap and it edits so many tg files for something that really shouldn't tbh
i'm neutral/leaning towards a -1

**Comment by Jujumatic** [comment]
it only edits 1 tg file and that's also because there's a typo in the medical scanners
:(

**Comment by Carbonhell** [comment]
Considering how in 20 days only i gave a fuck about this PR, i'll have to close it due to my -1 and lack of interest from other staff

**Pull request closed without merging**
