### PR TITLE
[MIRROR] [s] Improves AI, turret, and door logging

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/41327
----------------------------
:cl: ShizCalev
admin: Fixed AI fingersprints not getting logged
admin: Fixed some door interactions not being logged at all.
admin: Turret control interactions are now in mob combat logs
/:cl:

Fixes #40203

Semi WIP. Good to merge for the most part, but I would like to add logging in a couple more spots.

### CODE REVIEW

**Comment by yskefunky** [comment]
thank you, god

+1

**Comment by yobob591** [comment]
how am I supposed to grief and get away with it now +1

**Comment by yoyobatty** [comment]
You guys don't need to +1 shit related to logging and admin tools.

**Comment by yobob591** [comment]
no u

**Comment by yoyobatty** [comment]
dw, I will get this working lads

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
