### PR TITLE
Abductors now has a minimum playercount of 20

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: No more roundstart abductors on lowpop.
/:cl:

### CODE REVIEW

**Comment by ErwinSnowden** [comment]
Make hivemind have a minimum player requirement aswell.

**Comment by Toxici11i** [comment]
> Make hivemind have a minimum player requirement aswell.

this

**Comment by Toxici11i** [comment]
abductors gay +1 - only exists to give science ayy tech lol

**Comment by FantasticFwoosh** [comment]
> 
> 
> abductors gay +1 - only exists to give science ayy tech lol

You can get it off [lavaland's crashed ayy ruin](https://github.com/HippieStation/HippieStation/blob/07b8cd962f96ef4f6c4dcfa8e7e27cd62fe4e356/_maps/RandomRuins/LavaRuins/lavaland_surface_ufo_crash.dmm) via the tools, and also deconstruct the ayy walls of the UFO crash site for high value alien alloy that both deconstructs for a lot of resources & sells for a lot in cargo exports.

**Comment by cris5311** [comment]
-1
ayys on lowpop are chill, hivemeind is the real evil

**Comment by Toxici11i** [comment]
both are retarded on lowpop, people abuse ayys for infinite rad gun or free batons via slipping

**Comment by ghost** [comment]
+1 ayys are stronk when there aren't enough people on the station

**Comment by diegoxt45** [comment]
abductors are the sole cause of slog ass fucking rounds that last 5 hours and nothing exciting happens

**Comment by ghost** [comment]
diego says something relevant and not stupid for once.

👏

**Review by Manly-Dwarf — APPROVED** [review]

**Pull request merged**
