### PR TITLE
Adds the Syndie-Lad to the game.

### LINKED ISSUE #11801: Pip-Boy for Traitors
[Title]: # edasffhfah

[Implementation]: # Hfsdfadggh

[Why]: # 
hey hideandseeklogic
if you're reading this
you're smelly

[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers 

add it basically

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Manly Dwarf
add: Traitors can now set their uplink of choice to the Syndie-Lad, a portable arm mounted computer that tracks objectives and stores your uplink. Equipping it and pressing C will open the radial menu, or just hold it in your hand and press Z (assuming you're on hotkey mode). It also explodes, if you really need it to.
tweak: I currently don't have any good ideas for as to why you'd want to wear it instead of just hiding it in your backpack and using the pinpointer, so as of now it's also insulated. Have fun not getting shocked by the AI.
imageadd: Syndie-Lad sprite is by kmc, "detonate" button icon is by Navi.OS.
/:cl:

## About The Pull Request
Closes #11801 

## Why It's Good For The Game
fadsfadgfhh

pre-approved

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
There are two bugs with this right now that are currently unresolved:
1: A random, nonsensical runtime with the pinpointer. It doesn't stop the pinpointer from functioning or actually do anything, everything still works as it should, it just runtimes because ???. Also it fails to track the medal of captaincy.
2: Setting your uplink to the Syndie-Lad seems to not update uplink_purchase_logs_by_key, meaning if you purchased a bunch of stuff and then greentext with the Syndie-Lad as your uplink choice, you'll get "BADASS SYNDIE."

There's also a mild balance concern with being able to track objectives with a device that still pinpoints even if it's in your backpack. Not a huge deal since you likely already know where your objectives are, it plays sounds while you're fiddling with it, and if you get searched you're screwed. There's no uplink code, so make sure you're not fiddling around with this out in the open, lest you get it stolen.

**Review by ghost — DISMISSED** [review]
lgtm

**Comment by Manly-Dwarf** [comment]
don't merge this until balance discussion, potential new features, etc. is fully thought out and bugs are fixed

**Comment by Manly-Dwarf** [comment]
also we're gonna go for a quick testmerge round with this and liquids. it'll end badly I'm sure

**Comment by Lxtoofonea** [comment]
make it fire resistant too, similar to combat gloves. ether way this is good

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: ed234e9bc4291a39262eed266a0ac3844273fb22
Pull Request: 60f6e8d5e95bcc3bf62becc3b890170df52f8ecf
Server: cc22141f0e90499b169b6dea57b5356417e1bc3c

##### Comment
Quick testmerge for a balance run-down

**Comment by Majick1** [comment]
+1, the only thing i'd change is make the explosion the same as a nukie implant, seems kinda weak as is

**Comment by Manly-Dwarf** [comment]
It's already compatible with the KOTD and Double Agents gamemodes, which is good.

**Comment by ghost** [comment]
+1 btw

**Comment by lunaman22** [comment]
+1

**Comment by Manly-Dwarf** [comment]
Fixed the runtime and added a Syndie-Lad for Nuclear Operatives.
Made it so you can't examine the Syndie-Lad if you're wearing it.
Once the uplink bug is fixed, this will be ready. Might end up adding more to it in this PR or in the future.

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 9f693b670b74a037bddc378247d755c71c2e505c
Pull Request: 9dfb80364d834a51e82304862d9b03d2980d2259
Server: 22396f4b4970a6cdb08129d14c50c40fac461966

##### Comment
update n stuff y'know

**Comment by ghost** [comment]
#### Test Merge Removed

**Pull request merged**
