### PR TITLE
Spiked baseball bats and Columbine Kit

### PR DESCRIPTION
**Pull request by asskek**
Adds spiked baseball bats, craftable by using a metal rod on a normal bat. 

Adds a new spiked baseball bat sprite because I couldn't find the old one. 

Adds the Columbine Kit as seen here https://hippiestation.com/threads/columbine-kit.7429/ .

image

### CODE REVIEW

**Comment by 2Dollarbill** [comment]
+1 lad, just gotta go through the code review.

**Comment by tortellinitony** [comment]
Separate these into different PRs

**Comment by asskek** [comment]
that's fucking stupid but fine

**Comment by ghost** [comment]
atomize

**Pull request closed without merging**
