### PR TITLE
Removes SM from engineering, adds back Singulo/Tesla

### PR DESCRIPTION
**Pull request by ghost**
image

image

image

image

:cl: 
del: Removed the Supermatter shard from Engineering.
add: Added Singulo and Tesla back to Engineering.
/:cl:

Let's not force SM on our players, don't change what ain't broke /tg/. I'm actually alright with SM being a round start engine, but forcing the players to do SM or solars is kinda bad. I'm not a good enough mapper to try and take the whole remake old engineering with singulo/tesla and SM with atmos having access into the main area.

That being said, I redid this from scratch while referring to the old set up. I've compiled and tested the set up 5 or so times to fix small bugs. Cameras are working, engineering shutters are working, and it's generating power properly.

If there are any bugs that come up later, I'll fix them as they're reported.

### CODE REVIEW

**Comment by ghost** [comment]
What the fuck, I wasn't getting the step_x, step_y bug. Hold on.

**Comment by ghost** [comment]
Shit I got the commit the wrong way round. But yeah, I removed the rogue step_y = 0 regardless.

**Comment by ghost** [comment]
Fuck, I forgot to fix something.

**Comment by ghost** [comment]
NEVERMIND, I had a map error on switching branch but recompiling fixed it.

**Comment by Pyko1** [comment]
visually seems ok.
ctags seem ok.
Cameras are emp proof.

But i have to confirm whether you used plating or plating/airless out in the singulo room?
Don't want any more AT's.

**Comment by ghost** [comment]
Fuck I have not.
I'll do it later today.

**Comment by myontasm** [comment]
the comments show a broken man

**Comment by ghost** [comment]
fuck no, lets just have all engines so players can choose to setup either the SM, The Tesla, or the Singulo like we had pre-pre-pre rebase with two engines

**Comment by PopNotes** [comment]
^

**Comment by ghost** [comment]
As said in coderbus, I like old set up but this my first map change and there is currently an issue where people don't set up power since it's the new shard.

I'm all for redoing engineering a bit later again to do old old set up but I think we should merge this for the now so players are back in their comfort zone of singulo/tesla.

**Comment by ghost** [comment]
I ran a vote a couple days ago and just ran another one.
image
I understand this isn't very conclusive but I would like to put it out there that players have been asked about it.

**Comment by tortellinitony** [comment]
I'd rather have sing and no SM than SM and no sing. Nobody knows how to set up the supermatter. We can add it later if people complain (they won't.)

**Comment by ghost** [comment]
Which is my point. There's nothing wrong with SM being on the map for the players to set up, there's a problem when SM is the only thing players can set up.

**Review by tortellinitony — APPROVED** [review]

**Pull request merged**
