### PR TITLE
Thanos wardec now makes it impossible to get uranium bullets

### PR DESCRIPTION
**Pull request by ghost**
Garbage bandaid solution to a garbage hard-to-balance problem.

:cl:
balance: The reagent forge is now destroyed on thanos wardec.
/:cl:

Possible alternative/companion to https://github.com/HippieStation/HippieStation/pull/12007

### CODE REVIEW

**Comment by MeraNoMi** [comment]
+1 Garbage bullshit, whats the point in making thanos immune to so much power game and then still making him get knocked back by OP uranium bullets that do more than 30% more damage than normal bullets, you lose like a third of your 200 thanos hp from one bullet, shits op

**Comment by Ledwin1233** [comment]
this is /tg/ level of prs. imded pls nerf headass boi

**Comment by ghost** [comment]
@Ledwin1233 thanos is not meant to be cheesed. that was a design decision from the start. it's why he's immune to maxcaps and boh bombing.

**Comment by diegoxt45** [comment]
don't remove forge out-right. simply remove uranium with a message like "all the uranium in all the universe also mysteriously dissapeared but we're investigating the cause"

**Comment by ghost** [comment]
but uranium is still needed for cool science toys.

**Comment by Manly-Dwarf** [comment]
mad

**Comment by cb583** [comment]
-1 ang

**Comment by private-tristan** [comment]
+1 i'd prefer this over uranium getting nuked because uranium is used so often for making things in sci that are useful during thanos

**Comment by GuyonBroadway** [comment]
Or just do a "if(thanos) return" on the thing that makes uranium bullets do knockback.

Like, it's easy and not a retarded contrivance and you can still use uranium bullets on guantlet man they are just less effective.

**Comment by ghost** [comment]
It's not the knockback that's the problem. It's the problem you can load them into an autorifle and effortlessly chew through his health in 2-3 seconds.

**Comment by GuyonBroadway** [comment]
You could give purple chinman a tool to negate incoming ballistics perhaps?

**Comment by ghost** [comment]
ya know that's a good idea. like he did while fighting vs Iron Man in IW, when he yelled "COME ON!"

**Comment by GuyonBroadway** [comment]
Just as an idea what if he could toggle between "tanking bullets" "tanking lasers" or "tanking melee" so a mix of spessmens is necessary to bring him down.

**Comment by karmaisblackandbluepilled** [comment]
-1 fuck off retard

**Comment by AnthonyJNgo** [comment]
This PR irrelevant now.

**Pull request closed without merging**
