### PR TITLE
Replaces the current Syndicate Elite Hardsuit sprite with our old one.

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: Kawaii-Big-Boss
imageadd: Replaced the Syndicate Elite Hardsuit sprite with our sprite from 2016.
/:cl:

[why]: 
Because the old one looks better, and the current one bears too much of a resemblance to the Nanosuit.
Will get screenshots soon.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
elite hardsuit
okay

**Review by yoyobatty — APPROVED** [review]

**Comment by yoyobatty** [comment]
Will merge if headmins like it.

**Comment by ghost** [comment]
beautiful

**Comment by ExpAntique** [comment]
+1, I always hated how the elite suit made the person’s face show in combat mode, it looks goofy as fuck.

**Comment by Carbonhell** [comment]
Sure +1

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
