### PR TITLE
[MIRROR] Stockings

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/44274
----------------------------

## About The Pull Request
This pull request adds stockings into the game as selectable sock sprites
image
*(Sprites made by @Shazbot194)*

## Why It's Good For The Game
More customisation fluff is always good

## Changelog
:cl: AffectedArc07 and Shazbot
imageadd: Added 9 new sock styles
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Shazbot, you were supposed to bring balance to the sprites, not leave it in darkness!

**Comment by Manly-Dwarf** [comment]
these are only acceptable as long as we rename them "programmer socks" and pick a single color, preferably the one that will attract the least attention from a certain crowd

**Comment by Majick1** [comment]
If you're going for least faggy black and white is the only option, MAYBE orange if you need a second option

**Comment by DaydreamPuppeh** [comment]
The yellow or dark blue ones are the least degenerate.

**Comment by shazbot194** [comment]
Putting this out there
3E48DFF9-F341-4B2E-84EB-DDB125ABB6B2

**Comment by Manly-Dwarf** [comment]
BEES KNEES

**Comment by DaydreamPuppeh** [comment]
Green and purple

**Comment by mikolaj007** [comment]
+1, why the fuck not

**Comment by AnthonyJNgo** [comment]
Sure why not,  +1, marked for review by head maintainer before merge.

**Comment by ExpAntique** [comment]
-1

**Pull request closed without merging**
