### PR TITLE
[MIRROR] Add moth week as a holiday

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/39377
--------------------
:cl:
add: NanoTrasen now officially recognizes Moth Week as a holiday.
/:cl:

Completely untested. If you're going to merge it merge it quick since it ends in 4 days!

[why]: # http://nationalmothweek.org/

Not sure about other servers but Bagil is having fun with moth week (I think).

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
No. Denied.

**Comment by ghost** [comment]
-1

**Review by yoyobatty — APPROVED** [review]

**Comment by Manly-Dwarf** [comment]
@yoyobatty YOU BITCH

**Comment by ghost** [comment]
wtf is this

**Comment by Carbonhell** [comment]
jesus christ tg
Atleast it isn't a shitty event like valentines day

**Comment by ghost** [comment]
hhhhh

**Pull request merged**
