### PR TITLE
[MIRROR] Removes Soul Vessel, Cogscarab, and Anima Fragment Scriptures

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/29239
--------------------
:cl: Joan
rscdel: Removed the Soul Vessel, Cogscarab, and Anima Fragment Scriptures.
/:cl:

Don't worry, cogscarabs still spawn when ratvar is summoned.

But yeah, these are just kind of problematic; soul vessels let you get converted borgs and AIs from robotics at low cost, scarabs keep getting used for combat and being effective since they're tiny, and anima fragments are a relatively simple combat mob that cost a pretty large amount and aren't really effective enough to justify it.

Marauders get to stick around a bit, though! But only because removing them requires some combat tweaks so servants aren't weakened a ton in combat without them.

### CODE REVIEW

**Comment by PopNotes** [comment]
I'm gonna miss scarabs.

**Comment by FuryMcFlurry** [comment]
Dont we all

**Comment by GuyonBroadway** [comment]
If they nerf clock cult enough we could eventually add brass mechs to compensate. You need to be thinking 5 steps ahead on the monoply board while playing 4d chess lads!

**Comment by Hackole** [comment]
ew fuck no dont remove my meme drones

**Comment by oprayx77** [comment]
apparently this is a part of an upcoming rework that will have features to replace cogscarabs, or re-impliment them in a better way. I'd say its worth it if we want those other features

**Comment by tortellinitony** [comment]
Not our gamemode to mess with. If we'd like to have the new changes that are coming, then we should remove what is pending a rework. It's best to let the gamemode's creator do with it what he will.

**Review by j-mie — APPROVED** [review]

**Comment by j-mie** [comment]
If we want it back we should reimplement it modular.

**Pull request merged**
