### PR TITLE
[MIRROR] [READY] Goon Genetics

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/41258
----------------------------
### GENETICS

- The random hexadecimal rng game has been replaced with gene sequencing from goon.

- Adds mutation activators and mutators

- You can now store mutations

- Everyone now has their own set of unique mutations

- Limited mutations per person to 8 (including one always being monkey)

- Adds race specific mutations (See fire breathing for lizads)

- You can inspect discovered mutations, undiscovered mutations use an alias to recognize them by

- Adds a sequence analyzer. Can be used to scan someones genes sequence. Useful for determing what mutations they can safely have and or collecting data for very difficult sequences

- Adds mutation combining. It's currently only RADIOACTIVE + STRONG = HULK  (So yes you will now need 2 mutations for to get hulk)

- Adds several other mutations. Telepathy, firebreath, glowy, radioactive and strength

:cl: Time-Green
add: Goon genetics!
add: More mutations! Fire breath for lizards! Radioactive! Telepathy! Glowy! Strength, though its cosmetic and should be combined with radioactivity instead! Fiery sweat! 
add: Adds void magnet mutation by @tralezab !
/:cl:

Quick guide on how to have fun with mutations:

Every mutation consists of a sequence. It's the AT GC stuff. A goes with T and G goes with C. An active mutation has a correct sequence, like here:
image

First we want to disable this mutation, so we can move on with the others. Do this by making it faulty.
image
We replaced the fourth A with an X, making it a wrong sequence and thus disabling the mutation.

Now we can start with the real stuff. We'll select another mutation.
image
There's four X's, making it wrong. We can instantly fix two X's. The first pair with GX should be GC. The third pair with XA should be TA.

Now our mutation should look like this:
image
That just leaves a pair of X's. There's only four possibilities: AT, TA, GC and CG

image
It was CG. The mutation is now active and can be properly toyed with. 
Note: With two X pairs, there is still only 16 possibilities. If there are even more, you might consider peaking at someone else with the same mutation to see if they got that pair. (I recommend you do this with the sequence analyzer in your pocket, wich you can click on the DNA console to update it with the latest mutation names)

If we saved the mutation, it goes to our storage (Mutations)
image

Here we can do a bunch of stuff with it. 
Mutation name: Shows you more info
image
Export: Export the mutation to a disk for storage
Delete: Removes the mutation from your storage
Combine: First click, selects the mutation. Second click, attempts to merge it with another mutation to create a new one. Currently only works with Strength and Radioactive

Other notes about UI:
Removed rejuvenators. Get some from the chemist or use antitoxins. Note that most radiation damage has been reduced by alot.
Scramble DNA: Don't like the your subjects mutations and can't get a new one? Absolutely fucking radiation blast them and generate a new set of mutations
Disk: Disk interaction. Import, export and disk ejecting fall under this
Genetic Sequencer: Where you will be spending most of your time
Unique Identifiers: All identity mutation stuff has been moved to there. It still features buffers and the UE gene pulser for all your identity stealing needs.

Activators! Already got a mutation and want to give it to someone with it in their potential? Ram this thing into them to safely give them that mutation.
Mutators! Want to give someone a mutation that isn't listed on them? Use these to instantly give it to them for nothing*! *(actually violent humiliation and death)

Featuring more mutations!
Firebreath!
Telepathy!
Glowy!
Radioactive!
Strength! (Doesnt do anything)
Fiery sweat! 
Void magnet! Made by @tralezab 
And even some old ones!
Also disabled the unstable dna mutation, since it doesn’t fit well with goon genetics

End of guide 

- [X] Make mutations random for every person
- [X] New html
- [X] Make mutations stable and working
- [x] Add mutation disks
- [X] Mutation activators
- [X] Mutation injectors
- [X] More mutations
- [x] Even more mutations
- [x] Have genetic instability do something
- [x] Add some form of viewing your own DNA for discovered mutations
- [X] Alot of testing
- [x] Add the goon gene minigame

I will also be testing everything thoroughly and tweaking some stuff.

Another PR:
Chromosomes
Even more than more mutations! (Probably by someone else since I'll be prioritizing chromosomes)

### CODE REVIEW

**Review by yoyobatty — DISMISSED** [review]

**Comment by bardofrage** [comment]
+1

**Comment by earthmoonjune** [comment]
been playing for however long and still have never touched genetics. +1 tho

**Comment by Manly-Dwarf** [comment]
Some day, we'll run out of Goon to port.

**Comment by BlueNothing** [comment]
On the other hand, we don't have space pods yet...

**Comment by Manly-Dwarf** [comment]
Please don't steal Goon pods

**Comment by BlueNothing** [comment]
Because we should do them differently, or because they're a bad idea?

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by Manly-Dwarf** [comment]
Both.
Space poop right now, no reason to even have pods
Pods in goon are designed specifically for goon and should not be ripped off.

**Comment by BlueNothing** [comment]
It occurs to me that we could just make a jetpack part for mechs and get most of the important stuff that way. Maybe make a passenger seat part, too.

**Comment by Manly-Dwarf** [comment]
nah I'm not feelin that

**Comment by jediluke1999** [comment]
RIPLEY's can carry people in closets, though I don't know if the air tank also goes to them, and if not, just requires internals otherwise due to pressure.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
