### PR TITLE
[MIRROR] Remove nuclear operative TC consoles in favor of them just getting the TC pre-distributed

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43930
----------------------------

## About The Pull Request

With this PR, the nukies get their TC pre-distributed instead of having to do a complicated song-and-dance routine where people who sort-of know what they're trying try to convince people who don't to put their uplinks into the machines at roughly the same time to press some buttons.

## Why It's Good For The Game

The TC donation/distribution cycle is completely unneeded, realistically everyone is going to distribute their TC.

## Changelog
:cl: Naksu
balance: Nuclear operative TC now comes pre-distributed, the telecrystal assignment stations have been removed.
/:cl:

### CODE REVIEW

**Comment by mikolaj007** [comment]
+1

**Comment by Majick1** [comment]
+1, had way too many launches delayed because someone can't figure out how to distribute

**Comment by MaterialisticThings** [comment]
+1 We've been needing this for awhile, also keeps the lead operative from Jewing all of the TC.

**Comment by cb583** [comment]
As long as when declaring war the TC given from that is distributed evenly as well, which i'm sure it will be big huge +1

**Comment by Manly-Dwarf** [comment]
Why did they need to remove the console, though? What if they want to pool all of their telecrystals into the leader to buy a mech or something?
Granted, that never happens, but it's worth leaving them in just in case.

**Comment by Majick1** [comment]
Probably because people don't read and wouldn't know it got changed so they'd  keep doing it the old way

**Comment by cb583** [comment]
Also you can just buy raw tc and share that way anyway

**Review by ghost — APPROVED** [review]

**Pull request merged**
