### PR TITLE
Automatic beaker-take at ejection

### PR DESCRIPTION
**Pull request by Shdorsh**
Making multiple pills and getting your beaker back can be quite a pain in the butt, so I thought I would propose a small change that puts the beaker directly in the user's hand on ejection, so that it doesn't drown in pills.

[Changelogs]: # Beaker now directly added to hand after ejection

:cl: Automatic beakertake chem master
tweak: Beaker now directly added to hand after ejection
/:cl:

[why]: # Making chemistry less of a pain in the butt, as chemmaster tile tends to get littered by pills

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Needs to be made modular

**Comment by KayeArray** [comment]
And if hands are full?

**Comment by Shdorsh** [comment]
If hands are full, it automatically changes beaker loc to player loc.

**Comment by Shdorsh** [comment]
@Chnkr 
> Needs to be made modular

I'm not sure what you mean by made modular. I'm an amateur SS13 modder.

**Comment by Pyko1** [comment]
generally all our code changes are done in the hippie folder instead of directly to the regular tg code.

**Review by ghost — CHANGES_REQUESTED** [review]
make it modular

**Comment by KayeArray** [comment]
Get it working and sure I guess +1

**Comment by dreamcrab** [comment]
yea if it works properly ill be on board with this i guess

**Comment by ghost** [comment]
Upstream this, to be honest.

**Pull request closed without merging**
