### PR TITLE
Update slime.dm

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
tweak: Slimes will now eat faster, and get more nutrition.
/:cl:

## About The Pull Request
Apparently this got reverted from: https://github.com/HippieStation/HippieStation/pull/5525

## Why It's Good For The Game
Slimes will now eat faster because a lot of people think they're slow as shit.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by yoyobatty** [comment]
I want input as per our codebase standards before you merge this.

**Review by ghost — APPROVED** [review]
good code modularized properly

**Comment by MeraNoMi** [comment]
+1 Slimes are slow as shit, especially with Hippie rounds tendency to end in 30-45 minutes, plus compared to other departments Xenobio’s strength isn’t linear as round time progresses, it shoots up at certain milestones like getting a head slug from gold slime extracts for Xenoling, or getting a love potion and gender swap potion for your own personal army of Xenomorphs, compared to Robotics’ borgs and mechs throughout the round, or RnD’s tools and implants, meaning if the slimes don’t mate fast enough you just never hit these Xenobio power spikes

**Comment by karmaisblackandbluepilled** [comment]
+1 xenobio is fun but making slimes takes half a fucking aeon

**Comment by Manly-Dwarf** [comment]
stop +1ing this it's pre-approved code that was reverted on accident

**Comment by SireTurret** [comment]
when we mergin this

**Comment by ghost** [comment]
Yes

**Pull request merged**
