### PR TITLE
[MIRROR] Antagonist reputation system

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35485
--------------------
**#################################**
**This change will increase your odds to play as an antagonist on future rounds based on what roles you played in previous rounds.**
**#################################**

>**ElfLeaderMike**
> This PR is intended to encourage and reward people who play contributing roles on the station. It is my belief that there is a growing population of people that only play assistant and treat it as an antag rolling/valid hunting role. This is to help improve the balance between assistants and contributing roles while providing a reward for playing out a round as something useful to the station. This will also not reward players for committing suicide round start, so you are also encouraged to play through the round rather than round start suiciding without antag.

# **I'm only implementing this on his behalf and covering technical details. Please address ideological comments to him.**

**Bullet points**
- This does not apply to mid-round antagonists.
- Points are consumed when you roll antag.
- At least for now points _are_ intended to apply to latejoins.
- The numbers are very minor and will likely have to be tweaked (which is not difficult).
- Players cannot see their points.
- You cannot have negative points (i.e. you will not be discriminated against with negative personal odds)
- By current default settings the system will only allow you to double your odds. 100 points will double your odds.

**This PR includes**
- Configuration options for downstream servers
- Admin panel changes to see and modify people's point values (on the HTML player panel)

**Dear developers**
This is my first PR and first Byond/SS13 code. Triple check for me. I've tested things, but I may have made subtle mistakes.

**Things that still should be done in this or future PRs**
- Does this need a changelog? It affects stuff at the meta level but isn't a gameplay change. Not sure.
- Don't give people points if they suicide or leave the game very early on in the round without coming back.
- Add some kind of stat integration for debugging purposes to consistently verify the system is continuing to work correctly statistically.
- The role values are mostly for testing, I'm sure people will have a lot to say on what roles should give how many points.

**Community thoughts**
Admins can give points with the existing system (maybe even with a global announce) to highlight particularly cool or funny stuff after a round is over.

**How does this actually work?**
Copied from code comments-

```
This is a frequency selection system. You may imagine it like a raffle where each player
can have some number of tickets. The more tickets you have the more likely you are to
"win". The default is 100 tickets. If no players use any extra tickets (earned with the
antagonist rep system) calling this function should be equivalent to calling the normal
pick() function. By default you may use up to 100 extra tickets per roll, meaning at
maximum a player may double their chances compared to a player who has no extra tickets.

The odds of being picked are simply (your_tickets / total_tickets). Suppose you have
one player using fifty (50) extra tickets, and one who uses no extra:
    Player A: 150 tickets
    Player B: 100 tickets
       Total: 250 tickets

The odds become:
    Player A: 150 / 250 = 0.6 = 60%
    Player B: 100 / 250 = 0.4 = 40%
```

**What are the current point values for roles?**
(These numbers continue to be updated and revised as discussion evolves)
```
(20) AI - 5.0 games to double your odds
(20) Captain - 5.0 games to double your odds
(20) Chief Engineer - 5.0 games to double your odds
(20) Chief Medical Officer - 5.0 games to double your odds
(20) Detective - 5.0 games to double your odds
(20) Head of Personnel - 5.0 games to double your odds
(20) Head of Security - 5.0 games to double your odds
(20) Research Director - 5.0 games to double your odds
(20) Security Officer - 5.0 games to double your odds
(20) Warden - 5.0 games to double your odds
(17) Atmospheric Technician - 5.9 games to double your odds
(17) Botanist - 5.9 games to double your odds
(17) Chemist - 5.9 games to double your odds
(17) Cook - 5.9 games to double your odds
(17) Cyborg - 5.9 games to double your odds
(17) Geneticist - 5.9 games to double your odds
(17) Janitor - 5.9 games to double your odds
(17) Lawyer - 5.9 games to double your odds
(17) Medical Doctor - 5.9 games to double your odds
(17) Quartermaster - 5.9 games to double your odds
(17) Roboticist - 5.9 games to double your odds
(17) Scientist - 5.9 games to double your odds
(17) Shaft Miner - 5.9 games to double your odds
(17) Station Engineer - 5.9 games to double your odds
(17) Virologist - 5.9 games to double your odds
(14) Bartender - 7.1 games to double your odds
(14) Cargo Technician - 7.1 games to double your odds
(14) Chaplain - 7.1 games to double your odds
(14) Clown - 7.1 games to double your odds
(14) Curator - 7.1 games to double your odds
(14) Mime - 7.1 games to double your odds
(10) Assistant - 10.0 games to double your odds
```

### CODE REVIEW

**Comment by ghost** [comment]
deny

**Comment by JohnGinnane** [comment]
I like the idea however it's rewarding people to mostly play heads (all bar QM get 20 per round) or sec. It would be nice if we used to this to incentivize playing other roles like cook or MD or something that might help towards the round (even if they might do nothing, it's still more players taking a role and so more likely for the role to be actually played)

**Comment by Carbonhell** [comment]
This is retarded. Forcing people to play certain jobs won't make them magically good at them. And it would only give people like John McLaime, who joins as RD often, more antag chances. Literally why
-1, merge and disable it configwise

**Comment by JohnGinnane** [comment]
@Carbonhell we can change the breakdown of points

**Comment by KayeArray** [comment]
dont anger them this pr was made by team avo hackerman

**Comment by GuyonBroadway** [comment]
See I suggested a system to tg wherein if you do your job you get points but they told me it would be bad because "the people who want antag will get antag". and then they go and add this.

**Comment by ghost** [comment]
this is dumb since it just incentivises people who want to play for antag to shit up high profile jobs.

you want something to reward good players? make a system where admins can give antag tokens for interesting plays, even that's flawed but it does it better

**Comment by praisenarsie** [comment]
are you guys retarded, its a fucking config. it starts disabled anyway and erik can switch it whenever he likes, i hate this system too but at least look at the pr properly before whining.

**Review by praisenarsie — APPROVED** [review]
eat my ass

**Pull request merged**
