### PR TITLE
fixes farting and alternate screams

### LINKED ISSUE #7611: BRROOO farts are silent they have no sound
[Round ID]: # (If you discovered this issue from playing HippieStation hosted servers:) yes
[Round ID]: # (**INCLUDE THE ROUND ID**) 28820
[Round ID]: # (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.) no

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.) try to fart and its soundless

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.) no

### PR DESCRIPTION
**Pull request by GuyonBroadway**
:cl: Guyonbroadway
fix: Clothes with custom screams now work again.
fix: Farting now makes noise again
/:cl:

fixes: https://github.com/HippieStation/HippieStation/issues/7611

### CODE REVIEW

**Review by Carbonhell — APPROVED** [review]

**Comment by Jujumatic** [comment]
FUCK YEEEESSSS

You tested this I'm guessing?

**Comment by GuyonBroadway** [comment]
extensivly

**Comment by Jujumatic** [comment]
gooood anakin..... goooood.....

**Review by Jujumatic — APPROVED** [review]

**Comment by Dinopeaks** [comment]
LETS GO WE NEED FARTS BACK

**Pull request merged**
