### PR TITLE
[MIRROR] The Cook now only works under siege.

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35597
--------------------
:cl: Iamgoofball
fix: The Cook now ONLY works under siege.
/:cl:

### CODE REVIEW

**Comment by tortellinitony** [comment]
what the hell is this

**Comment by GuyonBroadway** [comment]
tg decided it would be a GREAT idea to give the cook free CQC, turns out it was a bad idea so they limited it to only working in the bar/kitchen.

**Comment by JohnGinnane** [comment]
Do we need this?

**Comment by GuyonBroadway** [comment]
If our cook has free cqc at roundstart then yes we do.

**Comment by JohnGinnane** [comment]
Okay, I've reflected the changes in *our* copy of cqc

**Review by JohnGinnane — APPROVED** [review]

**Pull request merged**
