### PR TITLE
Fixes SMES terminals and connection issues

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
fix: SMES power terminals not actually deleting the terminal reference when by cutting the terminal itself rather than the SMES.
fix: SMES now reconnect to the grid properly after construction.
refactor: SMES now uses wirecutter act to handle terminal deconstruction.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by JohnGinnane** [comment]
is this an upstream issue?

**Comment by yoyobatty** [comment]
The broken code originates upstream. This technically should be an upstream PR.

**Comment by Carbonhell** [comment]
can you bring it up to upstream then please

**Comment by yoyobatty** [comment]
I'll get one of them to

**Comment by yoyobatty** [comment]
could @McBawbaggings or @JohnGinnane upstream PR this? My tg is fucked, forking is broken on github.

**Comment by ghost** [comment]
sure

**Comment by JohnGinnane** [comment]
Yeah I would upstream this if you could, thanks

**Pull request closed without merging**
