### PR TITLE
Revert "Revert ling nerf"

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
Merge this so we can make "Revert "Revert "Revert ling nerf"""
Then it'll be perfect.

### CODE REVIEW

**Comment by yoyobatty** [comment]
???

**Comment by ghost** [comment]
wat

**Comment by sentientloaf** [comment]
They year is 2028.Society has begun tearing itself apart. People protest in the streets demanding that Revert "Revert Revert Revert Revert Revert Revert Revert Revert Revert Revert Revert Revert Revert Revert Ling Changes."The cycle has not been broken in the past decade. KBB is on trial for crimes against humanity as the one who started the cycle of constantly reverting than adding back in ling nerfs.

**Comment by G-erma** [comment]
-1 we live in a society

**Comment by Manly-Dwarf** [comment]
YOU'LL NEVER GET ME ALIVE

**Comment by Lxtoofonea** [comment]
-1 I can not in all good conscience allow a meme to go this far

**Comment by Manly-Dwarf** [comment]
How dare

**Comment by yskefunky** [comment]
no u -1

**Comment by yobob591** [comment]
revert revert revert revert

**Comment by danhibiki** [comment]
-2 headmins revert pr

**Comment by earthmoonjune** [comment]
revert
trever
the person behind this revert conspiracy meme is named trever????????????????

**Comment by GuyonBroadway** [comment]
The headmins have spoken, please talk to them if you wish this re-opened.

**Comment by Manly-Dwarf** [comment]
one year anniversary, revert dis!

**Comment by yoyobatty** [comment]
C-c-c-c-losed!

**Pull request closed without merging**
