### PR TITLE
Revert "Removes retard horn"

### PR DESCRIPTION
**Pull request by ghost**
No

### CODE REVIEW

**Comment by Substance455** [comment]
Yes. A horn that has a RNG chance to instantly kill you is OP as all hell.

**Comment by ghost** [comment]
Improve, don't remove

**Comment by Substance455** [comment]
Then make it cost more TC, or remove the instadeath chance.

**Comment by GuyonBroadway** [comment]
Its not an RNG chance, you die when you take 200 brain damage and the clown horn does a whopping _10_ per honk.

**Comment by GuyonBroadway** [comment]
Merging due to the pr this reverts violating standards.

**Review by GuyonBroadway — APPROVED** [review]

**Pull request merged**
