### PR TITLE
Adds a preference for footsteps, disables them by default

### PR DESCRIPTION
**Pull request by Carbonhell**
#8785 

:cl:
tweak: Added a preference for footsteps. It starts off by default, if you like them and want them, go in OOC preferences and turn them on.
/:cl:

[why]: Agreed by me and flux.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Can I piggyback this and add deepfryer sounds pls

**Comment by Carbonhell** [comment]
in a separate pr you mean?sure

**Comment by ghost** [comment]
+1

**Comment by Manly-Dwarf** [comment]
Ehh...
If hippiestation already has enough issues with stealth and sneaking about, adding footsteps would only complicate that even more. Didn't we revert an item pickup PR for exactly this kind of stuff?
Also why would you ever disable this when it gives you a direct advantage over other players? You can hear them walking when they're about to bust into your department.

**Comment by Carbonhell** [comment]
Someone may not like it, it isn't always about powergaming smh

**Comment by JohnGinnane** [comment]
@Carbonhell I meant in this PR

**Comment by Carbonhell** [comment]
i mean it's two separate things ree can't you make your own pr

**Comment by Manly-Dwarf** [comment]
It's not necessarily about powergaming when this is a concern about the gameplay its self. It's a niche feature that makes something that's already of concern with many gamemodes (i.e changeling, shadowling, abductor, so on) even more of a problem. (or we can just add boots or something that muffle footsteps)
Hippiestation **_IS_** powergaming you fool!

**Comment by JohnGinnane** [comment]
not wearing shoes should muffle but this isn't a PR that does that, it just adds a preference

**Review by yoyobatty — APPROVED** [review]
Code looks good.

**Comment by Carbonhell** [comment]
This pr may disable footsteps related to the mob completely, this means both hearing but also emitting them.

**Comment by Eagle-Eyess** [comment]
+1

**Comment by Carbonhell** [comment]
Codechecked and has enough +1s, merging

**Pull request merged**
