### PR TITLE
Adds PewDiePie's best quote as a roundend sound

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Jujumatic** [comment]
low effort unfunny 👺

**Review by Jujumatic — APPROVED** [review]
but code checks out

**Comment by WarRage333** [comment]
Won't really help with the image but if the new zeland thing didn' happen i would be so for this

**Comment by Manly-Dwarf** [comment]
@WarRage333 Did you forget all of our titlescreens?

Also meh, joke's old and passed by now. Probably not.

**Comment by ghost** [comment]
~~lol imagine tying PewDiePie to the NZ incident~~ whoops wrong NZ incident

**Comment by WarRage333** [comment]
Its about the new zeland round that happened on hippie not the guy talking about pewdiepie

**Comment by Manly-Dwarf** [comment]
What are you even going on about?

**Comment by Lxtoofonea** [comment]
-1, common guys, we already have an image problem as it is

**Comment by Jujumatic** [comment]
what toof said. goodnight sweet prince

**Pull request closed without merging**
