### PR TITLE
Changes disabler damage from 26 to 39

### PR DESCRIPTION
**Pull request by ghost**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
fix: Thanks to the new stamina system, a energy gun of disabler blasts didn't stun. Now, it should.
/:cl:

## About The Pull Request

Teegee did a bunch of stamina changes and we forgot to account for them. Now, disablers are literally useless. This should fix that problem - the reason for why it's lower than the original teejee value is because our original version stunned in 4 and not 3 as tg wants.

## Why It's Good For The Game
Something that was broken isn't broken anymore.

### CODE REVIEW

**Comment by yoyobatty** [comment]
What pr in particular changed it? Also, were you targetting chest?

**Comment by mikolaj007** [comment]
i once took 10 disabler shots and didnt fall down because the other guy was aiming for a leg

**Comment by ghost** [comment]
yep I was targeting chest. If you look at tg code they have theirs set to 40, up from 36 last time

**Comment by Manly-Dwarf** [comment]
can we fix the lightning bolt

**Comment by NautilusViper** [comment]
too lazy to self-test, does this slow after one shot? if so, -1, disablers are far more robust than people give them credit for already

if it still slows after two shots, then yeah sure why not +1

**Comment by ghost** [comment]
@NautilusViper it should be like tg, so pretty sure 2 hits go to orange.

**Comment by bigbluebeaker** [comment]
+1

**Comment by cris5311** [comment]
+1

No one uses them anyways

**Comment by Zyzarda** [comment]
merge pls

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
