### PR TITLE
Feb08 upstream merge

### PR DESCRIPTION
**Pull request by JohnGinnane**
Fetched and merged all the commits from tg up to yesterday night. @Pyko1 there's some changes to the shuttle that need to be done if you look at https://github.com/tgstation/tgstation/pull/33766 

You can see the following message I currently get when starting the server:

image

### CODE REVIEW

**Comment by JohnGinnane** [comment]
fuck off conflicts my DICK

**Comment by Manly-Dwarf** [comment]
Do not merge Hawaiian Pizza.

**Comment by JohnGinnane** [comment]
fuck off please

**Comment by JohnGinnane** [comment]
I did this wrong

**Pull request closed without merging**
