### PR TITLE
Adds country flags to OOC

### PR DESCRIPTION
**Pull request by ghost**
adds a brazil flag next to BRs

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
might as well just add the rest of the flags while you're at it

**Comment by ghost** [comment]
that'd require a lotta effort

**Comment by Manly-Dwarf** [comment]
lame and unnecessary then

**Comment by ghost** [comment]
good news: I managed to automate it

**Comment by DONKARMA** [comment]
let us choose flags like 4channel

**Review by Neotwr — APPROVED** [review]
brazil approves

**Comment by Fikou** [comment]
what happens if a person who's country is missing says something

**Comment by ghost** [comment]
@Fikou no flag

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by Majick1** [comment]
+1 unnecessary but funny enough

**Comment by diegoxt45** [comment]
+1 why ins't this merged?

**Review by yoyobatty — APPROVED** [review]

**Comment by yoyobatty** [comment]
Welp, lets see how this one goes.

**Pull request merged**
