### PR TITLE
adds bullsquids

### PR DESCRIPTION
**Pull request by DeityLink**
Commission for Wheezl, sprites by FantasticFwoosh

bullsquid
image

:cl:
* add: Added bullsquid hostile mobs. Those can spawn from gold slime cores injected with plasma.

### CODE REVIEW

**Comment by carlopault** [comment]
+2 sure why not

**Comment by wheezl** [comment]
+3 I plan on expanding on their abilities/behavior later. for now they are just a simple mob that eat headslugs and have slightly more health than a space bear

**Comment by byandaccount** [comment]
+2 i like it, it's sprite looks pretty good too.

**Comment by xTrainx** [comment]
only from plasma? what about blood or water?

**Comment by FantasticFwoosh** [comment]
Nobody left me a ``@`` for my own sprite? For shame. 

Nice to see this being used.

**Comment by DeityLink** [comment]
@FantasticFwoosh Sorry, I wasn't told who made the sprite. It looks good, kinda wish you made the icon 64x64 so it could look as big as it does in the original game.

Also I jury-rigged a dead version as you can see.

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
