### PR TITLE
Get rid of the SM delam countdown

### PR DESCRIPTION
**Pull request by ghost**
lmao this shit is for pussies over at /tg/

:cl: steamp0rt
tweak: the SM no longer has that pussy-ass "causality stabilization" before it explodes.
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
I thought the reason for it was so engies could fight a delam to the last possible second, because with enough hyper nobiliun you can stop even the worst delams, and still have 10 seconds to clear the blast area in case they can't do enough.

**Comment by ghost** [comment]
No, once the countdown starts, it's going to explode anyways. It's actually hardcoded that way. All the countdown does is scream every 5 seconds over common. And the SM does that anyways when the integrity gets low enough.

If you haven't cleared the blast area by the time it's done screaming, well, RIP you lol

**Comment by JohnGinnane** [comment]
@steamp0rt why remove it

**Comment by ghost** [comment]
@JohnGinnane it has no purpose other than to be a hugbox feature

**Comment by JohnGinnane** [comment]
\>hugbox feature
How is some nice lore fluff a "hugbox feature"?

**Comment by GuyonBroadway** [comment]
No as in, till the destabliser field kicks in engineers can still theoretically save the supermatter. The field kicking in is the *"YOU FUCKED UP. YOU'VE GOT 10 SECONDS TO FUCKING RUN FOR IT*"

And also to warn any crew that the SM is gonna go boom, don't be anywhere south of the janitors closet.

**Comment by JohnGinnane** [comment]
Yeah I don't have a vote but I think removing this because "lol fuck /tg/" is always a shit reason

**Comment by ghost** [comment]
C I N E M A T I C

**Comment by ghost** [comment]
Again, once the SM integrity is like, what, below 10%, it starts screaming on Common. So that also warns the crew.

It's hugbox cause it pretty much removes the chance of anyone directly dying from the SM explosion, cause they got 20 whole seconds, once it reaches 0%, to fuck off to the other side of the station!

**Comment by JohnGinnane** [comment]
should we remove the o2 indicator as well cause it pretty much removes the chance of anyone directly dying from lack of air?

I strongly -1. Removing a feature because you think it's "hugbox" isn't good enough to remove a feature

**Comment by ghost** [comment]
Still, no reason for this to exist. Literally everyone with a radio will know once it reaches 0%. No need for an arbitrary 20 second cooldown.

**Comment by JohnGinnane** [comment]
There is a reason for this to exist, it gives any people who were near SM a chance to get away. If the countdown starts it's the point of no return. You could still recover if it was 0% because the countdown hasn't started

What benefit is it to remove this feature?

**Comment by ghost** [comment]
Yes, but if it reaches 0%, you've fucked up. It's either "recover it", or run away before it reaches 0%

There's no consequence for those near it with the countdown, they're just gonna be like "oh i guess i can't fix it so i'm gonna flush myself down disposals and fuck off"

Fucking up the SM should fuck up those near it.

**Comment by JohnGinnane** [comment]
Yeah I still don't think that's good enough to remove it. Taking people out of the round (whether they caused SM to blow or not) isn't what I want in the game. This countdown gives people a chance to get away in a cinematic fashion, but they might not always get away if the explosion is big enough (dependant on state of SM) or they can't escape for whatever reason

**Comment by Eagle-Eyess** [comment]
-1 no reason to remove it

**Comment by Carbonhell** [comment]
-1. It's pointless to remove this.

**Comment by Carbonhell** [comment]
I'm sorry, denied.

**Pull request closed without merging**
