### PR TITLE
[TESTMERGE ONLY] fixes dullahan heads

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Not critical as the lasy fukken snowflakes could pick their own damn head up but it looks ok.

**Comment by ghost** [comment]
@GuyonBroadway no, their heads spawn at the menu screen

**Comment by GuyonBroadway** [comment]
Ah, never saw what happend to roundstart snowflakes. One the one hand FUCK SNOWFLAKES on the other hand PEOPLE ADDED THESE SNOWFLAKES AS AN ANIMIE REFERENCE AS OPPOSED TO AN IRISH MYTH REFERENCE! but on a more code related hand.... ok.

**Review by GuyonBroadway — APPROVED** [review]

**Comment by ghost** [comment]
Pull requests don't have to be open to be test merged, closing this for this exact reason to prevent someone from accidentally merging this.

**Pull request closed without merging**
