### PR TITLE
botany great again

### PR DESCRIPTION
**Pull request by RafRoq**
ignore the mess its working

### CODE REVIEW

**Comment by ghost** [comment]
long live botanystan

**Comment by bubberducky2** [comment]
it's nigh time botania rises...
:fist_raised: :seedling:

**Review by Jujumatic — CHANGES_REQUESTED** [review]
modularise dis shit *also* please highlight the changes you've made and insert a changelog

**Comment by RafRoq** [comment]
https://github.com/HippieStation/HippieStation/pull/9914/commits/e187523c49de7c765c82e1ff1111356f76cbdbf1 it is modularised and  the changes are, stock parts dont limit yield extraction and production speed extraction @Jujumatic  github dont ignore changes that cancel each other

**Pull request closed without merging**
