### PR TITLE
[DNM] PykoAI

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Manly Dwarf, CZ, Pyko
add: We fired the old AI lady and replaced them with a drunken finnish lad. fugg :-DDDD
/:cl:

## About The Pull Request
0% modularized
Huge filesize
All of the Pyko

## Why It's Good For The Game
It's Pyko, why wouldn't it be

Pre-approved

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
Do Not Merge because the PR is incomplete. Waiting on a few more soundfiles.

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by yobob591** [comment]
+1 EBIN :DDDD

**Comment by Maroonenahmoron** [comment]
+1

**Comment by ghost** [comment]
[s]

**Comment by ExpAntique** [comment]
+100

**Comment by BarginMart** [comment]
Of fucking course +1

**Comment by biggiOS** [comment]
+1

**Comment by NautilusViper** [comment]
+1 but only active on ass day

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: cf7d75cdc4b9761e2902cdaabc33ed6a37d6708b
Pull Request: 40fdc680624ef0eafe526d579774ba112dc9c409
Server: 373cef429e08fdae5b25967e85000717e716e340

##### Comment
okay let's do this

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 06f2efe93f8da6dad7478dcfb918aa39f6a0dcaa
Pull Request: 40fdc680624ef0eafe526d579774ba112dc9c409
Server: 0fad314f41f6ebac5ea74539092beed6a139976f

##### Comment
another test round

**Comment by ghost** [comment]
#### Test Merge Removed

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: fb7861a0503c3a61c00519f76b4df9824c24a612
Pull Request: 40fdc680624ef0eafe526d579774ba112dc9c409
Server: 2907375bc90421e2043cc8375e53d05ab145956c

##### Comment
Round Three

**Comment by ghost** [comment]
#### Test Merge Removed

**Review by ghost — APPROVED** [review]
Seems like this is just a sound add, can't see anything wrong with this

**Comment by Majick1** [comment]
Let's get this closed

**Comment by lunaman22** [comment]
is this literally pyko instead of ai voice?
+1

**Comment by DaydreamPuppeh** [comment]
Why was this closed...

**Pull request closed without merging**
