### PR TITLE
Adds HOS pug and grill 

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
add: HOS's pet pug, Handcuffs has been re-added
add: The grill has been added to the kitchen
/:cl:

## About The Pull Request
What it says on the tin.

## Why It's Good For The Game
Missing pet and new feature should be added into the map!

### CODE REVIEW

**Comment by diegoxt45** [comment]
cult this traitor that i just want to grill for god's sake! +1

**Comment by karmaisblackandbluepilled** [comment]
diego aren't you permabanned
+1

**Comment by spessbro** [comment]
+1 :)

**Comment by diegoxt45** [comment]
> diego aren't you permabanned
> +1

no i'm not wtf

**Comment by yoyobatty** [comment]
@HippieStation/designers @HippieStation/leadership

**Comment by Maroonenahmoron** [comment]
What the, I swear I saw the grill on the server the other day... is this not already in?

+1

**Comment by ghost** [comment]
> 
> 
> What the, I swear I saw the grill on the server the other day... is this not already in?
> 
> +1

this just maps it in

**Comment by yoyobatty** [comment]
@steamp0rt merge?

**Review by ghost — APPROVED** [review]

**Pull request merged**
