### PR TITLE
removes moth week

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Manly Dwarf
add: moths suck
/:cl:

## About The Pull Request
removes moth week

## Why It's Good For The Game
moths suck

remove moth

### CODE REVIEW

**Comment by geylard** [comment]
no denied

**Comment by 88scheming88** [comment]
+1 moths are only good for [REDACTED]

**Comment by MaterialisticThings** [comment]
+1

**Comment by ExpAntique** [comment]
+1 snowflake class get fucked

**Comment by Lxtoofonea** [comment]
-1, this does not get rid of moth players, it only makes them play as human and thus hides them from us. being racist to moths was one of the best parts of ss13 because only shitters play moth. And again, not having a shitter class does not remove the shitters.

**Comment by Pyko1** [comment]
This only removes moth week event

**Comment by Lxtoofonea** [comment]
sorry i got confused by the "remove moth" part

**Comment by cris5311** [comment]
+1

Fuck moths

**Review by AnthonyJNgo — APPROVED** [review]
Literally just deleting a few lines of code, nothing can go wrong here.

**Pull request merged**
