### PR TITLE
[MIRROR] Removes fucking gangs

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/30056
--------------------

:cl: More Robust Than You
del: Finally fucking removed gangs
/:cl:

This removes TEAM MURDERBONING: THE GAMEMODE!

almost nobody fucking likes this garbage gamemode, it's like splatoon meets CoD meets Team Deathmatch. it's horrible. gangsters get instakill/crit weapons (like c4 shurikens, which are almost guaranteed to kill if they hit), security has to deal with 3-4 groups trying to rip each other's hearts out, the AI constantly screams "HOOMAN HARM!!", and oh yeah, it's a fucking mass conversion mode.

Or, explained by @ YakumoChen: 
> It's like Revolution but the revs also get free ballistics to kill me more easily with!!!!
> Now with triple the revheads and the round doesn't end when I kill them all leading to an endless stalemate where I will have to implant absolutely everybody on the station (or end the round with shuttle as quickly as possible because fuck this gamemode) before it's finally over!!

### CODE REVIEW

**Comment by bardofrage** [comment]
No

**Comment by DinduStuffin** [comment]
-1
Keep grudgecode shit on /tg/ and off of hippie.

**Comment by earthmoonjune** [comment]
No.

**Comment by GuyonBroadway** [comment]
currently at - 1 2/3 needs a full -2 in order to be closed.

**Comment by ghost** [comment]
i think nu gangs suck

you convert people and they get their own uplink with strong weapons to murder with instead of the head boss dishing out the goods like a true boss or his lieutenants doing so.

i dunno, old gangs were cool

**Review by j-mie — APPROVED** [review]

**Comment by Arzion5** [comment]
I'll only support this if old-gangs is brought back afterwards. Otherwise, -1

**Comment by tortellinitony** [comment]
I will move gangs to the hippiestation folder later

**Pull request merged**
