### PR TITLE
Adminbus chem: Grape blast (WIP)

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
add: A mysterious drug from A1 convenience store has found it's way on the station
/:cl:

## About The Pull Request
This adds an admin only spawnable drug that induces extremely powerful and vivid hallucinations that are incredibly unique from all other drugs. It starts out as blurred vision and messages of euphoria and then your screen begins to tumble back and forth, melt and distort in very complex wave-like patterns.  You will also experience very surreal hallucinations that your character won't hesitate to express.

## Why It's Good For The Game
Proper drugs are highly underappreciated. Stuff like mind breaker toxin and space drugs pale in comparison to skewium and rotatium which are dwarfed by this chem. This has potential to be very hilarious for anyone watching, especially the victim of whoever takes the drug.

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
YOU KIDS LOOK LIKE YOU COULD USE A DELICIOUS FRUITY BEVERAGE

**Comment by NautilusViper** [comment]
> YOU KIDS LOOK LIKE YOU COULD USE A DELICIOUS FRUITY BEVERAGE

oh god oh fuck

also +1 from me more shitpostchems are always good

**Comment by Manly-Dwarf** [comment]
oh yeah also +1

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by Majick1** [comment]
+1 bring on the grapist

**Comment by ghost** [comment]
#### Test Merge Deployed

##### Server Instance
HippieStation

##### Revision
Origin: 3d2041e78faed35e25a6ed58660d79269879d2eb
Pull Request: a5bfce1fb98952281c63cfb68619bbe8eac8e835
Server: f835a98e2da0470f9f0399c3f083fa6b5348f455

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 639d8342c103ff2d3197d882ba1a2f558cfd5edc
Pull Request: 3120430b2060c8f43b4ed3a67ca90677206b1347
Server: 2d4004947c6b98cec6342fb128073dd57e026f86

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 8ad798873bf2ab73025ced8f9d2c1b347777407f
Pull Request: 3120430b2060c8f43b4ed3a67ca90677206b1347
Server: f15ffa120cb482cd80e7baa245907dbefb362220

##### Comment
THE GRAPIST

**Comment by cris5311** [comment]
ill +1 any chemicals which are somehow decent and this is great

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: ccbb0797d45c02daba153bf3f739bc6692ed8482
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: 5baa9fb2622c54665648dc3228fa9876fdf86054

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: ddefe65b5112604c6cb77552c64f834822ebab68
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: d2dd9f12f17ed24a28967e180f9777084154d85f

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 108a220378df96784ad3942bc39f6e03092b2dc7
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: 9183cb939885116804ce2012e418f1cda6d682bb

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 108a220378df96784ad3942bc39f6e03092b2dc7
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: bbcc1d2312a2a1d5b6d7f4506fd105c3d722f46c

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 310e178d24316b7bafd8fb77b42565e8dc9cbaf9
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: 02b05aea4ffc32cfa5d48a33661638f28bd07f8c

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 310e178d24316b7bafd8fb77b42565e8dc9cbaf9
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: 5d86e320745dfc523914d064e23a024751406e5d

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 67f4df41d842068f6939850ca543accbebc8e70a
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: da33c0edc22b8a30f695a874fd2fbcf9bf49e0da

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 0bfcae94d9525e97fb95971516e5e6d5021b179e
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: 714e784899af510034cd480241d09a0d5d6c0e96

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: fab9e0a430a814745f75fb6d8c8bd0c7cd97e499
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: 55988d3df4950419d290a98544a5338f7daa801e

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: bdeebde36b0d3765ef1c29e99833ca5c1df91cba
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: 2b2e4fa80eb2e64094b10643c3f6ccd28c664eff

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 37ec11dc828cdc1ee3239e38aa84bcaec28760bc
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: bb872e4741299c73900cc8710d72f5dbbe749fc0

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 21fecc8817b538b8bf27c1d9da8fb6a93d5a6477
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: 6687fed1ab416bc53d60fa2ac5cc264892366687

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: e6f9bc0c1632d0be33755a613cefb5e2aaff4732
Pull Request: c44ba54cf7ba87a55c408539e24446b23e72f99c
Server: cb7d7109fa95fbe2805c02e0e7dc9ae69497c761

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: dc05d74f3dd7344ebebe4697fa69108b969ace58
Pull Request: 4f7b56a22e57e1cdf5e7a53866617243ed4488bb
Server: 56dffd5b15c3d0072fa3f7298fcca339487db1d5

##### Comment
THE GRAPIST

**Comment by mikolaj007** [comment]
it's been testmerged for a while
just merge it and be done with it +1

**Comment by AnthonyJNgo** [comment]
Obvious +1.

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 1a2f3cb65fa92f3586a20c50efa8ed20e257fb7b
Pull Request: d02f3e77bf9da9a67a2def3352390ec6df0bf54a
Server: 44b8fe368f82921e929f0690f17ba9738271e5db

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 1a2f3cb65fa92f3586a20c50efa8ed20e257fb7b
Pull Request: d02f3e77bf9da9a67a2def3352390ec6df0bf54a
Server: dd0298ee74c908edd73ef9fdcb12c86a9eb23c3b

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 91a4d5a438db997d704c9295343e7bf40f2e7e76
Pull Request: d02f3e77bf9da9a67a2def3352390ec6df0bf54a
Server: f76779e756f0af1d6bf287b1bcb75f58f6236a3b

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: cbba97d1e020f6e4bd96e3ea814a08c18327746a
Pull Request: d02f3e77bf9da9a67a2def3352390ec6df0bf54a
Server: 56a21609227b77d5e0dfa4544cc220f189707f6a

##### Comment
THE GRAPIST

**Comment by ghost** [comment]
#### Test Merge Updated

##### Server Instance
HippieStation

##### Revision
Origin: 260977d467c52f5dea6e352a3a1e80be2f33c29f
Pull Request: d02f3e77bf9da9a67a2def3352390ec6df0bf54a
Server: 1f18fc6380271376dfc8b87dad10baaa830da60f

##### Comment
THE GRAPIST

**Review by AnthonyJNgo — APPROVED** [review]
Looks nice and clean, grape blast is good to go.

**Comment by ghost** [comment]
#### Test Merge Removed

**Pull request merged**
