### PR TITLE
Asay Hotkey

### PR DESCRIPTION
**Pull request by AliiTea**
Asay is now bound to f3

### CODE REVIEW

**Comment by tortellinitony** [comment]
What happened here?

**Comment by AliiTea** [comment]
@tortellinitony ??

**Comment by JohnGinnane** [comment]
Asay is already bound to F3

**Review by ghost — CHANGES_REQUESTED** [review]
Alright, so I'm pretty sure it would have been cleaner to make a new PR, but so long as this one is here: Go ahead and revert all of this, then plug in your changes manually. There's no need to give is-disabled = false the juden treatment.

**Comment by tortellinitony** [comment]
why is this reopen

**Comment by ghost** [comment]
Because asay isn't bound to f3 in /tg/, so it was assumed that it was closed by mistake. That being said, I have no problem with it being shut down if only for a new PR to be put up properly.

**Comment by ghost** [comment]
open a new PR

**Pull request closed without merging**
