### PR TITLE
Buffs cattle-prod stamina force from 80 to 100

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
balance: Makeshift cattle-prod stamina damage increase from 80 to 100
/:cl:

[why]: Because we like 2 hit cattle-prods.

### CODE REVIEW

**Comment by Lxtoofonea** [comment]
+1 AWWW YEEEE

**Comment by Manly-Dwarf** [comment]
Why did we make it two hit to begin with? If you're an Engineer or a Scientist, you can already acquire a stunbaton really easily if you truly cared that much.
I get the whole "all stuns suck" circlejerk that Guyon has going on with the other coders, but this still ain't gonna make the item viable in any way considering the ease of access other one hit stuns still have.
-1? I guess? Does this PR even matter considering it won't change anything? I dunno.

**Comment by Carbonhell** [comment]
all stuns suck
remove them all

**Comment by ghost** [comment]
+1

stunprods are virtually useless

**Comment by ghost** [comment]
the two use stunprod was a shitty tg nerf alongside not being able to put them into backpacks because hurr durr graytide dunked me

**Comment by yoyobatty** [comment]
Original cattleprods, have an insta 10 second stun, stunprods are 14 seconds, our stunprods are 10 seconds.

**Comment by WarRage333** [comment]
-1 
Improvised weapons should not be as good as proper ones 

2 shot if it fits in backpack 

One hit if wielded and it's a bulky item

**Comment by Manly-Dwarf** [comment]
@WarRage333 Hi, you must be new around here. Welcome to Hippiestation!
Stunprods originally weren't better than stunbatons at all on virtue of their power efficiency. Considering that literally every single melee weapon in the entire game was an instant stun, all this nerf does is reinforce powergaming and make security better than it has any right to be.
Already, improvised weapons aren't as good as security's stunbatons simply because they don't do anything. Sec can instant win you whereas you have to hit them around ten times just to get a kill, even with a wielded spear. Stunprod was still useful, but it was no ranged taser so it was still only really good for getting the jump. On top of that, its shorter stun duration matched with the hugely worse power efficiency meant that stunning someone and keeping them down for a long time (such as kidnapping & chases where you can't cuff) were incredibly difficult.

Nerfing someone hard enough to never fit in your backpack is already one of the hardest nerfs you can possibly give to an item. You also want to make it two handed (wielded) even though there's no purpose for that to be the case considering it has no advantage? What's the point of even making improvised weapons if there's no reason to ever use them considering there are still one hit stuns that are way better? You're just buffing powergame if you do that, and the last time we buffed powergame it got really bad.
These features might as well not be in the game if they're going to be as bad as they are now. Swing Combat is already desperately needed to make stunbatons not godking in melee combat, not helped by coders like Guyon who keep wanting to nerf everything into the ground because "stuns suck", completely failing to miss the point that he'll just go backwards and end up reinforcing the exact same meta by holding up ranged stuns to still be the best.

**Comment by WarRage333** [comment]
Buffing this won't change how powergamers powergame, this just makes it every shitter on the server has a one click kill stick in their backpack 

And security needs and has to be better in every regard considering all the destructive things antags get.

It's the power gamers that are the problem in this case and balancing around how those individuals play is dumb.

**Comment by Manly-Dwarf** [comment]
But every powergamer already knows a way around the nerf so what's the point of having the nerf to begin with?
You ideally want to give Assistants a reason to use improvised weaponry, but this gives them none, so they'll just charge towards greytiding sec gear every round any way. Which is what they do.

**Comment by WarRage333** [comment]
Graytiding sec for equipment is still better than having an infinite amount of craftable stuns

**Comment by Manly-Dwarf** [comment]
No, it's really not, considering Security can keep the greytide at bay with tasers and other means of crowd control. Greytiding sec effectively takes out what is supposed to be the round's peacekeeper for some bloodthirsty vigilants. An infinite amount of craftable stuns is also complete hokey, since the stunprods all need batteries, and someone snowflaked out the ability to use a low power cell battery with it, so you'll need either Science or Engineering to cooperate to begin with.
Both Science and Engineering can already get said dangerous gear without even trying, so if this nerf is meant to stop them, you failed miserably. They can also get flashes, which despite being better than stunprods due to them typically having more uses, a crowd control self-use, and being plentiful as well as having small sizes, are never even considered to be nerfed because someone died to a stunprod and now thinks that all stuns should be removed from the game.
EDIT:
They actually require igniters now, too, instead of wirecutters. Igniters can be found around the place for sure, but definitely require more effort than a wirecutter. So it was nerfed from a crafting standpoint, a usage standpoint, a power standpoint, and so on. Coders just cannot stop nerfing this thing, even though they just made Flashes a blatantly superior alternative and fixed nothing.

**Comment by yoyobatty** [comment]
It's 2 hit and fits in bag.

**Comment by WarRage333** [comment]
If it takes takes 200 stam dmg to get stunned then +1 I thought this makes then one shot like before thinking stam stuns at 100 dmg

**Comment by yoyobatty** [comment]
yeet

**Comment by Eagle-Eyess** [comment]
+1

**Comment by yskefunky** [comment]
yes pls +1

**Comment by bardofrage** [comment]
+1

**Review by Lxtoofonea — COMMENTED** [review]
code seems good to me

**Comment by GuyonBroadway** [comment]
Just saying that any stun greater than five seconds (enough time to cuff someone) is basically as good as any other stun greater than five seconds for virtue of once the cuffs are on its game the fuck over.

**Review by ghost — APPROVED** [review]

**Pull request merged**
