### PR TITLE
Sec overhaul: new cell and a better medbay 

### PR DESCRIPTION
**Pull request by Dinopeaks**
[Changelogs]: # adds a new cell to sec as seen here 
dreammaker_2018-05-10_16-17-39

and a sleeper to sec medbay as seen here  
dreammaker_2018-05-10_16-17-48

:cl:
add: Security has been overhauled slightly.
/:cl:

[why]: # well and new cell for the super shitters and showers in the gas chamber and a sleeper for you pussy boys who need meds

### CODE REVIEW

**Comment by yoyobatty** [comment]
We can't have overlapping pipes like this:
image
 Please fix this

**Comment by Dinopeaks** [comment]
you can't ah did not know that
i will fix it now

**Comment by Dinopeaks** [comment]
dreammaker_2018-05-10_18-00-45

here is the updated picture

**Comment by yoyobatty** [comment]
Open the map file in notepad and find step_ delete all instances and recommit

**Comment by Dinopeaks** [comment]
I know
I will

**Comment by Dinopeaks** [comment]
all is fixed, so lets go

**Comment by yoyobatty** [comment]
Looks great +1

**Comment by Dinopeaks** [comment]
bump

**Comment by Carbonhell** [comment]
I guess we can try it, +1

**Comment by Manly-Dwarf** [comment]
What's the point of the extra cell? It's essentially just a shorter, lamer permabrig.

**Comment by CorruptComputer** [comment]
I think you missed something:
image

**Comment by JohnMcLaime** [comment]
Whats the point of adding extra cell?

**Comment by Pyko1** [comment]
to ensure if we add nice things to real perma, no one gets to use em since they always get locked in to the worse one.

**Comment by CorruptComputer** [comment]
One more: 
image

**Comment by CorruptComputer** [comment]
Also here: 
image

**Comment by Dinopeaks** [comment]
well i have been cucked by this map update also will fix those things ASAP not home

**Comment by earthmoonjune** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by Jujumatic** [comment]
map conflicts - probably because of the upstream :(

**Comment by yoyobatty** [comment]
I recommend making a copy of the map you have modded, update your master branch, push it, then switch back to this branch, merge the master into this, push, run preparemaps.bat ,then copy and paste the changes in the copy map into hippiestation.dmm then map merge, it will work

**Comment by Jujumatic** [comment]
@Dinopeaks FIX UR MAP RRREEEEEEEEEEEEEEEE

**Comment by yoyobatty** [comment]
well dino I'm probably going to update this myself

**Comment by Jujumatic** [comment]
being redone in #7618

**Pull request closed without merging**
