### PR TITLE
Basic PDA Appearance Tweaks

### PR DESCRIPTION
**Pull request by TungstenOxide**
:cl: 
tweak: Added a few html snippets to change the font of the PDA
tweak: Added a few html snippets to remove bullet points and underlines from PDA menus
/:cl:

[why]:
Cleaning up the PDA and making it look a little nicer and more authentic. So, A E S T H E T I C .

ddgbg67798989

### CODE REVIEW

**Comment by j-mie** [comment]
Please follow the changelog standard:

:cl: optional name here
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
wip: added a few works in progress
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
experiment: added an experimental thingy
/:cl:

https://raw.githubusercontent.com/HippieStation/HippieStation/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by TungstenOxide** [comment]
Sorry. Better?

**Comment by ghost** [comment]
that font hurts my eyes

**Comment by TungstenOxide** [comment]
It'd probably be pretty easy to write a settings menu to change the font. I might do that if it hurts your eyes @MoreRobustThanYou . Personally, I think this is the best font, but I'll experiment.

**Comment by Thelolswat** [comment]
It'd be cool if there were options to change how your PDA looked, like how you can change UI color

**Comment by TungstenOxide** [comment]
Yes! Thank you! I was thinking about adding that. Coming _right_ up!

**Comment by TungstenOxide** [comment]
Making a new pull request because I added a few more features and this one is clearly getting nowhere.

**Pull request closed without merging**
