### PR TITLE
Fixes wiki manuals

### PR DESCRIPTION
**Pull request by Carbonhell**
:cl:
fix: Manuals based on the wiki now work.
/:cl:

### CODE REVIEW

**Review by JohnGinnane — DISMISSED** [review]
you test this?

**Comment by Carbonhell** [comment]
wait,doesn't work

**Comment by Carbonhell** [comment]
nvm it does work

**Comment by Carbonhell** [comment]
this will only partially fix them, the rest has to be done box wise, merge

**Pull request merged**
