### PR TITLE
answer to issue #10535

### PR DESCRIPTION
**Pull request by ghost**
#10535

## Changelog
:cl: zamolxius
tweak: tweaked macrobombs being restricted
/:cl:

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
you tested this, right? it works for micro and macro?
+1, never even noticed it had a pop cap

**Comment by ghost** [comment]
its for macro, micro didn't have restriction

**Comment by Manly-Dwarf** [comment]
merge this

**Comment by k-k-karma** [comment]
no it needs another +1

**Comment by DaydreamPuppeh** [comment]
+1

**Review by Jujumatic — APPROVED** [review]

**Comment by Jujumatic** [comment]
Lol eat pant

**Pull request merged**
