### PR TITLE
fixes mrty's bad keybindings port

### PR DESCRIPTION
**Pull request by ninjanomnom**
mrty is a bad smell please remove

:cl: ninjanomnom
fix: Keybindings should be working again and you can diagonal move
/:cl:

### CODE REVIEW

**Review by yoyobatty — APPROVED** [review]
Code looks good. I hope this is tested.

**Review by yoyobatty — APPROVED** [review]
+1

**Comment by Arzion5** [comment]
>You can diagonal move

YOU MADMAN, WHAT HAVE YOU DONE

**Comment by praisenarsie** [comment]
it's not really much of a gamechanger actually, considering this has been on /tg/ for like almost 2 weeks now

**Comment by Arzion5** [comment]
WAIT WHAT

**Comment by praisenarsie** [comment]
lol hippie fag

**Review by ghost — APPROVED** [review]

**Comment by ninjanomnom** [comment]
Now that this is merged you're going to have to re-implement any custom hippie controls you had because the system changed.

**Pull request merged**
