### PR TITLE
removes smoke machine

### PR DESCRIPTION
**Pull request by praisenarsie**
:cl: Frozenguy5
balance: Smoke machine now has a max range of 9, as opposed to 15.
balance: Smoke machine can now only hold 300 reagents, as opposed to 1000.
/:cl:

also makes smoke machine name and desc better
bantz told me to do this

### CODE REVIEW

**Comment by PopNotes** [comment]
should be 10 tiles max range and 500u max capacity to keep things nice and spicy

**Comment by praisenarsie** [comment]
fuck off

**Comment by PopNotes** [comment]
i'll kill you

**Comment by KayeArray** [comment]
+1

**Review by KayeArray — CHANGES_REQUESTED** [review]
Needs to be modular unless /tg/ get their ass in gear with the upstreeam one

**Comment by tortellinitony** [comment]
Smoke machine is garbage, just get rid of it

**Comment by tortellinitony** [comment]
ugly ass sprite and we have our own turfchem and chem gasses, we don't need a smoke machine

**Comment by praisenarsie** [comment]
will reopen because i've realised something and i hate tgui

**Pull request closed without merging**
