### PR TITLE
Changes many of our retarded sprites to be the better /tg/ sprites.

### PR DESCRIPTION
**Pull request by ghost**
Stop being resistant to the future, fucktards.

### CODE REVIEW

**Comment by ghost** [comment]
Build triggered. sha1 is merged.

**Comment by ghost** [comment]
Build started sha1 is merged.

**Comment by ghost** [comment]
fuck off honkbot

**Comment by ghost** [comment]
Build finished.

**Comment by KayeArray** [comment]
Our codebase is currently a mess of old and new sprites thanks to random incoherent changes.

I support either this or a complete change of new sprites to old but not the current half way bullshit.

**Comment by GuyonBroadway** [comment]
Sadly due to new machines being added we will never really be able to go all the way back to oldsprites without someone making them for us.

**Review by ghost — APPROVED** [review]
Code OK

**Comment by Blute1** [comment]
but we need images to see what you changed

**Comment by tortellinitony** [comment]
fuck off eris sprites are shit, we've turned into /tg/ enough at this point and we don't need to look like it even more

**Comment by ghost** [comment]
@tortellinitony We won't be able to keep up with our retarded sprites if /tg/ keeps adding new machines, so fuck off.

**Comment by tortellinitony** [comment]
that makes no sense

**Comment by ghost** [comment]
@tortellinitony You seem to be the only one here supporting our shitty sprites

**Comment by tortellinitony** [comment]
We can keep old sprites as long as we want to, you're one of the only people I've seen complain about us not having tgstation's sprites. This isn't tg, this is Hippie Station. Go play on tg.

**Comment by Carbonhell** [comment]
Jesus no i hate the new computers
Pls

**Comment by Blute1** [comment]
I like the old sprites, we should switch back to them, we need our own identity from TG

**Comment by Iamgoofball** [comment]
did you know disliking visual change is a sign of autism

**Pull request closed without merging**
