### PR TITLE
[READY]makes the circuit lab and RnD look better 

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: changes the huge ugly Rnd+circuits room combo. 

:cl: zamolxius
add: readds an autolathe in the circuits lab and adds a telescreen in the circuits lab
tweak: separated the RnD+circuits large ugly room into two rooms
/:cl:

[why]: it looked absolutely hideous, to be honest

### CODE REVIEW

**Comment by ghost** [comment]
de71463f0411576709ce280e36da11ca

**Comment by WarRage333** [comment]
YES YES

**Comment by GuyonBroadway** [comment]
Having the techfab in front of the vending machine seems awkward, try putting it by the window instead.

**Comment by Carbonhell** [comment]
Hell yes. +1

**Comment by ghost** [comment]
how about a tile north? looks S Y M M E T R I C

**Comment by yoyobatty** [comment]
Make sure the area names are correct please.

**Comment by ghost** [comment]
oh fuuuck.  i made this once,  did the areas,  then messed shit up and remade it,  forgot to remake the areas too

**Comment by yoyobatty** [comment]
Please make sure you test this. If you haven't, I advise going in-game to debug tab and enable debug verbs, then you will see a mapping tab appear. Run the tests there. If you see any broken pipes on coords (x,y,2) basically under z level 2, make sure you fix it.

Also do not forget camera tests!! You can play as an AI to see if you have any trouble with them. DO NOT FORGET TO CHANCE C-TAG'S TOO!!

**Comment by ghost** [comment]
68f918fe19619d72df9b5ba63a47d515
can be merged. ignore the reversed lightbulb.

**Comment by ghost** [comment]
cameras tested, is okay, there's a few weird pipes in engineering at the supermatter but I believe they're good and not a bug

**Comment by Eagle-Eyess** [comment]
+1

**Comment by Manly-Dwarf** [comment]
why is there so much empty space

**Comment by yoyobatty** [comment]
So you can test circuits

**Comment by JohnGinnane** [comment]
Looks great @zamolxius

**Comment by earthmoonjune** [comment]
+1

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
