### PR TITLE
[MIRROR] Removes the empty moth language file

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/35625
--------------------
didn't fully remove it in my remove moth language pr

added [s] tag because i don't want people from the servers coming here to cry about moth language

also it's not in the .dme either

### CODE REVIEW

**Comment by praisenarsie** [comment]
it's botched because for some reason you guys never removed the moth language even though it's removed upstream.

**Comment by JohnGinnane** [comment]
@Pyko1 https://github.com/HippieStation/HippieStation/pull/6061

Do we even have the moth language?

**Comment by Pyko1** [comment]
I recall removing it, but prolly forgot to make changes to the actual language file.

**Comment by Pyko1** [comment]
should be same as TG now

**Review by praisenarsie — APPROVED** [review]

**Pull request merged**
