### PR TITLE
add staplers

### LINKED ISSUE #8345: there are no staple guns anywhere
Issue reported from  Round ID: 30197 (Hippie Station)

Reporting client version: 512

we cannot reattach asses

### PR DESCRIPTION
**Pull request by Eagle-Eyess**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: EagleEyes
add: adds 5 staple guns to the map. 1 in library, medbay reception, lawyer office,  cargo and conference room. 
/:cl:
fixes #8345 
[why]: # why were they removed?

### CODE REVIEW

**Comment by mattmatterson111** [comment]
They weren't removed they just got lost in the 5 rebases.

**Comment by ghost** [comment]
sounds good, can't wait to restaple my ass on

**Comment by ghost** [comment]
woo staplers +1

**Comment by earthmoonjune** [comment]
+1

**Review by GuyonBroadway — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
code looks K and has enough +1's

**Pull request merged**
