### PR TITLE
[MIRROR] [READY] Adds the Gravitokinetic stand type

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/43846
----------------------------
## About The Pull Request

This adds the gravitokinetic stand. It's attacks are weaker but they apply heavy gravity.
They can also alt click the ground to apply heavy gravity to that tile, the gravity applied from floor punches is heavy enough to damage people over time.

Recalling drops all of the affected tiles, and they have a range as well.

## Why It's Good For The Game

Nobody ever really made a zoning stand, it's great for not letting people get away, or get to you for that matter. No other stand really does that, they just drag your corpse through the hallways.

I probably need to add a sound and an effect on the tile, like maybe the tile gets really blurry or something.

## Changelog
:cl:
add: Gravitokinetic stands are now available!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Me likey this

**Comment by DaydreamPuppeh** [comment]
Echoes ACT 3?

**Comment by Manly-Dwarf** [comment]
Nobody will use this.

**Comment by ghost** [comment]
someone add the thing to the hippie dme and merge it plz

**Comment by mikolaj007** [comment]
+1, might as well

**Comment by AnthonyJNgo** [comment]
This is good, marked for batty to check out.

**Pull request closed without merging**
