### PR TITLE
Burpinate: Burp inducing drug

### PR DESCRIPTION
**Pull request by neetdev**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: neetdev
add: Burpinate, a chem that makes you burp more and more the longer it's in your body. 
code: The recipe requires dr.gibbs which should prevent it conflicting with other recipes. The metabolism rate could be made faster but it requires a fair bit of chems to make it (kind of like chloral hydrate) so it's unlikely it could be abused as to lead to an obscene amount being pumped into the crew rapidly.
/:cl:

[why]: # We have fartium but no "burpium".

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
You forgot to commit the changes to hippiestation.dme too without it these files will never be compiled server-side.

**Comment by neetdev** [comment]
does that mean I open it, update and then add/commit?

**Comment by ghost** [comment]
no it means stick it deep up your asshole

**Comment by dreamcrab** [comment]
fuck yea memechems
+88888

**Comment by ghost** [comment]
hell yeah dude fix the shit and its +1

**Comment by JohnGinnane** [comment]
What you need to do is open up hippestation.dme in dream maker, navigate to your files and then tick the checkbox to include them in the build, otherwise when the server updates it won't include them

**Comment by JohnGinnane** [comment]
Wrong button, sorry about that!

**Comment by Pyko1** [comment]
speaking of burps, we need to make an agressive grab + help intent on torso, to pat people on back to make em burp.

**Comment by PopNotes** [comment]
The description is fucking legendary by the way
+1 from a maintainer

**Review by JohnGinnane — APPROVED** [review]
Looks good

**Comment by JohnGinnane** [comment]
Wait fuck, still missing the include

**Review by JohnGinnane — DISMISSED** [review]
Still missing the include

**Comment by neetdev** [comment]
I'm still unsure what to do. All the boxes are ticked in the dream maker tree of hippiestation.dme. Sorry to keep asking for spoonfeeding but I can't find anything on google.

**Review by ghost — APPROVED** [review]
These files were already existing in the DME, dumbasses

**Review by ghost — DISMISSED** [review]
You need to add the files to the DME

**Comment by KayeArray** [comment]
+1

**Pull request merged**
