### PR TITLE
Map Updates

### PR DESCRIPTION
**Pull request by yoyobatty**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty's Map Changes
Add: Flood light in engineering secure storage
Add: Shutters to armory and warden office + firelocks
Add: Strong doors to armory entrance and weapon racks
Add: More air vents around the station
Tweak: Fixed the symmetry on the AI sat entrance
Add: Chemistry shutters and desk facing hallway
Add: Plasma glass windows in tcomms +firelocks and firealarms
Add: Engineering security doors to the space windows
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Station's air vents weren't plentiful enough in some areas, armory needs more security, chemistry could use the extra socialization as well as security, tcomms was in dire need of stronger windows and fire alarms (It's a god damn server room) and engineering sec doors on the space windows were removed on the last engineering update by some sloppy copy paste job. Also that AI sat entrance was bothering me and a lot of other people.

Edit: Oh and the flood light in Engineering because it seemed pretty fitting that the Engineering/Maint department could use of these incase of a blackout.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Hey optional name here, thanks for the PR :^)

**Comment by praisenarsie** [comment]
Hey YoYoBatty's Map Changes, thanks for the PR :^)

**Comment by bardofrage** [comment]
+1 on this when it's reviewed.

**Comment by KayeArray** [comment]
+1 just fix the conflicts

**Comment by ghost** [comment]
Replaced by #5240

**Pull request closed without merging**
