### PR TITLE
Slime scanner changes

### PR DESCRIPTION
**Pull request by xTrainx**
[Changelogs]: # Slime scanners can be used from inside the console

:cl: Slime scanner upgrade
tweak: slime scanners can now be used at range and through cameras, enbling it to be used from the slime management console
/:cl:

[why]: # slime scanners are almost not used, except when rushing rainbow slimes, because of the need to be right next to the slime to use it, since it takes a bit too much time and click, and this pr removes that inconvinience

### CODE REVIEW

**Comment by WarRage333** [comment]
YES YESSSSSSSS YEEEEESSSSSSS

**Comment by ghost** [comment]
yeah why not
+1

**Review by JohnGinnane — APPROVED** [review]
Looks good

**Comment by xTrainx** [comment]
pls respond

**Comment by JohnGinnane** [comment]
Do we need @HippieStation/head on this???

**Comment by GuyonBroadway** [comment]
Needs 1 more +1

**Comment by JohnGinnane** [comment]
If the heads don't +1 soon I think merge anyway, worst case ontario we can revert. At least this way we get new things into the game

**Comment by xTrainx** [comment]
https://media.discordapp.net/attachments/276456582500319244/398607374577041408/unknown.png?width=400&height=162

**Comment by ghost** [comment]
Was this tested? If so +1

**Comment by Pyko1** [comment]
is approved and code looks good to me as well.

**Comment by xTrainx** [comment]
i cant belive it actually worked tbh

**Pull request merged**
