### PR TITLE
Adds a huge 500 unit beaker and other fixes and additions

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Huge beakers now spawn in chemical closet lockers
add: Huge beakers (500u) are now in the game as a minor chemistry buff
tweak: Vapor now looks MORE like vapor
code: Cleaned up some old code related to how chemical reagent dispensers worked
fix: Fixed sec wardrobe going invisible when powered off
/:cl:

## About The Pull Request
What it says in the changelog. 
Vapor now looks like a more transparent version of smoke rather than flying dots.

## Why It's Good For The Game
Lots of stuff you all love

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
by Allah it is time to make methbombs bigger than the maxcap again

**Comment by karmaisblackandbluepilled** [comment]
+3

**Comment by Punkinguy** [comment]
seems alright. +1

**Comment by ghost** [comment]
-2 This kind of makes bluespace beakers useless. All that research for something when you can just pull a beaker out of a closet at round start.

**Comment by yoyobatty** [comment]
Ah, but can you make infinite huge beakers? No, they are 200 units more and are basically a portable giant chem vat. Plus at most there's 2 in the map since iirc there's only 2 chemical closets, 1 in chemistry and 1 in the room beside EVA.

**Comment by enthethan** [comment]
You should be able to order them tbh

**Comment by yoyobatty** [comment]
Wouldn't be a bad idea if there's a limited stock aboard

**Comment by mkikt4743** [comment]
can they go in nades? shouldn't be able to sine again it makes bluespace useless, hate to agree with quarian but he's right

**Comment by yoyobatty** [comment]
I don't think it makes bluespace beakers useless since those can be basically made on the double in medical and science assuming you have the resources and these are confined to Chem closests

**Comment by carlopault** [comment]
Yeah it kinda makes bluespace beakers useless unless you only give chemistry one 500u beaker.

**Comment by enthethan** [comment]
Nigga I feel like there's just a bunch of bots talking here, bluespace beakers can be made infinetly you only get 2  of these in 1 round

**Comment by yoyobatty** [comment]
Chemistry does get 1 beaker, the only other one that I am aware of is in the room beside Eva maint which chemists don't have access too. That closet would require a way of opening too so greytiders couldn't easily mug it.

**Comment by carlopault** [comment]
> Chemistry does get 1 beaker, the only other one that I am aware of is in the room beside Eva maint which chemists don't have access too. That closet would require a way of opening too so greytiders couldn't easily mug it.

hmmm alright sure +2

**Review by Neotwr — APPROVED** [review]

**Pull request merged**
