### PR TITLE
Cleans up some human code.

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
there's some problems with this compiling, help?

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
HELP

**Review by yoyobatty — CHANGES_REQUESTED** [review]
Bro you this code doesn't even work, you can't code me out that easily!!!

**Comment by ghost** [comment]
speedmerge time

**Comment by Carbonhell** [comment]
This is really bad holy shit

**Comment by Manly-Dwarf** [comment]
YOU CAN'T CLOSE THIS I WORKED SO HARD ON IT
AAAAAAAA

**Comment by ghost** [comment]
who even is @AnthonyJNgo

**Pull request closed without merging**
