### PR TITLE
gets rid of our ugly RnD machine sprites

### PR DESCRIPTION
**Pull request by ghost**
gross

:cl: Thefastfoodguy
imageadd: added some icons and images
imagedel: gets rid of our ugly RnD machine sprites
/:cl:

### CODE REVIEW

**Comment by j-mie** [comment]
pics please

**Comment by ghost** [comment]
who u calling ugly

**Comment by Pyko1** [comment]
whats wrong with our beautiful RnD machines icons?

**Comment by ghost** [comment]
pic:

**Comment by ghost** [comment]
build this

**Comment by ghost** [comment]
Tbh the sprites we already have are better but that's just my take on it

**Comment by GuyonBroadway** [comment]
Our sprites are starting to look a bit dated though. Ideally we'd need some good spriters to come by and makes us some real new ones.

**Comment by ghost** [comment]
These look even worse

**Comment by ghost** [comment]
purely subjective, i just plain don't like these.
-1

**Comment by PopNotes** [comment]
v. not good

**Pull request closed without merging**
