### PR TITLE
Pre-Ass Update Computer Sprites

### PR DESCRIPTION
**Pull request by Manly-Dwarf**
[Changelogs]: #

:cl: Kawaii-Big-Boss
add: Adds "New" computer sprites, from Pre-Ass-Update
/:cl:

[why]: # The current computer sprites are ugly, flat in terms of color, and uninteresting. The keyboard sprites are all just random mish-mashes of colors, with the computer screens being flat colors that are boring and lame.

I fixed that by re-adding the superior old computer sprites, way back from before Ass Update. Will add images soon.

[Link to the suggestions page on the forums.](https://hippiestation.com/threads/pre-ass-update-computer-sprites.8337/)

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Gimmie some screenshots goyham.

**Review by GuyonBroadway — APPROVED** [review]
Yuo See Ivan, no code, no problem!

**Comment by Manly-Dwarf** [comment]
Screenshots.
ai upload
armory
bridge
research director
science
security
I can't edit modular console sprites, so that one ugly looking console on the bridge stays the same.

**Comment by tortellinitony** [comment]
Disgusting

**Comment by Manly-Dwarf** [comment]
Better than the current, flat ones.

**Comment by ghost** [comment]
i personally liked these, and as such, will give it my +1

**Comment by Carbonhell** [comment]
Did the iconbot die, wtf anyway its ok, +1

**Review by Carbonhell — APPROVED** [review]

**Comment by praisenarsie** [comment]
@Carbonhell leoz quit so he shutdown the icondiffbot i believe

**Comment by Manly-Dwarf** [comment]
community doesn't want this

**Comment by ghost** [comment]
-1

**Comment by Manly-Dwarf** [comment]
You're voting on a closed PR, nerd.
brainlet

**Comment by ghost** [comment]
aw fuk bye

**Pull request closed without merging**
