### PR TITLE
Maintenance Longface Lair (Fixed version)

### PR DESCRIPTION
**Pull request by carlopault**
Same as the other PR except it isn't wack and outta shape. 

image
top right corner of the station

## Changelog
:cl:
add: A new room in maintenance: the Longface Lair
/:cl:

### CODE REVIEW

**Comment by ProtozoaPrime** [comment]
Dude you can literally just commit again to the same old PR, you didn't need to make a new one, but other than that, I'm happy you finally got it finished, congrats man

**Comment by carlopault** [comment]
> Dude you can literally just commit again to the same old PR, you didn't need to make a new one, but other than that, I'm happy you finally got it finished, congrats man

oops oh well

**Comment by AnthonyJNgo** [comment]
What proto said, but it's okay, this is a learning process, and it is very obvious that you have done some learning. Extremely impressed that you went from asking how we could program an image, to actually making a working PR on git. +3 for the change also.

**Comment by yoyobatty** [comment]
I basically showed this boy everything, apparently teaching a man how to fish is hard when he doesn't even have a pole and bait.

**Comment by carlopault** [comment]
> I basically showed this boy everything, apparently teaching a man how to fish is hard when he doesn't even have a pole and bait.

yes

**Comment by AnthonyJNgo** [comment]
Waiting for just a few more votes, then this can merge.

**Comment by byandaccount** [comment]
i like it, we need more shit in maintenance and i can see the room itself being repurposed for alot of stuff.

**Review by AnthonyJNgo — APPROVED** [review]
lgtm

**Pull request merged**
