### PR TITLE
Xcom gun changes

### PR DESCRIPTION
**Pull request by Timmeye**
### **CHANGELOG** ### 
🆑 Aaa321
tweak: The 6.7mm rifle now costs more materials to make but the magazine is cheaper, also the sprite should be centered
/🆑
### **Info** ### 
might re-center sprite. also changes cost

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
+1
also since only admins can vote on shit now, ping @admin whenever you make a new pr

**Comment by mkikt4743** [comment]
yeah

**Comment by carlopault** [comment]
what xcom guns

**Comment by karmaisblackandbluepilled** [comment]
the 6.7mm rifle

**Comment by karmaisblackandbluepilled** [comment]
oh also viv said that +1 isn't the same as +3 so +3

**Review by yoyobatty — CHANGES_REQUESTED** [review]
Please document your changes with a changelog.

**Comment by Timmeye** [comment]
> Please document your changes with a changelog.

Made a changelog

**Comment by carlopault** [comment]
I dont know anything about the xcom gun

**Comment by mkikt4743** [comment]
Xcom my balls lol

**Comment by MrEpicSax** [comment]
+1

**Comment by Punkinguy** [comment]
+1

**Comment by ghost** [comment]
-2 Raising the cost isn't exactly what this weapon needs. At the moment, it's already worse than the magrifle despite costing more in research and materials. Buff the rifle to be noticeably better than the magrifle, or reduce the cost in both research and materials to be less than the magrifle.

**Comment by AnthonyJNgo** [comment]
Pretty stale PR.

**Comment by mikt4743thesecond** [comment]
Pretty stale server.

**Comment by carlopault** [comment]
@yoyobatty close this PR for me, it has been open for like 10 years and no progress

**Pull request closed without merging**
