### PR TITLE
[WIP] Modularizing circuits onto Hippiestation

### PR DESCRIPTION
**Pull request by Shdorsh**
[Changelogs]: # Keeps circuitry from being removed by Upstream PR and gives us FINALLY the possibility to pretty much change everything about it. Open up your old circuit PRs, folks, we're in for some fun!

:cl: Shdorsh
refactor: Modularizes the entirety of circuitry
/:cl:

[why]: Because hippie has definitely an interest in circuitry and we should help developing it further without being encumbered by upstream limitations. I don't know if this is too early to do so, but anyway, here you go.
The upstream PR: https://github.com/tgstation/tgstation/pull/41108
Might need a PR to remove the hippie folders temporarily, as they would just hinder the merging of th upstream PR once it's been approved by tg.

### CODE REVIEW

**Comment by k-k-karma** [comment]
literally nobody on hippie does circuitry but kiefer and i'm pretty sure he's given up with it since you nerfed atmos circuits

**Comment by BlueNothing** [comment]
I do it.

**Comment by ghost** [comment]
i just steal circuits from nerds and use them

**Comment by Carbonhell** [comment]
>noone does circuit
do you even play smh

**Comment by ghost** [comment]
@k-k-karma literally every night I come into xenobiology it's filled to the brim with various contraptions. You're definitely wrong there.

**Comment by k-k-karma** [comment]
if that's not kiefer then it's probably some random guy copying and pasting circuits

**Comment by Shdorsh** [comment]
@k-k-karma if you don't like circuits, that's your business.

**Comment by BlueNothing** [comment]
To be fair, the circuits people copy are sometimes their own.

**Comment by ATH1909** [comment]
I support keeping circuits- they're fun to design.

Plus, it'll draw some of the /tg/station circuit people to Hippie, which'd be pretty nice.

**Comment by CMOisLing** [comment]
circuits belong to the nords

**Comment by WarRage333** [comment]
I'm legit afraid to use circuits i have, last time i dropped the shitty shard thrower and some cunt moth copied it and it spread like wildfire.  I have some things thats terrifying would they be used by a bigger number of people

**Comment by BlueNothing** [comment]
[Desire to know more intensifies]

**Comment by ghost** [comment]
@WarRage333 are you the guy who made the room defender circuit? If so, yeah that shit's fucked

**Comment by Shdorsh** [comment]
You want me to PR a scannability switch inside an assembly, that can be toggled with someone's ID card in the future?

**Comment by Hate9** [comment]
I was actually working on something like that a while back. Sounds good to me, as long as it takes a little bit, so people don't just do it to everything they make immediately.

**Comment by Shdorsh** [comment]
It got accepted on tg, anyone seen the upstream PR pop up here?

**Review by yoyobatty — APPROVED** [review]

**Comment by Shdorsh** [comment]
Wow, thanks man!

**Pull request merged**
