### PR TITLE
Puts the bee shit in a crate in the back of botany

### PR DESCRIPTION
**Pull request by ghost**
[Guidelines]: 
image

## Changelog
:cl: zamolxius
tweak: made bee kit start packed in the botanist's backroom place; Also it's half as many stuff. Same contents as cargo bee crate
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
image
image

**Comment by QuarianCommando** [comment]
I like this PR better than steamports. +1 once bees are fixed.

**Comment by ghost** [comment]
This is the exact same PR as steamports. Also, bees are still broken so -1

**Comment by ghost** [comment]
oh shit didnt see his PR

**Comment by ghost** [comment]
why did u close this

**Pull request closed without merging**
