### PR TITLE
Adds discord emojis

### PR DESCRIPTION
**Pull request by Carbonhell**
:cl:
add: Adds discord emojis ingame. Their names are the same of the discord ones.
/:cl:

[why]: We NEED it.

### CODE REVIEW

**Comment by Carbonhell** [comment]
Also removes goonbee because it was against the license to use it.

**Comment by ghost** [comment]
+1

**Comment by earthmoonjune** [comment]
yes +1

**Review by yoyobatty — APPROVED** [review]
Good to go?

**Comment by Carbonhell** [comment]
Yes

**Pull request merged**
