### PR TITLE
Phoneposted 294 chemical name changes

### PR DESCRIPTION
**Pull request by Toxici11i**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
tweak: now renames bottles to their contents lmao, also adds more warning
/:cl:

## About The Pull Request
adds the chemical name to the epic 294 machine

## Why It's Good For The Game
more clarity on whats in a mysterious bottle
also adds more warning if somebody decides to dispense 30u of n-amino and run about w/ it

### CODE REVIEW

**Comment by Toxici11i** [comment]
Theoretically this will name all bottles (CHEM NAME) Bottle, wont throw errors even if its an incorrect name as it wont even allow it to work

**Comment by danhibiki** [comment]
This is bad. So it renames bottles if you add new contents to it? You wanna make floorpills safe too?

**Comment by Toxici11i** [comment]
> This is bad. So it renames bottles if you add new contents to it? You wanna make floorpills safe too?

no retard

**Comment by Toxici11i** [comment]
> This is bad. So it renames bottles if you add new contents to it? You wanna make floorpills safe too?

it makes it so that 294 dispensed bottles come with the original chemical name they contained

**Comment by Toxici11i** [comment]
image

**Comment by Toxici11i** [comment]
Travis map checking is ded due to connection issues, works fine

**Comment by Manly-Dwarf** [comment]
i mean
ain't nobody gonna use chemical bottles compared to pills or anything else
it's still anonymous in a drinking glass
i don't see why not

**Comment by Manly-Dwarf** [comment]
oh, this is just for the SCP. I missed that

**Review by ghost — APPROVED** [review]

**Pull request merged**
