### PR TITLE
YOU CAN NO LONGER MAKE THE LAG RIFLE

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by WarRage333** [comment]
TG nerfed it into the ground along x-ray nothing really lost

**Comment by ExpAntique** [comment]
+1 holy shit

**Comment by ghost** [comment]
Does the rifle only lag when you put it in a turret?

**Comment by Majick1** [comment]
+1

**Review by yoyobatty — APPROVED** [review]

**Pull request merged**
