### PR TITLE
[MIRROR] Fixes FIND_REF_NO_CHECK_TICK not actually disabling world.loop_checks

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/34217
--------------------

### CODE REVIEW

**Comment by Pyko1** [comment]
+	visibility = 1 //HIPPIE SHIT WHY?

Why?

**Comment by praisenarsie** [comment]
apparently tony put it there because it puts us on the hub???

@Cyberboss is this shit needed lol?

**Comment by Cyberboss** [comment]
See https://github.com/tgstation/tgstation/pull/29446

**Comment by Cyberboss** [comment]
All in all I believe the correct move is to remove the line and use the config

**Comment by Pyko1** [comment]
so prolly assign to @Chnkr

**Review by ghost — APPROVED** [review]

**Pull request merged**
