### PR TITLE
Better(?) Vampire blood draining

### PR DESCRIPTION
**Pull request by NautilusViper**
## Changelog
:cl: NautilusViper
balance: Vampire sipping has halved in drain effectiveness, but slightly more than doubled in speed.
soundadd: Vampire sipping is slightly quieter, but now has a unique sound not heard elsewhere, making it a dead giveaway.
/:cl:

## About The Pull Request

The sipp buff is largely a QoL change, but it's a buff as well. Draining a lethal amount of blood now takes roughly 40 seconds instead of 45.
## Why It's Good For The Game

Someone complained about vampire sipping taking too long in a previous PR and I feel that jam. The worst part about changelings was having to stand around for seven years waiting to absorb people, nobody likes sitting around waiting for progress bars to load. Turns out the problem is largely in your head. It doesn't really matter how long it takes so long as the progress bars move along nicely, isn't the placebo effect fun?

Also the eating sound was dumb. Blood usually isn't crunchy munchy. Now the sipp sounds like a sipp. Very much worth mentioning is the fact that this makes blood draining give you away without any ambiguity like with the generic eating noise. This PR isn't entirely a buff.

### CODE REVIEW

**Comment by ExpAntique** [comment]
+1 imo vampires should take like 20 seconds to succ. They already have you restrained and in their little ERP corner, so why don't we just stop wasting everyone's time and get right to the point.

**Comment by Manly-Dwarf** [comment]
If changelings can absorb a corpse in 15 seconds, why do Vampires need to stand still doin fuckin nothing for a full minute?
Speed it up even more, I say. You can kill someone in that time, but at least killing someone is more fun.

**Comment by yoyobatty** [comment]
The "about this or" tells you what was changed in detail. Your changelog should give a very brief and major detail of what you've changed. In other words what you've wrote in your CL should be in the about this or header.

**Comment by waterwater1212** [comment]
make vamp succ faster.............

**Comment by Majick1** [comment]
Yeah, fix the changelog, and 30 seconds or less should be good for succ time

**Comment by Maroonenahmoron** [comment]
+1 no more munchy vampires again

**Review by yoyobatty — COMMENTED** [review]
Lmao sip sounds like a Capri sun

**Comment by mikolaj007** [comment]
+1 for S I P P

**Comment by ExpAntique** [comment]
> If changelings can absorb a corpse in 15 seconds, why do Vampires need to stand still doin fuckin nothing for a full minute?
> Speed it up even more, I say. You can kill someone in that time, but at least killing someone is more fun.

honestly this, it shouldn't be slower to succ someone than if I were to just beat them to death with my bare hands.

**Comment by NautilusViper** [comment]
> +1 imo vampires should take like 20 seconds to succ. They already have you restrained and in their little ERP corner, so why don't we just stop wasting everyone's time and get right to the point.



> If changelings can absorb a corpse in 15 seconds, why do Vampires need to stand still doin fuckin nothing for a full minute?
> Speed it up even more, I say. You can kill someone in that time, but at least killing someone is more fun.



> Yeah, fix the changelog, and 30 seconds or less should be good for succ time



> > If changelings can absorb a corpse in 15 seconds, why do Vampires need to stand still doin fuckin nothing for a full minute?
> > Speed it up even more, I say. You can kill someone in that time, but at least killing someone is more fun.
> 
> honestly this, it shouldn't be slower to succ someone than if I were to just beat them to death with my bare hands.

you may have heard of this fun little thing called saline-glucose solution

**Comment by Manly-Dwarf** [comment]
why isn't this merged yet

**Comment by Manly-Dwarf** [comment]
also why isn't this sped up even more yet

**Comment by NautilusViper** [comment]
> why isn't this merged yet

dunno but it should be

**Comment by NautilusViper** [comment]
> also why isn't this sped up even more yet

read: saline-glucose

**Review by ghost — APPROVED** [review]

**Pull request merged**
