### PR TITLE
[MIRROR] Revert "Automatic unbuckle by player moving"

### PR DESCRIPTION
**Pull request by ghost**
Original PR: https://github.com/tgstation/tgstation/pull/30281
--------------------
Reverts tgstation/tgstation#30239

I MEAN
COME FUCKING ON

THAT PR THAT JUST TOLD YOU WHAT TO DO WAS BETTER... ALMOST EVERYONE HATED THE AUTO UNBUCKLE PR

### CODE REVIEW

**Review by ghost — APPROVED** [review]
hugbox/10

**Comment by j-mie** [comment]
build this

**Comment by j-mie** [comment]
build this

**Comment by j-mie** [comment]
build this

**Pull request merged**
