### PR TITLE
Stock parts can now be printed by any protolathe

### PR DESCRIPTION
**Pull request by xTrainx**
:cl: xTrainx
balance: stock parts can be made by any department fabricator/protolathe
/:cl:

[why]:  This way, our none excistance engineering and science staff who have to upgrade every department by going to each one and asking everyone to open the door can fuck off to do better things, still, only science and engineering can make rpeds, so you would still appriciate them comming around

### CODE REVIEW

**Comment by yoyobatty** [comment]
This isn't a tweak, this a balance, you're not going to fool anyone so you could bypass headmin input there laddy.

**Comment by xTrainx** [comment]
> 
> 
> This isn't a tweak, this a balance, you're not going to fool anyone so you could bypass headmin input there laddy.

i though tweak was when you change something a bit

**Comment by yoyobatty** [comment]
Well, you've gone and tweaked variables, but in turn this results in a relatively major gameplay change, this would need headmin input.

**Review by yoyobatty — APPROVED** [review]
Code looks good, just get it approved.

**Comment by Eagle-Eyess** [comment]
Sure +1

**Comment by yskefunky** [comment]
I see no issue with this +1

**Comment by xTrainx** [comment]
toof also reacted with a yee, so can this be merged?

**Comment by yoyobatty** [comment]
Sure

**Pull request merged**
