### PR TITLE
Adds small chance of doom door sound effect to play when opening/closing an airlock

### PR DESCRIPTION
**Pull request by JohnGinnane**
There's a 2% chance for this trigger when you open a door. If the open sound is played, then the close sound will also play before deactivating the override

Video (at 50% chance just for video purposes):
https://streamable.com/jyb87

I've also renamed the folder to match the original structure exactly

:cl: John
soundadd: Added a small chance for an alternative airlock sound to play when opening/closing an airlock
/:cl:

[why]: fun :¬)

### CODE REVIEW

**Comment by ghost** [comment]
A secret is revealed!

**Comment by Pyko1** [comment]
sure why not +1

**Comment by ghost** [comment]
fuck yes +1

**Comment by GuyonBroadway** [comment]
TBH just replace all of the door sounds with doom doors, its good shit.

**Review by GuyonBroadway — APPROVED** [review]

**Pull request merged**
