### PR TITLE
[WIP] Upstream merge 

### PR DESCRIPTION
**Pull request by GuyonBroadway**
Jesus ducks....

This is gonna need some actualy checking over by other people cus theres balance changes and shit plus I like gits diffchecker cus it makes it easier to find shit I need to fix, replace and update.

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Oh fuck imma have to recompile tgui too

GAAAAAAAAAHHH

**Comment by Shdorsh** [comment]
WTF? Can you plz give us a proper explanation on what this update does?

**Comment by GuyonBroadway** [comment]
Ok so it compiles, doesn;t mean its any good but it fucking compiles.

image

**Comment by danhibiki** [comment]
@shdorsh it’s an upstream merge of several hundred commits, it’s a whale just to list out the changes itself. I agree some clarification is necessary but given the nature of the PR it’s hard

**Comment by Manly-Dwarf** [comment]
The irony in this is that Guyon is british, yet he's more of a slave than any of the other coders.

**Comment by ghost** [comment]
:OMEGALUL:

**Comment by yoyobatty** [comment]
Changelogs will all show up later

**Comment by Jujumatic** [comment]
`The command "tools/travis/build_dependencies.sh || travis_terminate 1" exited with 0.
0.00s$ tools/travis/build_byond.sh
/home/travis/.travis/job_stages: line 104: tools/travis/build_byond.sh: Permission denied`

FUCK
@GuyonBroadway

**Comment by Jujumatic** [comment]
on the bright side that's the only thing stopping travis from giving the go ahead

**Comment by GuyonBroadway** [comment]
tgui updated and it looks like it works (none of our machines have missing interfaces) I think this is ready to go.

**Comment by GuyonBroadway** [comment]
Ok there, its done we got all the latest crap...

**Comment by yoyobatty** [comment]
Sorry guyon I broke it I might fix it later

**Comment by bubberducky2** [comment]
Epic

**Comment by Lxtoofonea** [comment]
Sure seems kek enough

**Comment by yoyobatty** [comment]
Closing this.

**Pull request closed without merging**
