### PR TITLE
Adds more burp noises

### PR DESCRIPTION
**Pull request by JohnGinnane**
*burp

[Changelogs]: # Renamed original burp.ogg to burp1.ogg and added a pick() for all 6 sounds

:cl: JohnGinnane
soundadd: Added five new burp sounds!
add: 5 units of burpinate has been added to all cans of soda
/:cl:

[why]: # More sounds make the game more fun

### CODE REVIEW

**Comment by ghost** [comment]
holy fuck are these grotesque

**Comment by JohnGinnane** [comment]
Exactly

**Comment by Blute1** [comment]
holy fuck i laughed out loud at the fifth one

**Review by ghost — DISMISSED** [review]
This is fine, I'd however prefer if we'd move burp sounds to species or mobs

**Comment by JohnGinnane** [comment]
@HippieStation/head thoughts?

**Comment by ghost** [comment]
It's a bit too realistic and gross for spess

also i can't stop thinking about that one thing and it's making me do the big think on it

**Comment by bardofrage** [comment]
Some of these are actually disgusting

**Comment by ghost** [comment]
add this immediately


it is of utmost importance to the future of hippiestation for this to be added

**Comment by JohnGinnane** [comment]
@McBawbaggings I beg for mercy and that you reconsider this))

Also.. I might add burpium to fizzy drinks (from vending machines) for *realism*

**Comment by ghost** [comment]
do it.  Also make people burp when a chemical in their blood runs out.

**Comment by praisenarsie** [comment]
john i dislike how you are slapping the headmin approval label for literally every minor pr ever.

e: y'know what im just tired.

**Comment by GuyonBroadway** [comment]
All non-bugfix PR's need the headmin +3

**Comment by KayeArray** [comment]
hilarious +1

**Comment by ghost** [comment]
holy fuck the fifth and sixth one are too powerful

**Comment by JohnGinnane** [comment]
@zamolxius would be kinda funny but not sure if it's ~totally~ accurate. Having it in sodas should mean more burps at least

**Comment by JohnGinnane** [comment]
@HippieStation/head what do you think of this?

**Comment by ghost** [comment]
i mean honestly why not
and the burpium is fine
+1

**Comment by xTrainx** [comment]
2 weeks

**Comment by ghost** [comment]
@JohnGinnane Please add the `burp` sound to either the `mob` or the `species` and i'll merge this

**Comment by JohnGinnane** [comment]
alrighty

**Comment by JohnGinnane** [comment]
Added a new var to `living` called `burp_sounds` (decided to use `living` because they're the mob that's allowed to burp)

**Review by ghost — APPROVED** [review]

**Pull request merged**
