### PR TITLE
Forge "Shotgun" Caliber Addition

### PR DESCRIPTION
**Pull request by Toxici11i**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Adds the "shotgun" caliber to forged bullets - allowing you to produce custom forged shells!
/:cl:

## About The Pull Request
This allows people to make omegalul spacelube shotgun shells for the wardens shotgun - also 1 brute zombie powder shells for subduing CRIMINALS

## Why It's Good For The Game
General good change to forge, allows for more supported weaponry.

soon ill probably add custom rods for the crossbow :spoi:

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
you talk about spacelube shotties  like you won't make radium buckshot to instantly dab on thanos
+1

**Comment by Manly-Dwarf** [comment]
this is an actually good PR and a welcome chemist buff compared to the other one

**Comment by Manly-Dwarf** [comment]
actually wait a second don't we already have shotgun darts?

**Comment by Toxici11i** [comment]
> actually wait a second don't we already have shotgun darts?

you infidel, these dont apply reagents

**Comment by Toxici11i** [comment]
> > actually wait a second don't we already have shotgun darts?
> 
> you infidel, these dont apply reagents

well thats kindve wrong, they do, but its nowhere near enough for stuff like zombiepowder to knock you out. Reagent darts do 0 brute and apply 60u of reagents if armor pend

**Comment by diegoxt45** [comment]
man, what the fuck.

**Comment by yoyobatty** [comment]
Is this tested?

**Comment by Toxici11i** [comment]
yes

**Review by yoyobatty — APPROVED** [review]

**Comment by yoyobatty** [comment]
Needs more approval

**Comment by mkikt4743** [comment]
do crossbow bolts NOW toxic +1

**Comment by Toxici11i** [comment]
> do crossbow bolts NOW toxic +1

I would but it would be such a fucking PAIN like im not joking

**Comment by AnthonyJNgo** [comment]
Yeah, this is pretty based.

edit: obviously a +1 but I should elaborate. It's a good buff to the forge and I can see it being used in a lot of different gamemodes, specifically Thanos rounds. Good. Thanos is extremely OP in my opinion and this seems like a good balancing act.

**Pull request merged**
