### PR TITLE
Enables Drunk Trait

### PR DESCRIPTION
**Pull request by AliiTea**
:cl: Nexendia
add: Alcohol Tolerance Trait
/:cl:

We are all alcoholics, don't lie.

### CODE REVIEW

**Comment by Carbonhell** [comment]
Describe what the quirks do for headmins please.

**Comment by mikolaj007** [comment]
-1 for depression, its a mood thing

**Comment by mikolaj007** [comment]
Alcohol tolerance is a +1, its effects are minor:
decreases damage to liver by 30%
faster recovery(not stun time) from beepsky smash
Removes some minor negative effects like jitteriness
manly dorf heals you 2 brute and burn per tick

**Comment by Manly-Dwarf** [comment]
Rename "quirk" to "trait" and we're good here.
Death to "quirk"
EDIT:
The only reason I'm in support of this is because these traits have zero impact on gameplay at all. They're the most worthless "traits" you could have, and traits already see zero use.

**Pull request closed without merging**
