### PR TITLE
Woohoo Vending TGUI!

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: Vending tgui-next!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Real chads test their code, will merge when you're done.

**Comment by ghost** [comment]
@steamp0rt ping me when you finish if you want me to do the testing for you

**Comment by yoyobatty** [comment]
Travis says :`hippiestation/code/modules/vending/_vending.dm:227:warning: N: variable defined but not used`

**Comment by ghost** [comment]
Ok, travis passes now. Fixed a performance issue. Ready now.

**Review by yoyobatty — APPROVED** [review]
IF THIS BREAKS ANYTHING, UR DED STEAMPORN!

**Pull request merged**
