### PR TITLE
Shotguns fire double pellets but deal half damage 

### PR DESCRIPTION
**Pull request by yoyobatty**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
balance: Buck and rubber shot now have half damage but twice as many are created
/:cl:

[why]: This gives shotguns more potential to work like an actual shotgun which tends to hit a bunch of crap from far away. Mid-close range has about the same effectiveness but long range shots will be less effective.

### CODE REVIEW

**Comment by k-k-karma** [comment]
too much of a nerf boo

**Comment by bardofrage** [comment]
Doesn't seem like too much a nerf, just makes it function more like a shotgun. +1 for now

**Comment by earthmoonjune** [comment]
+1

**Comment by Manly-Dwarf** [comment]
A needed change, though you should still implement my "buckshot rips off limbs/deals extra damage if you direct click on a standing person" idea!
Could we get a video of it in action? Also does this make rubber shot better or worse when spamming down the halls?

**Comment by RafRoq** [comment]
this is a nerf, halls have width 3, shotguns now spread 3 bullets it will spread 6 and all will hit walls in the end doing less damage

**Comment by DaydreamPuppeh** [comment]
Badush, this is meant to turn shotguns into more close range weapons. You will do more damage than now by firing very close to your target

**Comment by RafRoq** [comment]
@DaydreamPuppeh the purpose of using shotguns now is because other weapons are hard to hit the target due to how projectiles are slow compared to people at range, we need https://github.com/HippieStation/HippieStation/pull/10179 to be merged

**Comment by RafRoq** [comment]
@DaydreamPuppeh  one thing you dont want is getting close to a lethal target

**Comment by JohnMcLaime** [comment]
Shotgun blasts (when pellets hit stuff) already lag the game for some people (i am one of them), it started happening after moving to this "new" shitty chat system iirc.

**Comment by Carbonhell** [comment]
This pr has enough +1s

**Comment by yoyobatty** [comment]
It's good to go

**Comment by Carbonhell** [comment]
Since more pellets are made shouldn't you also raise the variance a bit? Not sure

**Comment by yoyobatty** [comment]
It's taken into account, same exact spread but just imagine an extra pellet inbetween each one, that's more or less what I noticed when testing.

**Review by Carbonhell — APPROVED** [review]

**Review by Carbonhell — APPROVED** [review]

**Pull request merged**
